### ISSUE TITLE
centos 7 bash: v2ray: command not found

### ISSUE THREAD

**Issue by yifenglv46** [233boy/v2ray#1]
bash: v2ray: command not found 怎么破

**Comment by 233boy** [comment]
@yifenglv46 
输入下面的代码应该即可解决，理论上 CentOS 7 没有这个问题的呀，至少我测试过的是没有的 😂 
```
ln -sf /usr/local/bin/v2ray /usr/bin/v2ray
```

**Comment by yifenglv46** [comment]
好的 谢谢大佬 我 重装 debian 后 正常了 
之前 是 gcp 的 centos7

**Comment by 233boy** [comment]
@yifenglv46 
我使用 GCP 的 CentOS 7 测试过，没有这个问题呢  😂

**Comment by yifenglv46** [comment]
奇怪了 难道 是 之前 装了 ss？

**Comment by yifenglv46** [comment]
你这个脚本 确实 是 目前 “最好用”的 V2Ray 顶一个

**Comment by 233boy** [comment]
@yifenglv46 
不太清楚是否是因为你之前安装了 SS 的原因，但是我测试过是没有问题的，或者你可以使用 GCP 新建一台小鸡，系统 选择 CentOS 7，然后来安装一下，我这边是不会出现 这个问题的 :joy

**Comment by hackeye** [comment]
这个问题是因为安装锐速，需要换核，换核后会出现这个问题

**Comment by chan1965** [comment]
您好！我也遇到这个问题。
GCP CentOS 7,
SSH 登入后，用sudo su转换root身份，然后用您脚本安装， 过程顺利，并且V2ray及SS server正常运行，但叫不出v2ray重新修改参数。
[root@instance-1 /]# v2ray
bash: v2ray: command not found

请问如何解决？
谢谢！

**Comment by RoyeeW** [comment]
可以在~/.bash_profile 中的PATH后增加
:/usr/local/sbin
保存退出，source .bash_profile 
以后每次登陆，就不需要敲全路径了。/usr/local/sbin/v2ray

**Comment by imaginebreake** [comment]
> 可以在~/.bash_profile 中的PATH后增加
> :/usr/local/sbin
> 保存退出，source .bash_profile
> 以后每次登陆，就不需要敲全路径了。/usr/local/sbin/v2ray

alias v2ray='/usr/local/sbin/v2ray'
也可以直接加入这一行

**Comment by Emmricjordans** [comment]
Some one help me with the bash v2ray command

**Comment by makerich** [comment]
输入/usr/local/bin/v2ray
显示 -bash: /usr/local/bin/v2ray: No such file or directory

**Comment by shijiezhou1** [comment]
> 

成功了谢谢你老板

**Comment by shijiezhou1** [comment]
> 可以在~/.bash_profile 中的PATH后增加 :/usr/local/sbin 保存退出，source .bash_profile 以后每次登陆，就不需要敲全路径了。/usr/local/sbin/v2ray

谢谢 成功了
