### ISSUE TITLE
V2rayNG安卓客户端问题

### ISSUE THREAD

**Issue by hhhbilibili** [233boy/v2ray#10]
服务端选择了tcp ＋HTTP伪装，Android客户端是v2rayNG，配置了tcp，HTTP伪装填写了域名，并没有进行伪装，BifrostV客户端就可以，为什么？

**Comment by 233boy** [comment]
@hhhbilibili 
脚本并没有 tcp ＋HTTP 伪装 这种功能提供，不是很清楚你的问题。
