### ISSUE TITLE
Caddyfile中的这个without是否应该换成except

### ISSUE THREAD

**Issue by crazypeace** [233boy/v2ray#100]
```
$domain {
    tls ${email}@gmail.com
    gzip
	timeouts none
    proxy / $proxy_site {
        without /${path}               // 大佬，这个without是否应该换成except? 
    }
    proxy /${path} 127.0.0.1:${v2ray_port} {
        without /${path}
        websocket
    }
}
```

 大佬，这个without是否应该换成except? 
我看了一下caddy的文档 
**without** is a URL prefix to trim before proxying the request upstream. A request to /api/foo without /api, for example, will result in a proxy request to /foo.
**except** is a space-separated list of paths to exclude from proxying. Requests that match any of ignored_paths will be passed thru.

**Comment by 233boy** [comment]
620ec46
