### ISSUE TITLE
HTTP/2或WS+TLS无法连接，TCP可以

### ISSUE THREAD

**Issue by janeroseloving** [233boy/v2ray#1000]
配置了tls就无法连接，域名没得问题，正确解析IP

**Comment by Christhas** [comment]
扫下443端口看看，可能是443被封了

**Comment by sunzongzheng** [comment]
我这边日志有报`error: remote error: tls: internal error`，看看你那边是不是一样，暂未解决

**Comment by crazypeace** [comment]
搭WS+TLS的过程中，不要开CDN.
然后自己查一下有没有获得证书成功。

第一次搭梯子 排错指引 (https://zelikk.blogspot.com/2022/04/setup-v2ray-websocket-tls-troubleshoot.html) (从来没成功过, 这是第一次搭)

**Comment by janeroseloving** [comment]
> 我这边日志有报`error: remote error: tls: internal error`，看看你那边是不是一样，暂未解决

https://tcp.ping.pe/ 
443端口没封，我访问自己的服务器的网站OK的，就是开了HTTP/2或tls上不了外网

**Comment by janeroseloving** [comment]
> 

怕是解决不了了，用ss凑合用速度还快点，就是担心被封，之前ip流量走大了(10G+)就封了1周，来回折腾了几次然后彻底封了
