### ISSUE TITLE
两周内搬瓦工IP被封了两次！到底是什么原因？

### ISSUE THREAD

**Issue by versacehy** [233boy/v2ray#1001]
一周前发现搬瓦工的IP被封，之后花钱买了一个新IP，用了没几天又被封了。用的是旧版本V2RAY脚本（bash <(curl -sL https://git.io/v2ray.sh) online old）。之前的老IP用了一年都没事，怎么最近被连封两个...
平时就只看youtube，上pinterest，最近浏览了stable diffusion 等一系列AI画图网站，请问是什么原因，最近严查吗？
恳求大佬们指点迷津！

**Comment by natsu-ten** [comment]
巧了 这一段时间老是坏. 昨天用新脚本重新部署了一遍,今天ip就被封了

**Comment by versacehy** [comment]
> 巧了 这一段时间老是坏. 昨天用新脚本重新部署了一遍,今天ip就被封了

跟我一模一样，重新部署脚本后第二天IP就封了...

**Comment by natsu-ten** [comment]
> > 巧了 这一段时间老是坏. 昨天用新脚本重新部署了一遍,今天ip就被封了
> 
> 跟我一模一样，重新部署脚本后第二天IP就封了...

搬瓦工换ip 8刀? 如果只是科学上网 划不来自己搭了 成本太高了

**Comment by versacehy** [comment]
> 


> 

感觉找一个可以换IP的要实惠点

**Comment by kililixi** [comment]
> > > 巧了 这一段时间老是坏. 昨天用新脚本重新部署了一遍,今天ip就被封了
> > 
> > 
> > 跟我一模一样，重新部署脚本后第二天IP就封了...
> 
> 搬瓦工换ip 8刀? 如果只是科学上网 划不来自己搭了 成本太高了

是啊，还是买现成的吧。自从端口被封，套cdn速度慢的要死，到期还是不续了。

**Comment by natsu-ten** [comment]
> > > > 巧了 这一段时间老是坏. 昨天用新脚本重新部署了一遍,今天ip就被封了
> > > 
> > > 
> > > 跟我一模一样，重新部署脚本后第二天IP就封了...
> > 
> > 
> > 搬瓦工换ip 8刀? 如果只是科学上网 划不来自己搭了 成本太高了
> 
> 是啊，还是买现成的吧。自从端口被封，套cdn速度慢的要死，到期还是不续了。

我这边套cloudflare 的cdn速度还行, 下载速度能到5-8M左右, 看视频也不卡, 就是时不时会抽风

**Comment by sealionking** [comment]
我已经不想用搬瓦工了，换IP太贵了。一次70rmb，只能用两天，我还不如租别人的vpn了。

**Comment by kililixi** [comment]
> 我已经不想用搬瓦工了，换IP太贵了。一次70rmb，只能用两天，我还不如租别人的vpn了。

同是搬瓦工的jms还行，几个人一起的话，除非是祖传的好套餐，不然感觉是比自建好点的。不过还有一点就是被openai屏蔽了。。。
