### ISSUE TITLE
添加反代之后，caddy状态：未在运行

### ISSUE THREAD

**Issue by qinlgumt** [233boy/v2ray#1004]
caddy.service - Caddy
     Loaded: loaded (/lib/systemd/system/caddy.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2022-11-18 15:50:16 CST; 20min ago
       Docs: https://caddyserver.com/docs/
    Process: 5564 ExecStart=/usr/local/bin/caddy run --environ --config /etc/caddy/Caddyfile (code=exited, status=1/FAILURE)
   Main PID: 5564 (code=exited, status=1/FAILURE)
     Status: "loading new config: http app module: start: listening on :80: listen tcp :80: bind: address already in use"

Nov 18 15:50:16 fine-delight-1.localdomain caddy[5564]: {"level":"info","ts":1668757816.2982917,"logger":"http","msg":"enabling automatic HTTP->H>
Nov 18 15:50:16 fine-delight-1.localdomain caddy[5564]: {"level":"info","ts":1668757816.2989955,"logger":"http","msg":"enabling HTTP/3 listener",>
Nov 18 15:50:16 fine-delight-1.localdomain caddy[5564]: {"level":"info","ts":1668757816.299204,"msg":"failed to sufficiently increase receive buf>
Nov 18 15:50:16 fine-delight-1.localdomain caddy[5564]: {"level":"info","ts":1668757816.2993236,"logger":"http.log","msg":"server running","name">
Nov 18 15:50:16 fine-delight-1.localdomain caddy[5564]: {"level":"info","ts":1668757816.299697,"logger":"tls.cache.maintenance","msg":"started ba>
Nov 18 15:50:16 fine-delight-1.localdomain caddy[5564]: {"level":"info","ts":1668757816.2997167,"logger":"tls.cache.maintenance","msg":"stopped b>
Nov 18 15:50:16 fine-delight-1.localdomain caddy[5564]: Error: loading initial config: loading new config: http app module: start: listening on :>
Nov 18 15:50:16 fine-delight-1.localdomain systemd[1]: caddy.service: Main process exited, code=exited, status=1/FAILURE
Nov 18 15:50:16 fine-delight-1.localdomain systemd[1]: caddy.service: Failed with result 'exit-code'.
Nov 18 15:50:16 fine-delight-1.localdomain systemd[1]: Failed to start Caddy.

这啥情况，大佬们，help！！

**Comment by qinlgumt** [comment]
还是不行，相关资料太少了，找不到能用的..

**Comment by qinlgumt** [comment]
来个大佬看看呀

**Comment by qinlgumt** [comment]
好像是Nginx影响caddy开启失败，我把Nginx卸掉就好了，目前不知道原因，希望有大佬来解答一下（我还想用Nginx...）

**Comment by crazypeace** [comment]
你能凭自己的能力找到这个原因已经很厉害了。
你要知道nginx和Caddy都是开网站的, 他们都要监听同样的端口, 所以他们之间会互相冲突。
你想用nginx可以去找用nginx搭前置的教程或脚本。

**Comment by qinlgumt** [comment]
> 你能凭自己的能力找到这个原因已经很厉害了。 你要知道nginx和Caddy都是开网站的, 他们都要监听同样的端口, 所以他们之间会互相冲突。 你想用nginx可以去找用nginx搭前置的教程或脚本。

是的，我后面也找到原因了，他们都监听80端口
