### ISSUE TITLE
背报，3天就封了IP

### ISSUE THREAD

**Issue by WebofLaw** [233boy/v2ray#1005]
vultr，只使用了TCP协议

**Comment by XijiaDaddy** [comment]
我的刚打开就没了

**Comment by xieruiyin** [comment]
请问有什么好方法翻墙吗

**Comment by Bandnwp** [comment]
麻烦提点有价值问题


发自 iPhone 版 Yahoo 邮箱


星期日, 十一月 20, 2022, 10:59 于 xieruiyin ***@***.***>写道：




请问有什么好方法翻墙吗

**Comment by x3xx1818** [comment]
用KCP加DTLS已经稳定4个月了

**Comment by edcyoo** [comment]
我也被封了 还好提供商给免费换了ip

**Comment by qiyang77** [comment]
不灵了，我感觉v2ray要落幕了，去试试新技术吧比如naiveproxy

**Comment by yeyuchen198** [comment]
> 不灵了，我感觉v2ray要落幕了，去试试新技术吧比如naiveproxy

不至于吧，v2ray要落幕了？heroku在28号停止免费服务倒是真的
