### ISSUE TITLE
脚本有问题，安装过程中有报错信息，服务无法启动

### ISSUE THREAD

**Issue by merry1314** [233boy/v2ray#1006]
`  inflating: /usr/bin/v2ray/geoip-only-cn-private.dat  
chmod: cannot access ‘/usr/bin/v2ray/v2ctl’: No such file or directory
Created symlink from /etc/systemd/system/multi-user.target.wants/v2ray.service to /usr/lib/systemd/system/v2ray.service.

v2ray status
flag provided but not defined: -version
Usage of /usr/bin/v2ray/v2ray:

 V2Ray 状态: 未在运行

v2ray start
flag provided but not defined: -version
Usage of /usr/bin/v2ray/v2ray:

 V2Ray 已启动
`

**Comment by 233boy** [comment]
@merry1314 
你使用什么命令安装的？

**Comment by tocky0** [comment]
遇到同样的问题，命令，

> bash <(curl -s -L https://raw.githubusercontent.com/xyz690/v2ray/master/go.sh)  

输入v2ray后，部分信息如下，

> ........... V2Ray 管理脚本 v3.52 by 233v2 ..........
 V2Ray 版本: v  /  V2Ray 状态: 未在运行
