### ISSUE TITLE
VLESS_WebSocket transport

### ISSUE THREAD

**Issue by Saeed-Pooyanfar** [233boy/v2ray#1007]
Hi  
Thanks for this, i appreciate it 🙏  
Can you provide a new option => "VLESS_WebSocket" that doesn't require a domain to setup ?  
Currently we have only "VLESS_WebSocket_TLS" option which needs a domain
Thanks again for this amazing script 😊

**Comment by 233boy** [comment]
try use `WebSocket`,  this is a VMess_WebSocket transport
