### ISSUE TITLE
配置好V2rayn可以ping通，但是Tcping显示timeout

### ISSUE THREAD

**Issue by wangdianzu** [233boy/v2ray#1008]
配置好V2rayn可以ping通，但是Tcping显示timeout

**Comment by x3xx1818** [comment]
你是TCP协议吗

**Comment by wangdianzu** [comment]
WS+TLS

**Comment by wangdianzu** [comment]
试了下也不行，从10月初之后就没能连上，之前ws+tls用了将近一年

**Comment by crazypeace** [comment]
需要套上CDN了估计

**Comment by x3xx1818** [comment]
是不是被ban了

**Comment by yeyuchen198** [comment]
> 配置好V2rayn可以ping通，但是Tcping显示timeout

我在hax用xui一键搭建的xray节点，vless+ws+tls，有时候也会这样

**Comment by crazypeace** [comment]
就是域名的问题。
如果不是用的hax的免费域名，那么可以自己弄无限多个出来。
google "v2ray caddyv2 无限域名"
https://zelikk.blogspot.com/2022/08/v2ray-caddy-v2-tls-ondemand.html
https://zelikk.blogspot.com/2022/08/v2ray-caddy-v2-cloudflare-wildcards-domain-certificate-15year.html

**Comment by Gattussolee** [comment]
谢谢小白终于找到问题了

**Comment by suncw2020** [comment]
> 谢谢小白终于找到问题了
最后怎么解决的，同问题。

**Comment by crazypeace** [comment]
> > 谢谢小白终于找到问题了
> > 最后怎么解决的，同问题。

tcp 不通很可能 是端口封了
