### ISSUE TITLE
An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by jgy1013** [233boy/v2ray#1009]
小白，按照大佬的教程上google搭建，用VMESS URL直接生成的。平日上班时间在办公室翻都是ok的，关掉电脑后，晚上回家用另一台电脑用同一节点翻时，有时没问题，但有时会翻不了，报错
rejected  v2ray.com/core/proxy/socks: failed to read request > read tcp 127.0.0.1:2333->127.0.0.1:52695: wsarecv: An existing connection was forcibly closed by the remote host.
请问这个是什么问题吗？如何解决？

**Comment by crazypeace** [comment]
你搭的Vmess + TCP 直连? 
看上去像是被运营商 中断连接了。

**Comment by jgy1013** [comment]
应该是，我看传输协议是TCP，整个流程都是按着大佬的傻瓜教程弄的。

**Comment by jgy1013** [comment]
运营商是指谷歌云吗，他为什么要掐断我的连接呢？

**Comment by crazypeace** [comment]
运营商是指你本地的 电信，联通，移动…… 他们是GFW的一部分。
