### ISSUE TITLE
进程总是被kill

### ISSUE THREAD

**Issue by lssb** [233boy/v2ray#101]
是鸡场主在搞怪吗

**Comment by 233boy** [comment]
@lssb 
可能是你的小鸡内存不够 😢

**Comment by lssb** [comment]
128m的🐔       只跑这个， 按理说应该是够的吧

**Comment by 233boy** [comment]
@lssb 
修改 /etc/v2ray/233blog_v2ray_backup.conf ，
将 alterid 更改为 32，之后 v2ray reload，然后继续使用看看。
注意：客户端的 alterid 也更改成 32。
