### ISSUE TITLE
协议404有没有大神帮忙解决下

### ISSUE THREAD

**Issue by chouchou631** [233boy/v2ray#1013]
wget -P /root -N --no-check-certificate "https://raw.githubusercontent.com/mack-a/v2ray-agent/master/install.sh" && chmod 700 /root/install.sh && /root/install.sh

**Comment by alie110** [comment]
not found

**Comment by crazypeace** [comment]
那是因为 作者 删库了。
你换个脚本吧，比如你现在留言的这个repo
或者换这个：
https://github.com/crazypeace/v2ray_wss
