### ISSUE TITLE
如何监听IPv 4?

### ISSUE THREAD

**Issue by monkey-sking** [233boy/v2ray#1014]
netstat -ntlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      1015/systemd-resolv 
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      1026/cupsd          
tcp        0      0 127.0.0.1:4822          0.0.0.0:*               LISTEN      1206/guacd          
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1222/sshd: /usr/sbi 
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      1217/nginx: master  
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      1/init              
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      1217/nginx: master  
tcp        0      0 192.168.122.1:53        0.0.0.0:*               LISTEN      1511/dnsmasq        
tcp6       0      0 ::1:3350                :::*                    LISTEN      1174/xrdp-sesman    
tcp6       0      0 ::1:631                 :::*                    LISTEN      1026/cupsd          
tcp6       0      0 :::8080                 :::*                    LISTEN      1170/java           
tcp6       0      0 :::22                   :::*                    LISTEN      1222/sshd: /usr/sbi 
tcp6       0      0 :::80                   :::*                    LISTEN      1217/nginx: master  
tcp6       0      0 :::111                  :::*                    LISTEN      1/init              
tcp6       0      0 :::99                   :::*                    LISTEN      2883/v2ray          
tcp6       0      0 :::443                  :::*                    LISTEN      1217/nginx: master  
tcp6       0      0 :::3389                 :::*                    LISTEN      1211/xrdp           
tcp6       0      0 :::36467                :::*                    LISTEN      2883/v2ray   

发现只监听了IPv 6,没有监听IPv 4…………
要怎么修改?

**Comment by XG520** [comment]
凉凉了

**Comment by crazypeace** [comment]
一般VPS上面ipv6和ipv4的端口是默认连通的。

你自己用netcat测试一下吧。
https://zelikk.blogspot.com/2022/05/linux-socat-tcp-udp-ipv4-ipv6-localhost.html
https://www.youtube.com/watch?v=bCwAEhZeJlY
