### ISSUE TITLE
请问下kcp流量能调整吗？

### ISSUE THREAD

**Issue by hypnossz86** [233boy/v2ray#1015]
机子是被tcp阻断的，所以只能用其他协议
用了几天发现再kcp协议下，流出流量始终几倍于流入，请问是否可以设置参数是的减少流出流入倍率？
流量用的略快

**Comment by FikaCode** [comment]
https://toutyrater.github.io/advanced/mkcp.html
配置文件  /etc/v2ray/config.json  
kcpSettings 里面添加参数 
kcp 容易被qos和被封，建议 上 cf 的tls + ws ，有信用卡的可以cf 通过回源自选IP
如果真要用kcp，建议再套一个 udp2raw
