### ISSUE TITLE
WebSockey+TLS和VLESS+TLS端口号固定443无法更改

### ISSUE THREAD

**Issue by GrisMouche** [233boy/v2ray#1019]
这两个协议下的端口号有问题，只能是443，设置成别的也没用。包括直接从/etc/v2ray下的两个JSON文件里改也不行，刷新后仍然是443。

**Comment by 233boy** [comment]
@GrisMouche 是的，标准真实的 TLS 就是 443

**Comment by crazypeace** [comment]
> 这两个协议下的端口号有问题，只能是443，设置成别的也没用。包括直接从/etc/v2ray下的两个JSON文件里改也不行，刷新后仍然是443。

来，补一下课。
[VPS上的配置文件与节点参数的对应关系 及 VPS内部数据流向](https://zelikk.blogspot.com/2022/05/v2ray-websocket-tls-caddy-path-data-flow.html)
[连接 V2Ray Websocket + TLS 模式服务器的过程及如何排错 Troubleshoot](https://zelikk.blogspot.com/2022/04/connect-v2ray-websocket-tls-troubleshoot.html)

这两种模式下，这个脚本是用的WEB服务器前置，所以对外暴露的就是标准的443。 所谓的v2ray的端口是内部端口，外面 看不到。
如果你想改对外的 TLS 端口，那么要修改caddy 配置文件。

**Comment by hixingchen** [comment]
> 大佬，ws+tls在香港的轻量服务器搭建，ping是正常的，telnet 443也没问题，但是就是上不了网怎么解决
