### ISSUE TITLE
V2ray配置后电脑正常使用，手机特别慢

### ISSUE THREAD

**Issue by CamelY424** [233boy/v2ray#1021]

**Comment by crazypeace** [comment]
排错教程：
[安装 V2ray Websocket + TLS 模式 排错 Troubleshoot](https://zelikk.blogspot.com/2022/04/setup-v2ray-websocket-tls-troubleshoot.html)

[连接 V2Ray Websocket + TLS 模式服务器的过程及如何排错 Troubleshoot](https://zelikk.blogspot.com/2022/04/connect-v2ray-websocket-tls-troubleshoot.html)
