### ISSUE TITLE
WebSocket+Tls模式报failed to dial WebSocket错误

### ISSUE THREAD

**Issue by oblivionpjk** [233boy/v2ray#1023]
前几周还能正常上网的，最近上不去了，v2ray客户端报failed to dial WebSocket错误。ping 自己的域名可以ping通，telnet 自己的域名 443 无法连通。请问是自己域名的端口号被墙了嘛？大佬该怎么解决呀？

**Comment by crazypeace** [comment]
ping.pe 查一下你的VPS的 443 端口。如果墙外是通的，墙里是断的。那就是端口被墙了。
