### ISSUE TITLE
ws+tls 登不上ins 而其他的Facebook YouTube 都没问题 望大佬指点一下 

### ISSUE THREAD

**Issue by chilll11** [233boy/v2ray#1024]
![image](https://user-images.githubusercontent.com/113433243/206840763-07985940-6090-4102-84da-bbe6b9e6f799.png)

**Comment by crazypeace** [comment]
有可能是IG把你的VPS屏蔽了。
你在VPS上命令行访问IG是什么结果？
`curl -L instagram.com`
有 <html>... </html>的结果出来吗？

**Comment by chilll11** [comment]
感谢大佬回复
输出curl -L instagram.com命令后有结果出来 （太长了 大佬需要看下吗）
我后来又查了下有点疑问 不知道是不是原生ip的问题

**Comment by chilll11** [comment]
2022/12/13 20:18:36 127.0.0.1:8247 accepted //github.githubassets.com:443 [http -> proxy]
2022/12/13 20:18:36 127.0.0.1:8248 accepted //github.githubassets.com:443 [http -> proxy]
2022/12/13 20:18:37 127.0.0.1:8256 accepted //avatars.githubusercontent.com:443 [http -> proxy]
2022/12/13 20:18:38 127.0.0.1:8259 accepted //avatars.githubusercontent.com:443 [http -> proxy]
2022/12/13 20:18:38 127.0.0.1:8258 accepted //avatars.githubusercontent.com:443 [http -> proxy]
2022/12/13 20:18:38 127.0.0.1:8260 accepted //avatars.githubusercontent.com:443 [http -> proxy]
2022/12/13 20:18:42 127.0.0.1:8264 accepted //api.github.com:443 [http -> proxy]
2022/12/13 20:18:43 127.0.0.1:8266 accepted //api.productsearch.app:443 [http -> proxy]
2022/12/13 20:18:43 127.0.0.1:8268 accepted //api.github.com:443 [http -> proxy]
2022/12/13 20:18:43 127.0.0.1:8270 accepted //api.productsearch.app:443 [http -> proxy]
2022/12/13 20:18:50 127.0.0.1:8272 accepted //user-images.githubusercontent.com:443 [http -> proxy]
2022/12/13 20:18:59 127.0.0.1:8274 accepted //api.twitter.com:443 [http -> proxy]
2022/12/13 20:19:21 127.0.0.1:8276 accepted //graph.instagram.com:443 [http -> proxy]
2022/12/13 20:19:25 127.0.0.1:8279 accepted //static.cdninstagram.com:443 [http -> proxy]
2022/12/13 20:19:25 127.0.0.1:8281 accepted //www.instagram.com:443 [http -> proxy]
2022/12/13 20:19:25 127.0.0.1:8283 accepted //scontent-lga3-1.cdninstagram.com:443 [http -> proxy]
2022/12/13 20:19:26 127.0.0.1:8285 accepted //static.cdninstagram.com:443 [http -> proxy]
2022/12/13 20:19:26 127.0.0.1:8286 accepted //static.cdninstagram.com:443 [http -> proxy]
2022/12/13 20:19:26 127.0.0.1:8287 accepted //static.cdninstagram.com:443 [http -> proxy]
2022/12/13 20:19:26 127.0.0.1:8292 accepted //www.instagram.com:443 [http -> proxy]
2022/12/13 20:19:26 127.0.0.1:8291 accepted //www.instagram.com:443 [http -> proxy]
2022/12/13 20:19:26 127.0.0.1:8295 accepted //scontent-lga3-1.cdninstagram.com:443 [http -> proxy]
2022/12/13 20:19:26 127.0.0.1:8297 accepted //www.instagram.com:443 [http -> proxy]
2022/12/13 20:19:26 127.0.0.1:8299 accepted //www.instagram.com:443 [http -> proxy]
2022/12/13 20:19:26 127.0.0.1:8301 accepted //static.cdninstagram.com:443 [http -> proxy]
2022/12/13 20:19:26 127.0.0.1:8302 accepted //static.cdninstagram.com:443 [http -> proxy]
2022/12/13 20:19:26 127.0.0.1:8305 accepted //www.instagram.com:443 [http -> proxy]
2022/12/13 20:19:29 127.0.0.1:8311 accepted //graph.instagram.com:443 [http -> proxy]
2022/12/13 20:19:39 127.0.0.1:14863 accepted http://ipv6.msftconnecttest.com/connecttest.txt [http -> proxy]
2022/12/13 20:20:21 127.0.0.1:14867 accepted //cn.bing.com:443 [http -> direct]

**Comment by chilll11** [comment]
看着好像也没啥问题

**Comment by crazypeace** [comment]
这是你的客户端还是服务端 v2ray的日志？
你需要查服务端的日志。

**Comment by chilll11** [comment]
这样😂 上面是客户端的  
2022/12/13 20:28:08 172.70.214.20:0 accepted tcp:14.22.9.191:33445 [direct]
2022/12/13 20:28:09 172.70.211.173:0 accepted tcp:dns.weixin.qq.com:80 [direct]
2022/12/13 20:28:09 172.70.211.173:0 accepted tcp:szextshort.weixin.qq.com:80 [direct]
2022/12/13 20:28:10 172.70.206.172:0 accepted tcp:sdkconfig.ad.xiaomi.com:443 [direct]
2022/12/13 20:28:20 162.158.166.120:0 accepted tcp:tl.upwork.com:443 [direct]
2022/12/13 20:28:23 172.70.211.173:0 accepted tcp:szminorshort.weixin.qq.com:80 [direct]
2022/12/13 20:29:12 172.70.214.20:0 accepted udp:1.1.1.1:53 [direct]
2022/12/13 20:29:13 172.70.214.20:0 accepted udp:1.1.1.1:53 [direct]
2022/12/13 20:29:13 172.70.214.20:0 accepted tcp:api.ad.xiaomi.com:443 [direct]
2022/12/13 20:29:17 172.70.214.20:0 accepted tcp:ssl.log.wtlogin.qq.com:443 [direct]
2022/12/13 20:29:50 172.70.211.173:0 accepted tcp:170.106.75.13:10001 [direct]
2022/12/13 20:30:50 172.70.211.3:0 accepted tcp:alive.github.com:443 [direct]
2022/12/13 20:30:50 172.71.150.122:0 accepted tcp:graph.instagram.com:443 [direct]
2022/12/13 20:30:50 172.71.150.122:0 accepted tcp:graph.instagram.com:443 [direct]
2022/12/13 20:30:53 108.162.246.97:0 accepted tcp:www.instagram.com:443 [direct]
2022/12/13 20:30:54 172.71.146.164:0 accepted tcp:www.instagram.com:443 [direct]
2022/12/13 20:30:55 172.71.150.122:0 accepted tcp:crx.commerceinspector.com:443 [direct]
2022/12/13 20:30:55 172.70.214.78:0 accepted tcp:static.cdninstagram.com:443 [direct]
2022/12/13 20:31:01 172.69.34.73:0 accepted tcp:twitter.com:443 [direct]
2022/12/13 20:31:03 172.71.146.164:0 accepted tcp:keywordseverywhere.com:443 [direct]
2022/12/13 20:31:32 108.162.246.97:0 accepted tcp:edge.microsoft.com:443 [direct]
2022/12/13 20:31:34 172.71.142.98:0 accepted tcp:static.cdninstagram.com:443 [direct]
2022/12/13 20:31:38 172.69.33.94:0 accepted tcp:170.106.75.13:10001 [direct]
2022/12/13 20:31:48 172.71.146.164:0 accepted tcp:edge.microsoft.com:443 [direct]
2022/12/13 20:32:03 172.71.150.122:0 accepted tcp:graph.instagram.com:443 [direct]
2022/12/13 20:32:08 172.70.211.3:0 accepted tcp:www.bing.com:443 [direct]
2022/12/13 20:32:08 172.69.34.73:0 accepted tcp:prod-streaming-video-msn-com.akamaized.net:443 [direct]
2022/12/13 20:32:11 172.71.142.98:0 accepted tcp:prod-streaming-video-msn-com.akamaized.net:443 [direct]
2022/12/13 20:32:13 108.162.246.97:0 accepted tcp:c.bing.com:443 [direct]
2022/12/13 20:32:13 108.162.246.97:0 accepted tcp:i.instagram.com:443 [direct]
2022/12/13 20:32:16 172.71.146.164:0 accepted tcp:ts3.cn.mm.bing.net:443 [direct]
2022/12/13 20:32:17 172.70.211.3:0 accepted tcp:c.bing.com:443 [direct]
2022/12/13 20:32:18 172.69.34.73:0 accepted tcp:www.instagram.com:443 [direct]
2022/12/13 20:32:21 172.70.207.9:0 accepted tcp:www.facebook.com:443 [direct]
2022/12/13 20:32:21 172.69.34.73:0 accepted tcp:api.msn.com:443 [direct]
2022/12/13 20:32:24 172.70.207.9:0 accepted tcp:assets.msn.com:443 [direct]
2022/12/13 20:32:25 172.70.214.78:0 accepted tcp:ts3.cn.mm.bing.net:443 [direct]
2022/12/13 20:32:26 172.70.207.9:0 accepted tcp:assets.msn.com:443 [direct]
2022/12/13 20:32:27 172.71.150.122:0 accepted tcp:ts3.cn.mm.bing.net:443 [direct]
2022/12/13 20:32:27 172.71.146.164:0 accepted tcp:ts3.cn.mm.bing.net:443 [direct]
2022/12/13 20:32:27 172.71.150.122:0 accepted tcp:ts3.cn.mm.bing.net:443 [direct]
2022/12/13 20:32:29 172.71.146.164:0 accepted tcp:img-s-msn-com.akamaized.net:443 [direct]
2022/12/13 20:32:32 172.69.34.73:0 accepted tcp:ts3.cn.mm.bing.net:443 [direct]
2022/12/13 20:32:38 172.71.142.98:0 accepted tcp:ipv6.msftconnecttest.com:80 [direct]

**Comment by chilll11** [comment]
说到这 大佬 还要请教一个问题😂 一个ssh连接服务器时候的问题  有时候ssh能连 有时候又连不上不知道为什么 （报错10053）试过两种工具（xshell7,putty) 都是这样  之前连的时候都没什么问题 😔

**Comment by crazypeace** [comment]
从服务器端的日志来看， 访问 IG 的请求出去了呀
发散一点思考的话。
1. 你有没有在 v2ray 上面配置dns?
2. 你自己的浏览器有没有奇怪的插件？ 不如你安装一个纯净的 firefox ，在它的浏览器设置中可以指定代理端口，让它“全局”走你的梯子。

**Comment by chilll11** [comment]
> 从服务器端的日志来看， 访问 IG 的请求出去了呀 发散一点思考的话。
> 
> 1. 你有没有在 v2ray 上面配置dns?
> 2. 你自己的浏览器有没有奇怪的插件？ 不如你安装一个纯净的 firefox ，在它的浏览器设置中可以指定代理端口，让它“全局”走你的梯子。
没有额外配置dns  脚本搭好后就基本没动啥了
下了火狐发现知识有点超纲了😂
是要配置socks吗
![1670943969160(1)](https://user-images.githubusercontent.com/113433243/207369797-8934eaa8-9327-4df4-996e-a0366fec84c2.jpg)

**Comment by crazypeace** [comment]
对呀， 直接配置socks代理。
如果你是用的v2rayN.
直接看界面左下角写的是什么。
![Xshell_socks5](https://user-images.githubusercontent.com/665889/207372927-93c4f483-a3aa-4ec3-929a-d028256ad581.png)

**Comment by rainmint** [comment]
解决了吗 我也是ins登录不上   429
