### ISSUE TITLE
windows v2rayN客户端，服务启动成功后无法科学上网，手机端shadowrocket正常

### ISSUE THREAD

**Issue by Sccpx** [233boy/v2ray#1027]
求教。。
![微信截图_20221210231228](https://user-images.githubusercontent.com/49812161/206862044-fcd9fbfe-9bd1-43e9-9299-d86d412128b8.png)

**Comment by crazypeace** [comment]
试试这个 https://github.com/crazypeace/v2rayN-3.29-VLESS

**Comment by FikaCode** [comment]
用3.29 ，之后的版本都用路由来分流了，需要配置一下。这个我看那个issues 已经好多人讨论过了。用旧版本吧。

**Comment by crazypeace** [comment]
这个  3.29 小改版 支持 vless 链接的复制粘贴 ，二维码分享和扫描。
https://github.com/crazypeace/v2rayN-3.29-VLESS

**Comment by Sccpx** [comment]
> 这个 3.29 小改版 支持 vless 链接的复制粘贴 ，二维码分享和扫描。 https://github.com/crazypeace/v2rayN-3.29-VLESS
 
您好 我试了一下 还是不行 方便加个联系方式咨询一下吗？

**Comment by crazypeace** [comment]
![v2ray-client-configuration](https://user-images.githubusercontent.com/665889/207884238-f94bb094-5d41-4e28-b5bd-1fd81aaddee0.png)
人眼检查一下配置参数
如果是搭的VMESS节点，电脑注意要同步系统时间（不用管时区设置）

**Comment by crazypeace** [comment]
这是一个如果节点本身没问题，而你不能用的排错教程
https://zelikk.blogspot.com/2022/04/connect-v2ray-websocket-tls-troubleshoot.html

**Comment by Sccpx** [comment]
> 这是一个如果节点本身没问题，而你不能用的排错教程 https://zelikk.blogspot.com/2022/04/connect-v2ray-websocket-tls-troubleshoot.html

感谢您的耐心解答。我刚刚对照了一遍，发现了一个问题——在namesilo购买的域名已经过期，查了下时间应该是今年五月份过期的，猜测可能是这个原因导致无法访问？
我的情况大概是这样的，两年多以前按照某篇教程通过域名进行伪装的服务器（目前该教程已经404），当时做好了一切设置，然后到最近，重装了一下电脑系统，重新下载了v2ray之后就无法访问。如果是因为域名的原因的话，目前手机端仍然可用，电脑端重装系统前也是可用的。还会有别的问题吗？

最后，由于域名过期时间已经有点长了，我是否需要重新够买个域名进行相关设置和伪装？是否能解决我的问题？

万分感谢！
