### ISSUE TITLE
服务器上开启成功，但是客户端一直连接不上

### ISSUE THREAD

**Issue by 18122711180** [233boy/v2ray#1029]
![微信图片_20221213174310](https://user-images.githubusercontent.com/21071715/207283837-8e87f9cb-3856-4830-b821-80ad0ab3a2d9.png)
![image](https://user-images.githubusercontent.com/21071715/207283897-ebacd465-55c9-417b-bdf1-f2de15ad6cbc.png)

**Comment by xuedongchenR** [comment]
尝试在供应商那里开启相应端口的防火墙，有安装宝塔类的面板要在那里放行端口。

**Comment by crazypeace** [comment]
排错教程：
[安装 V2ray Websocket + TLS 模式 排错 Troubleshoot](https://zelikk.blogspot.com/2022/04/setup-v2ray-websocket-tls-troubleshoot.html)
[连接 V2Ray Websocket + TLS 模式服务器的过程及如何排错 Troubleshoot](https://zelikk.blogspot.com/2022/04/connect-v2ray-websocket-tls-troubleshoot.html)

**Comment by jinfagang** [comment]
@crazypeace 你这个网站本身就反问不了了

**Comment by crazypeace** [comment]
> @crazypeace 你这个网站本身就反问不了了

这个博客用的是编程随想同款，所以被墙了。要搭梯子。
下面这两个反代，只能看到文字，看不到图片。
https://tzzhu.cf/2022/04/setup-v2ray-websocket-tls-troubleshoot.html
https://tzzhu.cf/2022/04/connect-v2ray-websocket-tls-troubleshoot.html
