### ISSUE TITLE
v2ray.sh 文件无法下载

### ISSUE THREAD

**Issue by zkbutt** [233boy/v2ray#1031]
bash <(curl -s -L https://git.io/v2ray.sh)
无法访问和下载

**Comment by 233boy** [comment]
@zkbutt 
试试看看看这个
```bash <(curl -s -L  https://github.com/233boy/v2ray/raw/master/v2ray.sh)```

**Comment by vhdp** [comment]
This doesn't work either

**Comment by vhdp** [comment]
> @zkbutt try and see this `bash <(curl -s -L https://github.com/233boy/v2ray/raw/master/v2ray.sh)`

This doesn't work either

**Comment by Dickson-25** [comment]
What happened ...

**Comment by Dickson-25** [comment]
> @zkbutt 
> 试试看看看这个
> ```bash <(curl -s -L  https://github.com/233boy/v2ray/raw/master/v2ray.sh)```

Not working properly my connections  is too luggish and slower
