### ISSUE TITLE
配置为kcp无法使用

### ISSUE THREAD

**Issue by Bryan007001** [233boy/v2ray#1033]
地址 (Address) = 43.128.xxx.xxx

 端口 (Port) = 37189

 用户ID (User ID / UUID) = 4710d934-8482-4db0-b178-f962bcbb0428

 额外ID (Alter Id) = 0

 传输协议 (Network) = kcp

 伪装类型 (header type) = wechat-video

经测试v2ray status显示v2ray运行正常
V2Ray 状态: 正在运行

用mobaxterm执行nc -vuz测试从自己pc到服务器端口正常可连通。
nc -vuz 43.128.72.125 37189
Connection to 43.128.72.125 37189 port [udp/*] succeeded!

复制了vmess连接，以剪贴板形式导入v2ray客户端，启动后无法连上google。

原来用的ws + tsl，用端口443可上google，但用了一天443貌似就被封了，从pc用telnet ip 443无法连通，被迫只能改为其他协议，改为tcp，试过伪装为下载那个，不行，后来改为微信视频这个，还是不行。

**Comment by 233boy** [comment]
@Bryan007001 测试一下 tcp 看看能不能行，端口不变

**Comment by strike94** [comment]
@233boy 你好，我同样出现了kcp协议无法使用，但换成tcp协议可以，是现在不能使用kcp协议了吗
