### ISSUE TITLE
10月ws+tls就被墙了一次443换tcp直接封了ip，换ip用到今天443又被墙了，被迫套了cdn

### ISSUE THREAD

**Issue by Daituyo** [233boy/v2ray#1035]

**Comment by HopscotchSen** [comment]
Did you find solutions?

**Comment by hixingchen** [comment]
怎么套cdn

**Comment by wuxushun** [comment]
套cdn你会发现，它依然会有其他手段阻断你通讯。上个网真是一言难尽，哎。

**Comment by P0sterboi** [comment]
我也是，12.30号突然443端口又给封了，但我明明套了CDN，也还是不能通讯了。

**Comment by crazypeace** [comment]
> 套cdn你会发现，它依然会有其他手段阻断你通讯。上个网真是一言难尽，哎。

弄多个域名
https://zelikk.blogspot.com/2022/01/ws-tls-v2ray-caddy-multi-domain.html
