### ISSUE TITLE
这玩意有挖坑后门 用一段时间后卡的不行

### ISSUE THREAD

**Issue by UnrealCherry** [233boy/v2ray#1036]
然后上线配置 v2ray看了一下日志就恢复了
绝壁被当成了机场

**Comment by crazypeace** [comment]
来看看这个极简脚本
https://github.com/crazypeace/v2ray_wss
这个一键脚本超级简单。有效语句11行(其中BBR 5行, 安装V2Ray 1行, 安装Caddy 5行)+Caddy配置文件18行(其中你需要修改4行)+V2Ray配置文件89行(其中你需要修改2行), 其它都是用来检验小白输入错误参数或者搭建条件不满足的。
你如果不放心开源的脚本，你可以自己执行那11行有效语句，再修改配置文件中的6行，也能达到一样的效果。

**Comment by mmat001** [comment]
这个是真的吗

**Comment by crazypeace** [comment]
你可以从这个极简脚本开始学习，很快你就能制作自己的脚本了。
反正都是拼拼凑凑。

**Comment by 233boy** [comment]
@UnrealCherry 
拜托，怎么又有人说这个；代码都是开源的，你觉得有问题，自己审查代码不就是行了吗 😂
