### ISSUE TITLE
不是吧 第二天就被墙了

### ISSUE THREAD

**Issue by fatCat2015** [233boy/v2ray#1037]
不是吧 第二天就被墙了

**Comment by BookerLiu** [comment]
我也是第二天就被墙了,  两个服务器最近都被墙了,  我估计这个脚本用的人太多了,  反而成了检测IP的办法

**Comment by 233boy** [comment]
@fatCat2015 @BookerLiu 
脚本只是优化搭建过程，跟什么检测被封没有什么关系

**Comment by yin-z** [comment]
最近是不是严打啊被封了三次了
