### ISSUE TITLE
用这个脚本搭的VPS一直被墙IP, 兄弟萌来推荐一个新的脚本用用

### ISSUE THREAD

**Issue by BookerLiu** [233boy/v2ray#1039]

**Comment by crazypeace** [comment]
你选带域名的模式, websocket + tls 模式。

https://github.com/crazypeace/v2ray_wss

**Comment by hixingchen** [comment]
我websocket+tls用了几天就被墙了，ping的通但是不能上网，有解决办法吗

**Comment by crazypeace** [comment]
自己排查一下
[安装 V2ray Websocket + TLS 模式 排错 Troubleshoot](https://zelikk.blogspot.com/2022/04/setup-v2ray-websocket-tls-troubleshoot.html)

[连接 V2Ray Websocket + TLS 模式服务器的过程及如何排错 Troubleshoot](https://zelikk.blogspot.com/2022/04/connect-v2ray-websocket-tls-troubleshoot.html)
