### ISSUE TITLE
分流时访问域名 cloudflare提示525 SSL handshake failed

### ISSUE THREAD

**Issue by lijump** [233boy/v2ray#104]
首先表示诚挚感谢，我作为非程序员小白也能用v2ray，甚至救回被封ip多亏了作者。
只是申请的freenom，收到邮件说需要有网页，否则收回域名。因此又尝试做分流。设置了分流路径和伪装网站。但是无论是在caddyfile里设置了root路径,加了index.html，还是用本脚本设置了伪装网站，访问域名都提示525 SSL handshake failed。
这个有办法解决么。

**Comment by 233boy** [comment]
@lijump 
你看一下 cloudflare 帮助文档看看？？：https://support.cloudflare.com/hc/en-us/articles/200278659-Error-525-SSL-handshake-failed
