### ISSUE TITLE
用国内域名供应商和国外的区别大吗？

### ISSUE THREAD

**Issue by oliverck** [233boy/v2ray#1042]
之前用腾讯云的
但是搭网站的时候，访问几次之后就会让我实名认证
所以想问下，这个会不会影响代理？

**Comment by mmat001** [comment]
扶墙居然用国内域名啊

**Comment by yin-z** [comment]
国内要实名的

**Comment by oliverck** [comment]
之前是为了省事就直接用了买过的腾讯云域名
不过总是过一阵子就用不了，当时也没排查为啥，就直接重新配置一遍就行了。
这次新搞了个namesilo的域名
