### ISSUE TITLE
最近是因为疫情解封开始大力封禁了吗

### ISSUE THREAD

**Issue by yin-z** [233boy/v2ray#1043]
最近被封的很频繁啊都是用了俩三天就封

**Comment by Dickson-24** [comment]
Am using xu-i panel v1.4.2 for multiuser ..it is  able to connect traffics running but not working  using port 443 HTTP mode its not working to me bash <(curl -Ls https://raw.githubusercontent.com/vaxilu/x-ui/master/install.sh) ..am using Ubuntu 22 TLS

**Comment by x3xx1818** [comment]
你用的是什么服务器
