### ISSUE TITLE
Debian系统安装curl失败

### ISSUE THREAD

**Issue by Chonglian233** [233boy/v2ray#1049]
![mmexport1675775301481](https://user-images.githubusercontent.com/44470472/217254886-cbcc025f-35a8-408b-b95f-1b3f19975f99.png)
安照教程操作，发现没装curl，然后输入指令，出现上图情况，小白求解

**Comment by Chonglian233** [comment]
系统 Debian10

**Comment by foolkiddes** [comment]
你这个没有安装上curl，建议apt update回车会有几个提示，输入Y回车。更新后在输入apt install curl
