### ISSUE TITLE
传输协议为 mKCP，Android 端网络良好，Mac 端网络不稳定。请问有解决的方法吗？

### ISSUE THREAD

**Issue by barrylu1999** [233boy/v2ray#105]
您好，使用了您的「V2Ray 一键安装脚本 & 管理脚本」。
我的情况：
IP，国内 TCP 检测不可用。所以传输协议设置为了 mKCP。

- Android 端，使用的是 v2rayNG 客户端。网络正常流畅；
- Mac 端，使用的是 V2rayU 客户端。网络十分不稳定，访问网页，经常需要刷新多次，才能打开。有时候基本无法使用了。
注：是一键脚本的默认配置。

请问有解决的方法吗？谢谢！

**Comment by 233boy** [comment]
@barrylu1999 
有点无解了，看看是不是开了 Mux ，在客户端看看
