### ISSUE TITLE
centos7服务自动停止

### ISSUE THREAD

**Issue by china-zhoujie** [233boy/v2ray#1050]
centos7服务自动停止，请问是做了什么更新么？

**Comment by azx4833** [comment]
原来不止我一个突然这样。。。。。。。。。。

**Comment by china-zhoujie** [comment]
> 原来不止我一个突然这样。。。。。。。。。。

解决了吗？我的一直都没有恢复

**Comment by china-zhoujie** [comment]
我的找到问题了，自身的环境原因,打扰了

**Comment by azx4833** [comment]
我的重装下好了，但是隔天瓦工IP已经被ban了...
