### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by gremlin-z** [233boy/v2ray#1057]
打开后如下

配置成功
[] [Trojan] TG群:@WeoAirport_Group(weo-hk-2***cf:443)
启动服务(2023/2/27 21:08:31)...
Xray 1.6.1 (Xray, Penetrates Everything.) Custom (go1.19.2 windows/386)
A unified platform for anti-censorship.
2023/02/27 21:08:31 [Info] infra/conf/serial: Reading config: C:\Users\an\Desktop\v2rayn\config.json
2023/02/27 21:08:31 [Warning] core: Xray 1.6.1 started

无法正常上网，求大佬帮忙

**Comment by iwaitu** [comment]
我之前是 websocket + tls 一直正常，从昨天开始也不能访问了，改 tcp 又可以
