### ISSUE TITLE
已安装成功，测试连接失败，net/http:TLS handshake timeout

### ISSUE THREAD

**Issue by ly4501221** [233boy/v2ray#1060]

**Comment by gentlelion99** [comment]
我也是，经常的，应该是常见的问题。

**Comment by gentlelion99** [comment]
没人愿意帮下小白吗

**Comment by x3xx1818** [comment]
你用的是什么协议

**Comment by gentlelion99** [comment]
我也不会 啥也不懂 只是根据提示来提问的

x3xx1818 ***@***.***> 於 2023年3月9日週四 下午3:05寫道：

**Comment by gentlelion99** [comment]
> 你用的是什么协议

一键安装脚本，缺省配置。

**Comment by x3xx1818** [comment]
好像是KCP+DTLS

**Comment by x3xx1818** [comment]
TCP之类的一般Ping通连接失败的

**Comment by gentlelion99** [comment]
> 好像是KCP+DTLS

应该怎么解决，谢谢。

**Comment by 1682145** [comment]
尝试打开下端口试试

> > 好像是KCP+DTLS
> 
> 应该怎么解决，谢谢。

**Comment by kaiguan** [comment]
> > 好像是KCP+DTLS
> 
> 应该怎么解决，谢谢。

你的配置搞定了吗？

**Comment by gentlelion99** [comment]
> > > 好像是KCP+DTLS
> > 
> > 
> > 应该怎么解决，谢谢。
> 
> 你的配置搞定了吗？
重新搞了

**Comment by KyuuChyan** [comment]
可以尝试换下os，我从ubuntu22换到debian10就没问题了

**Comment by WUWEI81** [comment]
kcp的，换成tcp就可以了

**Comment by jinfagang** [comment]
vultr的服务器好像都不行。。。。

**Comment by Machine60672** [comment]
我现在买了服务器，也按照步骤搭建了v2ray,但是还是无法上网

**Comment by activeGeo** [comment]
看一下服务器的端口有没有开放，一般来说买的服务器只会开通22端口

**Comment by Machine60672** [comment]
可以有你的联系方式吗？

**Comment by activeGeo** [comment]
如果需要帮助，请直接发送邮件即可。

在2023-05-08 ***@***.***写道：

可以有你的联系方式吗？

**Comment by activeGeo** [comment]
我知道的就是使用BBR加速：
wget --no-check-certificate https://github.com/teddysun/across/raw/master/bbr.sh && chmod +x bbr.sh && ./bbr.sh
systemctl restart v2ray

服务器的位置对速度也有很大影响。可以尝试韩国、日本、洛杉矶的服务器看一下。


在2023-05-08 ***@***.***写道：

我现在搭建V2RAY 也可以上网了，但是网速慢，我有重新做系统搭建了trojan，但是网速还是很慢，我买的服务器带宽是1，有什么加速的办法吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "233boy/v2ray" ***@***.***&gt;;
发送时间:&nbsp;2023年5月8日(星期一) 下午3:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [233boy/v2ray] 已安装成功，测试连接失败，net/http:TLS handshake timeout (Issue #1060)





如果需要帮助，请直接发送邮件即可。

在2023-05-08 ***@***.***写道：

可以有你的联系方式吗？

**Comment by Machine60672** [comment]
感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "233boy/v2ray"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月8日(星期一) 下午3:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [233boy/v2ray] 已安装成功，测试连接失败，net/http:TLS handshake timeout (Issue #1060)





 我知道的就是使用BBR加速：
 wget --no-check-certificate https://github.com/teddysun/across/raw/master/bbr.sh &amp;&amp; chmod +x bbr.sh &amp;&amp; ./bbr.sh
 systemctl restart v2ray
 
 服务器的位置对速度也有很大影响。可以尝试韩国、日本、洛杉矶的服务器看一下。
 
 
 在2023-05-08 ***@***.***写道：
 
 我现在搭建V2RAY 也可以上网了，但是网速慢，我有重新做系统搭建了trojan，但是网速还是很慢，我买的服务器带宽是1，有什么加速的办法吗
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------
 发件人: "233boy/v2ray" ***@***.***&amp;gt;;
 发送时间:&amp;nbsp;2023年5月8日(星期一) 下午3:33
 ***@***.***&amp;gt;;
 ***@***.******@***.***&amp;gt;;
 主题:&amp;nbsp;Re: [233boy/v2ray] 已安装成功，测试连接失败，net/http:TLS handshake timeout (Issue #1060)
 
 
 
 
 
 如果需要帮助，请直接发送邮件即可。
 
 在2023-05-08 ***@***.***写道：
 
 可以有你的联系方式吗？

**Comment by shawn0623** [comment]
这个问题如何解决?

**Comment by gentlelion99** [comment]
换成x-ui算了

ZHENYUWANG ***@***.***> 於 2023年9月10日週日 上午10:23寫道：

**Comment by jinyule** [comment]
**我也出现了这个情况，后面发现是因为我使用的VMess-mKCP-dynamic，重点在于动态端口这块，我的安全组/防火墙没有放开，所以出现该问题**[V2Ray 提供了一个叫动态端口的功能](https://guide.v2fly.org/advanced/dynamicport.html)

**Comment by gentlelion99** [comment]
厉害了，但我不懂怎么配置。

jinyule ***@***.***> 于 2024年2月18日周日 21:11写道：

**Comment by jinyule** [comment]
看使用什么VPS了，可以google一下查查对应教程

**Comment by okdddddd** [comment]
我解决了，是端口没开的问题。进去把端口开了就可以了。我用的是宝塔面板。
