### ISSUE TITLE
有能上chatgpt的机场吗？

### ISSUE THREAD

**Issue by jgy1013** [233boy/v2ray#1062]
自建的谷歌云，购买的JMS LA，都不行。。求推荐

**Comment by hellofuc1** [comment]
你个傻逼

**Comment by ClashPacfree** [comment]
这个可以用：[ChatGPT机场](https://github.com/xiaoming2028/FreePAC/wiki/ChatGPT%E6%B3%A8%E5%86%8C%E6%95%99%E7%A8%8B%EF%BC%88%E5%AE%8C%E6%95%B4%E6%8C%87%E5%8D%97%EF%BC%89)
