### ISSUE TITLE
有没有大佬教教github codespace怎么搭v2ray节点？

### ISSUE THREAD

**Issue by realysy** [233boy/v2ray#1069]
用这个仓库的install.sh脚本安装了，当`sudo v2ray - 8 启动 - 1 启动`的时候fail, 应该是因为codespace里面没有systemctl, 手动执行`service v2ray start`会提示`v2ray: unrecognized service`。

于是我尝试直接运行原生v2ray以启动结点，尝试了两个配置都无法代理：

- 尝试一：`sudo /usr/bin/v2ray/v2ray run -c /etc/v2ray/config.json`

- 尝试二：`sudo /usr/bin/v2ray/v2ray run -c /etc/v2ray/233blog_v2ray_config.json`

在运行上面命令之前已经手动开启了目标端口；尝试了前4种协议都不行

**Comment by piwawa** [comment]
这都能搭节点的吗、、、
