### ISSUE TITLE
用该脚本，近期443被封，求大神

### ISSUE THREAD

**Issue by zhysas** [233boy/v2ray#1070]
用该脚本年多一直很稳，TLS=WS+过CF云朵。近期443被封，记得233脚本安装时默认是443端口，不知可否换？
换成什么端口？求大神支招

**Comment by auhaij** [comment]
我只剩了22和80没被封

**Comment by songge8** [comment]
我的是过几天就被封，换个端口过几天继续封，就这样封了换换了封坚持了几个月了。最近不知道怎么了，SSL加密了还做了伪装还被封

**Comment by songge8** [comment]
亲测可以选择伪装协议，启用动态端口试试

**Comment by zhysas** [comment]
> 亲测可以选择伪装协议，启用动态端口试试

谢谢大佬！

**Comment by zhysas** [comment]
> 我的是过几天就被封，换个端口过几天继续封，就这样封了换换了封坚持了几个月了。最近不知道怎么了，SSL加密了还做了伪装还被封

据说是强升高了，被封后也一齐被标记了，以后会经常封
