### ISSUE TITLE
一键安装后手机端可正常使用，第二天电脑端尝试使用v2rayN后，手机端也提示net/http:TLS handshake timeout

### ISSUE THREAD

**Issue by Jay11235** [233boy/v2ray#1073]
协议是ws+tls，开启了分流和伪装，安装好后手机端是可以正常使用的
第二天用电脑尝试使用v2rayN，一直不能正常连接，然后用手机尝试，发现提示net/http:TLS handshake timeout
重装os，重装v2ray，更换域名，都一样的提示
大佬帮忙看看是什么问题？

**Comment by Jay11235** [comment]
vps可以正常ssh，域名也可以正常访问，都没有被墙

**Comment by ylbuuu** [comment]
443被墙了吧
