### ISSUE TITLE
请问下为啥4g下基本没有速度

### ISSUE THREAD

**Issue by Kiswelrg** [233boy/v2ray#1078]
是在ios下测的移动4g网的话，kitsunebi，shadowrocket这些都是一样几乎等于没有速度，想问下这是由于协议问题还是什么问题，
pc端的话win和mac都试过v2rayN clash这些客户端，油管能看4k的，就是移动端4g的话很慢，只能连wifi

**Comment by x3xx1818** [comment]
可能是你服务器的原因，可能宽带是电信的，但是你手机是联通或者移动的
