### ISSUE TITLE
Failed to start Caddy HTTP/2 web server.

### ISSUE THREAD

**Issue by zzh151223** [233boy/v2ray#108]
service caddy status出现这个Failed to start Caddy HTTP/2 web server.这个怎么搞

**Comment by sam019** [comment]
我也遇到过, 可能是域名还没有解析到你的服务器ip的原因, 我再解析成功后重新安装了一遍就没有这个问题了

**Comment by darkfitch** [comment]
> 我也遇到过, 可能是域名还没有解析到你的服务器ip的原因, 我再解析成功后重新安装了一遍就没有这个问题了

额 我已经可以解析了,但是caddy还是不能开启,依旧是这个错误

**Comment by renyusang** [comment]
我也碰到了该问题，求解答，我的服务器上lnmp部署着wordpress网站

**Comment by zzh151223** [comment]
我换了家服务器商就正常了，不过还是连接不上，然后我就继续用ssr了

**Comment by zzh151223** [comment]
我换了家服务器商就正常了，不过还是连接不上，然后我就继续用ssr了

**Comment by zzh151223** [comment]
我换了家服务器商就正常了，不过还是连接不上，然后我就继续用ssr了

**Comment by darkfitch** [comment]
> 我换了家服务器商就正常了，不过还是连接不上，然后我就继续用SSR了

我觉得sam019(https://github.com/sam019)他说的没毛病,我但我的域名解析已经完成了,可是可能是我这边已经能够解析了,而vps那边还没有完成解析,所以才会有这问题,顺便说 ssr还能用么?我的死活用不了

**Comment by huxiaofan1223** [comment]
估计就是80端口或者443端口被占用了。把nginx杀了就行了
