### ISSUE TITLE
 [Warning] failed to handler mux client connection > proxy/vmess/outbound: failed to find an available destination > common/retry: [dial tcp 198.23.137.17:65501: i/o timeout] > common/retry: all retry attempts failed

### ISSUE THREAD

**Issue by qaz1234560** [233boy/v2ray#1080]

**Comment by jinfagang** [comment]
Same here, vultr

**Comment by 233boy** [comment]
@jinfagang @qaz1234560 
是 vultr 的问题，应该是 IP 端口被搞了，换个商家吧

**Comment by jinfagang** [comment]
@233boy 一开始我没有加firewall规则，但是加了之后，tm直接ssh'都连不上了

**Comment by 233boy** [comment]
@lucasjinreal 正常，你把 SSH 端口开放才行

**Comment by PhiBrain-ZhaoLiang** [comment]
@233boy 一样的问题，但是关闭MUX后，则给出了另一个错误信息：
[Warning] [2933293801] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://sms-pog.tk/):  > remote error: tls: internal error] > common/retry: all retry attempts failed
用的是你的一键化脚本搭建的，最新版和旧版都试过了
协议：WS+TLS
参考教程：https://github.com/233boy/v2ray/wiki/%E4%BD%BF%E7%94%A8Cloudflare%E4%B8%AD%E8%BD%ACV2Ray%E6%B5%81%E9%87%8F
如果需要提供其他信息请告诉我，我会尽快回复

最终目的：WS＋TLS＋SOCKS5访问GPT
