### ISSUE TITLE
请问可以在纯ipv6 vps下安装吗？

### ISSUE THREAD

**Issue by suzhiming** [233boy/v2ray#1081]
前几天开了个纯ipv6的vps，运行脚本后截面没反应，Google了一会也不清楚咋搞，又开了个ipv4+ipv6的vps，运行脚本后就正常了

**Comment by 233boy** [comment]
@suzhiming Github 下载文件的时候，会失败，好像 Github 这边不支持 V6

**Comment by mingyueqianli** [comment]
只有v6怎么解决，我升级系统环境也不行找不到镜像，，装warp他也去GitHub下载，也不成功！不好解决呀
