### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by lucasjinreal** [233boy/v2ray#1083]
尝试了mKP TCP websocket vless vmess 全部是TSL Handshake timeout, windows android都不行。
vultr，

vps ssh能正常连接。

**Comment by 233boy** [comment]
@jinfagang 
你安装旧版本看看
```
bash <(curl -sL https://git.io/v2ray.sh) online old
```

**Comment by x3xx1818** [comment]
你端口（防火墙）开了吗
