### ISSUE TITLE
Red Hat 9.1 无法安装v2ray！

### ISSUE THREAD

**Issue by piwawa** [233boy/v2ray#1087]
![屏幕截图 2023-04-24 222533](https://user-images.githubusercontent.com/46926496/234027227-e4c58b37-79c9-40f1-83fe-eacdf6cd9bf3.png)

服务器的系统信息如下：
`cat /etc/redhat-release`
`Red Hat Enterprise Linux release 9.1 (Plow)`

另外好像脚本里用了ntp，我发现这个版本的系统无法用yum安装ntp，不过不知道安装失败的原因具体是什么。。。

**Comment by piwawa** [comment]
> @piwawa 这不是我的脚本，这是别人拿了我的脚本，然后只为了改那个显示 jms 推广的链接。**还有没有动别的地方，不清楚！**
> 
> **不建议使用这种来路不名的脚本！**
> 
> 如果你想要安装我的脚本， 一键安装：
> 
> `bash <(curl -sL https://git.io/v2ray.sh) `
> 
> 旧版本, V2 v4.45.2:
> 
> `bash <(curl -sL https://git.io/v2.sh) online old `
> 
> 至于 Red Hat 9.1 为什么无法正确安装，应该是最后生成配置文件的时候出错了，脚本推荐使用 Debian 或者Ubuntu 系统。

我用的这个破脚本，不知道谁写的：
bash <(curl -s -L https://git.io/v2ray.sh)

**Comment by 233boy** [comment]
> > @piwawa 这不是我的脚本，这是别人拿了我的脚本，然后只为了改那个显示 jms 推广的链接。**还有没有动别的地方，不清楚！**
> > **不建议使用这种来路不名的脚本！**
> > 如果你想要安装我的脚本， 一键安装：
> > `bash <(curl -sL https://git.io/v2ray.sh) `
> > 旧版本, V2 v4.45.2:
> > `bash <(curl -sL https://git.io/v2.sh) online old `
> > 至于 Red Hat 9.1 为什么无法正确安装，应该是最后生成配置文件的时候出错了，脚本推荐使用 Debian 或者Ubuntu 系统。
> 
> 我用的这个破脚本，不知道谁写的： bash <(curl -s -L https://git.io/v2ray.sh)

你这明显不是用我的呀

**Comment by piwawa** [comment]
> > > @piwawa 这不是我的脚本，这是别人拿了我的脚本，然后只为了改那个显示 jms 推广的链接。**还有没有动别的地方，不清楚！**
> > > **不建议使用这种来路不名的脚本！**
> > > 如果你想要安装我的脚本， 一键安装：
> > > `bash <(curl -sL https://git.io/v2ray.sh) `
> > > 旧版本, V2 v4.45.2:
> > > `bash <(curl -sL https://git.io/v2.sh) online old `
> > > 至于 Red Hat 9.1 为什么无法正确安装，应该是最后生成配置文件的时候出错了，脚本推荐使用 Debian 或者Ubuntu 系统。
> > 
> > 
> > 我用的这个破脚本，不知道谁写的： bash <(curl -s -L https://git.io/v2ray.sh)
> 
> 你这明显不是用我的呀

那应该用的这个:
`bash <(curl -s -L https://git.io/v2rayinstall.sh)`

https://www.itblogcn.com/article/406.html 这货的教程

**Comment by 233boy** [comment]
@piwawa 就是有的，别人拿我的去给换了
