### ISSUE TITLE
quic的配置文件在哪里

### ISSUE THREAD

**Issue by ltto** [233boy/v2ray#1090]
![image](https://user-images.githubusercontent.com/24884691/234553816-8a22fdf0-71c4-4c35-a46d-60e987e1f3da.png)

quic的配置文件在哪里? 我用这台电脑做中专站  链接我另一条电脑的v2ray服务

**Comment by 233boy** [comment]
@ltto 在 /etc/v2ray/config.json

**Comment by ltto** [comment]
3q
