### ISSUE TITLE
vps可用，但是xshell无法连接是什么情况

### ISSUE THREAD

**Issue by Chonglian233** [233boy/v2ray#1094]
IP在ping.pe显示没问题，联系客服vps没出问题。但是xshell无法连接到ssh
![mmexport1683294825156](https://user-images.githubusercontent.com/44470472/236478012-b423c4fa-333f-41cb-9628-396f76ff9d16.png)
![mmexport1683294823852](https://user-images.githubusercontent.com/44470472/236478020-9350c1a8-e03a-4bb0-b96d-35534eb90806.png)

**Comment by DAarkn** [comment]
可能是网的问题吧，用手机热点试试，校园网一般是不行的

**Comment by 233boy** [comment]
@Chonglian233 你设置了代理啊，把代理关了，属性，连接，代理

**Comment by Chonglian233** [comment]
> @Chonglian233 你设置了代理啊，把代理关了，属性，连接，代理

你是说要我把电脑开的vpn关了吗？我那时候试过了，不开代理也连不上ssh，那时候全部vps都是操作超时的。

**Comment by stampidx** [comment]
同，昨天开始频繁无法连接，想看看出了什么问题。结果在vps网页面板可以操作。但是无法ssh连上....报错跟你一样
