### ISSUE TITLE
现在IP被封后，套CF都没有办法出网了吗

### ISSUE THREAD

**Issue by strike94** [233boy/v2ray#1097]
被封ip后想通过套CF使用vless_websocket_tls救一救，但是都配置成功后还是无法访问vps
app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket

**Comment by strike94** [comment]
能出网了 但是时好时坏，经常会出现This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server，有大佬有解决方案吗

**Comment by PhiBrain-ZhaoLiang** [comment]
一样，我以为就我一个，没想到是一大片

**Comment by PhiBrain-ZhaoLiang** [comment]
> 能出网了 但是时好时坏，经常会出现This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server，有大佬有解决方案吗

重新套一下，先全部点灰，再点亮
