### ISSUE TITLE
你好 用了脚本后出现了些问题用不了 

### ISSUE THREAD

**Issue by zlt0907** [233boy/v2ray#11]
2018/03/08 21:34:12 183.*:47801 rejected  Proxy|VMess|Encoding: invalid user
2018/03/08 21:34:12 183.*.47451 rejected  Proxy|VMess|Encoding: invalid user
2018/03/08 21:34:12 183.*:50326 rejected  Proxy|VMess|Encoding: invalid user
2018/03/08 21:34:12 183.*:57756 rejected  Proxy|VMess|Encoding: invalid user
2018/03/08 21:34:12 183.*:42039 rejected  Proxy|VMess|Encoding: invalid user
2018/03/08 21:34:12 183.*:38070 rejected  Proxy|VMess|Encoding: invalid user
2018/03/08 21:34:12 183.*:37973 rejected  Proxy|VMess|Encoding: invalid user
2018/03/08 21:34:12 183.*:41905 rejected  Proxy|VMess|Encoding: invalid user
2018/03/08 21:34:12 183.*:44943 rejected  Proxy|VMess|Encoding: invalid user
2018/03/08 21:34:13 183.*:43045 rejected  Proxy|VMess|Encoding: invalid user

这是日志 貌似是拒绝访问的意思？

用的gcp 别的vps都可以 就gcp不行 不知道是哪的个问题

**Comment by 233boy** [comment]
@zlt0907 
检查一下你的客户端配置是否正确，不过我感觉还是直接重新开一台小鸡，用 Debian 9 系统来搞，然后再来配置，如果你有使用 V2RayN，我建议使用命令  `v2ray url`  ，之后复制 VMess 链接，然后导入配置，这样绝对不会出错
备注一下，GCP 的机子绝对没有问题的，因为我的脚本就是在 GCP 测试的。

**Comment by zlt0907** [comment]
你好 我按了你所说的去做 但还是老样子 所以我怀疑是不是gcp的防火墙设置问题
请问可以帮忙看看吗

https://i.imgur.com/mxG99fc.jpg

**Comment by 233boy** [comment]
@zlt0907 
GCP 的防火墙有点蛋痛，你先测试一下 80 443 这两个端口看看有没有问题吧，先确保你的实例已经开放这两个端口，如下图上所示，然后使用 `v2ray config` 命令更改端口，更改为 80 或者 443，协议就随便吧，先不要是 WS+TLS，凑合用
![snipaste_2018-03-08_15-13-19](https://user-images.githubusercontent.com/31657650/37138138-e0f75640-22e3-11e8-96e7-d1b9ea4dda93.png)

**Comment by zlt0907** [comment]
嗯 端口改成80就能用了...问题算是解决了（大概？）
顺便感谢解答

**Comment by 233boy** [comment]
@zlt0907 
那就是防火墙的问题了，所以不是脚本的问题。
顺便再说一下，你防火墙不是有那个名称标签的吗，就比如说你的那个 zlt0907 ，在新开小鸡的时候，加上这个标签，才算是开放你所定义的端口。
![image](https://user-images.githubusercontent.com/31657650/37139197-f78050ca-22e7-11e8-8bb1-4d64353dcef2.png)

**Comment by zlt0907** [comment]
按你说的做了 顺便端口换回去了 问题解决 
再次感谢！
