### ISSUE TITLE
关于使用Cloudflare后跳出百度云加速验证

### ISSUE THREAD

**Issue by StLein** [233boy/v2ray#110]
遇到一个问题，CloudFlare国内线路是不是有时会切换到百度云加速？
老家用的是电信网络，然后这个ip可能被运营商分配的太多用户使用的原因，
导致几乎所有网站都会弹一个百度云加速验证出来。
类似于这样  [https://www.v2ex.com/t/446003](https://www.v2ex.com/t/446003)

然后v2ray + CloudFlare加速也中招了，导致连接不成功。
我就想，v2ray有没有办法能过这个验证，比如主动弹出验证页面，验证完之后就在cookie里带上__cfduid和cf_clearance 这两个字段，不再被拦截之类的。

**Comment by 233boy** [comment]
@StLein 
这个我就不清楚了。 😂

**Comment by mikewubox** [comment]
CloudFlare国内版是与百度合作搞的。
