### ISSUE TITLE
脚本自动安装，但是不能用

### ISSUE THREAD

**Issue by luo1926** [233boy/v2ray#1100]
15:17:30) 开始安装...
15:17:30) 下载 V2Ray > https://github.com/v2fly/v2ray-core/releases/latest/download/v2ray-linux-arm64-v8a.zip
15:17:30) 下载 V2Ray 脚本 > https://github.com/233boy/v2ray/releases/latest/download/code.zip
15:17:33) 生成配置文件...

**Comment by 233boy** [comment]
@luo1926 断开 SSH，重新登录 SSH，输入 v2ray
