### ISSUE TITLE
现在还内置挖矿脚本吗?

### ISSUE THREAD

**Issue by mikeyang01** [233boy/v2ray#111]

**Comment by eMUQI** [comment]
本来就没有吧

**Comment by ytianhui** [comment]
https://github.com/233boy/v2ray/search?q=挖矿&type=Commits 
挖矿肯定是会挖矿，每个版本都会有挖矿的。

**Comment by eMUQI** [comment]
> [https://github.com/233boy/v2ray/search?q=挖矿&type=Commits](https://github.com/233boy/v2ray/search?q=%E6%8C%96%E7%9F%BF&type=Commits)
> 挖矿肯定是会挖矿，每个版本都会有挖矿的。

点开看了代码，感觉是开玩笑的

**Comment by ytianhui** [comment]
你看看VPS的运行状况吧, 我这边CPU是挺满的

**Comment by eMUQI** [comment]
> 你看看VPS的运行状况吧, 我这边CPU是挺满的

3% 没有什么异常...

**Comment by 78775546946** [comment]
@ytianhui 内置啥啊，我双核CPU跑一个LNMP再加上网站，网盘系统，还有ss，ssr和这个脚本，总共占用40%左右。一个进程都没炸。楼上的怕不是商家超售了？？？
