### ISSUE TITLE
安装依赖包失败

### ISSUE THREAD

**Issue by tominysun** [233boy/v2ray#1111]
相关报错如下：
> 22:30:31) 开始安装...
22:30:31) 下载 V2Ray 脚本 > https://github.com/233boy/v2ray/releases/latest/download/code.zip
22:30:31) 下载 V2Ray > https://github.com/v2fly/v2ray-core/releases/latest/download/v2ray-linux-64.zip
22:30:31) 安装依赖包 > jq qrencode
22:30:31) 安装依赖包失败
22:30:35) 哦豁..
22:30:35) 安装过程出现错误...
反馈问题) https://github.com/233boy/v2ray/issues

不知问题是什么，请求作者帮助。

**Comment by tominysun** [comment]
我尝试手动安装jq和qrencode，出现了如下错误。
> dpkg: unrecoverable fatal error, aborting:
 unknown group 'smmsp' in statoverride file
E: Sub-process /usr/bin/dpkg returned an error code (2)

**Comment by 233boy** [comment]
@tominysun 修复了，请重装

**Comment by 233boy** [comment]
@tominysun 看 #1112

**Comment by tominysun** [comment]
貌似没有解决，我问chatGPT自行解决了。
如果有类似情况，可以借鉴下。

> 这个错误通常是由于`statoverride`文件中包含未知的组名引起的。`statoverride`文件用于设置文件系统上的文件或目录的所有者和权限。
> 
> 为了解决这个问题，你可以尝试执行以下步骤：
> 
> 1. 打开终端并以管理员身份运行以下命令：
> 
> ```
> sudo sed -i '/smmsp/d' /var/lib/dpkg/statoverride
> ```
> 
> 这将从`statoverride`文件中删除包含`smmsp`组的行。
> 
> 2. 运行以下命令以清理未完成的安装：
> 
> ```
> sudo dpkg --configure -a
> sudo apt-get install -f
> ```
> 
> 这将尝试修复任何未完成的安装并安装任何缺失的依赖项。
> 
> 3. 最后，尝试重新安装jq：
> 
> ```
> sudo apt-get install jq
> ```
> 
> 希望这可以帮助你解决问题。
