### ISSUE TITLE
多配置文件时   选择操作目录会报错

### ISSUE THREAD

**Issue by izhoujie** [233boy/v2ray#1114]
1) 添加配置
 2) 更改配置
 3) 查看配置
 4) 删除配置
 5) 运行管理
 6) 更新
 7) 卸载
 8) 帮助
 9) 其他
10) 关于

请选择 [1-10]:4
选择: 删除配置
cat: /etc/v2ray/conf/VMess-TCP-2882.json VMess-WS-TLS-test.top.json: 没有那个文件或目录

错误! 无法识别协议: VMess-TCP-2882.json VMess-WS-TLS-test.top.json

#############################################
以上是安装完脚本后，再运行 v2ray add ws 命令添加伪装域名。之后再查看目录，如上 执行v2ray后输入4再执行就会报错，
解决办法：
     去/etc/v2ray/conf/ 把安装时的默认配置VMess-TCP-2882.json文件删除  只留VMess-WS-TLS-test.top.json 即可

**Comment by 233boy** [comment]
@izhoujie 不对啊。你删除配置的时候，你有两个配置，会让你选择其中一个的，你这个现象两个文件怎么识别为一个了，奇怪

**Comment by izhoujie** [comment]
> @izhoujie 不对啊。你删除配置的时候，你有两个配置，会让你选择其中一个的，你这个现象两个文件怎么识别为一个了，奇怪

我的操作顺序是：
1. 执行安装脚本
2. 执行 v2ray add ws  添加伪装域名
3. 执行 v2ray 
4. 任意选择一个操作（输入1-10任意）执行
5. 报错


你可以自己按顺序走一下就知道了，问题可以复现。

**Comment by 233boy** [comment]
@izhoujie 
完全无法复现，只有前 4 个选项会读取 json 文件，你后面的选项是怎么弄也不能存在报错，如果你还有其他 VPS，建议在别的 VPS  上安装一遍，复现你的操作是不是同样的错误

**Comment by izhoujie** [comment]
@233boy 
我重装复测了，确实不是全部，这块我说错了，是234三个选项会报错，应该是多文件冲突导致的，我最初是配置完ws后想用3查看配置，结果报错了。    我可以录制复现视频发给你。

**Comment by 233boy** [comment]
@izhoujie 
哦对，只有234才会读取 json，不用录视频，你这个问题，是无法将目录的 json 配置创建成一个列表返回，所以他默认将所有 json 当成是只有一个配置了，就会读取出错，但是我真的无法复现这个，你系统是不是没有 egrep

**Comment by izhoujie** [comment]
@233boy 
确定是egrep问题，用的centos，新装系统连wget都没。

**Comment by 233boy** [comment]
@izhoujie 

兄弟这个读取文件的 BUG 修复了

https://github.com/233boy/v2ray/releases/tag/v4.05

我不太清楚是否能解决你之前无法读取文件问题，如果你能帮忙测试一下那就太好了
