### ISSUE TITLE
最新版，添加配置无法选择伪装域名，手动修改后查看配置没有变化

### ISSUE THREAD

**Issue by PineSongCN** [233boy/v2ray#1132]
最新版，添加配置无法选择伪装域名，手动修改后查看配置没有变化
![image](https://github.com/233boy/v2ray/assets/39976617/60c231b0-9cb3-49cc-958e-e51972839d6d)

**Comment by 233boy** [comment]
@PineSongCN 那是伪装网站，不是伪装域名，指的是你打开自己域名的时候显示来自伪装网站的内容

**Comment by PineSongCN** [comment]
> @PineSongCN 那是伪装网站，不是伪装域名，指的是你打开自己域名的时候显示来自伪装网站的内容

谢谢，意思是伪装网站和伪装域名不同，并且伪装网站不显示在配置里吗？

**Comment by 233boy** [comment]
> > @PineSongCN 那是伪装网站，不是伪装域名，指的是你打开自己域名的时候显示来自伪装网站的内容
> 
> 谢谢，意思是伪装网站和伪装域名不同，伪装域名不可变，并且伪装网站不显示在配置里吗？

@PineSongCN 伪装域名其实就是你的域名，伪装网站不会显示出来的

**Comment by qcoltma** [comment]
请问伪装网站是不是随便设一个常用的比如www.baidu.com ,就可以了?

**Comment by 233boy** [comment]
@qcoltma 
不能是百度
