### ISSUE TITLE
老脚本升级失败

### ISSUE THREAD

**Issue by lt-gen2er** [233boy/v2ray#1135]
VPS：AWS Lightsail
Distributor ID: Debian
Description:    Debian GNU/Linux 9.13 (stretch)
Release:        9.13
Codename:       stretch

老脚本版本： v3.67

非root用户执行：
`bash <(curl -sL https://git.io/v2ray.sh)`

报错：
错误! 当前非 ROOT用户.

切换到su下执行：
`bash <(curl -sL https://git.io/v2ray.sh)`

得到以下log：

09:47:30) 开始安装...
09:47:30) 下载 V2Ray > https://github.com/v2fly/v2ray-core/releases/latest/download/v2ray-linux-64.zip
09:47:30) 下载 V2Ray 脚本 > https://github.com/233boy/v2ray/releases/latest/download/code.zip
09:47:30) 安装依赖包 > jq
09:47:33) 安装依赖包失败
09:47:33) 哦豁..
09:47:33) 安装过程出现错误...
反馈问题) https://github.com/233boy/v2ray/issues

**Comment by 233boy** [comment]
@lt-gen2er 但凡你稍微看一眼 https://github.com/233boy/v2ray/issues/1112

**Comment by lt-gen2er** [comment]
> @lt-gen2er 但凡你稍微看一眼 #1112

sorry 看了，解决了
