### ISSUE TITLE
在vultr上centos 7.5配置的时候出现问题

### ISSUE THREAD

**Issue by juilletVent** [233boy/v2ray#114]
#### 具体错误日志:

~~~
failed to serve http for WebSocket > accept tcp [::]:9722: use of closed network connection
~~~

#### 尝试过程

最开始在另一个厂家成功配置了WS+TLS模式，快到期了，重新配置这边，然后发现死活配置不好，WS+TLS、WS、TCP等等，都不行。检查了Caddy的状态，无法启动。

配置SS可以成功连接。不知道如何解决了

**Comment by ChristianYeah** [comment]
```journalctl -u caddy``` 查看一下 caddy的启动状态 应该签发证书的问题

**Comment by renyusang** [comment]
> journalctl -u caddy

`Feb 21 09:31:12 vultr.guest systemd[1]: Started Caddy HTTP/2 web server.
Feb 21 09:31:12 vultr.guest systemd[1]: caddy.service: main process exited, code=exited, status=226/NAMESPACE
Feb 21 09:31:12 vultr.guest systemd[1]: Unit caddy.service entered failed state.
Feb 21 09:31:12 vultr.guest systemd[1]: caddy.service failed.
Feb 21 09:31:12 vultr.guest systemd[1]: caddy.service holdoff time over, scheduling restart.
Feb 21 09:31:12 vultr.guest systemd[1]: Stopped Caddy HTTP/2 web server.
Feb 21 09:31:12 vultr.guest systemd[1]: Started Caddy HTTP/2 web server.
Feb 21 09:31:12 vultr.guest systemd[1]: caddy.service: main process exited, code=exited, status=226/NAMESPACE
Feb 21 09:31:12 vultr.guest systemd[1]: Unit caddy.service entered failed state.
Feb 21 09:31:12 vultr.guest systemd[1]: caddy.service failed.
Feb 21 09:31:12 vultr.guest systemd[1]: caddy.service holdoff time over, scheduling restart.
Feb 21 09:31:12 vultr.guest systemd[1]: Stopped Caddy HTTP/2 web server.
Feb 21 09:31:12 vultr.guest systemd[1]: Started Caddy HTTP/2 web server.
Feb 21 09:31:12 vultr.guest systemd[1]: caddy.service: main process exited, code=exited, status=226/NAMESPACE
Feb 21 09:31:12 vultr.guest systemd[1]: Unit caddy.service entered failed state.
Feb 21 09:31:12 vultr.guest systemd[1]: caddy.service failed.
Feb 21 09:31:12 vultr.guest systemd[1]: caddy.service holdoff time over, scheduling restart.
Feb 21 09:31:12 vultr.guest systemd[1]: Stopped Caddy HTTP/2 web server.
Feb 21 09:31:12 vultr.guest systemd[1]: Started Caddy HTTP/2 web server.
Feb 21 09:31:12 vultr.guest systemd[1]: caddy.service: main process exited, code=exited, status=226/NAMESPACE
Feb 21 09:31:12 vultr.guest systemd[1]: Unit caddy.service entered failed state.
Feb 21 09:31:12 vultr.guest systemd[1]: caddy.service failed.
Feb 21 09:31:13 vultr.guest systemd[1]: caddy.service holdoff time over, scheduling restart.
Feb 21 09:31:13 vultr.guest systemd[1]: Stopped Caddy HTTP/2 web server.
Feb 21 09:31:13 vultr.guest systemd[1]: Started Caddy HTTP/2 web server.
Feb 21 09:31:13 vultr.guest systemd[1]: caddy.service: main process exited, code=exited, status=226/NAMESPACE
Feb 21 09:31:13 vultr.guest systemd[1]: Unit caddy.service entered failed state.
Feb 21 09:31:13 vultr.guest systemd[1]: caddy.service failed.
Feb 21 09:31:13 vultr.guest systemd[1]: caddy.service holdoff time over, scheduling restart.
Feb 21 09:31:13 vultr.guest systemd[1]: Stopped Caddy HTTP/2 web server.
Feb 21 09:31:13 vultr.guest systemd[1]: start request repeated too quickly for caddy.service
Feb 21 09:31:13 vultr.guest systemd[1]: Failed to start Caddy HTTP/2 web server.
Feb 21 09:31:13 vultr.guest systemd[1]: Unit caddy.service entered failed state.`
什么问题啊
