### ISSUE TITLE
[Suggestion]TLS支持其他端口(Caddy)

### ISSUE THREAD

**Issue by momentforever** [233boy/v2ray#1146]
[场景]
443端口ban
[解决方法]
```caddy
www.domain.com:[port]{
  reverse_proxy ...
}
```
在port处填写自己的端口则可改变代理端口
[我的建议]
请在``修改配置``里添加``更改端口``选项，即修改caddy代理端口.
[实现逻辑]
1. 替换端口caddyfile中端口
2. 重载caddyfile文件

**Comment by viquu** [comment]
同求，持续使用好几年了，这2天突然把我443给Ban了

**Comment by 233boy** [comment]
@viquu @momentforever 

好了。

https://github.com/233boy/v2ray/releases/tag/v4.10

**Comment by viquu** [comment]
效率太高了👍

the_moment_forever ***@***.***>于2023年6月8日 周四14:21写道：
