### ISSUE TITLE
v2ray json配置转 vmess

### ISSUE THREAD

**Issue by XuanRanDev** [233boy/v2ray#1157]
您好，想向您询问一个与此项目关系并不大问题，我想知道您是怎样把v2ray的json配置文件转成vmess://xxxxxxxxxxx这种形式的，我在此之前通过询问ChatGPT和在网上搜索都没有结果，我听说把配置导入到v2rayNG然后再分享就可以了，但是经过我的尝试导入配置文件的形式只能导出配置文件，没有其他选项，然后我就想查看源码是怎么做到的，奈何我实在不会shell，无奈才提出疑问。

**Comment by XuanRanDev** [comment]
网上那些在线转换也只提供vmess//ss/这些转换的

**Comment by 233boy** [comment]
@XuanRanDev 

用电脑版本的 v2rayN，导入之后，再在主界面选择，分享，就会有链接了，

我不太清楚你的 json 是怎么形式的，你可以尝试使用 v2ray gen tcp 来看看我脚本返回的 json，对比一下；

然后你可以把 json 保存到 /etc/v2ray/conf/xxx.json，之后尝试使用脚本来生成 v2ray url xxx

备注，不确保脚本能完全正常读取你的 json 配置

**Comment by XuanRanDev** [comment]
> @XuanRanDev
> 
> 用电脑版本的 v2rayN，导入之后，再在主界面选择，分享，就会有链接了，
> 
> 我不太清楚你的 json 是怎么形式的，你可以尝试使用 v2ray gen tcp 来看看我脚本返回的 json，对比一下；
> 
> 然后你可以把 json 保存到 /etc/v2ray/conf/xxx.json，之后尝试使用脚本来生成 v2ray url xxx
> 
> 备注，不确保脚本能完全正常读取你的 json 配置

好的谢谢
