### ISSUE TITLE
请问证书放哪里

### ISSUE THREAD

**Issue by davidwlhuang** [233boy/v2ray#1159]
我想v2ray和ocserv 共存，其中ocserv使用233boy脚本从letsencrypt生成的密钥，请问密钥放哪里？

**Comment by 233boy** [comment]
@davidwlhuang 

放在 /root/.local/share/caddy/certificates/acme-v02.api.letsencrypt.org-directory

**Comment by davidwlhuang** [comment]
感谢大神。找到了！
