### ISSUE TITLE
新版本：Cloudfare 可以自由代理方式访问吗，如何实现

### ISSUE THREAD

**Issue by aaamber323** [233boy/v2ray#1163]
新版本脚本安装提示，要求解析只能到VPS的IP，不可以用自由代理，这个有办法解决不？目前倒是可以翻墙，有局限性，一切换到手机的移动网络无法翻。

**Comment by 233boy** [comment]
@aaamber323 

那个只是一个检测，先点灰云朵，通过检测之后，脚本生成了配置，然后你再点亮云朵，那就是套 CF 了。

**Comment by aaamber323** [comment]
点亮之后，解析的地址变了，访问进不来，访问日志里没新的访问信息。

**Comment by Martin-dq** [comment]
172.71.178.194:0 rejected  common/drain: common/drain: unable to drain connection > read tcp 127.0.0.1:30599->127.0.0.1:39540: i/o timeout > proxy/vmess/encoding: invalid user > proxy/vmess: Not Found
对的，我的CF套用后，会不定时显示这个， 172.71.178.194就是CF的IP

**Comment by Martin-dq** [comment]
找到原因了，是本地时间和服务器时间不匹配

**Comment by aaamber323** [comment]
时间不匹配的情况应该一直没翻成功过吧？我这是换了CF自由线路不通，解析到VPS翻是没问题的。

**Comment by Martin-dq** [comment]
vps后台v2ray命令选择9，查看连接日志，我的明显显示reject，另外就是再换一个域名解析，CF那里我也是一样，一个域名开始正常开了代理后也正常，但是一段时间后就只有连接记录没有数据，换一个域名不开代理就一直没问题

**Comment by aaamber323** [comment]
> Martin-dq
我想应该是要调整下新版本配置文件里的路由规则。

**Comment by aaamber323** [comment]
代理打开后面耐心等个几分钟之后测一下，访问是可以了。
