### ISSUE TITLE
安装后实际服务并没有启动

### ISSUE THREAD

**Issue by limuy2022** [233boy/v2ray#1166]
安装后使用netstat -tunlp |grep和lsof均没有发现任何进程使用端口，使用https://ping.sx/check-port 判断端口均为unreachable，简单编写以下python程序监听端口后，变为reachable，我猜测是因为某些原因导致v2ray实际并没有启动
```python
import socket
s=socket.socket()
s.bind(("ip_addr",port))
s.listen(5)
```

**Comment by 233boy** [comment]
@limuy2022 

执行 v2ray test
