### ISSUE TITLE
配置完成后依旧无法联网

### ISSUE THREAD

**Issue by Ariki28** [233boy/v2ray#118]
vultr centOS 7
按照脚本配置后依旧无法连接外网，报错如下
[Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 202.xxx.xxx.126:8010: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.] > v2ray.com/core/common/retry: all retry attempts failed

之前使用SSR客户端没有任何问题

**Comment by 233boy** [comment]
@Ariki28 
服务器输入 `v2ray status` 看看有没有在运行啊

**Comment by Ariki28** [comment]
已解决，是TCP阻断的问题。
还有建议在脚本内添加打开CentOS防火墙的脚本。

**Comment by colemanlee** [comment]
> 已解决，是TCP阻断的问题。
> 还有建议在脚本内添加打开CentOS防火墙的脚本。

TCP阻断的问题怎么解决?
