### ISSUE TITLE
关于流量伪装的问题

### ISSUE THREAD

**Issue by pureGavin** [233boy/v2ray#1182]
一直在使用你的脚本，今天尝试安装新的服务端的时候发现脚本更新了，和之前的不一样了，有几个小问题
之前我一直使用tcp+动态端口+http伪装，未更新之前的安装页面是这样的
![图片](https://github.com/233boy/v2ray/assets/45478229/4d95a691-75f8-4c1e-9539-76a385380d1d)
更新后的脚本选项更多了，也不知道和之前的服务端配置是否有不同，从客户端的自动配置来看，http伪装不会自动选择baidu.com了，即使手动加上了，从客户端配置文件来看，也没有http的必要信息
![图片](https://github.com/233boy/v2ray/assets/45478229/6c053618-5ed9-4f6c-a933-addddb26f437)

**Comment by 233boy** [comment]
@pureGavin 

这个客户端有选项配置的，就是 host  这些，有需求的话，可以配置一下

**Comment by pureGavin** [comment]
> @pureGavin
> 
> 这个客户端有选项配置的，就是 host 这些，有需求的话，可以配置一下

感谢回复，或许我描述的不太清楚
我的疑问是，只有客户端配置了User-Agent之类的字段有用么？在服务端不需要额外配置一些内容么？我对v2ray的http伪装不太了解，这个伪装是在客户端封包，然后在服务端进行解包么？

**Comment by 233boy** [comment]
@pureGavin 

服务器那边可以不用管（不管我没实测过），你直接在客户端配置就行了，这个 HTTP 伪装，有些人用来弄免流，就是有些运营商会有一些特定的 HOST 可以免流的，在伪装 HOST 那边写这个 HOST 就能免流

**Comment by pureGavin** [comment]
> @pureGavin
> 
> 服务器那边可以不用管（不过我没实测过），你直接在客户端配置就行了，这个 HTTP 伪装，有些人用来弄免流，就是有些运营商会有一些特定的 HOST 可以免流的，在伪装 HOST 那边写这个 HOST 就能免流

可否将原来的配置应用到现在的脚本中，从我实测来看，旧版的http伪装即使是在敏感时期，也可以很好的保证IP不被封

**Comment by 233boy** [comment]
@pureGavin 

你把之前的配置备份，然后如果是用了新脚本，配置在 /etc/v2ray/conf/，找到 http 端口相同的配置，把他替换一下就行

**Comment by pureGavin** [comment]
> @pureGavin
> 
> 你把之前的配置备份，然后如果是用了新脚本，配置在 /etc/v2ray/conf/，找到 http 端口相同的配置，把他替换一下就行

有没有办法在安装文件中就直接做出来啊？自己手动改的话，因为对配置文件和项目不了解，怕会改废

**Comment by pureGavin** [comment]
@233boy 我有个小问题，当初更新安装脚本的时候，为什么把原来的http伪装那部分给删了啊？

**Comment by pureGavin** [comment]
@233boy 
请问，如果要自己加http请求头的其他内容的话，服务端需要配置什么内容吗？

**Comment by pureGavin** [comment]
根据本人简单测试，在客户端修改http请求头内容，服务端并不需要修改任何内容，故此issue关闭，如有敏感时期封IP的情况，再另开issue
