### ISSUE TITLE
connection reset by peer transport/internet/websocket

### ISSUE THREAD

**Issue by chinese-wzq** [233boy/v2ray#1183]
[I] [io.go:429]  [Warning] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://nice.测试.测试/测试测试测试测试)
测试真连接速度的时候这样提示。服务端使用VMess-WS-TLS，但不知道为什么换了很多个ip和域名都不行，测试都是连接已重置。有老哥知道这是为什么吗？而且套cloudflare也是连接已重置。
不过ssh连接一直都能连上，难道是墙进化出了精准识别流量的能力了吗？

-------------- VMess-WS-TLS-nice.测试.测试.json -------------
协议 (protocol)         = vmess
地址 (address)          = nice.测试.测试
端口 (port)             = 443
用户ID (id)             = 测试测试测试测试
传输协议 (network)      = ws
伪装域名 (host)         = nice.测试.测试
路径 (path)             = /测试测试测试测试
传输层安全 (TLS)        = tls

**Comment by Zeyu-ZEYU** [comment]
检查下VPS 80和443端口是否可用

**Comment by chinese-wzq** [comment]
都可用。在外网直接访问https://nice.测试.测试 是空白页

**Comment by chinese-wzq** [comment]
![图片](https://github.com/233boy/v2ray/assets/40971680/399048ef-83e1-4cb4-b6cb-3a7dee085f0a)

**Comment by chinese-wzq** [comment]
更奇怪的是在浏览器刷新很多次后就可以打开一次https://nice.测试.测试，说明没有完全被墙

**Comment by Zeyu-ZEYU** [comment]
要从国内telnet试下80和443是否被禁，不是查看入站规则

**Comment by Zeyu-ZEYU** [comment]
> 更奇怪的是在浏览器刷新很多次后就可以打开一次[https://nice.测试.测试](https://nice.%E6%B5%8B%E8%AF%95.%E6%B5%8B%E8%AF%95) ，说明没有完全被墙

网也能访问就得看分流的时候有没有问题了

**Comment by chinese-wzq** [comment]
![图片](https://github.com/233boy/v2ray/assets/40971680/2351a9a7-198b-45db-a907-8b497322e558)
telent是可以连接上端口的

**Comment by chinese-wzq** [comment]
最新消息，换了宽带后再搞个新的子域名，然后套上cloudflare CDN，发现直接访问就不会被重置了。
怀疑是GFW只要检测到我原来的ip访问`测试.测试`的任何子域名就都拉入黑名单，但是只要我换个ip访问`新的`子域名就不会再被拉入黑名单
