### ISSUE TITLE
怎么修改alterId

### ISSUE THREAD

**Issue by IptablesNat** [233boy/v2ray#119]
到底怎么修改alterId，
为什么我把config.json和233blog_v2ray_config.json中alterId数值都改了，restart之后alterId还是233.。
***********************************************
就在刚刚试出来了，原来是修改脚本配置文件
233blog_v2ray_backup.conf

**Comment by myworksfun** [comment]
楼上正解，刚测试了一下，thank you ！

**Comment by andyliang007008** [comment]
233blog_v2ray_backup.conf路径在哪里？
