### ISSUE TITLE
获取服务器 IP 失败

### ISSUE THREAD

**Issue by Eison9** [233boy/v2ray#1193]
![获取服务器 IP 失败](https://github.com/233boy/v2ray/assets/43535121/ec236b04-475a-466e-a116-b908b6400946)

复现：
原debian10系统安装过脚本，在脚本未卸载的情况下，直接重装系统，再次安装，就出现 `获取服务器IP失败` 提示，无法安装

**Comment by NMS-LemonTec** [comment]
我debian11也遇到了同样的问题！就在刚刚

**Comment by 233boy** [comment]
@Eison9 @NMS-LemonTec 

执行这个再安装：
export ip=$(curl ip.me)
