### ISSUE TITLE
如何解决‘unsupported address for router: geoip:cn’？

### ISSUE THREAD

**Issue by luckypoem** [233boy/v2ray#12]
hi.

yudeMacBook-Air:v2ray-ar brite$ ls
233blog_v2ray_config.json
MTQ2NjctMzkyMi0yMjM4MAo=_233blog_v2ray.zip
yudeMacBook-Air:v2ray-ar brite$ mv 233blog_v2ray_config.json config.json
yudeMacBook-Air:v2ray-ar brite$ ls
MTQ2NjctMzkyMi0yMjM4MAo=_233blog_v2ray.zip
config.json
yudeMacBook-Air:v2ray-ar brite$ v2ray -config config.json
V2Ray v2.41 (One for all) 20171014
An unified platform for anti-censorship.
Main: failed to read config file: config.json > Ext|Tools|Conf|Serial: failed to parse json config > Ext|Tools|Conf: invalid field rule > Ext|Tools|Conf: invalid IP: geoip:cn > Ext|Tools|Conf: unsupported address for router: geoip:cn
yudeMacBook-Air:v2ray-ar brite$
谢谢你

**Comment by liyafly** [comment]
快用新版 v2ray吧 新版解决一切问题

**Comment by 2016adley** [comment]
Type: v2ray update, everything is normal after the update

**Comment by TrizontiBaL6** [comment]
你的v2ray core版本过低，请使用新版客户端内核

**Comment by luckypoem** [comment]
无效啊

**Comment by liyafly** [comment]
下载最新的 v2ray macos 客户端的内核 并全部解压 后 编辑 JSON文件 再用 内核联网  此外 可以使用 v2ray的 Mac客户端 V2RayX 也很好用配置也简单

**Comment by yuanyue456** [comment]
解压所有的东西

**Comment by luckypoem** [comment]
原来是因为：本地机器的时间要跟北京时间一致！！误差不能超过2分钟，否则会翻墙失败！！
