### ISSUE TITLE
生成ss二维码地址的后缀为pg，改成png后可以下载

### ISSUE THREAD

**Issue by ThunderKO9** [233boy/v2ray#121]
虽然不是什么大问题，不过还是改一下吧。刚开始的时候我还想着出于小体积，应该是jpg，没想到是png

**Comment by ThunderKO9** [comment]
至于v2ray qr生成的二维码，查看该元素header的status code则是404 not found，

**Comment by 233boy** [comment]
> 至于v2ray qr生成的二维码，查看该元素header的status code则是404 not found，

可能是生成网站那边 的问题。。我测试了一下没事啊 😂
