### ISSUE TITLE
感谢hub主提供的v2ray文章

### ISSUE THREAD

**Issue by forReak** [233boy/v2ray#122]
已根据文章成功配置v2ray并开启Cloudflare 中转 V2Ray WebSocket

**Comment by forReak** [comment]
我需要在服务器上进行搭建我的网站。看到caddy占用了80，修改caddyfile 添加反向代理的时候caddy一直起不起来，请问一下是什么原因？
具体的caddyfile 如下：
www.furaov2ray.top {
    tls 135807369216@gmail.com
timeouts none
proxy / 127.0.0.1:12345 {
websocket
}
}

furao.xyz{
gzip
proxy / 127.0.0.1:8080
}

import sites/*

**Comment by myworksfun** [comment]
你的首页还是“bad  request “，这是套CDN的结果。

**Comment by forReak** [comment]
@myworksfun 第一个域名是用于v2ray的，本来就是bad request，出问题的是第二个域名转发。现在已经修复了，谢谢。域名后面和花括号中间必须要有空格。我因为没有加空格导致caddy不识别配置文件

**Comment by myworksfun** [comment]
ok ,了解，我也试一下，看看能不能成功。谢谢~

for_reak <notifications@github.com> 于2019年2月22日周五 上午10:52写道：

**Comment by 233boy** [comment]
@forReak 
建议将其他网站的配置放到 `/etc/caddy/sites` 目录下，而不是修改 caddyfile 文件
例如 `/etc/caddy/sites/furao.xyz`
然后内容如下 ：
```
furao.xyz {
gzip
proxy / 127.0.0.1:8080
}
```

**Comment by forReak** [comment]
@233boy 明白了，非常感谢，一开始我还没看懂你为什么要在最后写一句` import sites/*` 大佬还是大佬，谢谢👍

**Comment by HandsomeLiu233** [comment]
非常感谢！
