### ISSUE TITLE
不合理的工作逻辑: 不是自动配置 TLS 的 WebSocket 不支持设置分流路径 (wsSettings.path)

### ISSUE THREAD

**Issue by ZHLONG-CN** [233boy/v2ray#1221]
因为域名有其他业务, 需要在同一个域名指定一个特定的路径给 v2ray. 可用 80 和 443 端口访问.

我需要在 nginx 写一个 location 给 v2ray 反代, 我还需要去修改 `/etc/v2ray/config.json`, 设置 `wsSettings: { path }` 与 location 相同的路径. 

在脚本管理中则无法在这种情况下设置 `wsSettings: { path }` .

**Comment by 233boy** [comment]
@ZHLONG-CN 

脚本是哪个版本啊？如果新版本你可以设置的，

如果你使用新版本 （v4+） 你可以在添加前先临时自定义一个路径；使用命令  `export path=/233`；

然后再使用 v2ray no-auto-tls  添加配置

**Comment by ZHLONG-CN** [comment]
啊看到版本是`........... V2Ray 管理脚本 v3.65 by 233v2.com ..........`

管理脚本更新失败了, 我刚重新从 `https://git.io/v2ray.sh` 安装了一遍, 现在可以用了.
