### ISSUE TITLE
[bug]kcp不通

### ISSUE THREAD

**Issue by YaeSakuraQvQ** [233boy/v2ray#1223]
53端口跑tcp可通，kcp就真连接-1

另:建议加个vless+kcp

**Comment by 233boy** [comment]
@YaeSakuraQvQ 

kcp 不通很有可能端口问题或者 UDP 防火墙开放等

vless kcp 这种配合暂时不考虑

**Comment by YaeSakuraQvQ** [comment]
好吧...
不过我防火墙的端口打开了，而且用其他工具(不是xray类的)走53 udp可通，感觉不是我端口或防火墙的问题

233boy ***@***.***> 于2023年10月14日周六 10:18写道：

**Comment by renxi-jack** [comment]
最后怎么解决的
