### ISSUE TITLE
错误! 获取服务器 IP 失败

### ISSUE THREAD

**Issue by ryc111** [233boy/v2ray#1224]
环境是国内的机器，尝试使用转发，然后获取IP失败。
`v2ray add door port dest_ip dest_port`

建议加个变量由用户输入IP，作为fallback。
比如先让用户定义
```
IP_ADDR=xxx.xxx.xxx.xxx
v2ray ...
```

**Comment by 233boy** [comment]
@ryc111 

首先不建议用在国内安装，其次你可以自定义 IP 的；使用：

```
export ip=1.2.3.4
```

**Comment by ryc111** [comment]
> @ryc111
> 
> 首先不建议用在国内安装，其次你可以自定义 IP 的；使用：
> 
> ```
> export ip=1.2.3.4
> ```

感谢，这样我运行 `v2ray add door ...` 就没问题了。

的确这个脚本没法在国内。直接安装。所有的下载地址都没法直接用
