### ISSUE TITLE
OpenAi 默认走direct

### ISSUE THREAD

**Issue by yujular** [233boy/v2ray#1242]
4.15版本的config里加了openai的配置且outbound默认走direct，如果仅在/etc/v2ray/conf里设置warp分流的话会被覆盖，openai还是走direct诶，好像需要把默认配置注释掉才能用warp代理。是否应该在脚本里去掉/etc/v2ray/config.json针对Openai的默认配置

**Comment by 233boy** [comment]
你要是觉得有问题就手动去掉就好了。

因为就是有人反馈有问题才加这个配置，现在又有人说加了这个有问题，我TMD 真的是服。

**Comment by yujular** [comment]
> 你要是觉得有问题就手动去掉就好了。
> 
> 因为就是有人反馈有问题才加这个配置，现在又有人说加了这个有问题，我TMD 真的是服。

好的好的 因为按照之前的issue调了好久才发现这个qaq 麻烦您了
