### ISSUE TITLE
怎么在同个端口新增不同id呀？

### ISSUE THREAD

**Issue by tomcat2023001** [233boy/v2ray#1258]
单个端口单个id可以用。就是同个端口id超过一个，只能认第一个id。
这是代码做配置转换只认第一个id吧？
就是有个需求 同个端口，多个用户Id用来上上网

**Comment by 233boy** [comment]
@tomcat2023001 

脚本暂时没法实现这个，只能多个不同配置，其实这个脚本偏向个人使用，而不是弄类似机场的作用

**Comment by tomcat2023001** [comment]
好的，了解了。我的几台设备开了不同端口不同配置来实现科学上网了
