### ISSUE TITLE
域名已经解析，但是输入v2ray add ws操作后，提示域名未解析

### ISSUE THREAD

**Issue by Ben1211234** [233boy/v2ray#1262]
您好，
域名已经解析，但是输入v2ray add ws操作后，提示域名未解析，多次操作仍旧一样。添加不上域名，无法弄伪装类型。
该怎么办，希望您有空解答。谢谢！

**Comment by 233boy** [comment]
@Ben1211234 

那你确定有正确解析了吗？如果是使用 CF，你得把云朵图标点灰；

**Comment by Ben1211234** [comment]
> @Ben1211234
> 
> 那你确定有正确解析了吗？如果是使用 CF，你得把云朵图标点灰；

谢谢回复。我用的购买的vps解析的。已经正确解析。域名joki.top
谢谢！

**Comment by Ben1211234** [comment]
> @Ben1211234
> 
> 那你确定有正确解析了吗？如果是使用 CF，你得把云朵图标点灰；

您好，我更换到cf做了解析，现在完全可以使用了。十分感谢！
