### ISSUE TITLE
geosite 、geoip在哪个目录

### ISSUE THREAD

**Issue by hasingzy** [233boy/v2ray#1264]
大佬你好，请问geosite 、geoip在哪个目录？

**Comment by 233boy** [comment]
@hasingzy 

/etc/v2ray/bin

**Comment by hasingzy** [comment]
谢谢，找到了> @hasingzy 
> 
> 
> 
> /etc/v2ray/bin

**Comment by hasingzy** [comment]
@233boy 谢谢，找到了！
