### ISSUE TITLE
请问能修改服务端的dns吗？

### ISSUE THREAD

**Issue by anonymousbone** [233boy/v2ray#127]
请教一下如何修改233大的v2ray的dns啊？
发现无法用 vim ect/v2ray/config.json 这句命令
Google的dns我这里不好用，不知233大的版本是不是用Google dns的，我想换成4个1的dns，感觉这个dns贼快还贼稳定。

**Comment by 233boy** [comment]
@LaurenceSamael 
已经默认使用 1.1.1.1 作为 DNS 了。
如果你的配置文件不是，请先使用 `v2ray update.sh` 更新脚本之后，再使用 `v2ray reload`  命令更新一下配置文件即可。
就会使用 1.1.1.1 作为默认 DNS 了
