### ISSUE TITLE
/dev/fd/63: No such file or directory

### ISSUE THREAD

**Issue by hyzx86** [233boy/v2ray#1283]
执行 sudo  bash <(curl -s -L https://git.io/v2ray.sh)
提示 `/dev/fd/63: No such file or directory`

**Comment by 233boy** [comment]
@hyzx86 

不能 sudo 带安装命令。。。

sudo -i 切 root 后再装

**Comment by hyzx86** [comment]
搞定了哈  sudo bash < <(curl -s -L https://git.io/v2ray.sh)
两个尖括号就行了
