### ISSUE TITLE
有没有老哥帮忙解答下,使用vultr的服务器搭建，某些网站会被拦截咋整

### ISSUE THREAD

**Issue by SeeMi157** [233boy/v2ray#1284]
如题如图
有的网站直接被拦截了，进不去，是要设置个啥吗，还是说就是vultr的服务器问题，我之前用的别的服务器商都没出现过这个问题

![1709820613742](https://github.com/233boy/v2ray/assets/158467514/2a210125-2415-454c-bfb0-0bcffbdbba58)

**Comment by PhiBrain-ZhaoLiang** [comment]
就是这个服务器全被屏蔽了，换一家吧，建议BWG

**Comment by SeeMi157** [comment]
> 就是这个服务器全被屏蔽了，换一家吧，建议BWG

个人用，搬瓦工太贵了，玩不起

**Comment by enjoyment1314** [comment]
还有别的好多vps，越贵使用的人越少，你能访问的网站就越多，越便宜，门槛就越低，用的人就多，干啥的都有，所以你就用不了了，就是这么简单的道理。

**Comment by lintianyuan666** [comment]
> 就是这个服务器全被屏蔽了，换一家吧，建议BWG

搬瓦工ip几天就被墙
