### ISSUE TITLE
安装完脚本后再安装oneinstack集成的nginx+php的服务器环境后就不能用了

### ISSUE THREAD

**Issue by airflybusoren** [233boy/v2ray#130]
如题,如果有空的话能不能抽空帮忙看一下,集成环境的安装地址https://oneinstack.com/install/

**Comment by 233boy** [comment]
@airflybusoren 
你是不是端口冲突了。。
比如说使用 ws+tls / http2 。

**Comment by airflybusoren** [comment]
用的是模式安装的

233boy <notifications@github.com> 於 2019年2月24日 週日 12:47 寫道：

**Comment by 233boy** [comment]
@airflybusoren 
什么鬼。。。
我问你是不是端口冲突了

**Comment by airflybusoren** [comment]
打错了，选的都是默认选项，应该不会冲突才对，晚点我看看

233boy <notifications@github.com> 於 2019年2月24日 週日 12:51 寫道：
