### ISSUE TITLE
伪装网址疑惑

### ISSUE THREAD

**Issue by 3wwjk4one** [233boy/v2ray#1312]
你好，我发现伪装网址有个问题，有些网址设置之后，直接访问自己的域名后显示的是伪装网址的页面，浏览器地址栏仍然正常显示自己的域名，但有些网址设置之后，浏览器再次访问自己域名会强制重定向到伪装网址，一直无法实现用自己域名加载伪装网页，请问是bug吗？

**Comment by 233boy** [comment]
@3wwjk4one 不是 bug 而是Feature！这是因为某些网站做了检测，不想被别人反代

**Comment by 3wwjk4one** [comment]
> @3wwjk4one 不是 bug 而是Feature！这是因为某些网站做了检测，不想被别人反代

完美解答！感谢！
