### ISSUE TITLE
caddy 没有自动配置证书

### ISSUE THREAD

**Issue by 1470429149** [233boy/v2ray#1313]

**Comment by 1470429149** [comment]
当脚本输出如下内容时，证书没有正确配置，客户端提示
2024/05/16 08:44:59 [Warning] [1673893901] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://xymmorpg.store/f54f8c1b-192c-499c-b203-f5e5697be8eb):  > remote error: tls: internal error] > common/retry: all retry attempts failed
------------------------------------------------
安装 Caddy 实现自动配置 TLS.

--2024-05-16 08:44:21--  https://github.com/caddyserver/caddy/releases/download/v2.7.6/caddy_2.7.6_linux_amd64.tar.gz
Resolving github.com (github.com)... 140.82.116.3
Connecting to github.com (github.com)|140.82.116.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/29207621/34503c5b-f603-49b3-a7ef-3b3857e78979?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240516%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240516T004421Z&X-Amz-Expires=300&X-Amz-Signature=cdabed5741dbfc0500307e34431d145e35c9abfaea66dacb10d7c65f8e3dbee3&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=29207621&response-content-disposition=attachment%3B%20filename%3Dcaddy_2.7.6_linux_amd64.tar.gz&response-content-type=application%2Foctet-stream [following]
--2024-05-16 08:44:22--  https://objects.githubusercontent.com/github-production-release-asset-2e65be/29207621/34503c5b-f603-49b3-a7ef-3b3857e78979?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240516%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240516T004421Z&X-Amz-Expires=300&X-Amz-Signature=cdabed5741dbfc0500307e34431d145e35c9abfaea66dacb10d7c65f8e3dbee3&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=29207621&response-content-disposition=attachment%3B%20filename%3Dcaddy_2.7.6_linux_amd64.tar.gz&response-content-type=application%2Foctet-stream
Resolving objects.githubusercontent.com (objects.githubusercontent.com)... 185.199.111.133, 185.199.109.133, 185.199.108.133, ...
Connecting to objects.githubusercontent.com (objects.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14655532 (14M) [application/octet-stream]
Saving to: ‘/tmp/tmp.5xxTja09m8/caddy.tar.gz’

/tmp/tmp.5xxTja09m8/cadd 100%[=================================>]  13.98M  3.25MB/s    in 4.2s    

2024-05-16 08:44:26 (3.29 MB/s) - ‘/tmp/tmp.5xxTja09m8/caddy.tar.gz’ saved [14655532/14655532]

安装 Caddy 成功.

**Comment by 233boy** [comment]
申请证书可能会延迟，或者如果你重装次数过多，会限制申请
