### ISSUE TITLE
bash <(wget -qO- -o- https://git.io/v2ray.sh)

### ISSUE THREAD

**Issue by rilzi** [233boy/v2ray#1315]
<img width="1137" alt="截屏2024-05-21 15 45 07" src="https://github.com/233boy/v2ray/assets/132825918/b53ee3c0-15c6-4e52-afda-82f472da13d7">

**Comment by rilzi** [comment]
Operating system: Debian 9 x86_64  
vps service provider:bandwagonhost

**Comment by rilzi** [comment]
Failed to install dependent packages

**Comment by rilzi** [comment]
<img width="808" alt="截屏2024-05-22 03 05 09" src="https://github.com/233boy/v2ray/assets/132825918/fa74bf60-011a-417e-90a8-00b690358338">
still not working

**Comment by rilzi** [comment]
> pls try
> 
> ```
> apt update -y; apt install unzip
> ```
still not working

**Comment by 233boy** [comment]
@rilzi 

try this
```
apt update --fix-missing; apt install unzip
```
note, ubuntu 18+ is recommended, if this problem cant fix, just reinstall a new ubuntu 18+ system. (for vps ram <=1G, ubuntu 18 is better)

**Comment by rilzi** [comment]
> @rilzi
> 
> try this 试试这个
> 
> ```
> apt update --fix-missing; apt install unzip
> ```
> 
> note, ubuntu 18+ is recommended, if this problem cant fix, just reinstall a new ubuntu 18+ system. (for vps ram <=1G, ubuntu 18 is better)注意，建议使用 Ubuntu 18+，如果这个问题无法解决，只需重新安装新的 Ubuntu 18+ 系统即可。（对于 vps ram <=1G，ubuntu 18 更好）

Yeah switch to ubuntu 18+ to easily generate configuration files. For users with memory less than 1G, it is not suitable for Debian 9 systems. Thank you for helping me solve the problem. Respect

**Comment by rilzi** [comment]
> @rilzi
> 
> try this 试试这个
> 
> ```
> apt update --fix-missing; apt install unzip
> ```
> 
> note, ubuntu 18+ is recommended, if this problem cant fix, just reinstall a new ubuntu 18+ system. (for vps ram <=1G, ubuntu 18 is better)注意，建议使用 Ubuntu 18+，如果这个问题无法解决，只需重新安装新的 Ubuntu 18+ 系统即可。（对于 vps ram <=1G，ubuntu 18 更好）

I want to ask how to enable BBR acceleration when switching to Ubuntu. Is there any tutorial?

**Comment by 233boy** [comment]
use `v2ray bbr` to enable BBR
> I want to ask how to enable BBR acceleration when switching to Ubuntu. Is there any tutorial?
