### ISSUE TITLE
安装VMess-WS-TLS时，提示Caddy 运行失败

### ISSUE THREAD

**Issue by Hohenheimp** [233boy/v2ray#1319]
系统转着圈全换了一便最后都是这个提示
![微信截图_20240602155720](https://github.com/233boy/v2ray/assets/39020828/abf1ec93-9705-4c68-b4fb-47b7dc5c6fea)

**Comment by QQ200550002** [comment]
![微信图片编辑_20240602161221](https://github.com/233boy/v2ray/assets/8945403/ab13e5ad-8595-4209-b705-9eee73438510)
我的也是错误了

**Comment by QQ200550002** [comment]
系统都装遍啦 也搞不定

**Comment by Hohenheimp** [comment]
> 系统都装遍啦 也搞不定

我换了一个用Nginx的脚本能正常安装
https://github.com/wulabing/V2Ray_ws-tls_bash_onekey

**Comment by 233boy** [comment]
@QQ200550002 @Hohenheimp 

现在修复了，那是因为 caddy 脑残了
