### ISSUE TITLE
绑定域名后浏览器访问打开域名是空白页，在哪修改空白页的内容？

### ISSUE THREAD

**Issue by huangzhuohua** [233boy/v2ray#1322]
按照教程安装好了 VMess-WS-TLS，域名在浏览器可以打开，但是没有显示任何内容。我想修改一下这个显示，请问在哪里修改？

**Comment by huangzhuohua** [comment]
能够修改显示内容的话，可以看出更像是一个网站

**Comment by 233boy** [comment]
@huangzhuohua 

直接执行这个命令，也可以把后面的域名换成你想要反代的网站
```
v2ray web tls example.com
```

**Comment by huangzhuohua** [comment]
@233boy 这样的修改就是重定向到第三方网站，我的意思是如果能够直接修改的话，这样更加方便可控一些。

> @huangzhuohua
> 
> 直接执行这个命令，也可以把后面的域名换成你想要反代的网站
> 
> ```
> v2ray web tls example.com
> ```

**Comment by 233boy** [comment]
重定向到第三方网站，是你反代的网站的问题啊。你想要手动更改可以在 /etc/caddy/233boy/ 目录这里有 .add 配置，在 .add 后缀文件里面写 caddy 配置就行

**Comment by huangzhuohua** [comment]
> 重定向到第三方网站，是你反代的网站的问题啊。你想要手动更改可以在 /etc/caddy/233boy/ 目录这里有 .add 配置，在 .add 后缀文件里面写 caddy 配置就行

非常感谢 @233boy 回答。

但是我对caddy不是很熟悉，能否帮忙给出一个示例呢？例如我想用/home/web/index.html文件作为域名在浏览器打开时显示的内容，应该如何配置caddy呢？

**Comment by 233boy** [comment]
@huangzhuohua 在 .add 后缀的文件里面写 index /home/web/
