### ISSUE TITLE
安装上去了但是不能运行

### ISSUE THREAD

**Issue by yafully** [233boy/v2ray#1324]
V2Ray 运行失败信息:
V2Ray 5.16.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.22.2 linux/amd64)
A unified platform for anti-censorship.
2024/06/12 20:55:41 Using confdir from arg: /etc/v2ray/conf
Failed to start: app/proxyman/inbound: failed to listen TCP on 6938 > transport/internet: failed to listen on address: 127.0.0.1:6938 > transport/internet/tcp: failed to listen TCP on 127.0.0.1:6938 > listen tcp 127.0.0.1:6938: bind: address already in use

kill掉这个进程重新执行v2ray命令一样还是提示这个，怎么破？

**Comment by 233boy** [comment]
v2ray fix-config.json

**Comment by yafully** [comment]
无效，执行了这个命令依旧提示端口被占用。重启服务器也不行。
[root@VM_0_4_centos v2ray]# v2ray fix-config.json
[root@VM_0_4_centos v2ray]# 

警告! (重启) V2Ray 失败

检测到运行失败, 自动执行测试运行.

测试运行 V2Ray ..

V2Ray 运行失败信息:
V2Ray 5.16.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.22.2 linux/amd64)
A unified platform for anti-censorship.
2024/06/13 17:48:58 Using confdir from arg: /etc/v2ray/conf
Failed to start: app/proxyman/inbound: failed to listen TCP on 29962 > transport/internet: failed to listen on address: 127.0.0.1:29962 > transport/internet/tcp: failed to listen TCP on 127.0.0.1:29962 > listen tcp 127.0.0.1:29962: bind: address already in use

**Comment by yafully** [comment]
换这个就成功了，已科学上网。谢谢大佬。
