### ISSUE TITLE
跑完脚本 添加了VMESS+WS+TLS规则   客户端提示连不上

### ISSUE THREAD

**Issue by zmm2tysu** [233boy/v2ray#1327]
步骤
1. 跑完脚本
2. 添加了VMESS+WS+TLS规则
3. v2ray web tsl xxxxx设置了伪装网站
4. 客户端切换代理模式为pac或者自动

客户端老是提示这个，且不无法翻墙。
![image](https://github.com/233boy/v2ray/assets/20849786/d28964b9-7080-4577-bc11-13b6b0c1f23d)

请问接下来我该怎么排查问题？我现在不确定是不是证书问题还是我没有往caddy/sites下面放网站项目的问题

**Comment by zmm2tysu** [comment]
跑完脚本送的tcp配置是可以用的

**Comment by zmm2tysu** [comment]
话说这个VMESS+WS+TLS规则能一定程度上规避被墙的风险么？ 如果还是容易被墙的话 我就不折腾了  直接用送的tcp算了

**Comment by 233boy** [comment]
@zmm2tysu 证书没申请上吧，你直接打开你的这个域名看看是否正常（

**Comment by zmm2tysu** [comment]
@233boy 不需要建个网站放点东西么？  打开是这样的
![image](https://github.com/233boy/v2ray/assets/20849786/a75e90c3-068e-4969-b0f8-049218be01b5)

**Comment by 233boy** [comment]
@zmm2tysu 证书没申请下来你这个

**Comment by zmm2tysu** [comment]
@233boy 后面咋整啊？

**Comment by 233boy** [comment]
@zmm2tysu 搞不了啊，不清楚你这个怎么回事弄不了，你换一个顶级域名再来看看

**Comment by zmm2tysu** [comment]
@233boy 我reinstall了  添加了顶级域名的ws规则  还是连不上……

**Comment by feitisn** [comment]
@zmm2tysu @233boy caddy直接使用不会申请证书，不知道为啥，在Caddy中手动加一下tls的配置就可以解决这个问题

**Comment by 233boy** [comment]
@feitisn @zmm2tysu 
他默认是会自动申请证书的，不能申请无非就是，域名申请次数被限制了，或者如果你 caddy 不是运行80-443 端口可能会无法正常申请，就这样

**Comment by zmm2tysu** [comment]
@feitisn 这个怎么添加啊?方便指个路么  谢谢

**Comment by feitisn** [comment]
> @feitisn @zmm2tysu 他默认是会自动申请证书的，不能申请无非就是，域名申请次数被限制了，或者如果你 caddy 不是运行80-443 端口可能会无法正常申请，就这样

那还真是有可能

**Comment by feitisn** [comment]
> @feitisn 这个怎么添加啊?方便指个路么 谢谢

@zmm2tysu  /etc/caddy/233boy/example.com.add(域名)中添加 tls xx@mail.com(邮箱地址)，然后重启caddy就好了

**Comment by 233boy** [comment]
> > @feitisn 这个怎么添加啊?方便指个路么 谢谢
> 
> @zmm2tysu /etc/caddy/233boy/example.com.add(域名)中添加 tls [xx@mail.com](mailto:xx@mail.com)(邮箱地址)，然后重启caddy就好了

@feitisn 莫名其妙的，怎么又要tls 邮箱了

**Comment by pengneal** [comment]
> > > @feitisn 这个怎么添加啊?方便指个路么 谢谢
> > 
> > 
> > @zmm2tysu /etc/caddy/233boy/example.com.add(域名)中添加 tls [xx@mail.com](mailto:xx@mail.com)(邮箱地址)，然后重启caddy就好了
> 
> @feitisn 莫名其妙的，怎么又要tls 邮箱了

caddy没有自动申请证书 请问如何解决？

**Comment by 233boy** [comment]
@pengneal 你也手动添加一下配置看看？

**Comment by LeonChiew** [comment]
> > > @feitisn 这个怎么添加啊?方便指个路么 谢谢
> > 
> > 
> > @zmm2tysu /etc/caddy/233boy/example.com.add(域名)中添加 tls [xx@mail.com](mailto:xx@mail.com)(邮箱地址)，然后重启caddy就好了
> 
> @feitisn 莫名其妙的，怎么又要tls 邮箱了

很奇怪，新脚本没有安装证书，但是老脚本就没这个问题，安装上就有，好像不一定是caddy的问题

**Comment by lazydreamerbliss** [comment]
![image](https://github.com/233boy/v2ray/assets/8576808/592e06ad-4e5d-4fe0-8bd8-2fe472f4bd3d)

确实没有生成证书，而且路径和 doc （https://233boy.com/v2ray/caddy-auto-tls/）中提到的不一样，多了一个 `acme` 目录

**Comment by 233boy** [comment]
@lazydreamerbliss 路径没啥问题的，你也尝试在 /etc/caddy/233boy/*.add 里面添加 tls xxx@gmail.com 试试看

**Comment by lazydreamerbliss** [comment]
@233boy 非常感谢！在 .add 下添加邮箱即可，已经跑起来了

**Comment by feitisn** [comment]
> > > > @feitisn 这个怎么添加啊?方便指个路么 谢谢
> > > 
> > > 
> > > @zmm2tysu /etc/caddy/233boy/example.com.add(域名)中添加 tls [xx@mail.com](mailto:xx@mail.com)(邮箱地址)，然后重启caddy就好了
> > 
> > 
> > @feitisn 莫名其妙的，怎么又要tls 邮箱了
> 
> 很奇怪，新脚本没有安装证书，但是老脚本就没这个问题，安装上就有，好像不一定是caddy的问题
caddy通过letsencrypt无法下发证书了，通过ZeroSSL下发证书是必须要有邮箱作为账号的，所以添加邮箱后，caddy就可以正常申请了

**Comment by feitisn** [comment]
> > > > @feitisn 这个怎么添加啊?方便指个路么 谢谢
> > > 
> > > 
> > > @zmm2tysu /etc/caddy/233boy/example.com.add(域名)中添加 tls [xx@mail.com](mailto:xx@mail.com)(邮箱地址)，然后重启caddy就好了
> > 
> > 
> > @feitisn 莫名其妙的，怎么又要tls 邮箱了
> 
> 很奇怪，新脚本没有安装证书，但是老脚本就没这个问题，安装上就有，好像不一定是caddy的问题

caddy 通过 Let’s Encrypt无法下发证书了，通过ZeroSSL下发证书要有邮箱作为账号，所以在配置中添加邮箱后就可以正常下发证书了

**Comment by LeonChiew** [comment]
> > > > > @feitisn 这个怎么添加啊?方便指个路么 谢谢
> > > > 
> > > > 
> > > > @zmm2tysu /etc/caddy/233boy/example.com.add(域名)中添加 tls [xx@mail.com](mailto:xx@mail.com)(邮箱地址)，然后重启caddy就好了
> > > 
> > > 
> > > @feitisn 莫名其妙的，怎么又要tls 邮箱了
> > 
> > 
> > 很奇怪，新脚本没有安装证书，但是老脚本就没这个问题，安装上就有，好像不一定是caddy的问题
> 
> caddy 的 Let’s Encrypt 无法下发证书了，通过ZeroSSL下发证书要有邮箱作为账号，所以在配置中添加邮箱后就可以正常下发证书了

好吧那可能是版本的问题，可是我也曾尝试加过邮箱没生效，可以求个文件.add文件内容的截图吗大佬

**Comment by LeonChiew** [comment]
> > > > > @feitisn 这个怎么添加啊?方便指个路么 谢谢
> > > > 
> > > > 
> > > > @zmm2tysu /etc/caddy/233boy/example.com.add(域名)中添加 tls [xx@mail.com](mailto:xx@mail.com)(邮箱地址)，然后重启caddy就好了
> > > 
> > > 
> > > @feitisn 莫名其妙的，怎么又要tls 邮箱了
> > 
> > 
> > 很奇怪，新脚本没有安装证书，但是老脚本就没这个问题，安装上就有，好像不一定是caddy的问题
> 
> caddy 的 Let’s Encrypt 无法下发证书了，通过ZeroSSL下发证书要有邮箱作为账号，所以在配置中添加邮箱后就可以正常下发证书了

好吧那可能是版本的问题，可是我也曾尝试加过邮箱没生效，不知道是邮箱有地区要求还是我格式写的有问题，可以求个.add文件内容的截图吗大佬

**Comment by feitisn** [comment]
> > > > > > @feitisn 这个怎么添加啊?方便指个路么 谢谢
> > > > > 
> > > > > 
> > > > > @zmm2tysu /etc/caddy/233boy/example.com.add(域名)中添加 tls [xx@mail.com](mailto:xx@mail.com)(邮箱地址)，然后重启caddy就好了
> > > > 
> > > > 
> > > > @feitisn 莫名其妙的，怎么又要tls 邮箱了
> > > 
> > > 
> > > 很奇怪，新脚本没有安装证书，但是老脚本就没这个问题，安装上就有，好像不一定是caddy的问题
> > 
> > 
> > caddy 的 Let’s Encrypt 无法下发证书了，通过ZeroSSL下发证书要有邮箱作为账号，所以在配置中添加邮箱后就可以正常下发证书了
> 
> 好吧那可能是版本的问题，可是我也曾尝试加过邮箱没生效，不知道是邮箱有地区要求还是我格式写的有问题，可以求个.add文件内容的截图吗大佬

就是上面的配置，可能你那边于其它地方的问题吧

**Comment by LeonChiew** [comment]
> > > > > > > @feitisn 这个怎么添加啊?方便指个路么 谢谢
> > > > > > 
> > > > > > 
> > > > > > @zmm2tysu /etc/caddy/233boy/example.com.add(域名)中添加 tls [xx@mail.com](mailto:xx@mail.com)(邮箱地址)，然后重启caddy就好了
> > > > > 
> > > > > 
> > > > > @feitisn 莫名其妙的，怎么又要tls 邮箱了
> > > > 
> > > > 
> > > > 很奇怪，新脚本没有安装证书，但是老脚本就没这个问题，安装上就有，好像不一定是caddy的问题
> > > 
> > > 
> > > caddy 的 Let’s Encrypt 无法下发证书了，通过ZeroSSL下发证书要有邮箱作为账号，所以在配置中添加邮箱后就可以正常下发证书了
> > 
> > 
> > 好吧那可能是版本的问题，可是我也曾尝试加过邮箱没生效，不知道是邮箱有地区要求还是我格式写的有问题，可以求个.add文件内容的截图吗大佬
> 
> 就是上面的配置，可能你那边于其它地方的问题吧

![image](https://github.com/233boy/v2ray/assets/85923401/aaa6a685-a63d-4875-99e4-b5f30ba9676c)
是这样吧

**Comment by feitisn** [comment]
@LeonChiew 你把前面的#去除才生效的

**Comment by zmm2tysu** [comment]
> @233boy 非常感谢！在 .add 下添加邮箱即可，已经跑起来了

+1
