### ISSUE TITLE
请问国内网站无法访问是什么情况啊？

### ISSUE THREAD

**Issue by javasopp** [233boy/v2ray#1334]
请问下，vps部署v2ray成功了，使用v2rayN也能访问谷歌了，但是我在开启全局代理的情况下，访问自己搭建的第三方服务，部署在其他vps上，使用ip访问就无法访问，或者国内ip的服务器搭建了mq服务，也无法访问，可直接使用部署v2ray的vps的服务器是可以直接访问的。请问这个问题是什么原因呢？谢谢。
(特殊要求:必须要开启全局代理的模式去访问其他服务或者通过ip访问特定网站)

**Comment by 233boy** [comment]
。。。。
因为默认屏蔽国内啊，你不看说明？
把 /etc/v2ray/config.json 路由里面的 ban_geoip_cn 删除就行，或者把 block 更改成 direct；
