### ISSUE TITLE
请问如何使用脚本实现链式转发

### ISSUE THREAD

**Issue by Vateer** [233boy/v2ray#1337]
我有个香港的服务器A和美国的服务器B，在国内访问B比较困难，但使用A访问B会快点。请问脚本是否支持链式转发的快速配置，感谢回答。

**Comment by 233boy** [comment]
美国b 使用 `v2ray add tcp 123`
香港 a 使用 `v2ray add door 123 usip 123`，把 usip 更改成你美国的IP
客户端使用 美国b 的配置；但是把服务器地址更改成香港 a 即可

https://233boy.com/v2ray/v2ray-dokodemo-door/

**Comment by Vateer** [comment]
666，感谢作者回答，已经解决问题了
