### ISSUE TITLE
VMess-WS-TLS caddy没有自动生成证书是怎么回事？

### ISSUE THREAD

**Issue by zhiqiuyiye666** [233boy/v2ray#1345]
使用脚本创建完成后/root/.local/share/caddy 目录下没有这个文件夹请问如何手动生成证书呢？

**Comment by 233boy** [comment]
你是不是 top 域名啊，要不然就是得手动添加一个选项 tls xxx@gmail.com，在 /etc/caddy/233boy/*.add 里面添加

**Comment by zhiqiuyiye666** [comment]
> 你是不是 top 域名啊，要不然就是得手动添加一个选项 tls [xxx@gmail.com](mailto:xxx@gmail.com)，在 /etc/caddy/233boy/*.add 里面添加

是top域名 创建完后caddy没有自动生成证书，最后我又下了nginx+acme手动续签证书加到caddy解决了
