### ISSUE TITLE
为什么需要关闭selinux，客户端才不报 ：当前服务的真连接延迟: -1

### ISSUE THREAD

**Issue by lglgdouble** [233boy/v2ray#1359]
我按照你的步骤，关闭防火墙，ping端口，降低和客户端一样的版本号。然后客户端连接就报：当前服务的真连接延迟: -1

然后我就关闭 selinux 就可以了

客户端使用：v2rayN 6.55

系统信息：
 cat /etc/redhat-release
Rocky Linux release 9.4 (Blue Onyx)
[root@vultr ~]#

 uname -r
5.14.0-427.33.1.el9_4.x86_64
[root@vultr ~]#

**Comment by 233boy** [comment]
没有遇到过这个问题，也许是系统的问题，可以试试看 Ubuntu系统
