### ISSUE TITLE
请问NAT机器怎么配置？

### ISSUE THREAD

**Issue by 78775546946** [233boy/v2ray#136]
如题，上了NAT   VPS的车，用脚本哗啦哗啦下来并不能用，连接测试有延迟数值，请问应该怎么办呢？

**Comment by 78775546946** [comment]
希望作者可以在以后的版本中增加自动识别NAT机器公网IP得功能，毕竟现在NAT机器也挺火的，换了网上找的另一个脚本以后就能用。希望作者可以更新一下吧，感谢作者

**Comment by 78775546946** [comment]
配置环境，端口是商家指定端口范围中的，协议TCP_HTTP，

**Comment by 233boy** [comment]
@78775546946 
按理来说没有问题的。。。不知道你的操作方式。
配置端口为 NAT 允许的端口，应该就没有问题了，至于外网 IP，脚本可以识别的

**Comment by 78775546946** [comment]
好吧，我佛了，第一遍安装以后客户端报错，以为是脚本的锅，后来又来了一次，还报错，后来就来这里提交issue，后来就好了。不过真心感谢大佬的脚本

**Comment by sunsan05** [comment]
系统配置
```shell
sysctl -w net.ipv4.ip_forward=1
net.ipv4.ip_forwaed=1             //将此行中的0改为1
```
iPtables配置NAT
```shell
iptables -t nat -A POSTROUTING -s 192.168.1.0/24 -o ppp0 -j MASQUERADE   //因环境不同这里的写法会有微妙差异，具体可百度 iptables SNAT DNAT
```
