### ISSUE TITLE
求教，v2ray突然不能用了，测试ping有延迟，真连接延迟超时

### ISSUE THREAD

**Issue by ErbaoWang** [233boy/v2ray#1363]
如下报错，同步时间，换端口等方法都是，还是不好，求教是哪里出问题了，前几天手机用流量还能连上，这几天也不好了
因为IP被封了，用了CF套域名转接，域名是可以ping通的，cf中也改成了“完全”
2024/10/05 09:29:45 [Warning] [3380054836] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://www.742050289.top/9748d318-825b-476c-b690-2098b7e5e10e):  > read tcp 192.168.11.55:7610->172.67.128.94:443: i/o timeout v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://www.742050289.top/9748d318-825b-476c-b690-2098b7e5e10e):  > write tcp 192.168.11.55:7619->104.21.0.230:443: i/o timeout v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://www.742050289.top/9748d318-825b-476c-b690-2098b7e5e10e):  > read tcp 192.168.11.55:7620->172.67.128.94:443: i/o timeout v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://www.742050289.top/9748d318-825b-476c-b690-2098b7e5e10e):  > dial tcp 104.21.0.230:443: operation was canceled v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://www.742050289.top/9748d318-825b-476c-b690-2098b7e5e10e):  > dial tcp: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed

**Comment by ErbaoWang** [comment]
@233boy 大佬，求帮看下这种情况是怎么回事，重装了系统和v2ray都没效果

**Comment by 574885378** [comment]
我也出现了同样的问题,套的也是cf,可以测试ping但是测试真延迟全都是-1,反复测试了几遍,应该是可以用的,只是不能真连接测试了,一测就发现节点不能用了,过段时间又可以用了,什么原理我也没有搞明白,但是只要不测试真连接,通过测速来判断能不能使用还是可以继续正常用的

**Comment by 233boy** [comment]
> @233boy 大佬，求帮看下这种情况是怎么回事，重装了系统和v2ray都没效果

@ErbaoWang 你到 tcp.ping.pe 测试端口通不通，顺便说一下，不要用 top 域名，换其他的看看

**Comment by ErbaoWang** [comment]
@

> > @233boy 大佬，求帮看下这种情况是怎么回事，重装了系统和v2ray都没效果
> 
> @ErbaoWang 你到 tcp.ping.pe 测试端口通不通，顺便说一下，不要用 top 域名，换其他的看看

感谢大佬，果然是域名的问题，换了个就好了，之前域名能ping通过一直没考虑过他会有问题，非常感谢哈！！！

@574885378 参考一下，看看你那里是不是也是这个问题

**Comment by 574885378** [comment]
> @
> 
> > > @233boy 大佬，求帮看下这种情况是怎么回事，重装了系统和v2ray都没效果
> > 
> > 
> > @ErbaoWang 你到 tcp.ping.pe 测试端口通不通，顺便说一下，不要用 top 域名，换其他的看看
> 
> 感谢大佬，果然是域名的问题，换了个就好了，之前域名能ping通过一直没考虑过他会有问题，非常感谢哈！！！
> 
> @574885378 参考一下，看看你那里是不是也是这个问题

我是.one的域名,tcp.ping.pe测了全通,就是测真连接就断网几分钟,我现在不测真连接,只测速来使用也能正常用.有点迷

**Comment by ErbaoWang** [comment]
> > @
> > > > @233boy 大佬，求帮看下这种情况是怎么回事，重装了系统和v2ray都没效果
> > > 
> > > 
> > > @ErbaoWang 你到 tcp.ping.pe 测试端口通不通，顺便说一下，不要用 top 域名，换其他的看看
> > 
> > 
> > 感谢大佬，果然是域名的问题，换了个就好了，之前域名能ping通过一直没考虑过他会有问题，非常感谢哈！！！
> > @574885378 参考一下，看看你那里是不是也是这个问题
> 
> 我是.one的域名,tcp.ping.pe测了全通,就是测真连接就断网几分钟,我现在不测真连接,只测速来使用也能正常用.有点迷

能用就挺好，我刚装好时候也能正常用，后来某天突然不好了，可能是域名被限制了
