### ISSUE TITLE
不能生成二维码链接

### ISSUE THREAD

**Issue by abelfourier** [233boy/v2ray#137]
root@instance-5:~# v2ray qr
 正在生成链接.... 稍等片刻即可....
---------- V2Ray 二维码链接 -------------
 适用于 V2RayNG v0.4.1+ / Kitsunebi = **_Could not save metadata_**
 友情提醒: 请务必核对扫码结果 (V2RayNG 除外) 
 V2Ray 客户端使用教程: https://v2ray6.com/post/4/
备注...链接将在 14 天后失效
提醒...请不要把链接分享出去...除非你有特别的理由....

二维码链接应该出现在斜体黑体字那个地方，但显示的是不能保存元数据。
谷歌云的vm服务器，美国西部1区。

**Comment by abelfourier** [comment]
解决了，vm换了东亚区就行了。也许是服务器跨区不能通信。

**Comment by 233boy** [comment]
@abelfourier 
这个生成有时候会抽抽的。。。无解

**Comment by MichaelJokAr** [comment]
又出现了现在。怎么弄？谢谢
