### ISSUE TITLE
各位想装来翻墙的司机，系统请选择ubantu。。别选centos。。 血泪史。。

### ISSUE THREAD

**Issue by skiingman** [233boy/v2ray#138]
centos 默认会开启防火墙， 相同的配置在 ubantu可以翻墙， 在centos 却不行，  即便我关了防火墙也没用。。 坑死我了。。。。   换个系统 然后一键安装就搞定了。。  坑。。。

**Comment by 78775546946** [comment]
我都用的Debian9加上BBRPlus内核

**Comment by 233boy** [comment]
@skiingman 
建议 Debian9 。。。还可以自动打开 BBR。。。

**Comment by smartlin** [comment]
我去 我测centos7 安装完成后查看状态 一直都是未在运行，明明已经启动过了

**Comment by Zxilly** [comment]
centos我就没问题，firewalld多好用啊，人菜不要怪系统

**Comment by Lv-Max** [comment]
人菜不要怪系统

**Comment by dendil** [comment]
人菜不要怪系统+1

**Comment by abelfourier** [comment]
debian9 +1

**Comment by w3924686** [comment]
ubuntu比较适合新手

在 2019-03-03 01:08:35，"skiingman" <notifications@github.com> 写道：


centos 默认会开启防火墙， 相同的配置在 ubantu可以翻墙， 在centos 却不行， 即便我关了防火墙也没用。。 坑死我了。。。。 换个系统 然后一键安装就搞定了。。 坑。。。

**Comment by Scared-Heart** [comment]
我也遇到了 @skiingman 的问题，检查出来的问题是centos7的防火墙。
解决方法：1：关闭centos防火墙;百度命令
                  2：将设定的代理端口加入防火墙白名单(放行),tcp/ip ;百度命令
我用的是第二种，算是解决了这个坑。

**Comment by zhongmax** [comment]
我只能呵呵了

**Comment by KickUasS** [comment]
ubuntu我默认安装18.04脚本命令不兼容，提示

> centos 默认会开启防火墙， 相同的配置在 ubantu可以翻墙， 在centos 却不行， 即便我关了防火墙也没用。。 坑死我了。。。。 换个系统 然后一键安装就搞定了。。 坑。。。

UBUNTU你是用的什么安装？是不是选择了BASH?我默认安装，脚本各种报错，不能运行

**Comment by kong-ling-hui** [comment]
防火墙打开对应的端口就ok了
