### ISSUE TITLE
请问脚本有计划增加xhttp协议吗？我看内核已经抛出warning已经提示弃用ws和host了。

### ISSUE THREAD

**Issue by Nicolas-Gong** [233boy/v2ray#1387]
```
[Warning] common/errors: This feature WebSocket transport (with ALPN http/1.1, etc.) is deprecated and being migrated to XHTTP H2 & H3. Please update your config(s) according to release note and documentation before removal.

[Warning] common/errors: This feature "host" in "headers" is deprecated and being migrated to independent "host". Please update your config(s) according to release note and documentation before removal.
```

客户端V2rayN，版本V7.4.0

内核Xray，版本v24.12.15

**Comment by 233boy** [comment]
https://github.com/233boy/Xray

**Comment by Nicolas-Gong** [comment]
> https://github.com/233boy/Xray

看到了，谢谢了。

**Comment by Nicolas-Gong** [comment]
> https://github.com/233boy/Xray

`Failed to start: main: failed to load config files: [/etc/xray/config.json /etc/xray/conf/VMess-H2-TLS-www.baidu.com.json] > common/errors: The feature HTTP transport (without header padding, etc.) has been removed and migrated to XHTTP stream-one H2 & H3. Please update your config(s) according to release note and documentation.`

使用xray no-auto-tls h2 输入域名www.baidu.com，启动报错

**Comment by 233boy** [comment]
收到，下一个版本修复
