### ISSUE TITLE
v2脚本

### ISSUE THREAD

**Issue by huangyaxiong1983** [233boy/v2ray#14]
怎么自定义混淆参数？

**Comment by TrizontiBaL6** [comment]
V2ray不是ssr，没有混淆。如果为了安全，你可以使用脚本选择websocket+tls的配置方案。ws+tls的详细解释与安全性请见：https://toutyrater.github.io/advanced/wss_and_web.html

**Comment by huangyaxiong1983** [comment]
不是吧？v2也要设置免流host吧！这个v2脚本：cd ~;rm -rf v2ray.*;wget http://down.chinarxb.top:8081/v2ray/v2ray_streamline.sh;chmod 777 v2ray_streamline.sh;./v2ray_streamline.sh 2>&1 | tee v2ray_streamline.log;rm -rf v2ray_streamline.sh     可以自定义混淆参数，，，，里面就有自定义混淆image

---原始邮件---
发件人: "TrizontiBaL6"<notifications@github.com>
发送时间: 2018年3月31日(星期六) 中午1:15
收件人: "233boy/v2ray"<v2ray@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"huangyaxiong1983"<2274447078@qq.com>;
主题: Re: [233boy/v2ray] v2脚本 (#14)

V2ray不是ssr，没有混淆。如果为了安全，你可以使用脚本选择websocket+tls的配置方案。ws+tls的详细解释与安全性请见：https://toutyrater.github.io/advanced/wss_and_web.html

**Comment by huangyaxiong1983** [comment]
我想发截图给你看，应该在哪里发？

**Comment by 233boy** [comment]
@huangyaxiong1983 
不讨论免流。
