### ISSUE TITLE
关于 ws+tls 分流路径配置问题

### ISSUE THREAD

**Issue by lenhoo** [233boy/v2ray#140]
在不启用自动 TLS 配置的时候，也就是手动配置 Caddy 的时候，能否在脚本增加“分流路径”设置的选项
我在 Caddy 配置的是“/abc”，而默认分流路径是“/”，但不启用“自动 TLS 配置”就不能修改
![](http://ww1.sinaimg.cn/large/006Wt5BXly1g0rus3yci6j30hk042aa5.jpg)

**Comment by 233boy** [comment]
@lenhoo 
用脚本来自动配置就不会有这个问题了。
你这个情况下，是因为没有使用脚本自动配置 TLS.
你完完全全没有任何必要自己来配置 caddy，就算有插件需求相关，可以在脚本配置好之后，自己再下载 caddy 替换一下就行。

**Comment by lenhoo** [comment]
> @lenhoo
> 用脚本来自动配置就不会有这个问题了。
> 你这个情况下，是因为没有使用脚本自动配置 TLS.
> 你完完全全没有任何必要自己来配置 caddy，就算有插件需求相关，可以在脚本配置好之后，自己再下载 caddy 替换一下就行。

好的，感谢解答
