### ISSUE TITLE
V2ray突然无法从公司PC连接，前半天还正常，移动4G正常连接

### ISSUE THREAD

**Issue by patpatshine** [233boy/v2ray#141]
各位大佬好，用tripodcloud san Jose的服务器建的v2ray，公司电脑连接昨天和今天上半天一直正常，刚刚突然就无法连接墙外网站了。。V2ray显示运作正常，手机移动4G的连接也正常。。电脑通过SS连接正常。。Google也没找到解决方法。。求各位大佬指导。。谢谢

#### 更新一下，把协议改成mKCP就没问题了。。不过据说流量跑得比较猛？请问还有别的解决方法吗？谢谢谢谢

**Comment by liuyf5231** [comment]
开始用的什么协议？
我目前发现ws+tls在某些网络下会出现断流(手机电信4g正常)，抓包发现断流的时候tls协议都用的1.1，正常时候协议是tls v1.2

**Comment by patpatshine** [comment]
> 开始用的什么协议？
> 我目前发现ws+tls在某些网络下会出现断流(手机电信4g正常)，抓包发现断流的时候tls协议都用的1.1，正常时候协议是tls v1.2

开始就是默认的TCP，貌似TLS没开，我不是很懂这些。。就跑着mKCP了。。不过很少看视频，Gmail和RSS为主，所以流量感觉也还好。。只是手机不舍得多买个支持KCP的app还用着SS，希望小火箭快更新。。
