### ISSUE TITLE
minikube需要拉k8s.gcr.io里的镜像，v2ray能否监听0.0.0.0:8001  而不是本地的:8001

### ISSUE THREAD

**Issue by lyuanx** [233boy/v2ray#142]
什么都弄好了，v2ray只能让本机使用，macos里构建的minikube是在虚拟机里的，虚拟机里需要本机的0.0.0.0:8001  但v2ray只有127.0.0.1:8001  虚拟机访问不了。
有办法让软件监听的是0.0.0.0吗

**Comment by 233boy** [comment]
@lyuanx 
你这个客户端的吧？？？服务器上 0.0.0.0 的

**Comment by abelfourier** [comment]
0.0.0.0不是某个服务器的ip地址，它代表任意一个合法的ip地址。
