### ISSUE TITLE
请教一下关于脚本的内容

### ISSUE THREAD

**Issue by AXslashl** [233boy/v2ray#143]
系统linux 64 ，我在v2ray下载了官方的包解压后可以正常运行但是客户端连接后会不稳定，会相隔20秒出现出现服务器拒绝重置的情况。报错是这个提示failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination。
用您的脚本没有这种情况发生，请教一下，您除了解压了官方的包还有什么其他的辅助配置吗。

**Comment by 233boy** [comment]
@AXslashl 
没有。
或者你可以选择使用我的脚本…… 😂

**Comment by AXslashl** [comment]
谢谢您我的问题已经解决了

**Comment by AXslashl** [comment]
谢谢您我的问题已经解决了
