### ISSUE TITLE
请问在WS+TLS协议下，还能挂个网站吗？

### ISSUE THREAD

**Issue by aass0810** [233boy/v2ray#144]
使用大大的脚本通过WS+TLS协议，并通过cloudflare进行转发且隐藏了IP（域名通过freenom注册），已经成功可以使用梯子了。因为不想浪费VPS资源和现有手上的腾讯云注册的域名，我想把腾讯云的域名解析到VPS上来，发现我不管是搭LNMP还是宝塔面板，还是改Nginx的端口，都不能访问。都会出现“404 Site ****** is not served on this interface”，请问大神们，这个有解吗？

**Comment by aass0810** [comment]
已经找到解决办法了，放到 /etc/caddy/sites目录下。

**Comment by 672110619** [comment]
老哥晚上好~想问一下，如果自己想搭建一个轻量级的博客（Hexo）这个方式可行么？

**Comment by callmepopo** [comment]
@aass0810 你好，同样使用WS+TLS协议，并通过cloudflare进行转发且隐藏了IP（域名通过freenom注册），已经成功可以使用梯子了。尝试搭LNMP还是宝塔面板都会出现“404 Site ****** is not served on this interface”。看了你的解决方案，还是没能成功，能详细指导下吗？谢谢。我的邮箱xujunpo@gmail.com

**Comment by napm** [comment]
自己琢磨了一下，原生233boy的脚本，WS+TLS搭建完成后，再挂上自己的网站。需要修改两个文件
`/etc/caddy/Caddyfile`和`/etc/v2ray/config.json`

### 1.修改`/etc/caddy/Caddyfile`
修改前配置：
```
www.xxx.com {
    tls xxxxxx@gmail.com
    timeouts none
    proxy / 127.0.0.1:12345 {
    websocket
    }
}
import sites/*
```
修改后配置为
```
www.xxx.com:443 {
    tls xxxxxx@gmail.com
    timeouts none
    proxy /abc 127.0.0.1:12345{
   	 websocket
    }
}
moe.xxx.com:80 {
    root /var/www
}
import sites/*
```
### 2.修改`/etc/v2ray/config.json`
找到关键字`streamSettings`
修改前：
```
"streamSettings": {
				"network": "ws"
			}
```
修改后
```
"streamSettings": {
				"network": "ws",
				"wsSettings": {
				"path": "/abc"
	              	         }
			}
```
### 创建 www目录
在`/var`’下创建`www`文件夹,随便放一个index.html
然后重启vps服务器，访问`moe.xxx.com`看效果（记得把moe.xxx.com解析到服务器）

---
两处改动分别修改了v2ray的代理路径为/abc ,增加网站 moe.xxx.com

# 重要👇
**另外v2ray客户端里的路径path需要修改为/abc** 如下图
![image](https://user-images.githubusercontent.com/16299874/63425284-c3994c00-c442-11e9-8b80-ee3a284db751.png)


其中敏感信息已经脱敏（/abc和moe.xxx.com），请替换为自己的配置。

**Comment by tonyyu0624** [comment]
> 已经找到解决办法了，放到 /etc/caddy/sites目录下。

你好，将哪些内容放到/etc/caddy/sites目录下？我也碰到了404的问题，会不会是搭建v2+ws+tls的原因导致的？谢谢！

**Comment by buoyont** [comment]
> > 已经找到解决办法了，放到 /etc/caddy/sites目录下。
> 
> 你好，将哪些内容放到/etc/caddy/sites目录下？我也碰到了404的问题，会不会是搭建v2+ws+tls的原因导致的？谢谢！

宝塔面板，用你的方法试了一下，无效。

**Comment by zlf4865231** [comment]
/etc/caddy/sites 下存放配置文件还是网页index.html文件？

**Comment by impn** [comment]
> /etc/caddy/sites 下存放配置文件还是网页index.html文件？

 目录/etc/caddy/sites 下放的是**配置文件**，建议首尾添加一行空行（没空行可能不生效）。

附上Caddyfile配置文件内容
```
autumn.cccc.ml {
    tls 426456944@gmail.com
    gzip
timeouts none
    proxy / https://winter.cccc.ml {
        except /music
    }
    proxy /music 127.0.0.1:36985 {
        without /music
        websocket
    }
}

winter.cccc.ml {
    root /var/www
}

import sites/*

```
其实这样就已经可以了。
sites文件夹下文件可以这样配置,文件名随意
```
pdf.cccc.ml {
    root /var/pdf/
    browse
}

```

重启caddy后，这样就有两个网站在运行了 分别是`winter.cccc.ml` 和 `pdf.cccc.ml`
而autumn.cccc.ml 是伪装**富强**用的域名。其中 cccc.ml是你的域名，记得替换哦
`/var/pdf/`和`/var/www/`两个目录需要有`index.html`等网页内容。

**Comment by we11cheng** [comment]
> > /etc/caddy/sites 下存放配置文件还是网页index.html文件？
> 
> 目录/etc/caddy/sites 下放的是**配置文件**，建议首尾添加一行空行（没空行可能不生效）。
> 
> 附上Caddyfile配置文件内容
> 
> ```
> autumn.cccc.ml {
>     tls 426456944@gmail.com
>     gzip
> timeouts none
>     proxy / https://winter.cccc.ml {
>         except /music
>     }
>     proxy /music 127.0.0.1:36985 {
>         without /music
>         websocket
>     }
> }
> 
> winter.cccc.ml {
>     root /var/www
> }
> 
> import sites/*
> ```
> 
> 其实这样就已经可以了。
> sites文件夹下文件可以这样配置,文件名随意
> 
> ```
> pdf.cccc.ml {
>     root /var/pdf/
>     browse
> }
> ```
> 
> 重启caddy后，这样就有两个网站在运行了 分别是`winter.cccc.ml` 和 `pdf.cccc.ml`
> 而autumn.cccc.ml 是伪装**富强**用的域名。其中 cccc.ml是你的域名，记得替换哦
> `/var/pdf/`和`/var/www/`两个目录需要有`index.html`等网页内容。

autumn 在哪里获取，网站跟目录是哪个。
下面是我的配置
weiguan.ml {
    gzip
timeouts none
    proxy / https://liyafly.com {
        except /233blog
    }
    proxy /233blog 127.0.0.1:31780 {
        without /233blog
        websocket
    }
}

import sites/*

/etc/caddy/sites

pdf.weiguan.ml {
    root /var/pdf/
    browse
}

**Comment by we11cheng** [comment]
@impn

**Comment by impn** [comment]
> > > /etc/caddy/sites 下存放配置文件还是网页index.html文件？
> 
> > 
> 
> > 目录/etc/caddy/sites 下放的是**配置文件**，建议首尾添加一行空行（没空行可能不生效）。
> 
> > 
> 
> > 附上Caddyfile配置文件内容
> 
> > 
> 
> > ```
> 
> > autumn.cccc.ml {
> 
> >     tls 426456944@gmail.com
> 
> >     gzip
> 
> > timeouts none
> 
> >     proxy / https://winter.cccc.ml {
> 
> >         except /music
> 
> >     }
> 
> >     proxy /music 127.0.0.1:36985 {
> 
> >         without /music
> 
> >         websocket
> 
> >     }
> 
> > }
> 
> > 
> 
> > winter.cccc.ml {
> 
> >     root /var/www
> 
> > }
> 
> > 
> 
> > import sites/*
> 
> > ```
> 
> > 
> 
> > 其实这样就已经可以了。
> 
> > sites文件夹下文件可以这样配置,文件名随意
> 
> > 
> 
> > ```
> 
> > pdf.cccc.ml {
> 
> >     root /var/pdf/
> 
> >     browse
> 
> > }
> 
> > ```
> 
> > 
> 
> > 重启caddy后，这样就有两个网站在运行了 分别是`winter.cccc.ml` 和 `pdf.cccc.ml`
> 
> > 而autumn.cccc.ml 是伪装**富强**用的域名。其中 cccc.ml是你的域名，记得替换哦
> 
> > `/var/pdf/`和`/var/www/`两个目录需要有`index.html`等网页内容。
> 
> 
> 
> autumn 在哪里获取，网站跟目录是哪个。
> 
> 下面是我的配置
> 
> weiguan.ml {
> 
>     gzip
> 
> timeouts none
> 
>     proxy / https://liyafly.com {
> 
>         except /233blog
> 
>     }
> 
>     proxy /233blog 127.0.0.1:31780 {
> 
>         without /233blog
> 
>         websocket
> 
>     }
> 
> }
> 
> 
> 
> import sites/*
> 
> 
> 
> /etc/caddy/sites
> 
> 
> 
> pdf.weiguan.ml {
> 
>     root /var/pdf/
> 
>     browse
> 
> }
> 
> 
> 
> 

winter，autumn，pdf这些都是自定义的。你只需要把对应的域名A记录解析到你的ip即可，需要去域名处设置。

**Comment by we11cheng** [comment]
小白一个，还有一些网站路径设置啥的，方便加个联系方式吗，感谢。1396539283我的qq，我加你也行
@impn

**Comment by we11cheng** [comment]
用二级域名吧。不选自动配置TLS 参考<https://hixingchen.com/index.php/2019/11/08/vps%E4%B9%8B%E5%AE%9D%E5%A1%94wordpress%E5%8D%9A%E5%AE%A2%E4%B8%8Ev2ray%E5%85%B1%E5%AD%98/>
