### ISSUE TITLE
请问一下关于QUIC的问题

### ISSUE THREAD

**Issue by mysq1isworst** [233boy/v2ray#146]
查了一下，这个协议貌似更为先进，但是装了之后，发现并不能连接，是还没有实装吗？还是我安装错误，需要指导一下，资料里面没有关于这个协议的攻略

**Comment by 233boy** [comment]
@mysq1isworst 
有些客户端不支持（比如说 V2RayN）

**Comment by mysq1isworst** [comment]
正好是N，佛了，那可以问下哪些支持吗？还有我在手机版本的NG也试过，好像也是不行的。这个是不是还不太完善，不适用啊。

**Comment by 1688aa** [comment]
@ mysq1isworst
V2Ray客户端支持，下载配置放入V2Ray目录即可

**Comment by mysq1isworst** [comment]
我看了下，似乎是因为没有稳定，所以N的作者还没有更新它。先不用了，而且没有可视化很难受，不过还是多谢解答 @1688aa

**Comment by 1688aa** [comment]
@mysq1isworst 是的，速度没有mKCP快，我这里mKCP测试下载速度4.5mb，QUIC时快时慢，有时候50kb-500kb有时候最快也只有3.5mb

**Comment by mysq1isworst** [comment]
最近好像更新了，测试了一下，不知道是不是我的问题，用脚本安装quic协议以后，无论是N还是NG都没法正常FQ，谷歌油管都没法用 @1688aa @233boy

**Comment by mysq1isworst** [comment]
mKCP正常的，无语了
