### ISSUE TITLE
无法 Cloning，请问这是什么原因？

### ISSUE THREAD

**Issue by LoveOctocat** [233boy/v2ray#150]
一键后卡在这个位置：
```
Cloning into '/etc/v2ray/233boy/v2ray'...
fatal: unable to access 'https://github.com/233boy/v2ray/': Failed to connect to github.com port 443: Connection timed out
~

 哎呀呀...克隆脚本仓库出错了...

 温馨提示..... 请尝试自行安装 Git: apt-get install -y git  之后再安装此脚本
```

无法 Cloning，请问这是什么原因？
输入：`ssh -T git@github.com` 也是没有反应的。

- 使用的是 VIRMACH 的 VPS。
- 系统：Debian 9.0 x64 Minimal

**Comment by 233boy** [comment]
@barrylu1999 
VPS 太垃圾。。。

**Comment by barrylu1999** [comment]
也就无解了？

**Comment by barrylu1999** [comment]
您好，解决了。
修改/etc/hosts文件，新增一行：
`13.250.177.223 github.com`

**Comment by meaverick** [comment]
> 您好，解决了。
> 修改/etc/hosts文件，新增一行：
> `13.250.177.223 github.com`

我加上了也不行呢？
