### ISSUE TITLE
多ip配置问题

### ISSUE THREAD

**Issue by AgonyLei** [233boy/v2ray#152]
服务器上有多个IP，我想让多ip都可用v2ray，但安装完成后，只有系统默认ip可用v2ray

**Comment by abelfourier** [comment]
主机路由问题。
1、你要做主机路由，比如在windows下写route print表，让所有ip都可以发送数据包。
2、同时还要做会话保持，如果数据包是访问ip1的，就要用ip1应答，而不是ip2。
我想知道，为啥要多ip呢？因为有多用户？
