### ISSUE TITLE
无法生成配置文件链接  请作者检查一下

### ISSUE THREAD

**Issue by 22646998** [233boy/v2ray#155]
无法生成

**Comment by msn1983aa** [comment]
对，刚试了，也是无法生成配置文件下载链接了，生成二维码的功能正常

**Comment by 233boy** [comment]
@22646998 
已经修复了。
请关注 TG 频道：https://t.me/blog2333 ，或者 TG 群组：https://t.me/blog233 ，来获取最新消息。

**Comment by msn1983aa** [comment]
> @22646998
> 已经修复了。
> 请关注 TG 频道：https://t.me/blog2333 ，或者 TG 群组：https://t.me/blog233 ，来获取最新消息。

---------- V2Ray 客户端配置文件链接 -------------

 链接 = Could not save metadata

貌似还是不行咧，大佬拜托再看看

**Comment by 233boy** [comment]
@22646998 
我的天啊，你要更新啊。。。 `v2ray update.sh; v2ray link`

**Comment by msn1983aa** [comment]
/尴尬了，谢谢！

233boy <notifications@github.com> 于2019年3月13日周三 下午12:26写道：
