### ISSUE TITLE
caddy  没有权限建目录，应该是用于保存ssl证书

### ISSUE THREAD

**Issue by crazypeace** [233boy/v2ray#16]
root@localhost:~# service caddy status
● caddy.service - Caddy HTTP/2 web server
   Loaded: loaded (/lib/systemd/system/caddy.service; enabled)
   Active: failed (Result: exit-code) since Mon 2018-04-02 04:00:58 CST; 37s ago
     Docs: https://caddyserver.com/docs
  Process: 2211 ExecStart=/usr/local/bin/caddy -log stdout -agree=true -conf=/etc/caddy/Caddyfile -root=/var/tmp (code=exited, status=1/FAILURE)
 Main PID: 2211 (code=exited, status=1/FAILURE)

Apr 02 04:00:58 localhost systemd[1]: Starting Caddy HTTP/2 web server...
Apr 02 04:00:58 localhost systemd[1]: Started Caddy HTTP/2 web server.
Apr 02 04:00:58 localhost caddy[2211]: Activating privacy features... 2018/04/02 04:00:58 [INFO] acme: Registering account for 6369159010@gmail.com
Apr 02 04:00:58 localhost caddy[2211]: 2018/04/02 04:00:58 could not save user: making user directory: mkdir /etc/ssl/caddy/acme: read-only file system
Apr 02 04:00:58 localhost systemd[1]: caddy.service: main process exited, code=exited, status=1/FAILURE
Apr 02 04:00:58 localhost systemd[1]: Unit caddy.service entered failed state.

**Comment by crazypeace** [comment]
直接用root去 mkdir /etc/ssl/caddy/acme
是可以成功的。

**Comment by 233boy** [comment]
@crazypeace 
输入 `choown -R root. /etc/ssl/caddy/` 然后再重启 Caddy 进程 `service caddy restart` 看看？

**Comment by crazypeace** [comment]
不行。我是bandwagon比较早的套餐了，最高只有debian8，tg群里说换debian9换不了。
现在换centos7，正常了。
