### ISSUE TITLE
腾讯新出了个TCPA加速，号称秒杀BBR，集成一下吧

### ISSUE THREAD

**Issue by xhqpp** [233boy/v2ray#160]
提问之前，请先查阅：[V2Ray 一键安装脚本疑问集合](https://v2ray6.com/post/10/)

若需要发起提问，请删除这些内容

**Comment by zhz1237ok** [comment]
开源的嘛，有地址瞅瞅嘛

**Comment by 672110619** [comment]
同求个地址~不过讲道理腾讯的东西真的敢装？

**Comment by 233boy** [comment]
@xhqpp 
贼麻烦了，还要专属内核 ，也不开源。你自己搞

**Comment by xc1988** [comment]
基于GPL协议，居然不开源。

**Comment by hundan2020** [comment]
参考这个 <https://www.v2ex.com/t/543692>

**Comment by mikewubox** [comment]
腾讯，阿里，百度的就别用了
