### ISSUE TITLE
我想手动修改配置文件

### ISSUE THREAD

**Issue by ghost** [233boy/v2ray#161]
我想手动修改配置文件,我该改 哪个
233blog_v2ray_config.json
233blog_v2ray_backup.conf
config.json

**Comment by 233boy** [comment]
config.json > v2ray 配置文件，（使用脚本修改过，这个文件会重新生成）
233blog_v2ray_config.json > 客户端配置文件，（使用脚本修改过，这个文件会重新生成）
233blog_v2ray_backup.conf  > 脚本配置文件
