### ISSUE TITLE
在Azure上用一键脚本搭建的V2Ray不能上网  我试了一下用官方的脚本可以  不知道哪里的问题

### ISSUE THREAD

**Issue by szweee** [233boy/v2ray#162]
如题

**Comment by 233boy** [comment]
@szweee 
可能是外部端口的原因，你检查一下防火墙配置

**Comment by chuhaibo** [comment]
要单独配置入站和出站端口才能正常使用  网络 - 入站端口规则添加0-65535；出站端口规则添加0-65535

**Comment by szweee** [comment]
可以了  多谢
2019年3月27日 +0800 14:02 EricCh <notifications@github.com>，写道：
