### ISSUE TITLE
未加入黑名单列表

### ISSUE THREAD

**Issue by 1688aa** [233boy/v2ray#163]
epochtimes.cz
epochtimes.nl
epochtimes.it
epochtimes.pl
epochtimes.com.br
epochtimes.se
epochtimestr.com
epochtimes.com.ua
ntd.com

**Comment by myworksfun** [comment]
这些domain都是恶心人的辣鸡媒体吧？ 睁着眼睛瞎扯淡的那种，建议禁止。

**Comment by William96911** [comment]
这个脚本自带黑名单，建议不使用

**Comment by mikewubox** [comment]
黑名单做个自选，昨天也看到了。BT也做个自选。做个说明，这样比较好一些。

**Comment by 1688aa** [comment]
@mikewubox 作者网站有说明的
@William96911 黑名单是为了防止小白误入歧途，知道那几个网站的一般都会去除黑名单，反正我无所谓啦，黑名单中网站的爬墙工具小气得很，不能畅快谷歌，黑了就黑了，留它们何用？

**Comment by William96911** [comment]
难道GFW不就是防止我们“误入歧途”吗

**Comment by William96911** [comment]
黑名单在"/etc/v2ray/233boy/v2ray/config/server/include/ban.json"

**Comment by WilliamChen996** [comment]
您好，我是陈蔚文，已收到您的邮件
