### ISSUE TITLE
config.json

### ISSUE THREAD

**Issue by xiaoyang666** [233boy/v2ray#164]
json文件官网我查不到，可否发一份linux版本的配置文件config.json 多谢。全面一点，困扰我一周了。

**Comment by 233boy** [comment]
@xiaoyang666 
使用脚本安装之后，配置文件在 `/etc/v2ray/config.json`
你可以参考这个文件。

**Comment by xiaoyang666** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
