### ISSUE TITLE
按照你的教程配置好后ss客户端不能梯子，但是v2rayN测试网速后可以正常梯子

### ISSUE THREAD

**Issue by jiao1603134620** [233boy/v2ray#166]
按照你的教程配置好后ss客户端不能梯子，v2ray也不能梯子，不过v2ray如果先设置全局代理再测试网速后就可以正常梯子，ss客户端Ping也有显示但就是不能用，服务器端口完全开放

**Comment by xuranran88** [comment]
一样的情况~

**Comment by NNorLand** [comment]
刚好相反，我的ss没问题，但是 v2rayU ，无法连接
