### ISSUE TITLE
希望能开启tcp与kcp两套配置模式

### ISSUE THREAD

**Issue by mutou172** [233boy/v2ray#168]
在公司使用tcp不行，使用kcp可以。
有时，使用tcp又可以。麻烦的很。
今天找到了一个一键安装两套配置的。
一直以来使用您的教程，方能放心地使用google，做为受益者，
便提出这项建议，希望您的方案越来越好。
希望能再次使用您的方案。

**Comment by 233boy** [comment]
@mutou172 
哈哈！会有的。请期待！ 😂
