### ISSUE TITLE
vultr centos7

### ISSUE THREAD

**Issue by Parkstud** [233boy/v2ray#173]
vultr centos7 实例 连接后服务器监听在ipv6上

**Comment by 233boy** [comment]
V4 地址没监听？？？

**Comment by Parkstud** [comment]
运行脚本后使用客户端 控制台一直显示failed to handler mux client connection.....
ping 远程ip 正确  使用telnet ip 端口 无法连接  就在服务器上看 程序 是已经启动的
但是 网络端口 只在 tcp6 上 进行监听

**Comment by Parkstud** [comment]
切换成系统ubuntu 18 没有问题

**Comment by 233boy** [comment]
那就 Ubuntu 18
