### ISSUE TITLE
能否修改SSL证书的申请邮箱

### ISSUE THREAD

**Issue by ilhuyi** [233boy/v2ray#174]
您好，我再caddy配置文件里面看到默认的申请ssl证书的邮箱，现在证书已经申请成功。能否在配置文件里面更改成我自己的邮箱，下次证书到期的时候自动更新证书？谢谢

**Comment by 233boy** [comment]
@ilhuyi 
那个邮箱是随机生成的，不用管。。
是自动更新证书的。也不用管。。。
