### ISSUE TITLE
添加Shadowsocks支持V2ray

### ISSUE THREAD

**Issue by iambiglee** [233boy/v2ray#177]
什么？这不是 V2Ray 吗？怎么说配置 Shadowsocks 呢？

骚年别紧张。V2Ray 集成有 Shadowsocks 模块的，用 V2Ray 配置成 Shadowsocks 服务器或者 Shadowsocks 客户端都是可以的，兼容 Shadowsocks-libev。
https://toutyrater.github.io/basic/Shadowsocks.html
可以参阅上面的网址

**Comment by 233boy** [comment]
@iambiglee 什么鬼？？？？
是说要支持 SS ???
输入 v2ray ss 啊

**Comment by shuihan666** [comment]
请问用Shadowsocks在iPhone上和iPad上使用Facebook和Messenger的时候，内容或者消息加载延迟比较严重，该如何解决？
