### ISSUE TITLE
BBR和内核的小疑问

### ISSUE THREAD

**Issue by SekiBetu** [233boy/v2ray#178]
debian9.7  内核4.9
如果更新内核是否能让BBR加速更加快？

**Comment by LaurenceSamael** [comment]
效果不明显，我是ubuntu 19.04，单单bbr的话无论原版、魔改版还是plus版都没多少作用。
电信来说现在好像会识别vmess的tcp流量，只要是vmess的tcp流量就算用了bbr一样会被QoS、一样丢包非常高，即便cn2 gia线路都是如此。
