### ISSUE TITLE
请提供关闭所谓黑名单的选项

### ISSUE THREAD

**Issue by ykla** [233boy/v2ray#179]
RT。请提供关闭所谓黑名单的选项

**Comment by liguojing83** [comment]
这代码安全吗？会不会泄漏信息？

**Comment by William96911** [comment]
已经换[脚本]了(https://github.com/Jrohy/multi-v2ray)

**Comment by William96911** [comment]
已经换脚本了 https://github.com/Jrohy/multi-v2ray

**Comment by Litangren** [comment]
> 已经换脚本了 https://github.com/Jrohy/multi-v2ray

中文版安装没有成功.....
能否提供手动删除黑名单的方法？

**Comment by lonepair** [comment]
> 
> 
> > 已经换脚本了 https://github.com/Jrohy/multi-v2ray
> 
> 中文版安装没有成功.....
> 能否提供手动删除黑名单的方法？

`vim /etc/v2ray/config.json`，找到那一排`domain*`并删除，之后重启v2ray

**Comment by hekly** [comment]
> > > 換速已經腳本了https://github.com/Jrohy/multi-v2ray
> > 
> > 
> > 中文版安裝沒有成功..... 
> > 能否提供手動刪除黑名單的方法？
> 
> `vim /etc/v2ray/config.json`，那一排找到`domain*`並刪除，之後重啟v2ray

谷歌云进去删除后，无法保存。重新进去还是原来的样子
