### ISSUE TITLE
无法安装："bash: /dev/fd/63: 没有那个文件或目录"

### ISSUE THREAD

**Issue by zegzag** [233boy/v2ray#181]
系统：
基于Ubuntu 16.04.1的Linux Mint 18.3 Sylvia
 
我之前通过一键脚本安装又卸载后，再次执行安装命令就出现了上面这个问题。。。。。。

root@username ~ $ bash <(curl -s -L https://git.io/go.sh)
提示： bash: /dev/fd/63: 没有那个文件或目录

**Comment by 233boy** [comment]
@zegzag 
。。。。。
是 `bash <(curl -s -L https://git.io/v2ray.sh)`

**Comment by zegzag** [comment]
一样的T.T
![Uploading Screenshot_20190416_153753.png…]()

**Comment by 233boy** [comment]
@zegzag 
那我就知道了。。换 Debian9

**Comment by ZhongqiXiao** [comment]
sudo bash -c "$(curl -s -L https://git.io/v2ray.sh)"
亲测管用

**Comment by xuguangheng** [comment]
sudo su
bash <(curl -s -L https://git.io/v2ray.sh)

**Comment by GuguguBear** [comment]
同问题 楼上几个命令都试过 没用…

**Comment by antstars** [comment]
wget 下载在用sudo运行

**Comment by zdc19930402** [comment]
> 系统：
> 基于Ubuntu 16.04.1的Linux Mint 18.3 Sylvia
> 
> 我之前通过一键脚本安装又卸载后，再次执行安装命令就出现了上面这个问题。。。。。。
> 
> root@username ~ $ bash <(curl -s -L https://git.io/go.sh)
> 提示： bash: /dev/fd/63: 没有那个文件或目录

这个问题解决了吗 基于centos8也出现了这个提示

**Comment by hyl520m** [comment]
bash <(wget -qO- -o- https://git.io/v2ray.sh)  要用root账户执行才可以  如果不是root用户 sudo su
