### ISSUE TITLE
谷歌云刚升级了脚本，输入v2ray出现错误

### ISSUE THREAD

**Issue by pctoolsx** [233boy/v2ray#182]
刚发现脚本升级，就升级了，然后

sudo -i
v2ray
就弹出以下提示
/usr/local/sbin/v2ray: line 13: syntax error near unexpected token `<<<'
/usr/local/sbin/v2ray: line 13: `<<<<<<< HEAD'

没修改过任何东西，用了半年多了，升级了很多次脚本都没遇到问题，请问这是怎么回事？怎么解决，谢谢

**Comment by 233boy** [comment]
执行如下 命令即可。。。

```bash
cd /etc/v2ray/233boy/v2ray;git merge --abort;git checkout .;cp -f v2ray.sh /usr/local/sbin/v2ray
```

**Comment by pctoolsx** [comment]
执行了您发的指令就可以了，发现管理脚本是3.07，如果再升级到3.09就又是之前那个错误提示。只能再执行您发的指令回落到3.07。
请问是不是3.09有问题？

**Comment by 233boy** [comment]
> 执行了您发的指令就可以了，发现管理脚本是3.07，如果再升级到3.09就又是之前那个错误提示。只能再执行您发的指令回落到3.07。
> 请问是不是3.09有问题？是否等下个版本就能修复？

卸载重装吧。。。这是一个蛋痛的BUG。。

`v2ray reinstall`
