### ISSUE TITLE
2个疑问

### ISSUE THREAD

**Issue by wenfangcn** [233boy/v2ray#184]
您好，有2个疑问需要解答
1. 安装v2ray时没有配置加密方式，默认是什么加密呢
2. v2ray和ss是两个完全分开的代理吗，因为安装v2ray时没有配置ss，这样不影响v2ray吧

**Comment by 233boy** [comment]
@wenfangcn 
1，无须理会加密方式，不同于 SS 必须加密方式相同，（你可以在客户端随意选择相关的加密方式，例如 V2RayN）
2，是，不影响
