### ISSUE TITLE
果真有黑名单，不厚道啊！

### ISSUE THREAD

**Issue by Litangren** [233boy/v2ray#186]
给个解除黑名单的开关，否则太不厚道了。墙内墙，你也墙？

**Comment by lonepair** [comment]
确实不厚道，你可以使用`vim /etc/v2ray/config.json`找到那一排`domain*`并删除它们，之后重启

**Comment by yuhuangniu** [comment]
有些人的自我审查是刻在骨子里的，即使网络上翻了墙，脑子还永远留在墙内。正确的做法是彻底换掉这个脚本，用别家的，或者自己搭。

**Comment by sutun2008** [comment]
脚本作者太不厚道，还搞域名拦截那一套，你以为自己是赵家的人吗？

**Comment by q276240802** [comment]
看了一下，发现作者已经在wiki提示过了
[https://github.com/233boy/v2ray/wiki/V2Ray%E4%B8%80%E9%94%AE%E5%AE%89%E8%A3%85%E8%84%9A%E6%9C%AC#%E5%AE%89%E8%A3%85%E6%88%96%E5%8D%B8%E8%BD%BD](url)

**Comment by a7611818** [comment]
> 有些人的自我审查是刻在骨子里的，即使网络上翻了墙，脑子还永远留在墙内。正确的做法是彻底换掉这个脚本，用别家的，或者自己搭。

作者不是说了屏蔽的是轮子的网站，也没把你咋地

**Comment by githubhao0705** [comment]
> > 有些人的自我审查是刻在骨子里的，即使网络上翻了墙，脑子还永远留在墙内。正确的做法是彻底换掉这个脚本，用别家的，或者自己搭。
> 
> 作者不是说了屏蔽的是轮子的网站，也没把你咋地

我认为，每个人有每个人的看法，是否屏蔽还是得看用户，我不觉得谁可以帮我下决定。

**Comment by geekyouth** [comment]
骂人就不对了。

vim "/etc/v2ray/config.json"
找到如下：

"domain:epochtimes.com",
"domain:epochtimes.com.tw",
"domain:epochtimes.fr",
"domain:epochtimes.de",
"domain:epochtimes.jp",
"domain:epochtimes.ru",
"domain:epochtimes.co.il",
"domain:epochtimes.co.kr",
"domain:epochtimes-romania.com",
"domain:erabaru.net",
"domain:lagranepoca.com",
"domain:theepochtimes.com",
"domain:ntdtv.com",
"domain:ntd.tv",
"domain:ntdtv-dc.com",
"domain:ntdtv.com.tw",
"domain:minghui.org",
"domain:renminbao.com",
"domain:dafahao.com",
"domain:dongtaiwang.com",
"domain:falundafa.org",
"domain:wujieliulan.com",
"domain:ninecommentaries.com",
"domain:shenyun.com"

删掉这些被屏蔽的网址，然后填入一个不存在的域名，注意json格式，然后重启v2ray 服务即可解决，记住别骂人

**Comment by githubhao0705** [comment]
> 骂人就不对了。
> 
> vim "/etc/v2ray/config.json"
> 找到如下：
> 
> "domain:epochtimes.com",
> "domain:epochtimes.com.tw",
> "domain:epochtimes.fr",
> "domain:epochtimes.de",
> "domain:epochtimes.jp",
> "domain:epochtimes.ru",
> "domain:epochtimes.co.il",
> "domain:epochtimes.co.kr",
> "domain:epochtimes-romania.com",
> "domain:erabaru.net",
> "domain:lagranepoca.com",
> "domain:theepochtimes.com",
> "domain:ntdtv.com",
> "domain:ntd.tv",
> "domain:ntdtv-dc.com",
> "domain:ntdtv.com.tw",
> "domain:minghui.org",
> "domain:renminbao.com",
> "domain:dafahao.com",
> "domain:dongtaiwang.com",
> "domain:falundafa.org",
> "domain:wujieliulan.com",
> "domain:ninecommentaries.com",
> "domain:shenyun.com"
> 
> 删掉这些被屏蔽的网址，然后填入一个不存在的域名，注意json格式，然后重启v2ray 服务即可解决，记住别骂人

我骂人？？黑人问好.jpg

**Comment by 1688aa** [comment]
早就知道了，不过那个门备胎现在确实好用

**Comment by ljkk** [comment]
> > > 有些人的自我审查是刻在骨子里的，即使网络上翻了墙，脑子还永远留在墙内。正确的做法是彻底换掉这个脚本，用别家的，或者自己搭。
> > 
> > 
> > 作者不是说了屏蔽的是轮子的网站，也没把你咋地
> 
> 我认为，每个人有每个人的看法，是否屏蔽还是得看用户，我不觉得谁可以帮我下决定。

> > > 有些人的自我审查是刻在骨子里的，即使网络上翻了墙，脑子还永远留在墙内。正确的做法是彻底换掉这个脚本，用别家的，或者自己搭。
> > 
> > 
> > 作者不是说了屏蔽的是轮子的网站，也没把你咋地
> 
> 我认为，每个人有每个人的看法，是否屏蔽还是得看用户，我不觉得谁可以帮我下决定。

你可以有你的看法, 但是否屏蔽还是得看作者, 没人帮你下决定, 你可以自己决定不用这个脚本, 完美解决问题

**Comment by githubhao0705** [comment]
是的，所以我没有用，我用的其他的。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: ljkk <notifications@github.com>
发送时间: Thursday, June 13, 2019 1:43:11 PM
收件人: 233boy/v2ray
抄送: Liang Dinghao; Comment
主题: Re: [233boy/v2ray] 果真有黑名单，不厚道啊！ (#186)


有些人的自我审查是刻在骨子里的，即使网络上翻了墙，脑子还永远留在墙内。正确的做法是彻底换掉这个脚本，用别家的，或者自己搭。

作者不是说了屏蔽的是轮子的网站，也没把你咋地

我认为，每个人有每个人的看法，是否屏蔽还是得看用户，我不觉得谁可以帮我下决定。

有些人的自我审查是刻在骨子里的，即使网络上翻了墙，脑子还永远留在墙内。正确的做法是彻底换掉这个脚本，用别家的，或者自己搭。

作者不是说了屏蔽的是轮子的网站，也没把你咋地

我认为，每个人有每个人的看法，是否屏蔽还是得看用户，我不觉得谁可以帮我下决定。

你可以有你的看法, 但是否屏蔽还是得看作者, 没人帮你下决定, 你可以自己决定不用这个脚本, 完美解决问题

―

**Comment by real18cm** [comment]
作者辛苦写代码，是让你们骂的？ 明明实惠了很多小白，做出了贡献。绝大部分人都是力挺作者的。
另一个，任何中国公民都有义务维护祖国统一，对企图割裂祖国的行为予以制止。

**Comment by Jyougen** [comment]
别人分享他的糖, 你可以吃, 也可以不吃.  但是有人伸手拿了, 吃了, 还要说糖不甜.

**Comment by 1688aa** [comment]
@Jyougen 是啊，自己写一个啊，你可以出钱叫人写个脚本呀，你要什么功能都给你定制，免费用别人分享的就不要瞎逼逼，你不出钱没人义务给你改，爱用不用。

**Comment by MichaelJokAr** [comment]
不厚道啊

**Comment by linhongjun** [comment]
没什么不好 屏蔽这类域名 可以降低你的主机被墙的机率
还有这是免费的脚本 没人逼你用 你有其他很多选择
况且作者在脚本使用说明里已经添加相关解释

ps 不过也可以看出那些抱怨的人 有可能都是轮子关系者

**Comment by HOMHOG** [comment]
> 没什么不好 屏蔽这类域名 可以降低你的主机被墙的机率
> 还有这是免费的脚本 没人逼你用 你有其他很多选择
> 况且作者在脚本使用说明里已经添加相关解释
> 单纯这点我支持作者的选择
> ps 不过也可以看出那些抱怨的人 有可能都是轮子关系者

难道法轮功不能消除修炼者内心怨念吗 哈哈哈，看来是火候不到，脑子还没被摘

**Comment by HOMHOG** [comment]
> 有些人的自我审查是刻在骨子里的，即使网络上翻了墙，脑子还永远留在墙内。正确的做法是彻底换掉这个脚本，用别家的，或者自己搭。

你的嘴脸太难看，youtube没审查，facebook没审查？你不想用就不用咯，这么简单的道理，没爹妈教你？有必要在这说难听话，法论功没教会你消除内心怨念吗？

**Comment by HOMHOG** [comment]
> > > 有些人的自我审查是刻在骨子里的，即使网络上翻了墙，脑子还永远留在墙内。正确的做法是彻底换掉这个脚本，用别家的，或者自己搭。
> > 
> > 
> > 作者不是说了屏蔽的是轮子的网站，也没把你咋地
> 
> 我认为，每个人有每个人的看法，是否屏蔽还是得看用户，我不觉得谁可以帮我下决定。

那么作者加不加开关这个决定谁来做？你做？

**Comment by linhongjun** [comment]
> > 没什么不好 屏蔽这类域名 可以降低你的主机被墙的机率
> > 还有这是免费的脚本 没人逼你用 你有其他很多选择
> > 况且作者在脚本使用说明里已经添加相关解释
> > 单纯这点我支持作者的选择
> > ps 不过也可以看出那些抱怨的人 有可能都是轮子关系者
> 
> 难道法轮功不能消除修炼者内心怨念吗 哈哈哈，看来是火候不到，脑子还没被摘

那么牛 还需要翻墙么 直接意念访问不就好了

**Comment by linhongjun** [comment]
> > > > 有些人的自我审查是刻在骨子里的，即使网络上翻了墙，脑子还永远留在墙内。正确的做法是彻底换掉这个脚本，用别家的，或者自己搭。
> > > 
> > > 
> > > 作者不是说了屏蔽的是轮子的网站，也没把你咋地
> > 
> > 
> > 我认为，每个人有每个人的看法，是否屏蔽还是得看用户，我不觉得谁可以帮我下决定。
> 
> 那么作者加不加开关这个决定谁来做？你做？

哈哈 笑死我了。。。这个就像是有人被强奸的时候 还要求被强奸的人摆好姿势并且享受强奸过程

**Comment by nxtreaming** [comment]
> 没什么不好 屏蔽这类域名 可以降低你的主机被墙的机率
> 还有这是免费的脚本 没人逼你用 你有其他很多选择
> 况且作者在脚本使用说明里已经添加相关解释
> 单纯这点我支持作者的选择
> ps 不过也可以看出那些抱怨的人 有可能都是轮子关系者

@linhongjun 我从没见过脑子像你这么愚蠢之人。
不要随便喷你不了解的事物，你要想一下在如此众多的轮子中肯定有比你智商高的，他们为啥做这些像这种智商的人认为很愚蠢的事呢？答案就是你看到和你理解的根本不是真相，这是你的智商低这一硬伤造成的致命缺陷。

**Comment by linhongjun** [comment]
> > 没什么不好 屏蔽这类域名 可以降低你的主机被墙的机率
> > 还有这是免费的脚本 没人逼你用 你有其他很多选择
> > 况且作者在脚本使用说明里已经添加相关解释
> > 单纯这点我支持作者的选择
> > ps 不过也可以看出那些抱怨的人 有可能都是轮子关系者
> 
> @linhongjun 我从没见过脑子像你这么愚蠢之人。
> 不要随便喷你不了解的事物，你要想一下在如此众多的轮子中肯定有比你智商高的，他们为啥做这些像你这种智商的人认为很愚蠢的事呢？答案就是你看到和你理解的根本不是真相，这是你的智商低这一硬伤造成的致命缺陷。

笑死我了 哈哈。。。你是想说你是这群人里智商比较高的么？当然 不得不承认 在这个群体里 职位高的智商肯定不低 不然会有那么多SB跟随 另外那些台湾景区兼职举牌子的例外 人家是为了赚钱

**Comment by nxtreaming** [comment]
> > > 没什么不好 屏蔽这类域名 可以降低你的主机被墙的机率
> > > 还有这是免费的脚本 没人逼你用 你有其他很多选择
> > > 况且作者在脚本使用说明里已经添加相关解释
> > > 单纯这点我支持作者的选择
> > > ps 不过也可以看出那些抱怨的人 有可能都是轮子关系者
> > 
> > 
> > @linhongjun 我从没见过脑子像你这么愚蠢之人。
> > 不要随便喷你不了解的事物，你要想一下在如此众多的轮子中肯定有比你智商高的，他们为啥做这些像你这种智商的人认为很愚蠢的事呢？答案就是你看到和你理解的根本不是真相，这是你的智商低这一硬伤造成的致命缺陷。
> 
> 笑死我了 哈哈。。。你是想说你是这群人里智商比较高的么？当然 不得不承认 在这个群体里 职位高的智商肯定不低 不然会有那么多SB跟随 另外那些台湾景区兼职举牌子的例外 人家是为了赚钱

我就知道你会这么回复，智商低真是你的硬伤。

我从没评论其他人智商，而是只说你的智商：不要对自己不理解的事情胡乱喷，即使轮子是真的如党媒宣传的那样恶，也不应该主动被屏蔽，因为如果允许主动屏蔽恶，则一定会出现权力滥用的情况，去主动屏蔽善，因为善恶的定义因人而异。

**Comment by HOMHOG** [comment]
> > > > 没什么不好 屏蔽这类域名 可以降低你的主机被墙的机率
> > > > 还有这是免费的脚本 没人逼你用 你有其他很多选择
> > > > 况且作者在脚本使用说明里已经添加相关解释
> > > > 单纯这点我支持作者的选择
> > > > ps 不过也可以看出那些抱怨的人 有可能都是轮子关系者
> > > 
> > > 
> > > @linhongjun 我从没见过脑子像你这么愚蠢之人。
> > > 不要随便喷你不了解的事物，你要想一下在如此众多的轮子中肯定有比你智商高的，他们为啥做这些像你这种智商的人认为很愚蠢的事呢？答案就是你看到和你理解的根本不是真相，这是你的智商低这一硬伤造成的致命缺陷。
> > 
> > 
> > 笑死我了 哈哈。。。你是想说你是这群人里智商比较高的么？当然 不得不承认 在这个群体里 职位高的智商肯定不低 不然会有那么多SB跟随 另外那些台湾景区兼职举牌子的例外 人家是为了赚钱
> 
> 我就知道你会这么回复，智商低真是你的硬伤。
> 
> 我从没评论其他人智商，而是只说你的智商：不要对自己不理解的事情胡乱喷，即使轮子是真的如党媒宣传的那样恶，也不应该主动被屏蔽，因为如果允许主动屏蔽恶，则一定会出现权力滥用的情况，去主动屏蔽善，因为善恶的定义因人而异。

你这个思维很符合轮子的思维，翻墙以来也遇到不少了

**Comment by nxtreaming** [comment]
我不支持轮子，就像我不支持屏蔽轮子网站一样。

谁敢说自己所知的信息就是真相？

**Comment by a7611818** [comment]
> 我不支持轮子，就像我不支持屏蔽轮子网站一样。
> 
> 谁敢说自己所知的信息就是真相？

别装理中客了，就这么说吧，假如你有一个女儿，你愿意让你的女儿生活在一个可能接触邪教的圈子里，还是生活在一个可能接触到混混流氓的圈子里？混混顶多骗财骗色，邪教连你命都要骗，还要你帮忙去骗别人的命，不坚决抵制邪教，等于邪教的从犯



除非邪教洗脑害人的故事是编的

**Comment by nxtreaming** [comment]
> > 我不支持轮子，就像我不支持屏蔽轮子网站一样。
> > 谁敢说自己所知的信息就是真相？
> 
> 别装理中客了，就这么说吧，假如你有一个女儿，你愿意让你的女儿生活在一个可能接触邪教的圈子里，还是生活在一个可能接触到混混流氓的圈子里？混混顶多骗财骗色，邪教连你命都要骗，还要你帮忙去骗别人的命，不坚决抵制邪教，等于邪教的从犯
> 
> 除非邪教洗脑害人的故事是编的

如果真的存在你说的邪教行为，那肯定不支持。

但如果某些国家对涉及一切聚集大规模人群的组织、教会、论坛、网站等都封杀，都需要满足censorship，从而杜绝一切可能的思想串连出现，则我个人觉得不应该支持这种封锁行为。，

**Comment by HOMHOG** [comment]
> > > 我不支持轮子，就像我不支持屏蔽轮子网站一样。
> > > 谁敢说自己所知的信息就是真相？
> > 
> > 
> > 别装理中客了，就这么说吧，假如你有一个女儿，你愿意让你的女儿生活在一个可能接触邪教的圈子里，还是生活在一个可能接触到混混流氓的圈子里？混混顶多骗财骗色，邪教连你命都要骗，还要你帮忙去骗别人的命，不坚决抵制邪教，等于邪教的从犯
> > 除非邪教洗脑害人的故事是编的
> 
> 如果真的存在你说的邪教行为，那肯定不支持。
> 
> 但如果某些国家对涉及一切聚集大规模人群的组织、教会、论坛、网站等都封杀，都需要满足censorship，从而杜绝一切可能的思想串连出现，则我个人觉得不应该支持这种封锁行为。，

你这种完全是理想化的不考虑实际的思维，治理中国远比你想得那样照搬西方那一套那么简单，我很认同目前执政党的这种维稳政策，你说的思想串联很容易被西方利用，看香港就知道了，我不想不愿意看到大陆也出现这种动乱，作为普通老百姓我想要的就是稳定，而且我相信大部分中国人也是这样的诉求。而且中国处在发展成长过程中，你的诉求在未来也未必不能得到实现，
但是现阶段，和全球意识形态被美国操纵的环境下，稳定是中国发展的一切前提。

**Comment by nxtreaming** [comment]
@HOMHOG 你说的这些我理解，我对HK的情形没能力评论，因为不同信源会得到完全相反的结论，而我又没能力却确认哪些信源是真的，哪些是假的，回到本issue的正题上来，我的本意是作者不应该由于自己的个人喜恶来屏蔽某些网站，这样不妥当，这和政府屏蔽敏感词实际是一个道理，不应该被支持。

**Comment by zhuhongjie** [comment]
> > > > > 有些人的自我审查是刻在骨子里的，即使网络上翻了墙，脑子还永远留在墙内。正确的做法是彻底换掉这个脚本，用别家的，或者自己搭。
> > > > 
> > > > 
> > > > 作者不是说了屏蔽的是轮子的网站，也没把你咋地
> > > 
> > > 
> > > 我认为，每个人有每个人的看法，是否屏蔽还是得看用户，我不觉得谁可以帮我下决定。
> > 
> > 
> > 那么作者加不加开关这个决定谁来做？你做？
> 
> 哈哈 笑死我了。。。这个就像是有人被强奸的时候 还要求被强奸的人摆好姿势并且享受强奸过程

还笑死了，这不就是你送你妈过来给我艹，完了说太大了疼得慌吗？
