### ISSUE TITLE
腳本能不能改英文

### ISSUE THREAD

**Issue by SZ-MB** [233boy/v2ray#188]
已經參考了網上很多很多改ubuntu顯示亂碼的解決辦法，試過很多次都不成功，中文顯示成“小方格”。。。安裝新字形也解決不了

不知道233boy大能不能把腳本的中文字改成簡單的英文，方便以後簡單使用。。。

謝了

**Comment by 233boy** [comment]
@SZ-MB 
尝试使用 Debian9 看看。

英文的话，可以考虑，但近期内不会提供……

**Comment by lonepair** [comment]
https://github.com/Jrohy/multi-v2ray
