### ISSUE TITLE
还没检测到v2ray v4.18.1的更新,官方已经更新了

### ISSUE THREAD

**Issue by lqhorochi** [233boy/v2ray#189]
还没检测到v2ray v4.18.1的更新,官方已经更新了
麻烦处理一下或者更新一下脚本
建议集成多个加速的BBR和BBRPlus的内核,谢谢!~

**Comment by 233boy** [comment]
@lqhorochi 
因为。。。。那不是正式版本的更新啊。。。
BBR PLUS那些的不集成了，你自己安装即可，贼简单的了
