### ISSUE TITLE
搬瓦工IP和自动脚本配置的IP不一致

### ISSUE THREAD

**Issue by lgp2013** [233boy/v2ray#19]
搬瓦工面板显示的外网IP和自动化脚本安装配置后的信息IP 不一样

**Comment by 233boy** [comment]
@lgp2013 
我这边的瓦工小鸡没有这种问题，不是很清楚原因。但是理论上，脚本获取到的 IP 就是本机的外网 IP 。
或者你在客户端配置的时候手动修改为正确的 IP 地址

**Comment by lgp2013** [comment]
我这个系统曾经配置SSR

**Comment by lgp2013** [comment]
我看了一下配置文件里面获取的IP也是不对的

**Comment by 233boy** [comment]
@lgp2013 
我不太清楚这个原因，我在所有的小鸡上都没有出现这个问题，我的瓦工小鸡也没有。
获取到的 IP 是多少？

**Comment by lgp2013** [comment]
卸载了之前的bbr和ssr IP 就正确了
