### ISSUE TITLE
ws+tls 连接不上

### ISSUE THREAD

**Issue by jyz1022** [233boy/v2ray#192]
提问之前，请先查阅：[V2Ray 一键安装脚本疑问集合](https://v2ray6.com/post/10/)
不管有没有用cloudflare都不行。。下面是错误日志

V2Ray 4.18.0 (Po) 20190228
A unified platform for anti-censorship.
2019/05/03 02:09:35 [Warning] v2ray.com/core: V2Ray 4.18.0 started
2019/05/03 02:09:52 tcp:127.0.0.1:2946 accepted tcp:www.google-analytics.com:443 
2019/05/03 02:09:52 tcp:127.0.0.1:2948 accepted tcp:www.youtube.com:443 
2019/05/03 02:10:02 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://cndota3.top/):  > dial tcp 104.194.79.98:443: connectex: No connection could be made because the target machine actively refused it.] > v2ray.com/core/common/retry: all retry attempts failed
2019/05/03 02:10:03 tcp:127.0.0.1:2956 accepted tcp:www.google-analytics.com:443 
2019/05/03 02:10:03 tcp:127.0.0.1:2957 accepted tcp:www.youtube.com:443 
2019/05/03 02:10:10 tcp:127.0.0.1:2963 accepted tcp:www.taobao.com:443 
2019/05/03 02:10:10 tcp:127.0.0.1:2965 accepted tcp:www.google-analytics.com:443 
2019/05/03 02:10:11 tcp:127.0.0.1:2968 accepted tcp:www.youtube.com:443 
2019/05/03 02:10:13 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://cndota3.top/):  > dial tcp 104.194.79.98:443: connectex: No connection could be made because the target machine actively refused it.] > v2ray.com/core/common/retry: all retry attempts failed
2019/05/03 02:10:14 tcp:127.0.0.1:2972 accepted tcp:www.taobao.com:443 
2019/05/03 02:10:14 tcp:127.0.0.1:2973 accepted tcp:www.google-analytics.com:443 
2019/05/03 02:10:14 tcp:127.0.0.1:2975 accepted tcp:www.youtube.com:443 
2019/05/03 02:10:20 tcp:127.0.0.1:2980 accepted tcp:www.taobao.com:443 
2019/05/03 02:10:23 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://cndota3.top/):  > dial tcp 104.194.79.98:443: connectex: No connection could be made because the target machine actively refused it.] > v2ray.com/core/common/retry: all retry attempts failed
2019/05/03 02:10:24 tcp:127.0.0.1:2983 accepted tcp:www.taobao.com:443 
2019/05/03 02:10:34 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://cndota3.top/):  > dial tcp 104.194.79.98:443: connectex: No connection could be made because the target machine actively refused it.] > v2ray.com/core/common/retry: all retry attempts failed

**Comment by cobnst** [comment]
No connection could be made because the target machine actively refused it
看看是不是防火墙 的原因，
或者你配置的时候 解析域名写的是 www.xxx.xxx  v2ray写的是 xxx.xxx

**Comment by jyz1022** [comment]
> No connection could be made because the target machine actively refused it
> 看看是不是防火墙 的原因，
> 或者你配置的时候 解析域名写的是 [www.xxx.xxx](http://www.xxx.xxx) v2ray写的是 xxx.xxx

搬瓦工的UBUNTU安装时默认没有防火墙。。。而且我写的就是不带WWW的 只有在DNS写了www和@

**Comment by cobnst** [comment]
看看 是不是IP以前就被ban了，我买的是Vultr的日本节点，debian9x64 一键安装下来没有问题

**Comment by RavenHuo** [comment]
> 提问之前，请先查阅：[V2Ray 一键安装脚本疑问集合](https://v2ray6.com/post/10/)
> 不管有没有用cloudflare都不行。。下面是错误日志
> 
> V2Ray 4.18.0 (Po) 20190228
> A unified platform for anti-censorship.
> 2019/05/03 02:09:35 [Warning] v2ray.com/core: V2Ray 4.18.0 started
> 2019/05/03 02:09:52 tcp:127.0.0.1:2946 accepted tcp:www.google-analytics.com:443
> 2019/05/03 02:09:52 tcp:127.0.0.1:2948 accepted tcp:www.youtube.com:443
> 2019/05/03 02:10:02 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://cndota3.top/): > dial tcp 104.194.79.98:443: connectex: No connection could be made because the target machine actively refused it.] > v2ray.com/core/common/retry: all retry attempts failed
> 2019/05/03 02:10:03 tcp:127.0.0.1:2956 accepted tcp:www.google-analytics.com:443
> 2019/05/03 02:10:03 tcp:127.0.0.1:2957 accepted tcp:www.youtube.com:443
> 2019/05/03 02:10:10 tcp:127.0.0.1:2963 accepted tcp:www.taobao.com:443
> 2019/05/03 02:10:10 tcp:127.0.0.1:2965 accepted tcp:www.google-analytics.com:443
> 2019/05/03 02:10:11 tcp:127.0.0.1:2968 accepted tcp:www.youtube.com:443
> 2019/05/03 02:10:13 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://cndota3.top/): > dial tcp 104.194.79.98:443: connectex: No connection could be made because the target machine actively refused it.] > v2ray.com/core/common/retry: all retry attempts failed
> 2019/05/03 02:10:14 tcp:127.0.0.1:2972 accepted tcp:www.taobao.com:443
> 2019/05/03 02:10:14 tcp:127.0.0.1:2973 accepted tcp:www.google-analytics.com:443
> 2019/05/03 02:10:14 tcp:127.0.0.1:2975 accepted tcp:www.youtube.com:443
> 2019/05/03 02:10:20 tcp:127.0.0.1:2980 accepted tcp:www.taobao.com:443
> 2019/05/03 02:10:23 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://cndota3.top/): > dial tcp 104.194.79.98:443: connectex: No connection could be made because the target machine actively refused it.] > v2ray.com/core/common/retry: all retry attempts failed
> 2019/05/03 02:10:24 tcp:127.0.0.1:2983 accepted tcp:www.taobao.com:443
> 2019/05/03 02:10:34 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://cndota3.top/): > dial tcp 104.194.79.98:443: connectex: No connection could be made because the target machine actively refused it.] > v2ray.com/core/common/retry: all retry attempts failed


> 提问之前，请先查阅：[V2Ray 一键安装脚本疑问集合](https://v2ray6.com/post/10/)
> 不管有没有用cloudflare都不行。。下面是错误日志
> 
> V2Ray 4.18.0 (Po) 20190228
> A unified platform for anti-censorship.
> 2019/05/03 02:09:35 [Warning] v2ray.com/core: V2Ray 4.18.0 started
> 2019/05/03 02:09:52 tcp:127.0.0.1:2946 accepted tcp:www.google-analytics.com:443
> 2019/05/03 02:09:52 tcp:127.0.0.1:2948 accepted tcp:www.youtube.com:443
> 2019/05/03 02:10:02 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://cndota3.top/): > dial tcp 104.194.79.98:443: connectex: No connection could be made because the target machine actively refused it.] > v2ray.com/core/common/retry: all retry attempts failed
> 2019/05/03 02:10:03 tcp:127.0.0.1:2956 accepted tcp:www.google-analytics.com:443
> 2019/05/03 02:10:03 tcp:127.0.0.1:2957 accepted tcp:www.youtube.com:443
> 2019/05/03 02:10:10 tcp:127.0.0.1:2963 accepted tcp:www.taobao.com:443
> 2019/05/03 02:10:10 tcp:127.0.0.1:2965 accepted tcp:www.google-analytics.com:443
> 2019/05/03 02:10:11 tcp:127.0.0.1:2968 accepted tcp:www.youtube.com:443
> 2019/05/03 02:10:13 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://cndota3.top/): > dial tcp 104.194.79.98:443: connectex: No connection could be made because the target machine actively refused it.] > v2ray.com/core/common/retry: all retry attempts failed
> 2019/05/03 02:10:14 tcp:127.0.0.1:2972 accepted tcp:www.taobao.com:443
> 2019/05/03 02:10:14 tcp:127.0.0.1:2973 accepted tcp:www.google-analytics.com:443
> 2019/05/03 02:10:14 tcp:127.0.0.1:2975 accepted tcp:www.youtube.com:443
> 2019/05/03 02:10:20 tcp:127.0.0.1:2980 accepted tcp:www.taobao.com:443
> 2019/05/03 02:10:23 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://cndota3.top/): > dial tcp 104.194.79.98:443: connectex: No connection could be made because the target machine actively refused it.] > v2ray.com/core/common/retry: all retry attempts failed
> 2019/05/03 02:10:24 tcp:127.0.0.1:2983 accepted tcp:www.taobao.com:443
> 2019/05/03 02:10:34 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://cndota3.top/): > dial tcp 104.194.79.98:443: connectex: No connection could be made because the target machine actively refused it.] > v2ray.com/core/common/retry: all retry attempts failed

你好，请问解决这个问题了吗

**Comment by sam019** [comment]
同样有这个问题。。。

**Comment by taibin23** [comment]
> 看看 是不是IP以前就被ban了，我买的是Vultr的日本节点，debian9x64 一键安装下来没有问题

ip被ban了就不行吗？我以为这个方法本来就是为了解决被ban ip所以我才安装的

**Comment by hxy493045049** [comment]
同样这个问题

**Comment by kestrelbright** [comment]
同样这个问题...

**Comment by liulizuikeai** [comment]
跟你一样的问题，我已经解决了，我用sudo netstat -tunlp命令看到我的443端口并未有被任何服务使用，我猜测应该是昨天我装V2ray的时候还没有卸载shadowsockesr（我是装完了后才想起卸载的），当时443端口被占用了，导致caddy并没有成功监听443端口，于是我重新安装了v2ray和caddy就好了。

**Comment by edwardwangdh** [comment]
同样问题，昨天突然出现，现在还未解决。

**Comment by mqliutie** [comment]
> 跟你一样的问题，我已经解决了，我用sudo netstat -tunlp命令看到我的443端口并未有被任何服务使用，我猜测应该是昨天我装V2ray的时候还没有卸载shadowsockesr（我是装完了后才想起卸载的），当时443端口被占用了，导致caddy并没有成功监听443端口，于是我重新安装了v2ray和caddy就好了。

我之前是自己配置的 tls,  不好使, 然后我把 nginx的 证书config注释掉, 443 端口也注释掉, 运行了这个脚本后 433 端口目前确实没有被用到... 问题是我刚重装的v2ray并自动配置tls, 它俺咋混个的caddy...

**Comment by eromoe** [comment]
突然出现+1 

重装解决了, 主要问题是 caddy 启动着，但是端口没监听，像是证书授权没通过之类的

**Comment by redstoneleo** [comment]
@eromoe 直接用233boy/v2ray 的脚本卸载了然后重装就可以用了？

**Comment by mqliutie** [comment]
还是推荐vary-ui, 贼好用

**Comment by redstoneleo** [comment]
@mqliutie  没找到vary-ui，给个网址吧

**Comment by mqliutie** [comment]
@redstoneleo 打错了... 
https://github.com/sprov065/v2-ui
