### ISSUE TITLE
failed to load config

### ISSUE THREAD

**Issue by Xman91** [233boy/v2ray#194]
> v2ray
报错如下：
V2Ray 4.18.0 (Po) 20190228
A unified platform for anti-censorship.
main: failed to load config:  > v2ray.com/core/main/confloader/external: config file not readable > open : no such file or directory

**Comment by 233boy** [comment]
@Xman91 
这是服务器那边报的错？？？

**Comment by 610278470** [comment]
@233boy 
这个情况我也遇到了，服务器报错

**Comment by 54huanan** [comment]
go.sh和v2ray.sh都试过，一直报这个错误。
4.19.1版本。
关键是想重启，但杀不掉这个v2ray这个进程。
会被守护进程拉起。

**Comment by 54huanan** [comment]
换个脚本好了
