### ISSUE TITLE
自动更新Kernel破坏BBR

### ISSUE THREAD

**Issue by jameslhc** [233boy/v2ray#196]
搬瓦工自带BBR的CentOS7，用了脚本安装会自动解决一些依赖，但是最大的问题是会自动更新Kernel到5.0，导致自带BBR失效，用BBR一键脚本也安装不上BBR了、

**Comment by 233boy** [comment]
@jameslhc 
```
	sed -i '/net.ipv4.tcp_congestion_control/d' /etc/sysctl.conf
	sed -i '/net.core.default_qdisc/d' /etc/sysctl.conf
	echo "net.ipv4.tcp_congestion_control = bbr" >>/etc/sysctl.conf
	echo "net.core.default_qdisc = fq" >>/etc/sysctl.conf
	sysctl -p >/dev/null 2>&1
```

手动打开 BBR

**Comment by jameslhc** [comment]
这个我在网上也搜到过，但是好像5.0的Kernel有什么特殊配置？我用了之后还是没开启BBR

**Comment by jameslhc** [comment]
更新下，后来换了非BBR版本，Kernel为3.1的，安装v2后再更新支持BBR的4.14Kernel。
如果Kernel本身为4.0版本时，用v2脚本安装时会自动update到5.0

**Comment by 233boy** [comment]
@jameslhc 更新了 BBR 相关，就算内核更新到 5.0 应该也可以打开了
