### ISSUE TITLE
Android Q连接后无法上网

### ISSUE THREAD

**Issue by ChinesePeopleRules** [233boy/v2ray#198]
05-08 17:17:16.431 I/GoLog   (16555): run vpn apps
05-08 17:17:16.431 I/GoLog   (16555): /data/user/0/com.v2ray.ang/tun2socks
05-08 17:17:16.431 I/GoLog   (16555): [--netif-ipaddr 26.26.26.2 --netif-netmask 255.255.255.252 --socks-server-addr 127.0.0.1:10808 --tunfd 51 --tunmtu 1500 --loglevel notice --enable-udprelay --netif-ip6addr da26:2626::2]
05-08 17:17:16.505 W/tun2socks(16594): type=1400 audit(0.0:7095): avc: granted { execute } for path="/data/data/com.v2ray.ang/ArchDep/arm64/tun2socks" dev="sda16" ino=6373693 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=file
05-08 17:17:16.514 I/GoLog   (16555): EscortRun Waiting....
05-08 17:17:16.530 D/tun2socks(16594): NOTICE(tun2socks): initializing BadVPN tun2socks 1.999.130
05-08 17:17:16.530 D/tun2socks(16594): ERROR(BTap): cannot set non-blocking
05-08 17:17:16.530 D/tun2socks(16594): ERROR(tun2socks): BTap_Init2 failed
05-08 17:17:16.530 D/tun2socks(16594): NOTICE(tun2socks): exiting
05-08 17:17:16.531 I/GoLog   (16555): EscortRun cmd.Wait err: exit status 1
05-08 17:17:16.531 I/GoLog   (16555): EscortRun Unexpected Exit
05-08 17:17:16.572 I/GoLog   (16555): EscortRun Waiting....
05-08 17:17:16.580 D/tun2socks(16603): NOTICE(tun2socks): initializing BadVPN tun2socks 1.999.130
05-08 17:17:16.580 D/tun2socks(16603): ERROR(BTap): cannot set non-blocking
05-08 17:17:16.580 D/tun2socks(16603): ERROR(tun2socks): BTap_Init2 failed
05-08 17:17:16.580 D/tun2socks(16603): NOTICE(tun2socks): exiting
05-08 17:17:16.581 I/GoLog   (16555): EscortRun cmd.Wait err: exit status 1
05-08 17:17:16.581 I/GoLog   (16555): EscortRun Unexpected Exit
05-08 17:17:16.615 I/GoLog   (16555): EscortRun Waiting....
05-08 17:17:16.621 D/tun2socks(16607): NOTICE(tun2socks): initializing BadVPN tun2socks 1.999.130
05-08 17:17:16.621 D/tun2socks(16607): ERROR(BTap): cannot set non-blocking
05-08 17:17:16.621 D/tun2socks(16607): ERROR(tun2socks): BTap_Init2 failed
05-08 17:17:16.621 D/tun2socks(16607): NOTICE(tun2socks): exiting
05-08 17:17:16.622 I/GoLog   (16555): EscortRun cmd.Wait err: exit status 1
05-08 17:17:16.622 I/GoLog   (16555): EscortRun Unexpected Exit
05-08 17:17:16.663 I/GoLog   (16555): EscortRun Waiting....
05-08 17:17:16.669 D/tun2socks(16608): NOTICE(tun2socks): initializing BadVPN tun2socks 1.999.130
05-08 17:17:16.669 D/tun2socks(16608): ERROR(BTap): cannot set non-blocking
05-08 17:17:16.669 D/tun2socks(16608): ERROR(tun2socks): BTap_Init2 failed
05-08 17:17:16.669 D/tun2socks(16608): NOTI

升级Android Q beta以后连接v2rayN无法联网

**Comment by QtHeisenberg** [comment]
我的也是

**Comment by ChinesePeopleRules** [comment]
更新到最新版发现问题已经解决了
