### ISSUE TITLE
关于服务器地址配置的问题

### ISSUE THREAD

**Issue by sumeibj** [233boy/v2ray#2]
由于我是在内网建的服务器，在内网通过代理访问外网（内网环境不允许直接访问外网），服务器双网卡（一张接内网一张接外网），但v2ray配置默认获取的是ISP分配的公网地址，与服务器实际的内网地址不一致，尝试直接修改配置文件，但不成功，具体要修改哪个配置呢？

**Comment by 233boy** [comment]
@sumeibj 
客户端配置的时候，地址写上内网地址看看，配置是监听 0.0.0.0 的
