### ISSUE TITLE
建议：ws tls 模式用户向导逻辑优化

### ISSUE THREAD

**Issue by ntgeralt** [233boy/v2ray#200]
你好，我这里建议下：
第一步要求输入“你的域名”；
回车后检测域名ip是否指向此主机。如果不一致则显示错误并要求重填。减少回车之前要求再三确认的警告。

错就错了，让菜鸟用户卡循环。

**Comment by 233boy** [comment]
不知道说什么好，提前你拜年了，祝你新年快乐。

**Comment by ntgeralt** [comment]
我意思是

请将 t4t.com 解析到: 34.80.130.242

 请将 t4t.com 解析到: 34.80.130.242

 请将 t4t.com 解析到: 34.80.130.242

这种确认省掉，检测不通过，再显示这种提示都未迟。
