### ISSUE TITLE
代码已经被删除了吗？code区空白一片

### ISSUE THREAD

**Issue by taibin23** [233boy/v2ray#206]
代码已经被删除了吗？code区空白一片

**Comment by fastkylin** [comment]
作者被请去喝茶了？

**Comment by taibin23** [comment]
真的假的？

kylin <notifications@github.com> 于2019年5月23日周四 上午1:21写道：

**Comment by msn1983aa** [comment]
作者朋友，看到请回复，让大家知道你ok

**Comment by 233boy** [comment]
@taibin23 
活蹦乱跳的 😂

**Comment by taibin23** [comment]
活着就好😎

233boy <notifications@github.com> 于2019年5月25日周六 上午10:18写道：

**Comment by ferristale** [comment]
wiki里面有安装命令，
代码在这https://raw.githubusercontent.com/233boy/v2ray/master/install.sh?v

**Comment by doKill** [comment]
> 你那个是rm分支，点开master就看到

你这。。
