### ISSUE TITLE
节点在v2ray手机端可以用在 pc端有问题

### ISSUE THREAD

**Issue by you-wuhaha** [233boy/v2ray#209]
main: failed to read config file: D:\v2ray\v2ray-windows-64\config.json > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl: v2ray.com/core/infra/conf/command: failed to parse json config > v2ray.com/core/infra/conf/serial: failed to read config file > internal error: polling on unsupported descriptor type
节点在手机上可以用，在PC端用不了，求助

**Comment by lanpangzhi** [comment]
解决了吗

**Comment by fuhua93** [comment]
这个问题解决了吗?我是在ios上可以用,电脑连接不上
