### ISSUE TITLE
建议增加对http2的支持

### ISSUE THREAD

**Issue by achilles78** [233boy/v2ray#21]
首先感谢这个高效的安装工具.
现在v2ray支持http2了,windows下的V2rayN和Android下的V2rayNG也都支持http2了.
能否在你的一键脚本里也增加对http2协议的支持?

**Comment by 233boy** [comment]
@achilles78 
计划中，待增加

**Comment by 233boy** [comment]
90a1e2b 已经支持 HTTP/2，关闭
