### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by JabinHao** [233boy/v2ray#213]
配置完成后输入v2ray报错：command not found

**Comment by 233boy** [comment]
😂 我今天推送了一个更新，可以解决这个问题了，你需要重装，然后安装完了，注销 SSH，之后重新登录 SSH 就会有 v2ray 命令了 @JabinHao

**Comment by CSTD-DD** [comment]
> 😂 我今天推送了一个更新，可以解决这个问题了，你需要重装，然后安装完了，注销 SSH，之后重新登录 SSH 就会有 v2ray 命令了 @JabinHao

您好，刚接触v2ray，我也遇到了一样的问题，今天重新安装并注销重新登陆后仍然提示command not found ，使用您教程中的v2ray update.sh 也提示command  not found，能否指导下如何处理，谢谢

**Comment by afei1997** [comment]
你链接的是普通用户把，我也是普通用户连接的，更改成用root用户连接，再重新安装下就好了

**Comment by CSTD-DD** [comment]
我已经解决了，我使用的是root用户，不过因为我是用的搬瓦工自带的网页shell，不支持中文导致选择错误没有正确安装，才发生了command not found的情况；

**Comment by yuweiyan7** [comment]
> 配置完成后输入v2ray报错：command not found

我也是，请问你有解决吗
