### ISSUE TITLE
建议设置TLS不要hardcode 443端口

### ISSUE THREAD

**Issue by hpkfq** [233boy/v2ray#214]
首先感谢大佬的脚本。

在此提出一个小建议，能否在脚本中添加更改TLS端口的选项。因为很多时候，VPS也用作搭建网站或反向代理的用途，此时443端口已经被监听了，脚本自动指定443端口会造成冲突，caddy无法启动，只能手动修改配置，这对小白来说不太容易了。另外，脚本中生成TLS的vmess链接时好像也是用的hardcode的443端口。

目前，cloudflare开放的SSL端口有以下：
443
2053
2083
2087
2096
8443
来源：https://support.cloudflare.com/hc/en-us/articles/200169156-Which-ports-will-Cloudflare-work-with-

**Comment by iwlei** [comment]
我现在就是这个情况，自己vps还搭建了网站，端口冲突导致caddy没有启动。求问怎么修改？

**Comment by hpkfq** [comment]
> 我现在就是这个情况，自己vps还搭建了网站，端口冲突导致caddy没有启动。求问怎么修改？

我是手动用nginx把v2ray的端口反代成2096，然后手动改了客户端json的端口为2096。
还是建议脚本能增加修改SSL端口的选项

**Comment by huxiaofan1223** [comment]
我也是，搞得我为了fq把网站给停了，停了就停了吧，懒得搞了。脚本不报错搞得我找了好久原因。

**Comment by iwlei** [comment]
> 我是手动用nginx把v2ray的端口反代成2096，然后手动改了客户端json的端口为2096。
> 还是建议脚本能增加修改SSL端口的选项
搞不懂，我是瞎搞的，最后我是直接按路径去改了caddy的配置文件，把端口成了你上面列的其中之一，现在v2是正常的，不过我的网站全部报404了。。。。

**Comment by huxiaofan1223** [comment]
改端口还不如改path

**Comment by iwlei** [comment]
> 改端口还不如改path

我要是知道怎么操作就不会来问了，网站也不是很重要，停了就停了，反正已经被墙了，直接也访问不了。

**Comment by AstralHope** [comment]
所以TLS下应该怎么设置nginx？proxy_pass设置到443用不了

**Comment by huxiaofan1223** [comment]
一键脚本好像并不支持改path，可以修改官方v2ray配置文件来修改，
https://www.madeliang.cn/archives/688.html，这个是老马的教程，感谢老马。

关键
config.json:

         "streamSettings": {
             "network": "ws",
             "wsSettings": {
                 "path": "/path"
             }
         }

nginx.conf

server {
    listen 80;
    server_name v2.huxiaofan1223.tk;
    return 301 https://$server_name$request_uri;
}
server {
    listen               443 ssl http2 default_server;
    root                 /usr/share/nginx/html;
    server_name       domain.com;
    ssl_certificate      /domain.cer;   
    ssl_certificate_key  /domain.key;    #ssl证书
    ssl_session_cache shared:SSL:1m;
    ssl_session_timeout   10m;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    location /path {
         proxy_pass            http://127.0.0.1:v2ray_listen_port;    #自行定义v2ray端口
         proxy_connect_timeout 600;
         proxy_read_timeout    600;
         proxy_http_version    1.1;
         proxy_set_header      Upgrade     $http_upgrade;
         proxy_set_header      Connection  "upgrade";
     }
}

**Comment by edorphin** [comment]
建议挺好 现在只能自己手动修改

**Comment by AstralHope** [comment]
我需要挂443端口的已经改用了官方的脚本
