### ISSUE TITLE
Win下v2rayN，如何讓應用程式走代理？

### ISSUE THREAD

**Issue by avorewong** [233boy/v2ray#215]
Chrome/Firefox上網都沒有問題，但是有些應用程式是不走代理服務器的。
比如Win下的CMD，Ping不到外網ip。
再比如Xshell（我沒有用Xshell，用的是Rlogin）和Filezilla都連不上被墻了的ip，請問如何設置，謝謝。

**Comment by Eveaz** [comment]
SocksCap64和Proxifier

**Comment by gonnalee** [comment]
proxifier
