### ISSUE TITLE
用了一键脚本部署在谷歌云上，但是mac客户端怎么也连不上。

### ISSUE THREAD

**Issue by pepperdog999** [233boy/v2ray#216]
采用的是ws+tls，服务端安装正常，运行状态也正常。但是mac客户端怎么也连不上。换了好几个工具都一样。

**Comment by MichealShin** [comment]
你肯定是忘记把端口给开了

**Comment by chalau** [comment]
我也是：两个不同的服务器（相同的设置方法（iptables端口已打开））+两个不同的客户端（相同的设置方法），一台服务器连得上、另一台（客户端打开SS/V2ray）服务器马上断开，有劳各位指点迷津

**Comment by chalau** [comment]
2019/06/06 23:26:32 [Warning] [3985815691] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: unable to set read deadline > v2ray.com/core/transport/internet/kcp: Connection closed.
2019/06/06 23:27:45 [Warning] [927318121] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: unable to set read deadline > v2ray.com/core/transport/internet/kcp: Connection closed.

**Comment by 233boy** [comment]
@pepperdog999 
MAC 屁事多不适合小白
或者请按照这个教程来操作：https://233v2.com/post/17/

**Comment by michaelpassion** [comment]
同，Mac死活连接不上报错如下：
2019/06/14 16:36:40 [Warning] [873300362] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://michaelpassion.xyz/):  > dial tcp: lookup michaelpassion.xyz on 10.0.131.29:53: read udp 192.168.251.36:63534->10.0.131.29:53: i/o timeout v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://michaelpassion.xyz/):  > dial tcp: i/o timeout v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://michaelpassion.xyz/):  > dial tcp: lookup michaelpassion.xyz on 10.0.131.29:53: read udp 192.168.251.36:62465->10.0.131.29:53: i/o timeout v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://michaelpassion.xyz/):  > dial tcp: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed

**Comment by pepperdog999** [comment]
mac的两个客户端，在配置文件中都和V2rayNg不兼容，真是头疼。
补充一下，现在已经搞定了，把v2rayx的版本降到1.3后成功！！

**Comment by icearl** [comment]
mac上的配置和mac客户端连接方式按这个：
https://233v2.com/post/17/
文中提到的客户端的另一个选择，亲测也可以哦：
https://github.com/yanue/v2rayu/wiki
