### ISSUE TITLE
提个醒

### ISSUE THREAD

**Issue by SekiBetu** [233boy/v2ray#217]
v2ray部分原作者因为很久不上线，部分成员权限不足，fork了一个镜像项目https://github.com/v2fly/v2ray-core
跟进维护中

**Comment by DXDE443** [comment]
看了下这个的最新release是14 Apr 4.18.1 而[v2ray/v2ray-core](https://github.com/v2ray/v2ray-core/releases)是v4.19.1啊

**Comment by zhz1237ok** [comment]
> 看了下这个的最新release是14 Apr 4.18.1 而[v2ray/v2ray-core](https://github.com/v2ray/v2ray-core/releases)是v4.19.1啊

分出去了
This branch is 43 commits ahead, 13 commits behind v2ray:master.
原项目还是有人在维护，但是主要的人不在了，所以才会造成这样分家的局面

**Comment by 233boy** [comment]
@zhz1237ok 
我知道的
