### ISSUE TITLE
希望能配置一个隔一段时间自动重启的服务

### ISSUE THREAD

**Issue by zhuanjiaozm** [233boy/v2ray#22]
不知道什么原因，有的时候连接上后不能正常代理，感觉像是卡主了一样，一动不动的，但是手动重启服务端就瞬间秒好了，因此希望有个配置每隔一定时间自动重启的功能。

**Comment by 233boy** [comment]
@zhuanjiaozm 
你好，我抱歉，目前这种情况建议自己搞定，写个 Crontab 就行，也许以后会增加。
