### ISSUE TITLE
請問在arm64 ubuntu系統上如何安裝

### ISSUE THREAD

**Issue by Mattaclp** [233boy/v2ray#221]
請問是否因為它用的是v2ray-linux-arm64.zip？腳本會自動選取嗎？

顯示：哈哈……这个 辣鸡脚本 不支持你的系统。 (-_-)

搞不懂問題所在，請指教，謝謝

**Comment by 233boy** [comment]
@Mattaclp 
很抱歉这个是脚本限制的问题。目前暂时不支持在这个系统上安装

**Comment by Mattaclp** [comment]
謝謝你更新,現在ARM系統可以正常安裝了
萬分感激

**Comment by 233boy** [comment]
> 謝謝你更新,現在ARM系統可以正常安裝了
> 萬分感激

😂 就是最近更新支持的，忘记说了。
