### ISSUE TITLE
我是不知道怎么救活被墙ip的鶸

### ISSUE THREAD

**Issue by mumusa** [233boy/v2ray#223]
https://github.com/233boy/v2ray/wiki/%E4%BD%BF%E7%94%A8Cloudflare%E4%B8%AD%E8%BD%ACV2Ray%E6%B5%81%E9%87%8F

ip 已经一天ping不通了，希望大佬指点如何救活

**Comment by 1688aa** [comment]
Cloudflare本身在边缘游走，速度非常慢，我这里只有100kb以下的速度

**Comment by slum63r** [comment]
i can help you if you don't mind. my vps and my friends' are both banned several days ago, and i tried the way you pasted  and then it worked. sry for replying you in english, i don't install chinese input method on my pc.

**Comment by mumusa** [comment]
@1688aa 找到两篇教程结果卡在，注册免费域名这里，注册免费域名时提示无法验证当前操作者是否为机器人(；一_一)

**Comment by mumusa** [comment]
@slum63r 不甚感激，可否提供哪个网站好注册免费域名及无限ip的设置步骤ʕ•ٹ•ʔ

**Comment by slum63r** [comment]
我不太清楚在哪注册免费域名，因为我早前就有一个域名。如果你仅仅用域名来翻墙不是做网站的话，可以在www.dynadot.com之类的网站购买一年的域名，我当初买第一年花了8块钱。如果你不介意的话也可以使用我的域名。

**Comment by mumusa** [comment]
> 我不太清楚在哪注册免费域名，因为我早前就有一个域名。如果你仅仅用域名来翻墙不是做网站的话，可以在www.dynadot.com之类的网站购买一年的域名，我当初买第一年花了8块钱。如果你不介意的话也可以使用我的域名。

感谢你的好意，我又重新换了一个ip 🙏

**Comment by mumusa** [comment]
> 我不太清楚在哪注册免费域名，因为我早前就有一个域名。如果你仅仅用域名来翻墙不是做网站的话，可以在www.dynadot.com之类的网站购买一年的域名，我当初买第一年花了8块钱。如果你不介意的话也可以使用我的域名。

[自己在狗爹上买了个域名配好啦，后面的小伙伴可以看这里教程](https://blog.sprov.xyz/2019/03/11/cdn-v2ray-safe-proxy/)

**Comment by 1688aa** [comment]
> @ slum63r不甚感激，可否提供哪个网站好注册免费域名及无限IP的设置步骤ʕ•ٹ•ʔ

我曾经用DNSPod的4元一个的域名

**Comment by mumusa** [comment]
@1688aa 狗爹这个也不算贵，九块 下一步看能不能折腾好无限域名备用
