### ISSUE TITLE
Ubuntu 19.04 提示脚本不支持

### ISSUE THREAD

**Issue by alwzying** [233boy/v2ray#225]
如题，发行版为Ubuntu budgie 19.04

**Comment by KickUasS** [comment]
18.04也提示不支持，看了一下SH脚本，应该是语法和Ubuntu的bash不兼容？
233大大费心处理一下呀

**Comment by KickUasS** [comment]
我尝试去掉脚本里面的系统验证，不过依然会有其他的错误，例如函数书写错误，unexpected [,(之类的
