### ISSUE TITLE
quic+utp不能用

### ISSUE THREAD

**Issue by edorphin** [233boy/v2ray#227]
之所以选择quic就是为了想降低延迟 但是无法使用 查找原因未知 系统Debian9

**Comment by 233boy** [comment]
@edorphin 
这个可能需要在客户端这边手动配置，而不是直接使用脚本导出的链接或者生成二维码之类的

**Comment by edorphin** [comment]
@233boy 我是手动配置的 但确实没用 客户端三个平台都没用

**Comment by crawt** [comment]
@233boy 配置似乎应该修改一下原配置带加密方式的似乎无法直接使用，我暂时没找到原因，但是尝试更改成如下配置可以使用, 关键修改为 "security" 改成"none", 如果为默认的加密方式似乎需要自己配置ssl证书才行
`			"streamSettings": {
				"network": "quic",
				"quicSettings": {
					"security": "none",
					"key": "",
					"header": {
						"type": "none"
					}
				}
			},
`

**Comment by edorphin** [comment]
@crawt 有道理 抽空我去试试 也好好找下原因

**Comment by amosbird** [comment]
@crawt 我试了下 none 依然不行, 服务端能收到相关udp包但是没有reply. 能共享一下完整的client server配置吗? 谢谢
