### ISSUE TITLE
移动4g连接缓慢，wifi正常

### ISSUE THREAD

**Issue by huige666a** [233boy/v2ray#230]
最近几天wifi速度代理正常，速度较快，但是一旦用移动4g便特别慢，只有20kb左右。有大佬知道如何解决吗

**Comment by c10854** [comment]
移动宽带同样慢  宽带大概只能到4m带宽   联通可以跑到免费上限100m带宽

**Comment by asd123wto** [comment]
之前用ssr移动被卡的死死的，最近移动ssr速度上去了，电信又开始限速。我在考虑换v2ray不
