### ISSUE TITLE
ws+tls+cf反应慢

### ISSUE THREAD

**Issue by underlaw** [233boy/v2ray#231]
搬瓦工 v2ray 采用ws+tls+cf，反应速度挺慢的，我用的网上免费的ws+tls+cf的ws分享链接，反应明显比我的自己的快。
请问这是什么情况

**Comment by 233boy** [comment]
@underlaw 
恭喜你用了真实的 CF。

**Comment by caoerlei** [comment]
能翻过去就可以了， 要求越多越容易挂，哈哈哈

**Comment by underlaw** [comment]
> @underlaw
> 恭喜你用了真实的 CF。

怎么还有假的CF吗，好像除了这模式，其它的基本废物了吧。兄弟听说你给国家屏蔽一些网站了 嘿嘿

**Comment by Jyougen** [comment]
@underlaw  cf都用上了, 就不要纠结速度的问题了(滑稽)

**Comment by gonnalee** [comment]
套了cf就有很多不稳定因素，毕竟用的别人免费服务。二是cf被大量使用也导致cf很多ip被ban，大量丢包。
