### ISSUE TITLE
运行脚本失败是什么原因

### ISSUE THREAD

**Issue by jiangfeng0205** [233boy/v2ray#232]
![image](https://user-images.githubusercontent.com/21293065/59420379-660fd000-8dff-11e9-9385-e11945512adc.png)
系统是：Centos 7 x86_64 bbr  
vps是搬瓦工，ip国内被ban。
为什么会这样？

**Comment by ChenQi960219** [comment]
我也有这样的问题 各种版本系统安装脚本会出现这个问题 我花钱换了个ip 办了机房 在跟着教程走就没有问题了

**Comment by jiangfeng0205** [comment]
> 我也有这样的问题 各种版本系统安装脚本会出现这个问题 我花钱换了个ip 办了机房 在跟着教程走就没有问题了
嗯，应该是ip被ban的原因，需要付费换ip。

**Comment by T2Je** [comment]
> ![image](https://user-images.githubusercontent.com/21293065/59420379-660fd000-8dff-11e9-9385-e11945512adc.png)
> 系统是：Centos 7 x86_64 bbr
> vps是搬瓦工，ip国内被ban。
> 为什么会这样？

你这是在basic shell上运行的吧？需要在interactive shell 上运行这个脚本
