### ISSUE TITLE
关于nat vps 使用Cloudflare中转V2Ray流量的问题

### ISSUE THREAD

**Issue by uragasit** [233boy/v2ray#233]
按照教程走到域名解析这一步，明明在cloudflare里填的域名对应的是vps公网ip解析，但是在ssh里面一键v2ray最后一步解析出来却成了10.10.x.x这样的内网ip并提示你的域名没有正确解析，安装失败。这种nat vps的情况版大能不能教教怎么解析啊，本人小白一枚

**Comment by 233boy** [comment]
@uragasit 
手上没有 NAT VPS 不是很清楚这个情况，不过我觉得你可以试试看在 /etc/hosts 将域名解析写死，然后脚本应该就不会提示错误了。。但是我不认为这是一个好的解决方案 😂 毕竟是 NAT
