### ISSUE TITLE
为啥不支持 Mac os 哇

### ISSUE THREAD

**Issue by T2Je** [233boy/v2ray#234]
@233boy

**Comment by 233boy** [comment]
@T2Je 
什么鬼呀

**Comment by T2Je** [comment]
你的脚本好像不支持macOS 啊

**Comment by T2Je** [comment]
弱弱的问下，v2ray是在 banwagong 的VPS上安装还是在我自己的电脑上装

**Comment by 233boy** [comment]
> 弱弱的问下，v2ray是在 banwagong 的VPS上安装还是在我自己的电脑上装

大哥。。。你这也太可爱了吧 😂 😂 

当然是在 VPS 上面安装啊。。。电脑上用 客户端来配置使用即可

**Comment by T2Je** [comment]
thank u 😁

**Comment by T2Je** [comment]
已解决
