### ISSUE TITLE
ws+tls连上 ping能通,但是不能用

### ISSUE THREAD

**Issue by a545254328** [233boy/v2ray#237]
ws+tls之前也可以用一直没问题,下午的时候卸载掉搞过其他脚本,重新装回这个脚本之后,需要域名解析的协议全部不能用,再电脑客户端测试连接延迟10ms左右,./'/现在tcp协议使用中  ,这个问题怎么解决?

**Comment by a545254328** [comment]
failed to handler mux client connection > Proxy|VMess|Outbound: failed to find an available destination > Retry: [Transport|Internet|WebSocket: failed to dial WebSocket >

**Comment by sam019** [comment]
同问

**Comment by sam019** [comment]
可以用 flyzy 小站这个微信小程序看看端口 tcp 是不是通的, 我的从国内国外都挂了...
