### ISSUE TITLE
申请证书次数过多了怎么办

### ISSUE THREAD

**Issue by daoshengwanwu** [233boy/v2ray#238]
不知重装了多少次vps系统 使用脚本安装v2ray （ws + tls) 最后caddy开不起来了，看log发现说是证书申请达到上限了。。
怎么配置一下能够突破上限呢...

**Comment by namingissohard** [comment]
cent os7我也重装了几次系统和脚本 我的caddy也一直开不起来   一直是在 运行一瞬间=>重启=>运行一瞬间 
log 也没什么报错
最绝望的就是没报错。。。
