### ISSUE TITLE
..由于你的 VPS 内核支持开启 BBR ...已经为你启用 BBR 优化....

### ISSUE THREAD

**Issue by 1265578519** [233boy/v2ray#239]
安装脚本前内核
CentOS Linux release 7.6.1810 (Core) 
Linux version 5.1.10-1.el7.elrepo.x86_64 (mockbuild@Build64R7) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)) #1 SMP Sat Jun 15 07:02:23 EDT 2019
net.ipv4.tcp_available_congestion_control = reno cubic bbr
net.ipv4.tcp_congestion_control = bbr
net.core.default_qdisc = fq
tcp_bbr                20480  13

安装后内核
CentOS Linux release 7.6.1810 (Core) 
Linux version 3.10.0-957.21.2.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) ) #1 SMP Wed Jun 5 14:26:44 UTC 2019
net.ipv4.tcp_available_congestion_control = cubic reno
net.ipv4.tcp_congestion_control = cubic
net.core.default_qdisc = fq

 1. 安装 BBR

 2. 安装 LotServer(锐速)

 3. 卸载 LotServer(锐速)

请选择 [1-3]:1

 BBR 已经启用啦...无需再安装

bbr没了。。

**Comment by ntgeralt** [comment]
我印象他不会装bbr内核，只会改/etc/sysctl.conf来开启bbr。当然其实开bbr作为可选项更好。我PVE鸡机已经开BBR，用这脚本时小鸡也自动开
