### ISSUE TITLE
Dedian9无法升级脚本

### ISSUE THREAD

**Issue by chenxuan5858** [233boy/v2ray#24]
debian9升级脚本，显示此脚本不支持此系统，请退回原脚本，还有脚本更新V2ray core，三位版本号的更新无法获取。

**Comment by 233boy** [comment]
@chenxuan5858 
那不是无法升级，那是回退，不过现在不会出现这种清楚，使用 `v2ray update.sh` 更新即可
脚本只会获取 V2Ray 的 releases 版本。
