### ISSUE TITLE
ws+tls 如何配置git的代理

### ISSUE THREAD

**Issue by DDullahan** [233boy/v2ray#240]
本地监听2334
git配置
`git config --global http.proxy 'socks5://127.0.0.1:2334'
git config --global https.proxy 'socks5://127.0.0.1:2334`
后提示connection abort 
v2ray日志显示'unknown Socks version: 67'

**Comment by gonnalee** [comment]
用一些把socket5代理转成全局代理的工具软件，例如proxifier。可以在软件中配置，让git走代理，或者全部走代理，或者某些域名走代理。很灵活

**Comment by DDullahan** [comment]
可以了 谢谢 @gonnalee
