### ISSUE TITLE
运行脚本错误， “输入错误”

### ISSUE THREAD

**Issue by T2Je** [233boy/v2ray#241]
![image](https://user-images.githubusercontent.com/8908302/59576698-3c9ebf00-90f3-11e9-8374-5c053e9a61af.png)

<img width="630" alt="kiwiError@2x" src="https://user-images.githubusercontent.com/8908302/59576390-2c3a1480-90f2-11e9-81f1-2b7754dcd859.png">

![image](https://user-images.githubusercontent.com/8908302/59576460-715e4680-90f2-11e9-970d-ec6111c787c6.png)
 按照教程 装了Debian 9  （x86-64）系统，但是运行脚本出错，不知道哪里出错了，还请大佬出面释疑

**Comment by T2Je** [comment]
这是在 vps 上basic shell  运行的，换个interactive shell 就可以了，或者用ssh 客户端连VPS

**Comment by dingpengqiang** [comment]
我在Interactive Shell上输入命令之后啥反应也没有，是什么情况 
![image](https://user-images.githubusercontent.com/20593092/59965158-eb505e80-953c-11e9-8d16-1b3eb6b2a224.png)

**Comment by T2Je** [comment]
> 我在Interactive Shell上输入命令之后啥反应也没有，是什么情况
> ![image](https://user-images.githubusercontent.com/20593092/59965158-eb505e80-953c-11e9-8d16-1b3eb6b2a224.png)

没遇到过这种情况，你要不在VPS上写个简单脚本，用在basic shell 里面bash 试一下呢？实在不行就在 VPS上直接安装 Debian 9 系统吧😂
