### ISSUE TITLE
老版本的脚本怎么升级？

### ISSUE THREAD

**Issue by lukemin** [233boy/v2ray#246]
V2Ray 客户端使用教程: https://v2ray6.com/post/4/

提示: 输入 v2ray url 可生成 vmess URL 链接 / 输入 v2ray qr 可生成二维码链接

**Comment by lukemin** [comment]
Root： v2ray update.sh

 木有发现新版本

**Comment by 233boy** [comment]
@lukemin 
重装吧
`v2ray reinstall`
