### ISSUE TITLE
用V2ray+CF 复活被ban IP，是不是还是不能用ssh客户端连vps？

### ISSUE THREAD

**Issue by T2Je** [233boy/v2ray#247]

**Comment by jayzh1010** [comment]
用vps的管理后台

**Comment by T2Je** [comment]
嗯嗯，就是用的很难受 @jayzh1010

**Comment by jayzh1010** [comment]
> 嗯嗯，就是用的很难受 @jayzh1010

如果有国内服务器和域名的话，可以做下内网传透，来反向代理国外的ssh端口

**Comment by T2Je** [comment]
这块知识匮乏，我抽时间来补一补，感谢🤝

**Comment by jayzh1010** [comment]
说错了，是国内服务器和ip。一不小心写成域名了 😓

**Comment by gitLinan** [comment]
> 说错了，是国内服务器和ip。一不小心写成域名了 😓

如果被被墙  国内的服务器也是访问不到的吧，反向代理可以做到？

**Comment by jayzh1010** [comment]
> > 说错了，是国内服务器和ip。一不小心写成域名了 😓
> 
> 如果被被墙 国内的服务器也是访问不到的吧，反向代理可以做到？

嗯，刚试了下。确实不行。之前以为是只阻断了出去的路，没想到进来的路也阻断了。我的锅。给楼主说声抱歉

**Comment by T2Je** [comment]
@jayzh1010  没事啦，也谢谢你@gitLinan

**Comment by czb1994** [comment]
去设置下,把你的被banip设置成走代理就好了

**Comment by T2Je** [comment]
> 去设置下,把你的被banip设置成走代理就好了

能详细的解释下吗🤔？

**Comment by jayzh1010** [comment]
ssh -o ProxyCommand='nc -x 127.0.0.1:{socks_port} {server_ip} 22' user@server_ip

这个试过了，可用，我这上边是默认22端口的，你可以改成自己的

@T2Je

**Comment by gonnalee** [comment]
ssh到vps时，让ssh到你ip也通过代理。ssh默认不通过本地的socket5代理的，你可以用一些软件例如proxifier让ssh走代理

**Comment by lliurf** [comment]
应该是如果你用pc端v2ray客户端，ssh客户端里面要设置本地代理。如果你用路由器里的客户端，ssh客户端不用设置本地代理。
