### ISSUE TITLE
可否考虑在脚本上添加上对arm处理器的支持？

### ISSUE THREAD

**Issue by ShengCSD** [233boy/v2ray#248]
脚本写的很方便。
但目前脚本中只是判断了32/64位

为了用这个脚本装在树莓派3B上，手动在脚本中加上
`elif [[ $sys_bit == "armv7l" ]]; then
	v2ray_bit="arm"`
以及download-caddy.sh中下载地址里加上
`https://caddyserver.com/download/linux/arm7?license=personal`

亲测在树莓派3B(官方系统Debian 9.3)上 用Websocket+TLS是可用的。其他没试
脚本写这么好用，建议加上arm处理器的支持，帮助更多人。

**Comment by 233boy** [comment]
@ShengCSD 
搞定了。。。 原来要默认分支才能直接 close。。。
