### ISSUE TITLE
centos7 GCP安装完bbr后就不能用了

### ISSUE THREAD

**Issue by hackeye** [233boy/v2ray#25]
提问之前，请先查阅：[V2Ray 一键安装脚本疑问集合](https://233blog.com/post/27/)

若需要发起提问，请删除这些内容

**Comment by 233boy** [comment]
@hackeye 
不存在的。

**Comment by hackeye** [comment]
我看了你之前的回答，在debian9中端口得改成80才行，但我没太看懂你所说的防火墙里面的标签问题，能否解答一下

**Comment by 233boy** [comment]
@hackeye 
https://233blog.com/post/30/

**Comment by hackeye** [comment]
防火墙规则修改以后centos7也可以了，不过通过我的试验来看锐速的加速效果更好，仅是个人观点。感谢，希望脚本越做越完善。
