### ISSUE TITLE
-bash: /usr/local/bin/v2ray: No such file or directory

### ISSUE THREAD

**Issue by TujinLee** [233boy/v2ray#251]
安装完脚本后，输入 vray 提示以上错误。系统是CentOS 7 x64

**Comment by TujinLee** [comment]
具体如下：
........... V2Ray 一键安装脚本 & 管理脚本 by 233v2.com ..........

帮助说明: https://233v2.com/post/1/

搭建教程: https://233v2.com/post/2/

 1. 安装

 2. 卸载

请选择 [1-2]:1

 大佬...你已经安装 V2Ray 啦...无需重新安装

 输入 v2ray 即可管理 V2Ray

[root@vultr ~]# v2ray
-bash: /usr/local/bin/v2ray: No such file or directory
[root@vultr ~]#

**Comment by 233boy** [comment]
@TujinLee 
又是 CentOS....

你重新登录  SSH 就有了

**Comment by oldzhg** [comment]
也遇到同样的问题 可以close了
