### ISSUE TITLE
脚本没问题，只是V2ray 完全不能用，换成shadowsock凑合能用

### ISSUE THREAD

**Issue by os9sur** [233boy/v2ray#252]
每天晚上shadowsocks 就变的很慢而且不稳定时断时续
所以考虑换V2ray，
但是经过了各种尝试，全都不行
脚本没问题，只是V2ray 完全不能用，换成shadowsock凑合能用

**Comment by xukongop** [comment]
我也遇到了相同的情况，Vmess协议不能用，ShadowSocks可以用

**Comment by eric0ca0** [comment]
我的还能用，你们别吓我，我最近于6月9日更新过v2ray，不知道你们是否在最近更新过？

**Comment by xukongop** [comment]
> 我的还能用，你们别吓我，我最近于6月9日更新过v2ray，不知道你们是否在最近更新过？

嗯，用的是最新版

**Comment by eric0ca0** [comment]
> > 我的还能用，你们别吓我，我最近于6月9日更新过v2ray，不知道你们是否在最近更新过？
> 
> 嗯，用的是最新版

那就不知道了，最近只换过ip端口，未试过重新搭建。
我也不知道这段时间更新了什么。我只是在那天才改ip顺手升级了。

**Comment by 233boy** [comment]
@White99 
时间对得上么。。。输入 `date` 看看

**Comment by xukongop** [comment]
> @White99
> 时间对得上么。。。输入 `date` 看看

果然是时辰的错，我竟然忽略了这么重要的问题2333

**Comment by White99** [comment]
> > @White99
> > 时间对得上么。。。输入 `date` 看看
> 
> 果然是时辰的错，我竟然忽略了这么重要的问题2333

啥时间设置？怎么设置的请问？

**Comment by jiqing112** [comment]
我也是，时间是对的。也是完全照着教程来的。v2ray就是不能用，我都有点怀疑我的认识了

**Comment by gonnalee** [comment]
> 我也是，时间是对的。也是完全照着教程来的。v2ray就是不能用，我都有点怀疑我的认识了

看看日志

**Comment by houyuehai** [comment]
我野是按照教程来的。ss可以连接。vmess不行

**Comment by houyuehai** [comment]
我把协议换成udp就可以了

**Comment by SM-N920T** [comment]
> 我把协议换成udp就可以了

请问udp是系统还是协议？
