### ISSUE TITLE
TCP_dynamicPort

### ISSUE THREAD

**Issue by delphinuz** [233boy/v2ray#253]
结束的port是比开始还大的，但一直出现这讯息。

" V2Ray 动态端口结束范围 不能包括 V2Ray 端口 "

**Comment by 233boy** [comment]
@delphinuz 
假设 V2Ray 端口是 2，动态端口开始是 1，动态结束端口是 3，那么就不可以。明白？

**Comment by delphinuz** [comment]
測試了幾個範圍，知道問題在哪了。

若目前使用port 1300，開始設定1200，結束1500，那就會出現這訊息。改到1301~1500就没問題。
簡單說，V2Ray的port，不能被包括在動態port的範圍中。
