### ISSUE TITLE
求代写配置文件！

### ISSUE THREAD

**Issue by anxuanzi** [233boy/v2ray#254]
大佬，我搞配置文件遇到了些问题，可否帮忙代写？付费也没问题，帮忙搞一下就行。我的情况在脚本里没有

**Comment by 233boy** [comment]
@anxuanzi 
什么问题。。

**Comment by anxuanzi** [comment]
额，解决了，谢谢啦

**Comment by anxuanzi** [comment]
我还是需要帮助，希望您能帮忙搞一下，我可以付费请您帮忙处理，可否加个QQ：2293968001

**Comment by anxuanzi** [comment]
大佬，快来帮帮我吧！
