### ISSUE TITLE
请问Caddy必须要占用80和443端口吗？

### ISSUE THREAD

**Issue by PineSongCN** [233boy/v2ray#256]
我这边服务器上自搭了网站，所以Caddy自动配置后无法启动....

**Comment by gonnalee** [comment]
一般来说这种反向代理和网站都想监听80，443端口，肯定是把反向代理服务器监听80，443，然后特定的域名或者路径转发到本地的网站。这个需要根据自己的情况手动修改caddy配置文件

**Comment by PineSongCN** [comment]
> 一般来说这种反向代理和网站都想监听80，443端口，肯定是把反向代理服务器监听80，443，然后特定的域名或者路径转发到本地的网站。这个需要根据自己的情况手动修改caddy配置文件

谢谢，请问有没相关教程推荐？

**Comment by dshvv** [comment]
你解决了吗  我也遇到了这个问题呢

**Comment by liwenjie119** [comment]
我也想知道怎么把caddy改到别的端口

**Comment by PineSongCN** [comment]
> 你解决了吗 我也遇到了这个问题呢

没有，不理解为什么这么做，所以没办法搜索替代方案

**Comment by gonnalee** [comment]
> 没有，不理解为什么这么做，所以没办法搜索替代方案

是因为你开启了脚本中的启用caddy分流伪装，caddy作为反向代理服务器，本身就是做这个工作的。你可以让caddy接管80，443端口，如果访问特定的路径，caddy把流量转发到v2ray服务器，其他路径转发到你的网站站，这样在外人看来，访问你的域名，就好像是一个普通的网站。这样就达到了伪装的目的。除了你自己知道特殊路径转发到v2ray，每个人都以为是个普通网站。如果不想用伪装功能，用脚本的时候你选择不开启即可。

或者下面这样设置caddy配置文件：
```
domain.com:443 {
    tls 32414344@gmail.com
    timeouts none
    proxy /v2ray 127.0.0.1:3333 {
        websocket
    }
    proxy / mask.com:80 {
        except /v2ray
    }
}
```

**Comment by PineSongCN** [comment]
> > 没有，不理解为什么这么做，所以没办法搜索替代方案
> 
> 是因为你开启了脚本中的启用caddy分流伪装，caddy作为反向代理服务器，本身就是做这个工作的。你可以让caddy接管80，443端口，如果访问特定的路径，caddy把流量转发到v2ray服务器，其他路径转发到你的网站站，这样在外人看来，访问你的域名，就好像是一个普通的网站。这样就达到了伪装的目的。除了你自己知道特殊路径转发到v2ray，每个人都以为是个普通网站。如果不想用伪装功能，用脚本的时候你选择不开启即可。
> 
> 或者下面这样设置caddy配置文件：
> 
> ```
> domain.com:443 {
>     tls 32414344@gmail.com
>     timeouts none
>     proxy /v2ray 127.0.0.1:3333 {
>         websocket
>     }
>     proxy / mask.com:80 {
>         except /v2ray
>     }
> }
> ```

谢谢...

**Comment by John4d3** [comment]
求一个修改caddy端口的方案。。

**Comment by shijia7** [comment]
> > 没有，不理解为什么这么做，所以没办法搜索替代方案
> 
> 是因为你开启了脚本中的启用caddy分流伪装，caddy作为反向代理服务器，本身就是做这个工作的。你可以让caddy接管80，443端口，如果访问特定的路径，caddy把流量转发到v2ray服务器，其他路径转发到你的网站站，这样在外人看来，访问你的域名，就好像是一个普通的网站。这样就达到了伪装的目的。除了你自己知道特殊路径转发到v2ray，每个人都以为是个普通网站。如果不想用伪装功能，用脚本的时候你选择不开启即可。
> 
> 或者下面这样设置caddy配置文件：
> 
> ```
> domain.com:443 {
>     tls 32414344@gmail.com
>     timeouts none
>     proxy /v2ray 127.0.0.1:3333 {
>         websocket
>     }
>     proxy / mask.com:80 {
>         except /v2ray
>     }
> }
> ```

请问443端口封了以后，我将domain.com:443{..}改成domain.com:12332{..}类似这样的其他端口可以吗？会不会有不良反应？比如证书啥的？

**Comment by Yousri** [comment]
> 

修改 /etc/caddy/Caddyfile 配置文件

{
  http_port 1234
  https_port 8888
}

大括号内是全局配置，可以声明 caddy 要在哪个端口监听外部的 HTTP / HTTPS 请求，这样不会和你其他80/443端口的web server 存在端口冲突启动失败
