### ISSUE TITLE
WS+TLS模式一键脚本不支持IPV6

### ISSUE THREAD

**Issue by kugoya** [233boy/v2ray#26]
请问是否有计划支持？
感谢提供一键脚本。

**Comment by 233boy** [comment]
@kugoya 
DNS 添加 AAAA 记录过去看看，我没 IPV6 环境测试不了，抱歉。

**Comment by xiaofami** [comment]
同求支持IPv6，现在的vps既有v4又有v6地址，A记录和AAAA记录都正常，但是安装脚本认为只有解析到v4地址才是正确的，然而解析貌似是v6优先所以在添加域名这一步直接失败
