### ISSUE TITLE
除了 ssh 使用的端口, 其他端口国内国外都无法访问是什么情况啊

### ISSUE THREAD

**Issue by sam019** [233boy/v2ray#265]
ssh 的端口, 国内 icmp tcp 都可用, 但是其他端口, 国外 tcp 都不可用, gfw 应该不会影响到国外吧, 怎么解决呢

**Comment by ThorOrtinson** [comment]
防火墙策略问题，这个是ipv6

**Comment by gonnalee** [comment]
主机防火墙问题，设置好防火墙，开放你需要访问的端口
