### ISSUE TITLE
麻烦尽快增加手动指定UUID的功能

### ISSUE THREAD

**Issue by flysn0w** [233boy/v2ray#27]
没有的话每次删除配置重建都要重新生成ID太不方便

**Comment by DolorHunter** [comment]
> 没有的话每次删除配置重建都要重新生成ID太不方便

可以手动修改配置文件 测试有效
用WinSCP进入服务器`/etc/v2ray`中
修改三个文件的UUID
233blog_v2ray_config.json
233blog_v2ray_backup.conf
config.json
重启V2ray, 就可以指定UUID了
