### ISSUE TITLE
请更新一下caddy的下载地址

### ISSUE THREAD

**Issue by ommo** [233boy/v2ray#272]
昨天一直安装不成功，caddy的地址有点不对，看信息下载地址是
https://caddyserver.com/download/linux/?license=personal
？前面的参数判断不出来，修改了一下直接加了amd64才OK，可能判断不准确吧

**Comment by jelly0925** [comment]
今天用脚本自动部署tls也不成功，caddy没有安装启动成功。

**Comment by 148i** [comment]
> 今天用脚本自动部署tls也不成功，caddy没有安装启动成功。
后来怎么解决的？

**Comment by ommo** [comment]
> > 今天用脚本自动部署tls也不成功，caddy没有安装启动成功。
> > 后来怎么解决的？
你先安装一遍，失败了，然后去到/etc/v2ray/233boy/v2ray/src里面，打开download-caddy.sh，第五行，把${caddy_arch}改成amd64或386，然后保存。
你直接wget http://git.io/v2ray.sh，然后编辑这个文件，找到七百多行的install_v2ray() ，把里面的[ -d /etc/v2ray ] && rm -rf /etc/v2ray这行删掉，再把它后面一点点的这几行也删掉
else
pushd /tmp
git clone https://github.com/233boy/v2ray -b "$_gitbranch" /etc/v2ray/233boy/v2ray
popd
删完保存，bash v2ray.sh就可以了

**Comment by 148i** [comment]
> > > 今天用脚本自动部署tls也不成功，caddy没有安装启动成功。
> > > 后来怎么解决的？
> > > 你先安装一遍，失败了，然后去到/etc/v2ray/233boy/v2ray/src里面，打开download-caddy.sh，第五行，把${caddy_arch}改成amd64或386，然后保存。
> > > 你直接wget [http://git.io/v2ray.sh，然后编辑这个文件，找到七百多行的install_v2ray()](http://git.io/v2ray.sh%EF%BC%8C%E7%84%B6%E5%90%8E%E7%BC%96%E8%BE%91%E8%BF%99%E4%B8%AA%E6%96%87%E4%BB%B6%EF%BC%8C%E6%89%BE%E5%88%B0%E4%B8%83%E7%99%BE%E5%A4%9A%E8%A1%8C%E7%9A%84install_v2ray()) ，把里面的[ -d /etc/v2ray ] && rm -rf /etc/v2ray这行删掉，再把它后面一点点的这几行也删掉
> > > else
> > > pushd /tmp
> > > git clone https://github.com/233boy/v2ray -b "$_gitbranch" /etc/v2ray/233boy/v2ray
> > > popd
> > > 删完保存，bash v2ray.sh就可以了

你这个应该是解决caddy下载地址不对的吧，我的caddy好像是安装成功了的，只是没有运行。我先试一下看。
