### ISSUE TITLE
pac模式速度十分慢的问题

### ISSUE THREAD

**Issue by coolzyl** [233boy/v2ray#275]
其他都没问题。用脚本搭了v2ray和ss都能用，但是一开始速度很慢，协议换了kcp之后就好了。

但是还有个问题一直存在，就是v2ray只有在kcp的全局模式下speedtest测速才能达到50Mpbs，youtube看4K也没问题。一旦切回到pac模式那么测速只有1M，youtube也极卡。

PAC在软件上更新过，我觉得可能是pac的问题但是小白不知道要怎么做。

推上去留过言但是没回复，这里再来留下，希望得到回复，谢谢

**Comment by zhangxinlong633** [comment]
pac 设置加下: youtube.com/*
