### ISSUE TITLE
v2rayN.exe端口设置加1问题

### ISSUE THREAD

**Issue by Cloudprogram** [233boy/v2ray#277]
使用官方安装服务器的v2ray，使用v2rayN.exe进入参数设置，本地监听端口设置1080，HTTP代理模式选择PAC模式，发现无法上网，选择全局模式可以正常上网，进入
IE浏览器 》局域网设置》代理服务器
发现端口竟然是1081，比v2rayN设置的1080多1
如图所示：
![1](https://user-images.githubusercontent.com/49339934/62002824-d4ee8180-b13e-11e9-88c0-1d9df429818b.JPG)
![2](https://user-images.githubusercontent.com/49339934/62002825-d5871800-b13e-11e9-9024-200a861d5952.JPG)
![3](https://user-images.githubusercontent.com/49339934/62002826-d6b84500-b13e-11e9-9172-d59128a7a821.JPG)

为什么实际使用端口要加1？？？
而PAC模式无法自动设置代理服务器，为什么全局模式就可以设置呢？

**Comment by xhqpp** [comment]
1081是http

**Comment by Cloudprogram** [comment]
> 1081是http
查看config.json没有对应的配置
{
  "log": {
    "access": "",
    "error": "",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "port": 1080,
      "listen": "127.0.0.1",
      "protocol": "socks",
      "sniffing": {
        "enabled": false,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "auth": "noauth",
        "udp": false,
        "ip": null,
        "clients": null
      },
      "streamSettings": null
    }
  ],

**Comment by wantdawn** [comment]
我也发现这个问题，搞不清楚是为什么
