### ISSUE TITLE
IDM多线程问题。

### ISSUE THREAD

**Issue by 94079490** [233boy/v2ray#28]
博主你好，
用你的V2RAY 一键 搭好了  浏览网页 看YOUTUBE都正常，
但是在用IDM多线程下载的时候会出现只有1-2个线程启动，其他线程一直连接不上。  在其他群里问说是和MUX有关系，小白不懂请大佬指导。

**Comment by 233boy** [comment]
@94079490 
很抱歉，我没在使用 IDM ，所以不是很清楚...
