### ISSUE TITLE
所有设置都正常，就是翻不了墙

### ISSUE THREAD

**Issue by lmsytewu** [233boy/v2ray#280]
所有的搭建都已经完成，但是就是翻不出去，好恼火

**Comment by lmsytewu** [comment]
哪位大神可以告诉我一下这是什么问题吗

**Comment by zhaobu** [comment]
你的电脑时间不同步,vmess协议对时间由校验

**Comment by ticktockKK** [comment]
> 你的电脑时间不同步,vmess协议对时间由校验

萌新想问依稀啊是指同步哪里的时间呀

**Comment by xuehui8888** [comment]
我的也遇到了。我客户端时间同服务器时间是一样的。但是就是翻不了墙
