### ISSUE TITLE
关于 搬x工 后台Root shell - interactive 问题

### ISSUE THREAD

**Issue by tou-7** [233boy/v2ray#285]
在 Root shell - interactive，使用一键脚本，脚本菜单的中文变成乱码！
 一键脚本，可以在 Root shell - interactive 提供中文的支持？
如果环境不支持，可以在一键脚本英文支持？（双语言支持）

**Comment by 148i** [comment]
用putty或者xshell之类的工具

**Comment by arnbunchen** [comment]
@148i  ip被强了，已经无法用 putty或 xshell了

**Comment by ankye** [comment]
都是乱码，被强有英文版吗
