### ISSUE TITLE
新版本V2ray完全沒辦法連接,只有SS正常

### ISSUE THREAD

**Issue by Mattaclp** [233boy/v2ray#287]
使用的是ws+tls
VPS已經全Port容許通過

另一個VPS幾個月前安裝的完全沒有問題

希望能找到問題所在

**Comment by Mattaclp** [comment]
轉用wechat video可以正常連接
就是新版ws+tls失效了

**Comment by tspring95** [comment]
应该是caddy申请证书有问题，换了几台服务器了，申请证书老是有问题。估计是这个版本的一键中自动申请证书上有问题。麻烦作者大神检查一下。

**Comment by marswow** [comment]
kcp+srtp没法连接，
机型：  RT-AC86U
固件版本：384.12
网络情况:中国电信线路 路由器拨号上网 双拨
机场信息：vultr自建的centos 7  洛杉矶5刀小鸡
可以ping通小鸡，ssh连接完全没问题。

**Comment by 148i** [comment]
我也遇到了，caddy没有运行
