### ISSUE TITLE
擋一堆輪子網站你他媽不得好死

### ISSUE THREAD

**Issue by coinvpn** [233boy/v2ray#288]
除了挖礦你還會幹啥

			{
				"type": "field",
				"domain": [
					"domain:epochtimes.com",
					"domain:epochtimes.com.tw",
					"domain:epochtimes.fr",
					"domain:epochtimes.de",
					"domain:epochtimes.jp",
					"domain:epochtimes.ru",
					"domain:epochtimes.co.il",
					"domain:epochtimes.co.kr",
					"domain:epochtimes-romania.com",
					"domain:erabaru.net",
					"domain:lagranepoca.com",
					"domain:theepochtimes.com",
					"domain:ntdtv.com",
					"domain:ntd.tv",
					"domain:ntdtv-dc.com",
					"domain:ntdtv.com.tw",
					"domain:minghui.org",
					"domain:renminbao.com",
					"domain:dafahao.com",
					"domain:dongtaiwang.com",
					"domain:falundafa.org",
					"domain:wujieliulan.com",
					"domain:ninecommentaries.com",
					"domain:shenyun.com"
				],
				"outboundTag": "blocked"
			}

**Comment by XueTeng2** [comment]
围观傻逼轮子 @coinvpn

**Comment by myworksfun** [comment]
不喜欢可以不用，用恶毒的语言攻击开发者是很low的行为，自己说的那句话送给楼主，祝你*********

**Comment by zhz1237ok** [comment]
不是，你谁呀，我们自己的小圈子档网站要你管了

**Comment by mrrubiks** [comment]
自己把这儿删掉吧，就一分钟的事儿，作者搞这个屏蔽也是延长这个脚本的存在时间，防止被消失掉😂

**Comment by Borber** [comment]
傻逼轮子  你妈买菜超级加倍

**Comment by Jasonpluto** [comment]
围观傻逼轮子 @coinvpn

**Comment by ntgeralt** [comment]
那个应该作为可选项，好像iPhone的手机降频开关一样

**Comment by feidao158** [comment]
傻逼轮子 去死吧

**Comment by SunZhizhong** [comment]
建议也屏蔽国外CCTV这些邪教网站，就是看不惯翻墙出来还不忘迫害同胞的鸟人。

**Comment by DoraemonAndRat** [comment]
轮子网站有啥好看的？一群骗子

**Comment by yuzhenghuan** [comment]
轮子死吗强我中华

**Comment by gentlelion99** [comment]
不懂得克制的垃圾不配使用本脚本，看你的语气就知道有多loser.

**Comment by doKill** [comment]
> 围观傻逼轮子 @coinvpn

+1

**Comment by gfw-breaker** [comment]
反串黑吧？法轮功学员会称自己的轮子？会去骂人？

**Comment by xuanke90** [comment]
唉，轮子的事情现在证明有些事是真的，平常上youtube上看的，还真不知道你这屏蔽了

**Comment by gentlelion99** [comment]
等死的轮粉

mowuxing2050 <notifications@github.com> 于2019年10月22日周二 下午2:55写道：

**Comment by qinkangdeid** [comment]
自己有需要自己改不就行了？用别人的东西还骂别人 你还真的得了便宜还卖乖  忘本的玩意儿

**Comment by gentlelion99** [comment]
> 自己有需要自己改不就行了？用别人的东西还骂别人 你还真的得了便宜还卖乖 忘本的玩意儿

请问，这个文件的路径在什么地方？

**Comment by Rom2333** [comment]
围观傻逼轮子

**Comment by enxier** [comment]
围观傻逼轮子

**Comment by c6ForH66** [comment]
傻逼轮子自己看看你们网站上写的什么智障玩意，什么“念九字真经，恶性脑瘤变良性”tm在这忽悠谁啊，你们这些傻逼轮子是不是连初中都没上过的文盲啊，
