### ISSUE TITLE
ubuntu 18.04布置v2ray tls失败

### ISSUE THREAD

**Issue by jelly0925** [233boy/v2ray#290]
2019年8月24日 系统是ubuntu 18.04 今天使用v2ray 脚本安装部署 TLS发现caddy启动不成功，不知道什么原因系统换为centos 7.6也是一样的。有时间更新一下脚本哈，谢谢。

**Comment by 233boy** [comment]
@jelly0925 更新脚本后，再试试看？

**Comment by henbucuoshanghai** [comment]
请问怎样用呢  ubuntu下
