### ISSUE TITLE
安装后，变成矿机

### ISSUE THREAD

**Issue by struggling-fish** [233boy/v2ray#291]
![image](https://user-images.githubusercontent.com/14232305/63630276-94096000-c64b-11e9-97c5-2e808621eadb.png)

**Comment by THUzhangga** [comment]
+1
🌱🌰👩，③👅💦👙🔪😄🌰，👀🗡🇺🇸，😁🅱👶，🌰👩😄👦🚬🅱🌱🌰👩🇩🇪，⑧🌰🏞🌑⚔👨‍❤️‍👨🌰🐑🏢

**Comment by frank-pian** [comment]
我认为你冤枉这个项目了，我并没有用他的脚本，而是使用v2ray的官方安装脚本，一样在昨天被判定为挖矿。我检查服务器的CPU使用率甚至没有超过10%。我认为google cloud故意禁用了一些账户，由于某些不为人知的原因。

**Comment by zzh151223** [comment]
使用的时候cpu会变高的，4m/s的传输速度一般配置的小鸡cpu都会满，不过两核的话最高是两个核心占用50%，应该是程序自动限制最大100%cpu占用
