### ISSUE TITLE
已经确认这个版本的WEBSOCKET+TLS 脚本有问题

### ISSUE THREAD

**Issue by tspring95** [233boy/v2ray#293]
已经在三台不同的VPS上测试过，两个小VPS商，1个GOOGLE云，系统都为CENTOS 7，均无法成功注册证书。没有验证是CADDY的问题还是脚本的问题。因为手工重新装过最新版的CADDY，因此估计是CADDY自己的问题可能性更大。换了老版本的CADDY，成功启用WEBSOCKET+TLS。由于证书申请有限制，此次测试持续了三周，终于搞定。

**Comment by tspring95** [comment]
修正一下，现在成功的WS+TLS的CADDY也是用的最新版1.0.3，估计是这个版本的一键V2RAY的ACME脚本有问题

**Comment by ggsjj** [comment]
我装了N次，都不成功，你是怎么成功的

**Comment by tspring95** [comment]
https://www.moerats.com/archives/404/ 用这个安装CADDY，是最新版1.0.3的CADDY，只是服务脚本用的是INITD不是SYSTEMCTL。证书申请是成功的。

**Comment by ggsjj** [comment]
我 也有 用 这个啊  一样不成功，奇怪  我 换个 IP 试一下 能不能 成功

**Comment by tspring95** [comment]
证书一周一个IP只能申请几次，一定要注意V2RAY一键的脚本是失败就一直自动申请证书，很有可能很快就达到限制。可以查看CADDY错误LOG看原因。所以我也花了三周才找到原因。

**Comment by ggsjj** [comment]
那是要先安装CADDY？ 脚 本旧的要不要删除

**Comment by ggsjj** [comment]
Caddyfile 文件内容你是什么写的复制旧的？

**Comment by tspring95** [comment]
xx.tsprinsgddd.tk {
    tls 24272afaqe4a37248@gmail.com
    gzip
timeouts none
    proxy / https://www.dealmoon.com {
        except /wtwtwt
    }
    proxy /wtwtwt 127.0.0.1:54394 {
        without /wtwtwt
        websocket
    }
}
import sites/*

**Comment by ggsjj** [comment]
也是一样的。 加上配置/etc/init.d/caddy start 用这个启动就会申请对吧 方便加个 电报？我再换个 IP 先装CADDY 试试

**Comment by ggsjj** [comment]
心态崩了，还是不行。。。难道人品问题？

**Comment by CloweYuge** [comment]
你们在讨论什么？我前不久才用过一键脚本，没发现什么问题啊

**Comment by com388488** [comment]
CADDY有问题 我用nginx去申请一次通过  用CADDY 死活不可以 ，希望新脚本能加NGINX 去申请或者等CADDY自已修复BUG

**Comment by com388488** [comment]
@tspring95 你 可以 再重搭一次 看不能成功

**Comment by tspring95** [comment]
@com388488 你看错了吧？我是手工装CADDY成功的。@CloweYuge 你用的WEBSOCKET+TLS？你申请了证书？如果你是CENTOS用的这个一键版本，只要是在8/11后使用的，肯定不对

**Comment by com388488** [comment]
@tspring95 　我手动装过CADDY难道 是我启动方式不对。我是先装了脚本 选择WEBSOCKET+TLS 发现CADDY启动不了  后面又手动安装CADDY 也启动不了，再着又新买一台VPS　单独装CADDY也是不成功。从２５号到今天没的一样成功启动　CADDY　去除了申请证书　就可以成功启动　加这申请证书就启动不了。 你指点一下，先谢谢了

**Comment by tspring95** [comment]
我用我的方法装了2台VPS了，都可申请到证书并正常启用WS+TLS. 方法我上面已经详细说明了。下面再列一下，如果再不懂我也没办法了。要注意一点，你使用的IP地址必须不是证书授权机构封了。如果被封了，就要等一周再试。如果是类似AAA.AAA.COM的域名好象一周只能申请5次，如果是AAA.COM好象是50次。可以查看CADDY日志看是否被封IP。现在的一键脚本，如果自动申请证书，那么失败会自动再申请，很快就会被封IP。
	1. V2RAY
	bash <(curl -s -L https://git.io/v2ray.sh)
	只安装v2ray不要装CADDY
	2. CADDY
	wget -N --no-check-certificate https://raw.githubusercontent.com/ToyoDAdoubi/doubi/master/caddy_install.sh && chmod +x caddy_install.sh && bash caddy_install.sh
	
	参考链接：https://www.moerats.com/archives/404/
3.手动配置caddy

**Comment by com388488** [comment]
到  自动配置NGINX或CADDY  选择不自动配置？

**Comment by com388488** [comment]
![360截图16530707908078](https://user-images.githubusercontent.com/54615116/63834300-9c450080-c9a7-11e9-8e78-84f671150280.png)
到这里选择N？

**Comment by com388488** [comment]
@tspring95  ![360截图166403267285110](https://user-images.githubusercontent.com/54615116/63834945-06aa7080-c9a9-11e9-89f5-2798e1a43ce3.png)
还是不行。兄弟你还在？域名和VPS都 是新的

**Comment by com388488** [comment]
这个 CADDy Error during parsing: Import takes only one argument (glob pattern or file)

**Comment by zhz1237ok** [comment]
> 我用我的方法装了2台VPS了，都可申请到证书并正常启用WS+TLS. 方法我上面已经详细说明了。下面再列一下，如果再不懂我也没办法了。要注意一点，你使用的IP地址必须不是证书授权机构封了。如果被封了，就要等一周再试。如果是类似AAA.AAA.COM的域名好象一周只能申请5次，如果是AAA.COM好象是50次。可以查看CADDY日志看是否被封IP。现在的一键脚本，如果自动申请证书，那么失败会自动再申请，很快就会被封IP。
> 1. V2RAY
> bash <(curl -s -L https://git.io/v2ray.sh)
> 只安装v2ray不要装CADDY
> 2. CADDY
> wget -N --no-check-certificate https://raw.githubusercontent.com/ToyoDAdoubi/doubi/master/caddy_install.sh && chmod +x caddy_install.sh && bash caddy_install.sh
> 
> ```
> 参考链接：https://www.moerats.com/archives/404/
> ```
> 
> 3.手动配置caddy

toyodoubi的脚本去年就没再更新过了，这人涉嫌诈骗被抓进去了，现在这个脚本库是备份状态，无人维护

**Comment by tspring95** [comment]
@com388488 请仔细看我的步骤，我每个步骤都是详细列出来了的。而且表述也很到位了，请仔细阅读并理解。如果你的域名和VPS都是新的，同时IP地址没被Let's Encrypt封的话，肯定是可以。

**Comment by tspring95** [comment]
不知道怎么贴图，给你看看我的运行状态
[root@vmo5v90r ~]# 
[root@vmo5v90r ~]# v2ray status

 V2Ray 状态: 正在运行

[root@vmo5v90r ~]# service caddy status
[信息] Caddy (PID 23559) 正在运行...
[root@vmo5v90r ~]# /usr/local/caddy/caddy -version
Caddy v1.0.3 (h1:i9gRhBgvc5ifchwWtSe7pDpsdS9+Q0Rw9oYQmYUTw1w=)
[root@vmo5v90r ~]# cat /usr/local/caddy/Caddyfile 
vsss.sssss5.tk {
    tls 24272a4a37347248@gmail.com
    gzip
timeouts none
    proxy / https://www.dealmoon.com {
        except /wtwtwt
    }
    proxy /wtwtwt 127.0.0.1:54394 {
        without /wtwtwt
        websocket
    }
}
import sites/*

**Comment by com388488** [comment]
确实可以  不过 不知道为什么 我80端口 一直没开放  后面又好 还真神奇

**Comment by KusuLeung** [comment]
我也遇到了，之前说的是用脚本说IP申请过多，现在单独建立Caddy反而说域名申请过多。是不是一定要一周后才能再次申请？

**Comment by com388488** [comment]
过几小时就可以再申请

**Comment by KusuLeung** [comment]
你们找到这个脚本自动申请证书为啥失败的原因没有？是哪方面造成的？

**Comment by com388488** [comment]
@KusuLeung 你关了防火墙或开放80 443端  我也 是卡这里N久 现在才搞明白

**Comment by jelly0925** [comment]
我也遇到相同的问题，v2ray 安装caddy不能正常运行。

**Comment by SmoosQ** [comment]
我也遇到同样问题，我看一直是 v2ray.com/core/transport/internet/websocket: failed to serve http for WebSocket > accept tcp [::]:22506: use of closed network connection

**Comment by 148i** [comment]
和楼上老哥遇到相同问题，caddy出问题了。但是不会手动配置caddy，有大神出个教程吗？

**Comment by Yu4n** [comment]
Too many registrations for this IP卡在申请证书。

**Comment by yunjie-li** [comment]
手动配置caddy:

wget -N --no-check-certificate https://raw.githubusercontent.com/ToyoDAdoubi/doubi/master/caddy_install.sh && chmod +x caddy_install.sh && bash caddy_install.sh
# 卸载命令：
wget -N --no-check-certificate https://raw.githubusercontent.com/ToyoDAdoubi/doubi/master/caddy_install.sh && chmod +x caddy_install.sh && caddy_install.sh uninstall

echo "xxx.com {
 tls 12345678@qq.com
 proxy / 127.0.0.1:1234{
  websocket
 }
}" > /usr/local/caddy/Caddyfile

启动：/etc/init.d/caddy start
停止：/etc/init.d/caddy stop
重启：/etc/init.d/caddy restart
查看状态：/etc/init.d/caddy status
查看Caddy启动日志： tail -f /tmp/caddy.log
Caddy配置文件位置：/usr/local/caddy/Caddyfile
Caddy自动申请SSL证书位置：/.caddy/acme/acme-v01.api.letsencrypt.org/sites/xxx.xxx(域名)/

**Comment by gaofn** [comment]
> 证书一周一个IP只能申请几次，一定要注意V2RAY一键的脚本是失败就一直自动申请证书，很有可能很快就达到限制。可以查看CADDY错误LOG看原因。所以我也花了三周才找到原因。

我也遇到这个问题了。弱弱问一下， 怎么用233的脚本只装v2ray但是不装caddy?

> 过几小时就可以再申请
上面tspring95说限制是算一周的，你说过几个小时就能再试？

**Comment by tspring95** [comment]
针对主机或是域，有不同的限制规则。不过一般都是一周

**Comment by lotern37** [comment]
caddy证书存储失败，导致反复申请证书，最后letsencrypt封掉ip。
手动部署caddy即可.

> https://github.com/233boy/v2ray/issues/309#issuecomment-533376354

**Comment by Lelouch-Lamperoge** [comment]
> 不知道怎么贴图，给你看看我的运行状态
> [root@vmo5v90r ~]#
> [root@vmo5v90r ~]# v2ray status
> 
> V2Ray 状态: 正在运行
> 
> [root@vmo5v90r ~]# service caddy status
> [信息] Caddy (PID 23559) 正在运行...
> [root@vmo5v90r ~]# /usr/local/caddy/caddy -version
> Caddy v1.0.3 (h1:i9gRhBgvc5ifchwWtSe7pDpsdS9+Q0Rw9oYQmYUTw1w=)
> [root@vmo5v90r ~]# cat /usr/local/caddy/Caddyfile
> vsss.sssss5.tk {
> tls [24272a4a37347248@gmail.com](mailto:24272a4a37347248@gmail.com)
> gzip
> timeouts none
> proxy / https://www.dealmoon.com {
> except /wtwtwt
> }
> proxy /wtwtwt 127.0.0.1:54394 {
> without /wtwtwt
> websocket
> }
> }
> import sites/*

你好 想问下这个tls邮箱是随便填的嘛

**Comment by yuzhenghuan** [comment]
mark一下虽然现在没有遇到，也许我的域名太多直接换了哈

**Comment by edwinhuish** [comment]
同样遇到这个问题，后来直接 NGINX 配置起来了。

不过不知道有没有必要做网站伪装。

**Comment by redstoneleo** [comment]
我测试了还不可以，你们的可以吗？
