### ISSUE TITLE
是不是作者把脚本时的仓库给删除了。一直克隆不到，脚本报错，救助啊。

### ISSUE THREAD

**Issue by jiaorong** [233boy/v2ray#294]
正克隆到 '/etc/v2ray/233boy/v2ray'...
fatal: unable to access 'https://github.com/233boy/v2ray/': Could not resolve host: github.com; Unknown error
/home/www

 哎呀呀...克隆脚本仓库出错了...

 温馨提示..... 请尝试自行安装 Git: yum install -y git  之后再安装此脚本

**Comment by CloweYuge** [comment]
你点开代码库不就知道了嘛=，=

**Comment by carli0215** [comment]
不是早就删除了吗

**Comment by devinstever** [comment]
> 不是早就删除了吗

没有删除，你点开页面上的branch，再点击master试试看。
： ）

**Comment by liuqianghui** [comment]
> 正克隆到 '/etc/v2ray/233boy/v2ray'...
> fatal: unable to access 'https://github.com/233boy/v2ray/': Could not resolve host: github.com; Unknown error
> /home/www
> 
> 哎呀呀...克隆脚本仓库出错了...
> 
> 温馨提示..... 请尝试自行安装 Git: yum install -y git 之后再安装此脚本

可以看哪些人 fork 了，然后把地址修改到 fork 的那些人的地址
