### ISSUE TITLE
切勿长时间连接V2Ray！！！

### ISSUE THREAD

**Issue by gaojun6854** [233boy/v2ray#295]
切勿长时间连接V2Ray！！！市区网安可以检测到家庭宽带IP异常。

**Comment by zhz1237ok** [comment]
除了关机我一直开着，快两年了，有什么问题吗

**Comment by tspring95** [comment]
V2RAY有很多种模式，你这样说没有任何意义

**Comment by gaojun6854** [comment]
> V2RAY有很多种模式，你这样说没有任何意义

我可以说我搭建的V2Ray以及采用的模式都符合最强的要求。你不是处在复杂区域类，但是你长时间连接的流量就是可以被网安监控到的！我是提醒你们，不要说没任何意义！

**Comment by gaojun6854** [comment]
> 除了关机我一直开着，快两年了，有什么问题吗

最近会被网安检测到。

**Comment by zhz1237ok** [comment]
> > 除了关机我一直开着，快两年了，有什么问题吗
> 
> 最近会被网安检测到。

我早就去拉过流量清单，以前用ws的时候都是未知流量，现在mkcp都是微信视频流量，根本没问题，你说的网安检测是啥，请出示你的证据，否则就是在造谣

**Comment by gaojun6854** [comment]
> > > 除了关机我一直开着，快两年了，有什么问题吗
> > 
> > 
> > 最近会被网安检测到。
> 
> 我早就去拉过流量清单，以前用ws的时候都是未知流量，现在mkcp都是微信视频流量，根本没问题，你说的网安检测是啥，请出示你的证据，否则就是在造谣

你先自己去看看网络安全警察是什么，我既然这么说肯定是有原因的。你所谓拉的流量只是时间段用了多少流量，但是网络安全平台上会监查你连接的所有的主机。

**Comment by zhz1237ok** [comment]
> > > > 除了关机我一直开着，快两年了，有什么问题吗
> > > 
> > > 
> > > 最近会被网安检测到。
> > 
> > 
> > 我早就去拉过流量清单，以前用ws的时候都是未知流量，现在mkcp都是微信视频流量，根本没问题，你说的网安检测是啥，请出示你的证据，否则就是在造谣
> 
> 你先自己去看看网络安全警察是什么，我既然这么说肯定是有原因的。你所谓拉的流量只是时间段用了多少流量，但是网络安全平台上会监查你连接的所有的主机。

突然想起来这个issue是你先提出来的，我为什么要去证明你说的对错，你来出示你自己证据，不然就是造谣了

**Comment by zhz1237ok** [comment]
> > > > 除了关机我一直开着，快两年了，有什么问题吗
> > > 
> > > 
> > > 最近会被网安检测到。
> > 
> > 
> > 我早就去拉过流量清单，以前用ws的时候都是未知流量，现在mkcp都是微信视频流量，根本没问题，你说的网安检测是啥，请出示你的证据，否则就是在造谣
> 
> 你先自己去看看网络安全警察是什么，我既然这么说肯定是有原因的。你所谓拉的流量只是时间段用了多少流量，但是网络安全平台上会监查你连接的所有的主机。

据我所知，拿推特当例子，用户登录推特，数据从ISP到VPS再到推特服务器，如果你想查这个人，你得向推特要IP再向VPS商索要原始IP，然后直接定位你的人，但是，推特和VPS商都不会给的，而你为什么被检测到了，想必是开着全局在国内网站到处逛导致的

**Comment by zhz1237ok** [comment]
> > > > > 除了关机我一直开着，快两年了，有什么问题吗
> > > > 
> > > > 
> > > > 最近会被网安检测到。
> > > 
> > > 
> > > 我早就去拉过流量清单，以前用ws的时候都是未知流量，现在mkcp都是微信视频流量，根本没问题，你说的网安检测是啥，请出示你的证据，否则就是在造谣
> > 
> > 
> > 你先自己去看看网络安全警察是什么，我既然这么说肯定是有原因的。你所谓拉的流量只是时间段用了多少流量，但是网络安全平台上会监查你连接的所有的主机。
> 
> 据我所知，拿推特当例子，用户登录推特，数据从ISP到VPS再到推特服务器，如果你想查这个人，你得向推特要IP再向VPS商索要原始IP，然后直接定位你的人，但是，推特和VPS商都不会给的，而你为什么被检测到了，想必是开着全局在国内网站到处逛导致的

毕竟，国内网站都是提供接口给高层网安查数据的

**Comment by gaojun6854** [comment]
> > > > > > 除了关机我一直开着，快两年了，有什么问题吗
> > > > > 
> > > > > 
> > > > > 最近会被网安检测到。
> > > > 
> > > > 
> > > > 我早就去拉过流量清单，以前用ws的时候都是未知流量，现在mkcp都是微信视频流量，根本没问题，你说的网安检测是啥，请出示你的证据，否则就是在造谣
> > > 
> > > 
> > > 你先自己去看看网络安全警察是什么，我既然这么说肯定是有原因的。你所谓拉的流量只是时间段用了多少流量，但是网络安全平台上会监查你连接的所有的主机。
> > 
> > 
> > 据我所知，拿推特当例子，用户登录推特，数据从ISP到VPS再到推特服务器，如果你想查这个人，你得向推特要IP再向VPS商索要原始IP，然后直接定位你的人，但是，推特和VPS商都不会给的，而你为什么被检测到了，想必是开着全局在国内网站到处逛导致的
> 
> 毕竟，国内网站都是提供接口给高层网安查数据的

你是不知道网安有多大权力，我就这么和你说把，我连了半个月，不在家，电脑一直开机，平时也就是google下资料，网安找上门说你家宽带被我们检测到了。都说了我是提示你们，你非要死脑筋在这咳！

**Comment by zhz1237ok** [comment]
> > > > > > > 除了关机我一直开着，快两年了，有什么问题吗
> > > > > > 
> > > > > > 
> > > > > > 最近会被网安检测到。
> > > > > 
> > > > > 
> > > > > 我早就去拉过流量清单，以前用ws的时候都是未知流量，现在mkcp都是微信视频流量，根本没问题，你说的网安检测是啥，请出示你的证据，否则就是在造谣
> > > > 
> > > > 
> > > > 你先自己去看看网络安全警察是什么，我既然这么说肯定是有原因的。你所谓拉的流量只是时间段用了多少流量，但是网络安全平台上会监查你连接的所有的主机。
> > > 
> > > 
> > > 据我所知，拿推特当例子，用户登录推特，数据从ISP到VPS再到推特服务器，如果你想查这个人，你得向推特要IP再向VPS商索要原始IP，然后直接定位你的人，但是，推特和VPS商都不会给的，而你为什么被检测到了，想必是开着全局在国内网站到处逛导致的
> > 
> > 
> > 毕竟，国内网站都是提供接口给高层网安查数据的
> 
> 你是不知道网安有多大权力，我就这么和你说把，我连了半个月，不在家，电脑一直开机，平时也就是google下资料，网安找上门说你家宽带被我们检测到了。都说了我是提示你们，你非要死脑筋在这咳！

别告诉我你用了360等等的国产软件，因为你可以清晰地在日志里看到，你不操作，也有流量经过这些软件，然后会被自动上报

**Comment by gaojun6854** [comment]
> > > > > > > > 除了关机我一直开着，快两年了，有什么问题吗
> > > > > > > 
> > > > > > > 
> > > > > > > 最近会被网安检测到。
> > > > > > 
> > > > > > 
> > > > > > 我早就去拉过流量清单，以前用ws的时候都是未知流量，现在mkcp都是微信视频流量，根本没问题，你说的网安检测是啥，请出示你的证据，否则就是在造谣
> > > > > 
> > > > > 
> > > > > 你先自己去看看网络安全警察是什么，我既然这么说肯定是有原因的。你所谓拉的流量只是时间段用了多少流量，但是网络安全平台上会监查你连接的所有的主机。
> > > > 
> > > > 
> > > > 据我所知，拿推特当例子，用户登录推特，数据从ISP到VPS再到推特服务器，如果你想查这个人，你得向推特要IP再向VPS商索要原始IP，然后直接定位你的人，但是，推特和VPS商都不会给的，而你为什么被检测到了，想必是开着全局在国内网站到处逛导致的
> > > 
> > > 
> > > 毕竟，国内网站都是提供接口给高层网安查数据的
> > 
> > 
> > 你是不知道网安有多大权力，我就这么和你说把，我连了半个月，不在家，电脑一直开机，平时也就是google下资料，网安找上门说你家宽带被我们检测到了。都说了我是提示你们，你非要死脑筋在这咳！
> 
> 别告诉我你用了360等等的国产软件，因为你可以清晰地在日志里看到，你不操作，也有流量经过这些软件，然后会被自动上报
> 
> 用梯子就要注意自己的安全，哪个步骤出了问题要提早弄清楚
> 
> 原理上，你只要不用代理IP登录国内任何网站，就是个没事人
> 除非你是政治犯，人家网警可以通过你的论坛ID人肉你，就根本不需要查IP了

怎么可能，我是爱国爱党人士（几年的老党员）！我问过了就是检测了ip异常长时间连接了hk的ip，静安区这一片的小区出入口都是被检测这的。我只开了2个 idea 一个chrome，1个postman ，一个后台的v2ray。剩下啥也没开！直接进门后翻了我电脑所有记录，网盘，历史记录，磁盘。然而啥也没有。

**Comment by zhz1237ok** [comment]
> > > > > > > 除了关机我一直开着，快两年了，有什么问题吗
> > > > > > 
> > > > > > 
> > > > > > 最近会被网安检测到。
> > > > > 
> > > > > 
> > > > > 我早就去拉过流量清单，以前用ws的时候都是未知流量，现在mkcp都是微信视频流量，根本没问题，你说的网安检测是啥，请出示你的证据，否则就是在造谣
> > > > 
> > > > 
> > > > 你先自己去看看网络安全警察是什么，我既然这么说肯定是有原因的。你所谓拉的流量只是时间段用了多少流量，但是网络安全平台上会监查你连接的所有的主机。
> > > 
> > > 
> > > 据我所知，拿推特当例子，用户登录推特，数据从ISP到VPS再到推特服务器，如果你想查这个人，你得向推特要IP再向VPS商索要原始IP，然后直接定位你的人，但是，推特和VPS商都不会给的，而你为什么被检测到了，想必是开着全局在国内网站到处逛导致的
> > 
> > 
> > 毕竟，国内网站都是提供接口给高层网安查数据的
> 
> 你是不知道网安有多大权力，我就这么和你说把，我连了半个月，不在家，电脑一直开机，平时也就是google下资料，网安找上门说你家宽带被我们检测到了。都说了我是提示你们，你非要死脑筋在这咳！

![image](https://user-images.githubusercontent.com/38283893/64307475-c8283d80-cfc8-11e9-8c7c-12ebf6664d26.png)
![image](https://user-images.githubusercontent.com/38283893/64307495-d413ff80-cfc8-11e9-8d61-26af8815d9b8.png)
网警看到第一个图就会上门了

**Comment by zhz1237ok** [comment]
现在去香港过关的时候会把你手机拿出来，如果有推特，会仔细翻看，就怕你是废青闹事去的

**Comment by gaojun6854** [comment]
> 现在去香港过关的时候会把你手机拿出来，如果有推特，会仔细翻看，就怕你是废青闹事去的
> 
> 你错就错在用了香港的VPS，你用日本美国的不好吗

香港我做过后的ping是56 美国100多。

**Comment by zhz1237ok** [comment]
> > 现在去香港过关的时候会把你手机拿出来，如果有推特，会仔细翻看，就怕你是废青闹事去的
> > 你错就错在用了香港的VPS，你用日本美国的不好吗
> 
> 香港我做过后的ping是56 美国100多。

你拿VPS当游戏加速器使的吗，延迟多50m那么严重？严重到可以让网安来查自己家？

**Comment by Schnappi-02** [comment]
> 你拿VPS当游戏加速器使的吗，延迟多50那么严重？严重到可以让网安来查自己家？
> 我现在的VPS延迟500，照样看youtube的4k视频

老哥，233boy的一键安装脚本用BBR和锐速的话哪个加速效果比较好？我的5刀每月的VPS只装了BBR，速度只能勉强看油管1080P，你是怎么配置才能看4K的？
据说用锐速会影响局域网还是别的什么去了，如果被VPS厂家检测到的话会被封号，是真的吗？

**Comment by zhz1237ok** [comment]
> > 你拿VPS当游戏加速器使的吗，延迟多50那么严重？严重到可以让网安来查自己家？
> > 我现在的VPS延迟500，照样看youtube的4k视频
> 
> 老哥，233boy的一键安装脚本用BBR和锐速的话哪个加速效果比较好？我的5刀每月的VPS只装了BBR，速度只能勉强看油管1080P，你是怎么配置才能看4K的？
> 据说用锐速会影响局域网还是别的什么去了，如果被VPS厂家检测到的话会被封号，是真的吗？

换VPS，换到和你家连接速度最快的为止，最好是日本的VPS

**Comment by Schnappi-02** [comment]
> > > 你拿VPS当游戏加速器使的吗，延迟多50那么严重？严重到可以让网安来查自己家？
> > > 我现在的VPS延迟500，照样看youtube的4k视频
> > 
> > 
> > 老哥，233boy的一键安装脚本用BBR和锐速的话哪个加速效果比较好？我的5刀每月的VPS只装了BBR，速度只能勉强看油管1080P，你是怎么配置才能看4K的？
> > 据说用锐速会影响局域网还是别的什么去了，如果被VPS厂家检测到的话会被封号，是真的吗？
> 
> 换VPS，换到和你家连接速度最快的为止，最好是日本的VPS

用的是校园网，不是家里。手机4G能看1080P，电脑很不稳定，有时候能看有时候不能，不知道是不是学校限流量了。

**Comment by zhz1237ok** [comment]
> > > > 你拿VPS当游戏加速器使的吗，延迟多50那么严重？严重到可以让网安来查自己家？
> > > > 我现在的VPS延迟500，照样看youtube的4k视频
> > > 
> > > 
> > > 老哥，233boy的一键安装脚本用BBR和锐速的话哪个加速效果比较好？我的5刀每月的VPS只装了BBR，速度只能勉强看油管1080P，你是怎么配置才能看4K的？
> > > 据说用锐速会影响局域网还是别的什么去了，如果被VPS厂家检测到的话会被封号，是真的吗？
> > 
> > 
> > 换VPS，换到和你家连接速度最快的为止，最好是日本的VPS
> 
> 用的是校园网，不是家里。手机4G能看1080P，电脑很不稳定，有时候能看有时候不能，不知道是不是学校限流量了。

VPS不是说有了就好了，要找到和你的网络最适合的才行，自己去测试，找个bench脚本什么的，手机网络和电脑是不同IP不同网络，我用的VPS和我的网络很好，但是我给你去用，说不定非常差，这是地区原因，没办法，投钱问路

**Comment by Slackboi** [comment]
ss没撑住，v2ray还行吗

**Comment by COWONER** [comment]
> ss没撑住，v2ray还行吗

昨天早上还在上YouTube，中午就被封掉了，一查IP被ban。就用的v2Ray

**Comment by dwjdo** [comment]
现在去香港过关的时候会把你手机拿出来，如果有推特，会仔细翻看，就怕你是废青闹事去的

你错就错在用了香港的VPS，你用日本美国的不好吗



能教一下怎么建一个安全的v2ray吗

**Comment by dwjdo** [comment]
#2 能教一下吗大神

**Comment by dwjdo** [comment]
请教一下怎么回复别人的评论。我好像只能自己发评论，不懂怎么针对别人的评论直接回复，请教一下谢谢

**Comment by devinstever** [comment]
> 请教一下怎么回复别人的评论。我好像只能自己发评论，不懂怎么针对别人的评论直接回复，请教一下谢谢

你可以点击对应卡片上的三个点，选择quote reply。

**Comment by devinstever** [comment]
可以试试websocket+cdn+tls，这样就像是模拟的正常https网站流量。

**Comment by dwjdo** [comment]
> > 请教一下怎么回复别人的评论。我好像只能自己发评论，不懂怎么针对别人的评论直接回复，请教一下谢谢
> 
> 你可以点击对应卡片上的三个点，选择quote reply。

好了，谢谢大神。请问大神现在用什么梯子？

**Comment by DoraemonAndRat** [comment]
长时间连着会以为你家里藏了个服务器在干坏事

**Comment by gaojun6854** [comment]
国庆在即 请大家正视网络安全，互联网不是法外之地，请合理上网。

**Comment by 8x8-64** [comment]
说的没根据，连设置都没贴出来。v2ray没流量会断开连接，你必然在后台有东西持续跑流量

**Comment by luxi78** [comment]
> 说的没根据，连设置都没贴出来。v2ray没流量会断开连接，你必然在后台有东西持续跑流量

没贴出配置的确没有根据, 楼主的说法是比较草率的

按我的理解,v2ray走tcp是会保持长连接的, 走udp的话就不存在连接这个说法了, 所以我觉得"v2ray没流量会断开连接"这个说法不太正确. 这是我对tcp udp网络的理解,有任何不对的地方请指出一下. 感谢

**Comment by luxi78** [comment]
> > 说的没根据，连设置都没贴出来。v2ray没流量会断开连接，你必然在后台有东西持续跑流量
> 
> 没贴出配置的确没有根据, 楼主的说法是比较草率的
> 
> 按我的理解,v2ray走tcp是会保持长连接的, 走udp的话就不存在连接这个说法了, 所以我觉得"v2ray没流量会断开连接"这个说法不太正确. 这是我对tcp udp网络的理解,有任何不对的地方请指出一下. 感谢

刚才专门测试了一下,确实如你所说,v2ray(vmess走tcp)没流量会断开连接的, 我之前的理解有误.

**Comment by michi-easynet811** [comment]
最近建了Google云，速度慢，断断续续上网。大概用了两三天，有点奇怪的是，我没有看见账单的费用。我看官方说明，应该是产生了流量，就有费用。想问大家是每日出账单还是周期出账单？

**Comment by NetHeritage** [comment]
楼上的有些回复有意思了，不能解决制造问题的人，就解决提出问题的人，解决吹哨人

**Comment by HKTY569** [comment]
> 最近建了Google云，速度慢，断断续续上网。大概用了两三天，有点奇怪的是，我没有看见账单的费用。我看官方说明，应该是产生了流量，就有费用。想问大家是每日出账单还是周期出账单？

一般是按小时收费的，我也没找到账单，貌似流量也算费用，我大概五天烧了400港币。。

**Comment by michi-easynet811** [comment]
谢谢回复;最近没没有使用,但是项目在,应该是收费的.刚刚看了下,依然没有显示任何使用的金额,still
感觉有点奇怪.不知道为什么最近感觉Google的产品,例如mailbox等一些产品很难打开,不知道您是否也是这样情况.幸好读研的是否保留了hotmail和ourlook邮箱.想想都是遥远的回忆.

Ves Mkt <notifications@github.com> 于2020年8月31日周一 下午6:26写道：

**Comment by lyrielau** [comment]
> > > > > 除了关机我一直开着，快两年了，有什么问题吗
> > > > 
> > > > 
> > > > 最近会被网安检测到。
> > > 
> > > 
> > > 我早就去拉过流量清单，以前用ws的时候都是未知流量，现在mkcp都是微信视频流量，根本没问题，你说的网安检测是啥，请出示你的证据，否则就是在造谣
> > 
> > 
> > 你先自己去看看网络安全警察是什么，我既然这么说肯定是有原因的。你所谓拉的流量只是时间段用了多少流量，但是网络安全平台上会监查你连接的所有的主机。
> 
> 据我所知，拿推特当例子，用户登录推特，数据从ISP到VPS再到推特服务器，如果你想查这个人，你得向推特要IP再向VPS商索要原始IP，然后直接定位你的人，但是，推特和VPS商都不会给的，而你为什么被检测到了，想必是开着全局在国内网站到处逛导致的

推特早就沦陷了

**Comment by Zzw-mazai** [comment]
> 

直接退出程序就时断开了连接吗

**Comment by betaberry** [comment]
还行吧，天天长时间高强度看p站，也没人找我

**Comment by Molyt-King** [comment]
> V2RAY有很多种模式，你这样说没有任何意义

大佬，应该用哪种模式

**Comment by GitHubbeginerTuring** [comment]
> > > > > > > > 除了关机我一直开着，快两年了，有什么问题吗
> > > > > > > 
> > > > > > > 
> > > > > > > 最近会被网安检测到。
> > > > > > 
> > > > > > 
> > > > > > 我早就去拉过流量清单，以前用ws的时候都是未知流量，现在mkcp都是微信视频流量，根本没问题，你说的网安检测是啥，请出示你的证据，否则就是在造谣
> > > > > 
> > > > > 
> > > > > 你先自己去看看网络安全警察是什么，我既然这么说肯定是有原因的。你所谓拉的流量只是时间段用了多少流量，但是网络安全平台上会监查你连接的所有的主机。
> > > > 
> > > > 
> > > > 据我所知，拿推特当例子，用户登录推特，数据从ISP到VPS再到推特服务器，如果你想查这个人，你得向推特要IP再向VPS商索要原始IP，然后直接定位你的人，但是，推特和VPS商都不会给的，而你为什么被检测到了，想必是开着全局在国内网站到处逛导致的
> > > 
> > > 
> > > 毕竟，国内网站都是提供接口给高层网安查数据的
> > 
> > 
> > 你是不知道网安有多大权力，我就这么和你说把，我连了半个月，不在家，电脑一直开机，平时也就是google下资料，网安找上门说你家宽带被我们检测到了。都说了我是提示你们，你非要死脑筋在这咳！
> 
> ![image](https://user-images.githubusercontent.com/38283893/64307475-c8283d80-cfc8-11e9-8c7c-12ebf6664d26.png) 这是未规范设置的代理，拉流量清单出来是未知TCP，注意，这只是拉出来的清单，在电信局那些地方是实时可查的 ![image](https://user-images.githubusercontent.com/38283893/64307495-d413ff80-cfc8-11e9-8d61-26af8815d9b8.png) 这是KCP的微信伪装
> 
> 网警看到未知流量，而且还是香港的IP，你说查不查你

大佬kcp模式怎么弄呀。
