### ISSUE TITLE
caddy软件的下载链接变了，麻烦更改一下download-caddy.sh文件

### ISSUE THREAD

**Issue by AllenLTB** [233boy/v2ray#297]
Archive:  /tmp/v2ray/v2ray.zip
  inflating: /tmp/v2ray/config.json  
   creating: /tmp/v2ray/doc/
  inflating: /tmp/v2ray/doc/readme.md  
  inflating: /tmp/v2ray/geoip.dat    
  inflating: /tmp/v2ray/geosite.dat  
   creating: /tmp/v2ray/systemd/
  inflating: /tmp/v2ray/systemd/v2ray.service  
   creating: /tmp/v2ray/systemv/
  inflating: /tmp/v2ray/systemv/v2ray  
  inflating: /tmp/v2ray/v2ctl        
 extracting: /tmp/v2ray/v2ctl.sig    
  inflating: /tmp/v2ray/v2ray        
 extracting: /tmp/v2ray/v2ray.sig    
  inflating: /tmp/v2ray/vpoint_socks_vmess.json  
  inflating: /tmp/v2ray/vpoint_vmess_freedom.json  
--2019-09-01 09:06:58--  **https://caddyserver.com/download/linux/?license=personal**
Resolving caddyserver.com (caddyserver.com)... 138.68.240.78, 2604:a880:2:d0::1145:e001
Connecting to caddyserver.com (caddyserver.com)|138.68.240.78|:443... connected.
**HTTP request sent, awaiting response... 404 Not Found**
2019-09-01 09:06:59 ERROR 404: Not Found.

 下载 Caddy 失败！

**Comment by h6fYe34KFSiH** [comment]
哇，我装了N遍都是无法启动caddy，原来是没有下载，之前脚本也没有提示下载失败。

**Comment by h6fYe34KFSiH** [comment]
好像有的可以下，有的系统不能下
