### ISSUE TITLE
vps重启caddy就失效啊

### ISSUE THREAD

**Issue by EzioAu** [233boy/v2ray#298]
caddy.service: Main process exited, code=exited, status=1/FAILURE 
vps重启就连不上了，查看caddy状态就显示这个。

**Comment by EzioAu** [comment]
可是v2就是连不上， failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://www.xxx.top/): 521 Origin Down > websocket: bad handshake v2ray.com/core/transport/internet/websocket: failed to dial WebSocket >

**Comment by i-love-tadpole** [comment]
你是不是加了cloudflare

**Comment by i-love-tadpole** [comment]
> caddy.service: Main process exited, code=exited, status=1/FAILURE
> vps重启就连不上了，查看caddy状态就显示这个。

你是不是加了cloudflare

**Comment by 148i** [comment]
> caddy.service: Main process exited, code=exited, status=1/FAILURE
> vps重启就连不上了，查看caddy状态就显示这个。

你解决了吗？我目前是caddy安装之后启动不了。
