### ISSUE TITLE
mac系统的是不是就不能装？

### ISSUE THREAD

**Issue by Bruce-1988** [233boy/v2ray#300]
不好意思 小白一枚， 看到系统要求那没有macOS 是不是意味着mac系统的就用不了？

**Comment by Rockzhangchenhao** [comment]
可以装的，名字不是v2rayN之类的，你直接github搜v2ray mac就可以了

**Comment by hasen6** [comment]
下载V2rayX，还比windows软件好用。

**Comment by devinstever** [comment]
可以看看这里的 https://github.com/yanue/V2rayU
