### ISSUE TITLE
测试服务器延迟有值，但还是无法科学上网

### ISSUE THREAD

**Issue by April-D-phil** [233boy/v2ray#301]
![image](https://user-images.githubusercontent.com/25237751/64843154-ef20e800-d636-11e9-917d-88d475c1d9ac.png)

**Comment by kanggou** [comment]
你看一下信息反馈，有可能是端口没打开呢

**Comment by April-D-phil** [comment]
我现在是，手机可以用，不过PC是，连接也可以，能测试返回延迟的值，不过就是无法上网，然后我看到其他评论，有可能是IPV4的问题，IPV6的可以用

**Comment by April-D-phil** [comment]
我在WIN10机子上，可以用，但是在另外一台win7中，不可以用，在http代理模式哪里，无法看到设置的状态，不确定是不是在win7上，有BUG，还是本身设置出了什么问题
