### ISSUE TITLE
v2rayn 在登录streamlabs用不了，一直显示无法连接网络

### ISSUE THREAD

**Issue by hasen6** [233boy/v2ray#304]
连上以后可以打开谷歌浏览器，或者火狐。可以在streamlabs的软件上，用不了，这一直显示网络无法连接。

**Comment by devinstever** [comment]
请检查你所使用的vpsip是否被对应网站服务商屏蔽（关于这块比较有名的是pixiv屏蔽日本vps的事情）
或者通过修改配置文件更换其他的dns再试。

**Comment by hasen6** [comment]
ip地址并没有问题，我用ssr和v2ray是同一个ip，但是ssr可以用twitch直播，v2ray就不能。而且v2ray可以打开浏览器上屏蔽的网站什么的没问题。
