### ISSUE TITLE
目前搬瓦工被墙，不还IP的话，用这个 能行么？

### ISSUE THREAD

**Issue by qq432591** [233boy/v2ray#305]

**Comment by Michaol** [comment]
IP段被封，除了CDN一法，用什么都没有，直到解封……

**Comment by lanmeiceo** [comment]
> IP段被封，除了CDN一法，用什么都没有，直到解封……

cdn是啥

**Comment by Michaol** [comment]
CDN的全称是Content Delivery Network，即内容分发网络。简单地说就是通过其他不会被墙的CDN服务器去调用你的VPS，经过CDN转给你。既能复活小鸡，又能隐藏VPS的真实IP。缺点是效率变低，速度变慢，鱼与熊掌。搬瓦工应该是付年费吧？还能救救。

**Comment by freelancer10** [comment]
谷歌云到现在还能用，美区

**Comment by tryboy1978** [comment]
> CDN的全称是Content Delivery Network，即内容分发网络。简单地说就是通过其他不会被墙的CDN服务器去调用你的VPS，经过CDN转给你。既能复活小鸡，又能隐藏VPS的真实IP。缺点是效率变低，速度变慢，鱼与熊掌。搬瓦工应该是付年费吧？还能救救。

请问有具体教程吗？我搬瓦工的IP也被墙了。。。

**Comment by 233boy** [comment]
> > CDN的全称是Content Delivery Network，即内容分发网络。简单地说就是通过其他不会被墙的CDN服务器去调用你的VPS，经过CDN转给你。既能复活小鸡，又能隐藏VPS的真实IP。缺点是效率变低，速度变慢，鱼与熊掌。搬瓦工应该是付年费吧？还能救救。
> 
> 请问有具体教程吗？我搬瓦工的IP也被墙了。。。

https://github.com/233boy/v2ray/wiki

**Comment by tryboy1978** [comment]
> > > CDN的全称是Content Delivery Network，即内容分发网络。简单地说就是通过其他不会被墙的CDN服务器去调用你的VPS，经过CDN转给你。既能复活小鸡，又能隐藏VPS的真实IP。缺点是效率变低，速度变慢，鱼与熊掌。搬瓦工应该是付年费吧？还能救救。
> > 
> > 
> > 请问有具体教程吗？我搬瓦工的IP也被墙了。。。
> 
> https://github.com/233boy/v2ray/wiki

请问我搭建成功了，但您脚本生成的路径是“/”根路径，这个可以修改吗？我尝试了修改，但却不能成功FQ，请问有什么讲究吗？还是说必须只能是根路径？
