### ISSUE TITLE
> ss没撑住，v2ray还行吗

### ISSUE THREAD

**Issue by tspring95** [233boy/v2ray#306]
一看就是不懂的，V2RAY只相当于一个平台，你用什么样的封装方式，会直接影响你的流量加密情况。举例来说，常见的SS可以作为V2RAY的一种封装方式。最稳的还是WEBSOCKET+TLS。
> ss没撑住，v2ray还行吗

昨天早上还在上YouTube，中午就被封掉了，一查IP被ban。就用的v2Ray

_Originally posted by @COWONER in https://github.com/233boy/v2ray/issues/295#issuecomment-532061113_

**Comment by Michaol** [comment]
大量封锁IP段，什么都没用，高墙根本懒得分析数据流，一棍子全打死，一了百了。

**Comment by luluuulu4848** [comment]
![image](https://user-images.githubusercontent.com/9544627/65022118-f4e23a80-d962-11e9-8349-a2a01cc37091.png)

> 大量封锁IP段，什么都没用，高墙根本懒得分析数据流，一棍子全打死，一了百了。

我觉得这个推测的确很靠谱,因为挂的大多数都是vultr和搬瓦工.
这些服务商的IP段相对来说比较固定.

**Comment by luluuulu4848** [comment]
> 大量封锁IP段，什么都没用，高墙根本懒得分析数据流，一棍子全打死，一了百了。

我觉得这个分析比较靠谱,毕竟ban运营商的IP段和分析流量完全不是一个工作量.
每次都是搬瓦工和vultr遭殃

**Comment by Michaol** [comment]
> > 大量封锁IP段，什么都没用，高墙根本懒得分析数据流，一棍子全打死，一了百了。
> 
> 我觉得这个分析比较靠谱,毕竟ban运营商的IP段和分析流量完全不是一个工作量.
> 每次都是搬瓦工和vultr遭殃

这些都是重灾区，还有DO。

**Comment by yellowaug** [comment]
搬瓦工的基本上都是直接墙的，都懒得分析流量了

**Comment by luoyanghero** [comment]
@tspring95 就是。我的bandwagon vps 用了几年好好的，国庆到了，封了。改了ip第二天又封了；再改ip，端口等两天又封了，一直用ss python版本。现在是第三次改ip了，看到有v2Ray，他的伪装有效果吗？

**Comment by Michaol** [comment]
> @tspring95 就是。我的bandwagon vps 用了几年好好的，国庆到了，封了。改了ip第二天又封了；再改ip，改端口，等两天又封了，一直用ss python版本。现在是第三次改ip了，看到有v2Ray，他的伪装有效果吗？

对IP段TCP+ICMP阻断，根本不管你是否伪装或者跑什么协议。简单地说，直接击沉你的船，不管你装的是贫民还是军火，明白？

**Comment by luoyanghero** [comment]
> > @tspring95 就是。我的bandwagon vps 用了几年好好的，国庆到了，封了。改了ip第二天又封了；再改ip，改端口，等两天又封了，一直用ss python版本。现在是第三次改ip了，看到有v2Ray，他的伪装有效果吗？
> 
> 对IP段TCP+ICMP阻断，根本不管你是否伪装或者跑什么协议。简单地说，直接击沉你的船，不管你装的是贫民还是军火，明白？

那能不能这样理解，我买两家公司的vps，用两个段的ip，这样被阻断的概率会小些?

**Comment by Michaol** [comment]
> > > @tspring95 就是。我的bandwagon vps 用了几年好好的，国庆到了，封了。改了ip第二天又封了；再改ip，改端口，等两天又封了，一直用ss python版本。现在是第三次改ip了，看到有v2Ray，他的伪装有效果吗？
> > 
> > 
> > 对IP段TCP+ICMP阻断，根本不管你是否伪装或者跑什么协议。简单地说，直接击沉你的船，不管你装的是贫民还是军火，明白？
> 
> 那能不能这样理解，我买两家公司的vps，用两个段的ip，这样被阻断的概率会小些?

理论上来说确实是的，我是一个搬瓦西岸VPS主跑，CN2线路不是浪得虚名（这次已封）。另外一个DO阿姆斯特丹VPS作为后备，速度慢，但是至今活着。最后就是CF的CDN暂且让搬瓦活着，毕竟那是年费的，等着出狱。

**Comment by zhanhb** [comment]
路由器和电脑上相同配置，路由器可用，电脑不可用，很奇怪。

**Comment by Nicepaul** [comment]
V2ray用WS+TLS目前看比较稳妥，通过了6月和10月都考验，没翻车
