### ISSUE TITLE
Caddy 状态: 未在运行

### ISSUE THREAD

**Issue by hyy34** [233boy/v2ray#309]
使用了cf，为什么安装完毕后，caddy不运行！？？

[root@108 ~]# v2ray status 

 V2Ray 状态: 正在运行  /  Caddy 状态: 未在运行

**Comment by lian233** [comment]
那是因为Caddy注册证书失败了  暂时没解决办法

**Comment by hyy34** [comment]
> 那是因为Caddy注册证书失败了 暂时没解决办法

额。那现在还有哪个好使呢？

**Comment by 372579561** [comment]
我也遇到了类似的问题

**Comment by lotern37** [comment]
1.申请证书时，创建证书存储目录失败，www-data用户权限有问题。

Sep 20 09:19:26 cc-gf caddy[12343]: 2019/09/20 09:19:26 [WARNING] No files matching import glob pattern: sites/*
Sep 20 09:19:26 cc-gf caddy[12343]: Activating privacy features... 2019/09/20 09:19:26 [INFO][cache:0xc000088780] Started certificate maintenance routine
Sep 20 09:19:26 cc-gf caddy[12343]: 2019/09/20 09:19:26 [INFO] acme: Registering account for 89779077120@gmail.com
Sep 20 09:19:27 cc-gf caddy[12343]: 2019/09/20 09:19:27 [ERROR] Making new certificate manager: could not save user: mkdir /etc/ssl/caddy/acme: read-only file system (attempt 1/3)
Sep 20 09:19:27 cc-gf caddy[12343]: 2019/09/20 09:19:27 [INFO] acme: Registering account for 89779077120@gmail.com
Sep 20 09:19:27 cc-gf caddy[12343]: 2019/09/20 09:19:27 [ERROR] Making new certificate manager: registration error: acme: error: 400 :: POST :: https://acme-v02.api.letsencryp...(attempt 2/3)
Sep 20 09:19:27 cc-gf caddy[12343]: 2019/09/20 09:19:27 [INFO] acme: Registering account for 89779077120@gmail.com

2.证书存储失败，导致反复申请证书，最终被letsencrypt封掉IP。

Sep 20 09:37:18 cc-gf caddy[12786]: Activating privacy features... 2019/09/20 09:37:18 [INFO][cache:0xc000088780] Started certificate maintenance routine
Sep 20 09:37:18 cc-gf caddy[12786]: 2019/09/20 09:37:18 [INFO] acme: Registering account for 89779077120@gmail.com
Sep 20 09:37:19 cc-gf caddy[12786]: 2019/09/20 09:37:19 [ERROR] Making new certificate manager: registration error: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-acct :: urn:ietf:params:acme:error:rateLimited :: Error creating new account :: too many registrations for this IP: see https://letsencrypt.org/docs/rate-limits/, url:  (attempt 1/3)
Sep 20 09:37:19 cc-gf caddy[12786]: 2019/09/20 09:37:19 [INFO] acme: Registering account for 89779077120@gmail.com
Sep 20 09:37:19 cc-gf systemd[1]: Stopping Caddy HTTP/2 web server...
Sep 20 09:37:19 cc-gf caddy[12786]: 2019/09/20 09:37:19 [INFO] SIGQUIT: Quitting process immediately

############################

解决方法，安装v2ray时，不安装caddy，改为手动部署caddy。
如果使用nginx，可以使用certbot来申请域名证书。

**Comment by 372579561** [comment]
> 1.申请证书时，创建证书存储目录失败，www-data用户权限有问题。
> 
> Sep 20 09:19:26 cc-gf caddy[12343]: 2019/09/20 09:19:26 [WARNING] No files matching import glob pattern: sites/*
> Sep 20 09:19:26 cc-gf caddy[12343]: Activating privacy features... 2019/09/20 09:19:26 [INFO][cache:0xc000088780] Started certificate maintenance routine
> Sep 20 09:19:26 cc-gf caddy[12343]: 2019/09/20 09:19:26 [INFO] acme: Registering account for [89779077120@gmail.com](mailto:89779077120@gmail.com)
> Sep 20 09:19:27 cc-gf caddy[12343]: 2019/09/20 09:19:27 [ERROR] Making new certificate manager: could not save user: mkdir /etc/ssl/caddy/acme: read-only file system (attempt 1/3)
> Sep 20 09:19:27 cc-gf caddy[12343]: 2019/09/20 09:19:27 [INFO] acme: Registering account for [89779077120@gmail.com](mailto:89779077120@gmail.com)
> Sep 20 09:19:27 cc-gf caddy[12343]: 2019/09/20 09:19:27 [ERROR] Making new certificate manager: registration error: acme: error: 400 :: POST :: https://acme-v02.api.letsencryp...(attempt 2/3)
> Sep 20 09:19:27 cc-gf caddy[12343]: 2019/09/20 09:19:27 [INFO] acme: Registering account for [89779077120@gmail.com](mailto:89779077120@gmail.com)
> 
> 2.证书存储失败，导致反复申请证书，最终被letsencrypt封掉IP。
> 
> Sep 20 09:37:18 cc-gf caddy[12786]: Activating privacy features... 2019/09/20 09:37:18 [INFO][cache:0xc000088780] Started certificate maintenance routine
> Sep 20 09:37:18 cc-gf caddy[12786]: 2019/09/20 09:37:18 [INFO] acme: Registering account for [89779077120@gmail.com](mailto:89779077120@gmail.com)
> Sep 20 09:37:19 cc-gf caddy[12786]: 2019/09/20 09:37:19 [ERROR] Making new certificate manager: registration error: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-acct :: urn:ietf:params:acme:error:rateLimited :: Error creating new account :: too many registrations for this IP: see https://letsencrypt.org/docs/rate-limits/, url: (attempt 1/3)
> Sep 20 09:37:19 cc-gf caddy[12786]: 2019/09/20 09:37:19 [INFO] acme: Registering account for [89779077120@gmail.com](mailto:89779077120@gmail.com)
> Sep 20 09:37:19 cc-gf systemd[1]: Stopping Caddy HTTP/2 web server...
> Sep 20 09:37:19 cc-gf caddy[12786]: 2019/09/20 09:37:19 [INFO] SIGQUIT: Quitting process immediately
> 
> ############################
> 
> 解决方法，安装v2ray时，不安装caddy，改为手动部署caddy。
> 如果使用nginx，可以使用certbot来申请域名证书。

多谢，确实是由此问题导致的，已经重装了nginx手动生成证书后一切正常

**Comment by lian233** [comment]
> 1.申请证书时，创建证书存储目录失败，www-data用户权限有问题。
> 
> Sep 20 09:19:26 cc-gf caddy[12343]: 2019/09/20 09:19:26 [WARNING] No files matching import glob pattern: sites/*
> Sep 20 09:19:26 cc-gf caddy[12343]: Activating privacy features... 2019/09/20 09:19:26 [INFO][cache:0xc000088780] Started certificate maintenance routine
> Sep 20 09:19:26 cc-gf caddy[12343]: 2019/09/20 09:19:26 [INFO] acme: Registering account for [89779077120@gmail.com](mailto:89779077120@gmail.com)
> Sep 20 09:19:27 cc-gf caddy[12343]: 2019/09/20 09:19:27 [ERROR] Making new certificate manager: could not save user: mkdir /etc/ssl/caddy/acme: read-only file system (attempt 1/3)
> Sep 20 09:19:27 cc-gf caddy[12343]: 2019/09/20 09:19:27 [INFO] acme: Registering account for [89779077120@gmail.com](mailto:89779077120@gmail.com)
> Sep 20 09:19:27 cc-gf caddy[12343]: 2019/09/20 09:19:27 [ERROR] Making new certificate manager: registration error: acme: error: 400 :: POST :: https://acme-v02.api.letsencryp...(attempt 2/3)
> Sep 20 09:19:27 cc-gf caddy[12343]: 2019/09/20 09:19:27 [INFO] acme: Registering account for [89779077120@gmail.com](mailto:89779077120@gmail.com)
> 
> 2.证书存储失败，导致反复申请证书，最终被letsencrypt封掉IP。
> 
> Sep 20 09:37:18 cc-gf caddy[12786]: Activating privacy features... 2019/09/20 09:37:18 [INFO][cache:0xc000088780] Started certificate maintenance routine
> Sep 20 09:37:18 cc-gf caddy[12786]: 2019/09/20 09:37:18 [INFO] acme: Registering account for [89779077120@gmail.com](mailto:89779077120@gmail.com)
> Sep 20 09:37:19 cc-gf caddy[12786]: 2019/09/20 09:37:19 [ERROR] Making new certificate manager: registration error: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-acct :: urn:ietf:params:acme:error:rateLimited :: Error creating new account :: too many registrations for this IP: see https://letsencrypt.org/docs/rate-limits/, url: (attempt 1/3)
> Sep 20 09:37:19 cc-gf caddy[12786]: 2019/09/20 09:37:19 [INFO] acme: Registering account for [89779077120@gmail.com](mailto:89779077120@gmail.com)
> Sep 20 09:37:19 cc-gf systemd[1]: Stopping Caddy HTTP/2 web server...
> Sep 20 09:37:19 cc-gf caddy[12786]: 2019/09/20 09:37:19 [INFO] SIGQUIT: Quitting process immediately
> 
> ############################
> 
> 解决方法，安装v2ray时，不安装caddy，改为手动部署caddy。
> 如果使用nginx，可以使用certbot来申请域名证书。

多谢  解决了

**Comment by boparticle** [comment]
兄弟们都是用这个脚本，解决了问题的哥们能否贴出自己的caddy配置？感谢感谢！

**Comment by lotern37** [comment]
> 兄弟们都是用这个脚本，解决了问题的哥们能否贴出自己的caddy配置？感谢感谢！

没用Caddy，用nginx，证书的话使用certBot或是自己装openssl生成都行。

**Comment by supriome** [comment]
我这边的解决方法是，重新certbot了网站的证书，然后再v2ray status时，显示caddy正常运行了

**Comment by MrBearWithHisSword** [comment]
如果想要以非root用户运行caddy可以参考一下这篇博客~ https://www.coldawn.com/%E5%9C%A8oracle-cloud%E5%85%8D%E8%B4%B9vps-centos-7-%E7%B3%BB%E7%BB%9F%E4%B8%8A%E5%AE%89%E8%A3%85web%E6%9C%8D%E5%8A%A1%E5%99%A8caddy/

**Comment by SunoAries** [comment]
80端口被占了，关了重启就ok了
