### ISSUE TITLE
国内部分网站无法访问

### ISSUE THREAD

**Issue by Tyro-Fang** [233boy/v2ray#310]
使用一键脚本搭建后开启全局模式，发现有些国内网站访问特别慢，有些甚至无法访问，比如csdn，几乎都是无法打开，请问是配置参数或者哪里需要修改么？

**Comment by zhz1237ok** [comment]
全局意思就是全部流量经过VPS再回到你的机子上，国内网站发到国外再发回来，当然慢，切成PAC就好

**Comment by Tyro-Fang** [comment]
> 全局意思就是全部流量经过VPS再回到你的机子上，国内网站发到国外再发回来，当然慢，切成PAC就好

这个我知道，但是有些网站是完全打不开的，使用别的第三方软件直接走全局却能打开，所以我想问下是不是在脚本之后还需要设置别的东西，类似dns之类的

**Comment by zhz1237ok** [comment]
> > 全局意思就是全部流量经过VPS再回到你的机子上，国内网站发到国外再发回来，当然慢，切成PAC就好
> 
> 这个我知道，但是有些网站是完全打不开的，使用别的第三方软件直接走全局却能打开，所以我想问下是不是在脚本之后还需要设置别的东西，类似dns之类的

不用设置´_＞` 就这样的，建议先用PAC，然后遇到github这种国内也能打开但是很慢的网站切换成全局

**Comment by Tyro-Fang** [comment]
> > > 全局意思就是全部流量经过VPS再回到你的机子上，国内网站发到国外再发回来，当然慢，切成PAC就好
> > 
> > 
> > 这个我知道，但是有些网站是完全打不开的，使用别的第三方软件直接走全局却能打开，所以我想问下是不是在脚本之后还需要设置别的东西，类似dns之类的
> 
> 不用设置´_＞` 就这样的，建议先用PAC，然后遇到github这种国内也能打开但是很慢的网站切换成全局

这种方法当然可以，但是我想解决全局模式下部分国内网站打不开的问题

**Comment by devinstever** [comment]
如果是特定网站太慢，而如果你知道vps所在地能访问到的最快ip的话，可以修改vps的hosts文件指过去。
如果是国内网站普遍都很慢的话，那就只能更换其他地域或者别的服务商的vps了。

**Comment by 233boy** [comment]
@Tyro-Fang 

你是不是开全局了。如果是使用 V2RayN ，可以在设置里面打开，路由设置，绕过局域网及大陆地址。

**Comment by zhz1237ok** [comment]
> > > > 全局意思就是全部流量经过VPS再回到你的机子上，国内网站发到国外再发回来，当然慢，切成PAC就好
> > > 
> > > 
> > > 这个我知道，但是有些网站是完全打不开的，使用别的第三方软件直接走全局却能打开，所以我想问下是不是在脚本之后还需要设置别的东西，类似dns之类的
> > 
> > 
> > 不用设置´_＞` 就这样的，建议先用PAC，然后遇到github这种国内也能打开但是很慢的网站切换成全局
> 
> 这种方法当然可以，但是我想解决全局模式下部分国内网站打不开的问题

打不开是怎么个打不开法，提示什么，我怀疑你IP被国内网站封了

**Comment by liuqianghui** [comment]
这种就像是国内网被国外网屏蔽了，从题主的服务器进不了该网站导致的，正确方法应该是使用 pac 分流

**Comment by qins** [comment]
有时候是DNS设置问题。刚刚就更改DNS解决了

**Comment by Pisceshub** [comment]
> 这种就像是国内网被国外网屏蔽了，从题主的服务器进不了该网站导致的，正确方法应该是使用 pac 分流

改pac模式全局就可以内外兼修了，太感谢了！！

**Comment by yuanxy** [comment]
https://github.com/2dust/v2rayN/issues/4374#issuecomment-2646815458
