### ISSUE TITLE
WebSocket + TLS 下载 Caddy 失败 

### ISSUE THREAD

**Issue by lzybio** [233boy/v2ray#313]
V2Ray 传输协议 = WebSocket + TLS 时，下载 Caddy 失败，如下：

--2019-09-20 16:21:14--  https://caddyserver.com/download/linux/amd64?license=personal
Resolving caddyserver.com (caddyserver.com)... 138.68.240.78, 2604:a880:2:d0::1145:e001
Connecting to caddyserver.com (caddyserver.com)|138.68.240.78|:443... connected.
HTTP request sent, awaiting response... 502 Bad Gateway
2019-09-20 16:21:17 ERROR 502: Bad Gateway.

 下载 Caddy 失败！

**Comment by h6fYe34KFSiH** [comment]
Duplicate of #297

**Comment by AbelMakihara** [comment]
Sorry, our download page is unavailable at the moment. The build server is undergoing maintenance. 

You could try again in a few minutes, or download Caddy from GitHub without waiting.

**Comment by foxes1998** [comment]
如果可以把脚本的 下载 caddy 的链接改成 caddy 在 github 上的下载链接就好了，可是我不知道改哪里

**Comment by AbelMakihara** [comment]
> 如果可以把脚本的 下载 caddy 的链接改成 caddy 在 github 上的下载链接就好了，可是我不知道改哪里

就把这里改掉就好了啊
`if [[ ${bit} == "x86_64" ]]; then
		wget --no-check-certificate -O "caddy_linux.tar.gz" "https://caddyserver.com/download/linux/amd64${extension_all}"
	elif [[ ${bit} == "i386" || ${bit} == "i686" ]]; then
		wget --no-check-certificate -O "caddy_linux.tar.gz" "https://caddyserver.com/download/linux/386${extension_all}"
	elif [[ ${bit} == "armv7l" ]]; then
		wget --no-check-certificate -O "caddy_linux.tar.gz" "https://caddyserver.com/download/linux/arm7${extension_all}"
	else`

**Comment by 233boy** [comment]
@lzybio 

这是因为官方的服务器出的问题，不过现在已经他们修复了 😄

**Comment by chaoxi24** [comment]
> 
> 
> @lzybio
> 
> 这是因为官方的服务器出的问题，不过现在已经他们修复了 😄

现在再次下载失败了，好像是改路径了，请问能修复吗？



--2020-07-21 20:55:17--  https://caddyserver.com/download/linux/amd64?license=personal
Resolving caddyserver.com (caddyserver.com)... 165.227.20.207, 2604:a880:2:d0::21b0:6001
Connecting to caddyserver.com (caddyserver.com)|165.227.20.207|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-07-21 20:55:17 ERROR 404: Not Found.

 下载 Caddy 失败！

**Comment by JamieStorpk** [comment]
> > @lzybio
> > 这是因为官方的服务器出的问题，不过现在已经他们修复了 😄
> 
> 现在再次下载失败了，好像是改路径了，请问能修复吗？
> 
> --2020-07-21 20:55:17-- https://caddyserver.com/download/linux/amd64?license=personal
> Resolving caddyserver.com (caddyserver.com)... 165.227.20.207, 2604:a880:2:d0::21b0:6001
> Connecting to caddyserver.com (caddyserver.com)|165.227.20.207|:443... connected.
> HTTP request sent, awaiting response... 404 Not Found
> 2020-07-21 20:55:17 ERROR 404: Not Found.
> 
> 下载 Caddy 失败！

是的，我今天也是這樣，caddy下載失敗
