### ISSUE TITLE
Commits #ebcbbc2 为嘛改用疼逊的DNS?

### ISSUE THREAD

**Issue by Antecer** [233boy/v2ray#319]
如题, 难道不怕死的快么, 竟然用疼逊的DNS?

**Comment by 233boy** [comment]
@Antecer 国内的域名用腾讯的 DNS 来解析有什么问题吗？？？

**Comment by Antecer** [comment]
好吧,我只是看到用了疼逊的DNS,没具体看是用在国内还是国外了..
