### ISSUE TITLE
Caddy跑不起来

### ISSUE THREAD

**Issue by edgeowner** [233boy/v2ray#320]
Redirecting to /bin/systemctl status caddy.service
● caddy.service - Caddy HTTP/2 web server
   Loaded: loaded (/etc/systemd/system/caddy.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since 日 2019-09-22 23:54:52 CST; 2min 58s ago
     Docs: https://caddyserver.com/docs
  Process: 6492 ExecStart=/usr/local/bin/caddy -log stdout -agree=true -conf=/etc/caddy/Caddyfile -root=/var/tmp (code=exited, status=1/FAILURE)
 Main PID: 6492 (code=exited, status=1/FAILURE)

**Comment by 233boy** [comment]
@edgeowner 新安装的？还是？输入 v2ray version 看看脚本版本是多少？

**Comment by jpfree** [comment]
一样的问题，最新的版本。

**Comment by AbelMakihara** [comment]
一样的哦 
不过我后来多试了几次后还是自动申请下来证书了
然后就好了
