### ISSUE TITLE
按教程一步一步装了SS后，客户端连接无法使用

### ISSUE THREAD

**Issue by ameue** [233boy/v2ray#321]
按教程一步一步装了SS后，客户端连接无法使用，tcpdump 抓ss断口包，发现没有任何数据。是否还需要在iptables里面增加端口规则呢？

**Comment by 233boy** [comment]
> 按教程一步一步装了SS后，客户端连接无法使用，tcpdump 抓ss断口包，发现没有任何数据。是否还需要在iptables里面增加端口规则呢？

看看 v2ray 有没有在运行

**Comment by ameue** [comment]
v2ray status:正在运行

**Comment by 233boy** [comment]
> v2ray status:正在运行
> netstat -tunpl|grep ss端口，也是运行的

输入 v2ray ss，换一个端口再看看？

**Comment by ameue** [comment]
还是不行。eth0 23456端口没有数据通过

**Comment by ameue** [comment]
阿里云CentOS Linux release 7.7.1908 (Core)

**Comment by 233boy** [comment]
你是 Centos? Debian 系的，脚本已经自动开放 iptables

**Comment by 233boy** [comment]
原来是阿里，国际大厂的小鸡你得开放防火墙规则

**Comment by 233boy** [comment]
国际大厂，比如 GCP AZURE AWS，当然国内阿里腾讯这种也有一个外部的防火墙的，你得开放相关端口，数据才能流入

**Comment by ameue** [comment]
firewall-cmd --query-port=23456/tcp 
yes
是这个吗

**Comment by 233boy** [comment]
firewall-cmd --permanent --zone=public --add-port=23456/tcp
firewall-cmd --permanent --zone=public --add-port=23456/udp
firewall-cmd --reload

**Comment by ameue** [comment]
还是不行

**Comment by 233boy** [comment]
你先确保你的外部防火墙（在阿里控制台那边配置）有没有将这个端口开放了，然后再开放主机的端口

**Comment by ameue** [comment]
是安全组规则的意思吗？

**Comment by ameue** [comment]
感谢大佬，添加了安全组规则就可以了

**Comment by ameue** [comment]
<img width="1247" alt="QQ20190923-162816@2x" src="https://user-images.githubusercontent.com/10040900/65411371-46853c00-de1f-11e9-957f-a95f12223073.png">
上午配置了完全组规则后开始能行，中午过后，这又不行了，这是eth0端口的数据。v2ray 是运行的。这是什么情况啊
