### ISSUE TITLE
我现在是9/11开始连不了外网 但可以ping通我的ip  哭

### ISSUE THREAD

**Issue by Lelouch-Lamperoge** [233boy/v2ray#322]
用的也是ws+tls  
上vultr看也是
 V2Ray 状态: 正在运行  /  Caddy 状态: 正在运行

两个运行的状态 重新装过好多次了  有碰到过同样问题的大佬救救俺嘛！

**Comment by smashdog** [comment]
同上，用的是cloudflare，连不上

**Comment by AbelMakihara** [comment]
搬瓦工和vultr都存活良好

**Comment by Lelouch-Lamperoge** [comment]
> 同上，用的是cloudflare，连不上

我重新租了个新的服务器 ok了= =
