### ISSUE TITLE
用不了，为什么用systemctl查caddy的状态是这样

### ISSUE THREAD

**Issue by smashdog** [233boy/v2ray#323]
● caddy.service - Caddy HTTP/2 web server
   Loaded: loaded (/usr/lib/systemd/system/caddy.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2019-09-23 18:17:46 CST; 11s ago
     Docs: https://caddyserver.com/docs
 Main PID: 20373 (caddy)
   CGroup: /system.slice/caddy.service
           └─20373 /usr/local/bin/caddy -log stdout -agree=true -conf=/etc/caddy/Caddyfile -root=/var/tmp

Sep 23 18:17:46 hwsrv-517892.hostwindsdns.com caddy[20373]: 2019/09/23 18:17:46 [WARNING] No files matching import glob pattern: sites/*
Sep 23 18:17:46 hwsrv-517892.hostwindsdns.com caddy[20373]: Activating privacy features... 2019/09/23 18:17:46 [INFO][cache:0xc000088780] Started certificate maintenance routine
Sep 23 18:17:46 hwsrv-517892.hostwindsdns.com caddy[20373]: 2019/09/23 18:17:46 [WARNING] Stapling OCSP: no OCSP stapling for [****.com]: parsing OCSP response: ocsp: error from server: unauthorized
Sep 23 18:17:46 hwsrv-517892.hostwindsdns.com caddy[20373]: 2019/09/23 18:17:46 [INFO] Certificate for [****.com] expires in -366h15m38.281206886s; attempting renewal
Sep 23 18:17:46 hwsrv-517892.hostwindsdns.com caddy[20373]: 2019/09/23 18:17:46 [INFO] [****.com] acme: Trying renewal with -366 hours remaining
Sep 23 18:17:46 hwsrv-517892.hostwindsdns.com caddy[20373]: 2019/09/23 18:17:46 [INFO] [****.com] acme: Obtaining bundled SAN certificate
Sep 23 18:17:46 hwsrv-517892.hostwindsdns.com caddy[20373]: 2019/09/23 18:17:46 [ERROR] Renewing [****.com]: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:p...
Sep 23 18:17:56 hwsrv-517892.hostwindsdns.com caddy[20373]: 2019/09/23 18:17:56 [INFO] [****.com] acme: Trying renewal with -366 hours remaining
Sep 23 18:17:56 hwsrv-517892.hostwindsdns.com caddy[20373]: 2019/09/23 18:17:56 [INFO] [****.com] acme: Obtaining bundled SAN certificate
Sep 23 18:17:57 hwsrv-517892.hostwindsdns.com caddy[20373]: 2019/09/23 18:17:57 [ERROR] Renewing [****.com]: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:p...

**Comment by smashdog** [comment]
系统是centos

**Comment by 233boy** [comment]
> 系统是centos

这个有限制了

**Comment by smashdog** [comment]
> > 系统是centos
> 
> 这个有限制了

该如何处理？
