### ISSUE TITLE
敏感时期，大量封禁端口

### ISSUE THREAD

**Issue by SekiBetu** [233boy/v2ray#324]
如果发现无法科学上网，切换端口即可，或者使用动态端口，现在的频率大约是一天封一次端口

**Comment by luoyanghero** [comment]
我经常上google浏览网页和论坛，协议选哪个好些？需要伪装吗？@zhz1237ok

**Comment by RighMelo** [comment]
> 如果发现无法科学上网，切换端口即可，或者使用动态端口，现在的频率大约是一天封一次端口

动态端口如何启用呢？一天封一次真的烦死了

**Comment by xhqpp** [comment]
别用动态端口 把墙惹急了直接封ip

**Comment by ZhaoqiangCn** [comment]
大佬。跟你一样啊。。最近不太平，有什么好办法吗

**Comment by saitoukibi** [comment]
我刚改了几次端口，IP已ban。

**Comment by ameue** [comment]
> 我刚改了几次端口，IP已ban。

哈哈

**Comment by hokuhouhi** [comment]
我说呢，换一个封一个

**Comment by topkof** [comment]
话说用什么协议组合比较安全呢

**Comment by darcyg** [comment]
一个月了，我的IP解封了..
貌似ss协议现在没封了，有兄弟证实一下不

**Comment by topkof** [comment]
有ping也连不上




------------------ 原始邮件 ------------------
发件人: "Darcy Gong"<notifications@github.com>; 
发送时间: 2019年10月24日(星期四) 晚上7:51
收件人: "233boy/v2ray"<v2ray@noreply.github.com>; 
抄送: "ゅ白袜子&#x2641;"<topkof@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [233boy/v2ray] 敏感时期，大量封禁端口 (#324)




一个月了，我的IP解封了..
 貌似ss协议现在没封了，有兄弟证实一下不

**Comment by darcyg** [comment]
ss好像可以用了，我用了2天，满30天自动解封ip

**Comment by topkof** [comment]
没办法，没办法已经买了JMS







------------------ 原始邮件 ------------------
发件人: "Darcy Gong"<notifications@github.com>; 
发送时间: 2019年10月27日(星期天) 下午2:50
收件人: "233boy/v2ray"<v2ray@noreply.github.com>; 
抄送: "ゅ白袜子&#x2641;"<topkof@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [233boy/v2ray] 敏感时期，大量封禁端口 (#324)




ss好像可以用了，我用了2天，满30天自动解封ip
 
&mdash;
