### ISSUE TITLE
如果你的caddy无法正常运行，试试我的方法

### ISSUE THREAD

**Issue by white0rchardpUnK** [233boy/v2ray#327]
我也是重装了两三次caddy有时跑有时不跑，搞到最后ssl证书申请太频繁了直接给我拒了，自己搞了个ssl证书，不自动配置tls，搭配宝塔面板，也跑通了，写了个教程
https://github.com/white0rchardpUnK/v2ray-etc/wiki
有需要的童鞋自取
希望继续完善脚本

**Comment by zgm406** [comment]
写的非常详细，虽然复杂，但是都能看懂，搭建成功，谢谢。

**Comment by jywyq** [comment]
搭建成功 谢谢
