### ISSUE TITLE
昨天更新了脚本文件，就不行了

### ISSUE THREAD

**Issue by leeJqqq** [233boy/v2ray#328]
首先先对这个脚本赞一个，用了好几个月了，但是昨天更新了脚本后就不行了。

用的 websocket+tls ； 服务器：bwg --CentOS 7.6。ip没被q，ssh能连；v2ray status ：v2ray和caddy两个都显示在运行。

报错信息：failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://（我的域名）/): 521 Origin Down > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed

不知道是脚本问题还是tcp阻断了？如果是tcp阻断了有什么方法可以解决吗?

**Comment by 233boy** [comment]
输入这个命令解决问题：`v2ray reinstall`

重装。。。

**Comment by ameue** [comment]
9月 24 12:21:57 iZj6c7upbhe18wh57tlch1Z systemd[1]: caddy.service holdoff time over, scheduling restart.
9月 24 12:21:57 iZj6c7upbhe18wh57tlch1Z systemd[1]: Stopped Caddy HTTP/2 web server.
9月 24 12:21:57 iZj6c7upbhe18wh57tlch1Z systemd[1]: Started Caddy HTTP/2 web server.
9月 24 12:21:57 iZj6c7upbhe18wh57tlch1Z caddy[14526]: 2019/09/24 12:21:57 [WARNING] No files matching import glob pattern: sites/*
9月 24 12:21:57 iZj6c7upbhe18wh57tlch1Z caddy[14526]: Activating privacy features... 2019/09/24 12:21:57 [INFO][cache:0xc0000867d0] Started certificate mai...e routine
9月 24 12:21:58 iZj6c7upbhe18wh57tlch1Z caddy[14526]: 2019/09/24 12:21:58 [INFO] acme: Registering account for 42014343168@gmail.com
9月 24 12:21:59 iZj6c7upbhe18wh57tlch1Z caddy[14526]: 2019/09/24 12:21:59 [ERROR] Making new certificate manager: registration error: acme: error: 429 :: POST :: ht...
9月 24 12:21:59 iZj6c7upbhe18wh57tlch1Z caddy[14526]: 2019/09/24 12:21:59 [INFO] acme: Registering account for 42014343168@gmail.com
9月 24 12:22:00 iZj6c7upbhe18wh57tlch1Z caddy[14526]: 2019/09/24 12:22:00 [ERROR] Making new certificate manager: registration error: acme: error: 429 :: POST :: ht...
9月 24 12:22:00 iZj6c7upbhe18wh57tlch1Z caddy[14526]: 2019/09/24 12:22:00 [INFO] acme: Registering account for 42014343168@gmail.com
Hint: Some lines were ellipsized, use -l to show in full.
@233boy 这是什么意思啊

**Comment by leeJqqq** [comment]
@233boy [笑哭]好，真的可以了[笑哭]
