### ISSUE TITLE
是否安全？会变矿机吗？节点会被分享吗？

### ISSUE THREAD

**Issue by chen406226** [233boy/v2ray#333]
请问下这个脚本有别的注入脚本吗？没有冒犯的意思！！！！只是不想变矿机，还有构建的节点会被分享出去吗？是不是隐私的。因为最近太严只要被分享了立马被封。还有pc的chrome浏览器用v2节点用不了google未授权怎么搞？希望回答 感谢！

**Comment by 1608637229** [comment]
这个脚本会屏蔽一些轮子的网站，已经默认屏蔽bt下载，其他应该没了

**Comment by jzoy** [comment]
油管里面有人拍了视频分析，可以看看哈哈，如果有恶意代码，这么多人用估计也早爆出来了
