### ISSUE TITLE
有人看看吗？服务器建了wordpress网站与v2ray的http/2冲突了

### ISSUE THREAD

**Issue by victsdo2005** [233boy/v2ray#334]
我先是弄了个wordpress网站，然后用脚本弄了个v2ray,http/2的，但是v2无法连接，而当我关闭nginx服务后，v2又可以正常连接了。
我用的脚本没有“caddy或nginx”的说明。。。
现在有什么方法可以让我的网站与v2共存？

**Comment by DoraemonAndRat** [comment]
检查443端口占用
