### ISSUE TITLE
套了cdn后还是没网，caddy启动中。

### ISSUE THREAD

**Issue by 1608637229** [233boy/v2ray#335]
ping我那个网址也是正常显示的美国 CloudFlare公司CDN节点。
日志大量重复以下是什么原因。
2019/09/26 11:25:11 [Warning] [1529034959] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://www.xxxxxxx.tk/): 301 Moved Permanently > websocket: bad handshake v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://www.xxxxxxx.tk/):  > read tcp 192.168.43.68:63156->104.28.0.123:443: wsarecv: An established connection was aborted by the software in your host machine. v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://www.xxxxxxxx.tk/):  > dial tcp: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed

**Comment by 233boy** [comment]
@1608637229 
客户端配置的端口，将 80 更改成 443

**Comment by 1608637229** [comment]
> @1608637229
> 客户端配置的端口，将 80 更改成 443

可我查看v2ray配置信息显示就是443啊。你这个脚本最后会自动改成443我记得

**Comment by 233boy** [comment]
> > @1608637229
> > 客户端配置的端口，将 80 更改成 443
> 
> 可我查看v2ray配置信息显示就是443啊。你这个脚本最后会自动改成443我记得

我说你客户端的配置，不是服务器，你看看你客户端的配置，是不是将端口写 80 了。如果是，请更改成 443，然后，**确保 Cloudflare 的 Crypto 选项卡的 SSL 为 Full**

**Comment by 1608637229** [comment]
> > > @1608637229
> > > 客户端配置的端口，将 80 更改成 443
> > 
> > 
> > 可我查看v2ray配置信息显示就是443啊。你这个脚本最后会自动改成443我记得
> 
> 我说你客户端的配置，不是服务器，你看看你客户端的配置，是不是将端口写 80 了。如果是，请更改成 443，然后，**确保 Cloudflare 的 Crypto 选项卡的 SSL 为 Full**

是443.我是直接导入的v2ray ur

**Comment by 1608637229** [comment]
> > > @1608637229
> > > 客户端配置的端口，将 80 更改成 443
> > 
> > 
> > 可我查看v2ray配置信息显示就是443啊。你这个脚本最后会自动改成443我记得
> 
> 我说你客户端的配置，不是服务器，你看看你客户端的配置，是不是将端口写 80 了。如果是，请更改成 443，然后，**确保 Cloudflare 的 Crypto 选项卡的 SSL 为 Full**

好吧。好像是哪个full没改，但是配置的时候看了一开始full后面今天看又变成了flexible了
