### ISSUE TITLE
配置nginx后，配置tls的path失败问题

### ISSUE THREAD

**Issue by qinghuannn** [233boy/v2ray#339]
问题描述：
   我自己配好nginx后，然后使用v2ray面板修改传输协议为web+TLS，因为脚本只允许自动设置或者选择自动设置关闭。然后我尝试修改/etc/v2ray/config.json文件中部分内如：
"wsSettings": {
                    "path": "/ray",
                    "headers": {
                        "Host": "****"
               }
}
然后重启v2ray，查看tls的path是否配置成功，发现path依旧是"/"，此时再去看config.json文件发现刚刚所做的修改消失了（是被v2ray脚本覆盖了吗？）
后面我尝试先关掉v2ray，然后修改完config.jason后，再启动v2ray，还是遇到同样的问题。
请问这是我哪里操作的不对吗？还是这是个bug？

**Comment by liuc96** [comment]
233blog_v2ray_config.json "path": "/"=>"path": "/ray"
