### ISSUE TITLE
v2 cf 加 ng 还是无法翻墙

### ISSUE THREAD

**Issue by misskiki** [233boy/v2ray#340]
![Uploading image.png…]()

我这边配置好了 v2
也测试了选择用cdn链接防止被ban ip
可是还是无法翻墙

**Comment by xzwork** [comment]
防火墙关了没

**Comment by SM-N920T** [comment]
> 我这边配置好了 v2
> 也测试了选择用cdn链接防止被ban ip
> 可是还是无法翻墙

现在的一键脚本都是CENTOS7的，请问现在CENTOS8如何配置V2RAY翻墙
