### ISSUE TITLE
请教大家，WS+TLS+代理的话，要不要开BBR加速，开的话是加速哪个端口，443端口还是v2ray配置文件里inbounds的端口号？谢谢大家！

### ISSUE THREAD

**Issue by lliurf** [233boy/v2ray#341]

**Comment by yuzhenghuan** [comment]
开完就加速了用哪个四合一脚本

**Comment by lliurf** [comment]
> 开完就加速了用哪个四合一脚本

谢谢！不好意思，我的是openvz小鸡，不能安装四合一，是另外安装浪版BBR，而且要手动输入要加速的端口

**Comment by yuzhenghuan** [comment]
233boy/v2ray
    centos7安装ws tls不能开启伪装 不然连不了 只有乌班图和debian可以

2019-09-28
<https://maas.mail.163.com/dashi-web-extend/html/proSignature.html?ftlId=1&name=ming+yu&uid=yuzhenghuan45%40outlook.com&iconUrl=https%3A%2F%2Fmail-online.nosdn.127.net%2Fsm7a2ff3dc9c86fdc1b00717c0c1e1f82a.jpg&items=%5B%22yuzhenghuan45%40outlook.com%22%5D>
[https://mail-online.nosdn.127.net/sm7a2ff3dc9c86fdc1b00717c0c1e1f82a.jpg]
ming yu
yuzhenghuan45@outlook.com
签名由 网易邮箱大师<https://mail.163.com/dashi/dlpro.html?from=mail81> 定制
在2019年09月28日 19:11，123<notifications@github.com><mailto:notifications@github.com> 写道：

开完就加速了用哪个四合一脚本

谢谢！不好意思，我的是openvz小鸡，不能安装四合一，是另外安装浪版BBR，而且要手动输入要加速的端口
