### ISSUE TITLE
centos7 ws+tls无法连接，ss可以连接，说明centos7这脚本搭建的不行，而且乌班图debian都没问题

### ISSUE THREAD

**Issue by yuzhenghuan** [233boy/v2ray#342]
脚本问题还是cent0s7不支持这种协议？

**Comment by blueveryday** [comment]
> 脚本问题还是cent0s7不支持这种协议？

确实连不上，另外一家脚本就没有问题。

**Comment by yuzhenghuan** [comment]
脚本 7开不了伪装  可以跳过 其他没问题

<https://maas.mail.163.com/dashi-web-extend/html/proSignature.html?ftlId=1&name=yuzhenghuan45&iconUrl=https%3A%2F%2Fmail-online.nosdn.127.net%2Fqiyelogo%2FdefaultAvatar.png&items=%5B%22%E9%82%AE%E7%AE%B1%EF%BC%9Ayuzhenghuan45%40outlook.com%22%5D>
[https://mail-online.nosdn.127.net/qiyelogo/defaultAvatar.png]
yuzhenghuan45
邮箱：yuzhenghuan45@outlook.com

Signature is customized by Netease Mail Master<https://mail.163.com/dashi/dlpro.html?from=mail88>

在2019年09月29日 21:05，blueveryday<mailto:notifications@github.com> 写道：

脚本问题还是cent0s7不支持这种协议？

确实连不上，另外一家脚本就没有问题。

**Comment by huakaidaojia** [comment]
关闭网站伪装和路径分流
