### ISSUE TITLE
使用Cloudflare中转V2Ray流量的问题

### ISSUE THREAD

**Issue by byonejohn** [233boy/v2ray#343]
请教一下使用 WebSocket TLS传输协议 + Cloudflare 救被墙 IP，转换协议成功后端口一定要改么，默认就是443，但教程建议不要用80和443端口，我现在用443试着感觉还好，是不是443端口会积累识别从而导致屏蔽？

**Comment by YangShizhao** [comment]
教程里的不要用443是说的v2ray不要占用这个端口，这个端口是给caddy留的，然后caddy把请求转到v2ray再去处理，对外的端口用443是没错的

**Comment by byonejohn** [comment]
明白了，谢谢！
