### ISSUE TITLE
oracle cloud上安装完成后无法使用

### ISSUE THREAD

**Issue by ID404** [233boy/v2ray#346]
oracle cloud 上的centos7 安装v2ray后发现只监听ipv6的地址，导致通过ipv4的网络无法连接。

**Comment by SunDevil68** [comment]
我之前搜尋過幾篇文章，大意是說IPv6可以處理IPv4的請求，所以看起來只監聽了IPv6，實際上IPv4和IPv4都有在處理。如果是用的WS+TLS，要不要看看是不是Web服務器沒有bind 80和443的權限？或者可能防火牆沒把埠打開？

下面文章供參考：

https://www.chengweiyang.cn/2017/03/05/why-netstat-not-showup-tcp4-socket/

https://www.coldawn.com/%e5%9c%a8oracle-cloud%e5%85%8d%e8%b4%b9vps-centos-7-%e7%b3%bb%e7%bb%9f%e4%b8%8a%e5%ae%89%e8%a3%85web%e6%9c%8d%e5%8a%a1%e5%99%a8caddy/

**Comment by mcdull** [comment]
oracle上要開 firewall port (不是vm內).
