### ISSUE TITLE
最新的ws+tls用freenom默认的dns解析成功后搭建不了了，用cf接管扣可以搭建，是freenom的dns原因还是脚本原因

### ISSUE THREAD

**Issue by yuzhenghuan** [233boy/v2ray#348]

**Comment by yuzhenghuan** [comment]
dns解析成功了，但是用自带dns都不行我好几个域名都试了，是不是更新脚本后导致默认dns解析不行了呢？

**Comment by SunDevil68** [comment]
DNS解析好像是為了能成功申請SSL證書？有沒有用freenom自帶DNS搭建時的報錯信息？或者是腳本有跑完，但V2Ray status時顯示V2Ray或者Caddy未在運行？那也許可以貼個log，大家研究一下問題出在哪兒。

**Comment by yuzhenghuan** [comment]
问题找到了 freenom的dns出了问题那天 第二天解析le就成功了

<https://maas.mail.163.com/dashi-web-extend/html/proSignature.html?ftlId=1&name=yuzhenghuan45&iconUrl=https%3A%2F%2Fmail-online.nosdn.127.net%2Fqiyelogo%2FdefaultAvatar.png&items=%5B%22%E9%82%AE%E7%AE%B1%EF%BC%9Ayuzhenghuan45%40outlook.com%22%5D>
[https://mail-online.nosdn.127.net/qiyelogo/defaultAvatar.png]
yuzhenghuan45
邮箱：yuzhenghuan45@outlook.com

Signature is customized by Netease Mail Master<https://mail.163.com/dashi/dlpro.html?from=mail88>

在2019年10月12日 09:17，SunDevil68<mailto:notifications@github.com> 写道：

DNS解析好像是為了能成功申請SSL證書？有沒有用freenom自帶DNS搭建時的報錯信息？或者是腳本有跑完，但V2Ray status時顯示V2Ray或者Caddy未在運行？那也許可以貼個log，大家研究一下問題出在哪兒。
