### ISSUE TITLE
websocket+TLS中网站伪装和路径分流怎么使用

### ISSUE THREAD

**Issue by byonejohn** [233boy/v2ray#352]
请问在安装websocket+TLS过程中，网站伪装和路径分流默认是不配置的，如果想配置的话，对v2ray有什么影响，在使用层面有没有相关这两方面的进阶运用

**Comment by SunDevil68** [comment]
目前都是這樣使用，沒有什麼問題，但我個人只追求能使用，對於速度那些不在意，所以你可以考慮先開啟偽裝試試，覺得速度沒問題，再把分流打開試試。

網站偽裝以及分流都是屬於配置在Web服務器端的，記得要先有一個可以用的域名。另外，要記得用233boy大神昨天剛推送的新腳本，應該已經解決之前Web服務器無法取得SSL證書，並導致小雞IP暫時被SSL發放服務器拉黑的情況。

**Comment by DoraemonAndRat** [comment]
nginx里面弄个路径代理v2ray的端口

**Comment by luoyanghero** [comment]
> 目前都是這樣使用，沒有什麼問題，但我個人只追求能使用，對於速度那些不在意，所以你可以考慮先開啟偽裝試試，覺得速度沒問題，再把分流打開試試。
> 
> 網站偽裝以及分流都是屬於配置在Web服務器端的，記得要先有一個可以用的域名。另外，要記得用233boy大神昨天剛推送的新腳本，應該已經解決之前Web服務器無法取得SSL證書，並導致小雞IP暫時被SSL發放服務器拉黑的情況。

我用两年前的脚本，检查更新说没有。233脚本更新网址在哪？

**Comment by QL000** [comment]
为什么我怎么设置我的伪装域名都会跟域名相同
