### ISSUE TITLE
使用一键脚本安装好服务后，更换成私有证书，无法正常使用

### ISSUE THREAD

**Issue by YangShizhao** [233boy/v2ray#353]
使用脚本安装了v2ray和caddy，然后修改了caddy的配置文件，将
```
tls 127263571968@gmail.com
```
改为
```
tls /root/server.pem /root/server.key
```
此时使用v2ray status查看状态都是正常运行的，但是使用v2rayN连接的时候会报错如下：
```
[Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://www.yshzhao.top/): 521 Origin Down > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed
```
请问有人知道怎么解决吗？

**Comment by 233boy** [comment]
你能直接打开你的域名吗

**Comment by YangShizhao** [comment]
> 你能直接打开你的域名吗

不行，打开后也是提示521的错误
![image](https://user-images.githubusercontent.com/13344900/66698917-d6c6ea80-ed14-11e9-83c1-6506cfb1f01c.png)

**Comment by wensley** [comment]
> > 你能直接打开你的域名吗
> 
> 不行，打开后也是提示521的错误
> ![image](https://user-images.githubusercontent.com/13344900/66698917-d6c6ea80-ed14-11e9-83c1-6506cfb1f01c.png)

把cloudflare里不必要的服务都关了就好了，我就是

**Comment by YangShizhao** [comment]
> > > 你能直接打开你的域名吗
> > 
> > 
> > 不行，打开后也是提示521的错误
> > ![image](https://user-images.githubusercontent.com/13344900/66698917-d6c6ea80-ed14-11e9-83c1-6506cfb1f01c.png)
> 
> 把cloudflare里不必要的服务都关了就好了，我就是

这个不必要 的服务具体是指什么呢，我应该关哪些服务啊？

**Comment by wensley** [comment]
> > > > 你能直接打开你的域名吗
> > > 
> > > 
> > > 不行，打开后也是提示521的错误
> > > ![image](https://user-images.githubusercontent.com/13344900/66698917-d6c6ea80-ed14-11e9-83c1-6506cfb1f01c.png)
> > 
> > 
> > 把cloudflare里不必要的服务都关了就好了，我就是
> 
> 这个不必要 的服务具体是指什么呢，我应该关哪些服务啊？

你把SSL/TLS关了试试

**Comment by kuchiki111** [comment]
我的解决方法是在私有证书的那个域名前面加上htts:// 再复制一套一样的换成http://并且把里面的tls删了就好了
![image](https://user-images.githubusercontent.com/24310042/73429490-c6478800-4376-11ea-80fa-268ca67b634d.png)

**Comment by sususweet** [comment]
> 我的解决方法是在私有证书的那个域名前面加上htts:// 再复制一套一样的换成[http://并且把里面的tls删了就好了](http://%E5%B9%B6%E4%B8%94%E6%8A%8A%E9%87%8C%E9%9D%A2%E7%9A%84tls%E5%88%A0%E4%BA%86%E5%B0%B1%E5%A5%BD%E4%BA%86)
> ![image](https://user-images.githubusercontent.com/24310042/73429490-c6478800-4376-11ea-80fa-268ca67b634d.png)

这个方法有效，感谢！
