### ISSUE TITLE
Please generate json config file without commnet

### ISSUE THREAD

**Issue by nooperpudd** [233boy/v2ray#354]
json data format dont support comment, please fix that.
```		//include_ss
		//include_socks
		//include_mtproto
		//include_in_config
		//
```
please remove the // comment.

**Comment by 233boy** [comment]
> json data format dont support comment, please fix that.
> 
> ```
> 		//include_socks
> 		//include_mtproto
> 		//include_in_config
> 		//
> ```
> 
> please remove the // comment.

please waiting 4.0 version update. the // comment will remove, i so sorry

**Comment by jolestar** [comment]
@233boy can support include external config, so user can add custom config.
