### ISSUE TITLE
中国服务器，白天安装不了v2ray，很慢

### ISSUE THREAD

**Issue by kingco-w** [233boy/v2ray#357]
想自己搭建回国线路，可是用中国服务器安装v2ray脚本真的好慢啊，白天安装都是XXXb一秒。、、、请问这个怎样才可以处理得了？

**Comment by a7611818** [comment]
老哥脚本可以发一个吗

**Comment by linhongjun** [comment]
因为你在中国。。。而脚本需要访问github  国内直连很慢。。。

**Comment by 233boy** [comment]
@kingco-w 无解呀，国内访问 github 速度不行。。

**Comment by nxtreaming** [comment]
一个简单的解决方法是：在一个回国速度快的线路（如某些香港直连华夏国的供应商）上部署一个http代理服务（squid之类的正向代理），然后通过代理来访问github。

注意一地要在海外主机上开正向代理，不要在过你机房开正向代理，否则会被有关部门喝茶。

**Comment by ntgeralt** [comment]
楼上够小胆，
想做个国内访问快的，tb 马云 onedrive 世纪互联直链。
or随便开台gcp aws，frp反代直链地址。frp服务端在大陆和cn2的都不会差
全可匿踪

**Comment by nxtreaming** [comment]
> tb 码云 onedrive 世纪互联等直链

这个不明白，请说详细一下如何实现？
