### ISSUE TITLE
v2ray，配置好后，不能上网

### ISSUE THREAD

**Issue by beckhamaaa** [233boy/v2ray#358]
config.json:
{
	"log": {
		"access": "/var/log/v2ray/access.log",
		"error": "/var/log/v2ray/error.log",
		"loglevel": "debug"
	},
	"inbounds": [
		{
			"port": xxxx,
			"protocol": "vmess",
			"listen":"xxxx", 
			"settings": {
				"clients": [
					{
						"id": "9b2c0ddd-8d81-4a83-ad0b-79571816799f",
						"level": 1,
						"alterId": 233
					}
				]
			},
			"streamSettings": {
				"network": "tcp"
			},
			"sniffing": {
				"enabled": true,
				"destOverride": [
					"http",
					"tls"
				]
			}
		}
		//include_ss
		//include_socks
		//include_mtproto
		//include_in_config
		//
	],
	"outbounds": [
		{
			"protocol": "freedom",
			"settings": {}
		},
		{
			"protocol": "blackhole",
			"settings": {},
			"tag": "blocked"
		},
		{
			"protocol": "freedom",
			"settings": {},
			"tag": "direct"
		},
		{
			"protocol": "mtproto",
			"settings": {},
			"tag": "tg-out"
		}
		//include_out_config
		//
	],
	"dns": {
		"server": [
			"1.1.1.1",
			"1.0.0.1",
			"8.8.8.8",
			"8.8.4.4",
			"localhost"
		]
	},
	"routing": {
		"domainStrategy": "IPOnDemand",	
		"rules": [
			{
				"type": "field",
				"ip": [
					"0.0.0.0/8",
					"10.0.0.0/8",
					"100.64.0.0/10",
					"127.0.0.0/8",
					"169.254.0.0/16",
					"172.16.0.0/12",
					"192.0.0.0/24",
					"192.0.2.0/24",
					"192.168.0.0/16",
					"198.18.0.0/15",
					"198.51.100.0/24",
					"203.0.113.0/24",
					"::1/128",
					"fc00::/7",
					"fe80::/10"
				],
				"outboundTag": "blocked"
			},
			{
				"type": "field",
				"inboundTag": ["tg-in"],
				"outboundTag": "tg-out"
			}
			,
			{
				"type": "field",
				"domain": [
					"domain:epochtimes.com",
					"domain:epochtimes.com.tw",
					"domain:epochtimes.fr",
					"domain:epochtimes.de",
					"domain:epochtimes.jp",
					"domain:epochtimes.ru",
					"domain:epochtimes.co.il",
					"domain:epochtimes.co.kr",
					"domain:epochtimes-romania.com",
					"domain:erabaru.net",
					"domain:lagranepoca.com",
					"domain:theepochtimes.com",
					"domain:ntdtv.com",
					"domain:ntd.tv",
					"domain:ntdtv-dc.com",
					"domain:ntdtv.com.tw",
					"domain:minghui.org",
					"domain:renminbao.com",
					"domain:dafahao.com",
					"domain:dongtaiwang.com",
					"domain:falundafa.org",
					"domain:wujieliulan.com",
					"domain:ninecommentaries.com",
					"domain:shenyun.com"
				],
				"outboundTag": "blocked"
			}			,
                {
                    "type": "field",
                    "protocol": [
                        "bittorrent"
                    ],
                    "outboundTag": "blocked"
                }
			//include_ban_ad
			//include_rules
			//
		]
	},
	"transport": {
		"kcpSettings": {
            "uplinkCapacity": 100,
            "downlinkCapacity": 100,
            "congestion": true
        },
		"sockopt": {
			"tcpFastOpen": true
		}
	}
}

error.log:
2019/10/10 22:53:46 [Info] [546809255] v2ray.com/core/proxy/vmess/inbound: received request for tcp:v1.mux.cool:0
2019/10/10 22:53:46 [Info] [546809255] v2ray.com/core/common/mux: received request for tcp:sb-ssl.google.com:443
2019/10/10 22:53:46 [Info] [546809255] v2ray.com/core/app/dispatcher: sniffed domain: sb-ssl.google.com
2019/10/10 22:53:46 [Info] [546809255] v2ray.com/core/app/dispatcher: default route for tcp:sb-ssl.google.com:443
2019/10/10 22:53:46 [Info] [546809255] v2ray.com/core/proxy/freedom: opening connection to tcp:sb-ssl.google.com:443
2019/10/10 22:53:46 [Info] [546809255] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:sb-ssl.google.com:443
2019/10/10 22:54:57 [Info] [546809255] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: failed to transfer request > read tcp xxxx:xxxx->117.132.196.142:61252: read: connection reset by peer
2019/10/10 22:54:57 [Info] [546809255] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > context canceled
2019/10/10 22:54:57 [Info] [546809255] v2ray.com/core/common/mux: unexpected EOF > v2ray.com/core/common/mux: failed to read metadata > io: read/write on closed pipe
2019/10/10 22:54:57 [Info] [546809255] v2ray.com/core/common/mux: session 1 ends. > io: read/write on closed pipe
2019/10/10 22:56:24 [Info] [840232144] v2ray.com/core/proxy/vmess/inbound: received request for tcp:v1.mux.cool:0
2019/10/10 22:56:24 [Info] [840232144] v2ray.com/core/common/mux: received request for tcp:github-production-release-asset-2e65be.s3.amazonaws.com:443
2019/10/10 22:56:24 [Info] [840232144] v2ray.com/core/app/dispatcher: sniffed domain: github-production-release-asset-2e65be.s3.amazonaws.com
2019/10/10 22:56:24 [Info] [840232144] v2ray.com/core/app/dispatcher: default route for tcp:github-production-release-asset-2e65be.s3.amazonaws.com:443
2019/10/10 22:56:24 [Info] [840232144] v2ray.com/core/proxy/freedom: opening connection to tcp:github-production-release-asset-2e65be.s3.amazonaws.com:443
2019/10/10 22:56:24 [Info] [840232144] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:github-production-release-asset-2e65be.s3.amazonaws.com:443
2019/10/10 22:59:56 [Info] [840232144] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > v2ray.com/core/proxy/freedom: failed to process request > io: read/write on closed pipe
2019/10/10 22:59:56 [Info] [840232144] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: connection ends > writev tcp xxxx:xxxx->117.132.196.142:61253: writev: connection reset by peer
2019/10/10 22:59:56 [Info] [840232144] v2ray.com/core/common/mux: session 1 ends. > io: read/write on closed pipe

**Comment by liuqianghui** [comment]
详细可参考[v2ray config](https://www.v2ray.com/chapter_00/start.html) 你这情况就是配置没配置对 上面那个如果没看懂的话 再参考这个白话版的试试[白话版](https://toutyrater.github.io/basic/vmess.html) 
````shell
{
  "inbounds": [
    {
      "port": 16823, // 服务器监听端口
      "protocol": "vmess",    // 主传入协议
      "settings": {
        "clients": [
          {
            "id": "b831381d-6324-4d53-ad4f-8cda48b30811",  // 用户 ID，客户端与服务器必须相同
            "alterId": 64
          }
        ]
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",  // 主传出协议
      "settings": {}
    }
  ]
}
````

**Comment by zhangluwei1997** [comment]
大佬，请教一个问题。 配置完成后 客户端  access.log 和 error.log 日志都是空的  是不是就是单纯的被墙了？ @liuqianghui

**Comment by beckhamaaa** [comment]
目前，我按照你说的配置了，还是连不上，这是日志：
Oct 19 01:22:12 quick-ponies-1.localdomain dhclient[26607]: DHCPDISCOVER on eth1 to 255.255.255.255 port 67 interval 5 (xid=0x42f108b8)
Oct 19 01:22:17 quick-ponies-1.localdomain dhclient[26607]: No DHCPOFFERS received.
Oct 19 01:22:17 quick-ponies-1.localdomain dhclient[26607]: No working leases in persistent database - sleeping.
Oct 19 01:22:17 quick-ponies-1.localdomain NetworkManager[820]: <info>  [1571419337.0245] dhcp4 (eth1): state changed unknown -> fail
Oct 19 01:22:17 quick-ponies-1.localdomain NetworkManager[820]: <info>  [1571419337.0409] dhcp4 (eth1): canceled DHCP transaction, DHCP client pid 26607
Oct 19 01:22:17 quick-ponies-1.localdomain NetworkManager[820]: <info>  [1571419337.0410] dhcp4 (eth1): state changed fail -> done
Oct 19 01:22:17 quick-ponies-1.localdomain NetworkManager[820]: <info>  [1571419337.0417] device (eth1): state change: ip-config -> failed (reason 'ip-config-unavailable') [70 120 5]
Oct 19 01:22:17 quick-ponies-1.localdomain NetworkManager[820]: <info>  [1571419337.0422] policy: disabling autoconnect for connection 'System eth1'.
Oct 19 01:22:17 quick-ponies-1.localdomain NetworkManager[820]: <warn>  [1571419337.0425] device (eth1): Activation: failed for connection 'System eth1'
Oct 19 01:22:17 quick-ponies-1.localdomain NetworkManager[820]: <info>  [1571419337.0436] device (eth1): state change: failed -> disconnected (reason 'none') [120 30 0]

**Comment by liuqianghui** [comment]
> 大佬，请教一个问题。 配置完成后 客户端 access.log 和 error.log 日志都是空的 是不是就是单纯的被墙了？ @liuqianghui

大佬不敢当，这个日志的，我倒是没特意去看过，一般配置完，然后服务跑起来我就去上网了，没看太多。:smile:

**Comment by liuqianghui** [comment]
> 目前，我按照你说的配置了，还是连不上，这是日志：
> Oct 19 01:22:12 quick-ponies-1.localdomain dhclient[26607]: DHCPDISCOVER on eth1 to 255.255.255.255 port 67 interval 5 (xid=0x42f108b8)
> Oct 19 01:22:17 quick-ponies-1.localdomain dhclient[26607]: No DHCPOFFERS received.
> Oct 19 01:22:17 quick-ponies-1.localdomain dhclient[26607]: No working leases in persistent database - sleeping.
> Oct 19 01:22:17 quick-ponies-1.localdomain NetworkManager[820]: [1571419337.0245] dhcp4 (eth1): state changed unknown -> fail
> Oct 19 01:22:17 quick-ponies-1.localdomain NetworkManager[820]: [1571419337.0409] dhcp4 (eth1): canceled DHCP transaction, DHCP client pid 26607
> Oct 19 01:22:17 quick-ponies-1.localdomain NetworkManager[820]: [1571419337.0410] dhcp4 (eth1): state changed fail -> done
> Oct 19 01:22:17 quick-ponies-1.localdomain NetworkManager[820]: [1571419337.0417] device (eth1): state change: ip-config -> failed (reason 'ip-config-unavailable') [70 120 5]
> Oct 19 01:22:17 quick-ponies-1.localdomain NetworkManager[820]: [1571419337.0422] policy: disabling autoconnect for connection 'System eth1'.
> Oct 19 01:22:17 quick-ponies-1.localdomain NetworkManager[820]: [1571419337.0425] device (eth1): Activation: failed for connection 'System eth1'
> Oct 19 01:22:17 quick-ponies-1.localdomain NetworkManager[820]: [1571419337.0436] device (eth1): state change: failed -> disconnected (reason 'none') [120 30 0]

你这边倒数第 7 行显示```ip-config -> failed```，你配合其他的报错看看配置有没有错，最好是从新走一遍流程，可能有哪些地方有遗漏的错误没发现，加油:fight:

**Comment by iszmxw** [comment]
我的可以上网

发送自 Windows 10 版邮件应用

发件人: liuqianghui
发送时间: 2019年10月22日 9:02
收件人: 233boy/v2ray
抄送: Subscribed
主题: Re: [233boy/v2ray] v2ray，配置好后，不能上网 (#358)

大佬，请教一个问题。 配置完成后 客户端 access.log 和 error.log 日志都是空的 是不是就是单纯的被墙了？ @liuqianghui
大佬不敢当，这个日志的，我倒是没特意去看过，一般配置完，然后服务跑起来我就去上网了，没看太多。😄
