### ISSUE TITLE
Please make a one-key script for vultr's CentOS 8 system. Now vultr only has CentOS 8 x64 VPS

### ISSUE THREAD

**Issue by SM-N920T** [233boy/v2ray#360]
I see that all the one-click scripts you provide are CentOS 7, but I can't surf the Internet with the CentOS 8 x64 VPS opened by vultr website with your previous scripts, please find a solution

**Comment by wimdaw** [comment]
guzhixxi

**Comment by 233boy** [comment]
@SM-N920T 
CentOS 8 cannot run????
