### ISSUE TITLE
小火箭（Shadowrocket）不支持KCP，TCP又慢得抓狂，有没有什么办法？

### ISSUE THREAD

**Issue by xBinge** [233boy/v2ray#361]
小火箭（Shadowrocket）不支持KCP，TCP又慢得抓狂，有没有什么办法？
或者有其他好用的IOS端APP？

**Comment by jzoy** [comment]
我用的是kitsunebi，不知道能不能满足你的需求，要美区账号

**Comment by xBinge** [comment]
> 我用的是kitsunebi，不知道能不能满足你的需求，要美区账号

Nice！可以了，十分感谢！
