### ISSUE TITLE
防火墙GFW再升级！识别封杀翻墙新技术，北京理工大学已申请V2ray流量识别新专利！面对GFW新技术，以后翻墙要如何应对？

### ISSUE THREAD

**Issue by gaojun6854** [233boy/v2ray#362]
![image](https://user-images.githubusercontent.com/10285630/66799105-656c7f00-ef42-11e9-9554-585a7c95a478.png)
![image](https://user-images.githubusercontent.com/10285630/66799126-79b07c00-ef42-11e9-865f-2fd2c1a8102f.png)

**Comment by gdky005** [comment]
我就说一句，以后怎么 访问 google 呢？ 请给一个官方指导。

**Comment by doKill** [comment]
我是政府官员，我就盯着你这个帖子怎么应对，我再针对你的应对来应对[手动狗头]

**Comment by SM-N920T** [comment]
楼主能提供我一个天朝能用来上外网的v2ray脚本吗？

**Comment by rufengsuixing** [comment]
神经网络识别流量效率太低，而且这是个现成的模子，我可以往任何流量上面套。水论文，没有应用条件。
即使应用了，如果1%的误识别率就是很大代价的话，你识别率99%也没用，毕竟对于1%那被误识别的流量来说，错误率是100%

**Comment by 690933449** [comment]
还只是个专利，没有任何实验数据证明的

**Comment by hangaj** [comment]
一直在用ss都没事

**Comment by Creky** [comment]
哎，用了多年的ss今天也转v2了，ss jp的在一个月前直接被封ip，遂上了个米国的，这个倒是没封ip了，但是用久了会封端口，经常换端口也不行。现在是端口封一会儿了又解封了，干脆上v2试试。要是v2还不稳定，那就只能自己写个了。

**Comment by lipeng1667** [comment]
> 哎，用了多年的ss今天也转v2了，ss jp的在一个月前直接被封ip，遂上了个米国的，这个倒是没封ip了，但是用久了会封端口，经常换端口也不行。现在是端口封一会儿了又解封了，干脆上v2试试。要是v2还不稳定，那就只能自己写个了。

v2 用ws+tls 稳定了1个月，今天晚上突然抽风，ping域名60%丢包。。。

**Comment by Creky** [comment]
> > 哎，用了多年的ss今天也转v2了，ss jp的在一个月前直接被封ip，遂上了个米国的，这个倒是没封ip了，但是用久了会封端口，经常换端口也不行。现在是端口封一会儿了又解封了，干脆上v2试试。要是v2还不稳定，那就只能自己写个了。
> 
> v2 用ws+tls 稳定了1个月，今天晚上突然抽风，ping域名60%丢包。。。

v2已被封，ip被墙，换了个服务器，操蛋，得好好研究一下参数配置了

**Comment by 1102569977** [comment]
封我没用，还不是封点搞破坏的，本人良民啊！

**Comment by Creky** [comment]
> > > 哎，用了多年的ss今天也转v2了，ss jp的在一个月前直接被封ip，遂上了个米国的，这个倒是没封ip了，但是用久了会封端口，经常换端口也不行。现在是端口封一会儿了又解封了，干脆上v2试试。要是v2还不稳定，那就只能自己写个了。
> > 
> > 
> > v2 用ws+tls 稳定了1个月，今天晚上突然抽风，ping域名60%丢包。。。
> 
> v2已被封，ip被墙，换了个服务器，操蛋，得好好研究一下参数配置了

原ip已经解封，但已经切换到ws+tls+cf了，这下封不封都无所谓了~~~ps：我只是用google查点技术性资料，我搞互联网开发的，百度那个垃圾经常get不到点上，没搞破坏，也不会去做坏事，国外反dsl洗不了我的nao！

**Comment by hadow** [comment]
> > > > 哎，用了多年的ss今天也转v2了，ss jp的在一个月前直接被封ip，遂上了个米国的，这个倒是没封ip了，但是用久了会封端口，经常换端口也不行。现在是端口封一会儿了又解封了，干脆上v2试试。要是v2还不稳定，那就只能自己写个了。
> > > 
> > > 
> > > v2 用ws+tls 稳定了1个月，今天晚上突然抽风，ping域名60%丢包。。。
> > 
> > 
> > v2已被封，ip被墙，换了个服务器，操蛋，得好好研究一下参数配置了
> 
> 原ip已经解封，但已经切换到ws+tls+cf了，这下封不封都无所谓了~~~ps：我只是用google查点技术性资料，我搞互联网开发的，百度那个垃圾经常get不到点上，没搞破坏，也不会去做坏事，国外反dsl洗不了我的nao！

大概可能是因爲你無腦吧，所以洗不了嘍

**Comment by Creky** [comment]
> > > > > 哎，用了多年的ss今天也转v2了，ss jp的在一个月前直接被封ip，遂上了个米国的，这个倒是没封ip了，但是用久了会封端口，经常换端口也不行。现在是端口封一会儿了又解封了，干脆上v2试试。要是v2还不稳定，那就只能自己写个了。
> > > > 
> > > > 
> > > > v2 用ws+tls 稳定了1个月，今天晚上突然抽风，ping域名60%丢包。。。
> > > 
> > > 
> > > v2已被封，ip被墙，换了个服务器，操蛋，得好好研究一下参数配置了
> > 
> > 
> > 原ip已经解封，但已经切换到ws+tls+cf了，这下封不封都无所谓了~~~ps：我只是用google查点技术性资料，我搞互联网开发的，百度那个垃圾经常get不到点上，没搞破坏，也不会去做坏事，国外反dsl洗不了我的nao！
> 
> 大概可能是因爲你無腦吧，所以洗不了嘍

看你的繁体字，是不是又是一个hk，tw的废青或是一个大陆的垃圾？你有点脑子还这么没点礼貌，当下人的感觉怎么样？

**Comment by WC12366** [comment]
> > > > > > 哎，用了多年的ss今天也转v2了，ss jp的在一个月前直接被封ip，遂上了个米国的，这个倒是没封ip了，但是用久了会封端口，经常换端口也不行。现在是端口封一会儿了又解封了，干脆上v2试试。要是v2还不稳定，那就只能自己写个了。
> > > > > 
> > > > > 
> > > > > v2 用ws+tls 稳定了1个月，今天晚上突然抽风，ping域名60%丢包。。。
> > > > 
> > > > 
> > > > v2已被封，ip被墙，换了个服务器，操蛋，得好好研究一下参数配置了
> > > 
> > > 
> > > 原ip已经解封，但已经切换到ws+tls+cf了，这下封不封都无所谓了~~~ps：我只是用google查点技术性资料，我搞互联网开发的，百度那个垃圾经常get不到点上，没搞破坏，也不会去做坏事，国外反dsl洗不了我的nao！
> > 
> > 
> > 大概可能是因爲你無腦吧，所以洗不了嘍
> 
> 看你的繁体字，是不是又是一个hk，tw的废青或是一个大陆的垃圾？你有点脑子还这么没点礼貌，当下人的感觉怎么样？

确实，这就是个无脑的废青

**Comment by zcq15** [comment]
> > > > > > 哎，用了多年的ss今天也转v2了，ss jp的在一个月前直接被封ip，遂上了个米国的，这个倒是没封ip了，但是用久了会封端口，经常换端口也不行。现在是端口封一会儿了又解封了，干脆上v2试试。要是v2还不稳定，那就只能自己写个了。
> > > > > 
> > > > > 
> > > > > v2 用ws+tls 稳定了1个月，今天晚上突然抽风，ping域名60%丢包。。。
> > > > 
> > > > 
> > > > v2已被封，ip被墙，换了个服务器，操蛋，得好好研究一下参数配置了
> > > 
> > > 
> > > 原ip已经解封，但已经切换到ws+tls+cf了，这下封不封都无所谓了~~~ps：我只是用google查点技术性资料，我搞互联网开发的，百度那个垃圾经常get不到点上，没搞破坏，也不会去做坏事，国外反dsl洗不了我的nao！
> > 
> > 
> > 大概可能是因爲你無腦吧，所以洗不了嘍
> 
> 看你的繁体字，是不是又是一个hk，tw的废青或是一个大陆的垃圾？你有点脑子还这么没点礼貌，当下人的感觉怎么样？

当下人?你想多了,美国人眼里hk和tw的废青连狗都不如,怎么能跟下人比?

**Comment by Starry-Sky-World** [comment]
> > > > > > > 哎，用了多年的ss今天也转v2了，ss jp的在一个月前直接被封ip，遂上了个米国的，这个倒是没封ip了，但是用久了会封端口，经常换端口也不行。现在是端口封一会儿了又解封了，干脆上v2试试。要是v2还不稳定，那就只能自己写个了。
> > > > > > 
> > > > > > 
> > > > > > v2 用ws+tls 稳定了1个月，今天晚上突然抽风，ping域名60%丢包。。。
> > > > > 
> > > > > 
> > > > > v2已被封，ip被墙，换了个服务器，操蛋，得好好研究一下参数配置了
> > > > 
> > > > 
> > > > 原ip已经解封，但已经切换到ws+tls+cf了，这下封不封都无所谓了~~~ps：我只是用google查点技术性资料，我搞互联网开发的，百度那个垃圾经常get不到点上，没搞破坏，也不会去做坏事，国外反dsl洗不了我的nao！
> > > 
> > > 
> > > 大概可能是因爲你無腦吧，所以洗不了嘍 大概可能是因为你无脑吧，所以洗不了伫
> > 
> > 
> > 看你的繁体字，是不是又是一个hk，tw的废青或是一个大陆的垃圾？你有点脑子还这么没点礼貌，当下人的感觉怎么样？
> 
> 当下人?你想多了,美国人眼里hk和tw的废青连狗都不如,怎么能跟下人比?

对啊对啊
