### ISSUE TITLE
V2RAY官方代码加入了tcp配置后报错，是否我语法错误？ 

### ISSUE THREAD

**Issue by SM-N920T** [233boy/v2ray#364]
官方命令安装v2ray后，用 vi /etc/v2ray/config.json 在Xshell 6中 加入了TCP配置后，然后启动v2ray报错，如何解决？（vultr的centos 8系统VPS）

[root@vultr ~]# cat /etc/v2ray/config.json
{
  "inbounds": [{
    "port": 35689,
    "listen": "0.0.0.0",
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "4b8f1e8f-6206-4336-83db-a304e1fc8d71",
          "level": 1,
          "alterId": 64
        }
      ]
    },
"streamSettings": {
    "network": "tcp",
    "security": "none",
    "tcpSettings": {
      "type": "none"
    }
  },
"tag": "",
  "sniffing": {
    "enabled": true,
    "destOverride": [
      "http",
      "tls"
    ]
  }
}### ],
  "outbounds": [{
    "protocol": "freedom",
    "settings": {}
  },{
    "protocol": "blackhole",
    "settings": {},
    "tag": "blocked"
  }],
  "routing": {
    "rules": [
      {
        "type": "field",
        "ip": ["geoip:private"],
        "outboundTag": "blocked"
      }
    ]
  }
}

请问我图中红色的] 是否不需要此括弧？报错如下：
[root@vultr ~]# systemctl start v2ray
[root@vultr ~]# systemctl status v2ray
● v2ray.service - V2ray deamon
   Loaded: loaded (/etc/systemd/system/v2ray.service; static; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2019-10-17 10:27:02 CST; 11s ago
  Process: 24810 ExecStart=/usr/bin/v2ray/v2ray (code=exited, status=23)
Main PID: 24810 (code=exited, status=23)

**Comment by SM-N920T** [comment]
> 官方命令安装v2ray后，用 vi /etc/v2ray/config.json 在Xshell 6中 加入了TCP配置后，然后启动v2ray报错，如何解决？（vultr的centos 8系统VPS）
> 
> [root@vultr ~]# cat /etc/v2ray/config.json
> {
> "inbounds": [{
> "port": 35689,
> "listen": "0.0.0.0",
> "protocol": "vmess",
> "settings": {
> "clients": [
> {
> "id": "4b8f1e8f-6206-4336-83db-a304e1fc8d71",
> "level": 1,
> "alterId": 64
> }
> ]
> },
> "streamSettings": {
> "network": "tcp",
> "security": "none",
> "tcpSettings": {
> "type": "none"
> }
> },
> "tag": "",
> "sniffing": {
> "enabled": true,
> "destOverride": [
> "http",
> "tls"
> ]
> }
> }### ],
> "outbounds": [{
> "protocol": "freedom",
> "settings": {}
> },{
> "protocol": "blackhole",
> "settings": {},
> "tag": "blocked"
> }],
> "routing": {
> "rules": [
> {
> "type": "field",
> "ip": ["geoip:private"],
> "outboundTag": "blocked"
> }
> ]
> }
> }
> 
> 请问我图中红色的] 是否不需要此括弧？报错如下：
> [root@vultr ~]# systemctl start v2ray
> [root@vultr ~]# systemctl status v2ray
> ● v2ray.service - V2ray deamon
> Loaded: loaded (/etc/systemd/system/v2ray.service; static; vendor preset: disabled)
> Active: failed (Result: exit-code) since Thu 2019-10-17 10:27:02 CST; 11s ago
> Process: 24810 ExecStart=/usr/bin/v2ray/v2ray (code=exited, status=23)
> Main PID: 24810 (code=exited, status=23)

**Comment by luozhongxiangsi** [comment]
我也遇到这个错误了，请问你解决了吗
