### ISSUE TITLE
IOS9系统下shadowrocket无法使用 V2Ray+nginx+ws+tls

### ISSUE THREAD

**Issue by FBLMG** [233boy/v2ray#368]
Centos7下使用宝塔面板 +V2Ray+ws+tls+Nginx，在IOS10下可以使用，电脑也是可以，但是在IOS9下使用shadowrocket无法进行谷歌

**Comment by FBLMG** [comment]
已自行解决！

**Comment by qiyuey** [comment]
自己可以 Close 一下

**Comment by vinsonma** [comment]
> 已自行解决！

请问如何解决的？用新脚本后 发现电脑都是可以 手机上Shadowrocket就无法链接

**Comment by vinsonma** [comment]
额外ID 填写0 就可以了，亲测可用
