### ISSUE TITLE
v2ray地址能否使用域名

### ISSUE THREAD

**Issue by michaelincn** [233boy/v2ray#37]
动态域名的NAT VPS，每天会变一次IP，供应商提供的公网访问地址就直接是域名，所以能不能设置成域名解析的方式，目前的脚本我尝试修改233blog_v2ray_config中的outbound／vnext／address为域名，但是似乎并没有生效

**Comment by 233boy** [comment]
@michaelincn 
直接在设置客户端配置的内容中将地址修改 服务商提供的域名就行
