### ISSUE TITLE
有幾個問題弄不清, 希望指教

### ISSUE THREAD

**Issue by mcdull** [233boy/v2ray#372]
1. 為何劇本默認不偽裝呢? 會影響到保密性嗎?
2. 如果用据本的v2ray NG設定, 是默認所有流量都走 VPS 嗎? 包括安卓推送?
3. CaddyFile TLS 內有一個gmail, 請問是什麼來? 是誰的?
4. 現在重開機caddy都不會運行, 要在ssh加上
nohup  /usr/local/bin/caddy -log stdout -agree=true -conf=/etc/caddy/Caddyfile -root=/var/tmp &
才可以, 請問原因.

謝謝解答

**Comment by 233boy** [comment]
@mcdull 
1，因为默认不开启更省事，开启是否由你自己定，不影响保密

2，NG 有一个规则选项的，比如说，绕过局域网及大陆地址，或，全局，你开全局才是全部流量都走代理

3，那个是随机生成的，是因为避免某些问题，将来这个邮箱很有可能移除掉，不会支持手动输入

4，默认已经是开机启动的，但是你可以执行此命令 `systemctl disable caddy;  systemctl enable caddy` ，再观察是否能开机启动

**Comment by linhongjun** [comment]
> 1. 為何劇本默認不偽裝呢? 會影響到保密性嗎?
伪装也会产生其他问题  所以默认TCP是最好的选择
> 2. 如果用据本的v2ray NG設定, 是默認所有流量都走 VPS 嗎? 包括安卓推送?
客户端里有选择 可以绕过指定APP或者代理指定APP 或者绕过大陆IP 但是感觉列表不完整
最好的就是代理指定APP

**Comment by ntgeralt** [comment]
@mcdull 伪装永远比真的差，看ssr的tls伪装现在成开会秒封的特征就知道
gmail是给caddy在tls到期的发送提示邮件地址
