### ISSUE TITLE
请问可以添加多用户管理脚本嘛

### ISSUE THREAD

**Issue by dsjasonh** [233boy/v2ray#374]
自己用，然后身边朋友也都在靠我翻墙，但是得限制每个人的速度。之前用的SSR的多用户脚本，很方便。但最近想转V2RAY，一直在找多用户的一键脚本。。。（我不会代码。。。都是一路粘贴复制操作。。。这里要感谢所有做一键脚本的大佬。。。）

**Comment by moaasd** [comment]
换个思路！ 搭建一个vpn 中转一下

**Comment by linhongjun** [comment]
> 自己用，然后身边朋友也都在靠我翻墙，但是得限制每个人的速度。之前用的SSR的多用户脚本，很方便。但最近想转V2RAY，一直在找多用户的一键脚本。。。（我不会代码。。。都是一路粘贴复制操作。。。这里要感谢所有做一键脚本的大佬。。。）

有v2 ui可以用 多用户 面板控制

**Comment by 1102569977** [comment]
自用一时爽，一直自用一直爽！
