### ISSUE TITLE
请保持网络中立，不要默认屏蔽大纪元等网站

### ISSUE THREAD

**Issue by haha-0000** [233boy/v2ray#375]

**Comment by wysnxzm** [comment]
轮子给👴爪巴

**Comment by linhongjun** [comment]
请不要把ZZ带入这里来  你有完全自由的选择权

**Comment by haha-0000** [comment]
没有啊，就是提个建议，不要想太多了，屏蔽规则应该让用户自己去加会更好

**Comment by haha-0000** [comment]
> 轮子给👴爪巴

别他妈乱扣帽子

**Comment by linhongjun** [comment]
> 没有啊，就是提个建议，不要想太多了，屏蔽规则应该让用户自己去加会更好

我个人观点  应该屏蔽 而且支持屏蔽 包括轮子 P2P 迅雷之内的所有  觉得不适合可以用其他脚本

**Comment by haha-0000** [comment]
> > 没有啊，就是提个建议，不要想太多了，屏蔽规则应该让用户自己去加会更好
> 
> 我个人观点 应该屏蔽 而且支持屏蔽 包括轮子 P2P 迅雷之内的所有 觉得不适合可以用其他脚本

让用户选择更好嘛，毕竟有些用户需要，虽然我已经卸载了一键脚本

**Comment by linhongjun** [comment]
> > > 没有啊，就是提个建议，不要想太多了，屏蔽规则应该让用户自己去加会更好
> > 
> > 
> > 我个人观点 应该屏蔽 而且支持屏蔽 包括轮子 P2P 迅雷之内的所有 觉得不适合可以用其他脚本
> 
> 让用户选择更好嘛，毕竟有些用户需要，虽然我已经卸载了一键脚本

免费脚本 选择权在用户

**Comment by haha-0000** [comment]
> > > > 没有啊，就是提个建议，不要想太多了，屏蔽规则应该让用户自己去加会更好
> > > 
> > > 
> > > 我个人观点 应该屏蔽 而且支持屏蔽 包括轮子 P2P 迅雷之内的所有 觉得不适合可以用其他脚本
> > 
> > 
> > 让用户选择更好嘛，毕竟有些用户需要，虽然我已经卸载了一键脚本
> 
> 免费脚本 选择权在用户

那是那是，所以我卸载了，但我说的是脚本本身的问题，没必要去做这种多余的事情，而且还影响体验

**Comment by linhongjun** [comment]
> > > > > 没有啊，就是提个建议，不要想太多了，屏蔽规则应该让用户自己去加会更好
> > > > 
> > > > 
> > > > 我个人观点 应该屏蔽 而且支持屏蔽 包括轮子 P2P 迅雷之内的所有 觉得不适合可以用其他脚本
> > > 
> > > 
> > > 让用户选择更好嘛，毕竟有些用户需要，虽然我已经卸载了一键脚本
> > 
> > 
> > 免费脚本 选择权在用户
> 
> 那是那是，所以我卸载了，但我说的是脚本本身的问题，没必要去做这种多余的事情，而且还影响体验

没感觉影响什么  那类网站反正我不看 假消息也不少 倾向性太严重 
看点BBC啥的 到可以

**Comment by fz0325** [comment]
傻批给爷爬，理中客你m呢

**Comment by saygoodbyebye** [comment]
自己修改一下就好了

**Comment by 1608637229** [comment]
同觉得没必要屏蔽。。虽然不上哪些网站。本身使用这软件去是为了反屏蔽。

**Comment by nxtreaming** [comment]
没有权力屏蔽其他网站，除非作者自己就是轮子。

**Comment by recolic** [comment]
如果你在大规模部署中懒得一个一个改的话，有一个其他人做的fork可以解决这个问题的： https://github.com/rootmelo92118/v2ray-edit-from-233boy
希望能帮助到大家
