### ISSUE TITLE
v3.20 版本配置显示和导出问题

### ISSUE THREAD

**Issue by wysnxzm** [233boy/v2ray#376]
配置好路径混淆和伪装网站会出错,伪装网站变成原域名,路径混淆恒定为/

**Comment by 233boy** [comment]
@wysnxzm 
你是从远古版本更新过来的嘛？ 😂 或者你能复现一下过程么？？

**Comment by wysnxzm** [comment]
> @wysnxzm
> 你是从远古版本更新过来的嘛？😂 或者你能复现一下过程过程么？？

不是,远古版本我一直跟着更新呐
就是这次升级后我发现查看配置里面的伪装路径变成/了,然后我手动设置了一下再查看还是/
不太正常的操作只有域名和ip对不上,因为不影响使用和更新ip需要切换配置我就没弄
