### ISSUE TITLE
CloudFare的DNS已经把Proxy status点成灰色了，为什么还是解析不到自己的IP地址？

### ISSUE THREAD

**Issue by Huaweidev** [233boy/v2ray#377]
CloudFare的DNS已经把Proxy status点成灰色了，为什么还是解析不到自己的IP地址？还是显示这样： 
 ```备注...如果你的域名是使用 Cloudflare 解析的话..在 Status 那里点一下那图标..让它变灰```？
* 在本机直接Ping域名出来的IP地址是正确的VPS的IP地址；
* 在VPS直接Ping域名出来的IP地址是正确的VPS的IP地址；
![PIC__11](https://user-images.githubusercontent.com/10258421/67836302-369bfe80-fb27-11e9-8895-9aaf9e1da517.jpg)

**Comment by limbo-envoy** [comment]
我也遇到了，不过我用的是阿里的dns解析，现在情况和你一样

**Comment by yinyh** [comment]
我也遇到了这个问题

**Comment by lumo0095** [comment]
同遇到这个问题，而且每次提示的解析到的IP还都不一样

**Comment by lumo0095** [comment]
解决了，卸载重装就可以了

**Comment by Creky** [comment]
> 解决了，卸载重装就可以了

+1

**Comment by chanv2ray19** [comment]
请问怎么卸载？

**Comment by premk267** [comment]
> 请问怎么卸载？

卸载并重新安装curl

**Comment by drinmo** [comment]
遇到相同问题。
