### ISSUE TITLE
求助，下载了v2rayN-Core一直提示错误，无法运行

### ISSUE THREAD

**Issue by vanleechaos** [233boy/v2ray#378]
之前一直用SSR，不能用了之后，下载v2rayN-Core一直提示错误，无法运行
<img src = 'https://ftp.bmp.ovh/imgs/2019/10/b1bf223994646a90.png' />
让安装.net Framework4.0.30319,
我在微软官网下载了
<img src = 'http://tva1.sinaimg.cn/large/007X8olVly1g8gd3c4at3j30bn0dc3ym.jpg' />
<img src = 'https://ftp.bmp.ovh/imgs/2019/10/a87d059fcdf2a460.png' />
安装完毕后
<img src = 'https://ftp.bmp.ovh/imgs/2019/10/4af242363339e150.png' />
运行，还是不能运行，出现以下提示
<img src = 'http://tva1.sinaimg.cn/large/007X8olVly1g8gd18h6blj30dz06wjrg.jpg' />

求指教！

**Comment by 233boy** [comment]
@vanleechaos 
不是很清楚这个问题了，感觉是运行库的原因。。

你 [下载](https://www.microsoft.com/en-US/Download/confirmation.aspx?id=17718) 这个安装看看
