### ISSUE TITLE
一键安装后能上google，但无法用邮件客户端收取gmail

### ISSUE THREAD

**Issue by tigeryull** [233boy/v2ray#379]
请问一下按照指引安装了v2ray后，我选的是tcp，网页访问都正常。就是不知道为何foxmail等邮件客户端无法连上gmail，网络设置已经是选择按照本地的设置，求大神解答，感谢感谢！

**Comment by linhongjun** [comment]
你直接在信箱客户端里设置代理就行了
gmail信箱可以用hotmail信箱远程获取邮件
QQ信箱以前可以 现在不太好说

**Comment by tigeryull** [comment]
> 你直接在信箱客户端里设置代理就行了
> gmail信箱可以用hotmail信箱远程获取邮件
> QQ信箱以前可以 现在不太好说

Foxmail里面设置的是使用IE的代理，以前用SS收发没问题，现在v2ray就不行了
