### ISSUE TITLE
阿里云轻量云服务器安装后，测速有延迟，但是连接不上，换了多个协议都是一样

### ISSUE THREAD

**Issue by 1716700602** [233boy/v2ray#380]
阿里云轻量云服务器安装后，测速有延迟，但是连接不上，换了多个协议都是一样，安全组已全放

**Comment by lee112358** [comment]
你看下是不是阿里云那里端口没有开放

**Comment by 1716700602** [comment]
端口全部开放，现在又可以了，但是换成华为云的不行了，也是端口全开



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Lee"; 
发送时间: 2019年11月21日(星期四) 中午1:12
收件人: "233boy/v2ray";
抄送: "1716700602"<1716700602@qq.com>;"Author";
主题: Re: [233boy/v2ray] 阿里云轻量云服务器安装后，测速有延迟，但是连接不上，换了多个协议都是一样 (#380)




你看下是不是阿里云那里端口没有开放
 
&mdash;

**Comment by 1716700602** [comment]
多个服务器安装都是不行
