### ISSUE TITLE
v2ray服务端支持CDN后添加shadowsocks协议支持，ss客户端链接还走CDN吗？

### ISSUE THREAD

**Issue by Huaweidev** [233boy/v2ray#381]
v2ray服务端支持ws+tls+candy+CDN后，服务端添加shadowsocks协议支持，使用v2rayN或者shadowsocks客户端添加ss协议服务器信息进行连接，请问：  
* 连接还走CDN吗？ss是不是就是直连了，很容易检测到并被封？

**Comment by 233boy** [comment]
@colemanlee SS 直连呀。。。被封这种情况很玄学，担心就 V2 走 CDN
