### ISSUE TITLE
你好 该脚本是默认安装了BBR加速吗

### ISSUE THREAD

**Issue by Maxxiecook** [233boy/v2ray#387]
如题

**Comment by jzoy** [comment]
是的哦，如果你想验证一下，可以ssh到服务器后，输入v2ray，然后选其他配置还是什么来着，可以手动安装bbr和锐速，我每次都会提醒我已经安装好了

**Comment by ntgeralt** [comment]
一些系统，如debian9和centos8等，自带bbr。没开启的233脚本执行完会开启

敲入 
sysctl net.ipv4.tcp_available_congestion_control
和
lsmod | grep bbr

有bbr代表开启

**Comment by hypnossz86** [comment]
> 一些系统，如debian9和centos8等，自带bbr。没开启的233脚本执行完会开启
> 
> 敲入 sysctl net.ipv4.tcp_available_congestion_control 和 lsmod | grep bbr
> 
> 有bbr代表开启

请问默认开启的话有办法关闭吗？
