### ISSUE TITLE
caddy无法启动

### ISSUE THREAD

**Issue by pkpkgtr1** [233boy/v2ray#390]
最近发现新版caddy服务无法启动错误
● caddy.service - Caddy HTTP/2 web server
   Loaded: loaded (/usr/lib/systemd/system/caddy.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2019-11-07 16:46:27 CST; 283ms ago
     Docs: https://caddyserver.com/docs
  Process: 12791 ExecStart=/usr/local/bin/caddy -log stdout -log-timestamps=false -agree=true -conf=/etc/caddy/Caddyfile -root=/var/tmp (code=exited, status=2)
 Main PID: 12791 (code=exited, status=2)

Nov 07 16:46:27 hostc0f39bcf62 systemd[1]: caddy.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Nov 07 16:46:27 hostc0f39bcf62 systemd[1]: Unit caddy.service entered failed state.
Nov 07 16:46:27 hostc0f39bcf62 systemd[1]: caddy.service failed.

替换老caddy.service中的内容就能正常启动.

**Comment by chanv2ray19** [comment]
替换老caddy.service中的内容就能正常启动
请问这个什么意思大哥

**Comment by pkpkgtr1** [comment]
> 替换老caddy.service中的内容可以正常启动请问
> 这个什么意思大哥

就是caddy无法启动是caddy.servic文件配置错误造成的。/usr/lib/systemd/system/caddy.service替换附件  systemctl restart caddy就能正常启动caddy
[caddy.zip](https://github.com/233boy/v2ray/files/3822771/caddy.zip)
