### ISSUE TITLE
脚本跑完后caddy无法正常启动

### ISSUE THREAD

**Issue by JDalready** [233boy/v2ray#391]

**Comment by pkpkgtr1** [comment]
解压后的附件内容替换/usr/lib/systemd/system/caddy.service  执行systemctl restart caddy重启服务
[caddy.zip](https://github.com/233boy/v2ray/files/3822792/caddy.zip)

**Comment by JDalready** [comment]
> 解压后的附件内容替换/usr/lib/systemd/system/caddy.service 执行systemctl restart caddy重启服务
> [caddy.zip](https://github.com/233boy/v2ray/files/3822792/caddy.zip)

感谢
