### ISSUE TITLE
2019/11/8 最新测试ws+tls+cdn失败

### ISSUE THREAD

**Issue by xhqpp** [233boy/v2ray#393]
caddy报错

**Comment by Tyro-Fang** [comment]
同样，跑完脚本后连接不上

**Comment by Mr-dbo** [comment]
+1

**Comment by Mr-dbo** [comment]
@233boy 求修复

**Comment by chenxuan5858** [comment]
+1

**Comment by zhaochunqi** [comment]
临时 fix ,  根据 https://github.com/233boy/v2ray/issues/390 给出的方案，编辑 /usr/lib/systemd/system/caddy.service ，将其中的 `-log-timestamps=false` 删掉, 这个参数在 caddy 中已经不存在了，所以导致了问题。

然后 `systemctl daemon-reload`, `systemctl start caddy` 即可

**Comment by Tyro-Fang** [comment]
> 临时 fix , 根据 #390 给出的方案，编辑 /usr/lib/systemd/system/caddy.service ，将其中的 `-log-timestamps=false` 删掉, 这个参数在 caddy 中已经不存在了，所以导致了问题。
> 
> 然后 `systemctl daemon-reload`, `systemctl start caddy` 即可

我是跑完脚本，status显示caddy未运行，然后去/usr/lib/systemd/system文件夹下也没有caddy.service文件，生成的vmess也无法连接成功

**Comment by 233boy** [comment]
@xhqpp @Mr-dbo @Tyro-Fang @chenxuan5858 
已修复，，请使用 `v2ray reinstall` 重装解决问题。。。

**Comment by 233boy** [comment]
> 临时 fix , 根据 #390 给出的方案，编辑 /usr/lib/systemd/system/caddy.service ，将其中的 `-log-timestamps=false` 删掉, 这个参数在 caddy 中已经不存在了，所以导致了问题。
> 
> 然后 `systemctl daemon-reload`, `systemctl start caddy` 即可

就是因为这个参数 😂

**Comment by BerQin** [comment]
> > 临时 fix , 根据 #390 给出的方案，编辑 /usr/lib/systemd/system/caddy.service ，将其中的 `-log-timestamps=false` 删掉, 这个参数在 caddy 中已经不存在了，所以导致了问题。
> > 然后 `systemctl daemon-reload`, `systemctl start caddy` 即可
> 
> 就是因为这个参数 😂

为什我的服务器还是不行，还有这个问题？
