### ISSUE TITLE
一键安装脚本安装后caddy一直无法启动

### ISSUE THREAD

**Issue by Demon1630** [233boy/v2ray#398]
用网站提供的一键安装脚本安装，按照安装流程走，自动配置的TLS，安装完后caddy一直无法启动，重启v2ray的时候显示.

Failed to restart caddy.service: Unit caddy.service not found.

 V2Ray 重启完成 

在centos和Debian 9系统上都是这样，不知道为什么

**Comment by Splanzar** [comment]
请看评论https://github.com/233boy/v2ray/commit/d568ae0299648ff7f142664c679a55505ec209c1

**Comment by vien-meng** [comment]
卸载Nginx后手动重启就好了
sudo systemctl start caddy.service
systemctl status caddy
最好设置开机启动
sudo systemctl enable caddy.service
