### ISSUE TITLE
PC客户端v2rayN v2.6 无法识别一键脚本http2模式制作的二维码

### ISSUE THREAD

**Issue by ntgeralt** [233boy/v2ray#40]
你好，我用你一键脚本选择http2模式，完成时我按Y，他做出的二维码，v2rayN v2.6 提示未找到有效二维码，你试试是否有这问题。

ps一个小建议：运行一键脚本代码时有个提示v2ray的运行状态

**Comment by 233boy** [comment]
@ntgeralt 
使用 PC 端的 V2RayN 可能是无法识别二维码的，是软件问题，可能是二维码太大了的原因，然后它识别不了，不要问我为什么，我也不知道 😂 
为什么把二维码做大？因为方便 手机扫描啊...
使用手机扫描是没有任何问题的
PC 端的 V2RayN 建议使用 `v2ray url` 复制链接之后 ，在 V2RayN 导入链接，这样挺方便的
脚本有运行状态，输入 `v2ray status` 即可

**Comment by ntgeralt** [comment]
建议：建好节点后显示vmess链接，我们直接复制,少去v2ray url一步
