### ISSUE TITLE
使用Cloudflare 中转V2Ray 流量不会导致Caddy 无法更新证书吧？

### ISSUE THREAD

**Issue by suzhi82** [233boy/v2ray#405]
使用Cloudflare 中转V2Ray 流量不会导致Caddy 无法更新证书吧？

**Comment by semglassie** [comment]
用文件验证域名如果套了CDN会造成无法更新证书，必须改成用dns来验证域名

**Comment by suzhi82** [comment]
> 用文件验证域名如果套了CDN会造成无法更新证书，必须改成用dns来验证域名

请问怎么设置呢？我现在是WS+TLS+CDN，参照下面链接来弄的。
https://github.com/233boy/v2ray/wiki/%E4%BD%BF%E7%94%A8Cloudflare%E4%B8%AD%E8%BD%ACV2Ray%E6%B5%81%E9%87%8F

**Comment by DoraemonAndRat** [comment]
使用cloudflare中转是无法验证证书的所属域名是你自己的机器。
但是cloudflare也提供了他自己的证书，用了他的cdn就不需要自己申请证书了
