### ISSUE TITLE
突发状况,请教下

### ISSUE THREAD

**Issue by Tatamethues** [233boy/v2ray#408]
不知道为啥突然ss连接无法使用了.vmess可以..电脑用的clash,ping的时候ss都是timeout,vmess可以用.

**Comment by XIANGCHAO1990** [comment]
> 不知道为啥突然ss连接无法使用了.vmess可以..电脑用的clash,ping的时候ss都是timeout,vmess可以用.

同样的问题

**Comment by Tatamethues** [comment]
> > 不知道为啥突然ss连接无法使用了.vmess可以..电脑用的clash,ping的时候ss都是timeout,vmess可以用.
> 
> 同样的问题

改端口
