### ISSUE TITLE
caddy站不起来，求教

### ISSUE THREAD

**Issue by gaoconggit** [233boy/v2ray#410]
[root@vultr ~]# systemctl status caddy -l 
● caddy.service - Caddy HTTP/2 web server
   Loaded: loaded (/usr/lib/systemd/system/caddy.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2019-11-21 16:42:19 CST; 20s ago
     Docs: https://caddyserver.com/docs
  Process: 16292 ExecStart=/usr/local/bin/caddy -log stdout -agree=true -conf=/etc/caddy/Caddyfile -root=/var/tmp (code=exited, status=1/FAILURE)
 Main PID: 16292 (code=exited, status=1/FAILURE)

Nov 21 16:42:16 vultr.guest caddy[16292]: 2019/11/21 16:42:16 [INFO] [demo.soeasytunnel.com] acme: Obtaining bundled SAN certificate
Nov 21 16:42:16 vultr.guest caddy[16292]: 2019/11/21 16:42:16 [ERROR][demo.soeasytunnel.com] failed to obtain certificate: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/, url: (attempt 1/3; challenge=tls-alpn-01)
Nov 21 16:42:17 vultr.guest caddy[16292]: 2019/11/21 16:42:17 [INFO] [demo.soeasytunnel.com] acme: Obtaining bundled SAN certificate
Nov 21 16:42:17 vultr.guest caddy[16292]: 2019/11/21 16:42:17 [ERROR][demo.soeasytunnel.com] failed to obtain certificate: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/, url: (attempt 2/3; challenge=tls-alpn-01)
Nov 21 16:42:18 vultr.guest caddy[16292]: 2019/11/21 16:42:18 [INFO] [demo.soeasytunnel.com] acme: Obtaining bundled SAN certificate
Nov 21 16:42:18 vultr.guest caddy[16292]: 2019/11/21 16:42:18 [ERROR][demo.soeasytunnel.com] failed to obtain certificate: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/, url: (attempt 3/3; challenge=tls-alpn-01)
Nov 21 16:42:19 vultr.guest caddy[16292]: 2019/11/21 16:42:19 failed to obtain certificate: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/, url:
Nov 21 16:42:19 vultr.guest systemd[1]: caddy.service: main process exited, code=exited, status=1/FAILURE
Nov 21 16:42:19 vultr.guest systemd[1]: Unit caddy.service entered failed state.
Nov 21 16:42:19 vultr.guest systemd[1]: caddy.service failed.

**Comment by gaoconggit** [comment]
centos 7 ，参考已有的 issues了。依然站不起来哦

**Comment by boatmac** [comment]
> centos 7 ，参考已有的 issues了。依然站不起来哦

可以参考：https://caddyserver.com/v1/docs/automatic-https#dns-challenge，尝试使用 DNS Challenge 获取证书。

**Comment by gaoconggit** [comment]
多谢指导，后来用 nginx解决的问题

**Comment by jackrong** [comment]
> 多谢指导，后来用 nginx解决的问题

你好，我也遇到同样的问题。大佬分享下解决方法吧。多谢多谢。
