### ISSUE TITLE
websocket+tls访问个别网站出现页面加载失败，页面提示Reference #18.ce7a4217.1574439975.7fe3759

### ISSUE THREAD

**Issue by pplive00** [233boy/v2ray#412]
使用233一键脚本部署websocket+tls，访问大多数网站如google都正常，但就是不能访问日本乐天https://www.rakuten.co.jp/ ，页面空白且有提示Reference #18.ce7a4217.1574439975.7fe3759，后面字符串是随机的。查看服务器端errorlog，只有这个错误 2019/11/23 00:06:54 [Warning] v2ray.com/core/transport/internet/websocket: failed to serve http for WebSocket > accept tcp [::]:21000: use of closed network connection；实在摸不着头脑，不知道哪里有问题

**Comment by mqliutie** [comment]
兄弟 你是手机还是pc上啊?

**Comment by Kinfar** [comment]
我也遇到这样的问题，请问你解决了吗
