### ISSUE TITLE
WebSocket + TLS开启之后提示不能修改v2ray的端口，想改端口咋办

### ISSUE THREAD

**Issue by qthongjian** [233boy/v2ray#415]
WebSocket + TLS开启之后提示不能修改v2ray的端口，想改端口咋办
另外还有个问题，使用了WebSocket + TLS，油管速度之前不开能跑8W，开了之后只有四万不到点现在，请问怎么解决的？

**Comment by mqliutie** [comment]
兄弟... 你能跑就不错了,  我开了 ws+tls 后 google都上不了0.0

**Comment by ChengEast** [comment]
要改协议，改完协议才能改端口，你可以先改成别的协议，再改回来，然后再去改端口就可以了
