### ISSUE TITLE
关于caddy未运行

### ISSUE THREAD

**Issue by jmsht777** [233boy/v2ray#418]
我碰到的问题是多次安装一键脚本后碰到的。
分析是因为证书多次颁发给同一个域名
我的解决方法很傻，重新买了一个域名，仍然使用这个脚本就可以运行caddy了。（旧域名重复尝试多次不可以）。
是不是可以在脚本中加入重复使用已颁发的证书或是清除证书（如果可以）的逻辑，这样是否可以解决同一个域名多次运行安装类似功能脚本时caddy和nginx未运行或ssl证书不成功的情况？
仅供参考

**Comment by jmsht777** [comment]
不知道是因为没找到和合适的方法，还是因为我太笨了。找了一些单独安装caddy（nginx）的方法，尝试后caddy安装成功，但是仍然不能成功FQ，不知道是不是仍然是因为证书的原因。

**Comment by 233boy** [comment]
> 我碰到的问题是多次安装一键脚本后碰到的。
> 分析是因为证书多次颁发给同一个域名
> 我的解决方法很傻，重新买了一个域名，仍然使用这个脚本就可以运行caddy了。（旧域名重复尝试多次不可以）。
> 是不是可以在脚本中加入重复使用已颁发的证书或是清除证书（如果可以）的逻辑，这样是否可以解决同一个域名多次运行安装类似功能脚本时caddy和nginx未运行或ssl证书不成功的情况？
> 仅供参考

域名申请证书有限，你那个旧域名限制等一周再申请就行了

**Comment by jmsht777** [comment]
> > 我碰到的问题是多次安装一键脚本后碰到的。
> > 分析是因为证书多次颁发给同一个域名
> > 我的解决方法很傻，重新买了一个域名，仍然使用这个脚本就可以运行caddy了。（旧域名重复尝试多次不可以）。
> > 是不是可以在脚本中加入重复使用已颁发的证书或是清除证书（如果可以）的逻辑，这样是否可以解决同一个域名多次运行安装类似功能脚本时caddy和nginx未运行或ssl证书不成功的情况？
> > 仅供参考
> 
> 域名申请证书有限，你那个旧域名限制等一周再申请就行了

这样啊 那后面我再试一下
