### ISSUE TITLE
移动的4G用不了

### ISSUE THREAD

**Issue by gefate** [233boy/v2ray#424]
移动的4G用不了，但是移动的宽带可以用，有人遇到类似的问题吗？

**Comment by xc1988** [comment]
我遇到了 有时候重启手机可以用。
大部分时候不行

**Comment by hzeddielau** [comment]
一样问题，电信4G正常。

**Comment by blackforest1840** [comment]
同样移动4G，延迟260+使用的是gcp tw，但在电信网络环境下延迟50ms左右可正常使用

**Comment by Simmy2580** [comment]
> 同样移动4G，延迟260+使用的是gcp tw，但在电信网络环境下延迟50ms左右可正常使用

mtr看下路由，是不是绕路了

**Comment by Leefm666** [comment]
> > 同样移动4G，延迟260+使用的是gcp tw，但在电信网络环境下延迟50ms左右可正常使用
> 
> mtr看下路由，是不是绕路了

怎么看是不是绕路了

**Comment by gefate** [comment]
最后我把kcp改成ws就可以了，有时候不行就开关一下手机的飞行模式就好了。可以给有类似问题的人作为参考。
