### ISSUE TITLE
怎么修改系统DNS? 或者某域名指定用DNS ？

### ISSUE THREAD

**Issue by kenchow-cd** [233boy/v2ray#425]
目前修改系统dns，都自动被重置了。貌似是运营商干的，能不能在V2ray配置里面修改？

**Comment by GasaiKota** [comment]
"dns": {
    "servers": [
      {
        "address": "x.x.x.x",
        "domains": [
          "domain:netflix.com",
          "domain:netflix.net",
          "domain:nflximg.net",
          "domain:nflxvideo.net",
          "domain:nflxso.net",
          "domain:nflxext.com",
          "domain:gamer2-cds.cdn.hinet.net",
          "domain:gamer-cds.cdn.hinet.net",
          "domain:gamer.com.tw",
          "domain:ani.gamer.com.tw",
          "domain:i2.bahamut.com.tw",
          "domain:app-measurement.com",
          "domain:api.gamer.com.tw"
        ],
        "port": 53
      },
      {
        "address": "119.29.29.29",
        "port": 53,
        "domains": ["geosite:cn"]
      },
      "1.1.1.1",
      "1.0.0.1",
      "8.8.8.8",
      "8.8.4.4",
      "localhost"
    ]
  }

**Comment by kenchow-cd** [comment]
非常感谢回复，之前也是这样修改的，但是没有生效。
"dns": {
                "server": [
           { 
                "address": "x.x.x.x",
                "port": 53,
                "domains": [
                    "domain:netflix.com",
                    "domain:netflix.net",
                    "domain:nflximg.net",
                    "domain:nflxvideo.net",
                    "domain:nflxso.net",
                    "domain:nflxext.com"
                ]
            },
                "1.1.1.1",
                        "1.0.0.1",
                        "8.8.8.8",
                        "8.8.4.4",
                        "localhost"
                ]
        },

不知道为何？

**Comment by kenchow-cd** [comment]
我直接修改本地dns,  /etc/resolv.conf  可以生效！

另外，咨询下，如果要配置生效，我修改了/etc/v2ray/233boy/v2ray/config/client/kcp.json 文件，这样使用一键配置也可以了，不知道对不对？

**Comment by GasaiKota** [comment]
> 非常感谢回复，之前也是这样修改的，但是没有生效。
> "dns": {
> "server": [
> {
> "address": "x.x.x.x",
> "port": 53,
> "domains": [
> "domain:netflix.com",
> "domain:netflix.net",
> "domain:nflximg.net",
> "domain:nflxvideo.net",
> "domain:nflxso.net",
> "domain:nflxext.com"
> ]
> },
> "1.1.1.1",
> "1.0.0.1",
> "8.8.8.8",
> "8.8.4.4",
> "localhost"
> ]
> },
> 
> 不知道为何？

请将server修改为servers

**Comment by kenchow-cd** [comment]
我修改了servers，还是不行！  必须修改系统DNS。

**Comment by GasaiKota** [comment]
> 我修改了servers，还是不行！ 必须修改系统DNS。

你修改的是哪个配置文件？

**Comment by kenchow-cd** [comment]
/etc/v2ray/config.json

**Comment by GasaiKota** [comment]
> /etc/v2ray/config.json

那修改完后是否重启v2ray

**Comment by kenchow-cd** [comment]
我把系统dns切换到8.8.8.8，v2ray restart   执行完，就不行了！  再把系统dns改到x.x.x.x，奈非就好了。

**Comment by GasaiKota** [comment]
将"outbounds"中的 {
                        "protocol": "freedom",
                        "settings": {}
                }
修改为{
      "protocol": "freedom",
      "settings": {
      	"domainStrategy": "UseIP"
      }
    }

**Comment by kenchow-cd** [comment]
搞定了，非常感谢！！

**Comment by oldzhg** [comment]
成功解锁，开始改错了配置文件，原来是config.json， 233blog_v2ray_config.json这个可能是开始的默认吧
