### ISSUE TITLE
怎么今天pc客户端突然用不了了，手机上还能正常使用

### ISSUE THREAD

**Issue by Paokemon** [233boy/v2ray#434]
2019/12/31 19:45:55 tcp:127.0.0.1:50542 accepted tcp:mtalk.google.com:443 [proxy] 
2019/12/31 19:45:57 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://www.paopaosong.cf/):  > dial tcp: lookup www.paopaosong.cf: getaddrinfow: This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server.] > v2ray.com/core/common/retry: all retry attempts failed

提示这些，我现在服务器是正常的，手机上都能连，网址也ping的通，电脑上试了别人的服务器也能连，就是在电脑上用自己的服务器连不上，我什么都没干，昨天还好好的，哪里可以出问题呢？

**Comment by BunnyBunny661** [comment]
测试了很多次，还重装了，朋友的电脑一样能连，现在问题锁定在是我的电脑连不上我的服务器，跟电信网络，v2客户端，甚至服务器都没关系。。。。完全就是我电脑内部问题，可是就一晚上我什么都没做。。。晚上降温冻坏了？？

**Comment by 233boy** [comment]
@BunnyBunny661 
是晚上降温冻坏了，重启一下电脑就好

**Comment by hackerempire** [comment]
我也碰到同样问题，手机端shadowrocket可以用，电脑端v2rayn 连不上

**Comment by zhz1237ok** [comment]
作为对比，作为一个路人，我用着很好，你ping下你的服务器试试？

**Comment by BunnyBunny661** [comment]
> 我也碰到同样问题，手机端shadowrocket没问题，电脑端v2rayn经常断连

我今天都连不上了

**Comment by BunnyBunny661** [comment]
> 作为对比，作为一个路人，我用着很好，你ping下你的服务器试试？
> 
> 上面的错误提示是你家电脑收不到服务器的回应

我服务器没问题的，后面突然又能连了，然而今天连手机端都连不上了，今天服务器ping过，也是没问题

**Comment by Leeray-Lau** [comment]
> 我也碰到同样问题，手机端shadowrocket没问题，电脑端v2rayn 经常断连

@hackerempire 一样的问题，折腾了几天了，解决不了……
