### ISSUE TITLE
Centos7下脚本生成配置连接失败

### ISSUE THREAD

**Issue by zz1985summer** [233boy/v2ray#44]
Centos7用脚本安装完v2ray，但是使用v2ray link或者v2ray qr生成配置信息时总是提示失败，重新安装v2ray一样的情况

**Comment by aduhappy** [comment]
https://t.me/blog2333/64



无法生成链接的，不用瞎折腾了，那是网站的证书过期 了，等修复吧。如果是想要 生成配置的话，可以使用 v2ray url ，如果是想要下载配置文件的话，可以输入 v2ray 然后选择下载 V2Ray 配置，然后选择直接下载配置就行，需要 Xshell

来自233blog公告板
