### ISSUE TITLE
针对ID的识别情况非常严重

### ISSUE THREAD

**Issue by yunzhitan** [233boy/v2ray#440]
我目前一个ID用不了2天就会被识别到，换一个新ID就能继续用了，不知道各位的情况如何

**Comment by evolutionjay** [comment]
搬瓦工服务器已经被墙

**Comment by FlyingStarlight** [comment]
用同一个id 2个月了
没感觉
ws+tls，没伪站...CF和直连都用

**Comment by evolutionjay** [comment]
> 用同一个id 2个月了
> 没感觉
> ws+tls，没伪站...CF和直连都用

有可能是你运气好

**Comment by FlyingStarlight** [comment]
> > 用同一个id 2个月了
> > 没感觉
> > ws+tls，没伪站...CF和直连都用
> 
> 有可能是你运气好

那也有可能是你运气差对吧...
全球最大mjj论坛 和 https://github.com/v2ray/v2ray-core/issues 都没有印象类似的问题
