### ISSUE TITLE
用域名搭建了网站的前提下，用子域名搭建wls+tls协议，发现网络无法连接的情况。

### ISSUE THREAD

**Issue by Devil180410CN** [233boy/v2ray#441]
我在用子域名搭建的wls+tls协议连接谷歌时发现连接不上的情况。以下两段是不同子域名搭建连接的错误日志

2020/01/15 19:13:42 tcp:127.0.0.1:3851 accepted tcp:www.google.com:443 [proxy] 
2020/01/15 19:13:42 tcp:127.0.0.1:3854 accepted tcp:fonts.googleapis.com:443 [proxy] 
2020/01/15 19:13:47 tcp:127.0.0.1:3858 accepted tcp:216.58.200.37:443 [proxy] 
2020/01/15 19:13:50 tcp:127.0.0.1:3861 accepted tcp:[2404:6800:4008:803::2005]:443 [proxy] 
2020/01/15 19:13:50 tcp:127.0.0.1:3864 accepted tcp:[2404:6800:4008:803::2005]:443 [proxy] 
2020/01/15 19:13:55 tcp:127.0.0.1:3867 accepted tcp:[2404:6800:4008:803::2005]:443 [proxy] 
**2020/01/15 19:14:03 tcp:127.0.0.1:3869 rejected  v2ray.com/core/proxy/socks: unknown Socks version: 67**
2020/01/15 19:14:05 tcp:127.0.0.1:3871 accepted tcp:[2404:6800:4008:803::2005]:443 [proxy] 
2020/01/15 19:14:05 tcp:127.0.0.1:3875 accepted tcp:gameplay.intel.com:443 [proxy] 
2020/01/15 19:14:05 tcp:127.0.0.1:3876 rejected  v2ray.com/core/proxy/socks: unknown Socks version: 67
2020/01/15 19:14:07 tcp:127.0.0.1:3877 rejected  v2ray.com/core/proxy/socks: unknown Socks version: 67
2020/01/15 19:14:08 tcp:127.0.0.1:3879 accepted tcp:clients4.google.com:443 [proxy] 
2020/01/15 19:14:09 tcp:127.0.0.1:3881 rejected  v2ray.com/core/proxy/socks: unknown Socks version: 67
**2020/01/15 19:14:12 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF**
2020/01/15 19:14:12 tcp:127.0.0.1:3885 accepted tcp:www.google.com:443 [proxy] 
2020/01/15 19:14:12 tcp:127.0.0.1:3889 accepted tcp:userstylesapi.com:443 [proxy] 
2020/01/15 19:14:13 tcp:127.0.0.1:3892 accepted tcp:gameplay.intel.com:443 [proxy] 
2020/01/15 19:14:16 tcp:127.0.0.1:3895 accepted tcp:fonts.googleapis.com:443 [proxy] 
2020/01/15 19:14:19 tcp:127.0.0.1:3898 accepted tcp:www.google.com:443 [proxy] 
2020/01/15 19:14:34 tcp:127.0.0.1:3900 accepted tcp:mail.google.com:443 [proxy] 
2020/01/15 19:14:38 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
2020/01/15 19:14:38 tcp:127.0.0.1:3904 accepted tcp:beacons.gcp.gvt2.com:443 [proxy] 
2020/01/15 19:14:39 tcp:127.0.0.1:3907 accepted tcp:gameplay.intel.com:443 [proxy] 

A unified platform for anti-censorship.
2020/01/15 19:17:31 [Warning] v2ray.com/core: V2Ray 4.22.1 started
2020/01/15 19:17:35 tcp:127.0.0.1:3995 accepted tcp:[2404:6800:4008:803::2005]:443 [proxy] 
2020/01/15 19:17:38 tcp:127.0.0.1:4003 accepted tcp:172.217.24.5:443 [proxy] 
2020/01/15 19:17:39 tcp:127.0.0.1:4010 accepted tcp:[2404:6800:4002:809::200a]:443 [proxy] 
2020/01/15 19:17:39 tcp:127.0.0.1:4012 accepted tcp:www.google.com:443 [proxy] 
**2020/01/15 19:17:44 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://surzpost.com/): 301 Moved Permanently > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed**
2020/01/15 19:17:45 tcp:127.0.0.1:4017 accepted tcp:www.google.com:443 [proxy] 
2020/01/15 19:17:45 tcp:127.0.0.1:4021 accepted tcp:[2404:6800:4002:809::200a]:443 [proxy] 
2020/01/15 19:17:46 tcp:127.0.0.1:4025 accepted tcp:172.217.24.5:443 [proxy] 
2020/01/15 19:17:52 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://surzpost.com/): 301 Moved Permanently > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed
2020/01/15 19:17:58 tcp:127.0.0.1:4031 accepted tcp:www.google.com:443 [proxy] 
2020/01/15 19:17:58 tcp:127.0.0.1:4034 accepted tcp:[2404:6800:4002:809::200a]:443 [proxy] 
2020/01/15 19:18:04 tcp:127.0.0.1:4042 accepted tcp:mail.google.com:443 [proxy] 
2020/01/15 19:18:04 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://surzpost.com/): 301 Moved Permanently > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed
2020/01/15 19:18:05 tcp:127.0.0.1:4046 accepted tcp:mail.google.com:443 [proxy] 
2020/01/15 19:18:09 tcp:127.0.0.1:4051 accepted tcp:clients4.google.com:443 [proxy] 
2020/01/15 19:18:13 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://surzpost.com/): 301 Moved Permanently > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed

**Comment by sutun2008** [comment]
在搭建了网站的情况下不可用吧
