### ISSUE TITLE
强烈要求屏蔽谷歌

### ISSUE THREAD

**Issue by cannotbeblank** [233boy/v2ray#446]

**Comment by Mackel123** [comment]
你是SB吗？

**Comment by 0x0004** [comment]
> 你是SB吗？

他应该是在嘲讽此脚本默认屏蔽一些网站，而屏蔽哪些网站却完全由作者决定。
其实应该要么不带屏蔽，要么支持可选屏蔽，默认就屏蔽有一说一确实恶心。

**Comment by doKill** [comment]
有一说一，作者不对任何人负责，完全由心情决定任何内容[手动狗头]

**Comment by nxtreaming** [comment]
有一说一，作者SB，不应该强制凭自己心情屏蔽了某些网站。

**Comment by Mackel123** [comment]
原来如此～还有这种蠢事

**Comment by Liuhuifeng** [comment]
这样是墙中墙啊，随意屏蔽，自作聪明。

**Comment by phlinhng** [comment]
改个配置文件就能去除的东西，都能上github了不会编辑config.json？

**Comment by zhz1237ok** [comment]
以后写个自用，这样就没怨言了，v2ray明明有官方的一键脚本，不去用，一定要贴到这里来用，用了还有怨言

**Comment by ChengEast** [comment]
建议233把这个帖删了。一堆白痴

**Comment by Mackel123** [comment]
这玩意现在有人用？反正我是不用，但是你自动屏蔽部分网站是真的骚，现在流行自己审查自己了？官方审查不够，你还要充当一下人民网警？怕不是要笑死人。上面两个SB竟然这样来回复～真是

**Comment by wuliao1223** [comment]
> > 你是SB吗？
> 
> 他应该是在嘲讽此脚本默认屏蔽一些网站，而屏蔽哪些网站却完全由作者决定。
> 其实应该要么不带屏蔽，要么支持可选屏蔽，默认就屏蔽有一说一确实恶心。

你可以选择不用这个一键脚本

**Comment by 0x0004** [comment]
> > > 你是SB吗？
> > 
> > 
> > 他应该是在嘲讽此脚本默认屏蔽一些网站，而屏蔽哪些网站却完全由作者决定。
> > 其实应该要么不带屏蔽，要么支持可选屏蔽，默认就屏蔽有一说一确实恶心。
> 
> 你可以选择不用这个一键脚本

只是最初了解v2ray的时候测试过一次这个脚本，后来早换v2-ui了。
