### ISSUE TITLE
关于多用户和流量统计问题

### ISSUE THREAD

**Issue by freedomwebcn** [233boy/v2ray#448]
可以直接在v2ray 的config.json 中 clients数组里面添加多条用户信息对象吗？我这样做了，貌似没有什么问题。另外关于流量统计问题，我照着V2官方的操作，到了使用 v2ctl 查询的时候 提示v2ctl command not found。

**Comment by freedomwebcn** [comment]
解决了

**Comment by Lauren-Guo** [comment]
如何添加多条用户信息对象？方便贴一下吗？谢谢
