### ISSUE TITLE
大佬啊是不是跟新下tls1.3支持啊

### ISSUE THREAD

**Issue by xmhlg** [233boy/v2ray#453]
大佬啊是不是跟新下tls1.3支持啊，不更新，一直断流

**Comment by Jacob0707** [comment]
> 大佬啊是不是跟新下tls1.3支持啊，不更新，一直断流

我也一直断流，家里用的移动宽带，这几天换了N个GCP的地区都是断流，各种断。

**Comment by Jacob0707** [comment]
我测试了其他脚本，更换了TLS 1.3，还是换断流，经过两天的测试，终于知道是运营商的问题。

**Comment by xmhlg** [comment]
营运商什么问题？怎么解决？

**Comment by Leeray-Lau** [comment]
@Jacob0707 @xmhlg 那个……你们是不是用几分钟左右就会出现断流的情况呀？(•́へ•́╬)

这是我发布的issues：[V2Ray + WebSocket + TLS + CDN 几分钟左右就会出现一次断流](https://github.com/v2ray/v2ray-core/issues/2198)

也是用的233大佬的脚本。网上的方案都是过了，依旧断流……

**Comment by Jacob0707** [comment]
> @Jacob0707 @xmhlg 那个……你们是不是用几分钟左右就会出现断流的情况呀？(•́へ•́╬)
> 
> 这是我发布的issues：[V2Ray + WebSocket + TLS + CDN 几分钟左右就会出现一次断流](https://github.com/v2ray/v2ray-core/issues/2198)
> 
> 也是用的233大佬的脚本。网上的方案都试过了，依旧断流……

是的，我用的是移动宽带+GCP+V2ray+WS+TLS（233和其他开发者提供的安装脚本都试过），长ping会有十分频繁的丢包，而且会经常断流。后来我尝试换其他服务商提供的VPS，情况依旧。经过一番折腾之后，我加上了Cloudflare的CDN，使用其他开发者的安装脚本，现在已经基本稳定了。最后的环境是移动宽带+HKVPS+V2ray+WS+TLS+CDN，V2ray用的是wulabing提供的脚本。

**Comment by ardayan** [comment]
难怪我的圈X 1.07（支持tls1.3）一直断流。。。

**Comment by ardayan** [comment]
断流的可以尝试把系统的ulimit -n改大试试
