### ISSUE TITLE
把云朵点亮后caddy 未运行

### ISSUE THREAD

**Issue by liangpu597** [233boy/v2ray#454]
按照脚本的教程，搭建了cloudflare ， 买的godaddy 的域名。ip已经被墙，在点灰的时候，ping域名可以得到vps的ip，按照脚本进行搭建，最后。v2ray status 显示都在运行，此时，还是不能正常翻墙。接着将云朵点亮，ssl 先设置成null 然后设置成full, 此时 v2ray status ，提示v2在运行， caddy 未在运行，还是不能翻墙。
请问应该怎么做？

**Comment by 233boy** [comment]
@liangpu597 
caddy 那边出错了
输入这个看看怎么回事吧
`systemctl status caddy`
