### ISSUE TITLE
ws+tls默认端口就是443？修改端口流程死循环

### ISSUE THREAD

**Issue by murazi** [233boy/v2ray#455]
> 之后选择安装，传输协议选择 WebSocket + TLS (即是选择 4 )，V2Ray 端口随便，不要是 80 和 443 即可，然后输入你的域名，域名解析 Y ，自动配置 TLS 也是 Y ，其他就默认吧，一路回车。等待安装完成

看说明是这么说，但安装后默认端口就是443啊

去SSH修改端口的话，要求我重新选择协议，再次选择ws+tls的话，提示已经是该模式了，切换别的模式再修改回来，仍然是默认443

死循环？

**Comment by 3199361233** [comment]
没办法我的也是，但是能用

**Comment by 233boy** [comment]
@murazi 

可能是教程没有写好，或者是你没理解好。那个端口指的是 V2RAY 的端口，你在配置的过程中会有一个 V2RAY 端口的选项配置的，然后因为要使用 CADDY 作为转发，CADDY 得监听 443 / 80 端口，所以 V2RAY 不能为这两个端口。

反正总的来说，就是 V2RAY 的端口不能 80 / 443。

但是为什么配置会显示 443 端口呢？
因为前面说了，要用 CADDY 转发，理解一下：你的请求》CADDY》V2RAY。

**Comment by ylsb** [comment]
@233boy 

请问如果我自建的nginx已经使用了443端口，我希望用其他端口来将请求转发到v2ray，应该怎么改呢？
我现在的nginx代理端口为8443，v2ray端口是9800，但是看v2ray info显示代理端口依然是443并不是正确的8443，然后配置下发客户端也是错误的443，需要手动修改8443才行

**Comment by ylsb** [comment]
补充一下，我是希望订阅功能继续生效，不需要每次都要手动修改客户端配置-.-

**Comment by miaobang** [comment]
> @233boy
> 
> 请问如果我自建的nginx已经使用了443端口，我希望用其他端口来将请求转发到v2ray，应该怎么改呢？ 我现在的nginx代理端口为8443，v2ray端口是9800，但是看v2ray info显示代理端口依然是443并不是正确的8443，然后配置下发客户端也是错误的443，需要手动修改8443才行

我也遇到同样的问题，请问最终解决了吗？

**Comment by Creepender-Brine** [comment]
我也...

**Comment by xYx-c** [comment]
果然是同一个问题，就是一直没找到怎么解决
