### ISSUE TITLE
v2ray经常连不上，必须要重新安装服务端

### ISSUE THREAD

**Issue by 1998ybr** [233boy/v2ray#456]
如题，
log好像也是正常输出的

**Comment by zhz1237ok** [comment]
仅看标题，感觉是服务器商IP经常被扫到，所以换个服务器商或者过一阵子就好了

**Comment by 1998ybr** [comment]
> 
> 
> 仅看标题，感觉是服务器商IP经常被扫到，所以换个服务器商或者过一阵子就好了

但是ip并没有被ban，ping得通
而且确实是昨天被ban过一次，之前用的挺稳定的，然后我换了一个ip，就这样了
用的是cloudcone

**Comment by qqlovekerry** [comment]
@1998ybr 你好！请问你的问题解决了吗？我也是用的cloudcone的vps，之前出现无法连接的问题之后重启vps好了，但是这两天发现用什么协议安装都不能正常使用，ubuntu和android都连接不上。
