### ISSUE TITLE
安装脚本会造成FRP内网穿透无法访问，端口无法访问

### ISSUE THREAD

**Issue by kofzjs** [233boy/v2ray#46]
一键安装脚本安装好，之后v2ray软件打开的服务tcp端口都可以正常访问，但是FRP软件打开的tcp端口都无法访问,无法使用服务器IP+端口访问FRP的WEB控制面板，FRP服务器IP+端口访问提示" Python 501的错误“。
  本人使用谷歌云，防火墙端口进站已经全部允许，在多次重复安装系统之后，才发现只要安装v2ray脚本就肯定造成FRP服务器端口无法访问，在多次重新安装系统后得出结果。安装原版v2ray go.sh安装脚本没有这个问题，麻烦大神测试谢谢,

**Comment by 233boy** [comment]
@kofzjs 
很抱歉咯...这个我真的不清楚，你可以尝试先安装 然后再 内网穿透 看看
