### ISSUE TITLE
协议选了ws+tls，pc连网线测速100M左右， 无线网络（pc和安卓）几乎没速度

### ISSUE THREAD

**Issue by SeanTong11** [233boy/v2ray#460]
如题，这个问题真的困扰了我很久，最近为了稳定弄了ws+tls，用的cf的cdn，服务器为搬瓦工，开启之后，有线网络能跑满宽带（100M），而用wifi连pc和安卓（pc客户端为v2rayN,安卓为v2rayNG）速度非常慢，开个视频都要半天响应，有时候甚至开不开网页，哪位懂的大佬能不能帮帮忙解决下小弟的疑惑，感激不尽。
附上日志：
客户端：
`2020/02/04 23:07:13 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)`

服务器端：
`2020/02/04 23:19:12 1*.2*.1*.2*:47072 rejected  v2ray.com/core/proxy/vmess/encoding: failed to read request header > websocket: close 1006 (abnormal closure): unexpected EOF
`

配置文件：

[233blog_v2ray_config_18939.txt](https://github.com/233boy/v2ray/files/4154257/233blog_v2ray_config_18939.txt)

**Comment by SeanTong11** [comment]
最令我绝望的是网上的ws+tls免费节点都比我的快

**Comment by zarrichen** [comment]
估计是DNS问题，我之前用SSR基本全部是满速的，油管最少可以到11W，后面改了v2+ws+tls之后感觉速度慢了不少。网上找了找相关资料，有的讲是因为用cf的问题，也有讲DNS的问题。
。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。
6月3号之后，之前的ss、S-S R、v2瑞露头就封。我之前用的是v2瑞 mkcp微信通话做的隐藏。很稳用了大半年没出问题。

这次好了，2天之内，必被封IP。无奈，升级到v2瑞的ws tls模式，套了CF，才得以苟活。大家那边的情况如何？

在K3梅林下，可以满速，但延时很高，经常掉包。把节点换到北美，好很多，但跟不带套，还是没法比。

奇怪的是，同样的节点，用A大的官改，延迟高，卡到废，跑一下，最多只能跑个三分之一带宽：3M/s左右。

搜索了全网，无解。只得用最笨的方法，一点一点测试，最终发现是DNS解析的问题。

A大留下的配置代码，没有指向DNS，有缺陷。通过对代码进行了小优化，终于解决了问题。

**Comment by SeanTong11** [comment]
@zarrichen 谢谢，我往这方面研究研究

**Comment by 233boy** [comment]
> A大留下的配置代码，没有指向DNS，有缺陷。通过对代码进行了小优化，终于解决了问题。

😢  指的哪个呢？

**Comment by zarrichen** [comment]
留下脚印，方便后来人。。。


{
  "inbound": {
    "protocol": "dokodemo-door",
    "port": 1234,  
    "settings": {
    "network": "### tcp,udp",
    "timeout": 30,
    "followRedirect": true
    }
  },
   ###  "dns": {
        "servers": [
            "8.8.8.8:53",
            "localhost"
        ]
    },
  "outbound": {
    "protocol": "vmess",
    "settings": {
    "udp": true,
      "vnext": [{
        "address": "xxx.ml", 
        "port": 443,  
         "users": [
        {
          "id": "111-222-333-444-555",
          "alterId": 64,
          "security": "aes-128-gcm",
          "level": 0
        }
              ]
      }]
    }, 
   "streamSettings": {
      "network": "ws",
      "security": "tls",
      "tlsSettings": {
        "serverName": "xxx.ml",
        "allowInsecure": true
       },
      "wsSettings": {
        "connectionReuse": true,
        "path": "/"
      }
    }
}
}

上述原理，CF套在美国，DNS就不能搞默认。完全指向8.8.8.8:53，速度明显提上去了。

**Comment by zarrichen** [comment]
原谅不会把重点代码的地方加粗，所以再回复一遍。
 "dns": {
        "servers": [
            "8.8.8.8:53",
            "localhost"
        ]
    },
主要是这一段。以上这些我也是网上查的

**Comment by SeanTong11** [comment]
> 原谅不会把重点代码的地方加粗，所以再回复一遍。
> "dns": {
> "servers": [
> "8.8.8.8:53",
> "localhost"
> ]
> },
> 主要是这一段。以上这些我也是网上查的

谢谢分享，我试了下，不行，应该是其他原因，而且我有线连也几乎没用了，似乎是cf的问题，ping 域名丢包率非常高，用空试试手动配一下，或者转trojan

**Comment by blackjackgg** [comment]
@zarrichen  感谢 亲测可用 很强

**Comment by byroning** [comment]
> 留下脚印，方便后来人。。。
> 
> { "inbound": { "protocol": "dokodemo-door", "port": 1234, "settings": { "network": "### tcp,udp", "timeout": 30, "followRedirect": true } },
> 
> ### "dns": {
> ```
>     "servers": [
>         "8.8.8.8:53",
>         "localhost"
>     ]
> },
> ```
> 
> "outbound": { "protocol": "vmess", "settings": { "udp": true, "vnext": [{ "address": "xxx.ml", "port": 443, "users": [ { "id": "111-222-333-444-555", "alterId": 64, "security": "aes-128-gcm", "level": 0 } ] }] }, "streamSettings": { "network": "ws", "security": "tls", "tlsSettings": { "serverName": "xxx.ml", "allowInsecure": true }, "wsSettings": { "connectionReuse": true, "path": "/" } } } }
> 
> 上述原理，CF套在美国，DNS就不能搞默认。完全指向8.8.8.8:53，速度明显提上去了。

请问，这代码放在什么位置？
