### ISSUE TITLE
websocket + TLS配置成功，小火箭已经成功上网，但mac端的v2rayX怎么填写都是连不上去？

### ISSUE THREAD

**Issue by merkillow** [233boy/v2ray#461]
有没有属于Mac的V2rayX关于websocket + TLS配置的教程，我想小火箭可以用应该就是客户端配置的问题了。

**Comment by zarrichen** [comment]
之前我也遇到同样的问题，应该是你的v2rayX的客户端设置的问题

**Comment by narrowsnap** [comment]
@merkillow 请问解决了吗，我也遇到这个问题，并且使用其他server address 在电脑上都能用。
