### ISSUE TITLE
安装一件脚本就封IP！

### ISSUE THREAD

**Issue by limintao** [233boy/v2ray#462]
我最近一个月，换了好几次IP了，只要不安装233一键脚本，IP就可以一直正常访问，一安装一键脚本立马IP就被封了！我现在已经被封5个IP了！

**Comment by 233boy** [comment]
@limintao 
请出示证据

**Comment by limintao** [comment]
我只是想知道是否脚本目前存在问题，我并没别的意思，我无法证明是否是因为脚本被封的，我只是每次在安装完脚本后五分钟之内就被封IP，所以我才来问你的！

**Comment by xiwei26** [comment]
我的digitalocean最近也是，用的mKCP，每隔24小时就被封，但奇怪的是脚本里的SS没有问题，就是v2ray被封

**Comment by limintao** [comment]
@xiwei26 我也没有用ss，我也是用的mKCP

**Comment by zhz1237ok** [comment]
哪家VPS商

**Comment by limintao** [comment]
> 哪家VPS商

tripodcloud

**Comment by zhz1237ok** [comment]
> > 哪家VPS商
> 
> tripodcloud

是个国产公司，可以考虑同行举报与攻击

**Comment by limintao** [comment]
> > > 哪家VPS商
> > 
> > 
> > tripodcloud
> 
> 是个国产公司，可以考虑同行举报与攻击

好的，谢谢了
