### ISSUE TITLE
v2ray使用wifi速度极慢 但使用4g网络速度正常

### ISSUE THREAD

**Issue by SkylakeXS** [233boy/v2ray#464]
wifi和4g均为联通网络 使用wifi打开被墙网站时速度极慢且偶尔直接打不开 4g则没有这个问题

**Comment by sk8erboii** [comment]
你好，我的情况是搭建好v2ray后，安卓联通4G秒连。但wifi能测2次显示正常，连上后却没有速度

**Comment by SkylakeXS** [comment]
你好 是这样 我换到一个速度快的联通WiFi后速度有明显提升 但我也不确定是什么原因导致的 如果你跟我一样使用GCP搭建的话可以尝试更改传输协议

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: sk8erboii<mailto:notifications@github.com>
发送时间: 2020年2月7日 4:50
收件人: 233boy/v2ray<mailto:v2ray@noreply.github.com>
抄送: SkylakeXS<mailto:mmyyll@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [233boy/v2ray] v2ray使用wifi速度极慢 但使用4g网络速度正常 (#464)


你好，我的情况是搭建好v2ray后，安卓联通4G秒连。但wifi能测2次显示正常，连上后却没有速度

―
