### ISSUE TITLE
www.nordstrom.com网站图片打不开

### ISSUE THREAD

**Issue by gassell** [233boy/v2ray#465]
TCP 推特正常、油管视频也能正常。但是www.nordstrom.com网站图片不能显示...有什么原因吗？火狐、chrome浏览器都不行

**Comment by Himalaya2020** [comment]
> TCP 推特正常、油管视频也能正常。但是www.nordstrom.com网站图片不能显示...有什么原因吗？火狐、chrome浏览器都不行

IP问题 服务端屏蔽
