### ISSUE TITLE
添加网站伪装后，出现的现象

### ISSUE THREAD

**Issue by timeday1102** [233boy/v2ray#467]
今天添加网站伪装的时候，网站名填的“https://github.com”，随后虽然添加成功了，但v2rayN这个软件里信息那一块，一直有
2020/02/06 02:15:12 tcp:127.0.0.1:14242 accepted tcp:1.tracker.eu.org:443 [proxy] 
2020/02/06 02:15:13 tcp:127.0.0.1:14245 accepted tcp:1.tracker.eu.org:443 [proxy] 
2020/02/06 02:15:18 tcp:127.0.0.1:14248 accepted tcp:1.tracker.eu.org:443 [proxy] 
2020/02/06 02:15:22 tcp:127.0.0.1:14251 accepted tcp:1.tracker.eu.org:443 [proxy] 这种信息出现。
  然后又重新改了个网站，仍然又该信息出现，请问这种信息出现是正常现象吗？

**Comment by timeday1102** [comment]
补充一下，虽然有上述的信息不断地出现，但该代理是可以用的，可以成功看youtube。

**Comment by 233boy** [comment]
@timeday1102 
这个只是展示访问日志呀，可能是某个网页或者某个软件访问了上面这个网址的，可能某些是 Report 之类的吧，实在不想看到，可以在 V2RAYN 配置屏蔽这个域名
