### ISSUE TITLE
为什么我其中一台小鸡始终不能用WS，配置之后连接一直显示

### ISSUE THREAD

**Issue by dbguo** [233boy/v2ray#469]
2020/02/07 10:24:27 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://www.dbvm.ml/): 521 Origin Down > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed

**Comment by noNameForMe1994** [comment]
请问这个问题你解决了么？我也遇到了相同的问题

**Comment by dbguo** [comment]
> 请问这个问题你解决了么？我也遇到了相同的问题

解决了，等了一天就好了。。

**Comment by edrainann** [comment]
> > 请问这个问题你解决了么？我也遇到了相同的问题
> 
> 解决了，等了一天就好了。。

我也遇到了...解决了好久...请问是怎么解决的呢？

**Comment by dbguo** [comment]
> > > 请问这个问题你解决了么？我也遇到了相同的问题
> > 
> > 
> > 解决了，等了一天就好了。。
> 
> 我也遇到了...解决了好久...请问是怎么解决的呢？

我的主要还是caddy未能启动的问题，你输入v2ray status看看呗。我等了一天后重启小鸡后caddy莫名就变正在运行了，我也不知道为什么。

**Comment by edrainann** [comment]
等待了一天，排查了一天的问题，还是不得行...于是全部重新装...半个小时愉快的成功了。
