### ISSUE TITLE
建议把安装命令写进README.md

### ISSUE THREAD

**Issue by iseeyo** [233boy/v2ray#47]
把 bash <(curl -s -L https://233blog.com/v2ray.sh) 这样的方法写进README.md，以便博客不正常时用户仍能从github上看到安装命令。

**Comment by darkrain88** [comment]
呵呵git clone 。/sh online

**Comment by 233boy** [comment]
@iseeyo 
如果我的博客打不开，这个 命令也没用呀 😂

**Comment by iseeyo** [comment]
哈哈哈，我主要想说的是 bash <(curl -s -L https://域名/v2ray.sh) 这个方法
