### ISSUE TITLE
bash <(curl -s -L https://git.io/v2ray.sh)  安装 Caddy 出错！

### ISSUE THREAD

**Issue by yanbodegithub** [233boy/v2ray#472]
您好，在使用V2Ray 传输协议 = WebSocket + TLS

/tmp/v2ray.zip        100%[=========================>]  11.60M  17.9MB/s    in 0.6s    

2020-02-07 20:52:14 (17.9 MB/s) - ‘/tmp/v2ray.zip’ saved [12163654/12163654]

Archive:  /tmp/v2ray.zip
  inflating: /usr/bin/v2ray/config.json  
  inflating: /usr/bin/v2ray/doc/readme.md  
  inflating: /usr/bin/v2ray/geoip.dat  
  inflating: /usr/bin/v2ray/geosite.dat  
  inflating: /usr/bin/v2ray/systemd/v2ray.service  
  inflating: /usr/bin/v2ray/systemv/v2ray  
  inflating: /usr/bin/v2ray/v2ctl    
 extracting: /usr/bin/v2ray/v2ctl.sig  
  inflating: /usr/bin/v2ray/v2ray    
 extracting: /usr/bin/v2ray/v2ray.sig  
  inflating: /usr/bin/v2ray/vpoint_socks_vmess.json  
  inflating: /usr/bin/v2ray/vpoint_vmess_freedom.json  
--2020-02-07 20:52:15--  https://caddyserver.com/download/linux/amd64?license=personal
Resolving caddyserver.com (caddyserver.com)... 138.68.240.78, 2604:a880:2:d0::1145:e001
Connecting to caddyserver.com (caddyserver.com)|138.68.240.78|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘/tmp/install_caddy/caddy.tar.gz’

/tmp/install_caddy/ca     [  <=>                     ]  10.69M  49.0MB/s    in 0.2s    

2020-02-07 20:52:15 (49.0 MB/s) - ‘/tmp/install_caddy/caddy.tar.gz’ saved [11206749]

/etc/v2ray/233boy/v2ray/src/download-caddy.sh: line 16: tar: command not found
cp: cannot stat '/tmp/install_caddy/caddy': No such file or directory
 安装 Caddy 出错！

**Comment by 233boy** [comment]
@yanbodegithub 
> /etc/v2ray/233boy/v2ray/src/download-caddy.sh: line 16: tar: command not found

因为没有 tar 命令，得安装
Debian /  Ubuntu 系统：`apt-get install tar`
Centos 系统：`yum install tar`
