### ISSUE TITLE
cloudflare 域名解析问题 一直是‘检测域名解析错误....’

### ISSUE THREAD

**Issue by seedsboy007** [233boy/v2ray#476]
检测域名解析错误....
 你的域名: xxxx.xxx 未解析到: xx.xxx.xx.xxx
 你的域名当前解析到: xxx.xx.xxx.xx

cloudflare那边设置完全没问题，云朵那边是灰色的，就是v2ray这步一直不行，怎么回事啊，有大佬知道吗，谢谢了

谷歌云的香港地址，ping不通，ip被墙了，想用这种方法挽救，我看网上都可以啊，为什么我解析都不行呢，哪里出问题了呢？

**Comment by dbguo** [comment]
换个二级域名看看

**Comment by yangdong861222** [comment]
我在cloudflare配置好后，在国内主机ping域名，解析到的IP正确，在VPS端ping域名，IP也正确，但是运行v2ray的安装脚本，解析会失败，发现是脚本里的这句话返回值在很长一段时间不包含IP地址（curl -sH 'accept: application/dns-json' "https://cloudflare-dns.com/dns-query?name=$domain&type=A"），等了大概一个多小时，才能得到，之后就正常了，所以你再多等等

**Comment by redstoneleo** [comment]
> 我在cloudflare配置好后，在国内主机ping域名，解析到的IP正确，在VPS端ping域名，IP也正确，但是运行v2ray的安装脚本，解析会失败，发现是脚本里的这句话返回值在很长一段时间不包含IP地址（curl -sH 'accept: application/dns-json' "[https://cloudflare-dns.com/dns-query?name=$domain&type=A"），等了大概一个多小时，才能得到，之后就正常了，所以你再多等等](https://cloudflare-dns.com/dns-query?name=$domain&type=A%22%EF%BC%89%EF%BC%8C%E7%AD%89%E4%BA%86%E5%A4%A7%E6%A6%82%E4%B8%80%E4%B8%AA%E5%A4%9A%E5%B0%8F%E6%97%B6%EF%BC%8C%E6%89%8D%E8%83%BD%E5%BE%97%E5%88%B0%EF%BC%8C%E4%B9%8B%E5%90%8E%E5%B0%B1%E6%AD%A3%E5%B8%B8%E4%BA%86%EF%BC%8C%E6%89%80%E4%BB%A5%E4%BD%A0%E5%86%8D%E5%A4%9A%E7%AD%89%E7%AD%89)

我也碰到了同样的问题，不知道作者能否优化下
