### ISSUE TITLE
这个程序有一个问题，CADDY的网页文件放哪了？找不到

### ISSUE THREAD

**Issue by sshappys** [233boy/v2ray#477]
或者，我在同一个VPS建了WEB服务器，但不知道怎么能让CADDY找到。。。。

**Comment by glovanni** [comment]
等着你的答案

**Comment by Rhinocros** [comment]
脚本安装过程记不记得除了翻墙的域名，还输入过一个网址，看一下Caddy的配置文件就知道了，直接转到你输入的那个网站了，本地并没有网站文件
