### ISSUE TITLE
一键v2好像没有正常运行，ss和mt却是正常的，

### ISSUE THREAD

**Issue by ianlie** [233boy/v2ray#479]
centos7，端口开放正常，
设置v2-8866，ss-8867，mt-8024，
ss和mt使用v2的端口是正常可搜可用的，
v2换用ss和mt本正常的端口，就不行，

v2在top里面也是经常不见踪影，
因为才刚升级了主程序到4.22.1，
不知道是不是有关系，

目前的情况就是v2无法使用，端口也无发扫描到，
ss和mt是正常的，

**Comment by yu-geek** [comment]
我和你一样的情况。今天重装了V2RAY以后，用了一下午正常，然后到傍晚突然异常无法使用v2ray。，但是该vps的ss却又能正常用。。再重装也是同样的情况。。兄弟后来有解决问题吗？

**Comment by Prussia** [comment]
Ubuntu 18 有同样的问题，11.20 版本是正常的

**Comment by ianlie** [comment]
> 我和你一样的情况。今天重装了V2RAY以后，用了一下午正常，然后到傍晚突然异常无法使用v2ray。，但是该vps的ss却又能正常用。。再重装也是同样的情况。。兄弟后来有解决问题吗？

还没解决，后来试过用v2自家的一键，是可以用的，只是配置比较麻烦，感觉应该是233的脚本哪里没处理好，v2没正常运行的样子，
正在等到大佬拯救，

**Comment by Prussia** [comment]
> Ubuntu 18上 有同样的问题，11.20 版本是正常的。

解决了。换了个vps，重新装下就行了。ip大概被墙了

**Comment by ianlie** [comment]
今天不死心又重起了一次，顺便查了一下端口发现是udp，就再试了一下，发现可以了，，，，不知道为啥，所以来关闭问题，只开udp的话就跟端口扫描结果没关系了，可是为啥以前可以搜到，v2自家的也可以，现在不行了呢，而且之前也是确实用不了的，现在又突然用得了了，，蔗，，，
