### ISSUE TITLE
安装V2Ray+WS+TLS后，如何通过域名访问自定义index.html？

### ISSUE THREAD

**Issue by glovanni** [233boy/v2ray#483]
现在通过233一键脚本成功安装了V2Ray和Websocks+Tls服务，也能成功上网。
但是想在此基础上部署web应用，请问该如何操作？应该将应用放在哪个目录，配置文件是否需要更改？

**Comment by glovanni** [comment]
通过网站伪装能实现打开另一个网页的功能，现在只想做一个index.html，输入域名后展示一些自定义文本，而不是bad request就行。
这个index.html该怎么放

**Comment by jaywong003** [comment]
兄弟，我也成功安装了V2Ray和Websocks+Tls服务，但是不能正常上网，怎么回事呢？能提个建议吗？

**Comment by glovanni** [comment]
> 兄弟，我也成功安装了V2Ray和Websocks+Tls服务，但是不能正常上网，怎么回事呢？能提个建议吗？
一键脚本安装成功后，通过链接或二维码添加客户端配置，直接就可以上了。
还有就是你的域名解析设置好就完事儿了

**Comment by jaywong003** [comment]
收到！已经弄好了，多谢！&nbsp;

——王杰^_^


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "glovanni"<notifications@github.com&gt;; 
发送时间: 2020年2月15日(星期六) 上午10:24
收件人: "233boy/v2ray"<v2ray@noreply.github.com&gt;; 
抄送: "王杰"<724647513@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [233boy/v2ray] 安装V2Ray+WS+TLS后，如何通过域名访问自定义index.html？ (#483)



 
兄弟，我也成功安装了V2Ray和Websocks+Tls服务，但是不能正常上网，怎么回事呢？能提个建议吗？
 一键脚本安装成功后，通过链接或二维码添加客户端配置，直接就可以上了。
 还有就是你的域名解析设置好就完事儿了

**Comment by jaywong003** [comment]
我连不上的原因是nginx配置文件没有与v2ray关联好，端口没设置对。
&nbsp;

——王杰^_^


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "glovanni"<notifications@github.com&gt;; 
发送时间: 2020年2月15日(星期六) 上午10:24
收件人: "233boy/v2ray"<v2ray@noreply.github.com&gt;; 
抄送: "王杰"<724647513@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [233boy/v2ray] 安装V2Ray+WS+TLS后，如何通过域名访问自定义index.html？ (#483)



 
兄弟，我也成功安装了V2Ray和Websocks+Tls服务，但是不能正常上网，怎么回事呢？能提个建议吗？
 一键脚本安装成功后，通过链接或二维码添加客户端配置，直接就可以上了。
 还有就是你的域名解析设置好就完事儿了

**Comment by ChengEast** [comment]
请问一上nginx配置要怎么设置呢？我现在就是v2ray和nginx端口冲突，一个能启动起来，另一个就不行了。

**Comment by baoyuangui** [comment]
> 现在通过233一键脚本成功安装了V2Ray和Websocks+Tls服务，也能成功上网。
> 但是想在此基础上部署web应用，请问该如何操作？应该将应用放在哪个目录，配置文件是否需要更改？

我也是，用了另外一个脚本安装的也是，看视频里安装完后可以通过域名打开一个网页，但是我的死活打不开，ip+443端口都没有网页。但是配置可以用了。我在想，会不会出现没有伪装的情况，永久了ip就挂了。有人可以回答一下这个问题吗

**Comment by xqos** [comment]
> 收到！已经弄好了，多谢！&nbsp; ——王杰^_^ &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "glovanni"<notifications@github.com&gt;; 发送时间: 2020年2月15日(星期六) 上午10:24 收件人: "233boy/v2ray"<v2ray@noreply.github.com&gt;; 抄送: "王杰@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [233boy/v2ray] 安装V2Ray+WS+TLS后，如何通过域名访问自定义index.html？ (#483) 兄弟，我也成功安装了V2Ray和Websocks+Tls服务，但是不能正常上网，怎么回事呢？能提个建议吗？ 一键脚本安装成功后，通过链接或二维码添加客户端配置，直接就可以上了。 还有就是你的域名解析设置好就完事儿了 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
我也遇到同样的问题，是否能提供一下解决方案，我现在访问我的域名，出现了bad request

**Comment by xqos** [comment]
我也遇到同样的问题，是否能提供一下解决方案，我现在访问我的域名，出现了bad request

**Comment by baoyuangui** [comment]
> 请问一上nginx配置要怎么设置呢？我现在就是v2ray和nginx端口冲突，一个能启动起来，另一个就不行了。

用nginx的话，可以用另外一个人的脚本，他的是nginx。好像叫wulabing

**Comment by little-hao** [comment]
> 现在通过233一键脚本成功安装了V2Ray和Websocks+Tls服务，也能成功上网。 但是想在此基础上部署web应用，请问该如何操作？应该将应用放在哪个目录，配置文件是否需要更改？

问下这个后续配置index.html你有遇到其他问题吗
