### ISSUE TITLE
被墙IP搭建V2ray总卡在检测域名解析...求大神指路！！！

### ISSUE THREAD

**Issue by fsatun** [233boy/v2ray#484]
我的是被墙IP，域名的DNS已改为cloudflare的
我用的是  bash <(curl -s -L https://git.io/v2ray.sh)  搭建
系统是     CentOS 7.0 (64bit)
域名能ping通IP，，但请求超时

你的域名: xxx 未解析到: xxx

 你的域名当前解析到: 

备注...如果你的域名是使用 Cloudflare 解析的话..在 Status 那里点一下那图标..让它变灰

![解析不了](https://user-images.githubusercontent.com/32808491/74589820-ba7ce680-5043-11ea-8523-86b58d5205b1.jpg)

![PING](https://user-images.githubusercontent.com/32808491/74589967-2744b080-5045-11ea-9a6b-236f00413725.jpg)

![PINGP](https://user-images.githubusercontent.com/32808491/74590100-560f5680-5046-11ea-9674-741f736410b5.jpg)

求大神指路！

**Comment by Javion-Zh** [comment]
把cloudflare的黄色云朵置灰

**Comment by Miigon** [comment]
建议搭建纯websocket，无TLS，然后由cloudflare提供TLS，这样就不需要证书，而且效果相同

**Comment by cocobear** [comment]
`	test_domain=$(curl -sH 'accept: application/dns-json' "https://cloudflare-dns.com/dns-query?name=$new_domain&type=A" | grep -oE "([0-9]{1,3}\.){3}[0-9]{1,3}" | head -1)
`
把这一行注释掉，打开：
`
test_domain=$(ping $domain -c 1 -4 | grep -oE -m1 "([0-9]{1,3}\.){3}[0-9]{1,3}")
`
这一行的注释
