### ISSUE TITLE
WebSocket + TLS 和 TCP HTTP方式都试了，网络链接不上

### ISSUE THREAD

**Issue by ghostxiu** [233boy/v2ray#486]
安装的时候没有报错，但是链接，不上，扫码,WINDOWS都试了，IP也没有被强,VLUTR主机CENTOS8、CENTOS7都试过了，延迟一百多。

**Comment by Miigon** [comment]
贴你的服务端和客户端配置

**Comment by ghostxiu** [comment]
你好！您的邮件已收到，处理成功后会与您联系。修ghostxiu
