### ISSUE TITLE
V2ray不能跑满带宽么？

### ISSUE THREAD

**Issue by lzyyukito** [233boy/v2ray#487]
家中网络500M坐标深圳电信，用的是搬瓦工贷宽1Gbps的服务器坐标美国Los angle，但是开youtube只能去到15000Kbps，请大佬指教原因

**Comment by ETAQ** [comment]
路上车多，限速120，有几个能开到120的

**Comment by lzyyukito** [comment]
> 路上车多，限速120，有几个能开到120的

**Comment by lzyyukito** [comment]
> 路上车多，限速120，有几个能开到120的

但也不至于只能跑到15000Kbps吧

**Comment by ETAQ** [comment]
> > 路上车多，限速120，有几个能开到120的
> 
> 但也不至于只能跑到15000Kbps吧

知足吧，墙又不是摆设。你要是用ss跑这么高的流量早晚会被BAN的
