### ISSUE TITLE
显示监听tcp6导致不能正常连接

### ISSUE THREAD

**Issue by bbbbyakko** [233boy/v2ray#489]
![image](https://user-images.githubusercontent.com/61156880/74670119-80e2e180-51e3-11ea-8f8d-7a2f8e8c56cd.png)

**Comment by Zhou-Bill** [comment]
请问解决了吗

**Comment by huachen0216** [comment]
同问

**Comment by wujbclzw** [comment]
同问

**Comment by wujbclzw** [comment]
同样遇到这样的问题，用的是google云服务器
后来发现是端口没有设置好
在防火墙中设置端口规则后，没有应用到虚拟机实例。

使用 netstat -apn | grep v2ray 命令查看 还是tcp6 ，但确实可以连上了
