### ISSUE TITLE
v2ray配置好了，依然无法科学上网，找了很久没找到问题

### ISSUE THREAD

**Issue by Coder-Chandler** [233boy/v2ray#49]
老铁有空帮我看下问题所在啊，谢啦！
首先上一下域名相关配置
<img width="1022" alt="2018-07-22 23 47 05" src="https://user-images.githubusercontent.com/27991177/43055379-e96fe2ce-8e68-11e8-892c-390ef992b5c8.png">
<img width="1042" alt="2018-07-22 23 47 11" src="https://user-images.githubusercontent.com/27991177/43055400-f388c622-8e68-11e8-8cbf-68afc4cb5a32.png">

然后我的服务器config文件
首先是/etc/v2ray下的config.json
`{
    "log": {
        "access": "/var/log/v2ray/access.log",
        "error": "/var/log/v2ray/error.log",
        "loglevel": "warning"
    },
    "inbound": {
        "port": 27271,
        "protocol": "vmess",
        "settings": {
            "udp": true,
            "clients": [
                {
                    "id": "2fd54153-8cef-46e2-aa93-95b172de3e7a",
                    "level": 1,
                    "alterId": 233
                }
            ]
        },
        "streamSettings": {
            "network": "ws"
        }
    },
    "outbound": {
        "protocol": "freedom",
        "settings": {}
    },
    "outboundDetour": [
        {
            "protocol": "blackhole",
            "settings": {},
            "tag": "blocked"
        }
    ],
    "routing": {
        "strategy": "rules",
        "settings": {
            "rules": [
                {
                    "type": "field",
                    "ip": [
                        "0.0.0.0/8",
                        "10.0.0.0/8",
                        "100.64.0.0/10",
                        "127.0.0.0/8",
                        "169.254.0.0/16",
                        "172.16.0.0/12",
                        "192.0.0.0/24",
                        "192.0.2.0/24",
                        "192.168.0.0/16",
                        "198.18.0.0/15",
                        "198.51.100.0/24",
                        "203.0.113.0/24",
                        "::1/128",
                        "fc00::/7",
                        "fe80::/10"
                    ],
                    "outboundTag": "blocked"
                }
            ]
        }
    }`
然后是/etc/v2ray
`{
    "log": {
        "error": "error.log",
        "loglevel": "warning"
    },
    "inbound": {
        "port": 2333,
        "listen": "127.0.0.1",
        "protocol": "socks",
        "settings": {
            "auth": "noauth",
            "udp": true,
            "ip": "127.0.0.1"
        }
    },
    "outbound": {
        "protocol": "vmess",
        "settings": {
            "vnext": [
                {
                    "address": "www.xxxx.xyz",
                    "port": 443,
                    "users": [
                        {
                            "id": "2fd54153-8cef-46e2-aa93-95b172de3e7a",
                            "alterId": 233,
                            "security": "auto"
                        }
                    ]
                }
            ]
        },
        "streamSettings": {
            "network": "ws",
            "security": "tls",
            "tlsSettings": {
                "serverName": "www.xxxx.xyz"
            },
            "wsSettings": {
                "path": "/",
                "headers": {
                    "Host": "www.xxxx.xyz"
                }
            }
        },
        "mux": {
            "enabled": true
        }
    },
    "inboundDetour": [
        {
            "port": 6666,
            "listen": "127.0.0.1",
            "protocol": "http",
            "settings": {
                "auth": "noauth",
                "udp": true,
                "ip": "127.0.0.1"
            }
        }
    ],
    "outboundDetour": [
        {
            "protocol": "freedom",
            "settings": {},
            "tag": "direct"
        }
    ],
    "dns": {
        "servers": [
            "8.8.8.8",
            "8.8.4.4",
            "localhost"
        ]
    },
    "routing": {
        "strategy": "rules",
        "settings": {
            "domainStrategy": "IPIfNonMatch",
            "rules": [
                {
                    "type": "field",
                    "ip": [
                        "0.0.0.0/8",
                        "10.0.0.0/8",
                        "100.64.0.0/10",
                        "127.0.0.0/8",
                        "169.254.0.0/16",
                        "172.16.0.0/12",
                        "192.0.0.0/24",
                        "192.0.2.0/24",
                        "192.168.0.0/16",
                        "198.18.0.0/15",
                        "198.51.100.0/24",
                        "203.0.113.0/24",
                        "::1/128",
                        "fc00::/7",
                        "fe80::/10",
                        "geoip:cn"
                    ],
                    "domain": [
                        "geosite:cn"
                    ],
                    "outboundTag": "direct"
                },
                {
                    "type": "chinasites",
                    "outboundTag": "direct"
                },
                {
                    "type": "chinaip",
                    "outboundTag": "direct"
                }
            ]
        }
    }
`
最后是客户端配置
<img width="539" alt="2018-07-22 23 58 11" src="https://user-images.githubusercontent.com/27991177/43055553-c488510c-8e69-11e8-886b-3c731b835409.png">

老铁有空帮我看下问题所在啊，谢啦！

**Comment by 233boy** [comment]
@Coder-Chandler 
Transport Settings 里面的配置几下.... 
使用不了显然 很有可能是你的配置你有问题，或者你使用其他设备，例如 WIN 电脑 / Android 手机，使用 V2RayN / V2RayNG 测试一下。 😄

**Comment by blankcw** [comment]
DNS配置的地址有问题
![22222](https://user-images.githubusercontent.com/23013029/44654411-23256d00-aa24-11e8-998e-d4b26a3ed8aa.png)
需要用cloudflare的地址，在域名商处修改

**Comment by ikkyusan123** [comment]
本地socks监听端口用2333，HTTP端口用6666，试一下。
