### ISSUE TITLE
 tls: first record does not look like a TLS handshake

### ISSUE THREAD

**Issue by ChengEast** [233boy/v2ray#490]
我遇到这样的问题了。不知道如何处理呀？我是ws+tls+nginx
服务端：
{
	"log": {
		"access": "/var/log/v2ray/access.log",
		"error": "/var/log/v2ray/error.log",
		"loglevel": "warning"
	},
	"inbounds": [
		{
			"port": 888,
			"protocol": "vmess",
			"settings": {
				"clients": [
					{
						"id": "ssssssssss-ssss-ssss-sssss-sssssssssssssssss",
						"level": 1,
						"alterId": 233
					}
				]
			},
			"streamSettings": {
				"network": "ws",
                                "wsSettings":{
                                      "path":"/east"
                                 }
			},
			"sniffing": {
				"enabled": true,
				"destOverride": [
					"http",
					"tls"
				]
			}
		}
		//include_ss
		//include_socks
		//include_mtproto
		//include_in_config
		//
	],
	"outbounds": [
		{
			"protocol": "freedom",
			"settings": {
				"domainStrategy": "UseIP"
			},
			"tag": "direct"
		},
		{
			"protocol": "blackhole",
			"settings": {},
			"tag": "blocked"
        },
		{
			"protocol": "mtproto",
			"settings": {},
			"tag": "tg-out"
		}
		//include_out_config
		//
	],
	"dns": {
		"servers": [
			"https+local://1.1.1.1/dns-query",
			"1.1.1.1",
			"1.0.0.1",
			"8.8.8.8",
			"8.8.4.4",
			"localhost"
		]
	},
	"routing": {
		"domainStrategy": "IPOnDemand",
		"rules": [
			{
				"type": "field",
				"ip": [
					"0.0.0.0/8",
					"10.0.0.0/8",
					"100.64.0.0/10",
					"127.0.0.0/8",
					"169.254.0.0/16",
					"172.16.0.0/12",
					"192.0.0.0/24",
					"192.0.2.0/24",
					"192.168.0.0/16",
					"198.18.0.0/15",
					"198.51.100.0/24",
					"203.0.113.0/24",
					"::1/128",
					"fc00::/7",
					"fe80::/10"
				],
				"outboundTag": "blocked"
			},
			{
				"type": "field",
				"inboundTag": ["tg-in"],
				"outboundTag": "tg-out"
			}
			,
			{
				"type": "field",
				"domain": [
					"domain:epochtimes.com",
				],
				"outboundTag": "blocked"
			}			,
                {
                    "type": "field",
                    "protocol": [
                        "bittorrent"
                    ],
                    "outboundTag": "blocked"
                }
			,
                {
                    "type": "field",
                    "domain": [
                        "fr.a2dfp.net",
                        "www.winaproduct.com"
                    ],
                    "outboundTag": "blocked"
                }
			//include_rules
			//
		]
	},
	"transport": {
		"kcpSettings": {
            "uplinkCapacity": 100,
            "downlinkCapacity": 100,
            "congestion": true
        }
	}
}

nginx服务配置：
server {
    server_name  eastcheng.tk;
    ssl_certificate    /etc/letsencrypt/live/eastcheng.tk/fullchain.pem;
    ssl_certificate_key    /etc/letsencrypt/live/eastcheng.tk/privkey.pem;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
          error_page 497  https://$host$request_uri;

    location /east {
         proxy_pass       http://127.0.0.1:888;
         proxy_redirect             off;
         proxy_http_version         1.1;
         proxy_set_header Upgrade   $http_upgrade;
         proxy_set_header Connection "upgrade";
         proxy_set_header Host      $http_host;

         root   /usr/share/nginx/html;
         index  index.html index.htm;
    }

}
客户端配置：
{
      "configVersion": 2,
      "address": "eastcheng.tk",
      "port": 889,
      "id": "sssssss-ssss-ssss-ssss-ssssssssssss",
      "alterId": 233,
      "security": "auto",
      "network": "ws",
      "remarks": "myws",
      "headerType": "none",
      "requestHost": "eastcheng.tk",
      "path": "/east",
      "streamSecurity": "tls",
      "allowInsecure": "",
      "configType": 1,
      "testResult": "",
      "subid": ""
    }

本人小白，纯属搬砖，望大神指点，非常感谢！！

**Comment by ChengEast** [comment]
自己学习搞好了

**Comment by ContinentalWuhu** [comment]
> 自己学习搞好了
老铁怎么弄的啊？我也碰到这个问题了，ping的伪地址都没问题！
