### ISSUE TITLE
一键脚本在国内vps无法运行

### ISSUE THREAD

**Issue by xuyita1** [233boy/v2ray#491]

**Comment by zhz1237ok** [comment]
没看懂你想说什么，你不会把脚本复制到本地再移动进VPS安装吗，还是说安装过程有些东西下载不下来

**Comment by xuyita1** [comment]
谢谢答复，短链长链输进去回车无任何反应也不报错。
用官方go.sh下载一直都没速度 如图
![11](https://user-images.githubusercontent.com/27287904/74710480-1e322a00-5265-11ea-845c-b9f108c6535a.png)
<img width="1180" alt="22" src="https://user-images.githubusercontent.com/27287904/74710495-238f7480-5265-11ea-9a51-9f892fd4ecd0.png">

**Comment by zhz1237ok** [comment]
https://git.io/v2ray.sh

**Comment by zhz1237ok** [comment]
你不会本地下载好脚本移动进去吗

**Comment by zhz1237ok** [comment]
![image](https://user-images.githubusercontent.com/38283893/74711419-e627e880-525e-11ea-96f5-492515e20b62.png)
![image](https://user-images.githubusercontent.com/38283893/74711448-f5a73180-525e-11ea-998e-ac9962840b8d.png)
![image](https://user-images.githubusercontent.com/38283893/74711467-fc35a900-525e-11ea-8099-e59c2f89ae5e.png)
![image](https://user-images.githubusercontent.com/38283893/74711499-0d7eb580-525f-11ea-84f1-a78e3a8b8ec7.png)
然后FTP什么的移动到你的服务器，直接bash v2ray.sh就能运行了啊

**Comment by zhz1237ok** [comment]
如果脚本运行过程中无法下载一些东西，也有办法，就是挂个代理，但是本末倒置了，建议直接买搭好的回国梯子

**Comment by xuyita1** [comment]
666，谢谢老哥，尽管过程还是不顺利，还是谢谢了。

**Comment by xuyita1** [comment]
> 有解吗，百度云vps想开一个v2ray回国节点，github连不上
