### ISSUE TITLE
怎么改额外id（alterid）和路径呢

### ISSUE THREAD

**Issue by dgfrwx** [233boy/v2ray#493]

**Comment by dgfrwx** [comment]
默认额外id是233， 路径（path）是空的或者就这个/ ，怎么改啊？

**Comment by Javion-Zh** [comment]
修改v2ray配置文件

**Comment by ChengEast** [comment]
在终端模式下，输入v2ray,有中文菜单可以改这些的

**Comment by phlinhng** [comment]
`sudo vi /etc/v2ray/config.json`

**Comment by dgfrwx** [comment]
> 在终端模式下，输入v2ray,有中文菜单可以改这些的

中断模式是那个xshell黑黑的模式吧

**Comment by dgfrwx** [comment]
> `sudo vi /etc/v2ray/config.json`

怎在终端模式输入，这行代码，然后下一步呢？

**Comment by dgfrwx** [comment]
@phlinhng 怎在终端模式输入，这行代码，然后下一步呢？

**Comment by dgfrwx** [comment]
@Javion-Zh 额外id改不了

**Comment by dgfrwx** [comment]
@phlinhng 输入了你说的代码结果这样
root@vultr:~# sudo vi /etc/v2ray/config.json
-bash: sudo: command not found

**Comment by phlinhng** [comment]
> @phlinhng 输入了你说的代码结果这样
> root@vultr:~# sudo vi /etc/v2ray/config.json
> -bash: sudo: command not found
有些vps没有预装vim 需要先 `sudo apt install vim` (ubuntu/debian)

**Comment by manatsu525** [comment]
> @phlinhng 输入了你说的代码结果这样
> root@vultr:~# sudo vi /etc/v2ray/config.json
> -bash: sudo: command not found

你已经是root用户了就不需要sudo了

**Comment by dgfrwx** [comment]
@Javion-Zh debian9系统好像不能修改配置文件啊怎么修改

**Comment by manatsu525** [comment]
> @Javion-Zh debian9系统好像不能修改配置文件啊怎么修改

如果你用的这个脚本装的v2ray，那配置文件和官方的有些不同，你可以直接用v2ray config命令然后按照提示改路径，用v2ray ai命令然后根据提示改alterId，当然你也可以直接修改配置文件比较麻烦，就是/etc/v2ray/目录下的三个文件，其中两个是配置文件，那个带backup的本来是备份文件但被作者用来作为脚本中v2ray info的输出内容了，建议三个都改

**Comment by liuqianghui** [comment]
使用本命令行的脚本，可以直接使用 v2ray ai 就有中文提示修改了
