### ISSUE TITLE
centos7 caddy 无法启动

### ISSUE THREAD

**Issue by jackrong** [233boy/v2ray#495]
运行完安装脚本，发现caddy无法启动。查看caddy log 如下。望大神帮忙看一下。多谢了！
[root@v136628 ~]# v2ray status

 V2Ray 状态: 正在运行  /  Caddy 状态: 未在运行

[root@v136628 ~]# systemctl status caddy.service -l
● caddy.service - Caddy HTTP/2 web server
   Loaded: loaded (/usr/lib/systemd/system/caddy.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2020-02-19 22:24:44 CST; 34s ago
     Docs: https://caddyserver.com/docs
  Process: 2055 ExecStart=/usr/local/bin/caddy -log stdout -log-timestamps=false -agree=true -conf=/etc/caddy/Caddyfile -root=/var/tmp (code=exited, status=1/FAILURE)
 Main PID: 2055 (code=exited, status=1/FAILURE)

Feb 19 22:24:41 v136628.kvm.u57759 caddy[2055]: 2020/02/19 22:24:41 [INFO] [cs.max20s.xyz] acme: Trying to solve HTTP-01
Feb 19 22:24:42 v136628.kvm.u57759 caddy[2055]: 2020/02/19 22:24:42 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/2901013013
Feb 19 22:24:42 v136628.kvm.u57759 caddy[2055]: 2020/02/19 22:24:42 [INFO] Unable to deactivate the authorization: https://acme-v02.api.letsencrypt.org/acme/authz-v3/2901013013
Feb 19 22:24:42 v136628.kvm.u57759 caddy[2055]: [ERROR][cs.max20s.xyz] failed to obtain certificate: acme: Error -> One or more domains had a problem:
Feb 19 22:24:42 v136628.kvm.u57759 caddy[2055]: [cs.max20s.xyz] acme: error: 400 :: urn:ietf:params:acme:error:connection :: Fetching http://cs.max20s.xyz/.well-known/acme-challenge/O1WwZweWWyTimc67qg3a7bnAzfg0vPwnKc8zH6fl2-I: Error getting validation data, url: (attempt 2/3; challenge=http-01)
Feb 19 22:24:43 v136628.kvm.u57759 caddy[2055]: 2020/02/19 22:24:43 [INFO] [cs.max20s.xyz] acme: Obtaining bundled SAN certificate
Feb 19 22:24:43 v136628.kvm.u57759 caddy[2055]: [ERROR][cs.max20s.xyz] failed to obtain certificate: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/, url: (attempt 3/3; challenge=http-01)
Feb 19 22:24:44 v136628.kvm.u57759 systemd[1]: caddy.service: main process exited, code=exited, status=1/FAILURE
Feb 19 22:24:44 v136628.kvm.u57759 systemd[1]: Unit caddy.service entered failed state.
Feb 19 22:24:44 v136628.kvm.u57759 systemd[1]: caddy.service failed.

**Comment by jackrong** [comment]
试了https://www.moerats.com/archives/900/。也不行

[root@v136628 ~]# caddy -conf Caddyfile
2020/02/19 22:30:04 Caddyfile:2 - Error during parsing: Unknown directive 'dns'

**Comment by Hzy0913** [comment]
有推荐使用哪个系统吗？ 完全按照流程试了一遍 caddy 一直未运行

**Comment by keylin1105** [comment]
修改防火墙，详见 [https://www.centlinux.com/2019/10/install-caddy-web-server-on-centos-7.html ](url)

**Comment by oyange** [comment]
相同的问题，楼主解决了嘛
