### ISSUE TITLE
香港阿里云,Ubuntu18经常出现SYN_RECV,无法使用

### ISSUE THREAD

**Issue by shpxhk** [233boy/v2ray#497]
tcp6       0      0 :::58220                :::*                    LISTEN      5872/v2ray          
tcp6       0      0 172.17.38.173:58220     120.84.9.180:32643      SYN_RECV    -

**Comment by Moac1129** [comment]
今年香港阿里云还没到期我就释放掉选择退款了，国内ping不通，SSH连不上，我也没怎么频繁的使用。后来换到腾讯云的香港服务器了，还是依然香，价格都一样。
