### ISSUE TITLE
unable to set read deadline 

### ISSUE THREAD

**Issue by houyuehai** [233boy/v2ray#499]
大佬们。我搭建完了之后。有时候能连上有时候又不能。
我看访问日志里面能看到
2020/02/23 10:16:20 udp:61.140.95.163:32338 accepted tcp:translate.google.com:443 [direct]
2020/02/23 10:16:21 udp:61.140.95.163:32338 accepted tcp:clients1.google.com:443 [direct]
2020/02/23 10:16:42 udp:61.140.95.163:32340 accepted tcp:clients1.google.com:443 [direct]
2020/02/23 10:16:49 udp:61.140.95.163:32340 accepted tcp:clients1.google.com:443 [direct]
2020/02/23 10:16:50 udp:61.140.95.163:32340 accepted tcp:clients1.google.com:443 [direct]
但是从错误日志里面看到这个：
[Warning] [605598460] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: unable to set read deadline > v2ray.com/core/transport/internet/kcp: Connection closed.
请问这是什么原因呢？

**Comment by kanglu0831** [comment]
我也是。。

**Comment by Rover1998** [comment]
我也是报这个错误，但是并不影响使用，蹲一个大佬

**Comment by VORhea** [comment]
同问
