### ISSUE TITLE
服务器更换IP之后的配置问题

### ISSUE THREAD

**Issue by songxinhua** [233boy/v2ray#5]
大佬，之前的IP被墙了，然后通过申请了浮动IP换了一个，同一个服务器上面的ssr可以直接换IP使用，这个V2ray怎么修改可以让客户机使用新的IP连接。脚本中给出的配置文件还是原来的IP，多谢大佬解答

**Comment by 233boy** [comment]
@songxinhua 
客户端直接用新的 IP 不能使用吗？我不太清楚你的原因，脚本并没有绑定什么 IP 之类的东西，或者你重装一下吧

**Comment by songxinhua** [comment]
直接用新IP的时候不能使用，重装脚本之后还是显示的以前的IP，因为这个原来的ip地址并没有解绑，只是增加上一个新的

**Comment by 233boy** [comment]
@songxinhua 
那我真的不清楚了，脚本获取到的 IP 是 VPS 去请求 ipinfo.io/ip 得到的 IP，
或者，既然都申请了新的 IP 了，让商家给你绑定上新的吧

**Comment by songxinhua** [comment]
嗯嗯，我再去试试，多谢

**Comment by 233boy** [comment]
@songxinhua 
不客气
