### ISSUE TITLE
手机能使用，电脑不能使用

### ISSUE THREAD

**Issue by a7611818** [233boy/v2ray#50]
同样的服务器，同样的配置文件，手机我用的是BifrostV，pc我用的是v2rayN，在pc端失败之后，我更正

了服务端的系统时间，更新客户端上的v2rayN和v2raycore还是没用，是不是服务端系统的问题？之前我

用的centos7，手机和pc都可以用，只是不稳定。现在我服务端的系统是debian8。

下面是我v2rayN客户端测速时候的错误日志

--------------------------------远程服务器返回错误: (500) 内部服务器错误。[15:40:10]--------------------------------
System.Net.WebException: 远程服务器返回错误: (500) 内部服务器错误。
   在 v2rayN.Handler.V2rayUpdateHandle.ws_DownloadFileCompleted(Object sender, AsyncCompletedEventArgs e)

**Comment by a7611818** [comment]
解决了，pc端上面要设置本地监听端口我没去设置

**Comment by zlrs** [comment]
我也遇到500. 不过是由于 serverside 未开放v2ray端口
