### ISSUE TITLE
 浏览器输入域名后无法打开网站

### ISSUE THREAD

**Issue by DeathInTheAir** [233boy/v2ray#500]
安装完成后，配置可以上油管了。

但是我的域名打不开网站，不是应该打开安装时指定的跳转网站或者代理服务器的默认网站吗？

如果打不开是不是代表着伪装不成功，会被发现封ip呢？

有人安装完能打开域名网站吗

**Comment by baoyuangui** [comment]
是因为服务器的配置没有指定根目录的网页吗，

**Comment by ChengEast** [comment]
是的，要重新配置相应的conf文件。改里面的root 后面那个路径，指向对应的index.html的存放文件夹

**Comment by phlinhng** [comment]
脚本只能设定跳转到别的网站，要打开自己的网站需要手动配置TLS。

**Comment by baoyuangui** [comment]
> 脚本只能设定跳转到别的网站，要打开自己的网站需要手动配置TLS。

我重新安装脚本，不指定跳转网站(使用默认的)，就可以打开它默认的网页了。但是如果安装时指定了一个跳转网站，之后通过域名是不能跳转到我指定的网站的。感觉是不是这里指定网站后，caddy的配置脚本没做好
