### ISSUE TITLE
Cloudflare CDN的证书，续签时需要手动点灰云朵吗

### ISSUE THREAD

**Issue by phlinhng** [233boy/v2ray#501]
目前用Websocket +TLS的模式，配置先把CF云朵点灰，然后用脚本自动申请SSL证书后再把云朵点亮，连线没有问题。那90天后证书到期前需要再手动点灰一次让Caddy续签吗？还是要搭配Caddy的`tls.dns.cloudflare` plugin使用？

**Comment by phlinhng** [comment]
我找到解答了，教程在这：https://www.cylindric.net/web/caddyserver-and-cloudflare

**Comment by Carnia** [comment]
1. 如果使用[DNS-01 校验方式签发证书](https://imroc.cc/kubernetes/trick/certs/sign-free-certs-with-cert-manager.html#dns-01-%E6%A0%A1%E9%AA%8C%E6%96%B9%E5%BC%8F%E7%AD%BE%E5%8F%91%E8%AF%81%E4%B9%A6)，则和cloudflare的cdn无关。
2. 如果是用[HTTP-01 校验方式签发证书](https://imroc.cc/kubernetes/trick/certs/sign-free-certs-with-cert-manager.html#http-01-%E6%A0%A1%E9%AA%8C%E6%96%B9%E5%BC%8F%E7%AD%BE%E5%8F%91%E8%AF%81%E4%B9%A6)，则需要确保cloudflare设置如下几点：
 - 关闭“始终https”和“自动https重写”
 - 不启用HSTS
 - 并且SSL/TLS模式为“完全（full）”
这样你可以开着cdn续签，但是得注意cloudflare的cdn只会代理特定端口的流量，见https://developers.cloudflare.com/fundamentals/get-started/reference/network-ports/
