### ISSUE TITLE
谷歌云ws+tls都正常，但总会时不时的断

### ISSUE THREAD

**Issue by ghost** [233boy/v2ray#502]
谷歌云ws+tls都正常，但是总是会是不是的断，ping服务器ip或者解析的域名会断，但是一会就回好，延迟40多ms，一般ping到100多就快断了，看油管也是，最快峰值能到20万，但是就是时不时的断很难受，求个明白人给指点一下，如果ip被墙应该ping不通才对啊

**Comment by ChengEast** [comment]
我和你一样的情况，不论用V2ray还是Trojan都一样，我感觉是墙高了。干扰严重。不知道有没有别的办法

**Comment by sunyigao888** [comment]
嗯,看看有没有其他大手子能出个解决办法

**Comment by doKill** [comment]
作者不是在文章里写的有么，这就是ws+tls的尿性

**Comment by sunyigao888** [comment]
作者的文档看了, 但是没看到哪里有写, 那我换个其他的协议就好了, 看好多人都推荐ws+tls
其他协议哪个比较稳啊 H2还是tcp+H2

**Comment by doKill** [comment]
> 作者的文档看了, 但是没看到哪里有写, 那我换个其他的协议就好了, 看好多人都推荐ws+tls
> 其他协议哪个比较稳啊 H2还是tcp+H2

https://github.com/233boy/v2ray/wiki/V2Ray%E6%90%AD%E5%BB%BA%E8%AF%A6%E7%BB%86%E5%9B%BE%E6%96%87%E6%95%99%E7%A8%8B#websocket--tls

**Comment by sunyigao888** [comment]
嗯看见了  直接tcp吧

**Comment by sunyigao888** [comment]
这个文档之前是看过  但是没看到最下面  尴尬
