### ISSUE TITLE
想看某些的网站，但是本脚本好像屏蔽了，怎么解禁？

### ISSUE THREAD

**Issue by dgfrwx** [233boy/v2ray#504]

**Comment by Alvin9999** [comment]
你可以使用vim /etc/v2ray/config.json找到那一排domain*并删除它们，之后重启

**Comment by dgfrwx** [comment]
在xshell终端模式模式下 vim /etc/v2ray/config.json得到下面这个不知道怎么删除。


自由上网 <notifications@github.com> 于2020年2月25日周二 下午7:04写道：

**Comment by Alvin9999** [comment]
网上搜索一下vim的使用方法

**Comment by zhz1237ok** [comment]
可以使用ftp类软件比如winscp，直接把config.json配置下载到本地，编辑修改后再覆盖移动到服务器上

**Comment by dgfrwx** [comment]
@zhz1237ok 编辑修改哪一段？

**Comment by 1102569977** [comment]
我找到了方法了，但是发现网站很不友好！选择不公布修改方法！爱国是一个中国公民最基本的品德与底线！

**Comment by 1102569977** [comment]
我选择不修改，并继续屏蔽！

**Comment by Himalaya2020** [comment]
自由就是自由，神圣不可侵犯
                      {
				"type": "field",
				"domain": [
					"domain:你想屏蔽的域名",
					"domain:比如360.com"
				],
				"outboundTag": "blocked"
			}
这部分

**Comment by steve3ussr** [comment]
看了一下，貌似都是轮子系列网站？

**Comment by recolic** [comment]
有一个其他人做的fork可以解决这个问题的： https://github.com/rootmelo92118/v2ray-edit-from-233boy
