### ISSUE TITLE
第一次用谷歌云搭建VPS，可以连接服务器但是无法打开网页

### ISSUE THREAD

**Issue by hyfneo** [233boy/v2ray#506]
使用软件可以正常建立与vps的连接，跑数据的时候一直跑不通。
防火墙端口已经打开。时间已经同步到上海。
报错信息如下
2020/02/26 11:58:13 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 我的ip与端口号: i/o timeout] > v2ray.com/core/common/retry: all retry attempts failed
请指教。
谢谢！

**Comment by cuserdzy** [comment]
一样的问题，离谱
