### ISSUE TITLE
ws TLS

### ISSUE THREAD

**Issue by abc-123-sudo** [233boy/v2ray#508]
请问一下233脚本的ws tls是不是有什么问题，我使用ws tls安装后使用v2ray status查看v2ray和Caddy状态，一开始v2ray和Caddy都显示正在运行，但是很快Caddy就显示未运行。我重启服务甚至重启VPS也是一样的，也是v2ray和Caddy都显示正在运行但几分钟后Caddy就显示未运行了，这是什么情况？是脚本问题吗

**Comment by 1102569977** [comment]
+1我也出现了这个问题！

**Comment by abc-123-sudo** [comment]
> +1我也出现了这个问题！

我听别人说是系统问题，你换成Debain 9在试试，我现在没有VPS了，你能不能用Debain 9再试一下，我想知道这样还有没有问题

**Comment by lixworth** [comment]
> > +1我也出现了这个问题！
> 
> 我听别人说是系统问题，你换成Debain 9在试试，我现在没有VPS了，你能不能用Debain 9再试一下，我想知道这样还有没有问题

我在ct7上出现此问题 之后切换到debain9 可以成功使用 没有问题了

**Comment by abc-123-sudo** [comment]
> > > +1我也出现了这个问题！
> > 
> > 
> > 我听别人说是系统问题，你换成Debain 9在试试，我现在没有VPS了，你能不能用Debain 9再试一下，我想知道这样还有没有问题
> 
> 我在ct7上出现此问题 之后切换到debain9 可以成功使用 没有问题了

看来的确是系统问题，我在Centous 7一直有这样的问题但是我没有在Debain 9试过这个脚本，你在Debain 9试了没有问题，那我下次也装Debain 9
