### ISSUE TITLE
关于某些封禁网站的问题

### ISSUE THREAD

**Issue by liups233** [233boy/v2ray#512]
脚本的编写者你好。我不是轮子，也不信仰什么宗教，但我认为在脚本中封禁某些网站是不好的，互联网是自由的。如果可以，希望能增加一个没有封禁网站的脚本，谢谢。

**Comment by 1102569977** [comment]
拒绝！你知道屏蔽的是啥吗？法伦，九评，其他都没有屏蔽！

**Comment by Papersman** [comment]
安装完之后自己编辑一下config.json不就行了

**Comment by lrpli** [comment]
开源项目自己编辑啊 自己就能解决的事情。。

**Comment by recolic** [comment]
有一个其他人做的fork可以解决这个问题的： https://github.com/rootmelo92118/v2ray-edit-from-233boy
