### ISSUE TITLE
v2ray脚本ws+tls问题！

### ISSUE THREAD

**Issue by 1102569977** [233boy/v2ray#517]
[警告]未能处理mux客户端连接>v2ray.com/core/proxy/vmess/outbound:未能找到可用的目标>v2ray.com/core/common/retry:[v2ray.com/core/transport/internet/websocket:未能拨入websocket>v2ray.com/core/transport/internet/websocket:未能拨入（wss://这里是域名+分流）：404未找到>websocket:握手错误]>v2ray.com/core/common/retry:所有重试尝试均失败！

[Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://这里是我的域名+分流): 404 Not Found > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed

**Comment by 1102569977** [comment]
当我关闭多路复用，报错！
[警告][777924408]v2ray.com/core/app/proxyman/outbound:未能处理出站流量>v2ray.com/core/proxy/vmess/outbound:未能找到可用的目标>v2ray.com/core/common/retry:[v2ray.com/core/transport/internet/websocket:未能拨号到websocket>v2ray.com/core/transport/internet/websocket:未能拨号到（wss://域名+分流:301已永久移动>websocket:bad handshake v2ray.com/core/transport/internet/websocket:failed to dial websocket>v2ray.com/core/transport/internet/websocket:failed to dial to（wss://域名+分流）：>拨号tcp:操作已取消]>v2ray.com/core/common/retry:所有重试尝试均失败！

[Warning] [777924408] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://域名+分流): 301 Moved Permanently > websocket: bad handshake v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://域名+分流):  > dial tcp: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed

**Comment by 233boy** [comment]
@1102569977 
你套 CF 了吧，在 SSL/TLS 那里选择 `Full`

`Your SSL/TLS encryption mode is Full`

**Comment by LULI6666666** [comment]
> @ 1102569977
> 你套CF了吧，在SSL / TLS那里选择`Full`
> 
> `Your SSL/TLS encryption mode is Full`

楼上大佬你说得啥意思 我也是一直跟他一样情况 一直用不了v2

**Comment by NBCR7** [comment]
> @1102569977 你套 CF 了吧，在 SSL/TLS 那里选择 `Full`
> 
> `Your SSL/TLS encryption mode is Full`
🙇‍，感谢 ，亲测有用
