### ISSUE TITLE
archlinux 下客户端无法打开

### ISSUE THREAD

**Issue by ZeR0ll** [233boy/v2ray#52]
在两个月前用过linux的客户端，记得当时可以正常使用，但是现在从Pacman安装v2ray之后
v2ray -config /etc/v2ray/config.json 提示如下错误：

V2Ray 3.32 (die Commanderin) Custom
A unified platform for anti-censorship.
Main: failed to read config file: /etc/v2ray/config.json > Main|Json: failed to execute v2ctl to convert config file. > Command|Platform|CtlCmd: failed to execute v2ctl: Ext|Tools|Conf|Command: failed to parse json config > Ext|Tools|Conf|Serial: failed to parse json config > Ext|Tools|Conf: invalid field rule > Ext|Tools|Conf: failed to load geosite: CN > Ext|Tools|Conf: failed to open file: geosite.dat > open /usr/bin/geosite.dat: no such file or directory
请问一下是什么原因？

**Comment by ZeR0ll** [comment]
服务器上的脚本装了好久了，是因为版本不匹配吗？

**Comment by TrizontiBaL6** [comment]
尝试用v2ray官方提供的linux安装脚本安装v2ray:
`bash <(curl -L -s https://install.direct/go.sh)`
