### ISSUE TITLE
为什么电脑版xshell 和手机版juicessh不能兼容？

### ISSUE THREAD

**Issue by dgfrwx** [233boy/v2ray#520]
同一个ip在xshell上搭建v2ray，juicessh就不能打开，在juicessh上搭建，xshell就打不开

**Comment by dgfrwx** [comment]
虽然已经习惯了用juicessh搭建v2ray但有时有些东西在电脑上修改快些，但似乎两者不兼容，那位大神帮忙解答？

**Comment by zhz1237ok** [comment]
换成termius，电脑版手机版都有
