### ISSUE TITLE
新脚本安装bbr时不能选版本，导致安装出错

### ISSUE THREAD

**Issue by johnshen007** [233boy/v2ray#521]

**Comment by 233boy** [comment]
@johnshen007 
你是说 v2ray bbr 的时候，选择安装那个场景吗

**Comment by johnshen007** [comment]
是的





------------------ 原始邮件 ------------------
发件人: 233boy <notifications@github.com&gt;
发送时间: 2020年3月13日 10:58
收件人: 233boy/v2ray <v2ray@noreply.github.com&gt;
抄送: johnshen007 <1164749219@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[233boy/v2ray] 新脚本安装bbr时不能选版本，导致安装出错 (#521)





 
@johnshen007
 你是说 v2ray bbr 的时候，选择安装那个场景吗

**Comment by johnshen007** [comment]
是的，我记得好像用v2ray4.19版本选装bbr.还可以选bbr版本来着



---原始邮件---
发件人: "233boy"<notifications@github.com&gt;
发送时间: 2020年3月13日(周五) 上午10:58
收件人: "233boy/v2ray"<v2ray@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"johnshen007"<1164749219@qq.com&gt;;
主题: Re: [233boy/v2ray] 新脚本安装bbr时不能选版本，导致安装出错 (#521)




 
@johnshen007
 你是说 v2ray bbr 的时候，选择安装那个场景吗
