### ISSUE TITLE
通过cloudflare中转后，为何还能直接显示vps的IP地址？

### ISSUE THREAD

**Issue by glovanni** [233boy/v2ray#523]
安装v2ray一键脚本后，通过配置cloudflare实现流量中转，在cloudflare中正确设置了A记录，也打开了代理的开关，通过ping域名也发现解析的是cloudflare给出的IP地址，上网一切正常。
但为何v2rayN设置全局模式的情况下，通过ip138.net ipip.net/ip.html等方式还是能直接看到vps的真实地址呢？

**Comment by devinstever** [comment]
因为要用vps做出口你才能翻墙。
cdn在其中充当的是中转站的作用，连接会在cdn服务器中转后再发送到vps出去。
你现在连接的ip并不是vps的ip，但是访问网站还需要转发到vps出去才能访问。

**Comment by MoonLord-LM** [comment]
楼上正解，CF 只是中转，最终的请求是从 VPS 出去的，网站能检测到的也就是这个 IP

**Comment by fullofstar** [comment]
我一开始套cdn居然目标网站识别出来我的ip也不是真实ip。。。不知道为什么
现在正常了，cdn只是中转下，目标网站能拿到我真实的vps的ip
