### ISSUE TITLE
大家WS+TLS+CDN速度都多少?

### ISSUE THREAD

**Issue by ssmnr** [233boy/v2ray#527]
为什么我的速度只有200kb?搬瓦工的机子

**Comment by pleaseRedo** [comment]
你把CDN关了，换加密模式看看会不会上去。公司300M宽带关了cf的cdn从4M上到30多M...至少能用了吧

**Comment by Xiaolv-9834** [comment]
我也是，用CDN慢很多的感觉

**Comment by doKill** [comment]
CDN便宜的慢，收费的又贵又要个人信息，自行取舍咯

**Comment by underlaw** [comment]
cf的比以前慢很多了
