### ISSUE TITLE
大神什么时候可以更新一下脚本呀

### ISSUE THREAD

**Issue by lookfeeb** [233boy/v2ray#528]
什么时候可以更新一下脚本修复一下bug，偶尔会出现断流情况。

**Comment by young1023x2** [comment]
我也想问大佬啥时候出TROJAN 和 V2RAY多合一脚本，在一台服务器装两个有点麻烦，端口重视冲突，把TROJAN端口换成8080和80可以用了，但233的WS+TLS怎么都用不了，应该是80端口冲突，但不会改，真麻烦啊

**Comment by freedomwebcn** [comment]
> 我也想问大佬啥时候出TROJAN 和 V2RAY多合一脚本，在一台服务器装两个有点麻烦，端口重视冲突，把TROJAN端口换成8080和80可以用了，但233的WS+TLS怎么都用不了，应该是80端口冲突，但不会改，真麻烦啊

你可以试着在docker中安装torjan 和 V2
