### ISSUE TITLE
Windows和IOS可以使用，安卓上面v2rayNG,BifrostV,Actinium三个软件都试了连接不上

### ISSUE THREAD

**Issue by gujiniCY** [233boy/v2ray#53]
Windows和IOS可以使用，安卓上面v2rayNG,BifrostV,Actinium三个软件都是了连接不上，点击链接的按钮，没反应，手机为坚果Pro2，安卓7.1.1

**Comment by herexf** [comment]
我手机上shadowsocks可以，v2ray扫了二维码也是连不上，，
晚上回去试试电脑看。

**Comment by gujiniCY** [comment]
我这个已经解决了，莫名其妙的就好了。
遇到了一个新的问题，两台电脑一台win10v2rayN可以正常使用，但是另一台win7扫描上去还是上不了外网，网上查找，有个博主说是GHO系统的原因

**Comment by herexf** [comment]
好像我的也好了，估计需要点时间…

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
