### ISSUE TITLE
谷歌云，ws+tls，电信 联通没有问题，移动龟速是什么原因？？

### ISSUE THREAD

**Issue by TheClown0** [233boy/v2ray#531]

**Comment by TheClown0** [comment]
![image](https://user-images.githubusercontent.com/32888355/77026565-ea1a6800-69ce-11ea-91ec-a3045d9e0375.png)
![image](https://user-images.githubusercontent.com/32888355/77026611-08806380-69cf-11ea-8b2a-7cef211cd78d.png)

**Comment by devinstever** [comment]
线路不行。与工具无关。
现在移动无论什么线路，丢包率都极其的严重，除非能找到适合移动的线路，否则将永远无法解决此问题。
