### ISSUE TITLE
我知道长城宽带是垃圾，但是哪一个配置最好？

### ISSUE THREAD

**Issue by alcatraz-zz** [233boy/v2ray#533]
长城宽带和v2ray还没超softether l2tp的速度。有没有人v2r和长城成功了吗？什么配置？谢谢

**Comment by doKill** [comment]
一路回车，不然本来就网速不行你还套各种协议参数连在出租屋逛P站都卡，努力赚钱换电信吧

**Comment by lrpli** [comment]
换联通绝对能解决你的问题
