### ISSUE TITLE
怎么我下了个v2ray-3.05的ZIP文件夹不能安装

### ISSUE THREAD

**Issue by echo860** [233boy/v2ray#536]
不好意思我是第一次在GITHUB下文件，这个下的ZIP文件夹解压后，里面没有EXE安装文件，
谁问你们是怎么安装的？

**Comment by zhz1237ok** [comment]
you pick the wrong door 到别的地方去下，这里只有脚本

**Comment by echo860** [comment]
> you pick the wrong door 到别的地方去下，这里只有脚本

麻烦帮我找个，我对电脑是一窍不通。我要windowns版的
