### ISSUE TITLE
v2ray  cloudflare 原先可以连接， VPS 换ip  后无法连接

### ISSUE THREAD

**Issue by eromoe** [233boy/v2ray#537]
请问要如何解决？
我已经去 cloudflare  把 ip 改成新的ip了

**Comment by devinstever** [comment]
再次确认一下，记录是不是填写正确？
如果确认记录填写正确的话那就可能是vps上的服务没有启动，需要使用ssh登录后执行命令启动。

**Comment by eromoe** [comment]
确认了 cloudflare  刷新太慢。。。
