### ISSUE TITLE
无法升级core到最新版本

### ISSUE THREAD

**Issue by joostshao** [233boy/v2ray#538]
无法升级core到最新版本

**Comment by itheabyss** [comment]
我也是，点升级说有新版本，升完还是4.22.1，再点升级就说木有新版本了。

**Comment by zhz1237ok** [comment]
最新稳定版不就是4.22.1，测试版的4.25你可以自己手动下载解压覆盖

**Comment by 233boy** [comment]
@joostshao @itheabyss 
先使用 `v2ray U` 更新脚本再试试看！

**Comment by itheabyss** [comment]
> @joostshao @itheabyss
> 先使用 `v2ray U` 更新脚本再试试看！

哈哈，本来我用自己改的那个download脚本已经更新到4.23了，更新脚本后，再更新主程序，又回到4.22.1了

**Comment by joostshao** [comment]
谢谢老板
