### ISSUE TITLE
说下怎么用脚本升级到最新版

### ISSUE THREAD

**Issue by itheabyss** [233boy/v2ray#540]
这个脚本默认只支持升级稳定版，预览版地址不一样，所以导致升不了级。对脚本做一点更改，可以升级最新版本，无论是什么版。

1. 找到这个目录：/etc/v2ray/233boy/v2ray/src，
2. vi download-v2ray.sh，第一行就是：
`_get_latest_version() {
	v2ray_latest_ver="$(curl -H 'Cache-Control: no-cache' -s https://api.github.com/repos/v2ray/v2ray-core/releases/latest | grep 'tag_name' | cut -d\" -f4)"`

把网址最后的`/lastest`删掉，这个是稳定版的网址，去掉这个是所有版本的地址。最后在f4后面加上一个awk命令取最新版的版本号，不加的话会取到无数个版本号，导致无法下载。修改后的这行如下，可以直接贴进去：
`_get_latest_version() {
	v2ray_latest_ver="$(curl -H 'Cache-Control: no-cache' -s https://api.github.com/repos/v2ray/v2ray-core/releases | grep 'tag_name' | cut -d\" -f4 | awk 'NR==1')"`

以上可以更新到最新版本了，如果只想更新到稳定版，可以把/latest加上去。

**Comment by 233boy** [comment]
默认脚本是只支持更新最新版本的，避免预览版有一些错误！

**Comment by binyzheng** [comment]
取列的方式有可能取错位置，还是用正则表达式匹配会更靠谱些，可以修改成
```
v2ray_latest_ver="$(curl -H 'Cache-Control: no-cache' -s https://api.github.com/repos/v2ray/v2ray-core/releases/latest | awk '{match($0,/.*tag_name[^:]*[^"]*"([^"]*)/,a);print a[1]}')"
```

**Comment by 233boy** [comment]
> 取列的方式有可能取错位置，还是用正则表达式匹配会更靠谱些，可以修改成
> `v2ray_latest_ver="$(curl -H 'Cache-Control: no-cache' -s https://api.github.com/repos/v2ray/v2ray-core/releases/latest | awk '{match($0,/.*tag_name[^:]*[^"]*"([^"]*)/,a);print a[1]}')"`

其实之前出现那个问题是 Github 他们的原因，grep 搜索出来貌似也没有什么不妥，凑合用 😂
