### ISSUE TITLE
v2ray显示未在运行

### ISSUE THREAD

**Issue by colourful-f** [233boy/v2ray#541]
xshell上显示v2ray未在运行

**Comment by 233boy** [comment]
@colourful-f 
使用 v2ray config 更改一下端口。

**Comment by colourful-f** [comment]
现在显示可以运行，就是把那个节点剪切到v2ray客户端添加后，用不了，翻不了墙
是不是跟重装了服务器系统有关

233boy <notifications@github.com> 于2020年3月25日周三 下午10:22写道：

**Comment by 233boy** [comment]
@colourful-f 
这个有太多原因了，推荐你看看客户端的 LOG 都显示什么，然后排错一下

**Comment by colourful-f** [comment]
太难了，小白上手浪费了一天时间



233boy <notifications@github.com> 于2020年3月25日周三 下午10:29写道：

**Comment by 233boy** [comment]
@colourful-f 
你什么 VPS 啊，要是国际大厂，GCP、AZURE、AWS、阿里国际等，这些得开放防火墙才行

**Comment by gzshasha** [comment]
你的服务器系统环境内核什么都不说，作者的脚本适用于X86-64的，内核的话应该4.1以上都行。
