### ISSUE TITLE
客户端对接问题，感谢！

### ISSUE THREAD

**Issue by worldofidea** [233boy/v2ray#542]
一键安装v2ray没报错，到caddy最后一步有4个红色警告
【info】firewall set start...
Warning:NOT_ENABLED:443:tcp
Warning:NOT_ENABLED:80:tcp
Warning:NOT_ENABLED:10086:tcp
Warning:NOT_ENABLED:10086:udp
装完后实测地址能连，伪装网站也正常，就是客户端连接不上，信息为：
` [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)`

**Comment by 233boy** [comment]
@worldofidea 
把 MUX 关了看看

**Comment by worldofidea** [comment]
> @worldofidea
> 把 MUX 关了看看

请教大哥，怎么关？
我是小白-_-#谢谢！

**Comment by worldofidea** [comment]
找到教程了，谢谢大哥，我研究下去

**Comment by worldofidea** [comment]
大佬好，我把所涉及到的错误信息整理了一下，烦请麻烦看一下，我愿付费求教，不想这么麻烦你，谢谢！
1、caddy安装错误信息
`Mar 25 22:40:37 v2rayhk04 caddy[9029]: [INFO] Caddy version: v1.0.4
Mar 25 22:40:37 v2rayhk04 caddy[9029]: Activating privacy features... [INFO][cache:0xc00008e820] Started certificate
Mar 25 22:40:37 v2rayhk04 caddy[9029]: done.
Mar 25 22:40:37 v2rayhk04 caddy[9029]: [WARNING] TLS disabled for http://test.cccray.xyz
Mar 25 22:40:37 v2rayhk04 caddy[9029]: Serving HTTP on port 80
Mar 25 22:40:37 v2rayhk04 caddy[9029]: http://test.cccray.xyz
Mar 25 22:40:37 v2rayhk04 caddy[9029]: [INFO] Serving http://4.cc2cc.xyz
Mar 25 22:40:37 v2rayhk04 caddy[9029]: Serving HTTPS on port 443
Mar 25 22:40:37 v2rayhk04 caddy[9029]: https://test.cccray.xyz
Mar 25 22:40:37 v2rayhk04 caddy[9029]: [INFO] Serving https://test.cccray.xyz
`
`2、客户端未关闭MUX的错误信息
2020/03/25 22:44:39 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://test.cccray.xyz:10087/game):  > dial tcp 314.92.229.158:10087: connectex: No connection could be made because the target machine actively refused it. v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://test.cccray.xyz:10087/game):  > dial tcp 314.92.229.158:10087: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://test.cccray.xyz:10087/game):  > dial tcp 314.92.229.158:10087: connectex: No connection could be made because the target machine actively refused it.] > 
`
3、客户端关闭MUX后的错误信息
failed to dial to (wss://test.cccray.xyz:10087/game):  > dial tcp 314.92.229.158:10087: operation was canceled v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://test.cccray.xyz:10087/game):  > dial tcp: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed
2020/03/25 22:51:19 [Warning] [1484861459] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://test.cccray.xyz:10087/game):  > dial tcp 314.92.229.158:10087: operation was canceled v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/web
‘
以上是我反复安装总结出来的错误信息，系统是centos7，端口也全部开放了，实在搞不懂是怎么回事，我太菜了。

**Comment by 233boy** [comment]
@worldofidea 
你配置写错了，，端口是 443，不是10087

**Comment by worldofidea** [comment]
谢谢大佬，搞定了，我好蠢！
