### ISSUE TITLE
caddy 配置

### ISSUE THREAD

**Issue by zlf4865231** [233boy/v2ray#544]
想知道各位大佬caddy配置文件是怎么配置的...有大佬能发一份看看吗？
/sites里面是二级域名的吗？就是部署一个简单的网页在自己域名上要怎么处理啊...我看了下caddy的配置是指向某个目录就可以了吗？

**Comment by zlf4865231** [comment]
...性感小白 在线求教

**Comment by 233boy** [comment]
@zlf4865231 

sites 下面放的是 类似 Caddyfile 的 Caddy 配置，不是用来放网页文件.

参考配置：

```
qq.com {
  root /var/www/qq.com
}
```

…性感靓仔，在线解答

**Comment by zlf4865231** [comment]
> @ zlf4865231
> 
> sites下面放的是类似Caddyfile的Caddy配置，不是用来放网页文件。
> 
> 参考配置：
> 
> ```
> qq.com {
>   root /var/www/qq.com
> }
> ```
> 
> …性感靓仔，在线解答

谢谢大佬！那默认端口是什么呀 2015？能不能看po一份完整的配置呀

**Comment by 233boy** [comment]
@zlf4865231 

哪里有什么默认端口？？？

你如果想要修改现在用来给 V2Ray 使用的域名。。那你得更改 Caddyfile

**Comment by zlf4865231** [comment]
@233boy 
谢谢大佬回复 看了一晚上caddy配置项..才搞明白 我用的是给V2RAY的域名来做网站的  更改 Caddyfile 
root:自己网站目录  就好了    我想知道难道还可以有二级域名吗？

**Comment by zlf4865231** [comment]
@233boy  改完 网站可以打开 v2ray 用不了了...是不能共存吗？

**Comment by 233boy** [comment]
> @233boy 改完 网站可以打开 v2ray 用不了了...是不能共存吗？

你 可能把那个转发流量到 v2ray 的给修改掉了

**Comment by zlf4865231** [comment]
![88V%M38Y1E`AUL2 $N %`BV](https://user-images.githubusercontent.com/37063413/77812370-d01e0b00-70db-11ea-8c55-48c93586200b.png)
![0T N7B7)ABAM9%T5HK{(3H](https://user-images.githubusercontent.com/37063413/77812397-fe034f80-70db-11ea-914c-9fdf97391a73.png)
@233boy  大佬大佬~ 我贴个图 是配置错了吗

**Comment by 233boy** [comment]
> ![88V%M38Y1EAUL2 $N %BV](https://user-images.githubusercontent.com/37063413/77812370-d01e0b00-70db-11ea-8c55-48c93586200b.png)
> ![0T N7B7)ABAM9%T5HK{(3H](https://user-images.githubusercontent.com/37063413/77812397-fe034f80-70db-11ea-914c-9fdf97391a73.png)
> @233boy 大佬大佬~ 我贴个图 是配置错了吗

443 错了，肯定不是这个端口呀，这个端口要为 V2Ray 的端口

**Comment by zlf4865231** [comment]
> V2Ray
 

![)9Q8VDX K@N{94%GHAB`(RV](https://user-images.githubusercontent.com/37063413/77816618-ef7a5f80-70fe-11ea-9c40-15afb0f24211.png)
 谢谢大佬回答 明白了 
还有就是caddy IP 申请证书申请频率有限制嘛？ 我看caddy一直报错找不到证书

**Comment by zlf4865231** [comment]
> > ![88V％M38Y1EAUL2 $ N％BV](https://user-images.githubusercontent.com/37063413/77812370-d01e0b00-70db-11ea-8c55-48c93586200b.png)
> > ![0T N7B7）ABAM9％T5HK {（3H](https://user-images.githubusercontent.com/37063413/77812397-fe034f80-70db-11ea-914c-9fdf97391a73.png)
> > @ 233boy大佬大佬〜我贴个图是配置错了吗
> 
> 443错了，肯定不是这个端口呀，这个端口要为V2Ray的端口

谢谢大佬回答 明白了
还有就是caddy IP 申请证书申请频率有限制嘛？ 我看caddy一直报错找不到证书
![)9Q8VDX K@N{94%GHAB`(RV](https://user-images.githubusercontent.com/37063413/77816654-4a13bb80-70ff-11ea-81ff-4f3625549c63.png)

**Comment by pleaseRedo** [comment]
> > > ![88V％M38Y1EAUL2 $ N％BV](https://user-images.githubusercontent.com/37063413/77812370-d01e0b00-70db-11ea-8c55-48c93586200b.png)
> > > ![0T N7B7）ABAM9％T5HK {（3H](https://user-images.githubusercontent.com/37063413/77812397-fe034f80-70db-11ea-914c-9fdf97391a73.png)
> > > @ 233boy大佬大佬〜我贴个图是配置错了吗
> > 
> > 
> > 443错了，肯定不是这个端口呀，这个端口要为V2Ray的端口
> 
> 谢谢大佬回答 明白了
> 还有就是caddy IP 申请证书申请频率有限制嘛？ 我看caddy一直报错找不到证书
> ![)9Q8VDX K@N{94%GHAB`(RV](https://user-images.githubusercontent.com/37063413/77816654-4a13bb80-70ff-11ea-81ff-4f3625549c63.png)

wiki里有写的，你这个是域名证书申请次数用完了。花个5块再去买一个最省事

**Comment by zlf4865231** [comment]
> > > > ![88V％M38Y1EAUL2 $ N％BV](https://user-images.githubusercontent.com/37063413/77812370-d01e0b00-70db-11ea-8c55-48c93586200b.png)
> > > > ![0T N7B7）ABAM9％T5HK {（3H](https://user-images.githubusercontent.com/37063413/77812397-fe034f80-70db-11ea-914c-9fdf97391a73.png)
> > > > @ 233boy大佬大佬〜我贴个图是配置错了吗
> > > 
> > > 
> > > 443错了，肯定不是这个端口呀，这个端口要为V2Ray的端口
> > 
> > 
> > 谢谢大佬回答 明白了
> > 还有就是caddy IP 申请证书申请频率有限制嘛？ 我看caddy一直报错找不到证书
> > ![)9Q8VDX K@N{94%GHAB`(RV](https://user-images.githubusercontent.com/37063413/77816654-4a13bb80-70ff-11ea-81ff-4f3625549c63.png)
> 
> wiki里有写的，你这个是域名证书申请次数用完了。花个5块再去买一个最省事

好的谢谢大佬 买域名吗 还是买次数？

**Comment by zlf4865231** [comment]
解决了       解析个二级域名就好  一个域名做转发 流量一个域名做首页..

**Comment by pleaseRedo** [comment]
> 解决了 解析个二级域名就好 一个域名做转发 流量一个域名做首页..

学到了，我当时懒得多动手直接买了个垃圾域名顶了下。1周后原域名又恢复可以申证书了。原来还能想你这样弄，浪费我5块钱
