### ISSUE TITLE
请问开启广告拦截对性能影响是多大？访问速度减倍？

### ISSUE THREAD

**Issue by PineSongCN** [233boy/v2ray#545]
另外请问有没办法安装两个v2ray，一个开启一个未开启，告知下方式即可，我自行百度谷歌，谢谢。

**Comment by 233boy** [comment]
@PineSongCN 
性能影响没测试过。。。然后不太建议开启这个（（将来会去掉这个选项……
安装两个的话，你自己手动安装就行，V2Ray 下载就能运行

**Comment by PineSongCN** [comment]
> @PineSongCN
> 性能影响没测试过。。。然后不太建议开启这个（（将来会去掉这个选项……
> 安装两个的话，你自己手动安装就行，V2Ray 下载就能运行

谢谢
