### ISSUE TITLE
请问V2ray有没有500InternalPrivoxyError＂错误的解决方案

### ISSUE THREAD

**Issue by qiuyu6789** [233boy/v2ray#546]
用的v2ray一键脚本，服务器是阿里云的，已经卸载了阿里云盾，所有配置正常，ws+tls, 前几天还可以，这几天就显示500了，重启服务器都做过了，不行，服务器端口都没有被墙。

**Comment by qiuyu6789** [comment]
我再服务器段更新了v2ray，设置都没变，就解决了这个问题，但是现在困扰我的是，这到底是什么问题？

**Comment by 1202010104** [comment]
caddy转发的问题，昨天我出现了只有google.com  500   其他的都没问题
