### ISSUE TITLE
求解：V2ray 安装好 没连接上

### ISSUE THREAD

**Issue by emodeqidao** [233boy/v2ray#548]
2020/03/30 09:04:22 [Warning] [4284918886] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
2020/03/30 09:04:22 [Info] [4284918886] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe

这个是客户端的日志

求解

**Comment by fengspread** [comment]
服务器端口被禁了
