### ISSUE TITLE
因系统中不存在iptables相关组件，导致安装后网络接口失效的问题

### ISSUE THREAD

**Issue by netwww1** [233boy/v2ray#55]
问题原因：

用一键脚本安装后，会生成 /etc/network/if-pre-up.d/iptables的Shell脚本文件。
如果服务器中不存在iptables等程序和服务的情况下，重启服务器时，会在处理该shell脚本后返回错误，直接导致网络接口的初始化失败，网卡IP设置等全部失效，ifconfig下只有lo配置了。

解决方法：
检测服务器中是否存在iptables组件，如不存在，则无需处理iptables的规则。

**Comment by 233boy** [comment]
@netwww1 
暂不修复这个问题，感觉有些特殊..... 抱歉 😂 😂
