### ISSUE TITLE
v2RayX配置问题

### ISSUE THREAD

**Issue by booboom** [233boy/v2ray#552]
![image](https://user-images.githubusercontent.com/24515720/78097440-dfb88f00-740e-11ea-8a21-f8989f410905.png)
提问大佬们，我已经配置好了这个，但是谷歌浏览器还是不能翻墙，也打开了pac模式。请大佬们指点一下。

![image](https://user-images.githubusercontent.com/24515720/78097569-3625cd80-740f-11ea-99cb-a8493132f027.png)

ss没有打开。

**Comment by booboom** [comment]
![image](https://user-images.githubusercontent.com/24515720/78097647-640b1200-740f-11ea-8b58-d0ad2935f46e.png)

**Comment by zhz1237ok** [comment]
你去问v2rayX的作者啊，来这里有啥用，这里只有脚本啊兄弟

**Comment by booboom** [comment]
@zhz1237ok 我只是想请教下。。。这玩意怎么用😂

**Comment by zhz1237ok** [comment]
> @zhz1237ok 我只是想请教下。。。这玩意怎么用😂

你问一个普通人怎么造飞机吗，当然是去问造飞机专家怎么用啊，你问错地方了

**Comment by zhz1237ok** [comment]
> @zhz1237ok 我只是想请教下。。。这玩意怎么用😂

https://github.com/Cenmrev/V2RayX/issues 不然这issues区是干嘛的

**Comment by zhz1237ok** [comment]
> @zhz1237ok 我只是想请教下。。。这玩意怎么用😂

就像你问我怎么造核弹一样的，我又没造过核弹，不清楚里面的原理，你要问也别到这里来问啊，去问谁造的，只有作者才知道怎么用
