### ISSUE TITLE
v2rayN:订阅内容解码失败（非BASE64码）是什么意思啊？求大神帮忙看看

### ISSUE THREAD

**Issue by Xiao-tangyuan** [233boy/v2ray#556]
在配置了订阅服务器后，更新订阅时出现的问题

**Comment by Xiao-tangyuan** [comment]
日志提示未找到文件：user-wininet.json，但实际上我确认了文件夹中有这个文件啊！！
--------------------------------info[17:17:13]--------------------------------
System.Exception: v2rayN start up

 
--------------------------------未能找到文件“D:\software\v2rayn\v2rayN-Core\user-wininet.json”。[17:17:14]--------------------------------
System.IO.FileNotFoundException: 未能找到文件“D:\software\v2rayn\v2rayN-Core\user-wininet.json”。
文件名:“D:\software\v2rayn\v2rayN-Core\user-wininet.json”
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   在 System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   在 v2rayN.HttpProxyHandler.SysProxyHandle.Read()

**Comment by zhz1237ok** [comment]
口说无凭，截图 D:\software\v2rayn\v2rayN-Core\user-wininet.json 看这个文件

**Comment by Xiao-tangyuan** [comment]
<img width="543" alt="image" src="https://user-images.githubusercontent.com/57514698/78232549-fe9a4c80-7506-11ea-9f5e-90e1e468e40b.png">

**Comment by zhz1237ok** [comment]
看你的图标，是旧版的

试试新版的

https://github.com/2dust/v2rayN/releases

**Comment by Xiao-tangyuan** [comment]
文件内容：
{
  "UserSettingsRecorded": false,
  "Flags": "1",
  "ProxyServer": null,
  "BypassList": "localhost;127.*;10.*;172.16.*;172.17.*;172.18.*;172.19.*;172.20.*;172.21.*;172.22.*;172.23.*;172.24.*;172.25.*;172.26.*;172.27.*;172.28.*;172.29.*;172.30.*;172.31.*;172.32.*;192.168.*;127.0.0.1;<local>",
  "PacUrl": null
}

**Comment by zhz1237ok** [comment]
你这个是史前版本了都😂

**Comment by Xiao-tangyuan** [comment]
哦哦，我正在下新版的，万分感谢！！

**Comment by Xiao-tangyuan** [comment]
我下载了新版本，可是报错信息一样，日志如下：能麻烦帮我看一下吗？
-------------------------------info[20:30:01]--------------------------------
System.Exception: v2rayN start up

 
--------------------------------info[20:30:02]--------------------------------
System.Exception: Webserver prefixes http://*:10810/pac/

 
--------------------------------拒绝访问。[20:30:02]--------------------------------
System.Net.HttpListenerException (0x80004005): 拒绝访问。
   在 System.Net.HttpListener.AddAllPrefixes()
   在 System.Net.HttpListener.Start()
   在 v2rayN.Base.HttpWebServer..ctor(String[] prefixes, Func`2 method)

 
--------------------------------info[20:30:02]--------------------------------
System.Exception: Webserver InitServer 拒绝访问。

 
--------------------------------info[20:30:02]--------------------------------
System.Exception: WebserverB at 127.0.0.1

 
--------------------------------info[20:30:03]--------------------------------
System.Exception: WebserverB Request 127.0.0.1

 
--------------------------------info[20:30:03]--------------------------------
System.Exception: WebserverB Request 127.0.0.1

 
--------------------------------info[20:30:51]--------------------------------
System.Exception: v2rayN start up

 
--------------------------------info[20:30:52]--------------------------------
System.Exception: Webserver prefixes http://*:10810/pac/

 
--------------------------------拒绝访问。[20:30:52]--------------------------------
System.Net.HttpListenerException (0x80004005): 拒绝访问。
   在 System.Net.HttpListener.AddAllPrefixes()
   在 System.Net.HttpListener.Start()
   在 v2rayN.Base.HttpWebServer..ctor(String[] prefixes, Func`2 method)

 
--------------------------------info[20:30:52]--------------------------------
System.Exception: Webserver InitServer 拒绝访问。

 
--------------------------------info[20:30:52]--------------------------------
System.Exception: WebserverB at 127.0.0.1

 
--------------------------------info[20:30:53]--------------------------------
System.Exception: WebserverB Request 127.0.0.1

 
--------------------------------info[20:30:53]--------------------------------
System.Exception: WebserverB Request 127.0.0.1

 
--------------------------------info[20:30:54]--------------------------------
System.Exception: WebserverB Request 127.0.0.1

**Comment by zhz1237ok** [comment]
最简单的解决办法，重装系统

**Comment by Xiao-tangyuan** [comment]
不不，我电脑配置了太多软件了，重装系统太麻烦。
另外，release下的v2rayN和v2rayN-Core都不能下载，试了好多遍都提示无法，进度条根本不动，这可咋破？

**Comment by EigenVecta** [comment]
可以试试用 i(nternet) d(ownload) m(anager)，n(eat) d(ownload) m(anager)，f(ree) d(ownload) m(anager) 等下载器接管浏览器下载。
订阅内容解码失败可以看看这个 https://github.com/2dust/v2rayN/issues/767

**Comment by jiahe224** [comment]
我和你相反，我用最新版3.27不行，用旧版3.5就能更新订阅
