### ISSUE TITLE
使用 Cloudflare 中转 V2Ray 流量报错：无法访问此网站 www.google.com 意外终止了连接。

### ISSUE THREAD

**Issue by neuron42** [233boy/v2ray#557]
服务是按照[这篇 WIKI ](https://github.com/233boy/v2ray/wiki/%E4%BD%BF%E7%94%A8Cloudflare%E4%B8%AD%E8%BD%ACV2Ray%E6%B5%81%E9%87%8F)设置的，已经仔细的看了多遍，自我认为没有什么纰漏了，望各位指教一二

客户端日志：

> 配置成功
> Vmess-233v2.com_neuron-proxy.ga(***ga:443)
> 启动服务(2020/4/3 10:28:51)...
> 2020/04/03 10:28:51 tcp:127.0.0.1:52991 accepted tcp:content-autofill.googleapis.com:443 [proxy] 
> V2Ray 4.23.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13 windows/386)
> A unified platform for anti-censorship.
> 2020/04/03 10:28:52 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message> 
> v2ctl> Read config:  D:\v2rayN\config.json
> 2020/04/03 10:28:52 [Warning] v2ray.com/core: V2Ray 4.23.1 started
> 2020/04/03 10:28:56 tcp:127.0.0.1:53004 accepted tcp:content-autofill.googleapis.com:443 [proxy] 
> 2020/04/03 10:28:57 tcp:127.0.0.1:53008 accepted tcp:content-autofill.googleapis.com:443 [proxy] 
> 2020/04/03 10:28:59 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://neuron-proxy.ga/):  > remote error: tls: handshake failure] > v2ray.com/core/common/retry: all retry attempts failed

还需要贴什么我也会尽快贴出来，大神们不吝赐教，万分感谢！！！

**Comment by neuron42** [comment]
哎，折腾了一天了

**Comment by WangWenBin2017** [comment]
你配置的是ws+tls吗？再不行客户端v2更新到最新版本
