### ISSUE TITLE
Ubuntu 18.04LTS 客户端

### ISSUE THREAD

**Issue by zixiliuUSC** [233boy/v2ray#566]
我已经搭建好了服务器了，但是发现Linux那边找不到一个现成的客户端，想问一下v2ray core能不能作为客户端翻墙。另外我只使用命令行，只要能命令行上的命令能加速就行。跪求指教。

**Comment by Johnson-7** [comment]
可以的啊，v2ray官网上就有安装脚本，但是要自己写json
`bash <(curl -L -s https://install.direct/go.sh)`

**Comment by zixiliuUSC** [comment]
> 可以的啊，v2ray官网上就有安装脚本，但是要自己写json
> `bash <(curl -L -s https://install.direct/go.sh)`

json可以用windows导出的吗？还有就是命令行的翻墙的话，要怎么配置端口啊，大佬

**Comment by Johnson-7** [comment]
可以的，json文件里可以改端口的

**Comment by zixiliuUSC** [comment]
> 可以的，json文件里可以改端口的。我就是用的win导出的。

好哒，谢谢

**Comment by Johnson-7** [comment]
成功的话可以把issue关掉咯

**Comment by zixiliuUSC** [comment]
> 成功的话可以把issue关掉咯

我好像不知道怎么启动Linux的v2ray 诶， 以前都是直接用大佬的脚本的

**Comment by Johnson-7** [comment]
> > 成功的话可以把issue关掉咯
> 
> 我好像不知道怎么启动Linux的v2ray 诶， 以前都是直接用大佬的脚本的

常用的三个命令：
sytemctl start/restart/status v2ray
