### ISSUE TITLE
配置一切正常，并且生成了vmess链接，但是就是不能翻墙

### ISSUE THREAD

**Issue by xunlili** [233boy/v2ray#568]
所有的配置都正常，最后也正常的生成了vmess链接，然后导入到了客户端，最后上google或者YouTube的时候就无响应。找不到线索，各位大佬棒棒忙

**Comment by stdioBUZZ** [comment]
有可能要把防火墙关了
systemctl stop firewalld.service//关防火墙
systemctl disable firewalld.service //禁止自启

**Comment by yuanter** [comment]
还有可能是服务器供应商还有上一层的防火墙/安全组，比如阿里云后台控制台还有一个安全组需要放行
