### ISSUE TITLE
Not an issue, just a question

### ISSUE THREAD

**Issue by ercxar** [233boy/v2ray#569]
Hello

I've been using your script I don't know for how long and never had any issues and I really appreciate you for that.

My question is, your script also uses Caddy in between, but if I use V2Ray + WebSocket + TLS + CDN only and do not use any of Nginx / Caddy / Apache, will it compromise anything? I should also note that the domain is not a real web page.

Thank you in advance.
Erfan

**Comment by 233boy** [comment]
@ercxar 
yeah, 
1. use WebSocket  protocol and **80** port, then in cloudflare SSL/TLS encryption choose **Flexible**.
2. v2ray client (eg.. v2rayN):  addrees fill in your domain, port fill in **443**,  also fill uuid, alterid. protocol is ws, TLS option must open.

note: script will show port info is 80, but in client config you should use 443.

**Comment by ercxar** [comment]
Thank you. My apologies for the late reply.
