### ISSUE TITLE
能不能加个进程值守

### ISSUE THREAD

**Issue by 1202010104** [233boy/v2ray#570]
512的小机器  经常不正常 手动ssh重启v2ray进程即可恢复

**Comment by 1202010104** [comment]
不过好像又不是进程问题  日志提示cloudflare的DNS？
2020/04/01 09:42:04 [Warning] v2ray.com/core: V2Ray 4.23.1 started
2020/04/02 13:43:37 [Warning] v2ray.com/core: V2Ray 4.23.1 started
2020/04/04 22:37:31 [Error] v2ray.com/core/app/dns: failed to retrive response > Post https://cloudflare-dns.com/dns-query: context deadline exceeded
2020/04/04 22:37:31 [Error] v2ray.com/core/app/dns: failed to retrive response > Post https://cloudflare-dns.com/dns-query: context deadline exceeded
2020/04/06 23:13:03 [Warning] v2ray.com/core: V2Ray 4.23.1 started
2020/04/08 16:20:17 [Error] v2ray.com/core/app/dns: failed to retrive response > Post https://cloudflare-dns.com/dns-query: context deadline exceeded
2020/04/08 23:35:11 [Error] v2ray.com/core/app/dns: failed to retrive response > Post https://cloudflare-dns.com/dns-query: context deadline exceeded
2020/04/09 19:32:56 [Warning] v2ray.com/core: V2Ray 4.23.1 started
2020/04/11 10:45:47 [Warning] v2ray.com/core: V2Ray 4.23.1 started
2020/04/15 10:31:02 [Warning] v2ray.com/core: V2Ray 4.23.1 started

**Comment by Cardidi** [comment]
我的问题和你也一样....但是没找到解决办法。
我之前用的是非此脚本自动配置的v2ray，同样的出现这个问题，我想这个问题可能与这个脚本无关，和v2ray本身有关吧...

**Comment by Cardidi** [comment]
https://www.linodovultr.com/post/resolve-v2ray-after-install-can-not-connect.html
刚刚找到的一篇文章，我先试试看...
