### ISSUE TITLE
《V2RayN使用教程》补充

### ISSUE THREAD

**Issue by redstoneleo** [233boy/v2ray#573]
[https://github.com/233boy/v2ray/wiki/V2RayN%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B#测试一下](https://github.com/233boy/v2ray/wiki/V2RayN%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B#测试一下
)
补充一下这个教程，要添加的内容：如果还是发现翻出去，并且电脑上运行着360安全卫士，那么可能是被360拦截了V2RayN，

![image](https://user-images.githubusercontent.com/5896180/79749108-2e3bb800-8341-11ea-969d-33152f11dbeb.png)

这时要做的是把V2RayN所在目录加入信任区
![image](https://user-images.githubusercontent.com/5896180/79749281-81ae0600-8341-11ea-8dda-ff08f023c75d.png)

我今天都被360的拦截浪费了好长好长时间，希望补充上去不让后来人浪费时间

**Comment by SekiBetu** [comment]
2020年了，还有人用360

**Comment by 5m17h** [comment]
360永远滴神

**Comment by larry0442** [comment]
ball ball you 不要用360勒哈哈哈。我是被他搞怕了，现在裸奔哈哈哈，大不了重装

**Comment by Jayhuangze** [comment]
都是裸机了吧

**Comment by zcat95** [comment]
整乐了，用v2ray还装个360，勇士冲塔不可取
