### ISSUE TITLE
failed to read request header

### ISSUE THREAD

**Issue by yuanter** [233boy/v2ray#575]
2020/04/22 18:11:30 我的服务器ip地址:59088 rejected  v2ray.com/core/proxy/vmess/encoding: failed to read request header > read tcp 172.17.41.98:80->我的服务器ip地址:59088: i/o timeout

v2ray这种报错是啥情况，开启国内阿里云服务器用的nginx中转

**Comment by fhbyljj** [comment]
同，我也是

**Comment by neciszhang** [comment]
同，我也是

**Comment by scut-shpan** [comment]
请问一下有什么解决方案吗？
