### ISSUE TITLE
V2ray + ws + tls ping可以维持在200毫秒左右，但访问网站极慢，墙又升级了？

### ISSUE THREAD

**Issue by magnusguo** [233boy/v2ray#578]
求教给位！ Ping这没问题 200多毫秒， 但iOS手机端Shadowsocks测试链路的方法有一种是连接一个网站， 则延迟一下跳到1100多 且不稳定。请问是不是V2ray + ws + tls 这方法已经不行了？

**Comment by shjdgwj** [comment]
你是不是还套了个cdn？本来这种方法就慢。。。。不过我cdn去掉看油管无压力

**Comment by magnusguo** [comment]
> 你是不是还套了个cdn？本来这种方法就慢。。。。不过我cdn去掉看油管无压力

然而并没有套cdn， 现在改为trojan还是不行 特别慢，怀疑vps的问题

**Comment by LaurenceSamael** [comment]
vultr的鸡吗？如是，那可以考虑换vps了。vultr的vps无一例外，不论地域，只要用ws+tls、trojan、wss+cdn等都会巨慢，此问题无解，是vps那边的问题。

**Comment by magnusguo** [comment]
> vultr的鸡吗？如是，那可以考虑换vps了。vultr的vps无一例外，不论地域，只要用ws+tls、trojan、wss+cdn等都会巨慢，此问题无解，是vps那边的问题。

不是不是，用的Hostwinds， 有推荐的VPS吗亲？

**Comment by xingpingcn** [comment]
> vultr

那用什么？kcp？那个流量浪费很多
