### ISSUE TITLE
无法访问谷歌学术

### ISSUE THREAD

**Issue by Breezy-ye** [233boy/v2ray#579]
可以访问谷歌等其他网站，谷歌学术提示：
我们很抱歉...
...但是您的计算机或网络可能正在发送自动查询。为了保护我们的用户，我们目前无法处理您的请求。

**Comment by zixiliuUSC** [comment]
你的IP地址有问题，应该是上一个用户是重度使用的，跟v2ray无关

**Comment by SekiBetu** [comment]
你服务器被用烂了，以前有人用爬虫大量爬取谷歌学术文章，被谷歌永久BAN了IP
