### ISSUE TITLE
请问多设备同时连接是否有冲突

### ISSUE THREAD

**Issue by gin063** [233boy/v2ray#580]
之前配置了一个服务器，但是当电脑在使用时，用手机的移动网络同时连接会出现连不上的情况。后来我手动增加了端口和uuid，电脑和手机使用不同的端口+uuid，同时访问就很少出现冲突了。
我是初学者，也不确定是不是因为这个问题，如果是的话，希望大神能在后续脚本中增加额外生成新的端口和id的选项，对于我这种小白是福音，用vim编辑真的很蛋疼。
我也没有太多需求，就是想多设备同时使用不起冲突，然后分享给几个朋友一起用，这样划得来一些，vps在我手里的确有点大材小用了😓
最后，感谢大神的开发和分享！

**Comment by yuanter** [comment]
https://blog.sprov.xyz/2019/08/03/v2-ui/
可以试下这个

**Comment by Shangbaize-Daoye** [comment]
服务器端设置一个uuid，多个客户端使用是不会有冲突的。你说的有时连不上的问题有两种可能，一是你的服务器到国内连接不稳定，另一种是你使用的客户端bug引起的断流问题。我这设置一个uuid，我几个朋友一起用都没问题。

**Comment by yw-2020** [comment]
> 之前配置了一个服务器，但是当电脑在使用时，用手机的移动网络同时连接会出现连不上的情况。后来我手动增加了端口和uuid，电脑和手机使用不同的端口+uuid，同时访问就很少出现冲突了。 我是初学者，也不确定是不是因为这个问题，如果是的话，希望大神能在后续脚本中增加额外生成新的端口和id的选项，对于我这种小白是福音，用vim编辑真的很蛋疼。 我也没有太多需求，就是想多设备同时使用不起冲突，然后分享给几个朋友一起用，这样划得来一些，vps在我手里的确有点大材小用了😓 最后，感谢大神的开发和分享！
好兄弟，这个问题解决了吗？
