### ISSUE TITLE
2020/4/27突然不能科学上网了，windows下客户端的报错如下

### ISSUE THREAD

**Issue by luluyouyue** [233boy/v2ray#581]
2020/04/28 19:35:37 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 1xx.168.201.229:64580: i/o timeout] > v2ray.com/core/common/retry: all retry attempts failed
2020/04/28 19:35:38 tcp:127.0.0.1:56938 accepted tcp:github-production-release-asset-2e65be.s3.amazonaws.com:443 [proxy] 
2020/04/28 19:37:00 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 1xx.168.201.229:64580: i/o timeout] > v2ray.com/core/common/retry: all retry attempts failed

（ip 经过隐藏处理）

**Comment by luluyouyue** [comment]
重新安装一些服务端的程序，又好了

**Comment by luluyouyue** [comment]
上面是在手机端又可以了，但是windows客户端不可以，有没有大佬有解决方案？

**Comment by luluyouyue** [comment]
重启一下电脑，然后打开客户端就可以了

**Comment by AgoniNemo** [comment]
端口的问题
