### ISSUE TITLE
使用广电宽带的一些问题

### ISSUE THREAD

**Issue by m250317460** [233boy/v2ray#587]
我之前使用电信宽带的时候使用v2ray科学上网十分方便，最近宽带到期换成了广电的宽带，发现科学上网的时候经常会有几分钟的连接超时，我中途换成自己手机热点访问正常，再换回wifi依然超时，过几分钟后就正常了，再等半小时之后再次访问依然是超时，依然是几分钟后再次可以访问，想问下有没有大佬明白是什么原因

**Comment by Shangbaize-Daoye** [comment]
线路问题，广电宽带到你国外vps的路径上数据传输慢延迟高，经常会断掉。而你手机热点的运营商网络到你的国外vps的路径上数据传输比较稳定。
解决方案目前两种：
1、换vps，找一个国外vps延迟低的。这个延迟低传输稳定的国外vps可能不好找，我之前也遇到这个问题，换了几个地区的都不太行。
2、在国内再买个阿里云或腾讯的vps做中转服务器，尽量选上海的，上海机房到美国西雅图机房的vps数据传输比较稳定。你在国内和国外vps各搭好v2ray，其中国内的用于中转流量到国外vps。这样相当于找了个捷径。我现在用这个方案，以前直连国外vps下载github文件下不动，现在做了中转，能有1MB/s的速度了。

**Comment by lovelyelfpop** [comment]
@Shangbaize-Daoye 你是怎么中转的？我使用websocket+tls协议，国内服务器nginx反代不了。
最后只能使用websocket协议，然后自己用nginx实现tls，这样国内服务器才能用nginx反代

**Comment by Shangbaize-Daoye** [comment]
> @Shangbaize-Daoye 你是怎么中转的？我使用websocket+tls协议，国内服务器nginx反代不了。
> 最后只能使用websocket协议，然后自己用nginx实现tls，这样国内服务器才能用nginx反代

国外服务器照样按脚本里原来方式设置websocket+tls（用的caddy）。
国内服务器也装了v2ray，设置outbounds连上国外的v2ray就好了。Inbounds一个道理，国内到国内路径不需要那么麻烦用ws+tls，我是直接tcp了。如果国内路径你也要tls的话，还用caddy或nginx都行。
国内服务器v2ray outbounds设置成这样就行。
"outbounds": [
                {
                        "protocol": "vmess",
                        "settings": {
                                "vnext": [
                                        {
                                                "address": "doman name",
                                                "port": 443,
                                                "users": [
                                                        {
                                                                "id": "。。。。",
                                                                "alterId": 。。。
                                                        }
                                                ]
                                        }
                                ]
                        },
                        "streamSettings": {
                                "network": "ws",
                                "security": "tls",
                                "wsSettings": {
                                        "path": "/v2ray-ws"
                                }
                        },
                        "tag": "bridge"
                },
                {
                        "protocol": "blackhole",
                        "settings": {},
                        "tag": "blocked"
                },
                {
                        "protocol": "mtproto",
                        "settings": {},
                        "tag": "tg-out"
                }
                //include_out_config
                //
        ]

**Comment by MFWT** [comment]
回到家乡用的是广电宽带，不得不说相比移动宽带要差100倍，直连VPS勉勉强强能用，但是走CDN就完全不行了。
现在靠的是上海的阿里云服务器转发数据（转发机连国外用WS＋TLS，我连转发机用TCP），限速5Mbps，聊胜于无，速度倒也可以

**Comment by jinbaolu** [comment]
这也忒麻烦了吧，为啥广电这样子的

**Comment by MFWT** [comment]
> 这也忒麻烦了吧，为啥广电这样子的

你猜猜为啥叫这个运营商广电，不叫电信联通移动（

顺带一提，同样情况还出现在鹏博士，长城宽带，蓝波万维等小宽带的情况上，为了节省可怜的出口带宽，各种奇技淫巧都用上了，副作用就是这个issues提到的情况：连接质量严重劣化
