### ISSUE TITLE
如果能使用非443、80端口监听http流量就好了

### ISSUE THREAD

**Issue by chengza** [233boy/v2ray#591]
在我的服务器上运行着我的博客，已占用了443和80端口。

当我使用这个脚本配置v2ray的时候如果能够使用8080、8443等端口用作http伪装（使用webscket+TSL）的端口，那么就不会和我的博客冲突。

因为我的博客已经运行了比较久的时间，做了较多的配置，所以把博客改为伪装背后的被代理内容非常困难。

倘若这个脚本能够允许使用其他的端口来伪装http流量，会更方便。

**Comment by chengza** [comment]
发现流量代理是caddy，自己手动改/etc/caddy/Caddyfile可以做到。

**Comment by doKill** [comment]
非443或80的不是自己给枪口上撞么
