### ISSUE TITLE
v2ray是不能用了吗

### ISSUE THREAD

**Issue by GentleCP** [233boy/v2ray#593]
如题，今天突然不行了，重装也没有解决问题

**Comment by songzexin** [comment]
同样问题

**Comment by wnehm** [comment]
我也是，原因大家都知道，但是有没有什么规避方案呢？

**Comment by 6ag** [comment]
同样不能用了，做开发不能没有梯子，哎

**Comment by wnehm** [comment]
> 同样不能用了，做开发不能没有梯子，哎

我已经买了justmysocks，先顶一个月再说

**Comment by GentleCP** [comment]
我重装了系统，然后再重装了v2ray又可以用了

**Comment by SekiBetu** [comment]
It's still working for me, please check your server side

**Comment by GentleCP** [comment]
> It's still working for me, please check your server side

yes, after I reinstalled my operating system and installed v2ray, it worked.

**Comment by ZHANGBAIFA9** [comment]
> 如题，今天突然不行了，重装也没有解决问题

你好，这边现在解决了吗？

**Comment by GentleCP** [comment]
> > 如题，今天突然不行了，重装也没有解决问题
> 
> 你好，这边现在解决了吗？

我现在不用这个了，尝试重装系统应该能解决这个问题，我改到multi-v2ray这个上了，你也可以尝试下这个

**Comment by ZHANGBAIFA9** [comment]
嗯，一直failed




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "233boy/v2ray"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月7日(星期天) 中午12:23
收件人:&nbsp;"233boy/v2ray"<v2ray@noreply.github.com&gt;;
抄送:&nbsp;"い゛i"<1350862999@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [233boy/v2ray] v2ray是不能用了吗 (#593)





   
如题，今天突然不行了，重装也没有解决问题
  
你好，这边现在解决了吗？
  
我现在不用这个了，尝试重装系统应该能解决这个问题，我改到multi-v2ray这个上了，你也可以尝试下这个
