### ISSUE TITLE
v2ray 无法建立tcp

### ISSUE THREAD

**Issue by NicoNicoCN** [233boy/v2ray#594]
Log如下
v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:
v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp : i/o timeout dial tcp operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed
这个问题是今天出现的

**Comment by NicoNicoCN** [comment]
Log如下
v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:
v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp : i/o timeout dial tcp operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed
这个问题是今天出现的

**Comment by wnehm** [comment]
一样，原因大家都懂的

**Comment by xc1988** [comment]
昨天全挂了 换成WebSocket + TLS 还可以用

**Comment by SekiBetu** [comment]
> 一样，原因大家都懂的

归根结底，不是脚本不能用，而是你服务器IP被BAN了

**Comment by tcw123** [comment]
> > 一样，原因大家都懂的
> 
> 归根结底，不是脚本不能用，而是你服务器IP被BAN了

我用的搬瓦工查ip发现没被ban，不知道咋回事，高级墙？

**Comment by sleafummer** [comment]
ip 正常 ping 通，但就是连不上，不知道咋回事，正卸载重装呢

**Comment by tcw123** [comment]
> ip 正常 ping 通，但就是连不上，不知道咋回事，正卸载重装呢

我也是，老哥能行的话叫我一声

**Comment by NicoNicoCN** [comment]
1. 不是ip被BAN，SS还可用
2. 没了解过v2ray的其他模式，vmess是不可以用了。
3. 现在在用v2ray可以正常使用的可以说下
4. 等开发者或者懂logic的人说明情况

**Comment by sleafummer** [comment]
> > ip 正常 ping 通，但就是连不上，不知道咋回事，正卸载重装呢
> 
> 我也是，老哥能行的话叫我一声

我重新安装，正常了。我的应该不是 v2ray 的问题

**Comment by SekiBetu** [comment]
不是很正常吗，封端口了啊，所以IP能ping通，重新安装可以成功就是说明原来那个端口被封了，如果你再用新的端口，多次重复这个过程之后，你服务器IP就被封了

**Comment by SekiBetu** [comment]
> 提出此类问题的人一般都是第一次使用此脚本吧，封端口是第一步，如果你继续换端口，或者直接用动态端口，下次就封服务器IP了，这种事情每天都在经历，换个服务器就完事了

**Comment by laoxue123** [comment]
> ip 正常 ping 通，但就是连不上，不知道咋回事，正卸载重装呢

我也是，IP正常，换系统默认端口，重装3次，还是不行。求指点

**Comment by NicoNicoCN** [comment]
> 提出此类问题的人一般都是第一次使用此脚本吧，封端口是第一步，如果你继续换端口，或者直接用动态端口，下次就封服务器IP了，这种事情每天都在经历，换个服务器或者使用websocket就完事了
> 
> 
> 
> 建议关闭此类issue，纯属浪费时间

好的，先感谢你的回答。 

顺便，不是所有人都是懂得端口服务器以及GW封禁的原理的，这些可能对某些人很小儿科但是对做别的行业有要用这个工具的人其实就是软件，按照章程弄好了，不work，自然会问，因为我们不知道他怎么工作的，也不知道如何应变。

倒是可以写个wiki Q&A 置顶 可以减少此类问题。

**Comment by Shangbaize-Daoye** [comment]
> > ip 正常 ping 通，但就是连不上，不知道咋回事，正卸载重装呢
> 
> 我也是，IP正常，换系统默认端口，重装3次，还是不行。求指点

有可能是vps防火墙问题。可以试试在vps控制面板开放指定端口，然后配置好让v2ray启动，监听指定端口。测试时在你的其他机子上（windows或linux）用telnet命令测试该端口可不可用（比如“telnet 200.31.41.22 44556”测试端口44556是否可用）。如果能有“escape character ]”字样说明端口开放，如果一直try或连不上，那就是端口被vps厂商或者国内gfw封了。

**Comment by preswang** [comment]
昨天发现v2ray tcp的端口被封，改了一个端口，用了几小时后又被封，现在改用ws+tls+cloudflare，就是速度慢点。
如果搞不清楚端口是否被封的，可以访问http://port.ping.pe
把vps的ip和端口贴进去

**Comment by hsiayuchih** [comment]
> 昨天发现v2ray tcp的端口被封，改了一个端口，用了几小时后又被封，现在改用ws+tls+cloudflare，就是速度慢点。
> 如果搞不清楚端口是否被封的，可以访问http://port.ping.pe
> 把vps的ip和端口贴进去

我刚刚被查也发现被封了，但是他貌似隔段时间会解封一段时间，然后又封，然后再解封就这样一直持续...

**Comment by xaatora** [comment]
我真的需要了解v2ray工具的安装方式有何帮助

**Comment by xaatora** [comment]
我想学习设置v2ray
