### ISSUE TITLE
tls+websocket 获取端口信息错误和生成url端口错误

### ISSUE THREAD

**Issue by divmid** [233boy/v2ray#595]
![image](https://user-images.githubusercontent.com/40823856/82784448-1d77e800-9e93-11ea-9e7f-103a7b01e6ed.png)
* 使用v2ray url 获取的配置端口也不对
![image](https://user-images.githubusercontent.com/40823856/82784545-51eba400-9e93-11ea-807b-7e7c1be824a1.png)

**Comment by Shangbaize-Daoye** [comment]
脚本最后显示的配置信息没问题，那是客户端配置信息。你客户端要填的访问端口就是443，走https的。
流程大概这样：客户端访问服务器443端口（https）→ caddy收到443请求后将请求转发到你设置的444端口 → 服务器端v2ray从444端口收到请求，然后解析请求。

**Comment by divmid** [comment]
感谢大佬
