### ISSUE TITLE
Does this matters?

### ISSUE THREAD

**Issue by SekiBetu** [233boy/v2ray#599]
https://github.com/v2ray/discussion/issues/704
https://github.com/v2ray/v2ray-core/issues/2518

**Comment by Shangbaize-Daoye** [comment]
Sure, the problem mentioned interferes with current mode TLS+WS, **but only on client side** not server side. That means your client's underlying v2ray-core has got to be updated to the latest version.
Of course you can also update your v2ray to latest version with command "bash <(curl -L -s https://install.direct/go.sh)" on your server to look nice, but this doesn't matter.
Only client side update is indispensable to deal with such a problem.
