### ISSUE TITLE
V2RAY升级至2.36无法再通过脚本命令v2ray打开脚本

### ISSUE THREAD

**Issue by gbmeco** [233boy/v2ray#60]
今天使用脚本的界面将V2RAY升级至2.36
但是完成后再使用V2RAY命令想进入脚本的界面就会出现以下提示

-bash: /usr/local/bin/v2ray: No such file or directory

目前v2ray 运行还算正常。 请教应该如何解决。 

谢谢！

**Comment by 233boy** [comment]
@gbmeco 
重新登录 SSH 即可，不是什么大问题... 因为有些系统 ( CentOS 7 ) 可能会无法直接执行这个命令，我就修改一下这个文件的目录路径让 CentOS 7 也可以执行
😂

**Comment by gbmeco** [comment]
果然就又可以了。 感谢！
