### ISSUE TITLE
v2ray无法冲浪，但是生成的ss可以

### ISSUE THREAD

**Issue by tiriolo** [233boy/v2ray#602]
事情是这样的，之前用的一键脚本搞得v2ray，一直都可以用，直到一个月前，突然无法使用，可以ping通端口也正常，我以为是墙有了什么新手段，但是今天实在忍不住了，就想试试ss，居然可以，但是用v2ray还是不行，有大佬知道怎么回事吗？

**Comment by grayren** [comment]
端口确定可以ping通？  应该是封端口没封ip

**Comment by tiriolo** [comment]
感谢大佬，换了端口可以了

**Comment by semiprojt** [comment]
我也遇到了你同样的问题，你怎么换的端口啊，更改协议么

**Comment by grayren** [comment]
> 
> 
> 我也遇到了你同样的问题，你怎么换的端口啊，更改协议么

输入v2ray  进入控制面板，选2
