### ISSUE TITLE
直接进入域名报500错 上谷歌正常

### ISSUE THREAD

**Issue by Astebreed** [233boy/v2ray#603]
使用vmess+ws+tls 申请了域名和SSL证书（均为腾讯云申请） SSL证书用winscp手动存入/root/，在v2-ui中正确填写路径 安装脚本是直接用v2-ui处提供的 我有一vultr和一conoha服务器 应用相同配置（域名和SSL证书是分别申请设置的）翻墙均功能正常但速度较慢（较同服务器使用ssr） vultr服务器直接进入域名可以看到伪装网页 但域名前面显示不安全 conoha的进入域名会无限转圈无法加载 翻墙后进入该域名秒报500错误 我也没有单独安装nginx 不清楚v2ray的一键脚本内是否自带了nginx 还是说vultr会自带nginx服务而conoha不带呢 基础知识缺乏望前辈指点 感谢！

**Comment by Shangbaize-Daoye** [comment]
Nginx配置出问题了，可能需要你手动改nginx.conf，学习成本高了些。
我记得这个一键脚本好像没有自带nginx，只有自带配置caddy。

**Comment by Astebreed** [comment]
> Nginx配置出问题了，可能需要你手动改nginx.conf，学习成本高了些。
> 我记得这个一键脚本好像没有自带nginx，只有自带配置caddy。

好的好的 感谢！
