### ISSUE TITLE
端口什么的都一样，用一段时间就要卸载掉重装才行。

### ISSUE THREAD

**Issue by udeth** [233boy/v2ray#604]
事情是这样的，我发现用了一段时间之后就无法愉快的上网冲浪了，起初以为是端口或ip的问题。但是重新开启一台新的实例也是用一段时间就不行了 。后来，我试了下卸了重新安装，端口协及传输协议都 是跟之前一样的，居然可以正常的上网冲浪了。试了很多次，这是什么问题，每次重装也太麻烦了。

**Comment by Shangbaize-Daoye** [comment]
ip端口没问题的时候，一般服务器端都没问题。
可能是客户端有断流问题。如果你用v2rayN客户端就经常会遇到断流问题。

**Comment by udeth** [comment]
Mac上用的是V2rayU,关了重开都没用，必须要服务端重装。

**Comment by Shangbaize-Daoye** [comment]
推荐个mac客户端clash，https://github.com/Dreamacro/clash/releases
然后你最好在下次重新出现这问题的时候，把服务器上/var/log/v2ray/error.log中时间上最近的部分贴出来，客户端的error log也贴出来看看。

**Comment by udeth** [comment]
clash 之前下载过，管理页面一片空白。
