### ISSUE TITLE
cloudflare CDN websocket fails

### ISSUE THREAD

**Issue by amirmt71** [233boy/v2ray#605]
Hi
I have a running server which works fine without CDN (cloudflare DNS gray).
But if I enable proxy (cloudflare DNS Orange) it fails to connect.
I have my server running your script, in ws+tls mode.

again it works fine when I use direct IP (instead of my domain name). And also it works fine when I disable cloudflare proxy and enable dns only mode.

I have cloudflare free account and I see the attached picture in the documents. Is my problem related to the low concurrent rate of my free cloudflare account?

If not, what should I do? My configuration is totally your default script, without any modification.

![image](https://user-images.githubusercontent.com/44301435/84566064-7399c600-ad83-11ea-8d9f-fb27943001f2.png)

**Comment by samuelthapa** [comment]
I had also same issue it might be coz of update delay from cloudfare side but after 12 hrs it work with cdn but its still blocked for data wifi is working fine
