### ISSUE TITLE
谷歌云和阿里云国际的机器，跑youtube永远没有超过6k

### ISSUE THREAD

**Issue by RICwang** [233boy/v2ray#618]
![image](https://user-images.githubusercontent.com/5809783/86801625-ce82bc80-c0a6-11ea-9510-0a46e7a413d5.png)
谷歌云和阿里云国际的机器，跑youtube永远没有超过6k，
各位是不是也是这样？？
用的ws+tls

**Comment by SekiBetu** [comment]
![image](https://user-images.githubusercontent.com/38283893/86801937-1bff2980-c0a7-11ea-973c-2486f82ff06c.png)

**Comment by Shangbaize-Daoye** [comment]
线路问题。我西雅图机器上海教育网访问能2M，到了福建有时候网页视频都放不动还经常断线。

**Comment by RICwang** [comment]
> 线路问题。我西雅图机器上海教育网访问能2M，到了福建有时候网页视频都放不动还经常断线。

但是我跑speedtest可以跑满速，所以很奇怪

**Comment by 1870947876** [comment]
我在谷歌云上配置的v2ray 速度就0.17m 看个锤子啊
