### ISSUE TITLE
能否增加支持设置WireGuard ?

### ISSUE THREAD

**Issue by gbmeco** [233boy/v2ray#62]
最近推上看各位大佬对WireGuard 评价非常高，我们的脚本能不能增加支持WireGuard？ 

谢谢啦！

**Comment by rhotov** [comment]
> 最近推上看各位大佬对WireGuard 评价非常高，我们的脚本能不能增加支持WireGuard？
> 
> 谢谢啦！

另一个脚本目前支持wireguard，可以试试看，另外我发现好像换成wireguard之后速度会快一些，不知道是不是错觉。

**Comment by gbmeco** [comment]
“另一个脚本”是哪个脚本啊？这个脚本是不是可以和你的V2RAY脚本同时安装在同一台VPS？

谢谢！

**Comment by rhotov** [comment]
>           “另一个脚本”是哪个脚本啊？这个脚本是不是可以和你的V2RAY脚本同时安装在同一台VPS？
> 谢谢！

https://github.com/Jrohy/multi-v2ray 没试验过能否共存，估计会出bug吧
