### ISSUE TITLE
PC手机等客户端可以使用V2RAY，但软路由无法连通

### ISSUE THREAD

**Issue by Ming526** [233boy/v2ray#621]
瓦工VPS，之前在openwrt已设置好SSR+的V2RAY的设置，且已经连通，但是升级4.26后，客户端可以连接，但软路由无法连接了，感谢！

**Comment by Shangbaize-Daoye** [comment]
这问题应该去v2ray官方仓库提交issue

**Comment by Ming526** [comment]
收到，感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "233boy/v2ray"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月15日(星期三) 下午3:21
收件人:&nbsp;"233boy/v2ray"<v2ray@noreply.github.com&gt;;
抄送:&nbsp;"铭记在新"<wangxinwise@vip.qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [233boy/v2ray] PC手机等客户端可以使用V2RAY，但软路由无法连通 (#621)





 
这问题应该去v2ray官方仓库提交issue
