### ISSUE TITLE
大家有没有碰到公司的网络可以使用，但是家里的网络不可以？

### ISSUE THREAD

**Issue by starsw001** [233boy/v2ray#622]
公司网络是电信的。
家里网络是移动的，如果移动不能用的话，下一步考虑换成电信宽带了。

**Comment by Axis6th** [comment]
可能是防火墙审计系统的问题。

**Comment by starsw001** [comment]
那是 移动本身的问题 还是 我家里电脑的问题？？？应该不是，我台式机访问不了。笔记本也是一样访问不了。
估计还是宽带自身的原因了。。。

**Comment by Shangbaize-Daoye** [comment]
之前有朋友也遇到这种问题，后来帮查了发现是他家电脑UTC时间和服务器UTC时间相差大于两分钟

**Comment by starsw001** [comment]
> 之前有朋友也遇到这种问题，后来帮查了发现是他家电脑UTC时间和服务器UTC时间相差大于两分钟

嗯。好的。回去检查一下看看，虽说感觉不太像，谢谢。

**Comment by gefate** [comment]
试一下重启移动的猫和路由器

**Comment by lidy996** [comment]
之前家里长城宽带是有限速的大约1M带宽，后来打电话给客服说访问国外的网速慢，他们给调成5M，很稳定。后来换成了电信的宽带，虽然有时能跑满带宽，但不稳定。如果在选一次，我选择长城宽带

**Comment by zhanghaidi** [comment]
我也遇到过，之前没问题，突然前几个月家里移动wifi和手机移动网络都不能用，服务器端口和ip都是通的，后来在公司发现用公司的联通宽带wifi和电脑都没问题
