### ISSUE TITLE
caddy下载链接失效

### ISSUE THREAD

**Issue by Jindom** [233boy/v2ray#624]
--2020-07-21 06:09:43--  https://caddyserver.com/download/linux/amd64?license=personal
Resolving caddyserver.com (caddyserver.com)... 165.227.20.207, 2604:a880:2:d0::21b0:6001
Connecting to caddyserver.com (caddyserver.com)|165.227.20.207|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-07-21 06:09:44 ERROR 404: Not Found.

 下载 Caddy 失败！

**Comment by chaoxi24** [comment]
我也遇到了这个问题。

**Comment by Shangbaize-Daoye** [comment]
caddy无法安装看旁边的issue。

v2ray我一般手动更新，
- sudo wget https://v2ray最新版linux64安装地址/v2ray.zip
- unzip v2ray.zip -d /usr/bin/v2ray
    - 如果提示覆盖一路覆盖下去
- service v2ray restart

v2ray.zip视链接里实际文件名而定。

**Comment by chaoxi24** [comment]
> 
> 
> caddy无法安装看旁边的issue。
> 
> v2ray我一般手动更新，
> 
>     * sudo wget [https://v2ray最新版linux64安装地址/v2ray.zip](https://v2ray%E6%9C%80%E6%96%B0%E7%89%88linux64%E5%AE%89%E8%A3%85%E5%9C%B0%E5%9D%80/v2ray.zip)
> 
>     * unzip v2ray.zip -d /usr/bin/v2ray
>       
>       * 如果提示覆盖一路覆盖下去
> 
>     * service v2ray restart
> 
> 
> v2ray.zip视链接里实际文件名而定。

谢谢。
