### ISSUE TITLE
使用脚本最后一句话的时候说下载caddy失败，怎么办呢？

### ISSUE THREAD

**Issue by kenandelu** [233boy/v2ray#625]

**Comment by yirangeqian** [comment]
一样操作

**Comment by fenglindubu** [comment]
一样操作

**Comment by Shangbaize-Daoye** [comment]
重新操作一遍，或者自己去下载安装caddy 1
caddy 1的配置文件Caddyfile：
```
https://your.domain.com {
    gzip
    timeouts none
    proxy / https://disguised.website.com {
        except /path-fenliu
    }
    proxy /path-fenliu 127.0.0.1:v2ray_port {
        without /path-fenliu
        websocket
    }
}
import sites/*
```

**Comment by pxcxd1989** [comment]
遇到了同样的问题

**Comment by hunxun** [comment]
遇到同样问题

**Comment by James-Hao** [comment]
+1 同样问题，重装系统再安装好几次还是caddy下载失败！

**Comment by kenandelu** [comment]
caddy官网更新有点问题，所以可以把脚本中caddy的链接换一下，或者用其他脚本。

**Comment by James-Hao** [comment]
> caddy官网更新有点问题，所以可以把脚本中caddy的链接换一下，或者用其他脚本。

![image](https://user-images.githubusercontent.com/32088388/88042289-49a3a280-cb7e-11ea-969b-003e07c36334.png)
请教下脚本中哪个位置换成哪个链接可以解决呀~ 多谢多谢！

**Comment by kenandelu** [comment]
> > caddy官网更新有点问题，所以可以把脚本中caddy的链接换一下，或者用其他脚本。
> 
> ![image](https://user-images.githubusercontent.com/32088388/88042289-49a3a280-cb7e-11ea-969b-003e07c36334.png)
> 请教下脚本中哪个位置换成哪个链接可以解决呀~ 多谢多谢！

在服务器中显示失败的上面地方的那个caddy的那个链接，找到那个替换掉就行，这个链接可以用：
https://github.com/mholt/caddy/releases/download/v0.11.0/caddy_v0.11.0_linux_amd64.tar.gz

**Comment by James-Hao** [comment]
> > > caddy官网更新有点问题，所以可以把脚本中caddy的链接换一下，或者用其他脚本。
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/32088388/88042289-49a3a280-cb7e-11ea-969b-003e07c36334.png)
> > 请教下脚本中哪个位置换成哪个链接可以解决呀~ 多谢多谢！
> 
> 在服务器中显示失败的上面地方的那个caddy的那个链接，找到那个替换掉就行，这个链接可以用：
> https://github.com/mholt/caddy/releases/download/v0.11.0/caddy_v0.11.0_linux_amd64.tar.gz

非常感谢！但是我没有在脚本中找到可以替换成您提供链接的地方，您可以告诉我一下吗？十分感谢！

**Comment by kenandelu** [comment]
> > > > caddy官网更新有点问题，所以可以把脚本中caddy的链接换一下，或者用其他脚本。
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/32088388/88042289-49a3a280-cb7e-11ea-969b-003e07c36334.png)
> > > 请教下脚本中哪个位置换成哪个链接可以解决呀~ 多谢多谢！
> > 
> > 
> > 在服务器中显示失败的上面地方的那个caddy的那个链接，找到那个替换掉就行，这个链接可以用：
> > https://github.com/mholt/caddy/releases/download/v0.11.0/caddy_v0.11.0_linux_amd64.tar.gz
> 
> 非常感谢！但是我没有在脚本中找到可以替换成您提供链接的地方，您可以告诉我一下吗？十分感谢！

有其他联系方式吗，这个感觉有点麻烦，关键是我不常看，一直蹦邮箱。

**Comment by James-Hao** [comment]
> > > > > caddy官网更新有点问题，所以可以把脚本中caddy的链接换一下，或者用其他脚本。
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/32088388/88042289-49a3a280-cb7e-11ea-969b-003e07c36334.png)
> > > > 请教下脚本中哪个位置换成哪个链接可以解决呀~ 多谢多谢！
> > > 
> > > 
> > > 在服务器中显示失败的上面地方的那个caddy的那个链接，找到那个替换掉就行，这个链接可以用：
> > > https://github.com/mholt/caddy/releases/download/v0.11.0/caddy_v0.11.0_linux_amd64.tar.gz
> > 
> > 
> > 非常感谢！但是我没有在脚本中找到可以替换成您提供链接的地方，您可以告诉我一下吗？十分感谢！
> 
> 有其他联系方式吗，这个感觉有点麻烦，关键是我不常看，一直蹦邮箱。

QQ可以吗？299346063，这是我的Q号，劳烦您~

**Comment by James-Hao** [comment]
> > > > > caddy官网更新有点问题，所以可以把脚本中caddy的链接换一下，或者用其他脚本。
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/32088388/88042289-49a3a280-cb7e-11ea-969b-003e07c36334.png)
> > > > 请教下脚本中哪个位置换成哪个链接可以解决呀~ 多谢多谢！
> > > 
> > > 
> > > 在服务器中显示失败的上面地方的那个caddy的那个链接，找到那个替换掉就行，这个链接可以用：
> > > https://github.com/mholt/caddy/releases/download/v0.11.0/caddy_v0.11.0_linux_amd64.tar.gz
> > 
> > 
> > 非常感谢！但是我没有在脚本中找到可以替换成您提供链接的地方，您可以告诉我一下吗？十分感谢！
> 
> 有其他联系方式吗，这个感觉有点麻烦，关键是我不常看，一直蹦邮箱。

QQ可以吗？2993460603这是我的QQ号，劳烦您啦~

**Comment by kenandelu** [comment]
> > > > > > caddy官网更新有点问题，所以可以把脚本中caddy的链接换一下，或者用其他脚本。
> > > > > 
> > > > > 
> > > > > ![image](https://user-images.githubusercontent.com/32088388/88042289-49a3a280-cb7e-11ea-969b-003e07c36334.png)
> > > > > 请教下脚本中哪个位置换成哪个链接可以解决呀~ 多谢多谢！
> > > > 
> > > > 
> > > > 在服务器中显示失败的上面地方的那个caddy的那个链接，找到那个替换掉就行，这个链接可以用：
> > > > https://github.com/mholt/caddy/releases/download/v0.11.0/caddy_v0.11.0_linux_amd64.tar.gz
> > > 
> > > 
> > > 非常感谢！但是我没有在脚本中找到可以替换成您提供链接的地方，您可以告诉我一下吗？十分感谢！
> > 
> > 
> > 有其他联系方式吗，这个感觉有点麻烦，关键是我不常看，一直蹦邮箱。
> 
> QQ可以吗？2993460603这是我的QQ号，劳烦您啦~

你的有加验证，你加我吧，1020391590，写好备注就行。

**Comment by doKill** [comment]
> > > caddy官网更新有点问题，所以可以把脚本中caddy的链接换一下，或者用其他脚本。
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/32088388/88042289-49a3a280-cb7e-11ea-969b-003e07c36334.png)
> > 请教下脚本中哪个位置换成哪个链接可以解决呀~ 多谢多谢！
> 
> 在服务器中显示失败的上面地方的那个caddy的那个链接，找到那个替换掉就行，这个链接可以用：
> https://github.com/mholt/caddy/releases/download/v0.11.0/caddy_v0.11.0_linux_amd64.tar.gz

感谢，亲测链接可用。

**Comment by chaoxi24** [comment]
@kenandelu
抱歉能说下具体修改方法吗？
我把gz文件下载到本地，也修改了download-caddy.sh，但不知道接下来不知道怎么做了。

**Comment by James-Hao** [comment]
> @kenandelu
> 抱歉能说下具体修改方法吗？
> 我把gz文件下载到本地，也修改了download-caddy.sh，但不知道接下来不知道怎么做了。

请教您download-caddy.sh文件是在哪里获得的呀？

**Comment by chaoxi24** [comment]
> 
> 
> > @kenandelu
> > 抱歉能说下具体修改方法吗？
> > 我把gz文件下载到本地，也修改了download-caddy.sh，但不知道接下来不知道怎么做了。
> 
> 请教您download-caddy.sh文件是在哪里获得的呀？

我把源文件下载到本地了，这是错误的。应该是编辑在服务器的download-caddy.sh，但我现在找不到这个文件在哪里，不知道路径。。。

**Comment by chaoxi24** [comment]
> 
> 
> > @kenandelu
> > 抱歉能说下具体修改方法吗？
> > 我把gz文件下载到本地，也修改了download-caddy.sh，但不知道接下来不知道怎么做了。
> 
> 请教您download-caddy.sh文件是在哪里获得的呀？

我把源文件下载到本地了，这是错误的。应该是编辑在服务器的download-caddy.sh，但我现在找不到这个文件在哪里，不知道路径。。。

**Comment by James-Hao** [comment]
> > > @kenandelu
> > > 抱歉能说下具体修改方法吗？
> > > 我把gz文件下载到本地，也修改了download-caddy.sh，但不知道接下来不知道怎么做了。
> > 
> > 
> > 请教您download-caddy.sh文件是在哪里获得的呀？
> 
> 我把源文件下载到本地了，这是错误的。应该是编辑在服务器的download-caddy.sh，但我现在找不到这个文件在哪里，不知道路径。。。

哈哈哈 是的 我也没找到这个文件

**Comment by Shangbaize-Daoye** [comment]
我提供一个完整流程，不过没在我的实际生产环境执行过一遍：

- 先运行一次原始233脚本，直到提示无法下载完成caddy。
    - sudo wget https://git.io/v2ray.sh
    - sudo chmod a+x ./v2ray.sh
    - sudo ./v2ray.sh
    - 正常按流程安装，直到提示无法下载完成caddy。
- sudo rm -rf /tmp/*
- sudo vim /etc/v2ray/233boy/v2ray/src/download-caddy.sh
- 改掉其中第八行：把local caddy_download_link="https://caddyserver.com/download/linux/${caddy_arch}?license=personal"中的链接改成https://github.com/mholt/caddy/releases/download/v0.11.0/caddy_v0.11.0_linux_amd64.tar.gz
- 重新执行sudo ./v2ray.sh

有问题再指出。

**Comment by chaoxi24** [comment]
> 
> 
> 我提供一个完整流程，不过没在我的实际生产环境执行过一遍：
> 
>     * 先运行一次原始233脚本，直到提示无法下载完成caddy。
>       
>       * sudo wget https://git.io/v2ray.sh
>       * sudo chmod a+x ./v2ray.sh
>       * sudo ./v2ray.sh
>       * 正常按流程安装，直到提示无法下载完成caddy。
> 
>     * sudo rm -rf /tmp/*
> 
>     * sudo vim /etc/v2ray/233boy/v2ray/src/download-caddy.sh
> 
>     * 改掉其中第八行：把local caddy_download_link="[https://caddyserver.com/download/linux/${caddy_arch}?license=personal"中的链接改成https://github.com/mholt/caddy/releases/download/v0.11.0/caddy_v0.11.0_linux_amd64.tar.gz](https://caddyserver.com/download/linux/$%7Bcaddy_arch%7D?license=personal%22%E4%B8%AD%E7%9A%84%E9%93%BE%E6%8E%A5%E6%94%B9%E6%88%90https://github.com/mholt/caddy/releases/download/v0.11.0/caddy_v0.11.0_linux_amd64.tar.gz)
> 
>     * 重新执行sudo ./v2ray.sh
> 
> 
> 有问题再指出。


谢谢。
尝试了数次都没成功。成功修改后，最后一步"sudo ./v2ray.sh"，会把文件还原成原始版本。

**Comment by yzyeengang** [comment]
> > 我提供一个完整流程，不过没在我的实际生产环境执行过一遍：
> > ```
> > * 先运行一次原始233脚本，直到提示无法下载完成caddy。
> >   
> >   * sudo wget https://git.io/v2ray.sh
> >   * sudo chmod a+x ./v2ray.sh
> >   * sudo ./v2ray.sh
> >   * 正常按流程安装，直到提示无法下载完成caddy。
> > 
> > * sudo rm -rf /tmp/*
> > 
> > * sudo vim /etc/v2ray/233boy/v2ray/src/download-caddy.sh
> > 
> > * 改掉其中第八行：把local caddy_download_link="[https://caddyserver.com/download/linux/${caddy_arch}?license=personal"中的链接改成https://github.com/mholt/caddy/releases/download/v0.11.0/caddy_v0.11.0_linux_amd64.tar.gz](https://caddyserver.com/download/linux/$%7Bcaddy_arch%7D?license=personal%22%E4%B8%AD%E7%9A%84%E9%93%BE%E6%8E%A5%E6%94%B9%E6%88%90https://github.com/mholt/caddy/releases/download/v0.11.0/caddy_v0.11.0_linux_amd64.tar.gz)
> > 
> > * 重新执行sudo ./v2ray.sh
> > ```
> > 
> > 
> > 有问题再指出。
> 
> 谢谢。
> 尝试了数次都没成功。成功修改后，最后一步"sudo ./v2ray.sh"，会把文件还原成原始版本。

刚安上，流程如下：
1.随便找个目录 ``git clone https://github.com/233boy/v2ray -b mastergit clone https://github.com/233boy/v2ray -b master``
2.修改v2ray/src/download-caddy.sh里面local caddy_download_link哪一行为``local caddy_download_link="https://github.com/mholt/caddy/releases/download/v0.11.0/caddy_v0.11.0_linux_${caddy_arch}.tar.gz"``
3.``bash v2ray/install.sh local``

**Comment by James-Hao** [comment]
> @chaoxi24
> 
> 刚安上，完整流程如下：
> 
> * 随便找个目录 `git clone https://github.com/233boy/v2ray -b mastergit clone https://github.com/233boy/v2ray -b master`
> * 把v2ray/src/download-caddy.sh里面local caddy_download_link的哪一行中的链接修改成[https://github.com/mholt/caddy/releases/download/v0.11.0/caddy_v0.11.0_linux_${caddy_arch}.tar.gz](https://github.com/mholt/caddy/releases/download/v0.11.0/caddy_v0.11.0_linux_$%7Bcaddy_arch%7D.tar.gz)
> * `bash v2ray/install.sh local` 完事

感谢！亲测有效！

**Comment by hunxun** [comment]
``

> > @chaoxi24
> > 刚安上，完整流程如下：
> > 
> > * 随便找个目录 `git clone https://github.com/233boy/v2ray -b mastergit clone https://github.com/233boy/v2ray -b master`
> > * 把v2ray/src/download-caddy.sh里面local caddy_download_link的哪一行中的链接修改成[https://github.com/mholt/caddy/releases/download/v0.11.0/caddy_v0.11.0_linux_${caddy_arch}.tar.gz](https://github.com/mholt/caddy/releases/download/v0.11.0/caddy_v0.11.0_linux_$%7Bcaddy_arch%7D.tar.gz)
> > * `bash v2ray/install.sh local` 完事
> 
> 感谢！亲测有效！

可以执行完 ，运行v2ray  URL  说安装出错

**Comment by James-Hao** [comment]
> @chaoxi24
> 
> 刚安上，完整流程如下：
> 
> * 随便找个目录 `git clone https://github.com/233boy/v2ray -b mastergit clone https://github.com/233boy/v2ray -b master`
> * 把v2ray/src/download-caddy.sh里面local caddy_download_link的哪一行中的链接修改成[https://github.com/mholt/caddy/releases/download/v0.11.0/caddy_v0.11.0_linux_${caddy_arch}.tar.gz](https://github.com/mholt/caddy/releases/download/v0.11.0/caddy_v0.11.0_linux_$%7Bcaddy_arch%7D.tar.gz)
> * `bash v2ray/install.sh local` 完事

![image](https://user-images.githubusercontent.com/32088388/88129876-bc0e9400-cc0b-11ea-892c-1c119e8921b8.png)
请教我安装完成后，caddy运行不了，请问您知道原因吗？

**Comment by yzyeengang** [comment]
@James-Hao 这我就不知道了，我的是新装vps，centos8 amd64的，防火墙全关，可能这个caddy版本不适合你的机子吧，你可以去https://github.com/caddyserver/caddy/releases选一个对应你机子的版本下载 ，要是caddy1的

**Comment by Nluva** [comment]
已经解决
`wget --no-check-certificate https://raw.githubusercontent.com/Nluva/v2ray/master/install.sh && bash install.sh`

**Comment by hunxun** [comment]
获取不到caddy，出现这个问题了吗


Length: 6429642 (6.1M) [application/octet-stream]
Saving to: ‘/tmp/install_caddy/caddy.tar.gz’


/tmp/install_caddy/ 100%[================&gt;]&nbsp; &nbsp;6.13M&nbsp; 10.5MB/s&nbsp; &nbsp; in 0.6s


2020-07-22 12:40:31 (10.5 MB/s) - ‘/tmp/install_caddy/caddy.tar.gz’ saved [6429642/6429642]


/etc/v2ray/233boy/v2ray/src/download-caddy.sh: line 16: tar: command not found
cp: cannot stat '/tmp/install_caddy/caddy': No such file or directory
&nbsp;安装 Caddy 出错！




---原始邮件---
发件人: "Nluva"<notifications@github.com&gt;
发送时间: 2020年7月22日(周三) 中午12:23
收件人: "233boy/v2ray"<v2ray@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"hunxun"<285346207@qq.com&gt;;
主题: Re: [233boy/v2ray] 使用脚本最后一句话的时候说下载caddy失败，怎么办呢？ (#625)




 
已经解决
 wget --no-check-certificate https://raw.githubusercontent.com/Nluva/v2ray/master/install.sh &amp;&amp; bash install.sh

**Comment by Nluva** [comment]
> 获取不到caddy，出现这个问题了吗 Length: 6429642 (6.1M) [application/octet-stream] Saving to: ‘/tmp/install_caddy/caddy.tar.gz’ /tmp/install_caddy/ 100%[================&gt;]&nbsp; &nbsp;6.13M&nbsp; 10.5MB/s&nbsp; &nbsp; in 0.6s 2020-07-22 12:40:31 (10.5 MB/s) - ‘/tmp/install_caddy/caddy.tar.gz’ saved [6429642/6429642] /etc/v2ray/233boy/v2ray/src/download-caddy.sh: line 16: tar: command not found cp: cannot stat '/tmp/install_caddy/caddy': No such file or directory &nbsp;安装 Caddy 出错！
> […](#)
> ---原始邮件--- 发件人: "Nluva"<notifications@github.com&gt; 发送时间: 2020年7月22日(周三) 中午12:23 收件人: "233boy/v2ray"<v2ray@noreply.github.com&gt;; 抄送: "Comment"<comment@noreply.github.com&gt;;"hunxun"<285346207@qq.com&gt;; 主题: Re: [233boy/v2ray] 使用脚本最后一句话的时候说下载caddy失败，怎么办呢？ (#625) 已经解决 wget --no-check-certificate https://raw.githubusercontent.com/Nluva/v2ray/master/install.sh &amp;&amp; bash install.sh — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

安装caddy出错应该是因为caddy版本不对吧，我只更改了git仓库和里面的caddy链接，添加了这个帖子前面有人提供的这个`https://github.com/mholt/caddy/releases/download/v0.11.0/caddy_v0.11.0_linux_${caddy_arch}.tar.gz`

**Comment by Holmeyoung** [comment]
请问一下caddy为什么要用0.11.0版本呢，我看git上都到2.x版本了

**Comment by SekiBetu** [comment]
> 请问一下caddy为什么要用0.11.0版本呢，我看git上都到2.x版本了

可以试试最新版的caddy，如果有问题再退回来，用老版本是因为稳定才用的

**Comment by Nluva** [comment]
> 请问一下caddy为什么要用0.11.0版本呢，我看git上都到2.x版本了

caddy可以往上升，但是仅限于1.x，不过用来做这个用途够用就好

**Comment by James-Hao** [comment]
> @James-Hao 这我就不知道了，我的是新装vps，centos8 amd64的，防火墙全关，可能这个caddy版本不适合你的机子吧，你可以去[https://github.com/caddyserver/caddy/releases选一个对应你机子的版本下载](https://github.com/caddyserver/caddy/releases%E9%80%89%E4%B8%80%E4%B8%AA%E5%AF%B9%E5%BA%94%E4%BD%A0%E6%9C%BA%E5%AD%90%E7%9A%84%E7%89%88%E6%9C%AC%E4%B8%8B%E8%BD%BD) ，要是caddy1的

我也是新cps，centos7-x86_64的，不知道为什么0.11.0老是看caddy status运行不了，哎

**Comment by James-Hao** [comment]
> @James-Hao 这我就不知道了，我的是新装vps，centos8 amd64的，防火墙全关，可能这个caddy版本不适合你的机子吧，你可以去[https://github.com/caddyserver/caddy/releases选一个对应你机子的版本下载](https://github.com/caddyserver/caddy/releases%E9%80%89%E4%B8%80%E4%B8%AA%E5%AF%B9%E5%BA%94%E4%BD%A0%E6%9C%BA%E5%AD%90%E7%9A%84%E7%89%88%E6%9C%AC%E4%B8%8B%E8%BD%BD) ，要是caddy1的

我也是新vps，centos7-x86_64的，不知道为什么0.11.0老是看caddy status运行不了，哎

**Comment by Shangbaize-Daoye** [comment]
> 请问一下caddy为什么要用0.11.0版本呢，我看git上都到2.x版本了

caddy 1和2的配置文件不相互兼容，你可以用caddy2，但是只能手动设置配置文件，因为233脚本自动化设置的Caddyfile配置文件只能用在caddy 1上。

**Comment by zhughe** [comment]
修改 /etc/v2ray/233boy/v2ray/src/download-caddy.sh 这个文件里面的下载连接就行

**Comment by kenandelu** [comment]
不知道为什么。。。今天再用原来的代码。。。居然成功了。。。。很神奇。

**Comment by manatsu525** [comment]
看commits，作者已经修复了

**Comment by manatsu525** [comment]
> 不知道为什么。。。今天再用原来的代码。。。居然成功了。。。。很神奇。

作者已经修复了

**Comment by tangheng1995** [comment]
> > 获取不到caddy，出现这个问题了吗 Length: 6429642 (6.1M) [application/octet-stream] Saving to: ‘/tmp/install_caddy/caddy.tar.gz’ /tmp/install_caddy/ 100%[================>]   6.13M  10.5MB/s    in 0.6s 2020-07-22 12:40:31 (10.5 MB/s) - ‘/tmp/install_caddy/caddy.tar.gz’ saved [6429642/6429642] /etc/v2ray/233boy/v2ray/src/download-caddy.sh: line 16: tar: command not found cp: cannot stat '/tmp/install_caddy/caddy': No such file or directory  安装 Caddy 出错！
> > […](#)
> > ---原始邮件--- 发件人: "Nluva"<[notifications@github.com](mailto:notifications@github.com)> 发送时间: 2020年7月22日(周三) 中午12:23 收件人: "233boy/v2ray"<[v2ray@noreply.github.com](mailto:v2ray@noreply.github.com)>; 抄送: "Comment"<[comment@noreply.github.com](mailto:comment@noreply.github.com)>;"hunxun"<[285346207@qq.com](mailto:285346207@qq.com)>; 主题: Re: [233boy/v2ray] 使用脚本最后一句话的时候说下载caddy失败，怎么办呢？ (#625) 已经解决 wget --no-check-certificate https://raw.githubusercontent.com/Nluva/v2ray/master/install.sh && bash install.sh — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 安装caddy出错应该是因为caddy版本不对吧，我只更改了git仓库和里面的caddy链接，添加了这个帖子前面有人提供的这个`https://github.com/mholt/caddy/releases/download/v0.11.0/caddy_v0.11.0_linux_${caddy_arch}.tar.gz`

为什么我这改了还报错？

![image](https://user-images.githubusercontent.com/47218360/88473925-aaebbd00-cf54-11ea-9ae3-5cf13e862d7f.png)

**Comment by Nluva** [comment]
> > > 获取不到caddy，出现这个问题了吗 Length: 6429642 (6.1M) [application/octet-stream] Saving to: ‘/tmp/install_caddy/caddy.tar.gz’ /tmp/install_caddy/ 100%[================>]   6.13M  10.5MB/s    in 0.6s 2020-07-22 12:40:31 (10.5 MB/s) - ‘/tmp/install_caddy/caddy.tar.gz’ saved [6429642/6429642] /etc/v2ray/233boy/v2ray/src/download-caddy.sh: line 16: tar: command not found cp: cannot stat '/tmp/install_caddy/caddy': No such file or directory  安装 Caddy 出错！
> > > […](#)
> > > ---原始邮件--- 发件人: "Nluva"<[notifications@github.com](mailto:notifications@github.com)> 发送时间: 2020年7月22日(周三) 中午12:23 收件人: "233boy/v2ray"<[v2ray@noreply.github.com](mailto:v2ray@noreply.github.com)>; 抄送: "Comment"<[comment@noreply.github.com](mailto:comment@noreply.github.com)>;"hunxun"<[285346207@qq.com](mailto:285346207@qq.com)>; 主题: Re: [233boy/v2ray] 使用脚本最后一句话的时候说下载caddy失败，怎么办呢？ (#625) 已经解决 wget --no-check-certificate https://raw.githubusercontent.com/Nluva/v2ray/master/install.sh && bash install.sh — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> > 
> > 
> > 安装caddy出错应该是因为caddy版本不对吧，我只更改了git仓库和里面的caddy链接，添加了这个帖子前面有人提供的这个`https://github.com/mholt/caddy/releases/download/v0.11.0/caddy_v0.11.0_linux_${caddy_arch}.tar.gz`
> 
> 为什么我这改了还报错？
> 
> ![image](https://user-images.githubusercontent.com/47218360/88473925-aaebbd00-cf54-11ea-9ae3-5cf13e862d7f.png)

本地改的没用

**Comment by tangheng1995** [comment]
> > > > 获取不到caddy，出现这个问题了吗 Length: 6429642 (6.1M) [application/octet-stream] Saving to: ‘/tmp/install_caddy/caddy.tar.gz’ /tmp/install_caddy/ 100%[================>]   6.13M  10.5MB/s    in 0.6s 2020-07-22 12:40:31 (10.5 MB/s) - ‘/tmp/install_caddy/caddy.tar.gz’ saved [6429642/6429642] /etc/v2ray/233boy/v2ray/src/download-caddy.sh: line 16: tar: command not found cp: cannot stat '/tmp/install_caddy/caddy': No such file or directory  安装 Caddy 出错！
> > > > […](#)
> > > > ---原始邮件--- 发件人: "Nluva"<[notifications@github.com](mailto:notifications@github.com)> 发送时间: 2020年7月22日(周三) 中午12:23 收件人: "233boy/v2ray"<[v2ray@noreply.github.com](mailto:v2ray@noreply.github.com)>; 抄送: "Comment"<[comment@noreply.github.com](mailto:comment@noreply.github.com)>;"hunxun"<[285346207@qq.com](mailto:285346207@qq.com)>; 主题: Re: [233boy/v2ray] 使用脚本最后一句话的时候说下载caddy失败，怎么办呢？ (#625) 已经解决 wget --no-check-certificate https://raw.githubusercontent.com/Nluva/v2ray/master/install.sh && bash install.sh — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> > > 
> > > 
> > > 安装caddy出错应该是因为caddy版本不对吧，我只更改了git仓库和里面的caddy链接，添加了这个帖子前面有人提供的这个`https://github.com/mholt/caddy/releases/download/v0.11.0/caddy_v0.11.0_linux_${caddy_arch}.tar.gz`
> > 
> > 
> > 为什么我这改了还报错？
> > ![image](https://user-images.githubusercontent.com/47218360/88473925-aaebbd00-cf54-11ea-9ae3-5cf13e862d7f.png)
> 
> 本地改的没用

我修改的是本地下载脚本，安装也是用本地执行的

**Comment by Nluva** [comment]
> > > > > 获取不到caddy，出现这个问题了吗 Length: 6429642 (6.1M) [application/octet-stream] Saving to: ‘/tmp/install_caddy/caddy.tar.gz’ /tmp/install_caddy/ 100%[================>]   6.13M  10.5MB/s    in 0.6s 2020-07-22 12:40:31 (10.5 MB/s) - ‘/tmp/install_caddy/caddy.tar.gz’ saved [6429642/6429642] /etc/v2ray/233boy/v2ray/src/download-caddy.sh: line 16: tar: command not found cp: cannot stat '/tmp/install_caddy/caddy': No such file or directory  安装 Caddy 出错！
> > > > > […](#)
> > > > > ---原始邮件--- 发件人: "Nluva"<[notifications@github.com](mailto:notifications@github.com)> 发送时间: 2020年7月22日(周三) 中午12:23 收件人: "233boy/v2ray"<[v2ray@noreply.github.com](mailto:v2ray@noreply.github.com)>; 抄送: "Comment"<[comment@noreply.github.com](mailto:comment@noreply.github.com)>;"hunxun"<[285346207@qq.com](mailto:285346207@qq.com)>; 主题: Re: [233boy/v2ray] 使用脚本最后一句话的时候说下载caddy失败，怎么办呢？ (#625) 已经解决 wget --no-check-certificate https://raw.githubusercontent.com/Nluva/v2ray/master/install.sh && bash install.sh — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> > > > 
> > > > 
> > > > 安装caddy出错应该是因为caddy版本不对吧，我只更改了git仓库和里面的caddy链接，添加了这个帖子前面有人提供的这个`https://github.com/mholt/caddy/releases/download/v0.11.0/caddy_v0.11.0_linux_${caddy_arch}.tar.gz`
> > > 
> > > 
> > > 为什么我这改了还报错？
> > > ![image](https://user-images.githubusercontent.com/47218360/88473925-aaebbd00-cf54-11ea-9ae3-5cf13e862d7f.png)
> > 
> > 
> > 本地改的没用
> 
> 我修改的是本地下载脚本，安装也是用本地执行的

是因为你启动脚本时他会再次从github重新clone一份，所以本地改的会被覆盖不生效

**Comment by Coltonchan** [comment]
> > > > > > caddy官网更新有点问题，所以可以把脚本中caddy的链接换一下，或者用其他脚本。
> > > > > 
> > > > > 
> > > > > ![image](https://user-images.githubusercontent.com/32088388/88042289-49a3a280-cb7e-11ea-969b-003e07c36334.png)
> > > > > 请教下脚本中哪个位置换成哪个链接可以解决呀~ 多谢多谢！
> > > > 
> > > > 
> > > > 在服务器中显示失败的上面地方的那个caddy的那个链接，找到那个替换掉就行，这个链接可以用：
> > > > https://github.com/mholt/caddy/releases/download/v0.11.0/caddy_v0.11.0_linux_amd64.tar.gz
> > > 
> > > 
> > > 非常感谢！但是我没有在脚本中找到可以替换成您提供链接的地方，您可以告诉我一下吗？十分感谢！
> > 
> > 
> > 有其他联系方式吗，这个感觉有点麻烦，关键是我不常看，一直蹦邮箱。
> 
> QQ可以吗？2993460603这是我的QQ号，劳烦您啦~

兄弟方便加个q吗，我是小白对这方便操作不太懂，非常感谢♪(･ω･)ﾉ
