### ISSUE TITLE
BBR加速和锐速可以共存吗？

### ISSUE THREAD

**Issue by midsmr** [233boy/v2ray#627]
安装bbr之后想换锐速但是不能卸载
重装影响人太多了
问下能不能共存

**Comment by doKill** [comment]
[装这个加速替换即可](https://github.com/chiakge/Linux-NetSpeed)
加速和 v2 配置是两个独立的东西，互不影响。

**Comment by Shangbaize-Daoye** [comment]
应该是可以共存的。不过还是建议你只用bbr。开发锐速的公司早就没了，锐速现在都没又维护了，算是上古软件，linux内核需要较低的版本才支持锐速。bbr现在较新的linux内核是直接支持的。虽然低版本的linux内核也可以装bbr，但是何必要用上古软件，锐速不是在所有云商环境下都比bbr好的
