### ISSUE TITLE
服务端正常状态，但是无法穿墙。

### ISSUE THREAD

**Issue by honcun** [233boy/v2ray#63]
服务端v2ray和caddy都正常，本地windows配置vmess，无法穿墙；
IOS小火箭配置vmess，一样无法穿墙。
检查过时间，没问题。
 win7下vmess客户端配置：

> {
  "log": {
    "access": "",
    "error": "",
    "loglevel": "warning"
  },
  "inbound": {
    "port": 1080,
    "listen": "127.0.0.1",
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": true,
      "ip": "127.0.0.1",
      "clients": null
    },
    "streamSettings": null
  },
  "outbound": {
    "tag": "agentout",
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "***.*****.tk",
          "port": 443,
          "users": [
            {
              "id": "b18b3811-e8da-4527-b356-320e5545ea10",
              "alterId": 100,
              "email": "t@t.tt",
              "security": "aes-128-gcm"
            }
          ]
        }
      ],
      "servers": null
    },
    "streamSettings": {
      "network": "ws",
      "security": "tls",
      "tlsSettings": {
        "allowInsecure": true,
        "serverName": null
      },
      "tcpSettings": null,
      "kcpSettings": null,
      "wsSettings": {
        "connectionReuse": true,
        "path": "/fuckgfw_gfwmotherfuckingboom/511c0b9e-5001-4fc6-96f6-23b5148bce59",
        "headers": null
      },
      "httpSettings": null
    },
    "mux": {
      "enabled": true
    }
  },
  "inboundDetour": null,
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {
        "response": null
      },
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      },
      "tag": "blockout"
    }
  ],
  "dns": {
    "servers": [
      "8.8.8.8",
      "8.8.4.4",
      "localhost"
    ]
  },
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "port": null,
          "outboundTag": "direct",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "domain": null
        }
      ]
    }
  }
}

三天了，头大……

**Comment by Hwatu** [comment]
我也遇到这个问题，服务正常运行，服务器可以不用翻墙访问，说明没被封，但是v2ray却连不上，服务器时间与本地时间也一至
bash <(curl -s -L https://v2ray66.com/v2ray.sh)
脚本

**Comment by 233boy** [comment]
@honcun 
如果服务器运行正常，那请检查你的客户端配置是否正确。
备注，你如果使用 GCP 或者类似相关的国际 大厂的 VPS ，你需要开放防火墙。
