### ISSUE TITLE
安装成功 服务启动一直失败【附临时解决方案】

### ISSUE THREAD

**Issue by bigbugcc** [233boy/v2ray#630]
错误日志如下：

 v2ray.service - V2Ray Service
   Loaded: loaded (/usr/lib/systemd/system/v2ray.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Thu 2020-07-30 16:04:56 CST; 28s ago
     Docs: https://www.v2ray.com/
           https://www.v2fly.org/
 Main PID: 4879 (code=exited, status=218/CAPABILITIES)

Jul 30 16:04:56 hk1491299250 systemd[1]: v2ray.service: main process exited, code=exited, **status=218/CAPABILITIES**
Jul 30 16:04:56 hk1491299250 systemd[1]: Unit v2ray.service entered failed state.
Jul 30 16:04:56 hk1491299250 systemd[1]: v2ray.service failed.
Jul 30 16:04:56 hk1491299250 systemd[1]: v2ray.service holdoff time over, scheduling restart.
Jul 30 16:04:56 hk1491299250 systemd[1]: Stopped V2Ray Service.
Jul 30 16:04:56 hk1491299250 systemd[1]: start request repeated too quickly for v2ray.service
Jul 30 16:04:56 hk1491299250 systemd[1]: Failed to start V2Ray Service.
Jul 30 16:04:56 hk1491299250 systemd[1]: Unit v2ray.service entered failed state.
Jul 30 16:04:56 hk1491299250 systemd[1]: v2ray.service failed.

journalctl -u执行结果如下
Failed at step CAPABILITIES spawning /usr/bin/v2ray/v2ray: Invalid argument

只有注释配置文件中的
#AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
才能启动

系统坐标 Centos7.8.2003
使用的是官方一件脚本

**Comment by the0demiurge** [comment]
我也遇到了同样的问题

**Comment by Devil-Cong** [comment]
我也遇到了同样的问题+1

**Comment by bigbugcc** [comment]
可通过修改服务脚本解决这个问题 修改脚本的执行用户即可
