### ISSUE TITLE
请问如何查看所有的访问日志

### ISSUE THREAD

**Issue by cxy2333355** [233boy/v2ray#631]
请问如何查看所有的访问日志，麻烦大佬解答一下

**Comment by Shangbaize-Daoye** [comment]
一般是 vim /etc/v2ray/access.log

**Comment by cxy2333355** [comment]
> 一般是 vim /etc/v2ray/access.log

打开了，但是还是没有诶，
![DY5G~RNOSBQ_SF(%}VSZ$B7](https://user-images.githubusercontent.com/69045706/89092144-c128cb80-d3e1-11ea-880c-dbf9a85d25d9.jpg)

**Comment by cxy2333355** [comment]
每次看日志只能看到当天一部分的

**Comment by Shangbaize-Daoye** [comment]
弄错了，应该是 vim /var/log/v2ray/access.log。里面包含了所有的记录，在vim里按大写的G可以直接到底看最近的记录。PgUp和PgDn可以上线翻滚。

**Comment by cxy2333355** [comment]
> 弄错了，应该是 vim /var/log/v2ray/access.log。里面包含了所有的记录，在vim里按大写的G可以直接到底看最近的记录。PgUp和PgDn可以上线翻滚。
大佬，我刚刚试了一下，还是不行，不知道为什么，按shift+pgup/dn,只是显示y/s，感觉是在输入，按esc还不能退出编辑，返回最开始的界面编辑命令

**Comment by cxy2333355** [comment]
![I0{_O%PS1X@H%QHH)8AHK59](https://user-images.githubusercontent.com/69045706/89092469-9724d880-d3e4-11ea-9cb1-5fc828ffbe89.png)

**Comment by Shangbaize-Daoye** [comment]
那你看看vim /etc/v2ray/config.json里log里面access写的地址是啥。

**Comment by cxy2333355** [comment]
地址是对的，刚刚看了是那个
![F}K8Q4{V1M0{%T7NS6}X1Z6](https://user-images.githubusercontent.com/69045706/89092992-fa186e80-d3e8-11ea-9ca9-28398fa11985.png)
对了大佬我进去查看后，没办法退出vim，按esc如何点q没有反应，按ctrl+c,也没有退出


> 那你看看vim /etc/v2ray/config.json里log里面access写的地址是啥。

大佬，地址是对的，刚刚看了是那个
![F}K8Q4{V1M0{%T7NS6}X1Z6](https://user-images.githubusercontent.com/69045706/89092992-fa186e80-d3e8-11ea-9ca9-28398fa11985.png)
对了大佬我进去查看后，没办法退出vim，按esc如何点q没有反应，按ctrl+c,也没有退出，按网上Linux的退出保存命令好像没有用

**Comment by Shangbaize-Daoye** [comment]
多按几次esc退出到命令模式，关闭是":q"，你少了冒号。保存是":w"，强制退出不保存是":q!"

**Comment by cxy2333355** [comment]
> 多按几次esc退出到命令模式，关闭是":q"，你少了冒号。保存是":w"，强制退出不保存是":q!"

哦哦，刚刚我又看了一遍访问日志，还是只有今天的，往前的可能没有了。谢谢大佬指导，非常感谢你！

**Comment by xhqpp** [comment]
sudo tail -1000 /var/log/v2ray/access.log
