### ISSUE TITLE
WS+TLS间歇性中断

### ISSUE THREAD

**Issue by xhqpp** [233boy/v2ray#638]
具体表现为有时无法打开Google，但是同时Youtube可以打开
或者刚开始可以打开Google，但是重开浏览器后无法打开
测试打不开google.com时把地址改为google.com.hk则可以正常打开
一开始以为是DNS的问题，后来查看DNS并无污染
中断持续时间大概几十秒，后续会自行恢复

有人有这样的问题吗

**Comment by 1608637229** [comment]
遇到过。

**Comment by Hi-Young** [comment]
用了一段时间ws+tls  以为找到了更稳定更好的方法 现在又回到裸奔状态了

**Comment by sisinet** [comment]
是的，我也遇到这样的问题。不知道如何解决

**Comment by derekdi** [comment]
这个脚本好久没更新了 估计原作者也不维护了 建议换一个脚本

**Comment by maxmax999** [comment]
我的也是呃，换官方脚本安装正常

**Comment by wonius** [comment]
> 我的也是呃，换官方脚本安装正常

官方脚本是哪个？

**Comment by derekdi** [comment]
> > 我的也是呃，换官方脚本安装正常
> 
> 官方脚本是哪个？

官方脚本设置起来比较复杂 可以上网找一些还在维护的第三方脚本

**Comment by hans362** [comment]
同样遇到这个问题，经过仔细排查，发现只要在 `/etc/v2ray/config.json` 中把
```json
"sniffing": {
	"enabled": true,
	"destOverride": [
		"http",
		"tls"
	]
}
```
修改成
```json
"sniffing": {
	"enabled": false
}
```
即关闭流量探测，该问题就不再复现，但仍不清楚开启流量探测为什么会导致这个问题。

**Comment by zhouscd** [comment]
233boy 的脚本里面，服务器端加入了很多 blocked 的规则，比如bittorrent流量就会 blocked 。建议在outbounds里把所有其他的配置都删除掉，就正常了....
