### ISSUE TITLE
v2ray和ss都用不了，status未运行

### ISSUE THREAD

**Issue by erfanw** [233boy/v2ray#639]
您好！首先感谢提供这么好用的傻瓜式脚本。想请问下，v2ray配置好后，使用`v2ray status`显示未在运行。使用`v2ray start`也不管用。SS和v2ray都用不了，换过很多端口也没用，请问这可能是什么情况呢？

装在微软azure虚拟机上，INBOUND和OUTBOUND全都设置成了所有协议所有端口全部通过。

**Comment by NXc9H7EC** [comment]
海归服务器:https://rs.aboutai.xyz

**Comment by Shangbaize-Daoye** [comment]
为什么不先提供一下status的输出内容呢

**Comment by erfanw** [comment]
> 为什么不先提供一下status的输出内容呢

红色的“未在运行”啊

**Comment by Shangbaize-Daoye** [comment]
未运行的原因有很多，权限不足或配置文件书写错误之类的。你不如手动运行一下v2看看有啥错误提示。
```bash
/usr/bin/v2ray/v2ray -config /etc/v2ray/config.json
```

**Comment by erfanw** [comment]
按您说的运行了，再查看status显示正在运行，可还是连不上。防火墙policy是全通...

**Comment by Kogava** [comment]
我也是这种情况，

/usr/bin/v2ray/v2ray -config /etc/v2ray/config.json
可以运行， 但是直接 v2ray start 显示启动失败

**Comment by nullTT** [comment]
我是这样操作的：

/usr/bin/v2ray/v2ray -config /etc/v2ray/config.json
可以正常运行， 用电脑也正常连接，可以完成SPEEDTEST测试。

然后CTRL+C结束， 再 v2ray start / v2ray restart 都不可以


通过/usr/bin/v2ray的日志：
2020/08/25 17:49:31 [Info] [3461316918] v2ray.com/core/app/dispatcher: sniffed domain: lh3.googleusercontent.com
2020/08/25 17:49:31 [Info] [3461316918] v2ray.com/core/app/dispatcher: default route for tcp:lh3.googleusercontent.com:443
2020/08/25 17:49:31 [Info] [3461316918] v2ray.com/core/proxy/freedom: opening connection to tcp:lh3.googleusercontent.com:443
2020/08/25 17:49:31 [Info] [3461316918] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:lh3.googleusercontent.com:443
2020/08/25 17:49:32 [Info] [2542354000] v2ray.com/core/proxy/vmess/inbound: received request for tcp:www.gstatic.com:443
2020/08/25 17:49:32 [Info] [2542354000] v2ray.com/core/app/dispatcher: sniffed domain: www.gstatic.com
2020/08/25 17:49:32 [Info] [2542354000] v2ray.com/core/app/dispatcher: default route for tcp:www.gstatic.com:443
2020/08/25 17:49:32 [Info] [2542354000] v2ray.com/core/proxy/freedom: opening connection to tcp:www.gstatic.com:443
2020/08/25 17:49:32 [Info] [2542354000] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:www.gstatic.com:443
2020/08/25 17:49:33 [Info] [2085982649] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/encoding: failed to read request header > EOF

**Comment by HKTY569** [comment]
我也是
![LG` VX)N@ EU3UN3 })V76R](https://user-images.githubusercontent.com/35788811/91635569-0e9c5680-e9e9-11ea-8587-c97acb7e5f8c.png)
![6WM8 LTV)NJC(_X9HT{}XTR](https://user-images.githubusercontent.com/35788811/91635572-10661a00-e9e9-11ea-873c-c12c4ab536a5.png)

**Comment by Shangbaize-Daoye** [comment]
你们要不直接试试service v2ray start和service v2ray status

**Comment by HKTY569** [comment]
> service v2ray status
不好用~~
![ZQVUY_3F_Q_6YRBG H6W1 H](https://user-images.githubusercontent.com/35788811/91636315-14953600-e9ef-11ea-86be-07a3ba0dc30e.png)

**Comment by Shangbaize-Daoye** [comment]
原来如此啊，没有v2ray.service这个文件，你运行v2ray start当然会失败了

**Comment by HKTY569** [comment]
> 原来如此啊，没有v2ray.service这个文件，你运行v2ray start当然会失败了

那要创建v2ray.service这个文件啦？在哪创建啊？

**Comment by Shangbaize-Daoye** [comment]
手动创建一个v2ray.service放进/lib/systemd/system里。
然后运行systemctl enable v2ray.service
最后service v2ray start

但是现在最新的v2ray.service和以前老的v2ray.service内容不一样了。最新4.27.4的v2ray.service内容是
```
[Unit]
Description=V2Ray Service
Documentation=https://www.v2fly.org/
After=network.target nss-lookup.target

[Service]
User=nobody
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
NoNewPrivileges=true
ExecStart=/usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json
Restart=on-failure

[Install]
WantedBy=multi-user.target
```
你们要根据情况把ExecStart=...这部分命令改成你们现在用的老的命令，老的命令一般是
```
ExecStart=/usr/bin/v2ray/v2ray -config /etc/v2ray/config.json
```

**Comment by 233boy** [comment]
@nullTT 
已经修复了这个问题，无法运行的，你使用 `v2ray reinstall` 命令来重装一下就行了（

**Comment by erfanw** [comment]
thx

Best Regards,
Erfan

________________________________

**Comment by jinwyp** [comment]
推荐一个脚本 trojan trojan-go v2ray 全支持 https://github.com/jinwyp/one_click_script

**Comment by BruceWayne2099** [comment]
太奇怪了，我这里端口打开了，用自己的Mac  Telnet对应的shadowrocket端口 也通，但是白色小火箭链接但是还是无法成功获取信息...

**Comment by wenguonideshou** [comment]
#644

**Comment by lilien1010** [comment]
nohup /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json  > out.file 2>&1 &
也不行

**Comment by xiaoliu0802** [comment]
运行/usr/bin/v2ray/v2ray -config /etc/v2ray/config.json
这个可以使用，但是CTRL+C退出后就不行了，

**Comment by 1305381033** [comment]
安装好一直运行不了,这是什么问题
root@SuperBubbly-VM:~# service v2ray status
● v2ray.service - V2Ray Service
     Loaded: loaded (/lib/systemd/system/v2ray.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2022-11-29 17:32:34 CST; 6s ago
       Docs: https://www.v2ray.com/
             https://www.v2fly.org/
    Process: 14050 ExecStart=/usr/bin/env v2ray.vmess.aead.forced=false /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json (code=exited, status=2)
   Main PID: 14050 (code=exited, status=2)

Nov 29 17:32:34 SuperBubbly-VM systemd[1]: v2ray.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Nov 29 17:32:34 SuperBubbly-VM systemd[1]: v2ray.service: Failed with result 'exit-code'.
Nov 29 17:32:34 SuperBubbly-VM systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 5.
Nov 29 17:32:34 SuperBubbly-VM systemd[1]: Stopped V2Ray Service.
Nov 29 17:32:34 SuperBubbly-VM systemd[1]: v2ray.service: Start request repeated too quickly.
Nov 29 17:32:34 SuperBubbly-VM systemd[1]: v2ray.service: Failed with result 'exit-code'.
Nov 29 17:32:34 SuperBubbly-VM systemd[1]: Failed to start V2Ray Service.

**Comment by yathob** [comment]
用nohup /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json &      
后台启动，就能成功运行了
