### ISSUE TITLE
LEDEv0.3.4中V2Ray插件如下设置，局域网中其他设备还是无法连接。

### ISSUE THREAD

**Issue by yangleitj** [233boy/v2ray#64]
"inbound": {
        "port": 2333,
        "listen": "0.0.0.0",
        "protocol": "socks",
        "settings": {
            "auth": "noauth",
            "udp": true,
            "ip": "127.0.0.1"
        }

**Comment by jackytj** [comment]
酷软V2ray插件只看outbound部分
