### ISSUE TITLE
v2ray今天更新一键脚本安装出错了

### ISSUE THREAD

**Issue by Leapzhang** [233boy/v2ray#643]
2020-08-29 15:03:11 (3.59 MB/s) - ‘/tmp/v2ray.zip’ saved [13242072/13242072]

Archive:  /tmp/v2ray.zip
  inflating: /usr/bin/v2ray/config.json
  inflating: /usr/bin/v2ray/geoip.dat
  inflating: /usr/bin/v2ray/geosite.dat
   creating: /usr/bin/v2ray/systemd/
   creating: /usr/bin/v2ray/systemd/system/
  inflating: /usr/bin/v2ray/systemd/system/v2ray.service
  inflating: /usr/bin/v2ray/systemd/system/v2ray@.service
  inflating: /usr/bin/v2ray/v2ctl
 extracting: /usr/bin/v2ray/v2ctl.sig
  inflating: /usr/bin/v2ray/v2ray
 extracting: /usr/bin/v2ray/v2ray.sig
  inflating: /usr/bin/v2ray/vpoint_socks_vmess.json
  inflating: /usr/bin/v2ray/vpoint_vmess_freedom.json
cp: cannot stat ‘/usr/bin/v2ray/systemd/v2ray.service’: No such file or director             y
sed: can't read /lib/systemd/system/v2ray.service: No such file or directory
Failed to execute operation: No such file or directory
Failed to restart v2ray.service: Unit not found.

**Comment by jiahaoliang** [comment]
什么平台？如果是linux的话提供一下 uname -a的结果

**Comment by CliffHan** [comment]
我也遇到这个问题，Debian 9, Ubuntu 18.04/20.04 都是一样的报错

**Comment by liji123** [comment]
我还以为是我系统的问题。。。。好像v2ray.service没创建，启动不了？我直接自己建了个v2ray.service，暂时能跑了。

**Comment by CliffHan** [comment]
我看了一下https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh
似乎是最新的v2ray.zip里，需要把v2ray.service放到/etc/systemd/system/

**Comment by HKTY569** [comment]
> 好像v2ray.service没创造，启动不了？我直接自己建了个v2ray.service，暂时能跑了。
问下你是怎么创建的？

**Comment by CliffHan** [comment]
v2ray.service需要放到/etc/systemd/system/
原来的/etc/v2ray/config.json需要放到/usr/local/etc/v2ray/config.json
不知道为什么会有这两个改动……

**Comment by HKTY569** [comment]
> v2ray.service需要放到/ etc / systemd / system /
> 原来的/etc/v2ray/config.json需要放到/usr/local/etc/v2ray/config.json
> 不知道为什么会有这两个替换……
我挪动/etc/v2ray/config.json到/usr/local/etc/v2ray/config.json可是显示下面这个错误
mv: cannot move '/etc/v2ray/config.json' to '/usr/local/etc/v2ray/config.json': No such file or directory

**Comment by CliffHan** [comment]
> > v2ray.service需要放到/ etc / systemd / system /
> > 原来的/etc/v2ray/config.json需要放到/usr/local/etc/v2ray/config.json
> > 不知道为什么会有这两个替换……
> > 我挪动/etc/v2ray/config.json到/usr/local/etc/v2ray/config.json可是显示下面这个错误
> > mv: cannot move '/etc/v2ray/config.json' to '/usr/local/etc/v2ray/config.json': No such file or directory

这两个替换原因可能不一样，临时修改的话，我建议你这么搞：
1. 从github上下载v2ray.zip，解压后将v2ray.service拷贝到/etc/systemd/system/
2. 创建/usr/local/etc/v2ray目录，把config.json拷贝过去
先说清楚我没测过，这会没时间，过几个小时才有时间试验一下。
正式修改应该也不困难。我就不考虑提交patch了

**Comment by 233boy** [comment]
@Leapzhang 已经修复了这个问题，无法运行的，你使用 `v2ray reinstall` 命令来重装一下就行了（

**Comment by Leapzhang** [comment]
> @Leapzhang 已经修复了这个问题，无法运行的，你使用 `v2ray reinstall` 命令来重装一下就行了（

谢谢
