### ISSUE TITLE
v2ray的版本更新到v4.27.4，然后这个脚本失效了

### ISSUE THREAD

**Issue by chnpeople** [233boy/v2ray#644]
旧的版本v.4.27.0正常，用脚本新建的不能运行。

**Comment by HKTY569** [comment]
大佬你有v.4.27.0的脚本吗？

**Comment by Shangbaize-Daoye** [comment]
v4.27.4好像有人更新了v2ray.service内容。你得手动操作v2ray.service文件。
可以看看这个https://github.com/233boy/v2ray/issues/639#issuecomment-683284976

**Comment by crazypeace** [comment]
如果 4.27 是正常的，那先曲线救国一下，把233脚本下载之后，再修改脚本指定下载4.27的v2ray就可以了吗？

**Comment by crazypeace** [comment]
https://github.com/crazypeace/v2ray 
这是一个将最新v2ray版本写死为 v4.27.0 的修改版本

**Comment by chnpeople** [comment]
> https://github.com/crazypeace/v2ray
> 这是一个将最新v2ray版本写死为v4.27.0的修改版本
> 经验证可行

谢谢大佬！

**Comment by 233boy** [comment]
@crazypeace 已经修复了这个问题，无法运行的，你使用 `v2ray reinstall` 命令来重装一下就行了（

**Comment by flzyup** [comment]
这个问题是因为这个安装脚本不知什么原因丢失了启动的service脚本文件，经测试如下方案可行：
```
sudo vim /lib/systemd/system/v2ray.service
```
加入如下内容：
```
[Unit]
Description=V2Ray Service
Documentation=https://www.v2ray.com/ https://www.v2fly.org/
After=network.target nss-lookup.target

[Service]
# If the version of systemd is 240 or above, then uncommenting Type=exec and commenting out Type=simple
#Type=exec
Type=simple
# This service runs as root. You may consider to run it as another user for security concerns.
# By uncommenting User=nobody and commenting out User=root, the service will run as user nobody.
# More discussion at https://github.com/v2ray/v2ray-core/issues/1011
User=root
#User=nobody
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
NoNewPrivileges=true
ExecStart=/usr/bin/v2ray/v2ray -config /etc/v2ray/config.json
Restart=always

[Install]
WantedBy=multi-user.target
```

然后执行:
```
sudo systemctl enable v2ray
sudo systemctl start v2ray
```

**Comment by HKTY569** [comment]
> @crazypeace 已经修复了这个问题，无法运行的，你使用 `v2ray reinstall` 命令来重装一下就行了（

好了，谢谢大佬

**Comment by ood0boo** [comment]
> @crazypeace 已经修复了这个问题，无法运行的，你使用 `v2ray reinstall` 命令来重装一下就行了（

tks

**Comment by xunjueyulin** [comment]
> @crazypeace 已经修复了这个问题，无法运行的，你使用 `v2ray reinstall` 命令来重装一下就行了（

感谢大佬，但是我v2ray reinstall后重新一键脚本后，win10使用v2rayN还是会报错，提示
`2020/08/31 16:44:09 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF`
但是在vps端是看错误日志倒是什么都没有，

**Comment by jiahaoliang** [comment]
> > @crazypeace 已经修复了这个问题，无法运行的，你使用 `v2ray reinstall` 命令来重装一下就行了（
> 
> 感谢大佬，但是我v2ray reinstall后重新一键脚本后，win10使用v2rayN还是会报错，提示
> `2020/08/31 16:44:09 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF`
> 但是在vps端是看错误日志倒是什么都没有；
> 尝试将kcp协议更换成tcp就可以了，不知道是什么道理

你服务器端用了TCP协议，客户端就只能用TCP，不能用KCP

**Comment by jinwyp** [comment]
推荐一个脚本 trojan trojan-go v2ray 全支持 https://github.com/jinwyp/one_click_script
