### ISSUE TITLE
想知道旧的版本怎么安装。。。

### ISSUE THREAD

**Issue by zjb76** [233boy/v2ray#645]

**Comment by 233boy** [comment]
@zjb76 
已经修复了这个问题，无法运行的，你使用 `v2ray reinstall` 命令来重装一下就行了（

**Comment by HKTY569** [comment]
好的谢谢，我试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "233boy/v2ray"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月30日(星期天) 上午10:10
收件人:&nbsp;"233boy/v2ray"<v2ray@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [233boy/v2ray] 想知道旧的版本怎么安装。。。 (#645)





 
@zjb76
 已经修复了这个问题，无法运行的，你使用 v2ray reinstall 命令来重装一下就行了（

**Comment by zjb76** [comment]
我好像还是连不上，显示正在运行但是tcping -1。。

**Comment by HKTY569** [comment]
> @ zjb76已经
> 修复了这个问题，无法运行的，你使用`v2ray reinstall`命令来重装一下就行了（

好了，可以运行了，谢谢大佬
