### ISSUE TITLE
v2ray怎么隐藏源ip？

### ISSUE THREAD

**Issue by mohanfeng3** [233boy/v2ray#646]
求各位大神指导下，怎么隐藏源ip，现在能正常上国外网站，就是在ip111.cn 或者是谷歌直接搜ip，查出来的定位还是本身的ip位置，求教下怎么修改隐藏源ip，谢谢

**Comment by mohanfeng3** [comment]
需要隐藏的是本机ip，不是服务器的，就是我谷歌搜ip显示的地理位置是国外的就可以了

**Comment by syouko** [comment]
客户端全局代理就行
