### ISSUE TITLE
配置后无法翻墙报这个错误是什么意思？

### ISSUE THREAD

**Issue by callmewayne** [233boy/v2ray#647]
failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp xxx.xxx.xxxx.:xxxx: i/o timeout] > v2ray.com/core/common/retry: all retry attempts failed

**Comment by callmewayne** [comment]
accepted tcp:content-autofill.googleapis.com:443

**Comment by dongzeyu** [comment]
I have met the same problem, did you solve it?

**Comment by jinwyp** [comment]
try this script https://github.com/jinwyp/one_click_script

**Comment by wenguonideshou** [comment]
#644
