### ISSUE TITLE
url 中 alterId 没有被修改为0

### ISSUE THREAD

**Issue by lyplft** [233boy/v2ray#650]
安装后，url 链接添加入客户端后，alterId 还是233

**Comment by Denny-Dong** [comment]
顶一下，我也遇到了这个问题。需要手动设置alterId 为0才行
@233boy 能否帮忙修复一下？

**Comment by Pidbid** [comment]
同样遇到这个问题，需手动修改才可使用！

**Comment by no-today** [comment]
/etc/v2ray/config.json 的 alterId 为 0

v2ray info 展示的 alterId 为 233

难怪一直连不上，坑啊

**Comment by 233boy** [comment]
@Denny-Dong 
@no-today 
@lyplft 
@Pidbid 
不好意思。。 😢 
已经修复了，使用 `v2ray U` 更新一下脚本。。就可以了。
很抱歉

**Comment by 233boy** [comment]
如果还是不行，建议使用 `v2ray ai` 来更改一下 aliterid，
或者关注一下我的 TG 频道 https://t.me/tg2333

**Comment by smdx** [comment]
> 如果还是不行，建议使用 `v2ray ai` 来更改一下 alterid，
> 或者关注一下我的 TG 频道 https://t.me/tg2333

你好，更新了4.28.1后请问在服务端要怎么使用VLESS协议啊？谢谢
