### ISSUE TITLE
遇到了奇怪的问题

### ISSUE THREAD

**Issue by jacklang1996** [233boy/v2ray#651]
v2rayN连接时报错
“[Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF”
然后检查两边系统时间，都是自动同步的相差很小。
同时，之前7月份时用脚本配置的服务器是可以正常使用的，这两天新配置就会出现这个问题，检查了一下两个服务器和电脑的时间基本没有差别，很奇怪。

**Comment by ood0boo** [comment]
同样，MAC有问题，IPhone正常。

**Comment by lyplft** [comment]
更新一下脚本。重新输出一下url 或者看看你的客户端 额外ID是不是不是0 如果不是修改成0试试。
