### ISSUE TITLE
v2ray 无法启动

### ISSUE THREAD

**Issue by fybandei** [233boy/v2ray#652]
使用centos7.8 x64，使用脚本后v2ray可正常使用。
为使用锐速，内核版本降低到3.10.0-229.1.2.el7.x86_64。
使用 v2ray start之后，显示：
 V2Ray 已启动
使用v2ray status之后 显示：
V2Ray 状态: 未在运行
 当前 V2Ray 版本: v4.28.1  /  当前 V2Ray 管理脚本版本: v3.37。
尝试v2ray reinstall，无效，尝试更新内核至.10.0-327.el7.x86_64，无效。
另一台centos7.6 降内核后可正常使用，跪求解决方法。

**Comment by cesar-commit** [comment]
我的也是这样，v2ray start显示已运行，接着输入v2ray status却显示不在运行。我是Ubuntu 18的。

**Comment by wenguonideshou** [comment]
#644
参考这个issue和解决办法
crazypeace的办法亲测可用

**Comment by fybandei** [comment]
> #644
> 参考这个issue

感谢回复，已经试过，无效。

**Comment by 233boy** [comment]
@fybandei 
一般来说，很有 可能是因为 端口 冲突造成的，你使用 `v2ray config` 更改一下端口试试看。

**Comment by fybandei** [comment]
> @fybandei
> 一般来说，很有 可能是因为 端口 冲突造成的，你使用 `v2ray config` 更改一下端口试试看。
感谢大佬回复，已经试过了，还是无效。
因为v2ray没运行过，就没有错误日志。
使用
journalctl -u v2ray.service
后，发现
Sep 19 23:45:24 vm221320.u85683.kvm.centos.7.64 systemd[1]: v2ray.service: main process exited, code=exited, status=218/CAPABILITIES
Sep 19 23:45:24 vm221320.u85683.kvm.centos.7.64 systemd[1]: Unit v2ray.service entered failed state.
Sep 19 23:45:24 vm221320.u85683.kvm.centos.7.64 systemd[1]: v2ray.service failed.
Sep 19 23:45:24 vm221320.u85683.kvm.centos.7.64 systemd[1]: v2ray.service holdoff time over, scheduling restart.
Sep 19 23:45:24 vm221320.u85683.kvm.centos.7.64 systemd[1]: Stopped V2Ray Service.
Sep 19 23:45:24 vm221320.u85683.kvm.centos.7.64 systemd[1]: start request repeated too quickly for v2ray.service
Sep 19 23:45:24 vm221320.u85683.kvm.centos.7.64 systemd[1]: Failed to start V2Ray Service.
Sep 19 23:45:24 vm221320.u85683.kvm.centos.7.64 systemd[1]: Unit v2ray.service entered failed state.
Sep 19 23:45:24 vm221320.u85683.kvm.centos.7.64 systemd[1]: v2ray.service failed.

搜索到其他类似问题[#630 ](url)，也注释了配置文件中的
#AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
但是依其所说还是无解。

继续研究。

**Comment by fybandei** [comment]
> @fybandei
> 一般来说，很有 可能是因为 端口 冲突造成的，你使用 `v2ray config` 更改一下端口试试看。

感谢大佬回复，已经试过了，还是无效。
因为v2ray没运行过，就没有错误日志。
使用
journalctl -u v2ray.service
后，发现
Sep 19 23:45:24 vm221320.u85683.kvm.centos.7.64 systemd[1]: v2ray.service: main process exited, code=exited, status=218/CAPABILITIES
Sep 19 23:45:24 vm221320.u85683.kvm.centos.7.64 systemd[1]: Unit v2ray.service entered failed state.
Sep 19 23:45:24 vm221320.u85683.kvm.centos.7.64 systemd[1]: v2ray.service failed.
Sep 19 23:45:24 vm221320.u85683.kvm.centos.7.64 systemd[1]: v2ray.service holdoff time over, scheduling restart.
Sep 19 23:45:24 vm221320.u85683.kvm.centos.7.64 systemd[1]: Stopped V2Ray Service.
Sep 19 23:45:24 vm221320.u85683.kvm.centos.7.64 systemd[1]: start request repeated too quickly for v2ray.service
Sep 19 23:45:24 vm221320.u85683.kvm.centos.7.64 systemd[1]: Failed to start V2Ray Service.
Sep 19 23:45:24 vm221320.u85683.kvm.centos.7.64 systemd[1]: Unit v2ray.service entered failed state.
Sep 19 23:45:24 vm221320.u85683.kvm.centos.7.64 systemd[1]: v2ray.service failed.

搜索到其他类似问题#630 ，也注释了配置文件中的
#AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
但是依其所说还是无解。

继续研究。

**Comment by fybandei** [comment]
已解决，硬是上传了个centos7.2的系统。

**Comment by q383186554** [comment]
怎么解决的 说一下啊 急急急

**Comment by 1592312635** [comment]
> 
是cecntos版本问题吗
