### ISSUE TITLE
Caddy 一直无法运行 导致服务无法使用

### ISSUE THREAD

**Issue by CANBAAA** [233boy/v2ray#653]
[root@aaaa ~]# v2ray status

 V2Ray 状态: 正在运行  /  Caddy 状态: 未在运行

[root@aaaa ~]# systemctl restart caddy
[root@aaaa ~]# v2ray status

 V2Ray 状态: 正在运行  /  Caddy 状态: 正在运行

[root@aaaa ~]# v2ray status

 V2Ray 状态: 正在运行  /  Caddy 状态: 正在运行

[root@aaaa ~]# v2ray status

 V2Ray 状态: 正在运行  /  Caddy 状态: 未在运行

[root@aaaa ~]# v2ray status

 V2Ray 状态: 正在运行  /  Caddy 状态: 未在运行

[root@aaaa ~]# v2ray status

 V2Ray 状态: 正在运行  /  Caddy 状态: 未在运行

重装也没用。。。这要怎么办

**Comment by wenguonideshou** [comment]
#644 
参考这个issue和解决办法

**Comment by jinwyp** [comment]
可以用这个脚本 https://github.com/jinwyp/one_click_script
