### ISSUE TITLE
不管怎么安装，安装好了之后查看url一直报错

### ISSUE THREAD

**Issue by TomsDay** [233boy/v2ray#654]
系统：Debian 9 x86_64
传输协议：tcp/mkcp
端口号：443
安装完成后不管什么操作都在报错
报错内容：哎呀哎呀…… 出错咯...请重新安装V2Ray ~(^_^)

**Comment by 233boy** [comment]
重装系统，换 Debian 9 再来试试看。

**Comment by TomsDay** [comment]
> 重装系统，换 Debian 9 再来试试看。

好的，非常感谢，我再试试
