### ISSUE TITLE
 安装 Caddy 出错！

### ISSUE THREAD

**Issue by baiguke2019** [233boy/v2ray#655]
WebSocket + TLS

cp: cannot create regular file '/usr/local/bin/': Not a directory
 安装 Caddy 出错！

**Comment by 233boy** [comment]
@baiguke2019 
你什么系统 啊。。。`/usr/local/bin` 竟然有问题。。。

**Comment by baiguke2019** [comment]
> @ baiguke2019
> 你什么系统啊。。。`/usr/local/bin`竟然有问题。。。。

ubuntu 18

**Comment by baiguke2019** [comment]
换debian了 好了
