### ISSUE TITLE
由于挖掘加密货币（挖矿），与您的项目 CloudVPS (id: cloudvps-289511) 关联的资源因违反我们的免费试用服务条款而被暂停

### ISSUE THREAD

**Issue by shenchihua** [233boy/v2ray#656]
概要
由于挖掘加密货币（挖矿），与您的项目 CloudVPS (id: cloudvps-289511) 关联的资源因违反我们的免费试用服务条款而被暂停。
 
详细信息
受影响的项目/虚拟机：CloudVPS (id: cloudvps-289511)/

说明：因从虚拟机 挖掘加密货币（挖矿）而违反了我们的免费试用服务条款，进而导致虚拟机实例被暂停。

时间范围：从 2020-09-21 02:53 到 2020-09-21 03:00（美国太平洋时间）

**Comment by neciszhang** [comment]
这是什么鸟问题？

**Comment by heiye1024** [comment]
很大可能 vps 被入侵中了挖矿程序吧

**Comment by ssnnow** [comment]
这个版本的 caddy 有bug，感觉可以被外部执行任意指令，我这边的进程中也看到caddy用户在跑挖矿程序

**Comment by jymr92** [comment]
操，难道脚本里有木马程序

**Comment by ssnnow** [comment]
脚本里是没有木马程序的，我觉得是 caddy的问题。
