### ISSUE TITLE
请问shadowsocks的配置文件在哪里。

### ISSUE THREAD

**Issue by xiaoze1332** [233boy/v2ray#657]
感谢作者的脚本。233boy久负盛名。
不过我想修改配置文件缺没有找到位置，wiki里的我都看了也没找到。

**Comment by 233boy** [comment]
@xiaoze1332 
建议使用 `v2ray config` 来更改 shadowsocks 配置

如果你确实想要手动更改配置的话，更改 `/etc/v2ray/config.json` 即可
