### ISSUE TITLE
ubuntu下的v2ray  怎样翻墙呢  求助

### ISSUE THREAD

**Issue by henbucuoshanghai** [233boy/v2ray#658]

**Comment by Bella722** [comment]
ubuntu下的软件中心搜索qv2ray安装，再找个账号登录就可以了

**Comment by henbucuoshanghai** [comment]
大佬 厉害 我按你说的安装好  把连接塞进去  点击激活  提示没有core   请问怎么回事

**Comment by henbucuoshanghai** [comment]
qv2ray core executable not found

**Comment by Bella722** [comment]
https://bella722.github.io/post/a231f91f.html按照这个方法配置

**Comment by henbucuoshanghai** [comment]
厉害。。   我装了个core   后面就没看了    然后就连了。。。      多谢多谢  找对人还是快。。。
