### ISSUE TITLE
有些网站不能访问

### ISSUE THREAD

**Issue by pubshare2** [233boy/v2ray#659]
比如**元之类的，不能访问，这个DNS的问题，还是在哪个配置文件里面控制？

**Comment by ablebodied** [comment]
可以自己去 /etc/v2ray/config.json 里面把那一堆网址删掉

**Comment by xiaoshenwl** [comment]
> 可以自己去 /etc/v2ray/config.json 里面把那一堆网址删掉

请问如何进入该目录
