### ISSUE TITLE
此脚本的Shadowsocks装的是python版还是libev 版？

### ISSUE THREAD

**Issue by ikkyusan123** [233boy/v2ray#66]
Shadowsocks服务端有Shadowsocks-Python， Shadowsocks-Go， Shadowsocks-libev 4种版本，请问此脚本中的是哪个版本？

**Comment by rhotov** [comment]
补充一下，用这个脚本之后不建议再用其它脚本单独安装SS/SSR，可能会有各种奇怪的问题。
