### ISSUE TITLE
v2ray已经支持VLESS+XTLS，大佬能否更新支持一下VLESS

### ISSUE THREAD

**Issue by liwenjie119** [233boy/v2ray#660]
https://www.v2fly.org/config/protocols/vless.html
https://github.com/v2fly/v2ray-core/releases/tag/v4.30.0

**Comment by gearfox** [comment]
是啊。。。

**Comment by shuishou4184** [comment]
还是233大佬的脚本用着舒心，期盼早日更新

**Comment by ardayan** [comment]
vless脚本推荐atrandys的。。。大家可以自己琢磨手动安装啦，安装程序，申请证书，编译安装nginx，然后配置直接套模版复制粘贴，一点也不难。vmess真的可以抛弃了，目前客户端mac win和安卓基本都支持了xtls，vless+xtls性能大增，回落功能既可以建站，又可以与vless+wss等共存，真香。

**Comment by jinwyp** [comment]
推荐一个终极脚本 支持 trojan-go trojan v2ray 共存,带可视化面板,升级和卸载,自动证书续签.可以修改root和ssh端口,支持WS+CDN，Vless和xtls 模式 https://github.com/jinwyp/one_click_script

**Comment by chancat87** [comment]
凉了…换脚本吧

**Comment by ardayan** [comment]
因为233停更 学会了编译nginx 学会了安装证书 学会了自己修改配置文件

**Comment by lylcaac** [comment]
今天更新脚本后发现已经支持VLESS了

**Comment by ardayan** [comment]
看了下配置，仍旧是caddy/nginx前置的ws分流，性能提升可能只有10%左右。。。应该使用VLESS over tcp, with TLS/XTLS，回落到ws，性能可以提高 50%+。
