### ISSUE TITLE
无法更新v2raycore

### ISSUE THREAD

**Issue by yinglight** [233boy/v2ray#663]
无法更新v2raycore,链接地址变了，所以无法下载。

**Comment by LeoYoung** [comment]
优先更新一下脚本，之后再尝试更新v2ray-core

亲测使用v3.37脚本，可以顺利更新v2ray-core到v4.31.0

**Comment by yinglight** [comment]
使用v3.37脚本,可是github中是3.0.5

**Comment by yinglight** [comment]
谢谢了

**Comment by MrPoopyLobster** [comment]
脚本版本显示为v3.37，更新v2raycore的url还是旧的，导致更新失败。title还是写着3.26，我是用的自己fork的code，是不是没更新成功？

**Comment by jinwyp** [comment]
推荐一个终极脚本 支持 trojan-go trojan v2ray 共存,带可视化面板,升级和卸载,自动证书续签.可以修改root和ssh端口,支持WS+CDN，Vless和xtls 模式 https://github.com/jinwyp/one_click_script
