### ISSUE TITLE
请问下怎么修改默认的名称

### ISSUE THREAD

**Issue by HenryJi529** [233boy/v2ray#664]
想把代理的名字改成hk0, jp1这样的,, ,除了在V2rayN这样的客户端上修改,有没有更方便的方法呀
<img width="388" alt="Screenshot 2020-10-16 at 19 49 42" src="https://user-images.githubusercontent.com/41288155/96255005-cc56c500-0fe8-11eb-9fa4-346368838994.png">

**Comment by Shangbaize-Daoye** [comment]
没有，这名字本来就是客户端配置文件里设置的名字，你还能去哪改？

**Comment by 529HenryMJi** [comment]
客户端配置文件里怎么会有233v2.com?这应该是服务端的吧

**Comment by crazypeace** [comment]
https://zelikk.blogspot.com/2020/10/233vmess-url.html
