### ISSUE TITLE
成功安装但无法正常使用

### ISSUE THREAD

**Issue by baoyudu** [233boy/v2ray#665]
使用justhost的主机，可以ssh连接，使用ssh可以ping通Google，使用一键脚本成功安装，但是无法访问外网，使用windows和Android端都不行
![image](https://user-images.githubusercontent.com/13388614/96327174-da98f580-1069-11eb-9a8b-ee81937ece6b.png)

**Comment by anonlooker** [comment]
我之前用俄罗斯justhost也是不行

**Comment by anonlooker** [comment]
和你的情况一样
