### ISSUE TITLE
在宿舍网不可用;手机流量可用;宿舍网+不同服务器可用

### ISSUE THREAD

**Issue by Erial21** [233boy/v2ray#667]
学校宿舍的网络连自己的服务器，翻墙速度极慢。
换成流量连接同一个服务器之后速度正常。
学校教学楼的WiFi连接同一个服务器速度也很快。
然后是连接隔壁宿舍的网络用同一个服务器，速度也正常。
然后就是宿舍的网络连接不同的服务器速度又正常。
没搞懂原因出在哪里，希望有大佬解答。
传输协议是ws+tls。

**Comment by anonlooker** [comment]
不知道-------- 原始邮件 --------发件人： Aerialith <notifications@github.com>日期： 2020年10月17日周六 下午2:20收件人： 233boy/v2ray <v2ray@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： [233boy/v2ray] 在宿舍网不可用;手机流量可用;宿舍网+不同服务器可用 (#667)
学校宿舍的网络连自己的服务器，翻墙速度极慢。
换成流量连接同一个服务器之后速度正常。
学校教学楼的WiFi连接同一个服务器速度也很快。
然后是连接隔壁宿舍的网络用同一个服务器，速度也正常。
然后就是宿舍的网络连接不同的服务器速度又正常。
没搞懂原因出在哪里，希望有大佬解答。
传输协议是ws+tls。

**Comment by crazypeace** [comment]
加了 cloudflare 的cdn吗？

可参考
https://guide.v2fly.org/advanced/cdn.html
https://github.com/v2ray/v2ray-core/issues/1742
