### ISSUE TITLE
想从ss迁来v2ray，服务安装完成后无法连接，救助~

### ISSUE THREAD

**Issue by yangeren** [233boy/v2ray#668]
## 服务搭建完成，但手机&电脑客户端无法连接，救助~
使用最新脚本在vultr centos 8 X64上安装完成，服务正常启动，端口：29654，vultr tcp 入站的防火墙已打开，但客户端测试连接总是失败，如何排查问题在哪？能否在本地测试

### 服务启动
![image](https://user-images.githubusercontent.com/3181945/96663395-2f4ab200-1383-11eb-8bab-57cf21420c58.png)

### v2ray端口图
![image](https://user-images.githubusercontent.com/3181945/96663581-83559680-1383-11eb-9d9f-f6dd7ec28aaa.png)

### 防火墙端口开放
![image](https://user-images.githubusercontent.com/3181945/96663678-b8fa7f80-1383-11eb-92dc-e9fa0229d814.png)

**Comment by Shangbaize-Daoye** [comment]
telnet那个端口看看端口是不是真的能访问。可以的话有可能是客户端设置有问题。

**Comment by jinwyp** [comment]
推荐一个终极脚本 支持 trojan-go trojan v2ray 共存,带可视化面板,升级和卸载,自动证书续签.可以修改root和ssh端口,支持WS+CDN，Vless和xtls 模式 https://github.com/jinwyp/one_click_script
