### ISSUE TITLE
墙升级了么？今天旧服务器被墙，新部署一台服务器，一键安装后，客户端无法翻墙

### ISSUE THREAD

**Issue by fatwang2000** [233boy/v2ray#669]
今天用了很久的一台vultr的服务器突然墙了，ip地址ping不通了，于是重新部署一台新服务器，用一键安装脚本设置好v2ray之后，客户端依然翻不出去，无论换协议还是换端口，都没用。是今天墙升级了么？有什么解决办法

**Comment by nilfei** [comment]
一样，回滚到kcp+ss 没有问题

**Comment by zeasonvan** [comment]
单v2ray无法运行，ss则没问题
