### ISSUE TITLE
校园网无法翻出去但热点可以？

### ISSUE THREAD

**Issue by TomatoRabbit** [233boy/v2ray#672]
如题，使用校园网时(有线or无线) v2rayN能ping通vps而且它自带的测速都能通过，但是无法连上任何外网（能访问墙内网）。但是使用手机热点就能翻出去。试过几个地区的服务器都这样，请教大佬这是什么情况，是校园网有限制吗？

**Comment by KyonCN** [comment]
大概率你们学校是端口白名单制度 你把服务器端口改到443或者80试试

**Comment by wf09** [comment]
可能是dns的问题

**Comment by TomatoRabbit** [comment]
> 大概率你们学校是端口白名单制度 你把服务器端口改到443或者80试试
改成他俩还是不行~2333

**Comment by crazypeace** [comment]
加了 cloudflare 的cdn吗？

可参考
https://guide.v2fly.org/advanced/cdn.html
v2ray/v2ray-core#1742

**Comment by 2306681547** [comment]
我也是

**Comment by gbbh** [comment]
同样问题，校园网用有线无法使用，但连接无线可以使用

**Comment by crazypeace** [comment]
排错教程
* 排错
[V2ray Websocket + TLS 模式 第一次搭梯子 排错指引](https://zelikk.blogspot.com/2022/04/setup-v2ray-websocket-tls-troubleshoot.html)
[V2Ray Websocket + TLS 模式 梯子没问题 查自己的问题 排错指引](https://zelikk.blogspot.com/2022/04/connect-v2ray-websocket-tls-troubleshoot.html) （比如别人能用就你不能用，或者一直能用突然不能用）

**Comment by jiukeeeeee** [comment]
> 同样问题，校园网用有线无法使用，但连接无线可以使用

一样的情况，请问解决了吗

**Comment by chamberxxx** [comment]
网线连接不能是中文
设置vpn自动连接设置

**Comment by chamberxxx** [comment]
> > 同样问题，校园网用有线无法使用，但连接无线可以使用
> 
> 
> 
> 一样的情况，请问解决了吗

**Comment by chamberxxx** [comment]
> > 同样问题，校园网用有线无法使用，但连接无线可以使用
> 
> 
> 
> 一样的情况，请问解决了吗

拨号连接名字不能是中文
然后高级选项
该vpn代理设置改成
自动检测设置

**Comment by chamberxxx** [comment]
拨号连接名字不能是中文
然后高级选项
该vpn代理设置改成
自动检测设置

重启电脑和魔法

**Comment by Timefying** [comment]
> 同样问题，校园网用有线无法使用，但连接无线可以使用

无线也无法使用

**Comment by xblxblxbl** [comment]
我也是这样，有没有大佬可以教教我

**Comment by lingmeng12** [comment]
有点奇怪，我们学校的网线接路由器能访问，但是直用网线连不行

**Comment by crazypeace** [comment]
> 有点奇怪，我们学校的网线接路由器能访问，但是直用网线连不行

是不是你们校园网第一次安装的时候记录了网口MAC.
你试试把网口MAC改为路由器的MAC 试试.

**Comment by sxhy** [comment]
> 拨号连接名称不能是中文 然后高级选项 该vpn代理设置改成 自动检测设置
> 
> 重新启动电脑和魔法

我靠nb

**Comment by crazypeace** [comment]
> 求助各位大佬， Mac连的学校 WIFI，翻不出去，用热点可以，怎么解决

先查清楚, IP封了吗? 端口封了吗?
https://tcp.ping.pe/

**Comment by yyds886912** [comment]
我是Windows端使用校园网可以翻出去，但是在安卓端用校园网连不通，只能用流量翻出去，有没有什么解决方案？

**Comment by zhuchangqing19-ship-it** [comment]
请问各位，连接校园网翻不了墙，但用流量可以翻。VPN的客服说是校园网拦截，这该怎么解决
