### ISSUE TITLE
更新了v4.32.0版本后这个问题

### ISSUE THREAD

**Issue by zhangyenull** [233boy/v2ray#673]
<img width="1266" alt="image" src="https://user-images.githubusercontent.com/13203670/97870512-072d5c80-1d4e-11eb-93b1-51c7bfbd01a0.png">

**Comment by jinwyp** [comment]
推荐一个终极脚本 支持 trojan-go trojan v2ray 共存,带可视化面板,升级和卸载,自动证书续签.可以修改root和ssh端口,支持WS+CDN，Vless和xtls 模式 https://github.com/jinwyp/one_click_script
