### ISSUE TITLE
v2ray status 未在运行

### ISSUE THREAD

**Issue by cuijieer** [233boy/v2ray#675]
![image](https://user-images.githubusercontent.com/24519126/97974630-d4916b80-1e02-11eb-8f4d-cf95ddd04b38.png)
这个状态怎么也连不上
但是执行/usr/bin/v2ray/v2ray -config /etc/v2ray/config.json 就可以成功访问
![image](https://user-images.githubusercontent.com/24519126/97974675-e83cd200-1e02-11eb-8a1b-08a8d5488cac.png)

脑阔疼  咋回事呢

**Comment by CDshuiyiha** [comment]
我也是这样，能ping通就是出不去。

**Comment by 233boy** [comment]
@cuijieer 换一个端口试试看

**Comment by crazypeace** [comment]
查一下v2ray的日志。 有可能是service运行的用户或者环境与你当前命令行的不一致。所以你用命令行可以跑，但是service跑不起来。
