### ISSUE TITLE
完全访问Just my sock需要梯子

### ISSUE THREAD

**Issue by wuxianghou** [233boy/v2ray#676]
根据介绍，感觉直接购买搬瓦工锝服务比自己搭建服务好，于是想购买教程里面推荐的just my sock的服务。但是发现组成环节的验证码是被墙了的，导致一直无法注册。
这个JS不能加载，导致一直无法注册 https://www.recaptcha.net/recaptcha/api.js

**Comment by exodusmulaggusi** [comment]
hey i need a working VMess server.........i want to create a working
napsternetV file.......


can you help me please.....?

**Comment by 233boy** [comment]
@wuxianghou 
你看看这个 https://bwgjms.com/post/justmysocks-register/

**Comment by w2816771** [comment]
> 根据介绍，感觉直接购买搬瓦工锝服务比自己搭建服务好，于是想购买教程里面推荐的just my sock的服务。但是发现组成环节的验证码是被墙了的，导致一直无法注册。
> 这个JS不能加载，导致一直无法注册 https://www.recaptcha.net/recaptcha/api.js

有拼单的么
