### ISSUE TITLE
刷Facebook评论和视频，TWITTER经常突然卡住断流

### ISSUE THREAD

**Issue by goolguy007** [233boy/v2ray#678]
不管用什么协议，浏览Facebook的评论，刷TWITTER的时候经常突然卡住，另外最近Google网页也是无法打开，而YouTube一直正常，希望可以找到原因吧，我用的阿里云香港，联通网络。

**Comment by 233boy** [comment]
@goolguy007 不知道是啥原因，建议换个 VPS，再测试一下是否会复现

**Comment by Solarex** [comment]
@goolguy007 有找到原因吗？我也遇到这个问题了

**Comment by flyfire** [comment]
@goolguy007 又找到原因吗？我最近也遇到这个问题了
