### ISSUE TITLE
请帮忙解答设VLESS的域名成功后是否要把CF里的云朵再次点成橙色

### ISSUE THREAD

**Issue by zhysas** [233boy/v2ray#679]
先把cloudflare里的云朵点灰，再VPS升级脚本，设置VLESS域名成功后，是否需要把CF里的云朵再次点成橙色？
设置成功后WIN客户端试过CF点灰和点成橙色都可正常使用，就是CF点成橙色网速较慢。
到底用不用把CF里的云朵再次点成橙色？谢谢！

**Comment by 233boy** [comment]
@zhysas 
橙色 = 使用 CF 中转流量，因为经过 CF 服务器中转，所以速度相对来说会比较慢，但是好处是，这个不用担心被封了。
灰色 = 仅使用 CF 解析，不使用 CF 中转。速度不会变慢，但是会存在被封的风险。

各有所好，你自己决定吧。

**Comment by zhysas** [comment]
谢谢大佬指点
