### ISSUE TITLE
纯ipv6主机，新脚本安装caddy报错

### ISSUE THREAD

**Issue by jbmmp** [233boy/v2ray#681]
以前安装好的升级没有问题，新安装的话caddy报错，caddy服务不能启动，不管是vmess-tls-web 还是vless-tls-web，希望能够更新解决，谢谢。

另外可以添加检测是否纯ipv6主机功能吗？

**Comment by jbmmp** [comment]
实在不知道哪里出差了，笨办法解决：
1、fork一份上一次的更新版本 750dcfc on Sep 15
https://github.com/jbmmp/v2ray/tree/master
2、git clone 到本地安装
git clone https://github.com/jbmmp/v2ray -b master
cd v2ray
chmod +x install.sh
./install.sh local
3、此时更新报错，需要
cd /etc/v2ray/233boy
rm -rf v2ray
git clone https://github.com/233boy/v2ray -b master
此时可以更新正常使用了，可以变更协议切换到vless

**Comment by crazypeace** [comment]
对。有时候回退版本是最好的解决方法。
如果想回退v2ray core的版本，可以参考这个 https://github.com/crazypeace/v2ray
