### ISSUE TITLE
v2ray服务器更换ip

### ISSUE THREAD

**Issue by r1is** [233boy/v2ray#684]
本人的v2ray运行在校园网环境内，校内IP为：172.28.176.xxx,公网出口IP为：117.160.xxx.xxx
这个服务目的是想运行在校内，用为中转，想配置为 172.28.176.xxx，可是每次配置都是公网IP，请问这个该怎么解决呢。
![image](https://user-images.githubusercontent.com/21257485/100003487-22e1cb00-2e01-11eb-80a3-b10e69b73f74.png)

**Comment by Zxilly** [comment]
这个是脚本本身的限制，因为有的云服务商网卡上给的是内网IP检测不到，所以是直接检测的外网IP，但是服务本身是绑定到端口的，和IP无关，你自己客户端填参数就好了，就是`v2ray url`不能用了

**Comment by crazypeace** [comment]
参考这个 https://zelikk.blogspot.com/2020/10/233vmess-url.html
用base64解码 编码 自己再生成个url
