### ISSUE TITLE
甲骨文云上安装不成功

### ISSUE THREAD

**Issue by lorrydong** [233boy/v2ray#685]
什么原因？
---------- V2Ray 配置信息 -------------

 地址 (Address) = <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 403 (Forbidden)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>403.</b> <ins>That’s an error.</ins>
  <p>Access is forbidden.  <ins>That’s all we know.</ins>

 端口 (Port) = 49344

 用户ID (User ID / UUID) = 1b9ded06-47c8-4c40-92dc-89ec6184214a

 额外ID (Alter Id) = 233

 传输协议 (Network) = tcp

 伪装类型 (header type) = http
<img width="887" alt="截屏2020-11-26 下午2 34 38" src="https://user-images.githubusercontent.com/57822102/100315967-8c75fb00-2ff4-11eb-91e7-2a25d30ff750.png">

**Comment by crazypeace** [comment]
需要把整个安装过程的日志拿出来。

**Comment by telnetpig** [comment]
地址被甲骨文替换了吧

**Comment by chen123liu123** [comment]
我的也是这样，问题解决了吗？

**Comment by lorrydong** [comment]
换了其他脚本工具



发自我的小米手机
在 chen123liu123 ***@***.***>，2021年4月22日 下午8:30写道：

我的也是这样，问题解决了吗？
