### ISSUE TITLE
Centos7使用  33项vless协议无法联网

### ISSUE THREAD

**Issue by honkerjin** [233boy/v2ray#686]
建立后，服务正常，日志中也无报错，分别用几台客户端及服务器交叉测试过，都无法访问网页，但可测试延迟时间。已多次检查配置项，均无错误。
服务端/客户端v2ray-code 版本：4.33.0
使用vmess协议均正常，一键部署vless则无法使用
PC客户端：V2rayN  安卓：v2rayNG

**Comment by honkerjin** [comment]
补充：服务端与客户端v2ray-code均为 4.33.0

**Comment by honkerjin** [comment]
使用vmess协议均正常，但无法使用一键部署的vless协议

**Comment by honkerjin** [comment]
> 建立后，服务正常，日志中也无报错，分别用几台客户端和服务器交叉测试过，都无法访问网页，但可测试延迟时间。已多次检查配置项，均无错误。
> 服务端/客户端v2ray-code版本：4.33.0
> 使用vmess协议均正常，一键部署vless则无法使用

**Comment by jinwyp** [comment]
推荐一个终极脚本 支持 trojan-go trojan v2ray 共存,带可视化面板,升级和卸载,自动证书续签.可以修改root和ssh端口,支持WS+CDN，Vless和xtls 模式 https://github.com/jinwyp/one_click_script

**Comment by aishaome** [comment]
在v2raN 没有VLESS协议，所以无法联网，需要用Qv2ray  客户端来配置

**Comment by honkerjin** [comment]
> 在v2raN没有VLESS协议，所以无法联网，需要用Qv2ray客户端来配置

![Uploading newscreen3647630.jpg…]()

**Comment by aishaome** [comment]
> 在v2raN没有VLESS协议，所以无法联网，需要用Qv2ray客户端来配置

安卓的v2ray可以链接(我测试过了)，PC端的需要Qv2ray

**Comment by honkerjin** [comment]
> > 在v2raN没有VLESS协议，所以无法联网，需要用Qv2ray客户端来配置
> 
> 安卓的v2ray可以链接(我测试过了)，PC端的需要Qv2ra
安卓我也用不了，V2rayN 3.27是有vless协议的，交叉测试过安卓PC多台都不行，所以是服务端的问题了。但日志却没有错误。延时也可以测试，这就奇怪了。DNS也没问题

**Comment by 1608637229** [comment]
你没看它的更新日志吗。4.33版本移除了对vless的支持。
因为开源的问题导致的，反正那边还争论了几天。
