### ISSUE TITLE
一键脚本安装的v2ray无法使用

### ISSUE THREAD

**Issue by IcyFeather233** [233boy/v2ray#688]
当前 V2Ray 版本: v4.33.0  /  当前 V2Ray 管理脚本版本: v3.42

v2rayN测试链接真延迟信息：操作超时
[Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://101.32.178.221:62599/):  > tls: first record does not look like a TLS handshake] > v2ray.com/core/common/retry: all retry attempts 

测试服务器速度信息：远程服务器返回错误
2020/11/30 20:21:14 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://101.32.178.221:62599/):  > tls: first record does not look like a TLS handshake] > v2ray.com/core/common/retry: all retry attempts failed
2020/11/30 20:21:14 [Warning] [1250103872] v2ray.com/core/proxy/http: failed to read response from speedtest-sgp1.digitalocean.com > unexpected EOF

conf.json配置：
{
        "log": {
                "access": "/var/log/v2ray/access.log",
                "error": "/var/log/v2ray/error.log",
                "loglevel": "warning"
        },
        "inbounds": [
                {
                        "port": 62599,
                        "protocol": "vmess",
                        "settings": {
                                "clients": [
                                        {
                                                "id": "3d59c1e5-8d79-46c1-9d41-50ef75765b14",
                                                "level": 1,
                                                "alterId": 0
                                        }
                                ]
                        },
                        "streamSettings": {
                                "network": "ws"
                        },
                        "sniffing": {
                                "enabled": true,
                                "destOverride": [
                                        "http",
                                        "tls"
                                ]
                        }
                }
                //include_ss
                //include_socks
                //include_mtproto
                //include_in_config
                //
        ],
        "outbounds": [
                {
                        "protocol": "freedom",
                        "settings": {
                                "domainStrategy": "UseIP"
                        },
                        "tag": "direct"
                },
                {
                        "protocol": "blackhole",
                        "settings": {},
                        "tag": "blocked"
        },
                {
                        "protocol": "mtproto",
                        "settings": {},
                        "tag": "tg-out"
                }
                //include_out_config
                //
        ],
        "dns": {
                "servers": [
                        "https+local://cloudflare-dns.com/dns-query",
                        "1.1.1.1",
                        "1.0.0.1",
                        "8.8.8.8",
                        "8.8.4.4",
                        "localhost"
                ]
        },
        "routing": {
                "domainStrategy": "IPOnDemand",
                "rules": [
                        {
                                "type": "field",
                                "ip": [
                                        "0.0.0.0/8",
                                        "10.0.0.0/8",
                                        "100.64.0.0/10",
                                        "127.0.0.0/8",
                                        "169.254.0.0/16",
                                        "172.16.0.0/12",
                                        "192.0.0.0/24",
                                        "192.0.2.0/24",
                                        "192.168.0.0/16",
                                        "198.18.0.0/15",
                                        "198.51.100.0/24",
                                        "203.0.113.0/24",
                                        "::1/128",
                                        "fc00::/7",
                                        "fe80::/10"
                                ],
                                "outboundTag": "blocked"
                        },
                        {
                                "type": "field",
                                "inboundTag": ["tg-in"],
                                "outboundTag": "tg-out"
                        }
                        ,
                        {
                                "type": "field",
                                "domain": [
                                        "domain:epochtimes.com",
                                        "domain:epochtimes.com.tw",
                                        "domain:epochtimes.fr",
                                        "domain:epochtimes.de",
                                        "domain:epochtimes.jp",
                                        "domain:epochtimes.ru",
                                        "domain:epochtimes.co.il",
                                        "domain:epochtimes.co.kr",
                                        "domain:epochtimes-romania.com",
                                        "domain:erabaru.net",
                                        "domain:lagranepoca.com",
                                        "domain:theepochtimes.com",
                                        "domain:ntdtv.com",
                                        "domain:ntd.tv",
                                        "domain:ntdtv-dc.com",
                                        "domain:ntdtv.com.tw",
                                        "domain:minghui.org",
                                        "domain:renminbao.com",
                                        "domain:dafahao.com",
                                        "domain:dongtaiwang.com",
                                        "domain:falundafa.org",
                                        "domain:wujieliulan.com",
                                        "domain:ninecommentaries.com",
                                        "domain:shenyun.com"
                                ],
                                "outboundTag": "blocked"
                        }                       ,
                {
                    "type": "field",
                    "protocol": [
                        "bittorrent"
                    ],
                    "outboundTag": "blocked"
                }
                        //include_ban_ad
                        //include_rules
                        //
                ]
        },
        "transport": {
                "kcpSettings": {
            "uplinkCapacity": 100,
            "downlinkCapacity": 100,
            "congestion": true
        }
        }
}

**Comment by ouzc12358** [comment]
这个脚本我最近也发现几个问题，
NGINX失败导致不能连接，V2ray 会不定期状态失败。都是重装一遍解决的，供参考。
要是你说的不能连接是IP 被ban，那就不是这个原因了

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jinwyp** [comment]
推荐一个终极脚本 支持 trojan-go trojan v2ray 共存,带可视化面板,升级和卸载,自动证书续签.可以修改root和ssh端口,支持WS+CDN，Vless和xtls 模式 https://github.com/jinwyp/one_click_script

**Comment by gumpjt** [comment]
> 推荐一个终极脚本 支持 trojan-go trojan v2ray 共存,带可视化面板,升级和卸载,自动证书续签.可以修改root和ssh端口,支持WS+CDN，Vless和xtls 模式 https://github.com/jinwyp/one_click_script

你这各种推你的脚本，咋地，是挖矿肉鸡太少吗？

**Comment by crazypeace** [comment]
> 新版本v2ray 和 xray 升级很快 还是换我的脚本把 可以看我的github

我偏要和你对着干。不想老是更新的。来看我这个repo https://github.com/crazypeace/v2ray
你还可以参考我的修改方法，fork之后修改成自己的版本，想下哪个版本的v2ray就下哪个。
