### ISSUE TITLE
如何回退v2ray版本到4.29？

### ISSUE THREAD

**Issue by CANBAAA** [233boy/v2ray#692]
4.33的总是会出现这个问题，而4.29的就没有这个问题
[Warning] [1707810474] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://xxxxxx.cf/): > dial tcp: lookup thatissushi.cf: getaddrinfow: This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server.] > v2ray.com/core/common/retry: all retry attempts failed

**Comment by crazypeace** [comment]
参考一下 https://github.com/crazypeace/v2ray
"本repo修改了src/download-v2ray.sh 第3行，将最新V2Ray版本写死为 v4.27.0，不会跟随最新的V2Ray版本"

当然，你目前的233脚本也许有变化，具体的行数不是那一行，但是修改的思路我想是相似的。
