### ISSUE TITLE
听说有一种叫神机规则的东西，这是指什么样的规则内特

### ISSUE THREAD

**Issue by sam019** [233boy/v2ray#694]

**Comment by crazypeace** [comment]
请用搜索引擎查看答案

**Comment by sam019** [comment]
> 请用搜索引擎查看答案

百度和google都搜了，没找到解释。
我理解是不是字面意思，就是把手机变得很神(能fq，去广告等)的规则，可能一开始我想多了。

**Comment by crazypeace** [comment]
请参考 https://merlinblog.xyz/wiki/rules.html
就是一个综合了很多规则之后的规则。
你也可以做一个适合你自己的“神机规则“
