### ISSUE TITLE
服务器端主程序升级到最新之后，手机上V2RAY便无法连接了

### ISSUE THREAD

**Issue by Mr-Carobon** [233boy/v2ray#696]
报“失败：io：read/write on closed pipe错误"

**Comment by crazypeace** [comment]
给你一个回悔药：https://github.com/crazypeace/v2ray
一个固定使用 Caddy v1.0.4 和 V2Ray v4.27.0 的 233一键脚本 v3.34

**Comment by Mr-Carobon** [comment]
感谢，有机会试试

**Comment by crazypeace** [comment]
我没有紧跟最新版本，所以不太了解。

**Comment by Mr-Carobon** [comment]
非常感谢！

**Comment by crazypeace** [comment]
以下来自google play的软件评论：


> 谝闲传
> 2020年11月28日
> 107
> 一直都在用，体验很好，但是今天更新了最新版后，华为p20不能连接了，显示io错误read或write错误，网上搜说是要服务器调整时间，但是我是正在用着升级后打开就不能用了，没有调整服务器和手机，怀疑还是软件出问题了。后续经查是：Core4.28.0 版本及以后版本中，**如果把 alterId 设置为 0 则代表为启用VMess AEAD** （别忘了更新服务端）。的问题，已经解决。

所以我想，你确认一下手机上和服务器上的alterID设置，也许可以解决问题。

**Comment by Mr-Carobon** [comment]
alterID设置还真没注意过，回头有机会我试下。
