### ISSUE TITLE
更新之后V2Ray一直未再运行，手动启动服务依然无法正常运行

### ISSUE THREAD

**Issue by MiKing233** [233boy/v2ray#697]
如题
![image](https://user-images.githubusercontent.com/26044744/104876793-5a996900-5993-11eb-9c8d-e384f33446d7.png)

**Comment by herewshow** [comment]
我也是，不知道怎么回事。

**Comment by crazypeace** [comment]
给你一个回悔药：https://github.com/crazypeace/v2ray
一个固定使用 Caddy v1.0.4 和 V2Ray v4.27.0 的 233一键脚本 v3.34

如果你想使用某个特定的v2ray版本，也可以参考这个repo的修改方法自行修改脚本。

**Comment by lxqker** [comment]
> 给你一个回悔药：https://github.com/crazypeace/v2ray
> 一个固定使用 Caddy v1.0.4 和 V2Ray v4.27.0 的 233一键脚本 v3.34
> 
> 如果你想使用某个特定的v2ray版本，也可以参考这个repo的修改方法自行修改脚本。

这个方法有效，多谢
