### ISSUE TITLE
采用脚本配置Websocket+TLS 或者 VLess+Websocket+TLS 模式时，config文件没有正确设置

### ISSUE THREAD

**Issue by Anguskk** [233boy/v2ray#699]
本人尝试了配置 33 VLess+Websocket+TLS 模式时发现了这个问题
vim /etc/v2ray/config.json ,查看配置文件确实是有问题的
在
"streamSettings": {
                             "network": "ws",            
                                            
           },
中缺失了 
"wsSettings": {  "path": "/ray" }
路径映射的配置，导致出现问题。
需要自行补上路径，不知道其他小伙伴发现这个没有
 "streamSettings": {
 23                                 "network": "ws",
 24                                 "wsSettings": {
 25                                        "path": "/ray"
 26                                  }
 27                  },

**Comment by Bblackc** [comment]
一样的，是少了路径映射的配置
