### ISSUE TITLE
能否添加https伪装的设置？

### ISSUE THREAD

**Issue by Sharkkkk** [233boy/v2ray#7]
现在使用WebSocket+TLS的设置，通过V2可以正常访问网页，但是当我使用浏览器访问v2中添加的网站时显示为空白，可不可以添加转发功能。使得浏览器访问v2的域名时也能正常提供自定义的内容，减小被发现的概率？

**Comment by 233boy** [comment]
@Sharkkkk 
下一个更新将支持

**Comment by Sharkkkk** [comment]
期待！

**Comment by 233boy** [comment]
@Sharkkkk 
请使用 v2ray update.sh 更新脚本，然后再使用 v2ray config 配置网站伪装和路径分流

**Comment by Sharkkkk** [comment]
我原来就配置好了，现在是直接更新还是要全部重新配置呢？ @233boy

**Comment by Sharkkkk** [comment]
请问新版脚本的WebSocket 分流功能是什么意思？具体有什么作用？反代已经可以伪装了呀

**Comment by Sharkkkk** [comment]
请问新版脚本的WebSocket 分流功能是什么意思，具体有什么作用呢   反代已经可以伪装了呀 @233boy

**Comment by 233boy** [comment]
@Sharkkkk 
就是路径分流啊，只要还是伪装，如果你实在不懂，我这边也不知道如何跟你解释清楚。

**Comment by Sharkkkk** [comment]
分流分的是什么流量，路径是用来做什么的，，，，安装了这个是不是就不能用宝塔建站了

**Comment by Sharkkkk** [comment]
或者有没有相关文档，我自己去看看，，，

**Comment by 233boy** [comment]
@Sharkkkk 
就是一个 Path，这个 Path 是用来将流量转到 V2Ray 从而实现翻出去。
如果你想要 用 宝塔建站，请自行配置。不要用脚本自动化解决 TLS 的实现，免得出现问题。
文档：https://www.v2ray.com/chapter_02/transport/websocket.html

**Comment by Sharkkkk** [comment]
或者能举几个例子吗

**Comment by Sharkkkk** [comment]
谢谢

**Comment by Sharkkkk** [comment]
文档说得好简陋。。。可以举个例子吗

**Comment by Sharkkkk** [comment]
path路径是文件夹吗，用来存放什么的呢

**Comment by Sharkkkk** [comment]
https://steemit.com/v2ray/@laosan/v2ray-websocket-ws-tls-nginx-bbr-cdn-wordpress
找到了

**Comment by f43310** [comment]
> https://steemit.com/v2ray/@laosan/v2ray-websocket-ws-tls-nginx-bbr-cdn-wordpress
> 找到了

太复杂了，没看明白。
