### ISSUE TITLE
求教大佬手机移动无法使用，WIFI可以正常使用

### ISSUE THREAD

**Issue by Null-dot** [233boy/v2ray#700]
手机上用的是v2rayNG,谷歌商店下载的最新版，VPS是Vultr，6美元的那个，全部弄好后，尝试了TCP,MKCP协议，伪装和不加伪装都尝试了，但就是WIFI可以正常使用，移动无法使用，根本链接不上，修改端口也是，笔记本电脑用v2rayN可以正常使用，求教大佬是什么原因，非常感谢

**Comment by crazypeace** [comment]
先弄清楚你的手机是连不上服务器，还是连上了之后的问题。
试下能不能ping通服务器，如果你开了网站作伪装，看手机能不能打开服务器的网站页面。

加了 cloudflare 的cdn吗？

可参考
https://guide.v2fly.org/advanced/cdn.html
v2ray/v2ray-core#1742

**Comment by Null-dot** [comment]
> 手机上用的是v2rayNG,谷歌商店下载的最新版，VPS是Vultr，6美元的那个，全部弄好后，尝试了TCP,MKCP协议，伪装和不加伪装都尝试了，但就是WIFI可以正常使用，移动无法使用，根本链接不上，修改端口也是，笔记本电脑用v2rayN可以正常使用，求教大佬是什么原因，非常感谢

**Comment by Null-dot** [comment]
> 先弄清楚你的手机是连不上服务器，还是连上了之后的问题。
> 试下能不能ping通服务器，如果你开了网站作伪装，看手机能不能打开服务器的网站页面。
> 
> 加了 cloudflare 的cdn吗？
> 
> 可参考
> https://guide.v2fly.org/advanced/cdn.html
> [v2ray/v2ray-core#1742](https://github.com/v2ray/v2ray-core/issues/1742)

感谢大佬回复，我是没有用CDN的，然后重新下载了2dust/v2rayNG版本的，还是这样，移动现在PING可以PING通，但延迟不定，大多情况太高，网站页面打不开，加不加伪装都一样，WIFI可以正常使用，估计后续我也要考虑WebSocket + TLS了

**Comment by crazypeace** [comment]
便宜的VPS如果不加CDN，延迟会很高。

https://github.com/233boy/v2ray/issues/696#issuecomment-766849570

确认一下手机上和服务器上的alterID设置，也许可以解决问题。

**Comment by Null-dot** [comment]
> 便宜的VPS如果不加CDN，延迟会很高。
> 
> [#696 (comment)](https://github.com/233boy/v2ray/issues/696#issuecomment-766849570)
> 
> 确认一下手机上和服务器上的alterID设置，也许可以解决连不上的问题。

好的，非常感谢

**Comment by Null-dot** [comment]
> 便宜的VPS如果不加CDN，延迟会很高。
> 
> [#696 (comment)](https://github.com/233boy/v2ray/issues/696#issuecomment-766849570)
> 
> 确认一下手机上和服务器上的alterID设置，也许可以解决连不上的问题。

大佬我已经试过修改alterID，用了websocket + tls，用手机移动网络还是无法使用，失败：context deadline exceeded ，WIFI是正常使用的，我又去找了手机联通网络测试，可以正常使用，最近也是在网上搜索查看很多，感觉是移动网络问题~

**Comment by Sp-Juno** [comment]
> > 便宜的VPS如果不加CDN，延迟会很高。
> 
> > 
> 
> > [#696 (comment)](https://github.com/233boy/v2ray/issues/696#issuecomment-766849570)
> 
> > 
> 
> > 确认一下手机上和服务器上的alterID设置，也许可以解决连不上的问题。
> 
> 
> 
> 大佬我已经试过修改alterID，用了websocket + tls，用手机移动网络还是无法使用，失败：context deadline exceeded ，WIFI是正常使用的，我又去找了手机联通网络测试，可以正常使用，最近也是在网上搜索查看很多，感觉是移动网络问题~

> 你问题解决了吗？ 我电脑联通宽带没问题，手机是北京移动换了n多ios客户端都是连上以后无速度，打不开任何qiang外网站

**Comment by Null-dot** [comment]
> 手机是北京移动4g 连能连上，一点速度没有，但是手机连电脑开的wifi热点就能连上。您的脚本是不是有点问题，怎么改设置？

问题解决了，这个是vps的问题，移动的出口网络很差，联通是最好的，换一个线路好些的vps就可以了，我现在用的就是CN2优化过的线路
