### ISSUE TITLE
端口占用导致服务启动失败

### ISSUE THREAD

**Issue by anantic4u** [233boy/v2ray#702]
[root@ONEVPS210124105638 ~]# /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json
V2Ray 4.27.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.6 linux/amd64)
A unified platform for anti-censorship.
2021/01/26 20:07:04 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message> 
v2ctl> Read config:  /etc/v2ray/config.json
Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 22122 > v2ray.com/core/transport/internet: failed to listen on address: 0.0.0.0:22122 > listen tcp 0.0.0.0:22122: bind: address already in use
如上。vps应该没问题。自己查了tcp，端口，IP都正常。应该怎么处理呢？拜托

**Comment by anantic4u** [comment]
Jan 26 20:03:50 ONEVPS210124105638 v2ray[25531]: V2Ray 4.27.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.6 linux/amd64)
Jan 26 20:03:50 ONEVPS210124105638 v2ray[25531]: A unified platform for anti-censorship.
Jan 26 20:03:50 ONEVPS210124105638 v2ray[25531]: 2021/01/26 20:03:50 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message>
Jan 26 20:03:50 ONEVPS210124105638 v2ray[25531]: v2ctl> Read config:  /etc/v2ray/config.json
Jan 26 20:03:50 ONEVPS210124105638 v2ray[25531]: Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 22122 > v2ray.com/core/transport/internet: failed to listen o
Jan 26 20:03:50 ONEVPS210124105638 systemd[1]: v2ray.service: main process exited, code=exited, status=255/n/a
Jan 26 20:03:50 ONEVPS210124105638 systemd[1]: Unit v2ray.service entered failed state.
Jan 26 20:03:50 ONEVPS210124105638 systemd[1]: v2ray.service failed.
Jan 26 20:03:51 ONEVPS210124105638 systemd[1]: v2ray.service holdoff time over, scheduling restart.
Jan 26 20:03:51 ONEVPS210124105638 systemd[1]: Stopped V2Ray Service.
这是journal日志

**Comment by crazypeace** [comment]
有没有可能 你跑了两个v2ray实例？你查一下内存是不是已经跑了一个？

**Comment by anantic4u** [comment]
好像是被sshd占用了端口。但是杀进程无效。最后换了端口就好了。完
