### ISSUE TITLE
甲骨文云安装完了之后，为什么还是打不开谷歌

### ISSUE THREAD

**Issue by hcllmsx** [233boy/v2ray#704]
我的甲骨文账号的主区域是：South Korea Central (Seoul)，这应该是韩国首尔吧？然鹅我安装了之后，也没报错什么的，但节点死活没网速，怎么回事啊

**Comment by crazypeace** [comment]
你先确定安装成功了没有。v2ray status 看一下状态。

最新的v2ray和233脚本不对付，这几天很多人发issue说有问题。
