### ISSUE TITLE
安装成功后出错，请重新安装V2Ray ？？

### ISSUE THREAD

**Issue by Roboppi** [233boy/v2ray#705]
---------- END -------------

V2Ray 客户端使用教程: https://233v2.com/post/4/

提示: 输入  v2ray url  可生成 vmess URL 链接 / 输入  v2ray qr  可生成二维码链接

免被墙..推荐使用JMS: https://getjms.com

root@localhost:~# v2ray url
 哎呀哎呀…… 出错咯...请重新安装V2Ray ~(^_^) 
root@localhost:~#

**Comment by crazypeace** [comment]
你可以参考这个，自己指定下载哪个版本的v2ray
https://zelikk.blogspot.com/2021/01/233v2ray-local.html
