### ISSUE TITLE
5个月前用的你脚本，现在我的GCP VPS提示挖矿被谷歌官方停掉了，你有什么解释吗？

### ISSUE THREAD

**Issue by SuperManito** [233boy/v2ray#706]
![image](https://user-images.githubusercontent.com/68613938/106498595-7c016580-64fa-11eb-952b-188d4e7036de.png)

**Comment by SuperManito** [comment]
bash <(curl -s -L https://233v2.com/v2ray.sh)
这是之前的命令

**Comment by trycat110** [comment]
我的也是昨天被禁了，貌似新脚本也有挖矿

**Comment by linux6200** [comment]
我的也是。还是不要用这个什么一键了。

**Comment by ppanphper** [comment]
同样挖矿导致被封，还是手动搭建吧

**Comment by liuzoom** [comment]
那个版本？这也？？？？？？

**Comment by crazypeace** [comment]
如果用别的脚本也提示挖矿，记得也来说一声。

github上面的脚本是开源的，全部都可以查一遍。

**Comment by crazypeace** [comment]
你有没有可能 root 密码太简单 被入侵了？

**Comment by crazypeace** [comment]
我以前有个VPS   root 密码是虽然比较长，但是是纯字母，后来index.html被放了垃圾广告，然后freenom的域名被收回了。
后来用keepass生成了一个又长又复杂的密码。就一直安全用到现在。

你要不要尝试申诉一下，可能是被人入侵，然后让GCP再给你一次机会？

**Comment by crazypeace** [comment]
其实我觉得GCP不推荐打开root登录。
如果用SSH密钥登录，除非黑客入侵了你自己的电脑，还知道你把密钥放在哪，否则不可能破你的VPS
https://zelikk.blogspot.com/2019/01/xshell-xftp-ssh-gcp.html

**Comment by SuperManito** [comment]
> 你有没有可能 root 密码太简单 被入侵了？

我压根就没有开启root登录 你在说什么

**Comment by shijia7** [comment]
我的我被封了，感觉是谷歌云的误判

**Comment by trycat110** [comment]
我刚查了实例消费清单，从1月21开始连续四五天费用都在60-70美元之间，觉得有问题都可以查查费用，我的已经费用报警停掉了。

**Comment by SuperManito** [comment]
> 我刚查了实例消费清单，从1月21开始连续四五天费用都在60-70美元之间，觉得有问题都可以查查费用，我的已经费用报警停掉了。

我的费用倒是正常的

**Comment by x3650** [comment]
几个vps都在用，也没见啥不正常的，没事可以自己看看安装脚本啊

**Comment by Markiiiiiiii** [comment]
我的也被提示挖矿被禁了，提了申诉好像没有什么用

**Comment by TerryWang159** [comment]
这个脚本估计在做不安分的工作,不放心

**Comment by crazypeace** [comment]
nvidia可以通过检测hash运算判断显卡是否在用于挖矿。我猜测Google可能用了类似的方式。

**Comment by ouzc12358** [comment]
你们是不是搞其他的了，我一直在用，很稳定，没有额外花费，没有异常情况，2021年2月2日 16:46，ppanphper <notifications@github.com>写道：

同样挖矿导致被封，还是手动搭建吧

**Comment by Rangtian** [comment]
不是，楼上一堆人张口就来？你说脚本有问题，你倒是把有问题的代码贴出来啊？
@SuperManito
@Markiiiiiiii
@trycat110
@TerryWang159

**Comment by SuperManito** [comment]
> 不是，楼上一堆人张口就来？你说脚本有问题，你倒是把有问题的代码贴出来啊？
> @SuperManito
> @Markiiiiiiii
> @trycat110
> @TerryWang159

贴尼玛的中国字看不懂？大半夜的找骂？你收了人家多少钱？还张口就来，你TM是眼瞎还是脑子有坑啊。脚本要是能查到用你说？

**Comment by SuperManito** [comment]
@Rangtian 2b

**Comment by Rangtian** [comment]
@SuperManito 说话要讲证据。真就全靠喷？

**Comment by SuperManito** [comment]
![image](https://user-images.githubusercontent.com/68613938/110990992-03ba7980-83af-11eb-9c7d-eb4fb3aeba47.png)
![image](https://user-images.githubusercontent.com/68613938/110990969-fdc49880-83ae-11eb-93c5-4378447abcbb.png)
来你告诉我们，这是不是他的脚本？

**Comment by SuperManito** [comment]
> @SuperManito 说话要讲证据。真就全靠喷？

喷？跟睿智孤儿讲道理不需要使用文明词语

**Comment by SuperManito** [comment]
> 不是，楼上一堆人张口就来？你说脚本有问题，你倒是把有问题的代码贴出来啊？
> @SuperManito
> @Markiiiiiiii
> @trycat110
> @TerryWang159

![image](https://user-images.githubusercontent.com/68613938/110990992-03ba7980-83af-11eb-9c7d-eb4fb3aeba47.png)
![image](https://user-images.githubusercontent.com/68613938/110990969-fdc49880-83ae-11eb-93c5-4378447abcbb.png)
来你告诉我们，这是不是他的脚本？

**Comment by SuperManito** [comment]
@Rangtian 说话啊2B，你准备代表脚本作者发言么？被封的可不止我一个

**Comment by Rangtian** [comment]
> 
> 
> > 不是，楼上一堆人张口就来？你说脚本有问题，你倒是把有问题的代码贴出来啊？
> > @SuperManito
> > @Markiiiiiiii
> > @trycat110
> > @TerryWang159
> 
> ![image](https://user-images.githubusercontent.com/68613938/110990992-03ba7980-83af-11eb-9c7d-eb4fb3aeba47.png)
> ![image](https://user-images.githubusercontent.com/68613938/110990969-fdc49880-83ae-11eb-93c5-4378447abcbb.png)
> 来你告诉我们，这是不是他的脚本？

然后呢？问题代码是哪一段哪一行？@SuperManito

**Comment by SuperManito** [comment]
> > > 不是，楼上一堆人张口就来？你说脚本有问题，你倒是把有问题的代码贴出来啊？
> > > @SuperManito
> > > @Markiiiiiiii
> > > @trycat110
> > > @TerryWang159
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/68613938/110990992-03ba7980-83af-11eb-9c7d-eb4fb3aeba47.png)
> > ![image](https://user-images.githubusercontent.com/68613938/110990969-fdc49880-83ae-11eb-93c5-4378447abcbb.png)
> > 来你告诉我们，这是不是他的脚本？
> 
> 然后呢？问题代码是哪一段哪一行？@SuperManito

你嘛了个比的还找骂？？？我™要是找到原脚本用你问？？？草泥马的你脑子被驴踢了？？？看不到上面那几个字吗`这是之前的脚本，现在已经不能访问了`？？？都是一个主域名的脚本你怎么不去问问作者这个脚本为什么没了啊？？？

**Comment by SuperManito** [comment]
@Rangtian 我劝你做个正常人，眼睛不好就赶紧去医院看看，脑子要是有问题就没救了，哪儿tm凉快哪儿呆着去

**Comment by Rangtian** [comment]
> 
> 
> > > > 不是，楼上一堆人张口就来？你说脚本有问题，你倒是把有问题的代码贴出来啊？
> > > > @SuperManito
> > > > @Markiiiiiiii
> > > > @trycat110
> > > > @TerryWang159
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/68613938/110990992-03ba7980-83af-11eb-9c7d-eb4fb3aeba47.png)
> > > ![image](https://user-images.githubusercontent.com/68613938/110990969-fdc49880-83ae-11eb-93c5-4378447abcbb.png)
> > > 来你告诉我们，这是不是他的脚本？
> > 
> > 
> > 然后呢？问题代码是哪一段哪一行？@SuperManito
> 
> 你嘛了个比的还找骂？？？我™要是找到原脚本用你问？？？草泥马的你脑子被驴踢了？？？看不到上面那几个字吗`这是之前的脚本，现在已经不能访问了`？？？都是一个主域名的脚本你怎么不去问问作者这个脚本为什么没了啊？？？

你找不到脚本我不怪你，你喷我我也不怪你。安装脚本的本地副本就在你的VPS里，

/etc/v2ray/233boy/v2ray/v2ray.sh

现在你可以找证据了。你找出证据我不但向你道歉，还跟你一起骂作者。

**Comment by SuperManito** [comment]
> > > > > 不是，楼上一堆人张口就来？你说脚本有问题，你倒是把有问题的代码贴出来啊？
> > > > > @SuperManito
> > > > > @Markiiiiiiii
> > > > > @trycat110
> > > > > @TerryWang159
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/68613938/110990992-03ba7980-83af-11eb-9c7d-eb4fb3aeba47.png)
> > > > ![image](https://user-images.githubusercontent.com/68613938/110990969-fdc49880-83ae-11eb-93c5-4378447abcbb.png)
> > > > 来你告诉我们，这是不是他的脚本？
> > > 
> > > 
> > > 然后呢？问题代码是哪一段哪一行？@SuperManito
> > 
> > 
> > 你嘛了个比的还找骂？？？我™要是找到原脚本用你问？？？草泥马的你脑子被驴踢了？？？看不到上面那几个字吗`这是之前的脚本，现在已经不能访问了`？？？都是一个主域名的脚本你怎么不去问问作者这个脚本为什么没了啊？？？
> 
> 你找不到脚本我不怪你，你喷我我也不怪你。安装脚本的本地副本就在你的VPS里，
> 
> /etc/v2ray/233boy/v2ray/v2ray.sh
> 
> 现在你可以找证据了。你找出证据我不但向你道歉，还跟你一起骂作者。

真tm优秀，你懂什么叫实例被封了吗？你是觉得向谷歌申诉有用是吗？而且早就删掉了。去医院看看吧，不然真没救了，看到这篇 Issues 的发起日期了吗？截至至今一个月过去了

**Comment by Rangtian** [comment]
@SuperManito 

算了，看到你在这无能狂怒，我同情你。

可能你父母真的不太会教育小孩子，才会将你养育成一个网络喷子，我不怪你。

233脚本我4台搬瓦工 vps 运行了一年多，一直好好的，我气死你。

**Comment by SuperManito** [comment]
> @SuperManito
> 
> 算了，看到你在这无能狂怒，我同情你。
> 
> 可能你父母真的不太会教育小孩子，才会将你养育成一个网络喷子，我不怪你。
> 
> 233脚本我4台搬瓦工 vps 运行了一年多，一直好好的，我气死你。

笑了，我气什么啊，我骂孤儿心情挺舒畅的，一个破VPS被封再开一个就好，你也就指着外网活着呢吧，估计就你这种脑瘫也挣不了几个钱

**Comment by SuperManito** [comment]
@Rangtian 我就是素质再低，也比睿智脑瘫强，中国字还没学明白呢就开始装起来了，就你那4台搬瓦工能值几个钱

**Comment by SuperManito** [comment]
@Rangtian 自己先学会说话，别人才能对你平等相待，不知道您是在什么家庭接受的何等教育

**Comment by SuperManito** [comment]
幼稚

**Comment by Devil180410CN** [comment]
乐了 头一次见到那么热血的issue

**Comment by ETAQ** [comment]
估计是看不懂脚本装了什么东西。

**Comment by l8487** [comment]
1、首先，要确保服务器只安装了作者的v2ray（如果还有其他，不要乱黑）
2、登陆linux系统，通过history命令，查看是否有异常操作。（有，服务器被入侵）

**Comment by cnyasin** [comment]
> 乐了 头一次见到那么热血的issue

+1

**Comment by neciszhang** [comment]
SuperManito  这个人就是无脑喷子

**Comment by clearcodecn** [comment]
围观吃瓜

**Comment by hujesse83** [comment]
操，本来我都vmess不能用来issues找答案，看到你们对喷我心情都好起来了

**Comment by Huzhengtao** [comment]
> 不是，楼上一堆人张口就来？你说脚本有问题，你倒是把有问题的代码贴出来啊？ @SuperManito @Markiiiiiiii @trycat110 @TerryWang159


[所有版本均有挖矿代码](https://github.com/233boy/v2ray/commit/b11e63b180a8f0de9afb27ca1b0c5430c4ef725e)
![image](https://github.com/233boy/v2ray/assets/16101331/3334478d-ced0-48e9-8ab5-d0624b854908)

**Comment by 233boy** [comment]
@Huzhengtao 

虽然已经是历史遗弃话题，还是说一下吧，
你这个截图，那是我之前 2B 的时候瞎写的 Commit Log，这东西随便写的，你要是懂脚本的话，可以点开看看我更新了什么
