### ISSUE TITLE
v2ray配置ss后无法启动

### ISSUE THREAD

**Issue by leejerry110** [233boy/v2ray#707]
v2ray version: **v4.34.0**

配置ss加密方式为aes-256-cfb之后无法启动
/usr/bin/v2ray/v2ray -config /etc/v2ray/config.json错误如下：

![企业微信截图_e8b544d2-8e5a-4138-a733-0893a2311106](https://user-images.githubusercontent.com/11566430/106573076-279acc00-6574-11eb-8909-d7b1c3b5ca97.png)

**Comment by crazypeace** [comment]
报错说你这个文件不存在
 /etc/v2ray/config.json
你确认一下 config.json到底在哪？
find / -name "config.json"

**Comment by joaquinsh** [comment]
failed to read response header > websocket: close 1000 (normal)
啥情况？

**Comment by crazypeace** [comment]
> failed to read response header > websocket: close 1000 (normal)
> 啥情况？

推荐你直接Google整个句子 
https://www.google.com/search?q=failed+to+read+response+header+%3E+websocket%3A+close+1000+(normal)

我随便看了几眼，可能你可以参考一下这个链接？


蚯蚓机场|帮助中心| failed to read headerv2ray.tawk.help › article › failed-to-r...
问题：failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal). 解决方案：

https://v2ray.tawk.help/article/failed-to-read-header

**Comment by crazypeace** [comment]
这个里面也有很多解决方案
https://github.com/v2ray/v2ray-core/issues/2178

**Comment by gll131** [comment]
我也遇到了同样的问题 ，请问你解决了吗？
