### ISSUE TITLE
WebSocket + TLS  下能加上web吗

### ISSUE THREAD

**Issue by underlaw** [233boy/v2ray#71]
参照"https://v2ray666.com/post/6/   使用 Cloudflare 中转 V2Ray WebSocket 的流量来避免 IP 被墙"已成功使用，请问如果我不想浪费空间加个web小站，怎么配置
后台我用了bt面板，安装nginx1.14不能运行，80端口占用，如果可以请在教程加上开web这小节吧

**Comment by rhotov** [comment]
可以换一个思路，先装LNMP包，再申请TLS，Cloudflare，把网站建好，最后装V2Ray。

**Comment by underlaw** [comment]
那80端口会不会冲突了？

**Comment by rhotov** [comment]
> 那80端口会不会冲突了？

不会的，v2ray不会占用80和443端口，这两个端口都由nginx控制，然后对443端口的特定目录（ws指定的那个目录）的访问会由nginx转发给v2ray实现隐藏v2ray端口的效果。

**Comment by myworksfun** [comment]
我也遇到了这样的问题，一直没找到解决办法。兄弟们有高招，可以指点一下哦。

**Comment by aass0810** [comment]
我也是研究了好久，没能搞出来，全部显示“404 Site ****** is not served on this interface”

**Comment by f43310** [comment]
我也有同样的需求，求大神给提供思路。

**Comment by xianshenglu** [comment]
我弄好了，你可以试下 [这个](https://github.com/xianshenglu/crossTheWall/blob/master/v2ray/v2ray-nginx.md)

**Comment by Rain73437** [comment]
> 我弄好了，你可以试下 [这个](https://github.com/xianshenglu/crossTheWall/blob/master/v2ray/v2ray-nginx.md)

我没有成功，第二部添加文件，转发本地端口失败了。错误日志说8000端口占用，其实就是v2yay再用这个端口。求问大佬这一步怎么解决

**Comment by xianshenglu** [comment]
> > 我弄好了，你可以试下 [这个](https://github.com/xianshenglu/crossTheWall/blob/master/v2ray/v2ray-nginx.md)
> 
> 我没有成功，第二部添加文件，转发本地端口失败了。错误日志说8000端口占用，其实就是v2yay再用这个端口。求问大佬这一步怎么解决

这样正常的呀，v2ray 用的 8000端口，然后 nginx 把域名的 80 端口转发给 本地的8000端口。你那个应该不是错误原因，应该其他地方有问题。你访问下指向 v2ray 的域名，看转发成功了没
