### ISSUE TITLE
用俄罗斯VPS安装V2ray后无法代理

### ISSUE THREAD

**Issue by lingyi06** [233boy/v2ray#710]
我用俄罗斯VPS安装V2ray后无法代理，我测试端口的时候并没有在使用，我安装SSR后，就能正常使用SSR并可以代理！系统也是重装了很多次也是不行！求解决

**Comment by crazypeace** [comment]
v2ray status 看一下跑起来没有

**Comment by lingyi06** [comment]
> v2ray状态看一下跑起来没有

没跑起来，怎么办？

**Comment by crazypeace** [comment]
试试 旧版本
https://github.com/crazypeace/v2ray
