### ISSUE TITLE
centos7 使用后内核被升级=锐速失效

### ISSUE THREAD

**Issue by ntgeralt** [233boy/v2ray#711]
贵站脚本的yum 升级了300多个centos小组件包括内核……

**Comment by crazypeace** [comment]
你可以把脚本下载到本地，修改掉升级组件的命令，再从本地安装。

修改 install.sh 第783行

注释掉  $cmd update -y

具体化操作参考
https://zelikk.blogspot.com/2021/01/233v2ray-local.html

**Comment by ntgeralt** [comment]
嗯，改脚本这个明白的。已无后悔药
