### ISSUE TITLE
安卓客户端能用win7客户端v2rayN用不了

### ISSUE THREAD

**Issue by xinjun-zhan** [233boy/v2ray#713]
服务器端的访问日志输出入下，有没有大佬指点一下，灰常感谢

2021/02/16 12:48:07 36.xxx.xxx.xxx:63292 rejected  v2ray.com/core/proxy/vmess/encoding: failed to drain connection DrainSize = 1310 27 7 > v2ray.com/core/proxy/vmess/encoding: invalid user > v2ray.com/core/proxy/vmess: Not Found

2021/02/16 12:48:12 36.xxx.xxx.xxx:63292 rejected  v2ray.com/core/proxy/vmess/encoding: failed to drain connection DrainSize = 1310 27 14 > v2ray.com/core/proxy/vmess/encoding: invalid user > v2ray.com/core/proxy/vmess: Not Found

2021/02/16 12:48:14 36.xxx.xxx.xxx:63292 rejected  v2ray.com/core/proxy/vmess/encoding: failed to drain connection DrainSize = 1310 27 18 > v2ray.com/core/proxy/vmess/encoding: invalid user > v2ray.com/core/proxy/vmess: Not Found

2021/02/16 12:48:43 36.xxx.xxx.xxx:63292 rejected  v2ray.com/core/proxy/vmess/encoding: failed to drain connection DrainSize = 1310 27 16 > v2ray.com/core/proxy/vmess/encoding: invalid user > v2ray.com/core/proxy/vmess: Not Found

**Comment by crazypeace** [comment]
https://github.com/v2fly/v2ray-core/issues/487
