### ISSUE TITLE
国内服务器之间无法连接成功。

### ISSUE THREAD

**Issue by zhouaini528** [233boy/v2ray#714]
我目前有一个需求，国内搭建了一台代理服务器作为固定IP服务器， 还有几台国内服务器做了白名单限制，只能由固定IP服务器才能访问，    目前的情况的  国外的服务器没问题，   但是国内的服务器缺无法连接成功。请问我需要如何配置??

**Comment by crazypeace** [comment]
>  但是国内的服务器缺无法连接成功。

【谁】 连接 【谁】 不成功？用什么协议连？

我猜测有可能是防火墙设置？

**Comment by zhouaini528** [comment]
> > 但是国内的服务器缺无法连接成功。
> 
> 【谁】 连接 【谁】 不成功？用什么协议连？
> 
> 我猜测有可能是防火墙设置？

我是默认脚本一键安装的
我的client在国内，连接国内搭建的一台代理服务器，目的是作为固定IP服务器，该代理服务器再去连接国内或者国外的服务器。  我的业务需求就是国内国外的服务器需要一台固定IP服务器访问，作为白名单限制。

现在的问题是，国内固定IP服务器连接到国外的服务器能正常连接，    但是连接到国内服务器反而不行了。

**Comment by crazypeace** [comment]
为了简化描述，涉及到的连接为 
 client - A（国内代理服务器） - B（国内目标服务器）
 client - A（国内代理服务器） - C（国外目标服务器）

我觉得你先排查：
1. A - B 是通的，如果你能在A上直接跑一个client检查就最好了
2. client - A - B的时候，是不是client直接连了B，如果你能查到B上面的拒绝访问记录就最好了

**Comment by crazypeace** [comment]
有没有可能 A - B 的时候和 A - C 的时候，走的网口不一样？（IP地址不一样）

**Comment by zhouaini528** [comment]
> 为了简化描述，涉及到的连接为
> client - A（国内代理服务器） - B（国内目标服务器）
> client - A（国内代理服务器） - C（国外目标服务器）
> 
> 我觉得你先排查：
> 
> 1. A - B 是通的，如果你能在A上直接跑一个client检查就最好了
> 2. client - A - B的时候，是不是client直接连了B，如果你能查到B上面的拒绝访问记录就最好了

谢谢你的回复。  
我再描述一下
client - A（国内代理服务器） - B（国内目标服务器）    不成功
client - A（国内代理服务器） - C（国外目标服务器）    成功

我在A（国内代理服务器）设置了 国内IP 直连，会是这个问题？  但是如果不设置~ client连接,全部走A，  会很费A的带宽。我在client端也做了 国内IP直连。

**Comment by zhouaini528** [comment]
> 有没有可能 A - B 的时候和 A - C 的时候，走的网口不一样？（IP地址不一样）

应该一样的吧，我购买的阿里云的，不是同区域，  ping也没问题。

**Comment by crazypeace** [comment]
> 我在client端也做了 国内IP直连。
我不清楚你具体用的什么v2ray 配置或者pac配置，一般来说，在client设置【国内IP直连】，可能有两种情况：
1. 经过pac判断，访问的是国内IP，直接去连接了，没有走v2ray建出来的代理
2. 经过v2ray判断，访问的是国内IP，直接去连接了，没有转发给 B

不管你的client是用pac配置还是用v2ray的配置，基本思路就是要让B的IP相当于“国外”IP。

**Comment by zhouaini528** [comment]
> > 我在client端也做了 国内IP直连。
> 
> 我不清楚你具体用的什么v2ray 配置或者pac配置，一般来说，在client设置【国内IP直连】，可能有两种情况：
> 
> 1. 经过pac判断，访问的是国内IP，直接去连接 B 了，没有走v2ray建出来的代理
> 2. 经过v2ray判断，访问的是国内IP，直接去连接 B 了，没有转发给 A
> 
> 不管你的client是用pac配置还是用v2ray的配置，基本思路就是要让B的IP相当于“国外”IP。一般来说，是自定义某个列表之类的，把B的IP放进去。

非常谢谢你的帮助，我已经解决了，是我本地的问题。搭建的代理服务器没问题的。
