### ISSUE TITLE
v2ray 流量中转报错

### ISSUE THREAD

**Issue by link2022** [233boy/v2ray#715]
客户端---->v2ray中转----->v2ray目标
v2ray版本：v4.34.0
【v2ray中转】json中 outbounds  的 "alterId"  和【v2ray目标】机器的json中 inbounds  的 "alterId":  如果都是：0
则报错：v2ray.com/core/proxy/vmess/encoding: Failed To Decrypt Length > cipher: message authentication failed
如果"alterId":  如果都是：改成非0，且一致
则报错：unexpected response header. Expecting 134 but actually 44
有大佬遇到吗

**Comment by crazypeace** [comment]
我觉得你应该去 v2ray (v2fly) 那里提issue，这个脚本管不了v2rays本身的问题。
你也可以去 v2ray 的tg群里 喊一声。https://t.me/projectv2ray
