### ISSUE TITLE
大神是否尝试过http2套cdn

### ISSUE THREAD

**Issue by jsjcjsjc** [233boy/v2ray#72]
不套cdn正常，套了后就打不开网页，无法使用，但是伪装的主页能进，cdn也开了ssl。不知道啥情况。。。求指导

**Comment by rhotov** [comment]
套cdn之后端口要改成443，另外服务器的path也要和客户端对应上。还有，服务器的caddy/nginx/apache监听是否正常？

**Comment by Abreto** [comment]
这个跟CDN回源是 HTTP/1.1 是不是有关系？
