### ISSUE TITLE
一直提示我输入错误

### ISSUE THREAD

**Issue by chok-cheng** [233boy/v2ray#720]
我运行了安装的代码。不知道为啥，我没输入东西。他就提示我输入错误。然后一直刷下去

**Comment by crazypeace** [comment]
好歹发个截屏上来啊……
你描述的这些不能帮助别人了解你具体遇到了什么问题。

**Comment by wp-jackliu** [comment]
是的，就是不停地滚屏，感觉while true 死循环了一样
![image](https://user-images.githubusercontent.com/3220935/168774809-f76993fa-ee41-4767-9c1c-33eeafdd4174.png)

**Comment by chok-cheng** [comment]
换个服务器。重新安装就好了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月17日(星期二) 下午5:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [233boy/v2ray] 一直提示我输入错误 (#720)





 
是的，就是不停地滚屏，感觉while true 死循环了一样

**Comment by crazypeace** [comment]
> 是的，就是不停地滚屏，感觉while true 死循环了一样 ![image](https://user-images.githubusercontent.com/3220935/168774809-f76993fa-ee41-4767-9c1c-33eeafdd4174.png)

那个…… 我也不是作者。
你如果是搭 vless+WS+TLS模式，不如来看看这个简单得多的脚本？
https://github.com/crazypeace/V2ray_VLESS_WebSocket_TLS_CaddyV2
