### ISSUE TITLE
无法联网

### ISSUE THREAD

**Issue by chok-cheng** [233boy/v2ray#721]
服务器上v2ray状态显示正在运行。手机端和电脑端的都配置好，配置对了。然后连接不上，没办法上网
![image](https://user-images.githubusercontent.com/65767256/111586531-eeed4400-87fb-11eb-97f9-454ffaf856c2.png)

**Comment by greatlog** [comment]
+1，我也是最近出现这个状况，之前没有这个问题的

**Comment by chok-cheng** [comment]
有没有什么解决办法呀？晕死。。。我一直以为服务器问题。都换几个了

**Comment by chok-cheng** [comment]
> +1，我也是最近出现这个状况，之前没有这个问题的

我弄好了。国内没办法访问服务器ip。。你要换别的 运营商

**Comment by zhanghming** [comment]
@chok-cheng 换别的运营商什么意思？重新买VPS？我最近也上不了网了，v2ray提示：
```
[Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp ip: i/o timeout] > v2ray.com/core/common/retry: all retry attempts failed
```

**Comment by Rangtian** [comment]
> 
> 
> @chok-cheng 换别的运营商什么意思？重新买VPS？我最近也上不了网了，v2ray提示：
> 
> ```
> [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp ip: i/o timeout] > v2ray.com/core/common/retry: all retry attempts failed
> ```

先看看你的 VPS 是不是 IP 或者 Port 被墙了。

**Comment by zhanghming** [comment]
@Rangtian 谢谢回复，已查明问题，确实是IP被墙了。。。

**Comment by Feng-Bu-Jue** [comment]
azure 不彳亍

**Comment by 498072478** [comment]
我的也是这样，怎么知道IP是不是被墙了？

**Comment by chok-cheng** [comment]
> 我的也是这样，怎么知道IP是不是被墙了？

先去ping一下。。。ping不通就证明呗墙了 
http://ping.chinaz.com/+服务器IP

**Comment by 498072478** [comment]
> > 我的也是這樣，怎麼知道IP是不是被牆了？
> 
> 先去ping一下。。。ping不通就證明唄牆了
> [http://ping.chinaz.com/+服務器IP](http://ping.chinaz.com/+%E6%9C%8D%E5%8A%A1%E5%99%A8IP)

谢谢，不是IP的问题，我的改成tcp协议就好了
