### ISSUE TITLE
只要用这个脚本安装，什么都不用选择，直接退出，就会被报DDOS/Hacking

### ISSUE THREAD

**Issue by richwxd** [233boy/v2ray#722]
然后就被停住了。

**Comment by richwxd** [comment]
这个脚本是不是在挖矿，在用来建私服？arma3server 是什么鬼？ 刚重新安装的系统，跑一遍这个脚本就被警告，报出这个report了
`
Mar 20 07:37:26 uapps sshd[9014]: Invalid user arma3server from 111.222.111.222 port 34412
Mar 20 07:37:28 uapps sshd[9014]: Failed password for invalid user arma3server from 111.222.111.222 port 34412 ssh2
Mar 20 07:37:28 uapps sshd[9014]: Received disconnect from 111.222.111.222 port 34412:11: Bye Bye [preauth]
Mar 20 07:37:28 uapps sshd[9014]: Disconnected from invalid user arma3server 111.222.111.222 port 34412 [preauth]
Mar 20 07:55:14 uapps sshd[9190]: User www-data from 111.222.111.222 not allowed because not listed in AllowUsers
Mar 20 07:55:14 uapps sshd[9190]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=111.222.111.222 user=www-data
Mar 20 07:55:16 uapps sshd[9190]: Failed password for invalid user www-data from 111.222.111.222 port 55844 ssh2
Mar 20 07:55:18 uapps sshd[9190]: Received disconnect from 111.222.111.222 port 55844:11: Bye Bye [preauth]
Mar 20 07:55:18 uapps sshd[9190]: Disconnected from invalid user www-data 111.222.111.222 port 55844 [preauth]
Mar 20 07:57:54 uapps sshd[9217]: Invalid user dell from 111.222.111.222 port 40266
Mar 20 07:57:56 uapps sshd[9217]: Failed password for invalid user dell from 111.222.111.222 port 40266 ssh2
`

**Comment by Rangtian** [comment]
这就是显示有人从 111.222.111.222 这个 IP 不断尝试 ssh 你的 VPS。是不是在挖矿，你看看你 VPS 的 CPU 占用是不是异常，有没有可疑 Process 不就知道了么。

**Comment by richwxd** [comment]
最近试过几次了，重新安装的系统，只要一开这个脚本安装，突然就报出一对尝试登录、扫描的日志。最多的是arma3server。

**Comment by Rangtian** [comment]
> 
> 
> 最近试过几次了，重新安装的系统，只要一开这个脚本安装，突然就报出一对尝试登录、扫描的日志。最多的是arma3server。

脚本是以 root 权限执行的，真要搞什么小动作的话直接就搞了。你这应该就是被 bot 暴力扫描了。我是上星期才弃用 233脚本的，因为转用 Xray 了。之前4台 VPS 用了一年多的 233 脚本，没任何问题。你要实在不放心，就手动搭建吧，网上都有教程。

**Comment by crazypeace** [comment]
我猜是 一键脚本为了适应不同的VPS环境，可能粗暴地关闭了防火墙。你那个VPS就被人扫描尝试暴破。

你要么就手工搭建，要么就脚本装完后再设置防火墙。

**Comment by qeqeq1** [comment]
> 我猜是 一键脚本为了适应不同的VPS环境，可能粗暴地关闭了防火墙。你那个VPS就被人扫描尝试暴破。
> 
> 你要么就手工搭建，要么就脚本装完后再设置防火墙。

你说的是对的，我观察了两个一件脚本都有禁用防火墙的操作
