### ISSUE TITLE
小白求助

### ISSUE THREAD

**Issue by 4M3D** [233boy/v2ray#723]
连得Vmess的节点，昨天还能好好翻墙，今天就上不去了，能ping，测速也有结果，但是翻不出去

**Comment by Rangtian** [comment]
一键后不是会生成配置链接么，小白最好的办法就是做排除法。一个配置不行，就一键设置改为另一个配置，然后导入客户端。要是什么配置都不行，那肯定是你被墙了。

**Comment by crazypeace** [comment]
1、设置成全局也翻不出去吗？
2、如果你使用的是v2rayng / v2rayn，测试一下服务器真连接

如果你不是自己搭的服务器，有可能别人修改了参数。
