### ISSUE TITLE
vultr centos7 启动失败

### ISSUE THREAD

**Issue by fi5** [233boy/v2ray#724]
大神，启动失败；不支持centos7了么？之前一直用的挺好，那个服务器ip被封，也是centos7啊。

● v2ray.service - V2Ray Service
   Loaded: loaded (/usr/lib/systemd/system/v2ray.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since 一 2021-03-22 19:26:19 CST; 4min 35s ago
     Docs: https://www.v2ray.com/
           https://www.v2fly.org/
  Process: 1939 ExecStart=/usr/bin/v2ray/v2ray -config /etc/v2ray/config.json (code=exited, status=218/CAPABILITIES)
 Main PID: 1939 (code=exited, status=218/CAPABILITIES)

3月 22 19:26:19 vultr.guest systemd[1]: v2ray.service: main process exited, code=exited, stat...IES
3月 22 19:26:19 vultr.guest systemd[1]: Unit v2ray.service entered failed state.
3月 22 19:26:19 vultr.guest systemd[1]: v2ray.service failed.
3月 22 19:26:19 vultr.guest systemd[1]: v2ray.service holdoff time over, scheduling restart.
3月 22 19:26:19 vultr.guest systemd[1]: Stopped V2Ray Service.
3月 22 19:26:19 vultr.guest systemd[1]: start request repeated too quickly for v2ray.service
3月 22 19:26:19 vultr.guest systemd[1]: Failed to start V2Ray Service.
3月 22 19:26:19 vultr.guest systemd[1]: Unit v2ray.service entered failed state.
3月 22 19:26:19 vultr.guest systemd[1]: v2ray.service failed.

**Comment by crazypeace** [comment]
我用gogole搜索  【(code=exited, status=218/CAPABILITIES)】
在搜索结果中我猜这个可能有用
https://www.daxiblog.com/v2ray%E5%90%AF%E5%8A%A8%E6%8A%A5codeexited-status218-capabilities%E9%94%99%E8%AF%AF%E7%9A%84%E8%A7%A3%E5%86%B3%E6%96%B9%E6%B3%95/

**Comment by crazypeace** [comment]
对了，在我的vps上，v2ray.service的位置和那篇文章里的不一样。在 /lib/systemd/system/v2ray.service 
你可能需要用 find 命令找一下

**Comment by fi5** [comment]
多谢。我这里没起作用，还是起不来。

**Comment by fi5** [comment]
> 对了，在我的vps上，v2ray.service的位置和那篇文章里的不一样。在 /lib/systemd/system/v2ray.service
> 你可能需要用 find 命令找一下

我重新部了一台vps可以了，不晓得什么问题
