### ISSUE TITLE
请问有没有gitee搭建的方法

### ISSUE THREAD

**Issue by 1965514404** [233boy/v2ray#725]
....额,我用腾讯云的国内服务器搭建v2,使用这脚本发现服务器无法连接到github因为他是外网的,我主要用来免流而不是fq

**Comment by crazypeace** [comment]
把233脚本和v2ray都拿到你自己的服务器上，再进行 本地安装，参考：
https://zelikk.blogspot.com/2021/03/233-v2ray-download-local-install.html

**Comment by 1965514404** [comment]
非常感谢

**Comment by 1965514404** [comment]
那个请问搭建已经成功了,但是连不上,就是连接超时,是什么原因....腾讯轻量云,国内服务器

**Comment by crazypeace** [comment]
说一下你都排除了哪些问题。
或者说你参考的哪一篇教程，是不是教程里说的你都完成了。

**Comment by 1965514404** [comment]
嗯,照着做的,那个教程,已经显示安装成功得反馈,把对应得信息输入到手机上后连不上,阿里云得轻量云服务器搭建完延迟非常高,这个基本连不上,直接ping服务器ip有显示

**Comment by 1965514404** [comment]
然后防火墙我(腾讯这边叫安全组)出战和入站规则已经全部允许

**Comment by crazypeace** [comment]
教程网址贴一下

**Comment by 1965514404** [comment]
https://zelikk.blogspot.com/2021/03/233-v2ray-download-local-install.html就是你提供得教程.去gtihub下载得master脚本和vray....要不要我把我的服务器连接方式发给你你看一下我有什么做的不妥当得

**Comment by crazypeace** [comment]
如果是延迟高，不是v2ray的问题。
你试试v2ray的旧版本 https://github.com/v2fly/v2ray-core/releases/download/v4.27.0/v2ray-linux-64.zip

我那篇教程只是帮你搭起来，如果是阿里云、腾讯云带来的问题（而不是v2ray的问题），你需要去查更多的针对服务器的教程。

**Comment by crazypeace** [comment]
推荐你加入 v2ray 的telegram group喊一嗓子？
https://t.me/projectv2ray

还有Xray的telegram group
https://t.me/projectXray

**Comment by 1965514404** [comment]
https://233boy.github.io/tools/qr.html#vmess://ewoidiI6ICIyIiwKInBzIjogIjIzM3YyLmNvbV84MS42OS4xOTguNjIiLAoiYWRkIjogIjgxLjY5LjE5OC42MiIsCiJwb3J0IjogIjgwIiwKImlkIjogIjg4ZTk0NzQ5LWRlNjItNDE4OC1hMTQyLTUwODFmMGJiNzU1MyIsCiJhaWQiOiAiMCIsCiJuZXQiOiAid3MiLAoidHlwZSI6ICJub25lIiwKImhvc3QiOiAiIiwKInBhdGgiOiAiIiwKInRscyI6ICIiCn0K

**Comment by 1965514404** [comment]
您可以帮我看一下么,,,我只是想要一个延迟稳定得v2用于免流.我找过很多机场都不满足要求,只能自己搭建

**Comment by crazypeace** [comment]
我没有用过内地的VPS，对于这类VPS的优化也不清楚。
我只是知道如何解决你的“不能从github下载导致不能安装”的问题。

**Comment by crazypeace** [comment]
我觉得你可以先设置一个普通的v2ray服务端，然后看看使用起来怎么样。如果这样都不好用，那问题不出在免流上面。

**Comment by 1965514404** [comment]
嗯,麻烦你了,我在自己看一下

**Comment by 1965514404** [comment]
问题不在免流上,,,以前用国外服务器搭建过,并没有什么问题....

**Comment by 1965514404** [comment]
发现问题乐,,,,,好像是因为测速的那个网址呗墙乐导致的

**Comment by 1965514404** [comment]
额,现在已经可以了,就是感觉延迟非常高.好像流量走了国外又回来了的感觉,还是要使用ssr和openvpn试试

**Comment by 1965514404** [comment]
https://233boy.github.io/tools/qr.html#vmess://ewoidiI6ICIyIiwKInBzIjogIjIzM3YyLmNvbV84MS42OS4xOTguNjIiLAoiYWRkIjogIjgxLjY5LjE5OC42MiIsCiJwb3J0IjogIjgwIiwKImlkIjogImY3ZjE2MjhjLTllZDItNDUyYS1hZTE5LWU4MGI4NzgwMTU5OSIsCiJhaWQiOiAiMCIsCiJuZXQiOiAid3MiLAoidHlwZSI6ICJub25lIiwKImhvc3QiOiAiIiwKInBhdGgiOiAiIiwKInRscyI6ICIiCn0K

**Comment by 1965514404** [comment]
这个是腾讯国内云服务器1m得,可以访问百度,不能github和谷歌得

**Comment by Arjen10** [comment]
有没有兴趣把干扰开源一下😀
