### ISSUE TITLE
config.json应该没有问题，但是服务一直启不来，netflix流量转发

### ISSUE THREAD

**Issue by mj923** [233boy/v2ray#726]
手上有两台VPS，都是使用233boy的一键脚本安装的v2ray。一台Oracle云的韩国VPS，看奈飞没有中文字幕，一台是香港的看奈飞比较爽，想能不能实现直连韩国这台，到netflix的流量都导到香港的VPS，于是有了以下的配置，但一直报错。不知道各位大神有遇到过这种问题不？
报错内容如下：

> V2Ray 4.36.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16 linux/amd64)
> A unified platform for anti-censorship.
> 2021/03/25 15:35:02 [Info] github.com/v2fly/v2ray-core/v4/main/jsonem: Reading config: /etc/v2ray/config.json.bak
> main: failed to read config files: [/etc/v2ray/config.json] > github.com/v2fly/v2ray-core/v4/infra/conf: 0 VMess receiver configured

配置文件如下：
> {
>         "log": {
>                 "access": "/var/log/v2ray/access.log",
>                 "error": "/var/log/v2ray/error.log",
>                 "loglevel": "warning"
>         },
>         "inbounds": [
>                 {
>                         "port": 51888,
>                         "protocol": "vmess",
>                         "settings": {
>                                 "clients": [
>                                         {
>                                                 "id": "894ae8f8-191d-4c28-be09-b38b5dd8ae1f",
>                                                 "level": 1,
>                                                 "alterId": 0
>                                         }
>                                 ]
>                         },
>                         "streamSettings": {
>                                 "network": "ws"
>                         },
>                         "sniffing": {
>                                 "enabled": true,
>                                 "destOverride": [
>                                         "http",
>                                         "tls"
>                                 ]
>                         }
>                 }
>         ],
>         "outbounds": [
>                 {
>                         "protocol": "freedom",
>                         "settings": {}
>                 },
>                 {
>                         "protocol": "vmess",
>                         "setting": {
>                                 "vnext": [{
>                                         "address": "hk.gogogo.xyz",
>                                         "port": 443,
>                                         "user": [{
>                                                 "id": "244ff17e-8561-4481-aff7-e1fa8b098280",
>                                                 "security": "auto",
>                                                 "alterId": 0
>                                                 }]
>                                         }]
>                                     },
>                         "tag": "HK"
>                 }
>         ],
>         "dns": {
>                 "servers": [
>                         "https+local://cloudflare-dns.com/dns-query",
>                         "1.1.1.1",
>                         "1.0.0.1",
>                         "8.8.8.8",
>                         "8.8.4.4",
>                         "localhost"
>                 ]
>         },
>         "routing": {
>                 "domainStrategy": "IPOnDemand",
>                 "rules": [
>                         {
>                                 "type": "field",
>                                 "domain": ["geosite:netflix"],
>                                 "outboundTag": "HK"
>                         }
>                 ]
>         },
>         "transport": {
>                 "kcpSettings": {
>             "uplinkCapacity": 100,
>             "downlinkCapacity": 100,
>             "congestion": true
>         }
>         }

**Comment by crazypeace** [comment]
报错说有问题就是有问题，文件读取失败，和文件里面配置项写得对不对没关系。
你找个json检查工具，比如：https://www.json.cn/

我猜是"congestion": true }  这里少了一个 }  

另外，id port address 这些关键信息最好是打码了再发出来。

**Comment by mj923** [comment]
感谢，确实是自己编辑JSON文件不熟悉，现在已经搞定了！
