### ISSUE TITLE
用了这个脚本，CPU100%被占用，应该是被拿来挖矿了

### ISSUE THREAD

**Issue by TianLing2020** [233boy/v2ray#727]
用了这个脚本，CPU100%被占用，应该是被拿来挖矿了
重装系统后用别的脚本CPU维持在20%

**Comment by 23232333aaa** [comment]
> 用了这个脚本，CPU100%被占用，应该是被拿来挖矿了
> 重装系统后用别的脚本CPU维持在20%

估計是你服務器別的地方的事，我的一直是0.3%

**Comment by kkkccz** [comment]
是的，我也有同样的情况。我自己搭建的CPU空闲使用率是0，用这个脚本CPU使用率稳定在30%。
