### ISSUE TITLE
启动v2ray，但status显示没有运行

### ISSUE THREAD

**Issue by WTFnicetry** [233boy/v2ray#728]
输入 v2ray start启动后，v2ray status显示未在运行...

**Comment by crazypeace** [comment]
如果你记得用某个旧版本的v2ray是一切正常的，你可以试试继续用旧版本的v2ray. 你也可以用某个旧版本的233脚本。
参考：
https://zelikk.blogspot.com/2021/01/233v2ray-local.html
https://zelikk.blogspot.com/2021/01/233v2ray-github-commit-.html
