### ISSUE TITLE
V2Ray 启动失败 ，重新安装，检测使用的端口是否被其他程序占用，也没有

### ISSUE THREAD

**Issue by AllanTian** [233boy/v2ray#729]

**Comment by AllanTian** [comment]
V2Ray 启动失败 ，重新安装，检测使用的端口是否被其他程序占用，也没有用，重新启动，更换端口，重启VPS 我都尝试过了，还是启动失败，执行启动命令显示启动成功，但是v2ray status 查看显示 V2Ray 状态: 未在运行

**Comment by skyfuckerzhao** [comment]
> V2Ray 启动失败 ，重新安装，检测使用的端口是否被其他程序占用，也没有用，重新启动，更换端口，重启VPS 我都尝试过了，还是启动失败，执行启动命令显示启动成功，但是v2ray status 查看显示 V2Ray 状态: 未在运行

是不是ss没有选默认的协议

**Comment by l8487** [comment]
重装vps，用root用户搞。

**Comment by ixsword** [comment]
我就是root用户啊，跟你的一样的情况，而且log一点信息都没有，我还以为这脚本有后门，赶紧卸了

**Comment by crazypeace** [comment]
请看 https://github.com/233boy/v2ray/issues/675

233脚本很久都没动了，你也可以使用旧一点版本的v2ray。比如参考这个：
https://github.com/crazypeace/v2ray

**Comment by AllanTian** [comment]
对啊，我也是使用root 用户直接安装的，并且系统是新开的，端口占用也查看了，没有存在占用

**Comment by AllanTian** [comment]
> 重装vps，用root用户搞。

**Comment by AllanTian** [comment]
> > V2Ray 启动失败 ，重新安装，检测使用的端口是否被其他程序占用，也没有用，重新启动，更换端口，重启VPS 我都尝试过了，还是启动失败，执行启动命令显示启动成功，但是v2ray status 查看显示 V2Ray 状态: 未在运行
> 
> 是不是ss没有选默认的协议

选择了，安装的时候我选了默认协议

**Comment by AllanTian** [comment]
> 请看 #675
> 
> 233脚本很久都没动了，你也可以使用旧一点版本的v2ray。比如参考这个：
> https://github.com/crazypeace/v2ray

好的，我试下
