### ISSUE TITLE
哎呀哎呀…… 出错咯...请重新安装V2Ray ~(^_^) 

### ISSUE THREAD

**Issue by SMooxx** [233boy/v2ray#731]
v2ray 命令， 就提示

>哎呀哎呀…… 出错咯...请重新安装V2Ray ~(^_^) 

已经连续两次出现这种情况。

第一次是直接莫名其妙丢失 etc/v2ray文件夹下的所有配置，

第二次就是什么都没有操作，只要输入 v2ray 就提示“哎呀哎呀…… 出错咯...请重新安装V2Ray ~(^_^) ”

ps -ef查看 v2ray 进程还在

很诡异。

**Comment by crazypeace** [comment]
如果你记得用某个旧版本的v2ray是一切正常的，你可以试试继续用旧版本的v2ray. 你也可以用某个旧版本的233脚本。
参考：
https://zelikk.blogspot.com/2021/01/233v2ray-local.html
https://zelikk.blogspot.com/2021/01/233v2ray-github-commit-.html
