### ISSUE TITLE
help求助，搭建起v2ray结点后，就是不能上网，ping检测ip地址，可以ping通

### ISSUE THREAD

**Issue by muyi4757** [233boy/v2ray#733]
在vultr买的服务器，ping检测IP可上网，但是搭建起v2ray服务后，将节点导入v2ray软件就是不能上网，国内网站都不能访问。纯小白啥也不懂，不知道问题再哪里。
####1这是v2ray的日志信息：
`2021/04/11 00:29:03 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 155.138.149.100:233: i/o timeout] > v2ray.com/core/common/retry: all retry attempts failed`
####2然后这是xshell6搭建好v2ray服务的信息
`---------- V2Ray 配置信息 -------------

 地址 (Address) = 155.138.149.100

 端口 (Port) = 233

 用户ID (User ID / UUID) = 290fc3af-cede-4a2e-81b7-7d2d44a19199

 额外ID (Alter Id) = 0

 传输协议 (Network) = tcp

 伪装类型 (header type) = none

---------- END -------------

V2Ray 客户端使用教程: https://233v2.com/post/4/

提示: 输入  v2ray url  可生成 vmess URL 链接 / 输入  v2ray qr  可生成二维码链接

免被墙..推荐使用JMS: https://getjms.com

root@muyi4757:~# v2ray url

---------- V2Ray vmess URL / V2RayNG v0.4.1+ / V2RayN v2.1+ / 仅适合部分客户端 -------------

vmess://ewoidiI6ICIyIiwKInBzIjogIjIzM3YyLmNvbV8xNTUuMTM4LjE0OS4xMDAiLAoiYWRkIjogIjE1NS4xMzguMTQ5LjEwMCIsCiJwb3J0IjogIjIzMyIsCiJpZCI6ICIyOTBmYzNhZi1jZWRlLTRhMmUtODFiNy03ZDJkNDRhMTkxOTkiLAoiYWlkIjogIjAiLAoibmV0IjogInRjcCIsCiJ0eXBlIjogIm5vbmUiLAoiaG9zdCI6ICIiLAoicGF0aCI6ICIiLAoidGxzIjogIiIKfQo=
`
导入url后，全局代理就是不能上网，不知到问题在哪，希望有大佬解答下疑问，谢谢啦

**Comment by crazypeace** [comment]
电脑还是手机？
电脑试试v2rayn的旧版本 v3.29

**Comment by wangliho** [comment]
vps防火墙关了没 systemctl status firewalld active的话关掉 systemctl stop firewalld

**Comment by qq332984152** [comment]
好像是Win10的问题，还在查。

**Comment by Feng-Bu-Jue** [comment]
我也是遇到一样的问题
通过 `bash <(curl -s -L https://git.io/v2ray.sh) ` 一路回车默认配置后 

开启全局代理后，直接用chrome 访问波报错
```
500 Internal Privoxy Error
Please contact your proxy administrator.

If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory).
```

**Comment by trdthg** [comment]
我的也是，不过手机端倒是能连

**Comment by JavaBoysx** [comment]
我搭建的最新版v2ray，没有什么问题，但是用不了，没有网络，端口我开放了，测速的时候会报
![image](https://github.com/233boy/v2ray/assets/70039764/f44f20d3-c28c-4826-af2b-b9009327c3fd)

**Comment by crazypeace** [comment]
> 我搭建的最新版v2ray，没有什么问题，但是用不了，没有网络，端口我开放了，测速的时候会报 ![image](https://user-images.githubusercontent.com/70039764/274767926-f44f20d3-c28c-4826-af2b-b9009327c3fd.png)

 排错教程
https://zelikk.blogspot.com/2022/04/setup-v2ray-websocket-tls-troubleshoot.html
https://zelikk.blogspot.com/2022/04/connect-v2ray-websocket-tls-troubleshoot.html
