### ISSUE TITLE
新版V2ray NG无法使用

### ISSUE THREAD

**Issue by yizhiaoxiangdeying** [233boy/v2ray#734]
新版V2rayNG无法使用223boy脚本搭建的http协议的节点
![S10411-11494634](https://user-images.githubusercontent.com/73765513/114291736-4f4e6900-9abc-11eb-8233-0638503d2a8f.png)  
![S10411-11391926](https://user-images.githubusercontent.com/73765513/114291753-6b520a80-9abc-11eb-9505-d432db359b50.png)

**Comment by crazypeace** [comment]
1. 你换个协议就可以用了吗？  - 确认是否是http协议带来的问题
2.  Google搜一下 "io: read/write on closed pipe" 大部分答案是服务器与客户端时间不一致。

**Comment by yizhiaoxiangdeying** [comment]
我使用旧版的v2ray能够正常使用我的那个http协议的节点，我Google搜一下 "io: read/write on closed pipe"&nbsp;按照网上提供的方法校正了服务器的时间，结果还是显示"io: read/write on closed pipe"&nbsp;我认为是新版的v2ray的原因&nbsp;

追求不止，只因热爱

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月13日(星期二) 中午11:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [233boy/v2ray] 新版V2ray NG无法使用 (#734)





  
你换个协议就可以用了吗？  - 确认是否是http协议带来的问题
 
Google搜一下 "io: read/write on closed pipe" 大部分答案是服务器与客户端时间不一致。

**Comment by liuhongzhe111** [comment]
偷偷的告诉你，在path里输入/有奇效。
