### ISSUE TITLE
V2Ray 状态: 未在运行

### ISSUE THREAD

**Issue by fishmisswater** [233boy/v2ray#743]
[root@gtco4qgr ~]# v2ray start

 V2Ray 已启动

[root@gtco4qgr ~]# v2ray status

 V2Ray 状态: 未在运行

重装不行，安装 v4.27.0也不行。

**Comment by Demon1630** [comment]
我也是，两台vps上安装都是出现未在运行问题

**Comment by Jmt1995** [comment]
怎么办？

**Comment by minggangLu** [comment]
我的也是

**Comment by yohototo** [comment]
一样的问题，有没有早期版本的
