### ISSUE TITLE
v2ray web+tls 昨天突然就不能用了，客户端提示这个

### ISSUE THREAD

**Issue by Apurikotto** [233boy/v2ray#746]
>  [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://2***.********.tk/):  > dial tcp 1*.2*.*.*:443: i/o timeout] > v2ray.com/core/common/retry: all retry attempts failed

搜了好久说是监听不了443端口？因为dial tcp 1*.2*.*.*:443: i/o timeout这段？
但是我监视了端口并好像没有问题

> [root@root ~]# netstat -lnpt
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      9136/sshd           
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      9259/master         
tcp6       0      0 :::80                   :::*                    LISTEN      31732/caddy         
tcp6       0      0 :::22                   :::*                    LISTEN      9136/sshd           
tcp6       0      0 ::1:25                  :::*                    LISTEN      9259/master         
tcp6       0      0 :::443                  :::*                    LISTEN      31732/caddy         
tcp6       0      0 :::64388                :::*                    LISTEN      31951/v2ray  

奇怪的是我如果不用伪装直接用tcp的话是可以用的，问题到底出在哪里了。。
服务器根本没有报错
昨天之前都是可以用的，重装，换域名都没有用，太怪了，求帮助谢谢

**Comment by Apurikotto** [comment]
顺便一提重装之后用的是crazypeace的版本，还是不行

**Comment by charmingYouYou** [comment]
遇到同样的问题, 求助!!!

**Comment by Apurikotto** [comment]
> 遇到同样的问题, 求助!!!

错误代码也一样吗？什么情况

**Comment by Apurikotto** [comment]
> 遇到同样的问题, 求助!!!

找到问题了，是我的443端口被墙了，在cloudflare套了个cdn就好了
