### ISSUE TITLE
我发现这个脚本用不了了

### ISSUE THREAD

**Issue by hoctoboy** [233boy/v2ray#748]
这个脚本前几天突然就用不了了，最开始以为是我服务器的问题，现在，经过两天的测试，使用它就不行，使用其他的脚本就可以科学上网，应该是这个脚本出问题了，各位有遇到吗，希望博主看到后回复，一直觉得这个一键脚本做得最好，去年坚持了一年很稳定，希望早日解决这个问题，加油啊

**Comment by top-develpoer** [comment]
大佬，能发下其他脚本嘛，我想试试看。弄了半天还是连不上😭

**Comment by crazypeace** [comment]
突然用不了一般都是有东西改动了。可能是v2ray新版本？脚本新版本？

如果你想在最新的233脚本上指定下载某个版本的v2ray
https://zelikk.blogspot.com/2021/01/233v2ray-local.html

如果你想下载某个“旧版本”的233脚本
https://zelikk.blogspot.com/2021/01/233v2ray-github-commit-.html

**Comment by top-develpoer** [comment]
> 突然用不了一般都是有东西改动了。可能是v2ray新版本？脚本新版本？
> 
> 如果你想在最新的233脚本上指定下载某个版本的v2ray
> https://zelikk.blogspot.com/2021/01/233v2ray-local.html
> 
> 如果你想下载某个“旧版本”的233脚本
> https://zelikk.blogspot.com/2021/01/233v2ray-github-commit-.html

感谢
