### ISSUE TITLE
俄区vps，服务器已配置，客户端连接后无流量。能ping通主机，telnet端口无响应

### ISSUE THREAD

**Issue by JiinJie** [233boy/v2ray#749]
各位好：
我的ssr v2都配置了，安卓和PC客户端连接后无上下行流量，客户端均为最新版软件
问题排查：能ping通主机，ip应该没有被墙，服务器提示ssr和v2的进程都在运行，ufw防火墙已关闭（相关端口已开放）。
服务器访问网络正常，ping了google、baidu。
实在想不出还有什么原因会导致连接无法使用，大佬们能看看是啥原因不？

**Comment by yiqingdi** [comment]
同步服务器时间

**Comment by cui830608** [comment]
你好，请问解决了么，我也是同样的问题，安装都成功了，就是没有流量。上不了网。

**Comment by JiinJie** [comment]
这个脚本有问题，请尝试使用其他版本的脚本

**Comment by cui830608** [comment]
有其他一键脚本么，求推荐一个，谢谢了。

**Comment by JiinJie** [comment]
https://github.com/crazypeace/v2ray
在233脚本的基础上改的，修复了一些bug，可以正常运行的
