### ISSUE TITLE
安装最新的脚本后无法使用,求指教，谢谢各位大佬

### ISSUE THREAD

**Issue by juefeiyechen** [233boy/v2ray#750]
安装最新的脚本后无法使用，防火墙这些都关了的

**Comment by yjghb** [comment]
今天凌晨3点多突然无法使用了,域名解析,ping ip都正常,然后用ssr安装使用也能正常使用.
后来关闭所有分流/域名伪装, 协议只选websocket 就可以了,,我怀疑是caddy tls证书失效有关,,,脚本不是应该会自动续签时间的吗

**Comment by yjghb** [comment]
> 安装最新的脚本后无法使用，防火墙这些都关了的

可以参考下我遇到的:  今天凌晨3点多突然无法使用了,域名解析,ping ip都正常,然后用ssr安装使用也能正常使用.
后来关闭所有分流/域名伪装, 协议只选websocket 就可以了,,我怀疑是caddy tls证书失效有关,,,脚本不是应该会自动续签时间的吗

**Comment by juefeiyechen** [comment]
> > 安装最新的脚本后无法使用，防火墙这些都关了的
> 
> 可以参考下我遇到的: 今天凌晨3点多突然无法使用了,域名解析,ping ip都正常,然后用ssr安装使用也能正常使用.
> 后来关闭所有分流/域名伪装, 协议只选websocket 就可以了,,我怀疑是caddy tls证书失效有关,,,脚本不是应该会自动续签时间的吗

我去找了一个老的脚本才行

**Comment by jake9301** [comment]
> > > 安装最新的脚本后无法使用，防火墙这些都关了的
> > 
> > 
> > 可以参考下我遇到的: 今天凌晨3点多突然无法使用了,域名解析,ping ip都正常,然后用ssr安装使用也能正常使用.
> > 后来关闭所有分流/域名伪装, 协议只选websocket 就可以了,,我怀疑是caddy tls证书失效有关,,,脚本不是应该会自动续签时间的吗
> 
> 我去找了一个老的脚本才行

用的哪个老版本的脚本? 我用的一个得换端口才可以使用 但是换了端口等于tls也没用 麻烦发下
