### ISSUE TITLE
ping 正常，打不开推特主页。。。

### ISSUE THREAD

**Issue by itcodes** [233boy/v2ray#752]
打不开推特主页。升级了最新脚本之后。。

**Comment by transparentmask** [comment]
这几天总体不太正常... 估计墙启用了v2ray的规则吧...

**Comment by itcodes** [comment]
> 这几天总体不太正常... 估计墙启用了v2ray的规则吧...

好吧。能刷到 feed 流。不能打开个人主页。。问题挺多。
