### ISSUE TITLE
websocket + tls 或 HTTP/2无法连接

### ISSUE THREAD

**Issue by DDullahan** [233boy/v2ray#753]
原本一直使用的websocket+tls 大概两年时间了
最近突然连接不上报 i/o time out

查了一下 ping通 tcping 80端口通 tcping 443端口不通 
443端口也确实建立了连接 都处在SYN_RECV状态

猜测可能是caddy或v2ray更新导致出现bug

目前本人的解决方案是使用websocket或者tcp 避开使用caddy的协议 可正常访问

**Comment by gcfanghao** [comment]
443端口被封了

**Comment by canondin** [comment]
有什么解决办法吗？我一度怀疑鸿蒙把谷歌给禁了。。

**Comment by leshaofeng** [comment]
就是caddy证书出问题了,我也以为443端口被封了
结果发现同一机房其他机器都是好的
唯一区别就是被封那台我更新了脚本和v2ray

**Comment by MaDd0G007** [comment]
> 就是球童证书出问题了，我也以为443端口被封了
> 结果发现了同一机房其他机器都是
> 很好的唯一区别就是连不上那台我之前更新了脚本和v2ray，其他的装好v2ray后基本没动过

同

**Comment by FLynnGame** [comment]
caddy证书出问题，应该怎么修复呢？我这边也是没辙caddy证书出问题，应该怎么修复呢？我这边也是没辙

**Comment by FLynnGame** [comment]
caddy证书出问题，应该怎么修复呢？我这边也是没辙了

**Comment by FrankRoc** [comment]
> 看了v2ray日志
> `rejected v2ray.com/core/proxy/socks: unknown Socks version: 3`
> 改成ws，可以用了，端口默认的，感觉比ws+tls快

同改成ws 可以用了

**Comment by crazypeace** [comment]
跑ws+tls模式的不用更新。能跑就一直用。我用这个旧版本ws+tls用到现在啥事没有。
https://github.com/crazypeace/v2ray
