### ISSUE TITLE
装了以后机器密码被改了？

### ISSUE THREAD

**Issue by John0x00** [233boy/v2ray#754]
老板牛逼啊

**Comment by big-idea** [comment]
我也是，过了一段时间vps root密码登不上了

**Comment by big-idea** [comment]
我也是，过了一段时间vps root密码登不上了

**Comment by John0x00** [comment]
看来是真的了，一键脚本不能用 啊，花里胡哨，机器没了。哈哈

big-idea ***@***.***> 于2021年6月27日周日 上午3:10写道：
