### ISSUE TITLE
小白求救555用了ws+tls失败 用tcp也失败

### ISSUE THREAD

**Issue by shuyeee** [233boy/v2ray#757]
用ws+tls的时候显示：2021/06/29 23:41:44 [Warning] [2052417458] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://kuaileqifei.xyz/): 502 Bad Gateway > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed

用的vultr日本服务器
但是我域名是可以ping出来的。。

用tcp的时候显示这个：2021/06/30 00:00:15 [Warning] [3363230817] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 66.42.37.85:34505: connectex: No connection could be made because the target machine actively refused it. dial tcp 66.42.37.85:34505: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. dial tcp 66.42.37.85:34505: connectex: No connection could be made because the target machine actively refused it.] > v2ray.com/core/common/retry: all retry attempts failed

**Comment by FLynnGame** [comment]
相同问题，wss连接不上，还不知道咋回事，不知道有没有大佬清楚，这个脚本目前出bug了

**Comment by guaiwucc** [comment]
遇到同样问题 脚本有问题

**Comment by dbguo** [comment]
443端口被封了吧

**Comment by crazypeace** [comment]
ws+tls 旧版本就有啊，用得挺好的就不用更新。
安全性是TLS保证的，里面vmess不是最新的版本也没问题。
你试试这个旧版本
https://github.com/crazypeace/v2ray

**Comment by willianzhao** [comment]
别猜了，直接这样修复：

在你的云服务网站上，打开所有的TCP incoming ports。 

![image](https://user-images.githubusercontent.com/302781/131228348-97491fff-873a-4d67-9ecd-dd4074a12178.png)
