### ISSUE TITLE
请问大大什么时候可以添加多用户功能？

### ISSUE THREAD

**Issue by xunqiuhuiyi** [233boy/v2ray#76]
一直使用大大的v2一键脚本 非常好用 现在挂在路由器里面非常方便
但是目前有需要 手机也想使用 看你写的不支持多用户
找到了https://github.com/Jrohy/multi-v2ray  雨落无声的多用户脚本 但是不知道能不能同时安装在一个vps上面  特来请教 
如果可以的话 还是希望大大能够添加多用户 用大大的脚本 稳定 放心 谢谢

**Comment by andyliang007008** [comment]
> 一直使用大大的v2一键脚本 非常好用 现在挂在路由器里面非常方便
> 但是目前有需要 手机也想使用 看你写的不支持多用户
> 找到了https://github.com/Jrohy/multi-v2ray 雨落无声的多用户脚本 但是不知道能不能同时安装在一个vps上面 特来请教
> 如果可以的话 还是希望大大能够添加多用户 用大大的脚本 稳定 放心 谢谢

我也想大大支持多用户，因为我和几个朋友一起用。
