### ISSUE TITLE
v2ray 4.40.1 /usr/local/bin/v2ray   Failed to execute command: No such file or directory   

### ISSUE THREAD

**Issue by ToTdate** [233boy/v2ray#761]
Debian 10  v2ray 4.40.1

安装报错，日志如下

请问这是什么原因导致的，我google了三天了，实在找不到答案！debian10 已经apt install update upgrade，

我的理解：   /usr/local/bin/v2ray 这个目录与服务进程都不存在，但是安装的时候不是应该写入目录与文件吗？为什么会不存在？然后更高端的linux 命令与运用我一时半会也不会，全程都是自己按教程琢磨，不明白的google，但是这个可能太基础了，请路过的大神指点下，不胜感激~~

PS：已经三天吃饭不香了，拜谢！

// v2ray 安装日志

Downloading verification file for V2Ray archive: https://github.com/v2fly/v2ray-core/releases/download/v4.40.1/v2ray-linux-64.zip.dg                                   st
info: Extract the V2Ray package to /tmp/tmp.X8WLXRjiqg and prepare it for installation.
rm: cannot remove '/etc/systemd/system/v2ray.service.d/10-donot_touch_multi_conf.conf': No such file or directory
rm: cannot remove '/etc/systemd/system/v2ray@.service.d/10-donot_touch_multi_conf.conf': No such file or directory
info: Systemd service files have been installed successfully!
warning: The following are the actual parameters for the v2ray service startup.
warning: Please make sure the configuration file path is correctly set.
# /etc/systemd/system/v2ray.service
[Unit]
Description=V2Ray Service
Documentation=https://www.v2fly.org/
After=network.target nss-lookup.target

[Service]
User=nobody
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
NoNewPrivileges=true
ExecStart=/usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json
Restart=on-failure
RestartPreventExitStatus=23

[Install]
WantedBy=multi-user.target

# /etc/systemd/system/v2ray.service.d/10-donot_touch_single_conf.conf
# In case you have a good reason to do so, duplicate this file in the same directory and make your customizes there.
# Or all changes you made will be lost!  # Refer: https://www.freedesktop.org/software/systemd/man/systemd.unit.html
[Service]
ExecStart=
ExecStart=/usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json

installed: /usr/local/bin/v2ray
installed: /usr/local/bin/v2ctl
installed: /usr/local/share/v2ray/geoip.dat
installed: /usr/local/share/v2ray/geosite.dat
installed: /etc/systemd/system/v2ray.service
installed: /etc/systemd/system/v2ray@.service
removed: /tmp/tmp.X8WLXRjiqg
info: V2Ray v4.40.1 is installed.
You may need to execute a command to remove dependent software: apt purge curl unzip

// v2ray 运行日志

root@sv-486 :~# service v2ray status
● v2ray.service - V2Ray Service
   Loaded: loaded (/etc/systemd/system/v2ray.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/v2ray.service.d
           └─10-donot_touch_single_conf.conf
   Active: failed (Result: exit-code) since Tue 2021-07-06 23:41:24 CST; 7s ago
     Docs: https://www.v2fly.org/
  Process: 16675 ExecStart=/usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json (code=exited, status=203/EXEC)
 Main PID: 16675 (code=exited, status=203/EXEC)

Jul 06 23:41:24 sv-486  systemd[1]: v2ray.service: Service RestartSec=100ms expired, scheduling restart.
Jul 06 23:41:24 sv-486  systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 5.
Jul 06 23:41:24 sv-486  systemd[1]: Stopped V2Ray Service.
Jul 06 23:41:24 sv-486  systemd[1]: v2ray.service: Start request repeated too quickly.
Jul 06 23:41:24 sv-486  systemd[1]: v2ray.service: Failed with result 'exit-code'.
Jul 06 23:41:24 sv-486  systemd[1]: Failed to start V2Ray Service.

// v2ray服务异常日志如下

root@sv-486:~# journalctl -u v2ray
-- Logs begin at Mon 2021-07-05 11:03:19 CST, end at Tue 2021-07-06 23:41:24 CST. --
Jul 05 12:03:09 sv-486 systemd[1]: Started V2Ray Service.
Jul 05 12:03:09 sv-486 systemd[13777]: v2ray.service: Failed to execute command: No such file or directory
Jul 05 12:03:09 sv-486 systemd[13777]: v2ray.service: Failed at step EXEC spawning /usr/local/bin/v2ray: No s
Jul 05 12:03:09 sv-486 systemd[1]: v2ray.service: Main process exited, code=exited, status=203/EXEC
Jul 05 12:03:09 sv-486 systemd[1]: v2ray.service: Failed with result 'exit-code'.
Jul 05 12:03:09 sv-486 systemd[1]: v2ray.service: Service RestartSec=100ms expired, scheduling restart.
Jul 05 12:03:09 sv-486 systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 1.
Jul 05 12:03:09 sv-486 systemd[1]: Stopped V2Ray Service.
Jul 05 12:03:09 sv-486 systemd[1]: Started V2Ray Service.
Jul 05 12:03:09 sv-486 systemd[13778]: v2ray.service: Failed to execute command: No such file or directory
Jul 05 12:03:09 sv-486 systemd[13778]: v2ray.service: Failed at step EXEC spawning /usr/local/bin/v2ray: No s
Jul 05 12:03:09 sv-486 systemd[1]: v2ray.service: Main process exited, code=exited, status=203/EXEC
Jul 05 12:03:09 sv-486 systemd[1]: v2ray.service: Failed with result 'exit-code'.
Jul 05 12:03:10 sv-486 systemd[1]: v2ray.service: Service RestartSec=100ms expired, scheduling restart.
Jul 05 12:03:10 sv-486 systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 2.
Jul 05 12:03:10 sv-486 systemd[1]: Stopped V2Ray Service.
Jul 05 12:03:10 sv-486 systemd[1]: Started V2Ray Service.
Jul 05 12:03:10 sv-486 systemd[13779]: v2ray.service: Failed to execute command: No such file or directory
Jul 05 12:03:10 sv-486 systemd[13779]: v2ray.service: Failed at step EXEC spawning /usr/local/bin/v2ray: No s
Jul 05 12:03:10 sv-486 systemd[1]: v2ray.service: Main process exited, code=exited, status=203/EXEC
Jul 05 12:03:10 sv-486 systemd[1]: v2ray.service: Failed with result 'exit-code'.

**Comment by crazypeace** [comment]
以前装过233脚本吗？正常吗？
那就继续用老版本呗。
试试这个？https://github.com/crazypeace/v2ray
