### ISSUE TITLE
v2ray + ws +TLS 配置 默认流程走下来用了三天没问题，从7/7开始就不能用了，查不清楚原因

### ISSUE THREAD

**Issue by davidGooo** [233boy/v2ray#762]
你好：
目前重新走了下流程，配置成v2ray+WS 的方式 ，能正常上网，手机 电脑 都可以，但加上TLS就不行了，怀疑是TLS配置出问题了，想修改candy的 443端口，请问需要如何修改

**Comment by MichaelJokAr** [comment]
我7.1前就不能用了

**Comment by crazypeace** [comment]
ws+tls模式的，能用就不要瞎更新。
继续用老版本挺好的。
https://github.com/crazypeace/v2ray

**Comment by jasonfan168** [comment]
建议看下是不是443端口被墙了，我的就是未升级却忽然连不上了，开始以为是服务器问题，折腾半天，最后发现是端口被墙了

**Comment by MichaelJokAr** [comment]
我换了脚本就可以了，这个脚本又很大问题；https://ssr.tools/1810

**Comment by davidGooo** [comment]
有木有大神帮忙看看原因呢？

**Comment by daixiaokang** [comment]
> ws+tls模式的，能用就不要瞎更新。 继续用老版本挺好的。 https://github.com/crazypeace/v2ray

大佬，这是什么原因呢？ 我也是ws+tls用了快一年了，最新重装了一下就不行了，然后用你的旧的脚本就搞定了。

**Comment by crazypeace** [comment]
> 

有很多种可能。我现在也不研究，233脚本我是知道好久没动了，不知道最近v2ray(v2fly)那边更新了什么。

以前就发生过v2ray(v2fly)把自动启动的设置要求改了，然后这类一键脚本就不兼容了。
还发生过caddy v1升到v2，把配置文件的规则改了，233脚本又是用caddy伪装网站的，配置文件就不生效了。

我觉得，用ws+tls还走CDN的，大多数买的便宜的VPS，就一直用个能用的老版本就够了，youtube能看1080p就够了，哪怕720p也凑活。反正安全性是由tls保证的，GFW只知道你访问了伪装站，不知道你的流量里面访问的是什么。v2ray(v2fly)再怎么更新，也不会动tls啊

**Comment by daixiaokang** [comment]
> > 
> 
> 有很多种可能。我现在也不研究，233脚本我是知道好久没动了，不知道最近v2ray(v2fly)那边更新了什么。
> 
> 以前就发生过v2ray(v2fly)把自动启动的设置要求改了，然后这类一键脚本就不兼容了。 还发生过caddy v1升到v2，把配置文件的规则改了，233脚本又是用caddy伪装网站的，配置文件就不生效了。
> 
> 我觉得，用ws+tls还走CDN的，大多数买的便宜的VPS，就一直用个能用的老版本就够了，youtube能看1080p就够了，哪怕720p也凑活。反正安全性是由tls保证的，GFW只知道你访问了伪装站，不知道你的流量里面访问的是什么。v2ray(v2fly)再怎么更新，也不会动tls啊

**Comment by daixiaokang** [comment]
> > 
> 
> 有很多种可能。我现在也不研究，233脚本我是知道好久没动了，不知道最近v2ray(v2fly)那边更新了什么。
> 
> 以前就发生过v2ray(v2fly)把自动启动的设置要求改了，然后这类一键脚本就不兼容了。 还发生过caddy v1升到v2，把配置文件的规则改了，233脚本又是用caddy伪装网站的，配置文件就不生效了。
> 
> 我觉得，用ws+tls还走CDN的，大多数买的便宜的VPS，就一直用个能用的老版本就够了，youtube能看1080p就够了，哪怕720p也凑活。反正安全性是由tls保证的，GFW只知道你访问了伪装站，不知道你的流量里面访问的是什么。v2ray(v2fly)再怎么更新，也不会动tls啊

给大佬倒茶，是的，我就是买的便宜的vps，三个人用，一般查查资料，偶尔上上youtube，还没套CDN，就用的ws+tls。

**Comment by crazypeace** [comment]
有可能是VMessAEAD相关
https://github.com/v2fly/v2ray-core/issues/1509
