### ISSUE TITLE
只要一使用ws就会出现warning，使用TCP正常

### ISSUE THREAD

**Issue by qiyang77** [233boy/v2ray#763]
vmess ws、ws+TLS； vless ws、ws+TLS都会出现下面的warning。google啥的可以连接，但有时需要刷新一下才行，看到下面的warning就很难受，不管开不开TLS都会出现下面的warning. 用TCP就没有warning，求大佬解答！
`[Warning] [2148791470] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (ws://xxx.xxxxx.com:xxxxx/):  > read tcp 192.168.31.9:49346->xxx.xxx.xxx.xxx:xxxxx: wsarecv: An existing connection was forcibly closed by the remote host. v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (ws://xxx.xxxxx.com:xxxxx/):  > dial tcp xxx.xxx.xxx.xxx:xxxxx: operation was canceled v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (ws://xxx.xxxxx.com:xxxxx/):  > dial tcp: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed`

**Comment by crazypeace** [comment]
你是一直这样还是出问题的时候才这样？
我使用的ws+tls 用了CDN. 有时会这样，域名解析被封了。
1. 我在caddy里加了好几个域名。在V2raynN里添加了对应的几套设置。出现问题的时候切换一下就好了。
https://zelikk.blogspot.com/2021/02/v2ray-path-domain-multi-user.html
2. 域名长时间被封的话，在cf上面加worker.
https://zelikk.blogspot.com/2021/05/domian-ban-websocket-tls-web-cdn-cloudclare-worker.html

**Comment by canondin** [comment]
> vmess ws、ws+TLS； vless ws、ws+TLS都会出现下面的warning。google啥的可以连接，但有时需要刷新一下才行，看到下面的warning就很难受，不管开不开TLS都会出现下面的warning. 用TCP就没有warning，求大佬解答！
> `[Warning] [2148791470] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (ws://xxx.xxxxx.com:xxxxx/): > read tcp 192.168.31.9:49346->xxx.xxx.xxx.xxx:xxxxx: wsarecv: An existing connection was forcibly closed by the remote host. v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (ws://xxx.xxxxx.com:xxxxx/): > dial tcp xxx.xxx.xxx.xxx:xxxxx: operation was canceled v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (ws://xxx.xxxxx.com:xxxxx/): > dial tcp: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed`

我今天发现这个问题，以为连不上，就换了个端口。
另外，ws+tls 不行切换成 ws后，觉得速度还不错，就一直用 ws。

**Comment by yellowpuppy** [comment]
> 你是一直这样还是出问题的时候才这样？
> 我使用的ws+tls 用了CDN. 有时会这样，域名解析被封了。
> 
> 1. 我在caddy里加了好几个域名。在V2raynN里添加了对应的几套设置。出现问题的时候切换一下就好了。
>    https://zelikk.blogspot.com/2021/02/v2ray-path-domain-multi-user.html
> 2. 域名长时间被封的话，在cf上面加worker.
>    https://zelikk.blogspot.com/2021/05/domian-ban-websocket-tls-web-cdn-cloudclare-worker.html

其实也可以正常用，就是看到warning感觉很奇怪。
用cdn的确会这样，但是cdn很慢，后来我都不用cdn。关键是我现在没用cdn仅解析dns都会这样，就很奇怪了，而且出现了warning刷新一下网页也可以刷进去，我就感觉更奇怪了，这个是有一定概率的么
