### ISSUE TITLE
VPS正常，手机端能访问，一开始PC也能访问，突然不知什么原因PC不能访问

### ISSUE THREAD

**Issue by davidGooo** [233boy/v2ray#764]
延迟ping没问题，
TCP不通，换了两个IP也是一样的问题，怀疑和本地PC环境有关，但不知道具体问题出在哪里，

客户端错误日志如下：
2021/07/20 22:29:12 [Info] [340071866] v2ray.com/core/common/mux: failed to fetch all input > io: read/write on closed pipe
2021/07/20 22:29:31 [Info] [4014296864] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2021/07/20 22:29:31 [Info] [4014296864] v2ray.com/core/common/mux: failed to fetch all input > io: read/write on closed pipe
2021/07/20 22:30:47 [Info] [3055791642] v2ray.com/core/common/mux: failed to fetch all input > io: read/write on closed pipe
2021/07/20 22:30:47 [Info] [3055791642] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2021/07/20 22:32:34 [Info] [383551710] v2ray.com/core/proxy/socks: TCP Connect request to tcp:1535008-8.chat.api.drift.com:443

--
PS：本地PC挂的一个免费的梯子一直能用，自己最近搭的梯子突然不能用了，太打击人了，求指导

**Comment by crazypeace** [comment]
"手机端能访问，一开始PC也能访问，突然不知什么原因PC不能访问"
问题肯定出在“突然”上。
---
如果现在手机和PC都走同一个WIFI，手机行 PC不行，那肯定是PC上的设置。你想想“突然”改动过PC什么。如果是WS+TLS模式，看看是不是PC的DNS的问题，多换几个DNS试试。
如果现在手机走流量行 手机和PC走WIFI都不行，那估计是你的宽带“突然”改了什么。如果是WS+TLS模式，看看是不是域名被屏蔽了。
https://zelikk.blogspot.com/2021/05/domian-ban-websocket-tls-web-cdn-cloudclare-worker.html
---
多说一句，要证明你的VPS没问题，最直接的办法是让你的一个异地的朋友试一试，看能不能用。

**Comment by davidGooo** [comment]
我换成 WS也是一样的问题，一开始我认为是单独wifi和5G的差异，但手机用WIFI 和 5G都是可行的。所以排除 WIFI和5G的差异

另外我对PC的操作 ，家里有两台电脑，最近用的都是windows，MAC 只是在测试VPS连接过后面就没用过MAC电脑了。最近测试VPS，MAC和window电脑都出现同样的情况，所以我觉得可以排除单独PC的设置变化。
最近关于网络的变化有一点  家里联通网络换了套餐  ，刚好是在最近生效的，目前对这块网络变化的影响没有排查思路

**Comment by demodeom** [comment]
> 
> 
> 延迟ping没问题，
> TCP不通，换了两个IP也是一样的问题，怀疑和本地PC环境有关，但不知道具体问题出在哪里，
> 
> 客户端错误日志如下：
> 2021/07/20 22:29:12 [Info] [340071866] v2ray.com/core/common/mux: failed to fetch all input > io: read/write on closed pipe
> 2021/07/20 22:29:31 [Info] [4014296864] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
> 2021/07/20 22:29:31 [Info] [4014296864] v2ray.com/core/common/mux: failed to fetch all input > io: read/write on closed pipe
> 2021/07/20 22:30:47 [Info] [3055791642] v2ray.com/core/common/mux: failed to fetch all input > io: read/write on closed pipe
> 2021/07/20 22:30:47 [Info] [3055791642] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
> 2021/07/20 22:32:34 [Info] [383551710] v2ray.com/core/proxy/socks: TCP Connect request to tcp:1535008-8.chat.api.drift.com:443
> 
> --
> PS：本地PC挂的一个免费的梯子一直能用，自己最近搭的梯子突然不能用了，太打击人了，求指导

我也遇到了， 分享下解决方法：

方法1： 重启服务器，就是这么神器！！！ 问题解决了（可能服务器配置太低了）
方法2： PC客户端不要使用预览版， 建议使用稳定版， 卸载重装，下载并配置最新版的 v2ray-core
