### ISSUE TITLE
无论如何重启 用v2ray status 看状态都是未在运行

### ISSUE THREAD

**Issue by wubushanyan** [233boy/v2ray#767]
![img](https://z3.ax1x.com/2021/08/03/fiRdj1.jpg)

**Comment by crazypeace** [comment]
如果你以前曾经正常安装过，用以前的老版本。
https://zelikk.blogspot.com/2021/01/233v2ray-local.html
https://zelikk.blogspot.com/2021/08/233v2ray-github-commit.html

**Comment by wubushanyan** [comment]
> 如果你以前曾经正常安装过，用以前的老版本。
> https://zelikk.blogspot.com/2021/01/233v2ray-local.html
> https://zelikk.blogspot.com/2021/08/233v2ray-github-commit.html

安装了老版本后，查了下状态是正在运行了，但是测试速度时一直是0M了
请问咋办

**Comment by MMJ12345** [comment]
你的系统不是debian吧，大佬的这个脚本好像不太兼容其他的系统，你可以换成debain系统，80%的概率可以解决。
