### ISSUE TITLE
脚本偷跑流量

### ISSUE THREAD

**Issue by wclnqj** [233boy/v2ray#769]
![5](https://user-images.githubusercontent.com/66767220/128989112-f6fb1267-94f4-4e27-89ec-9e95e1354756.jpg)

我的4t流量被淦完了，一天时间
今天才发现

**Comment by wclnqj** [comment]
这个vps就单单安装了这个脚本，使用十天

**Comment by xiaohui24** [comment]
跟你一样的情况 我服务器设置流量异常邮件提醒 出现异常情况后 我直接把服务器停了

**Comment by yi250** [comment]
？？？卧槽该不会用来做跳板吧！

**Comment by Clownsw** [comment]
卧槽有点离谱

**Comment by ncwsszs** [comment]
那还是不用这个脚本了，毕竟不开源

**Comment by BestRicky** [comment]
+1，后来自建了，不知道为何

**Comment by BestRicky** [comment]
![image](https://user-images.githubusercontent.com/17917532/132093830-ad2d5bec-6f6f-4bfe-b145-cd8295ff5f46.png)
