### ISSUE TITLE
 command not found

### ISSUE THREAD

**Issue by aiden2017** [233boy/v2ray#77]
提问之前，请先查阅：[V2Ray 一键安装脚本疑问集合](https://v2ray66.com/post/10/)

若需要发起提问，请删除这些内容

[root@instance-1 google]# v2ray
bash: v2ray: command not found

不知道是什么情况

**Comment by love3kkk** [comment]
如果提示 curl: command not found ，那是因为你的 VPS 没装 Curl
ubuntu/debian 系统安装 Curl 方法: apt-get update -y && apt-get install curl -y
centos 系统安装 Curl 方法: yum update -y && yum install curl -y
安装好 curl 之后就能安装脚本了
