### ISSUE TITLE
dns 报错。 请问这个有问题吗？ 我正常使用没问题。但是tg用socket就不行！

### ISSUE THREAD

**Issue by HBat11233** [233boy/v2ray#771]
2021/08/30 12:19:59 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/30 12:19:59 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/30 12:19:59 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/30 12:34:09 [Error] app/dns: failed to retrieve response > context canceled
2021/08/30 12:34:09 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/30 12:38:16 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/30 13:43:13 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/30 13:43:13 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled

**Comment by HBat11233** [comment]
如果开着代理，再用tg上socket也可以。，单独用tg上socket就不行

**Comment by sinduanan** [comment]
同样报这个错

**Comment by HBat11233** [comment]
前段时间重装了一下服务器，只有我一个人用，现在没问题了。orz

**Comment by BigKunLun** [comment]
有进展吗，最近也遇到这个问题了

**Comment by linwin1995** [comment]
没有


| |
江健伟
|
|
***@***.***
|
签名由网易邮箱大师定制
在2022年3月13日 ***@***.***> 写道：

有进展吗，最近也遇到这个问题了
