### ISSUE TITLE
这个怎么解决？

### ISSUE THREAD

**Issue by houmy001** [233boy/v2ray#772]
[root@172 ~]# v2ray
V2Ray 4.36.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16 linux/amd64)
A unified platform for anti-censorship.
2021/09/03 22:14:38 Using config from STDIN
2021/09/03 22:14:38 [Info] github.com/v2fly/v2ray-core/v4/main/jsonem: Reading config: stdin:

**Comment by crazypeace** [comment]
你这是在直接运行v2ray。它告诉你需要提供config参数。 如果你真想这么干，请看v2ray的文档。
我猜这并非你本意。所以请说明你想干什么。
