### ISSUE TITLE
v2ray和caddy服务都在运行中 但是没有安装nginx服务

### ISSUE THREAD

**Issue by 95359646** [233boy/v2ray#773]
我用的是安装选项4 ：ws + tls
服务都启动运行中 但是nginx服务和https证书啥都没有安装呢
请问这是什么原因呢？
我的服务器不是x86_64的，是aarch架构的，这个应该没有关系吧？安装过程都正常，没有报错。

[root@ip-172-31-33-208 ~]# v2ray status

 V2Ray 状态: 正在运行  /  Caddy 状态: 正在运行

[root@ip-172-31-33-208 ~]# netstat -lntp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      920/master          
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      516/rpcbind         
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1096/sshd           
tcp6       0      0 :::443                  :::*                    LISTEN      1421/caddy          
tcp6       0      0 :::65287                :::*                    LISTEN      1456/v2ray          
tcp6       0      0 :::111                  :::*                    LISTEN      516/rpcbind         
tcp6       0      0 :::80                   :::*                    LISTEN      1421/caddy          
tcp6       0      0 :::22                   :::*                    LISTEN      1096/sshd           
[root@ip-172-31-33-208 ~]# curl localhost
404 Site localhost is not served on this interface
[root@ip-172-31-33-208 ~]# curl localhost:443
Client sent an HTTP request to an HTTPS server.
[root@ip-172-31-33-208 ~]# ps -ef | grep nginx
root      1897  1191  0 07:36 pts/0    00:00:00 grep --color=auto nginx
[root@ip-172-31-33-208 ~]#

**Comment by crazypeace** [comment]
caddy 就是用来搞定网页服务和https证书的。
