### ISSUE TITLE
安装后默认是ipv6，怎么改成ip4 ?

### ISSUE THREAD

**Issue by lxsgbin** [233boy/v2ray#774]
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:ssh             0.0.0.0:*               LISTEN      798/sshd
tcp6       0      0 [::]:ssh                [::]:*                  LISTEN      798/sshd
tcp6       0      0 [::]:32798              [::]:*                  LISTEN      5939/v2ray

**Comment by shescat** [comment]
同问。。。

**Comment by shescat** [comment]
https://debian.cn/articles/531?www
参考一下这个
