### ISSUE TITLE
服务器端运行失败？一直显示未在运行

### ISSUE THREAD

**Issue by ShiJinBuShi** [233boy/v2ray#775]
![image](https://user-images.githubusercontent.com/77663525/134803741-5087c70a-b9ee-4f9c-95da-016fdbcd7473.png)

**Comment by ShiJinBuShi** [comment]
重启也不得行

**Comment by crazypeace** [comment]
要么换个脚本，要么试试老一点的版本。
https://github.com/crazypeace/v2ray

**Comment by Vivhchj** [comment]
同问，楼主解决了吗

**Comment by wonderhong** [comment]
我也是这个问题，运行不了，请问楼主解决了吗

**Comment by Vivhchj** [comment]
换一下服务器的v2ray端口试试，就是“修改v2ray配置”里的“修改v2ray端口”选项

**Comment by crazypeace** [comment]
看看错误日志
/var/log/v2ray/error.log

**Comment by wonderhong** [comment]
> 

启动不了，也就没有日志

**Comment by crazypeace** [comment]
看看这两个系统服务的状态，里面会有一点日志的。
service v2ray status
service caddy status
========
你还可以命令行直接跑/usr/bin/v2ray/v2ray 看看是什么结果。
