### ISSUE TITLE
完全按照Wiki里的安装，运行正常，ping域名正常，打不开油管。。。。

### ISSUE THREAD

**Issue by YinXueFeng** [233boy/v2ray#776]
2021/09/29 04:12:34 125.120.227.122:0 rejected  common/drain: common/drain: unable to drain connection > read tcp 127.0.0.1:31895->127.0.0.1:36790: i/o timeout > proxy/vmess/encoding: invalid user > proxy/vmess: Not Found
2021/09/29 04:12:55 125.120.227.122:0 rejected  common/drain: common/drain: drained connection > proxy/vmess/encoding: invalid user > proxy/vmess: Not Found
2021/09/29 04:12:57 125.120.227.122:0 rejected  common/drain: common/drain: drained connection > proxy/vmess/encoding: invalid user > proxy/vmess: Not Found
2021/09/29 04:13:09 125.120.227.122:0 rejected  common/drain: common/drain: drained connection > proxy/vmess/encoding: invalid user > proxy/vmess: Not Found
2021/09/29 04:13:11 125.120.227.122:0 rejected  common/drain: common/drain: drained connection > proxy/vmess/encoding: invalid user > proxy/vmess: Not Found
2021/09/29 04:13:20 125.120.227.122:0 rejected  common/drain: common/drain: drained connection > proxy/vmess/encoding: invalid user > proxy/vmess: Not Found
2021/09/29 04:13:21 125.120.227.122:0 rejected  common/drain: common/drain: drained connection > proxy/vmess/encoding: invalid user > proxy/vmess: Not Found
2021/09/29 04:13:32 125.120.227.122:0 rejected  common/drain: common/drain: drained connection > proxy/vmess/encoding: invalid user > proxy/vmess: Not Found
2021/09/29 04:13:34 125.120.227.122:0 rejected  common/drain: common/drain: drained connection > proxy/vmess/encoding: invalid user > proxy/vmess: Not Found
2021/09/29 04:14:10 125.120.227.122:0 rejected  common/drain: common/drain: unable to drain connection > websocket: close 1000 (normal) > proxy/vmess/encoding: invalid user > proxy/vmess: Not Found

这种是什么情况，有大佬知道吗？谢谢

**Comment by crazypeace** [comment]
我猜，你可能需要，检查一下你自己和服务器的系统时间，检查一下UUID

**Comment by fzj1365974754** [comment]
请问解决了吗我也有这么问题

**Comment by YinXueFeng** [comment]
> 请问解决了吗我也有这么问题

我重启了服务器，并安装了旧的版本，问题原因是caddy出了问题

**Comment by huweikkk** [comment]
云主机需要同步网络时间，如果时间相差太大就会这样
