### ISSUE TITLE
使用v2ray就会报错

### ISSUE THREAD

**Issue by LookStars** [233boy/v2ray#778]
我是个新手,我不知道是不是我的问题，但是我在确保没有其他问题的时候我的v2ray错误日志却在我每次使用v2ray的时候报错，虽然这不影响我的使用，但是这个报错是不是别有含义呢?
![image](https://user-images.githubusercontent.com/79433682/137603627-0f68e022-468b-4e9b-b0b3-59eab9938fe4.png)

**Comment by fzj1365974754** [comment]
我也有这个问题

**Comment by crazypeace** [comment]
不影响使用就先不管。
你会编辑config.json的话，把1.1.1.1那一行删了就行了。

**Comment by LookStars** [comment]
> 不影响使用就先不管。 你会编辑config.json的话，把1.1.1.1那一行行了就行了。

谢谢
