### ISSUE TITLE
更新脚本后，使用tcp协议无法连接，换mkcp没问题

### ISSUE THREAD

**Issue by HonJoe** [233boy/v2ray#783]
版本4.43
错误日志只看到
[Error] app/dns: failed to retrieve response > Post "https://1.1.1.1/dns-query": context canceled

**Comment by zxa971201** [comment]
同问，谢谢！

**Comment by fzj1365974754** [comment]
同问，谢谢！

**Comment by L947** [comment]
同问，谢谢！

**Comment by wangyanjun56** [comment]
谢谢你解决了我的问题

**Comment by eternalpal** [comment]
谢谢这个好用。之前我用了官方的脚本，客户端一直都不能访问外网。后面使用了旧版本
https://github.com/crazypeace/v2ray
之后，使用tcp协议pc可以正常使用，安卓手机一连接就断线，断线了之后电脑也连接不上了，但是一段时间又会恢复。不知道为什么。
后面更改了mkcp协议后，目前就没啥问题了。
