### ISSUE TITLE
报错 proxy/vmess/encoding: Critical Warning: potentially invalid user: *********

### ISSUE THREAD

**Issue by sinduanan** [233boy/v2ray#785]
服务器更新了v2ray版本 v4.43.0   升级了管理脚本到 v3.45  
使用的时候有时候就会报错，然后链接上就连不上了，报错如下：
[Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
[Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
[Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
[Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
****************
****************
****************
[Warning] V2Ray 4.43.0 started
[Warning] 
	proxy/vmess/encoding: 
		Critical Warning: potentially invalid user: 
			a non VMessAEAD connection is received. From 2022 Jan 1st, 
			this kind of connection will be rejected by default. 
			You should update or replace your client software now. 
			This message will not be shown for further violation on this inbound.

-------------------------------------------------------------------------------------------
请问我该怎么解决呢      刚开始用着能用    再继续用就不行      更新v2ray时候提示我用同版本的客户端程序，找了好久也没找到v4.43.0的版本。。。   小白求帮助

**Comment by HonJoe** [comment]
换kcp协议
