### ISSUE TITLE
求助！！搬瓦工安装脚本后，无法代理访问Instagram

### ISSUE THREAD

**Issue by samsun277** [233boy/v2ray#787]
网站提示“错误，稍等几分钟再试”，其他网站没有这个问题；应该是被ins的反爬策略认定为机器人，将vps的ip拉黑了。原始请求就是浏览器发起的。
V2Ray 管理脚本版本: v3.45
V2Ray 版本: v4.42.2
想请教有没有什么配置或者其他方法解决这个问题，感谢！！

**Comment by alexli0707** [comment]
是的,我也遇到同样的问题.
