### ISSUE TITLE
iOS Twitter客户端看不了别人主页，提示“用户不存在”或“Something went wrong”

### ISSUE THREAD

**Issue by ChanceFeng** [233boy/v2ray#788]
iOS Twitter客户端看不了别人主页，提示“用户不存在”或“Something went wrong”

美国AWS节点，用shadowrocket，iOS Twitter客户端看任何人的主页都报错“Something went wrong”。在iOS上用Safari或Chrome正常。
尝试在shadowrocket-配置-编辑配置-通用中增加DNS 8.8.8.8问题依旧。求助大家有没有类似情况？
![I can't see anyone‘s page](https://user-images.githubusercontent.com/46808630/141434164-cab8efac-90f5-46f6-9224-6c1c3bad653d.PNG)

**Comment by Ryan817** [comment]
完全一样的问题，不知道咋搞，求解

**Comment by yang12me** [comment]
需要在AWS VPS上设置分流 或者试试WARP

**Comment by gumin163** [comment]
完全一样的问题。有解决办法吗？

**Comment by yang12me** [comment]
> 完全一样的问题。有解决办法吗？

需要设置分流，把推特流量分流到能正常访问推特的节点。

**Comment by yang12me** [comment]
可以安装WARP，设置转发。把推特流量转发到WARP

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: gumin163 ***@***.***>
发送时间: Monday, January 17, 2022 7:14:57 PM
收件人: 233boy/v2ray ***@***.***>
抄送: yang12me ***@***.***>; Comment ***@***.***>
主题: Re: [233boy/v2ray] iOS Twitter客户端看不了别人主页，提示“用户不存在”或“Something went wrong” (Issue #788)


完全一样的问题。有解决办法吗？

―
Reply to this email directly, view it on GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2F233boy%2Fv2ray%2Fissues%2F788%23issuecomment-1014406116&data=04%7C01%7C%7C021de1137b3848eb3fad08d9d9aa9923%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637780149018757560%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=iKIjEmtzxm4970kjY9%2BKiWqKcQqbenPp5yHK2MwBJpo%3D&reserved=0>, or unsubscribe<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAELCK5UOUDBYQT65VFWQTMLUWP23DANCNFSM5H4INWUA&data=04%7C01%7C%7C021de1137b3848eb3fad08d9d9aa9923%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637780149018757560%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=WWUgfv9xCozf5HRtzGwl4Ikys4av6doYpf3SJ7EVPKo%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C021de1137b3848eb3fad08d9d9aa9923%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637780149018757560%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=DaY9SzeHWogso%2BMk%2Ba54FxbUBwkR%2BIVYIcO3rikPRSk%3D&reserved=0> or Android<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C021de1137b3848eb3fad08d9d9aa9923%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637780149018757560%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2FJZGthX7YUhOHc%2FXSddX9dvA5sWxToF4hSh5WJobrWs%3D&reserved=0>.
