### ISSUE TITLE
域名认证错误，请问怎么解决？

### ISSUE THREAD

**Issue by edica02** [233boy/v2ray#790]
[Tue Nov 16 09:05:09 CST 2021] drivecheche.tk:Verify error:Fetching http://drivecheche.tk/.well-known/acme-challenge/_ir1lCpQy8HqOKIcSKt7Gb_7TTmnajPm8nx4HLcqLKY: Error getting validation data
[Tue Nov 16 09:05:10 CST 2021] Please add '--debug' or '--log' to check more details.
[Tue Nov 16 09:05:10 CST 2021] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Tue Nov 16 09:05:10 CST 2021] Run post hook:'systemctl restart nginx'

**Comment by crazypeace** [comment]
你这个问题应该找nginx相关去问。
