### ISSUE TITLE
未知错误，能连接但不能用

### ISSUE THREAD

**Issue by Mr-Rabbit99** [233boy/v2ray#792]
自11月11号起，突然无法访问外网，YouTube主界面显示未联网（不是浏览器的无法访问界面），每次打开代理第一次测速显示正常,tcp延迟120ms，但随后第二次测试为0.0M/s。重新选择服务器使用脚本搭建后仍不能使用，连接失败。用的是vultr美国机房，新加坡也试了。

**Comment by drc5521** [comment]
换其他一键脚本可以使用，这个脚本应该是有问题了。

**Comment by xiaojz1998** [comment]
> 换其他一键脚本可以使用，这个脚本应该是有问题了。
能否推荐一个？谢谢了？

**Comment by xiaojz1998** [comment]
> 换其他一键脚本可以使用，这个脚本应该是有问题了。

能否推荐一个？谢谢了？

**Comment by drc5521** [comment]
> > 换其他一键脚本可以使用，这个脚本应该是有问题了。
> 
> 能否推荐一个？谢谢了？

试试这个[https://github.com/mack-a/v2ray-agent](https://github.com/mack-a/v2ray-agent)

**Comment by lulu123ningmeng** [comment]
dddd
