### ISSUE TITLE
一句话安装V2ray后，服务进程未运行

### ISSUE THREAD

**Issue by lxsgbin** [233boy/v2ray#795]
这是一句话脚本
`bash <(curl -s -L https://git.io/v2ray.sh)` 

查看服务状态
`[root@qyi-5c73808390a30 ~]# systemctl status v2ray
● v2ray.service - V2Ray Service
   Loaded: loaded (/usr/lib/systemd/system/v2ray.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Mon 2021-11-29 22:44:30 CST; 2min 36s ago
     Docs: https://www.v2ray.com/
           https://www.v2fly.org/
  Process: 19790 ExecStart=/usr/bin/v2ray/v2ray -config /etc/v2ray/config.json (code=exited, status=218/CAPABILITIES)
 Main PID: 19790 (code=exited, status=218/CAPABILITIES)

Nov 29 22:44:29 qyi-5c73808390a30 systemd[1]: Unit v2ray.service entered failed state.
Nov 29 22:44:29 qyi-5c73808390a30 systemd[1]: v2ray.service failed.
Nov 29 22:44:30 qyi-5c73808390a30 systemd[1]: v2ray.service holdoff time over, scheduling restart.
Nov 29 22:44:30 qyi-5c73808390a30 systemd[1]: Stopped V2Ray Service.
Nov 29 22:44:30 qyi-5c73808390a30 systemd[1]: start request repeated too quickly for v2ray.service
Nov 29 22:44:30 qyi-5c73808390a30 systemd[1]: Failed to start V2Ray Service.
Nov 29 22:44:30 qyi-5c73808390a30 systemd[1]: Unit v2ray.service entered failed state.
Nov 29 22:44:30 qyi-5c73808390a30 systemd[1]: v2ray.service failed.`

**Comment by crazypeace** [comment]
参考一下https://github.com/v2ray/v2ray-core/issues/2720试试？
