### ISSUE TITLE
使用v2ray可以在连接wifi情况下翻墙，但是校园网宽带拨号再次使用v2ray只能访问墙内网站，墙外无法访问，这是什么情况？

### ISSUE THREAD

**Issue by 2306681547** [233boy/v2ray#796]

**Comment by 2306681547** [comment]
用的是拨号上网，而V2ray貌似不适配这种上网方式的，所以有疑问有方法适配这种拨号方式的连网来用v2ray翻墙吗

**Comment by Loss-of-time** [comment]
同样

**Comment by Huaxidesu** [comment]
> 用的是拨号上网，而V2ray貌似不适配这种上网方式的，所以有疑问有方法适配这种拨号方式的连网来用v2ray翻墙吗

windows - internet选项，选中拨号的网，打开PAC，填你的pac地址，当然底下的代理地址也可以，取决于你用啥模式
