### ISSUE TITLE
V2Ray 状态: 未在运行

### ISSUE THREAD

**Issue by wonderhong** [233boy/v2ray#797]
v2ray start运行后显示V2Ray 已启动，再运行v2ray status命令却说V2Ray 状态: 未在运行。4.27版本也试过了，不行。手动运行/usr/bin/v2ray/v2ray -config /etc/v2ray/config.json倒是可行，CTRL+C结束， 再 v2ray start / v2ray restart 都不可以

**Comment by Vivhchj** [comment]
换一下服务器的v2ray端口试试，就是“修改v2ray配置”里的“修改v2ray端口”选项

**Comment by wonderhong** [comment]
> 换一下服务器的v2ray端口试试，就是“修改v2ray配置”里的“修改v2ray端口”选项

还是不行

**Comment by wanqiuya** [comment]
我也遇到了同样情况
![Uploading Screenshot_2021-12-08-09-14-15-957_com.sonelli.juicessh.jpg.png…]()

**Comment by crazypeace** [comment]
手动运行/usr/bin/v2ray/v2ray -config /etc/v2ray/config.json
使用正常吗？
如果是，那就是v2ray.service的配置有问题。
参考一下 https://github.com/v2ray/v2ray-core/issues/2720
