### ISSUE TITLE
安装Shadowsocks时，加密协议只有gcm选项

### ISSUE THREAD

**Issue by freyzer** [233boy/v2ray#798]
最新脚本安装时，配置 Shadowsocks 只有GCM选项，求处理方式：
请选择 Shadowsocks 加密协议 [1-3]

 1. aes-128-gcm

 2. aes-256-gcm

 3. chacha20-ietf-poly1305

**Comment by song19871207** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
