### ISSUE TITLE
安装脚本有一个地方疏漏

### ISSUE THREAD

**Issue by DwightSir** [233boy/v2ray#8]
今天安装测试时发现没有检查curl依赖
而Curl在WS+TLS安装时需要
所以希望添加上使脚本变得更完美
也省去了小萌新的时间减少不必要的麻烦

**Comment by 233boy** [comment]
@DwightSir 
你是说执行这条安装命令的时候没检查 curl 依赖？
```
bash <(curl -s -L https://233blog.com/v2ray.sh)
```
