### ISSUE TITLE
拆掉独立显卡后v2ray连上但是打不开网页

### ISSUE THREAD

**Issue by yangkang5303** [233boy/v2ray#80]
cpu有intel hd4000核显，独立显卡nVidia 1070，最近拆掉1070后，用独显工作。
 v2ray连的上，但是chrome无法打开墙外网站，装上1070后问题恢复。
请问这是为啥
ps：使用v2raypro.top的傻瓜式客户端。

**Comment by 70akaline** [comment]
那一定是因为v2ray内置挖矿了呀(便乘

**Comment by nicholascw** [comment]
寄一张1070让我们复现一下？

**Comment by wysnxzm** [comment]
至少从字面上看,这是个傻瓜问题
