### ISSUE TITLE
国内服务器无法正常安装

### ISSUE THREAD

**Issue by NovaShen0724** [233boy/v2ray#801]
国内的服务器，脚本是我本地下载后上传到服务器的，不过github不通，改hosts后能ping通但是git clone的时候依然是不行，或者说，脚本执行到克隆仓库的时候就会报错，能不能把脚本换个镜像源呢?或者有什么其他的好的解决办法

**Comment by crazypeace** [comment]
可以把233脚本和v2ray都下载好，上传到你的服务器。参考：
https://zelikk.blogspot.com/2021/03/233-v2ray-download-local-install.html
