### ISSUE TITLE
自建v2ray连接不稳定

### ISSUE THREAD

**Issue by 864016954** [233boy/v2ray#802]
购买的vps搭建v2ray连接不稳定有时候无法访问网站

**Comment by shenyuhang555** [comment]
具体细节?

**Comment by jungege-Arny** [comment]
我也是无法访问网络，搭建都搭建都是正确的，就是用不了，前几天我自己搭建的都能用，就这一两天搭建的用不了

**Comment by jungege-Arny** [comment]
我也是无法访问网络，搭建都搭建都是正确的，就是用不了，前几天我自己搭建的都能用，就这一两天搭建的用不了

**Comment by crazypeace** [comment]
可能是脚本和最新的v2ray不兼容。试试旧版本。
https://github.com/crazypeace/v2ray
