### ISSUE TITLE
v2ray

### ISSUE THREAD

**Issue by jungege-Arny** [233boy/v2ray#803]
第一种协议 或者第4种协议 
VPS安装成功了，都无法翻墙
v2rayN 测试服务器速度显示为 0 M/s
测试ping 是能ping出来的
就是使用不了，我前几天也是这样搭建的，都能使用，以前搭建的能用，现在搭建的用不了。
请大佬修复一下，如果是我安装错误的话，我之前搭建的都能使用，按照这样的安装方法，同样的配置和网络，都反复检查了，就是这两天安装脚本安装成功了，翻墙不了，也使用不了。
希望大佬修复一下吧

**Comment by crazypeace** [comment]
如果是怀疑自己操作了服务器什么地方导致的问题，可以重装服务器的系统的。
如果是干净的系统，跑脚本结果不对，有可能是v2ray更新了什么地方，和脚本不兼容了。可以考虑使用旧一点版本的v2ray
https://zelikk.blogspot.com/2021/01/233v2ray-local.html

如果你反正是用 4. WebSocket + TLS 那也可以试试这个旧版本的脚本+旧版本的v2ray
https://github.com/crazypeace/v2ray

**Comment by jungege-Arny** [comment]
好的，谢谢

crazypeace ***@***.***> 于2021年12月28日周二 23:11写道：
