### ISSUE TITLE
就你这个认知能力 还翻墙 轮子都有人洗这你不是蠢就是跟他们一伙的> > > > 轮x子是什么东西。

### ISSUE THREAD

**Issue by HOMHOG** [233boy/v2ray#808]
> > > > 轮x子是什么东西。
> > > 
> > > 
> > > 法轮功，一个害人的邪教，因为教唆人有病不去医院治（这算是最轻的罪过了），自sha，sha人等，被赶出了大陆，但是在国外依然很盛行。轮子背后有美国政府的资助
> > 
> > 
> > 真的是章口就来哈哈哈哈，NT还是不要出墙了，没有半点思考能力。法轮功是法轮功，美国政府是美国政府，你说人家资助，证据呢？就因为你不喜欢美国？哈哈哈哈
> 
> https://falunaz.net/zh-hans/%e7%be%8e%e5%9b%bd%e5%9b%bd%e4%bc%9a%e8%b5%a0%e6%97%97%e8%a1%a8%e5%bd%b0%e6%b3%95%e8%bd%ae%e5%a4%a7%e6%b3%95%e5%88%9b%e5%a7%8b%e4%ba%ba%e6%9d%8e%e6%b4%aa%e5%bf%97%e5%85%88%e7%94%9f/ https://falunaz.net/zh-hans/%e6%b3%95%e8%bd%ae%e5%8a%9f%e5%8f%8d%e8%bf%ab%e5%ae%b321%e5%91%a8%e5%b9%b4/ 反正翻出去这么久我倒是没见过美国国会和国务院对哪个宗教团体这么关心，如果有，请给我拿出证据。法轮功的宣传很多都是引用自美国之声，美国之声什么媒体大家都清楚。你引用任何美国其他主流媒体政治倾向都没这个明显 另外，张口就骂别人NT，您这种素质有脸说别人吗。看看多少人踩你

声援

_Originally posted by @HOMHOG in https://github.com/233boy/v2ray/issues/190#issuecomment-1002848287_

**Comment by youchen-0** [comment]
那个人github里除了folk了一份和翻墙有关的存储库啥也没有,而且几乎没做过更改,基本看不出来有会动脑子的迹象
可能他觉得github就是讨论这些话题的吧,
