### ISSUE TITLE
TCP协议，同样的网络环境同样的账号，PC端用V2rayN可以使用，iphone用小火箭可以正常连接，但油管谷歌都连不上

### ISSUE THREAD

**Issue by ewanbandit** [233boy/v2ray#809]

**Comment by ewanbandit** [comment]
小火箭是最新版本，换了同一个服务器的ssr账号，可以使用，v2ray依然不能用

**Comment by crazypeace** [comment]
手机shadowrocket开全局能上油管谷歌吗？
手机用流量不用wifi能上油管谷歌吗？

手机有工具的话ping一下油管谷歌，或者wifi路由器DNS改一下 1.1.1.1 8.8.8.8 有效果吗？

**Comment by ljr1626** [comment]
> 小火箭是最新版本，换了同一个服务器的ssr账号，可以使用，v2ray依然不能用

请问最后是如何解决的，我也出现这样的问题，pc 上同样的配置可以用，iOS 部分 App 可以通，浏览器不能通
