### ISSUE TITLE
服务端和客户端版本不一致无法正常链接

### ISSUE THREAD

**Issue by tianhe0312** [233boy/v2ray#810]
服务端使用的一键脚本在搬瓦工搭建的，服务端  V2Ray 版本: v4.44.0  客户端，使用实在AX86的科学插件上V2Ray版本：v4.22.1 现在客户端是无法更新的，提示最新V2Ray版本，手机单独使用客户端没有问题，今天突然用不了了，查询是端口被封了，我单独换了个端口还不行，手机测试也不行，就重新卸载安装了，然后手机好了，路由器挂不起，目前先用的SS协议，但是不安全，之前就是这样被封的，麻烦问下有没有解决办法。

**Comment by crazypeace** [comment]
服务器端安装旧的v2ray版本的方法：
https://zelikk.blogspot.com/2021/01/233v2ray-local.html
