### ISSUE TITLE
读取响应头失败

### ISSUE THREAD

**Issue by x2z2x2x2** [233boy/v2ray#811]
failed to read response header > websocket: close 1000 (normal)
之前一直好好的，几年1月突然这样了，有没有大佬遇到同样情况的，改系统时间似乎不管用

**Comment by jackyzonewen** [comment]
同样的问题

**Comment by songge8** [comment]
这个不是读取响应头失败，是安全机制更新造成的，说明如下
VMess MD5 认证信息 淘汰机制

VMessAEAD 协议已经经过同行评议并已经整合了相应的修改。 VMess MD5 认证信息 的淘汰机制已经启动。

自 2022 年 1 月 1 日起，服务器端将默认禁用对于 MD5 认证信息 的兼容。任何使用 MD5 认证信息的客户端将无法连接到禁用 VMess MD5 认证信息的服务器端。

在服务器端可以通过设置环境变量 v2ray.vmess.aead.forced = true 以关闭对于 MD5 认证信息的兼容。 或者 v2ray.vmess.aead.forced = false 以强制开启对于 MD5 认证信息 认证机制的兼容 （不受到 2022 年自动禁用机制的影响） 。 (v4.35.0+)

**Comment by x2z2x2x2** [comment]
> 这个不是读取响应头失败，是安全机制更新造成的，说明如下
> 
> VMess MD5 认证信息 淘汰机制
> 
> VMessAEAD 协议已经经过同行评议并已经整合了相应的修改。 VMess MD5 认证信息 的淘汰机制已经启动。
> 
> 自 2022 年 1 月 1 日起，服务器端将默认禁用对于 MD5 认证信息 的兼容。任何使用 MD5 认证信息的客户端将无法连接到禁用 VMess MD5 认证信息的服务器端。
> 
> 在服务器端可以通过设置环境变量 v2ray.vmess.aead.forced = true 以关闭对于 MD5 认证信息的兼容。 或者 v2ray.vmess.aead.forced = false 以强制开启对于 MD5 认证信息 认证机制的兼容 （不受到 2022 年自动禁用机制的影响） 。 (v4.35.0+)
> 
> 应对方法是将服务端和客户端的AlterID改为0，但是作者这个好像不支持配置，只能通过手工修改配置文件来实现

谢谢，解决了。而且这个方法得注意得把v2ray版本更新到4.28以上

**Comment by x2z2x2x2** [comment]
> 同样的问题

下面有人发了解决办法，设置AID=0
