### ISSUE TITLE
求解域名绑定

### ISSUE THREAD

**Issue by umikingso** [233boy/v2ray#815]
事情是这样，在公司电信网套cf可以正常使用，但是因为地处西南山区移动的魔爪，cf基本断开连接，然后就用了另一家的cdn，cname解析过去，ip地址回vps上，但是caddy没绑定用不了，按说明在 /etc/caddy/sites新建一个Caddyfile，并且把cdn.域名.免费，按照 /etc/caddy/Caddyfile模仿着写上。重启服务初始的就打不开了。闪了追加文件就能打开。这种情况有办法么，屌大的帮个忙。。。

**Comment by crazypeace** [comment]
怀疑你的caddyfile格式有问题。你可以把你的caddyfile马赛克敏感信息后放出来。

如果你只是要增加域名，直接修改caddyfile 域名那一行，加几个域名就可以了。
https://zelikk.blogspot.com/2022/01/ws-tls-v2ray-caddy-multi-domain.html

**Comment by umikingso** [comment]
> 

刚又试了一下，可以了。谢谢 @crazypeace

**Comment by umikingso** [comment]
高兴早了
proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://cdn.kxxxx.gq/blog):  > remote error: tls: internal error] > common/retry: all retry attempts failed

**Comment by umikingso** [comment]
failed to handler mux client connection > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://kxxxx.gq/blog):  > dial tcp: lookup kingso.gq: no such host] > common/retry: all retry attempts failed

这个是直接改文件上加的，上一个是site文件夹里追加的报错。记录一下。后面再研究。。。。

**Comment by 233boy** [comment]
> failed to handler mux client connection > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://kxxxx.gq/blog): > dial tcp: lookup kingso.gq: no such host] > common/retry: all retry attempts failed
> 
> 这个是直接改文件上加的，上一个是site文件夹里追加的报错。记录一下。后面再研究。。。。



首先你要确保你的域名已经解析到 VPS 了，配置文件大概这样写
```
$domain {
    proxy /${path} 127.0.0.1:${v2ray_port} {
        without /${path}
        websocket
    }
}
```

**Comment by umikingso** [comment]
> > failed to handler mux client connection > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://kxxxx.gq/blog): > dial tcp: lookup kingso.gq: no such host] > common/retry: all retry attempts failed
> > 这个是直接改文件上加的，上一个是site文件夹里追加的报错。记录一下。后面再研究。。。。
> 
> 首先你要确保你的域名已经解析到 VPS 了，配置文件大概这样写
> 
> ```
> $domain {
>     proxy /${path} 127.0.0.1:${v2ray_port} {
>         without /${path}
>         websocket
>     }
> }
> ```

谢大佬，现在能连上了，我在客户端上把伪装域名的cdn字样删除了，配置文件恢复初始了。
猜测可能是这么个原因，因为我加的是二级域名，cdn.原域名.xx，初始改一次设置时候caddy自动申请了证书，然后我删除了配置以后，解析仍然可行，即二级到一级的默认网站。
然后代理的是基础域名，我删除伪装域名的cdn就成了的原理我没想清楚，可能和没有找到网站目录有关还是怎么得就不得而知了，现在能用了，先观察一下。

**Comment by umikingso** [comment]
1
