### ISSUE TITLE
很多人的服务器都有几个IP，但怎么设置多IP出口呢?

### ISSUE THREAD

**Issue by rianwg** [233boy/v2ray#817]
很多人的服务器都有几个IP，但怎么设置多IP出口呢?
服务器里有三个IP，现在只有一个IP出来，余下2个IP就浪费了...
希望能增加多IP出口，或者出多IP出口教程..

**Comment by crazypeace** [comment]
> 很多人的服务器都有几个IP，但怎么设置多IP出口呢?
> 服务器里有三个IP，现在只有一个IP出来，余下2个IP就浪费了...
> 希望能增加多IP出口，或者出多IP出口教程..

你是觉得多ip出口网速会变快吗？

**Comment by rianwg** [comment]
> > 很多人的服务器都有几个知识产权，但怎么设置多互联网协议(Internet Protocol)出口呢？服务器里有三个知识产权，现在只有一个互联网协议(Internet Protocol)出来,余下2个互联网协议(Internet Protocol)就浪费了...希望能增加多互联网协议(Internet Protocol)出口,或者出多互联网协议(Internet Protocol)出口教程..
> 
> 你是觉得多互联网协议（Internet Protocol的缩写）出口网速会变快吗？

不是多出口更快，是玩游戏或者刷刷网站之类的，很多时候要不同的用户用不同的IP..

**Comment by crazypeace** [comment]
> > > 很多人的服务器都有几个知识产权，但怎么设置多互联网协议(Internet Protocol)出口呢？服务器里有三个知识产权，现在只有一个互联网协议(Internet Protocol)出来,余下2个互联网协议(Internet Protocol)就浪费了...希望能增加多互联网协议(Internet Protocol)出口,或者出多互联网协议(Internet Protocol)出口教程..
> > 
> > 
> > 你是觉得多互联网协议（Internet Protocol的缩写）出口网速会变快吗？
> 
> 不是多出口更快，是玩游戏或者刷刷网站之类的，很多时候要不同的用户用不同的IP..

1. 可以配多个 inbound  （比如：端口12345是网页，端口23456是游戏）
2. 给不同的inbound，配不同的inboundTag （比如，web-tag, game-tag)
3. 在routing的rules里，判断inboundTag，打上不同的outboundTag (比如，net-1, net-2)
4. 在outbounds，给你的多个网卡分别 添加 outbound，使用 "sendThrough": "1.2.3.4", // 选择网口的IP地址
"tag": "net-1",
参考 https://www.v2fly.org/config/outbounds.html#outboundobject

举例
	"inbounds": [
		{
			"port": 12345,
			"tag": "web-tag"
		},
		{
			"port": 23456,
			"tag": "game-tag"
		}
	],
	"outbounds": [
		{
			"sendThrough": "1.2.3.4",	// 网口1
			"tag": "net1-tag"
		},
		{
			"sendThrough": "4.3.2.1",	// 网口2
			"tag": "net2-tag"
		}
	],
	"routing": {
		"rules": [
			{
				"inboundTag": ["web-tag"],
				"outboundTag": "net1-tag"
			},						
			{
				"inboundTag": ["game-tag"],
				"outboundTag": "net2-tag"
			}	
		]
	}
