### ISSUE TITLE
能救救吗？刚从ssr换到v2ray，根据教程操作搭好就是上不了网，日志全是direct

### ISSUE THREAD

**Issue by Cakeyan** [233boy/v2ray#821]
以下是日志：
2022/01/18 23:42:23 112.49.92.11:50844 accepted tcp:www.google.com:443 [direct] 
2022/01/18 23:42:30 112.49.92.11:50907 accepted tcp:mtalk.google.com:5228 [direct] 
2022/01/18 23:42:31 112.49.92.11:50917 accepted tcp:api.github.com:443 [direct] 
2022/01/18 23:42:32 112.49.92.11:50924 accepted tcp:www.google.com:443 [direct] 
2022/01/18 23:42:32 112.49.92.11:50923 accepted tcp:play.google.com:443 [direct] 
2022/01/18 23:42:32 112.49.92.11:50929 accepted tcp:www.google.com:443 [direct] 
2022/01/18 23:42:32 112.49.92.11:50931 accepted tcp:www.google.com:443 [direct]
全是direct感觉不太对把。这怎么解决呢

**Comment by Cakeyan** [comment]
已经开了全局了，换了好几个系统都用不了，旧版本也用不了

**Comment by crazypeace** [comment]
这个是你客户端的日志吧？
原因是你的客户端v2ray的路由配置让走direct。
找你用的什么客户端的帮助文档，看看路由配置那部分。或者换一个你能弄懂则么配置路由的客户端。

**Comment by learn-py-c** [comment]
我的服务端部署好之后无法生成url，不管使用什么命令都提示出错了，要重新安装软件

**Comment by crazypeace** [comment]
> 我的服务端部署好之后无法生成url，不管使用什么命令都提示出错了，要重新安装软件

233脚本的输出url不是从config文件转换的，是在安装工程中记录的设置，存到了一个备份文件里。我建议你要么用脚本在设置一下之后试试导出url，要么自己学会读懂config.json

**Comment by Clover177** [comment]
生成的URL 没办法在V2ray使用
已建立的连接被您的主机中的软件终止
是什么问题啊？

**Comment by crazypeace** [comment]
> 生成的URL 没办法在V2ray使用 已建立的连接被您的主机中的软件终止 是什么问题啊？

URL 不能用就自己一个一个填参数。那个URL在不同的翻墙客户端里是不一定通用的。
