### ISSUE TITLE
最新版本对挖矿有抽水，抽水26%。

### ISSUE THREAD

**Issue by autoing** [233boy/v2ray#824]
最新版本对挖矿有抽水，抽水26%。

**Comment by crazypeace** [comment]
show me the code.

**Comment by sinduanan** [comment]
怎么统计得

**Comment by AcosX** [comment]
真的假的？证据呢？

**Comment by cangbai12** [comment]
果真吗

**Comment by potato1992** [comment]
第一次用梯子？这脚本我用很多年了，人家就是个帮你部署v2ray服务端(v2ray也是开源的)的脚本，脚本源码也是清清楚楚的，就是个透明代理从不会去识别你走的是不是挖矿协议，怎么抽你水？人家作者连挖矿是啥回事都不一定明白。自己查网络稳定性吧，可能就是你的vps不行，多花点钱买CN2线路的vps吧。

**Comment by MoSplain** [comment]
傻口，黑人黑魔怔了

**Comment by Crisliu7** [comment]
应该是谷歌云的提醒，我的也是，说我在挖矿，强行给我suspend了

**Comment by kkkccz** [comment]
挖矿是真的。作者把挖矿程序藏在网站伪装里面了，网站伪装只要设置作者提供的伪装网站就会被挖矿。

**Comment by potato1992** [comment]
> 挖矿是真的。作者把挖矿程序藏在网站伪装里面了，网站伪装只要设置作者提供的伪装网站就会被挖矿。

代码片段证据呢？
1. 这是个代理软件，如果需要偷挖矿收益（也就是抽水），他必须识别拦截挖矿数据包流量，然后把数据包里面别人的地址换成自己的地址，你可以看能不能找到这样的代码。
2. 如果你的意思是这个代理程序本身会挖矿，那就更不可能了，他并没有附带任何挖矿的可执行程序或者是代码，我也没有见过我的vps CPU占用变高。

**Comment by kkkccz** [comment]
首先，作者以前就有以挖矿威胁收费10美元的先例：https://freefq.com/m/jq/2018/03/17/V2Ray.html。

作者自然不会把挖矿代码写脚本里。想开启挖矿可以试试开启Websocket+TLS，并且开启网站位置，使用程序默认的https://liyafly.com。反正这网站不是开源的，什么代码只有作者知道。

也可能你也试不出来，作者想改可以随时改。

**Comment by potato1992** [comment]
> 

这个显然不是233boy作者的网站，是一个freefq(免费翻墙网)这个网站的行为，与作者无关。比方说，文中称自己是小白:
···
此脚本是为了方便像我这种[小小白萌新]更加容易去使用 V2Ray，配置 V2Ray。希望对你有帮助 ^_^
···
freefq这种行为就是借用别人的脚本自己卖钱，网站还夹带私活挂自己筛选的新闻。
websocket的伪装网站随便设置啊，而且我刚试了一下，默认的也不是liyafly.com啊，而是`233blog.com`， 不知道你在哪里看到的教程写的是`liyafly`。脚本所有代码都是可以查看源码的，不存在挖矿行为的。

**Comment by kkkccz** [comment]
你是作者的托吗？还是是阅读理解能力不行？
![image](https://user-images.githubusercontent.com/32994981/178155116-92ca8058-f560-4e4f-b049-7bfa1d113bdc.png)

**Comment by kkkccz** [comment]
![image](https://user-images.githubusercontent.com/32994981/178155494-9b327afe-0c5a-4bba-93b4-a35138f06f24.png)

**Comment by potato1992** [comment]
> ![image](https://user-images.githubusercontent.com/32994981/178155494-9b327afe-0c5a-4bba-93b4-a35138f06f24.png)

这个确实是我看错了。
但是这个脚本仍然不可能挖矿。脚本就这么点代码，明明白白写的清清楚楚，代码就只是按照配置替换几个json模板文件里面的内容，然后调用的就是v2ray官方程序了，啥别的都没干。代理那一块，就算是`liyafly.com`，你看他代码，读取到liyafly.com存到$domain变量，也就是直接传到caddy配置文件里面去了(1224行caddy_config()->caddy-config.sh)，caddy-config.sh内部也就只是文本处理修改配置文件，他下载caddy的在`download-caddy.sh`第六行，也是官方的`https://caddyserver.com/download/linux/amd64?license=personal`。挖矿程序在哪下载的？基于web的挖矿的程序也是要代理给浏览器处理运算的，caddy/v2ray官方程序干不了这个。
他的paypal头像也说了没有挖矿，不要因为这个打钱。

**Comment by kkkccz** [comment]
"但是这个脚本仍然不可能挖矿。脚本就这么点代码，明明白白写的清清楚楚"
这话就骗骗小白吧，一个脚本可是会调用一堆其他东西。没人有空一行一行给你找证据。

**Comment by kkkccz** [comment]
用这个脚本的人可要注意了，最好时时刻刻查看自己CPU的使用率。如果空闲状态CPU使用率不是0%，就是有问题。

**Comment by potato1992** [comment]
> "但是这个脚本仍然不可能挖矿。脚本就这么点代码，明明白白写的清清楚楚" 这话就骗骗小白吧，一个脚本可是会调用一堆其他东西。没人有空一行一行给你找证据。

我已经追踪给你看了了他domain变量(就是你纠结的这个liyafly.com)去的位置，调用了啥东西了？就这么点代码一下子就看完了，如果你不会脚本可以请个人帮你检查。

**Comment by kkkccz** [comment]
谢谢，我是计算机科班出身。话说你们挖矿挖了多少钱？

**Comment by potato1992** [comment]
> 谢谢，我是计算机科班出身。话说你们挖矿挖了多少钱？

CPU矿也就XMR了吧，我刚算了一下，一个单核心vps，就算满载一个月不到0.2美元，这个脚本都不知道有没有500个人用，要有这么多人CPU满载issue早就炸毛了。
不相信这个脚本的话，把这个脚本生成的配置文件自己弄到v2ray配置目录里面去，自己独立运行v2ray。https代理用apache自己做也很简单的，我就是apache2自己做的https代理，他这个caddy我不喜欢就没用。
