### ISSUE TITLE
shadowsocks一用就会出现 failed to9 read IV > EOF

### ISSUE THREAD

**Issue by MarioXiang** [233boy/v2ray#827]
v2ray用这很正常，但脚本建的shadowsocks一用就会出现 failed to9 read IV > EOF这种该怎么解呢

**Comment by MarioXiang** [comment]
![image](https://user-images.githubusercontent.com/24436539/151655908-857dc8ae-1aba-4514-b188-47e2b6c7d8db.png)
log好像也是异常的 没有

**Comment by 233boy** [comment]
@MarioXiang 更新 SS 客户端版本看看
