### ISSUE TITLE
V2RAY Telegram MTProto 相关配置暂时不推荐使用 

### ISSUE THREAD

**Issue by iubucuoo** [233boy/v2ray#830]
我输入 v2ray tg 提示这个，现在是不能弄tg的么

**Comment by 233boy** [comment]
@wangshijun12 是的。

**Comment by wangshijun12** [comment]
> @wangshijun12 是的。

请教下，我最近用v2ray在PC上不能翻，手机上却可以，看日志报了警告。 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp xx.xx.xx.xx:xx: i/o timeout] > v2ray.com/core/common/retry: all retry attempts failed。能看出来什么原因么

**Comment by 233boy** [comment]
> > @wangshijun12 是的。
> 
> 请教下，我最近用v2ray在PC上不能翻，手机上却可以，看日志报了警告。 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp xx.xx.xx.xx:xx: i/o timeout] > v2ray.com/core/common/retry: all retry attempts failed。能看出来什么原因么

@wangshijun12 关了MUX 看看

**Comment by wangshijun12** [comment]
> > > @wangshijun12 是的。
> > 
> > 
> > 请教下，我最近用v2ray在PC上不能翻，手机上却可以，看日志报了警告。 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp xx.xx.xx.xx:xx: i/o timeout] > v2ray.com/core/common/retry: all retry attempts failed。能看出来什么原因么
> 
> @wangshijun12 关了MUX 看看

我之前改了端口后好了， 这个Telegram功能啥时候能开起来呢
