### ISSUE TITLE
同一个ip ws+tls 比mkcp慢很多，有大佬指点下应该怎么设置或者参考什么教程吗，萌新

### ISSUE THREAD

**Issue by onlyinheaven** [233boy/v2ray#832]

**Comment by 233boy** [comment]
@onlyinheaven ws+tls 比 mkcp 慢是正常的，你可以看看 vless+ws+tls，可能会好一些。但是非要对比速度的话，还是不如 mkcp 的

**Comment by onlyinheaven** [comment]
> @onlyinheaven ws+tls 比 mkcp 慢是正常的，你可以看看 vless+ws+tls，可能会好一些。但是非要对比速度的话，还是不如 mkcp 的

感谢回复啊，我现在就是用freenom申请了一个域名，设置DNS解析到vps的ip，然后用大佬的脚本ws+tls的选项搭起来的。试了下这种方式确实比mkcp不容易被封，就是原来mkcp可以youtube 720P的，ws+tls连基础240P都会卡，所以想知道是不是哪里没搞对或者少了什么步骤
