### ISSUE TITLE
脚本是不是自动滥发邮件啊，有没有xd遇到的

### ISSUE THREAD

**Issue by JellyTOP** [233boy/v2ray#836]
![image](https://user-images.githubusercontent.com/35587996/153760459-f6c37a1c-ca9d-48c3-b75b-c04cbc174c03.png)

**Comment by backuponeday** [comment]
脚本的问题？

**Comment by backuponeday** [comment]
暂时还没有遇到

**Comment by 233boy** [comment]
@JellyTOP 和脚本没有任何关系，你应该看看是不是你的代理被别人用了

**Comment by JellyTOP** [comment]
那就是我被其他人搞了？

**Comment by houmy001** [comment]
> 那就是我被其他人搞了？

瓦工？我也有这种情况，只要装宝塔，和v2ray，不管是233还是官方，就会被垃圾邮件暂停，只挂网站就没有事情，弄了很久，关25，删除邮件应用，关闭密码登录都没用

**Comment by JellyTOP** [comment]
> > 那就是我被其他人搞了？
> 
> 瓦工？我也有这种情况，只要装宝塔，和v2ray，不管是233还是官方，就会被垃圾邮件暂停，只挂网站就没有事情，弄了很久，关25，删除邮件应用，关闭密码登录都没用

找到解决方法了吗

**Comment by crazypeace** [comment]
> > 那就是我被其他人搞了？
> 
> 瓦工？我也有这种情况，只要装宝塔，和v2ray，不管是233还是官方，就会被垃圾邮件暂停，只挂网站就没有事情，弄了很久，关25，删除邮件应用，关闭密码登录都没用

如果不是破你的VPS，那就是你的v2ray inbound被扫到了。你查一下 v2ray 的access.log，是不是和你发邮件的记录吻合？

**Comment by xxx1989626** [comment]
你们解决问题了吗？我的好像是我电脑中毒了。我前年的时候只有我自己一个人用。一只出现这个问题。后来发现是魔兽地图里有一个病毒。然后我就再也没玩魔兽了。几年都没问题。我都忘记这事了。前几天朋友喊我玩魔兽。我又装了魔兽了。结果今天又出现了这个问题。但是现在是三个人在用。开始以为是别人的问题。我一只在排除。结果查到只要我电脑一连上v2ray。就会警告停机。我现在电脑都不敢连了。我的手机和另外两个人连上正常。没有警告停机。
