### ISSUE TITLE
克隆脚本仓库出错了

### ISSUE THREAD

**Issue by lsw0922** [233boy/v2ray#839]
Failed loading plugin "osmsplugin": No module named 'librepo'
CentOS Linux 8 - AppStream                          36  B/s |  38  B     00:01    
Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
Failed loading plugin "osmsplugin": No module named 'librepo'
CentOS Linux 8 - AppStream                          68  B/s |  38  B     00:00    
Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist

已将你的主机设置为Asia/Shanghai时区并通过systemd-timesyncd自动同步时间。

主机时间：
               Local time: Tue 2022-02-15 23:19:32 CST
                Time zone: Asia/Shanghai (CST, +0800)

/tmp ~
/dev/fd/63: line 805: git: command not found
~

 哎呀呀...克隆脚本仓库出错了...

 温馨提示..... 请尝试自行安装 Git: yum install -y git  之后再安装此脚本
[root@bp ~]# yum install -y git
Failed loading plugin "osmsplugin": No module named 'librepo'
CentOS Linux 8 - AppStream                          63  B/s |  38  B     00:00    
Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
[root@bp ~]#

**Comment by lsw0922** [comment]
和大家汇报一下，换了U系统才解决问题，之前CenOs8，换了几个脚本都是同样问题。不知道为什么

**Comment by crazypeace** [comment]
别用centos了，用Ubuntu20以上或者Debian10以上，好用得多。现在最便宜的VPS性能也上来了，不用扣扣索索地用centos了。

**Comment by banchihaishen** [comment]
谢谢我也遇到了同样的问题

**Comment by JY-jiuyi** [comment]
本来用的u 但是bbr安装失败看教程让换c 换完v2ray直接安装不了了

**Comment by crazypeace** [comment]
> 本来用的u 但是bbr安装失败看教程让换c 换完v2ray直接安装不了了

要看你用的哪个版本的 ubuntu 了.
旧版本的bbr不是自带的, 不好装.
新版本的ubuntu内核已经带了bbr, 只要打开几个设置项就行了.
