### ISSUE TITLE
未来是否会支持ipv6?

### ISSUE THREAD

**Issue by PhilCity** [233boy/v2ray#84]
很多vps换ipv6的ip很随意 而且有些vps商的ipv4路由惨不忍睹 ipv6会好点

**Comment by 233boy** [comment]
@PhilCity 
Github 不支持 V6 呀 😢

**Comment by PhilCity** [comment]
@233boy 不是脚本 是v2ray支持ipv6

**Comment by ytianhui** [comment]
很多便宜的小鸡是只有IPv6地址
