### ISSUE TITLE
A unified platform for anti-censorship.

### ISSUE THREAD

**Issue by zion-cn** [233boy/v2ray#841]
A unified platform for anti-censorship.
这个问题如何解决？

**Comment by spring59** [comment]
同求  最近出现这问题

**Comment by zion-cn** [comment]
邮件已收到！待查阅！   注：平安商圈的家人们注意了！如果邮件内容不符合要求，将延缓处理哦！

**Comment by borgiav** [comment]
`A unified platform for anti-censorship.
panic: infra/conf/serial: failed to read config file at line 17 char 9 > invalid character '}' looking for beginning of object key string
goroutine 1 [running]:
github.com/v2fly/v2ray-core/v4/common.Must(...)
        github.com/v2fly/v2ray-core/v4/common/common.go:27
github.com/v2fly/v2ray-core/v4/main/jsonem.init.0.func1({0xc87ea0, 0xc00000df08})
        github.com/v2fly/v2ray-core/v4/main/jsonem/jsonem.go:27 +0x32c
github.com/v2fly/v2ray-core/v4.LoadConfig({0xddb800, 0x4}, {0x7ffd40327f18, 0x0}, {0xc87ea0, 0xc00000df08})
        github.com/v2fly/v2ray-core/v4/config.go:68 +0x1fb
main.startV2Ray()
        github.com/v2fly/v2ray-core/v4/main/main.go:109 +0xe9
main.main()
        github.com/v2fly/v2ray-core/v4/main/main.go:138 +0x9f
v2ray.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
v2ray.service: Failed with result 'exit-code'.
v2ray.service: Service RestartSec=100ms expired, scheduling restart.
v2ray.service: Scheduled restart job, restart counter is at 1.`
相同的问题，以上是日志文件

**Comment by crazypeace** [comment]
> 
```
 failed to read config file at line 17 char 9 > invalid character '}'
```
config.json wrong.

**Comment by EurusX31** [comment]
請問這種如何解決？
可以檢測延遲，可以ping通，但是一旦要連接就會出現這樣的提示。

**Comment by zion-cn** [comment]
邮件已收到！待查阅！   注：平安商圈的家人们注意了！如果邮件内容不符合要求，将延缓处理哦！

**Comment by crazypeace** [comment]
> 請問這種如何解決？ 可以檢測延遲，可以ping通，但是一旦要連接就會出現這樣的提示。

第一次搭就有问题，推荐看
https://zelikk.blogspot.com/2022/04/setup-v2ray-websocket-tls-troubleshoot.html

别人能用，就你不能用。或者以前能用，现在突然不能用，推荐看
https://zelikk.blogspot.com/2022/04/connect-v2ray-websocket-tls-troubleshoot.html

**Comment by zion-cn** [comment]
邮件已收到！待查阅！   注：平安商圈的家人们注意了！如果邮件内容不符合要求，将延缓处理哦！
