### ISSUE TITLE
vultr的vps安装后还是被墙

### ISSUE THREAD

**Issue by Deus-Glen** [233boy/v2ray#843]
之前是可以的，最近换了好几个都不行，不知道是啥原因

**Comment by xietang** [comment]
俺也一样！

**Comment by hujesse83** [comment]
俺也一样

**Comment by crazypeace** [comment]
套CDN防墙啊。
https://zelikk.blogspot.com/2021/11/racknerd-vps-v2ray-1g-1t-12g-768mb-1088.html
