### ISSUE TITLE
关于VPS出现如下问题的解决方案   v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic

### ISSUE THREAD

**Issue by pureGavin** [233boy/v2ray#844]
https://github.com/2dust/v2rayN/issues/2051
在这个issue中已经给出了解决方案，我希望作者能在一键搭建脚本中加入这部分的命令，这样就不需要使用者手动输入了

**Comment by 206559** [comment]
怎么解决啊

**Comment by pureGavin** [comment]
> 怎么解决啊

我不是已经给出了链接了么……
