### ISSUE TITLE
dns报错

### ISSUE THREAD

**Issue by signiotg** [233boy/v2ray#845]
app/dns: failed to retrieve response > Post "https://8.8.8.8/dns-query": context canceled
NDS报错，v2ray显示接收到连接，但是谷歌就是打不开求解决

**Comment by crazypeace** [comment]
你是 IPv6 only的小鸡吗？用warp搭个 ipv4 出来。
```
bash <(curl -fsSL https://raw.githubusercontents.com/crazypeace/warp.sh/main/warp.sh) 4
```
https://zelikk.blogspot.com/2022/03/hax-vps-us-1-github-warp-usercontents.html

**Comment by THU-Pieris** [comment]
> 你是 IPv6 only的小鸡吗？用warp搭个 ipv4 出来。
> 
> ```
> bash <(curl -fsSL https://raw.githubusercontents.com/crazypeace/warp.sh/main/warp.sh) 4
> ```
> 
> https://zelikk.blogspot.com/2022/03/hax-vps-us-1-github-warp-usercontents.html

我也是这个问题。但我的VPS是有公网IPv4地址的。

**Comment by crazypeace** [comment]
> > 你是 IPv6 only的小鸡吗？用warp搭个 ipv4 出来。
> > ```
> > bash <(curl -fsSL https://raw.githubusercontents.com/crazypeace/warp.sh/main/warp.sh) 4
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > https://zelikk.blogspot.com/2022/03/hax-vps-us-1-github-warp-usercontents.html
> 
> 我也是这个问题。但我的VPS是有公网IPv4地址的。

那你自己在vps上访问一下你想访问的网址看看
```
curl https://网址
```
