### ISSUE TITLE
github没有v2ray_download_link路径

### ISSUE THREAD

**Issue by xiaoluanECNU** [233boy/v2ray#847]
v2ray_download_link="https://github.com/v2ray/v2ray-core/releases/download/$v2ray_latest_ver/v2ray-linux-${v2ray_bit}.zip"该github没有v2ray_download_link路径

**Comment by crazypeace** [comment]
> v2ray_download_link="[https://github.com/v2ray/v2ray-core/releases/download/$v2ray_latest_ver/v2ray-linux-${v2ray_bit}.zip"该github没有v2ray_download_link路径](https://github.com/v2ray/v2ray-core/releases/download/$v2ray_latest_ver/v2ray-linux-$%7Bv2ray_bit%7D.zip%22%E8%AF%A5github%E6%B2%A1%E6%9C%89v2ray_download_link%E8%B7%AF%E5%BE%84)

你该更新脚本了吧？现在是v2ray在v2fly下面。
---
如果没问题，不用老是更新。不会弄 越更新越出错。
https://zelikk.blogspot.com/2022/01/v2ray-caddy-ws-tls-cdn.html
