### ISSUE TITLE
使用cloudflare中转后无法代理

### ISSUE THREAD

**Issue by liuqisakuya** [233boy/v2ray#850]
### 操作环境  
centos7
### 操作步骤：
1. 安装脚本 选择4（WebSocket + TLS）,正常完成安装，此时PC和移动端均可以使用生成的vmess进行代理；
2. 在cloudflare上打开域名的代理，ios的shadowrocket能正常使用vmess链接；
但mac端V2rayU（3.2.0）导入vmess能测速，但是PAC模式和全局模式均无法代理；
windows10和mac（10.15）上 使用0.19和0.15.10版的clashForWindow，均无法测速和代理
3. 关闭cloudflare的代理后一切正常

希望能告知如何解决这个问题或者如何排查问题原因

### vmess链接：
vmess://ewoidiI6ICIyIiwKInBzIjogIjIzM3YyLmNvbV9ibG9nLmxpdXFpc2FrdXlhLnRvcCIsCiJhZGQiOiAiYmxvZy5saXVxaXNha3V5YS50b3AiLAoicG9ydCI6ICI0NDMiLAoiaWQiOiAiZGU4MmZmNWQtMDlkNi00YWQ3LWE0MTYtOWM5OWZlNjNhMjg0IiwKImFpZCI6ICIwIiwKIm5ldCI6ICJ3cyIsCiJ0eXBlIjogIm5vbmUiLAoiaG9zdCI6ICJibG9nLmxpdXFpc2FrdXlhLnRvcCIsCiJwYXRoIjogIi9saXVxaSIsCiJ0bHMiOiAidGxzIgp9Cg==

### v2rayU配置
```json
{
  "log": {
    "error": "",
    "loglevel": "info",
    "access": ""
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "protocol": "socks",
      "settings": {
        "udp": false,
        "auth": "noauth"
      },
      "port": "1080"
    },
    {
      "listen": "127.0.0.1",
      "protocol": "http",
      "settings": {
        "timeout": 360
      },
      "port": "1087"
    }
  ],
  "outbounds": [
    {
      "mux": {
        "enabled": false,
        "concurrency": 8
      },
      "protocol": "vmess",
      "streamSettings": {
        "wsSettings": {
          "path": "/liuqi",
          "headers": {
            "host": "blog.liuqisakuya.top"
          }
        },
        "tlsSettings": {
          "serverName": "blog.liuqisakuya.top",
          "allowInsecure": false
        },
        "security": "tls",
        "network": "ws"
      },
      "tag": "proxy",
      "settings": {
        "vnext": [
          {
            "address": "blog.liuqisakuya.top",
            "users": [
              {
                "id": "de82ff5d-09d6-4ad7-a416-9c99fe63a284",
                "alterId": 0,
                "level": 0,
                "security": "none"
              }
            ],
            "port": 443
          }
        ]
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIP",
        "userLevel": 0
      }
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "none"
        }
      }
    }
  ],
  "dns": {},
  "routing": {
    "settings": {
      "domainStrategy": "AsIs",
      "rules": [
        {
          "type": "field",
          "outboundTag": "proxy",
          "domain": [
            "github.com"
          ]
        }
      ]
    }
  },
  "transport": {}
}
```
### 截图
![image](https://user-images.githubusercontent.com/17400269/156301513-b950ee14-edc3-4286-8a98-7b3d9e1fff39.png)
![image](https://user-images.githubusercontent.com/17400269/156301445-252df946-1952-4083-9744-e45654fac73e.png)

**Comment by crazypeace** [comment]
我猜问题出在cloudflare的设置上。
TLS 设置为 “完全”
https://zelikk.blogspot.com/2021/11/racknerd-vps-v2ray-1g-1t-12g-768mb-1088.html
--- 
给你个测试思路，如果你说PC正常是指windows的话，把config.json取出来。在mac上裸跑v2ray，用一样的config.json。你在应用软件里直接设置走v2ray的sock代理，看能否正常使用。

**Comment by liuqisakuya** [comment]
感谢 虽然经常断链，但是能使用了

**Comment by xazl02** [comment]
> ## 我猜问题出在cloudflare的设置上。
> TLS 设置为 “完全”
> https://zelikk.blogspot.com/2021/11/racknerd-vps-v2ray-1g-1t-12g-768mb-1088.html
> 给你个测试思路，如果你说PC正常是指windows的话，把config.json取出来。在mac上裸跑v2ray，不用图形界面。用一样的config.json。你在应用软件里直接设置走v2ray的sock代理，看能否正常使用。

太感谢您了，解决了我的困惑！排查了几乎所有的错误，把这个设置忘了。
