### ISSUE TITLE
 [Warning] [1352912064] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [dial tcp vpsip:端口: connectex: No connection could be made because the target machine actively refused it. ] > common/retry: all retry attempts failed 

### ISSUE THREAD

**Issue by Lxmwww** [233boy/v2ray#852]
[Warning] [1352912064] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [dial tcp vpsip:端口: connectex: No connection could be made because the target machine actively refused it. ] > common/retry: all retry attempts failed 
这个问题搞了一下午了了，大佬该怎么解决啊

**Comment by crazypeace** [comment]
你也不讲一下你自己的环境，想干什么。丢个配置文件出来 也行啊。

**Comment by gy9527** [comment]
> [Warning] [1352912064] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [dial tcp vpsip:端口: connectex: No connection could be made because the target machine actively refused it. ] > common/retry: all retry attempts failed 这个问题搞了一下午了了，大佬该怎么解决啊

老哥，解决了吗，同样的问题，也是一下午了

**Comment by crazypeace** [comment]
安装 V2ray Websocket + TLS 模式 排错指引
https://zelikk.blogspot.com/2022/04/setup-v2ray-websocket-tls-troubleshoot.html
连接 V2Ray Websocket + TLS 模式的过程 及 排错指引
https://zelikk.blogspot.com/2022/04/connect-v2ray-websocket-tls-troubleshoot.html

**Comment by Killxifat** [comment]
一模一样的问题，Vultr的服务器，完全一样的代码和安装步骤，去年创建的服务器可用，今年创建的所有服务器绝不可用。
翻遍了论坛没有找到任何一个有用的解决方案。真是绝了

**Comment by crazypeace** [comment]
> 

说一下你用的脚本 或者 教程？

**Comment by jackcxj** [comment]
https://github.com/233boy/v2ray/wiki/V2Ray%E4%B8%80%E9%94%AE%E5%AE%89%E8%A3%85%E8%84%9A%E6%9C%AC 用的这个教程的脚本，手机ss可以，但是电脑vmess不行，改成用ss方式也不行，有没有有一样的问题

**Comment by crazypeace** [comment]
换一个更简单的脚本？
https://github.com/crazypeace/V2ray_VLESS_WebSocket_TLS_CaddyV2
