### ISSUE TITLE
使用ws+tls失败，用tcp就可以，服务器ubuntu20.0.4，443端口nginx监听了。请问要怎么解决？

### ISSUE THREAD

**Issue by miaobang** [233boy/v2ray#853]
2022/03/11 18:00:20 [Warning] [2215579602] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://mbtyymz.xyz/233blog): 302 Moved Temporarily > websocket: bad handshake] > common/retry: all retry attempts failed
2022/03/11 18:00:20 [Info] [2215579602] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2022/03/11 18:00:20 [Info] [2226596838] proxy/http: request to Method [CONNECT] Host [rr3---sn-
2022/03/11 18:00:21 [Warning] [1058071681] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://mbtyymz.xyz/233blog): 302 Moved Temporarily > websocket: bad handshake] > common/retry: all retry attempts failed
2022/03/11 18:00:21 [Info] [1058071681] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2022/03/11 18:00:21 [Info] [2992110019] proxy/http: request to Method [CONNECT] Host [aegis.qq.com:443] with URL [//aegis.qq.com:443]

**Comment by miaobang** [comment]
补充nginx的conf文件的配置
server {
	     #SSL 访问端口号为 443
	     listen 443 ssl; 
	     #填写绑定证书的域名
	     server_name mbtyymz.xyz; 
	     #证书文件名称
	     ssl_certificate XXXX; 
	     #私钥文件名称
	     ssl_certificate_key XXX;
	     ssl_session_timeout 5m;
	     #请按照以下协议配置
	     ssl_protocols TLSv1.2 TLSv1.3; 
	     #请按照以下套件配置，配置加密套件，写法遵循 openssl 标准。
	     ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE; 
	     ssl_prefer_server_ciphers on;
	     return https://www.baidu.com;
	}

**Comment by miaobang** [comment]
v2ray服务器上面查看的错误日志
2022/03/11 17:53:25 [Error] app/dns: failed to retrieve response > Post "https://8.8.8.8/dns-query": context canceled
2022/03/11 17:53:46 [Warning] V2Ray 4.44.0 started

**Comment by crazypeace** [comment]
自己不会弄就交给脚本来弄。

**Comment by miaobang** [comment]
> > > 自己不会弄就交给脚本来弄。
> > 
> > 
> > 是用脚本弄，弄了连接不上啊不就来求助
> 
> 233 脚本不是装caddy的吗？ 你这是nginx啊。

因为要用nginx来做中转。那能否两个同时使用吗？

**Comment by miaobang** [comment]
> > > 自己不会弄就交给脚本来弄。
> > 
> > 
> > 是用脚本弄，弄了连接不上啊不就来求助
> 
> 233 脚本不是装caddy的吗？ 你这是nginx啊。

所以解决方案是不是，nginx不监听443端口？留给caddy？

**Comment by crazypeace** [comment]
> > > > 自己不会弄就交给脚本来弄。
> > > 
> > > 
> > > 是用脚本弄，弄了连接不上啊不就来求助
> > 
> > 
> > 233 脚本不是装caddy的吗？ 你这是nginx啊。
> 
> 所以解决方案是不是，nginx不监听443端口？留给caddy？

你拿nginx干什么的？不监听443端口怎么搭HTTPS网站呢？
1、要么你去学一下怎么用ngix建站，然后学习nginx的语法，然后学会怎么反代给caddy
2、要么你跑脚本装caddy，然后学习怎么用caddy建站，修改caddy的配置文件
3、要么你跑别人的脚本，xray监听443，“回落”到ngix或者caddy你建的站

**Comment by crazypeace** [comment]
抱歉我不会Nginx

**Comment by crazypeace** [comment]
233boy在这里写了一篇，你看看？
https://233v2.com/post/3/

**Comment by miaobang** [comment]
> 233boy在这里写了一篇，你看看？ https://233v2.com/post/3/

感谢！应该就是需要这个配置
