### ISSUE TITLE
v2ray的端口开放后也ping不通，查看到端口未使用

### ISSUE THREAD

**Issue by loohalh** [233boy/v2ray#854]
v2ray的端口开放后也ping不通，查看到端口未使用。导致无法连接，
 netstat -ntlp 查看到，只监听了一个端口，为ssr端口
安装时如果不选择配置ssr，安装完成后， netstat -ntlp 没有看到v2ray任何端口

**Comment by hellger** [comment]
同样端口未使用，我的使用oracle cloud免费的实例，更换ubuntu 20和centos 7 都不行，宝塔安装后使用 lsof -i 80可以看到同时开启了ipv4和ipv6的80端口，但是v2ray安装后lsof -i 只能看到ipv6的端口开启，ipv4没有记录（然而主机并未启用ipv6）。请问你的问题解决了吗？

**Comment by loohalh** [comment]
> 同样端口未使用，我的使用oracle cloud免费的实例，更换ubuntu 20和centos 7 都不行，宝塔安装后使用 lsof -i 80可以看到同时开启了ipv4和ipv6的80端口，但是v2ray安装后lsof -i 只能看到ipv6的端口开启，ipv4没有记录（然而主机并未启用ipv6）。请问你的问题解决了吗？
没有解决，放弃了 ==

**Comment by loohalh** [comment]
> 同样端口未使用，我的使用oracle cloud免费的实例，更换ubuntu 20和centos 7 都不行，宝塔安装后使用 lsof -i 80可以看到同时开启了ipv4和ipv6的80端口，但是v2ray安装后lsof -i 只能看到ipv6的端口开启，ipv4没有记录（然而主机并未启用ipv6）。请问你的问题解决了吗？

没解决，放弃了==

**Comment by Yuanlailai** [comment]
找到可能的原因，kcp会使用动态端口，或许跟这个有关，改成其他的协议就可以正常listen了
