### ISSUE TITLE
無法安裝

### ISSUE THREAD

**Issue by 23232333aaa** [233boy/v2ray#855]
顯示以下錯誤
aaa@aaa:~$ sudo bash <(curl -s -L https://git.io/v2ray.sh)                                                                         

bash: /dev/fd/63: No such file or directory                               

請問大佬如何解決

**Comment by crazypeace** [comment]
能重装系统吗？换Debian 10以上版本，使用方便。

**Comment by 23232333aaa** [comment]
> 能重装系统吗？换Debian 10以上版本，使用方便。

還沒試過
最近Ubuntu和deepin全有這個問題，要換命令才解決https://github.com/233boy/v2ray/issues/181#issuecomment-485095408

**Comment by ljb698** [comment]
系统换了u，安装的代码有什么改变，完全小白，谢谢🙏
sudo -i#获取超级用户权限
	bash <(curl -s -L https://git.io/v2ray.sh)#在服务器安装V2ray，都选默认
	systemctl stop firewalld.service#执行关闭防火墙命令
	systemctl disable firewalld.service#执行开机禁用防火墙自启命令
	v2ray url#获取vmess地址

**Comment by ljb698** [comment]
我这样做出来的V2ray.还是不能用

**Comment by crazypeace** [comment]
> 我这样做出来的V2ray.还是不能用

哪个VPS商？
