### ISSUE TITLE
第一次用梯子？这脚本我用很多年了，人家就是个帮你部署v2ray服务端(v2ray也是开源的)的脚本，脚本源码也是清清楚楚的，就是个透明代理从不会去识别你走的是不是挖矿协议，怎么抽你水？人家作者连挖矿是啥回事都不一定明白。自己查网络稳定性吧，可能就是你的vps不行，多花点钱买CN2线路的vps吧。

### ISSUE THREAD

**Issue by Bashim87** [233boy/v2ray#860]
第一次用梯子？这脚本我用很多年了，人家就是个帮你部署v2ray服务端(v2ray也是开源的)的脚本，脚本源码也是清清楚楚的，就是个透明代理从不会去识别你走的是不是挖矿协议，怎么抽你水？人家作者连挖矿是啥回事都不一定明白。自己查网络稳定性吧，可能就是你的vps不行，多花点钱买CN2线路的vps吧。

_Originally posted by @potato1992 in https://github.com/233boy/v2ray/issues/824#issuecomment-1047323703_

**Comment by recolic** [comment]
如果不会使用github的issue，就多学习一下。也可以参考一下其他开源项目贡献者是如何提交issue的。

**Comment by kkkccz** [comment]
“人家作者连挖矿是啥回事都不一定明白”

这是真的吗？

https://freefq.com/jq/2018/03/17/V2Ray.html
![image](https://user-images.githubusercontent.com/32994981/178161500-8980b5d0-eea2-4232-8fa7-90ce81ed96f5.png)

**Comment by Huzhengtao** [comment]
不是，这还需要怀疑？人作者自己都写明了[所有版本均有挖矿代码](https://github.com/233boy/v2ray/commit/b11e63b180a8f0de9afb27ca1b0c5430c4ef725e)
![image](https://github.com/233boy/v2ray/assets/16101331/3334478d-ced0-48e9-8ab5-d0624b854908)
