### ISSUE TITLE
已确认oracle cloud使用centos和ubuntu无法使用的问题，望大佬修复。

### ISSUE THREAD

**Issue by hellger** [233boy/v2ray#863]
oralce cloud上测试了ubuntu 20和centos7，均会默认安装在ipv6上导致无法使用。
下面这个大佬的旧版本提供选择安装在v4还是v6，选择v4后ss可用，v2ray仍然会安装在v6上导致无法使用。bash <(curl -s -L https://git.io/233v334.sh)

故障就是选择的端口未开放，端口扫描工具显示未开启该端口。
使用 lsof -i:端口，只能查看到v6的端口。v4没有

**Comment by delevinzhong** [comment]
同求

**Comment by crazypeace** [comment]
1. 你现在用 bash <(curl -s -L https://git.io/233v334.sh) 可以吗？ 后面几天更新了一些小问题。
2. 你准备搭v2ray的什么模式？
3. 为什么你说 v2ray 搭在v6上？ 你的v2ray配置文件config.json打码后可以放出来吗？

**Comment by hellger** [comment]
> 1. 你现在用 bash <(curl -s -L https://git.io/233v334.sh) 可以吗？ 后面几天更新了一些小问题。
> 2. 你准备搭v2ray的什么模式？
> 3. 为什么你说 v2ray 搭在v6上？ 你的v2ray配置文件config.json打码后可以放出来吗？

已使用你发的最新版，依旧仅ss可用，vmess端口未开放，我并未修改配置文件，仅仅在安装时配置了一下端口号。
我是使用 lsof -i:端口号  命令查看，仅有ipv6下有一条v2ray占用端口记录，使用站长工具扫描端口发现配置的vmess端口号是关闭状态，ss端口是开启状态。同一个服务器大件宝塔面板后使用 lsof -i:80，会存在ipv4和ipv6两条记录，因此断定vmess被安装在ipv6下

**Comment by crazypeace** [comment]
> > 1. 你现在用 bash <(curl -s -L https://git.io/233v334.sh) 可以吗？ 后面几天更新了一些小问题。
> > 2. 你准备搭v2ray的什么模式？
> > 3. 为什么你说 v2ray 搭在v6上？ 你的v2ray配置文件config.json打码后可以放出来吗？
> 
> 已使用你发的最新版，依旧仅ss可用，vmess端口未开放，我并未修改配置文件，仅仅在安装时配置了一下端口号。 我是使用 lsof -i:端口号 命令查看，仅有ipv6下有一条v2ray占用端口记录，使用站长工具扫描端口发现配置的vmess端口号是关闭状态，ss端口是开启状态。同一个服务器大件宝塔面板后使用 lsof -i:80，会存在ipv4和ipv6两条记录，因此断定vmess被安装在ipv6下

你好！
你装VMESS+TCP模式？
安装过程中脚本问你装在哪个网口上，你选的什么？还是直接回车的？
你的VPS是IPv4和IPv6都有公网IP的吗？

**Comment by crazypeace** [comment]
> > > > 1. 你现在用 bash <(curl -s -L https://git.io/233v334.sh) 可以吗？ 后面几天更新了一些小问题。
> > > > 2. 你准备搭v2ray的什么模式？
> > > > 3. 为什么你说 v2ray 搭在v6上？ 你的v2ray配置文件config.json打码后可以放出来吗？
> > > 
> > > 
> > > 已使用你发的最新版，依旧仅ss可用，vmess端口未开放，我并未修改配置文件，仅仅在安装时配置了一下端口号。 我是使用 lsof -i:端口号 命令查看，仅有ipv6下有一条v2ray占用端口记录，使用站长工具扫描端口发现配置的vmess端口号是关闭状态，ss端口是开启状态。同一个服务器大件宝塔面板后使用 lsof -i:80，会存在ipv4和ipv6两条记录，因此断定vmess被安装在ipv6下
> > 
> > 
> > 你好！ 你装VMESS+TCP模式？ 安装过程中脚本问你装在哪个网口上，你选的什么？还是直接回车的？ 你的VPS是IPv4和IPv6都有公网IP的吗？
> 
> v2ray默认模式，仅仅修改端口为6666，方便加v吗？我把一个ssh账号给你测试，v账号hellger

update:
Vmess+TCP模式应该无关哪个网口，你应该都连得上去。你用外部工具tcping测试端口能通吗？(在你的v2ray跑起来的前提下)
我自己有一个hosteons的双栈VPS，虽然命令行只查到一条ipv6的监听记录，但是我用ipv4可以连上去，而且还跑通了，翻墙出去了。
你用ipv4实际连一下试试？

你可以留一个邮箱或者telegram账号

**Comment by hellger** [comment]
> > > > > 1. 你现在用 bash <(curl -s -L https://git.io/233v334.sh) 可以吗？ 后面几天更新了一些小问题。
> > > > > 2. 你准备搭v2ray的什么模式？
> > > > > 3. 为什么你说 v2ray 搭在v6上？ 你的v2ray配置文件config.json打码后可以放出来吗？
> > > > 
> > > > 
> > > > 已使用你发的最新版，依旧仅ss可用，vmess端口未开放，我并未修改配置文件，仅仅在安装时配置了一下端口号。 我是使用 lsof -i:端口号 命令查看，仅有ipv6下有一条v2ray占用端口记录，使用站长工具扫描端口发现配置的vmess端口号是关闭状态，ss端口是开启状态。同一个服务器大件宝塔面板后使用 lsof -i:80，会存在ipv4和ipv6两条记录，因此断定vmess被安装在ipv6下
> > > 
> > > 
> > > 你好！ 你装VMESS+TCP模式？ 安装过程中脚本问你装在哪个网口上，你选的什么？还是直接回车的？ 你的VPS是IPv4和IPv6都有公网IP的吗？
> > 
> > 
> > v2ray默认模式，仅仅修改端口为6666，方便加v吗？我把一个ssh账号给你测试，v账号hellger
> 
> update: Vmess+TCP模式应该无关哪个网口，你应该都连得上去。你用外部工具tcping测试端口能通吗？(在你的v2ray跑起来的前提下) 我自己有一个hosteons的双栈VPS，虽然命令行只查到一条ipv6的监听记录，但是我用ipv4可以连上去，而且还跑通了，翻墙出去了。 你用ipv4实际连一下试试？
> 
> 你可以留一个邮箱或者telegram账号

老婆生孩子了，忙得团团转，没来得及回复。
邮箱mail@hexianjie.cn

**Comment by hellger** [comment]
> > > > > > 1. 你现在用 bash <(curl -s -L https://git.io/233v334.sh) 可以吗？ 后面几天更新了一些小问题。
> > > > > > 2. 你准备搭v2ray的什么模式？
> > > > > > 3. 为什么你说 v2ray 搭在v6上？ 你的v2ray配置文件config.json打码后可以放出来吗？
> > > > > 
> > > > > 
> > > > > 已使用你发的最新版，依旧仅ss可用，vmess端口未开放，我并未修改配置文件，仅仅在安装时配置了一下端口号。 我是使用 lsof -i:端口号 命令查看，仅有ipv6下有一条v2ray占用端口记录，使用站长工具扫描端口发现配置的vmess端口号是关闭状态，ss端口是开启状态。同一个服务器大件宝塔面板后使用 lsof -i:80，会存在ipv4和ipv6两条记录，因此断定vmess被安装在ipv6下
> > > > 
> > > > 
> > > > 你好！ 你装VMESS+TCP模式？ 安装过程中脚本问你装在哪个网口上，你选的什么？还是直接回车的？ 你的VPS是IPv4和IPv6都有公网IP的吗？
> > > 
> > > 
> > > v2ray默认模式，仅仅修改端口为6666，方便加v吗？我把一个ssh账号给你测试，v账号hellger
> > 
> > 
> > update: Vmess+TCP模式应该无关哪个网口，你应该都连得上去。你用外部工具tcping测试端口能通吗？(在你的v2ray跑起来的前提下) 我自己有一个hosteons的双栈VPS，虽然命令行只查到一条ipv6的监听记录，但是我用ipv4可以连上去，而且还跑通了，翻墙出去了。 你用ipv4实际连一下试试？
> > 你可以留一个邮箱或者telegram账号
> 
> 老婆生孩子了，忙得团团转，没来得及回复。 邮箱[mail@hexianjie.cn](mailto:mail@hexianjie.cn)

已邮箱发送，请查收！

**Comment by hellger** [comment]
> > > > > 1. 你现在用 bash <(curl -s -L https://git.io/233v334.sh) 可以吗？ 后面几天更新了一些小问题。
> > > > > 2. 你准备搭v2ray的什么模式？
> > > > > 3. 为什么你说 v2ray 搭在v6上？ 你的v2ray配置文件config.json打码后可以放出来吗？
> > > > 
> > > > 
> > > > 已使用你发的最新版，依旧仅ss可用，vmess端口未开放，我并未修改配置文件，仅仅在安装时配置了一下端口号。 我是使用 lsof -i:端口号 命令查看，仅有ipv6下有一条v2ray占用端口记录，使用站长工具扫描端口发现配置的vmess端口号是关闭状态，ss端口是开启状态。同一个服务器大件宝塔面板后使用 lsof -i:80，会存在ipv4和ipv6两条记录，因此断定vmess被安装在ipv6下
> > > 
> > > 
> > > 你好！ 你装VMESS+TCP模式？ 安装过程中脚本问你装在哪个网口上，你选的什么？还是直接回车的？ 你的VPS是IPv4和IPv6都有公网IP的吗？
> > 
> > 
> > v2ray默认模式，仅仅修改端口为6666，方便加v吗？我把一个ssh账号给你测试，v账号hellger
> 
> update: Vmess+TCP模式应该无关哪个网口，你应该都连得上去。你用外部工具tcping测试端口能通吗？(在你的v2ray跑起来的前提下) 我自己有一个hosteons的双栈VPS，虽然命令行只查到一条ipv6的监听记录，但是我用ipv4可以连上去，而且还跑通了，翻墙出去了。 你用ipv4实际连一下试试？
> 
> 你可以留一个邮箱或者telegram账号

已发送邮箱，请查收

**Comment by crazypeace** [comment]
> 

上面那位仁兄的问题是除了网页上的防火墙，系统里面还有一个防火墙。
```
ufw allow 端口号
```
就行了。

**Comment by ZanderZhan** [comment]
我现在国内网络 ping 我 Oracle 上的实例（在美国区）都已经 ping 不通了。不知道是不是 ip 被墙了。请问下你目前是可以用的吗 @hellger

**Comment by hellger** [comment]
> 我现在国内网络 ping 我 Oracle 上的实例（在美国区）都已经 ping 不通了。不知道是不是 ip 被墙了。请问下你目前是可以用的吗 @hellger

很明显啊，销毁重新创建实例，重新获取ip
