### ISSUE TITLE
tcp timeout

### ISSUE THREAD

**Issue by Facico** [233boy/v2ray#864]
配置是 v2ray(vless+nginx+ws+tls)，机子是vultr的ubuntu，域名是namesilo的。

2022/04/16 13:43:48 [Warning] [1883459213] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vless/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://mg.facico.top/ee7723249b63/):  > dial tcp 207.148.27.115:443: i/o timeout v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://mg.facico.top/ee7723249b63/):  > dial tcp 207.148.27.115:443: operation was canceled v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://mg.facico.top/ee7723249b63/):  > dial tcp: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed
VPN装好后能用，但是偶尔会出现上面的问题，一般过一分钟左右就恢复了，想知道怎么解决上面这个问题

**Comment by Facico** [comment]
tcp端口（80）在https://tcp.ping.pe测没有问题，服务挂的443端口本地也能正常telnet（没在断连的时候测过）

**Comment by crazypeace** [comment]
应该是域名被干扰了。有可能是干扰解析，有可能是针对 sni 干扰。

可以多弄几个域名，freenom有免费的
https://zelikk.blogspot.com/2022/01/ws-tls-v2ray-caddy-multi-domain.html
也可以弄cloudflare的worker
https://zelikk.blogspot.com/2021/05/domian-ban-websocket-tls-web-cdn-cloudclare-worker.html

**Comment by FanFanFantastic** [comment]
同样的情况。。
