### ISSUE TITLE
v2ray

### ISSUE THREAD

**Issue by zyssd** [233boy/v2ray#865]

**Comment by githubwomengay** [comment]
大佬们，萌新就想要个翻墙做设计用的VPN，有没有教我用的

**Comment by crazypeace** [comment]
这个两个VPS是免费的.你先练练手.
https://zelikk.blogspot.com/2022/03/hax-ipv6-only-vps-v2ray-vmess-tcp-warp-ipv4.html
https://zelikk.blogspot.com/2022/04/woiden-ipv6-vps-v2ray-vless-websocket-tls.html
如果你想长期的.可以买一个VPS https://zelikk.blogspot.com/2021/11/racknerd-vps-v2ray-1g-1t-12g-768mb-1088.html

教程比较长，比较啰嗦，但是很详细，图文并茂。只要你认得字母就能操作。
