### ISSUE TITLE
下载 V2Ray 失败啦..可能是你的 VPS 网络太辣鸡了...请重试...

### ISSUE THREAD

**Issue by defuswang** [233boy/v2ray#866]
是不是因为在境外的原因而安装不了？用的瓦工的50美金一年的vps

**Comment by defuswang** [comment]
/etc/v2ray/233boy/v2ray/src/download-v2ray.sh: line 22: wget: command not found
No match for argument: qrencode

**Comment by crazypeace** [comment]
apt update
apt install -y wget

**Comment by JY-jiuyi** [comment]
> apt update apt install -y wget
> 
> 以后你凡是看到 command not found 就把前面的那个命令用 apt install 装一下

用apt的时候 command not found

**Comment by crazypeace** [comment]
> > apt update apt install -y wget
> > 以后你凡是看到 command not found 就把前面的那个命令用 apt install 装一下
> 
> 用apt的时候 command not found

那可能 你的操作系统 不是 ubuntu 或者 debian.
要么你查一下你的操作系统用什么方式安装.
要么你换操作系统, 换成 Debian 或者 Ubuntu.
