### ISSUE TITLE
安卓 windows 都正常。 ios链接超时

### ISSUE THREAD

**Issue by Johnny-dot** [233boy/v2ray#867]
安卓 windows 都正常。 ios链接超时。是不是协议不支持，还是哪些东西shadowWocket不支持

**Comment by crazypeace** [comment]
安装 V2ray Websocket + TLS 模式 排错指引
https://zelikk.blogspot.com/2022/03/v2ray-websocket-tls-troubleshoot.html

连接 V2Ray Websocket + TLS 模式的过程 及 排错指引
https://zelikk.blogspot.com/2022/04/v2ray-websocket-tls-troubleshoot.html
