### ISSUE TITLE
谷歌云安装后慢

### ISSUE THREAD

**Issue by smilencexh** [233boy/v2ray#868]
使用谷歌云，按照这个脚本安装后，发现网速很慢，YouTube只有5K左右，原来的时候可以达到一二十万，这个是什么原因？

**Comment by crazypeace** [comment]
和线路有关。
VPS换个地区开？
如果你是套CDN的，试试CF IP优选？

**Comment by smilencexh** [comment]
选的是香港地区，也没有套用CDN，不知道是啥情况

**Comment by henryswisvip** [comment]
安装BBR PLUS + FQ 然后系统选debian 10
