### ISSUE TITLE
 哈哈……这个 辣鸡脚本 不支持你的系统。 (-_-) 

### ISSUE THREAD

**Issue by 1265578519** [233boy/v2ray#87]
sh v2ray.sh
 哈哈……这个 辣鸡脚本 不支持你的系统。 (-_-) 

为啥不支持centos6 x64呢。

**Comment by babyofsnake** [comment]
/bin/systemctl 这个文件不存在

**Comment by 1265578519** [comment]
嘤嘤嘤？vi /bin/systemctl 123 :wq?

**Comment by babyofsnake** [comment]
https://www.feiqy.com/v2ray/

**Comment by 233boy** [comment]
@1265578519 
老掉牙的系统 懒得支持了，快来使用新时代的产物吧
