### ISSUE TITLE
访问不了百度主页，其他网站正常

### ISSUE THREAD

**Issue by xiyuvi** [233boy/v2ray#870]
看了一下服务器错误日志，提示这个“[Error] app/dns: failed to retrieve response > Post "https://8.8.8.8/dns-query": context canceled”
我猜测是8.8.8.8解析www.baidu.com有问题，想把他改成别的试一试。
请教一下这个应该在哪里设置

**Comment by xiyuvi** [comment]
https://1.1.1.1/dns-query 改成这个应该就可以了

**Comment by crazypeace** [comment]
建议你 百度 就别走梯子了。
在你的v2ray客户端应该有路由分流设置。或者你用浏览器插件
https://zelikk.blogspot.com/2022/01/chrome-switchyomega-gfwlist.html
