### ISSUE TITLE
在Xshell7上输入bash <(curl -s -L https://233v2.com/v2.sh)，并没有反应。

### ISSUE THREAD

**Issue by hanlin22** [233boy/v2ray#873]
在Xshell7上输入bash <(curl -s -L https://233v2.com/v2.sh) ，并且是在已经安装了Curl之后，并没有反应。请问下各位大佬们怎么解决。

**Comment by crazypeace** [comment]
github后来发了新公告了 git.io 不会失效了
你还是用原来的
bash <(curl -s -L git.io/v2ray.sh)

**Comment by TeddyWong19** [comment]
> worked，感谢大佬
