### ISSUE TITLE
可以隐藏DNS吗

### ISSUE THREAD

**Issue by SolinTao** [233boy/v2ray#874]
VPS是香港服务器广播IP到英国的，https://whoer.net/zh检测发现IP是英国，DNS解析是中国：你的 DNS 服务器所在的国家不同于你的 IP 地址所在的国家。通常情况下，这表明你试图隐藏自己的位置。请问有解决方法吗？

**Comment by crazypeace** [comment]
你试试 DOH?
https://zelikk.blogspot.com/2018/12/firefox-dns-over-https-doubi.html
