### ISSUE TITLE
执行安装命令后无任何输出

### ISSUE THREAD

**Issue by laferce** [233boy/v2ray#875]
在 Hax VPS 上用刚安装的 CentOS7 和 Debian11 都试过，本地的虚拟机 CentOS7 和 Kali2022 也试过，执行后过几分钟结束，没有任何输出。请问是哪里配置没对？

**Comment by AllenHeeee** [comment]
+1

**Comment by hugoking1979** [comment]
+1

**Comment by crazypeace** [comment]
1. 把全部的日志提交上来
2. 换个脚本
如果你是想搭 vless +ws +tls
https://github.com/crazypeace/V2ray_VLESS_WebSocket_TLS_CaddyV2
在hax上是没问题的。
教程
https://zelikk.blogspot.com/2022/03/hax-ipv6-only-vps-v2ray-vmess-tcp-warp-ipv4.html
