### ISSUE TITLE
V2Ray 版本: v4.45.0，不能登录HBOMAX，但访问netfliex正常。

### ISSUE THREAD

**Issue by tyler2002** [233boy/v2ray#877]
V2Ray 版本: v4.45.0，不能登录HBOMAX，但访问netfliex正常。
我的IP是美国的地址，服务正常启动，服务在pc和app上正常使用。
访问HBOMAX，点击登录报错，提示“We’re having issues connecting to HBO Max right now. Please try again.”。
请问，是我哪里需要调整或这个修改。

**Comment by crazypeace** [comment]
在你自己的VPS上访问你想访问的网址，返回结果是否正常？
```
curl https://你想访问的网址
```
如果你想装warp，让hbomax换个出口出去。可以参考
https://zelikk.blogspot.com/2022/05/woiden-v2ray-cloudflare-warp-socks-proxy-google-domainstrategy-outboundtag-routing.html
https://zelikk.blogspot.com/2022/03/racknerd-v2ray-cloudflare-warp--ipv6-google-domainstrategy-outboundtag-routing.html
