### ISSUE TITLE
搭建好的v2ray 复制粘贴到 v2ray软件上出现这个提示 已建立的连接被您的主机中的软件终止 是什么原因啊？

### ISSUE THREAD

**Issue by Clover177** [233boy/v2ray#879]
app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [dial tcp 45.76.211.236:24886: i/o timeout dial tcp 45.76.211.236:24886: operation was canceled] > common/retry: all retry attempts failed

**Comment by Clover177** [comment]
上面这个是日志

**Comment by crazypeace** [comment]
你搭的什么模式？
如果是vmess协议的，把系统时间同步一下。

**Comment by Sadcrazy** [comment]
> 开始更新 v2rayN...
2022/06/24 12:22:34 127.0.0.1:49695 accepted //www.google.com:443 [http -> proxy]
5.26 已是最新版本。
2022/06/24 12:23:07 [Warning] [3310581681] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [dial tcp 45.63.82.78:29229: i/o timeout dial tcp 45.63.82.78:29229: operation was canceled] > common/retry: all retry attempts failed

请问我这个v2rayN客户端导入vmess节点是这样 检查更新v2rayN失败 右下角显示网速未启用

**Comment by Sadcrazy** [comment]
> 系统时间同步

请问大佬怎么把系统时间同步一下

**Comment by crazypeace** [comment]
google搜索
电脑系统时间同步
