### ISSUE TITLE
Socks install failed

### ISSUE THREAD

**Issue by XstepAhead** [233boy/v2ray#881]
![Screenshot_2022-06-01-18-06-54-198_com sonelli juicessh](https://user-images.githubusercontent.com/61716582/171390630-2a0a7eee-0d89-4eb0-b408-4a7126d82a6b.jpg)

This always show when im install or uninstall, and vps get close session

**Comment by 233boy** [comment]
@XstepAhead 
fixed. 9b158e4
use `v2ray update.sh` command update script and try again.
