### ISSUE TITLE
连接几分钟内就ping不通了,丢包网页也打不开了

### ISSUE THREAD

**Issue by FanFanFantastic** [233boy/v2ray#882]
为什么以前用的好好的VPS，今年连接几分钟内就ping不通了。

一直用的谷歌云，近期大姨妈一样，断断续续的或者30分钟就根本ping不通，是不是被GFW盯上了

**Comment by FanFanFantastic** [comment]
大家有类似的情况吗，还是现在GFW升级了v2ray已经不稳定了

**Comment by EsunR** [comment]
同样的情况，应该是谷歌云的问题吧，azure云的服务器还算稳定，只会偶尔断线很快就会重连上，谷歌云一断就是好久

**Comment by crazypeace** [comment]
[连接 V2Ray Websocket + TLS 模式服务器的过程及如何排错 Troubleshoot](https://zelikk.blogspot.com/2022/04/connect-v2ray-websocket-tls-troubleshoot.html)

[安装 V2ray Websocket + TLS 模式 排错 Troubleshoot](https://zelikk.blogspot.com/2022/04/setup-v2ray-websocket-tls-troubleshoot.html)
