### ISSUE TITLE
谷歌访问时好时坏

### ISSUE THREAD

**Issue by DynamesC** [233boy/v2ray#884]
服务器用的搬瓦工的CN2GIA，协议是WS+TLS。浏览器访问谷歌时好时坏，其他netflix, youtube等网站长期能连接只有谷歌有的时候会持续十几分钟连不上。访问不了google的时候试过ssh连接到服务器以后ping google.com，是可以的，但是本地浏览器还是无法访问

**Comment by crazypeace** [comment]
你访问google.com的时候，让DNS走VPS去解析。
其实所有被墙的域名，都应该走VPS做DNS解析。

**Comment by DynamesC** [comment]
> 你访问google.com的时候，让DNS走VPS去解析。 其实所有被墙的域名，都应该走VPS做DNS解析。

不是特别理解，能不能展开讲讲或者分享一些相关资料呢，谢谢!

**Comment by crazypeace** [comment]
V2rayNG的这个设置
![微信图片_20220620010838](https://user-images.githubusercontent.com/665889/174492537-f948427c-9a6e-43ff-95ae-9d17eacb3e84.jpg)

**Comment by Aruelius** [comment]
可以参考这个：https://github.com/v2ray/v2ray-core/issues/3019

**Comment by DynamesC** [comment]
> v2ray/v2ray-core#3019

已经按照这个issue下面的建议修改了，尝试几天看看，感谢！

**Comment by VoiceBeer** [comment]
@DynamesC 想问下大佬是否有解决
