### ISSUE TITLE
阿里云香港服务器装一键v2ray  无法使用

### ISSUE THREAD

**Issue by codemonkey1** [233boy/v2ray#885]
是阿里云限制了吗？同样的配置腾讯云香港服务器可以

**Comment by Root-1404** [comment]
把日志调出来看看哪里出错

**Comment by crazypeace** [comment]
> 是阿里云限制了吗？同样的配置腾讯云香港服务器可以

 一般从防火墙上面找原因. 端口开放了没有.
还有一个可能是云服务商监测进程不让运行v2ray

**Comment by YAKUNAMAKAKA** [comment]
> > 是阿里云限制了吗？同样的配置腾讯云香港服务器可以
> 
> 一般从防火墙上面找原因. 端口开放了没有. 还有一个可能是云服务商监测进程不让运行v2ray

被检测了的进程怎么办呀

**Comment by Allenleila** [comment]
> 

阿里云没有检测v2ray进程

**Comment by willemswang** [comment]
需要在防火墙开放指定端口：
云厂商控制台 -> 进入实例 -> 点击防火墙 -> 添加规则 -> 输入端口（来自配置v2ray的端口） -> 确认

**Comment by KingBright** [comment]
我的阿里云

运行：
v2ray start
结果：
V2Ray 已启动

运行：
v2ray status
结果：
V2Ray 状态: 未在运行  /  Caddy 状态: 正在运行

目前看起来像是运行起来马上被kill了

**Comment by KingBright** [comment]
> 

更新...

通过 ps -ef | grep v2ray 看到如下信息
nobody   20306     1  0 13:55 ?        00:00:00 /usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json
root     20422 19841  0 14:04 pts/0    00:00:00 grep --color=auto v2ray

我不太确定是我机器上之前装过v2ray导致出了问题，还是阿里云搞的鬼，还是这个脚本的问题。从现象上看就是调用了错误的v2ray可执行文件，且配了一个错误的config文件，我自己手动调用了 /usr/bin/v2ray/v2ray run -config /etc/v2ray/config.json &

再查看v2ray status 就可以了，并且客户端测试通过。

**Comment by crazypeace** [comment]
1. 你可以修改service文件里关于执行的那一行命令，改成你可以正常跑起来的那一句
2. service跑不起来，而你当前用户可以跑起来，常常是因为用户权限的关系。粗暴一点的修改呢，就把service里的用户改成你当前能执行那一行命令的用户，我猜是root.
