### ISSUE TITLE
甲骨文arm慎用这个脚本安装websocket+tls，会变砖

### ISSUE THREAD

**Issue by woyjuq** [233boy/v2ray#888]
连接节点会造成内核崩溃，机器失联

**Comment by crazypeace** [comment]
你试试这个极简梯子？
https://github.com/crazypeace/V2ray_VLESS_WebSocket_TLS_CaddyV2
这个一键脚本超级简单。有效语句11行(其中BBR 5行, 安装V2Ray 1行, 安装Caddy 5行)+Caddy配置文件15行(其中你需要修改4行)+V2Ray配置文件89行(其中你需要修改2行), 其它都是用来检验小白输入错误参数或者搭建条件不满足的。
你如果不放心开源的脚本，你可以自己执行那11行有效语句，再修改104行配置文件中的6行，也能达到一样的效果。
