### ISSUE TITLE
是不是finalshell关了之后服务就会终止？

### ISSUE THREAD

**Issue by JnhyeLee** [233boy/v2ray#890]
我是finalshell关了就连不上了。所以如果想一直翻需要保持电脑开机+ssh运行么

**Comment by crazypeace** [comment]
你要把v2ray配置成服务
然后用 service v2ray start运行在后台。这样就不怕终端连接断开了。

找篇好一点的教程。

**Comment by JnhyeLee** [comment]
好的！十分感谢
