### ISSUE TITLE
v2rayN 自建vmess节点导入v2rayN电脑客户端之后更新一直失败 没有网速 右下角也显示没有网速的提示 不知道问题在哪

### ISSUE THREAD

**Issue by Sadcrazy** [233boy/v2ray#892]

**Comment by crazypeace** [comment]
推荐你两个排错的教程

第一次装就不成功看这个
https://zelikk.blogspot.com/2022/04/setup-v2ray-websocket-tls-troubleshoot.html

别人能用你不能用看这个
https://zelikk.blogspot.com/2022/04/connect-v2ray-websocket-tls-troubleshoot.html

**Comment by Sadcrazy** [comment]
谢谢大佬 我现在换木马了 成功了 应该是我的服务器IP被墙了 还有端口没打开

**Comment by fanrecy** [comment]
你好请问你怎么解决的我也是自建vmess没有网。我vps的系统用的linux debian 11x64的，用的是Xshell7  搭建的v2ray.   url生成成功后上不了网。ip地址ping是通的，求助！！！谢谢

**Comment by crazypeace** [comment]
自建vmess不通大概率是因为系统时间未校准。

**Comment by BruceWayne2099** [comment]
> 自建vmess不通大概率是因为系统时间未校准。

是的，我就是突然不好使了，发现PC端的时间跟互联网的时间差了几分钟，调整回来就好了
