### ISSUE TITLE
A unified platform for anti-censorship. 这个错误有怎么修复呢？

### ISSUE THREAD

**Issue by buuuuuuuuu** [233boy/v2ray#894]
配置成功
[] [Vmess] 8.210.46.199(8***199:31742)
启动服务(2022/6/26 4:49:08)...
Xray 1.5.6 (Xray, Penetrates Everything.) Custom (go1.18.2 windows/386)
A unified platform for anti-censorship.
2022/06/26 04:49:08 [Info] infra/conf/serial: Reading config: C:\Users\bu\Downloads\v2rayN-Core\config.json
2022/06/26 04:49:09 [Warning] core: Xray 1.5.6 started
2022/06/26 04:52:20 127.0.0.1:62264 accepted //safebrowsing.googleapis.com:443 [http -> direct]

**Comment by buuuuuuuuu** [comment]
是因为 A unified platform for anti-censorship. 错误而导致的连不上吗？

**Comment by crazypeace** [comment]
> A unified platform for anti-censorship.

你翻译一下这句话是啥意思。

**Comment by buuuuuuuuu** [comment]
> > A unified platform for anti-censorship.
> 
> 你翻译一下这句话是啥意思。

问题找到了，阿里云香港的服务器的问题，得换个服务器
