### ISSUE TITLE
安装完成，端口开放，就是不能连接翻墙

### ISSUE THREAD

**Issue by wildlily980** [233boy/v2ray#895]
小火箭无法连通，显示超时，ping IP正常。
用的是oracle的实例，centos 7
给个思路？
防火墙已经开放全部协议
`netstat -antl

Active Internet connections (servers and established)

Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN
tcp        0     64 10.0.0.150:22           xxxxxxx:4062     ESTABLISHED
tcp6       0      0 :::52266                :::*                    LISTEN
tcp6       0      0 :::61579                :::*                    LISTEN
tcp6       0      0 :::111                  :::*                    LISTEN
tcp6       0      0 :::22                   :::*                    LISTEN
tcp6       0      0 ::1:25                  :::*                    LISTEN
`
52266, 61579是翻墙端口
谢谢各位关注，非时间校正问题，非防火墙问题，是必须指定tcp4，而默认是tcp6

**Comment by 1440674806** [comment]
是不是时间不对  校正一下时间

**Comment by crazypeace** [comment]
你看一下是不是VPS商在web面板上还有一个防火墙

**Comment by LINAICAI** [comment]
@wildlily980 请问具体要怎么修改

**Comment by Peixin-Wu** [comment]
那如何把tp6改成tp4呢
