### ISSUE TITLE
如何自定义一个index.html页面？

### ISSUE THREAD

**Issue by zxq2233** [233boy/v2ray#90]
通过ws+tls+caddy搭建
打开域名之后页面显示Bad Request，
我修改过了/etc/caddy/Caddyfile文件，设置了网页文件路径，重启后依然显示Bad Request

**Comment by myworksfun** [comment]
同样求解！

**Comment by 233boy** [comment]
@zxq2233 
脚本直接就能设置，`v2ray config` 更改伪装地址，然后你输入一个网址就可以了，直接反代。
不要直接去更改 caddy 的配置文件。

**Comment by napm** [comment]
问题已经解决，见 #144 回答
