### ISSUE TITLE
无法修改伪装域名

### ISSUE THREAD

**Issue by yangkailungit** [233boy/v2ray#900]
![image](https://user-images.githubusercontent.com/45474289/178456387-a7e77be4-d993-4ff5-aa1d-4163cfd36ce3.png)
伪装域名修改提示这个，能绕过TLS 配置吗 ？ 我只想改个伪装域名，因为旧域名到期了

**Comment by crazypeace** [comment]
我干脆自己动手改配置文件。

https://zelikk.blogspot.com/2022/05/v2ray-websocket-tls-caddy-path-data-flow.html

修改域名之前，新域名把CDN关掉。
修改VPS上的配置文件，把新域名写进去。
caddy跑起来以后，再把CDN打开。
