### ISSUE TITLE
建议增加禁止domain_check的方法

### ISSUE THREAD

**Issue by honeyshine75** [233boy/v2ray#902]
目前想要更换域名，操作时提示 ping: invalid option -- '4'
实际上输入的域名正确，而且也配置了正确的ip

建议增加 禁止domain_check 的方法，以在用户保证的情况下能正常配置

**Comment by crazypeace** [comment]
> 目前想要更换域名，操作时提示 ping: invalid option -- '4' 实际上输入的域名正确，而且也配置了正确的ip
> 
> 建议增加 禁止domain_check 的方法，以在用户保证的情况下能正常配置

我干脆自己动手改配置文件。

https://zelikk.blogspot.com/2022/05/v2ray-websocket-tls-caddy-path-data-flow.html

修改域名之前，新域名把CDN关掉。
修改VPS上的配置文件，把新域名写进去。
caddy跑起来以后，再把CDN打开。

**Comment by honeyshine75** [comment]
按照你说的确实是可以，新域名可以生效。但是你的生效之后v2ray插件立面的配置信息跟着更新吗？插件里面显示的配置信息还是未更新之前的，您知道如何让v2ray插件信息更新吗

**Comment by crazypeace** [comment]
我就自己用，不管那个插件管理界面啥的。

其实梯子不出事就一直用，不要老是动来动去。

我现在v2rayN还在用3.29
