### ISSUE TITLE
浏览器访问经常性ERR_CONNECTION_CLOSED，每次要重启服务端恢复

### ISSUE THREAD

**Issue by liangzhenduo0608** [233boy/v2ray#907]
最近把服务端版本更新了，顺便换了新的域名、证书和uuid，从此之后就经常性的突然打不开网页了，浏览器报ERR_CONNECTION_CLOSED，每次都是重启服务端才能恢复，有时恢复几分钟就又打不开了
看了服务日志都是
```2022/07/25 19:28:14 127.0.0.1:44600 accepted tcp:www.google.com:443 [direct]```
这种也没看到什么异常
能想到的改动就是换了域名证书，tls禁用了v1.0和v1.1，客户端强制开启了证书校验，别的就没什么改动了，请大佬看看怎么回事

**Comment by crazypeace** [comment]
说实话 也只有把你改了的一项一项改回去 测试效果
