### ISSUE TITLE
现在反代网站的功能不能用了？

### ISSUE THREAD

**Issue by charure** [233boy/v2ray#908]
websocket+tls
如果不设置伪装网站一切正常 但是一旦设置伪装网站，就连不上了。

>  6. 修改 分流的路径 (如果可以)
> 
>   7. 修改 伪装的网址 (如果可以)
> 
>   8. 关闭 网站伪装 和 路径分流 (如果可以)
>  

只能关闭网站伪装和路径分流才能正常使用。

**Comment by charure** [comment]
启用伪装后：
systemctl status caddy

caddy.service: Main process exited
Failed to start Caddy.

**Comment by crazypeace** [comment]
来试试这个极简的一键脚本
有效语句11行(其中BBR 5行, 安装V2Ray 1行, 安装Caddy 5行)+Caddy配置文件15行(其中你需要修改4行)+V2Ray配置文件89行(其中你需要修改2行), 其它都是用来检验小白输入错误参数或者搭建条件不满足的。

你如果不放心开源的脚本，你可以自己执行那11行有效语句，再修改104行配置文件中的6行，也能达到一样的效果。

https://github.com/crazypeace/V2ray_VLESS_WebSocket_TLS_CaddyV2

**Comment by Drc0rp** [comment]
遇到里类似的问题。重装vps（debian11）后安装脚本，选择33（VLESS+websocket+tls），在选择伪装网站之后caddy就跑不起来。显示的错误信息里有效内容如下：


localhost.localdomain caddy[727]: {"level":"warn","ts":16***3,"msg":"**No files matching import glob pattern","pattern":"sites/*"**}
localhost.localdomain caddy[727]: run: adapting config using caddyfile: parsing caddyfile tokens for 'reverse_proxy': /etc/caddy/Caddyfile:2 - **Error during parsing: for now, URLs for proxy upstreams only support scheme, host, and port components**
localhost.localdomain systemd[1]: caddy.service: Main process exited, code=exited, status=1/FAILURE
localhost.localdomain systemd[1]: Failed to start Caddy.
localhost.localdomain systemd[1]: caddy.service: Unit entered failed state.
localhost.localdomain systemd[1]: caddy.service: Failed with result 'exit-code'.
Exit code: 3

看起来似乎caddyfile的写法有误。

**Comment by crazypeace** [comment]
来换个脚本试试
https://github.com/crazypeace/V2ray_VLESS_WebSocket_TLS_CaddyV2
