### ISSUE TITLE
关于vemss和ss协议同时开启的问题

### ISSUE THREAD

**Issue by xunqiuhuiyi** [233boy/v2ray#91]
萌新学习中 请问下 我使用一键脚本配置好了vemss和ss协议 在使用的时候 我是否可以同时使用vemss和ss？
比如 我PC使用vemss协议  手机使用ss（9.33IOS没有支持vemss的软件） 同时使用 是否会影响? 特征是否太明显会被墙 谢谢

**Comment by aglent** [comment]
可以同时使用的 走不同端口

**Comment by 233boy** [comment]
@xunqiuhuiyi 
可以同时使用，使用 v2ray ss 即可配置 SS 使用。
是否会不会被墙看脸
