### ISSUE TITLE
阿里云 context deadline exceeded

### ISSUE THREAD

**Issue by herowhdl** [233boy/v2ray#910]
安卓手机安装最新版无法使用

**Comment by htzhenggz** [comment]
我的也是一样，手机和电脑也一样，不知道怎么回事，之前也一直好好用着的。方便加个微信交流一下吗？

**Comment by htzhenggz** [comment]
我的微信是：13044294424

**Comment by crazypeace** [comment]
之前 用得好好的，那就和旧版本呗~ 
翻墙没问题别乱动。
https://github.com/crazypeace/v2ray

**Comment by htzhenggz** [comment]
> 之前 用得好好的，那就和旧版本呗~ 翻墙没问题别乱动。 https://github.com/crazypeace/v2ray

可以加一下你微信咨询一下吗？

**Comment by crazypeace** [comment]
> > 之前 用得好好的，那就和旧版本呗~ 翻墙没问题别乱动。 https://github.com/crazypeace/v2ray
> 
> 可以加一下你微信咨询一下吗？

不好意思，我没有微信。
