### ISSUE TITLE
配置好v2ray后，ping 显示timeout, TCping 显示timeout, 是怎么回事？

### ISSUE THREAD

**Issue by htzhenggz** [233boy/v2ray#911]
配置好v2ray后，ping 显示timeout, TCping 显示timeout, 是怎么回事？

**Comment by crazypeace** [comment]
你确定在配置v2ray之前 这两个是好的吗？

**Comment by htzhenggz** [comment]
> 

是阿，之前一直用的很好的，突然就不行了。

**Comment by crazypeace** [comment]
那你现在给VPS重装系统 ，应该也是好的喽？

**Comment by htzhenggz** [comment]
> 那你现在给VPS重装系统 ，应该也是好的喽？

重装也是没有用。

**Comment by crazypeace** [comment]
> > 那你现在给VPS重装系统 ，应该也是好的喽？
> 
> 重装也是没有用。

我确认一下，你重装了系统，ping 显示timeout, TCping 显示timeout, 对吧？
那就是你的VPS 的IP 被墙了呀。 
你用ping.pe 第三方检测一下？

**Comment by htzhenggz** [comment]
> 

IP 检测确实是被封了，怎么解决？

**Comment by htzhenggz** [comment]
> > > 那你现在给VPS重装系统 ，应该也是好的喽？
> > 
> > 
> > 重装也是没有用。
> 
> 我确认一下，你重装了系统，ping 显示timeout, TCping 显示timeout, 对吧？ 那就是你的VPS 的IP 被墙了呀。 你用ping.pe 第三方检测一下？

IP 检测确实是被封了，怎么解决？

**Comment by crazypeace** [comment]
没啥办法。找VPS商客服发工单换IP吧，一般要钱。

或者你踩个梯子也能SSH连上去操作。

然后你套着CDN使用梯子，也不是不能用。如果是口袋里比较穷的，就将就着用吧。
