### ISSUE TITLE
修改配置，会重置config.json配置文件

### ISSUE THREAD

**Issue by Skyellbin** [233boy/v2ray#913]
修改配置，会重置config.json配置文件，如果在配置文件中配置过v2ray多用户，会被重置，导致其他用户无法上网。

**Comment by AskedYORK** [comment]
请问下怎么配置多个用户，然后设置路由功能？我有三个机器，分别时香港，印度，美国，想从香港出去，两个用户分别走印度和美国，一个用户走香港这样
