### ISSUE TITLE
腾讯云香港服务器一键搭建后无法链接

### ISSUE THREAD

**Issue by zhangweibo123** [233boy/v2ray#914]
服务器是腾讯云的香港服务器。客户端v2rayNG V1.7.3
一键搭建的V2ray 生成代码后 从剪切板一键导入
连接成功，但是无法联网。安卓 pc都无法联网。
![Screenshot_20220819_110216_com v2ray ang](https://user-images.githubusercontent.com/24311876/185535585-5d4831a0-b751-4279-bf95-7642dc6139b7.jpg)

**Comment by zhangweibo123** [comment]
防火墙 端口号 已经开放

**Comment by YAKUNAMAKAKA** [comment]
> 防火墙 端口号 已经开放

估计进程被官方查封了

**Comment by zhangweibo123** [comment]
> 



> 

我又买了一台阿里云的服务器，同样一键安装脚本。仍然无法联通

**Comment by zhangweibo123** [comment]
> > 防火墙 端口号 已经开放
> 
> 估计进程被官方查封了

我又买了一台阿里云的香港服务器，同样一键安装v2ray 仍然在客户端无法联网

**Comment by Skyellbin** [comment]
记得关闭防火墙

**Comment by neo-no93** [comment]
最近也一直无法连接

**Comment by LienRow** [comment]
的确，用的其他云是没问题，搭建ssr是可以的

**Comment by lifangzheng** [comment]
1. 网络的出站和入站相关端口放行（所有协议、任意源、所有目的地）
2. 换传输协议（默认TCP，可换KCP）
3. 重启软件
4. 重启系统
5. 重新创建虚拟机
6. 换朵云
7. 花钱上网
