### ISSUE TITLE
服务器上安装完成启动失败

### ISSUE THREAD

**Issue by amazingyur** [233boy/v2ray#915]
![image](https://user-images.githubusercontent.com/111621343/185725464-b4c667e6-8f2b-4675-878f-02cc314f5187.png)
使用脚本一键安装完成之后启动失败

**Comment by Skyellbin** [comment]
v2ray status   看一下是否已经启动

**Comment by feiya1314** [comment]
我也是这样
![image](https://user-images.githubusercontent.com/19203880/186680953-f387fd76-0932-4b89-87fa-8f1c29508e00.png)

**Comment by feiya1314** [comment]
我这边的问题应该是systemctl  v2ray.service启动服务有问题，service v2ray start 没有拉起来，我手动 执行 nohup /usr/bin/env v2ray.vmess.aead.forced=false /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json & 就好了

**Comment by crazypeace** [comment]
只搭 vmess+tcp 模式？
https://github.com/crazypeace/V2ray_Vmess_TCP

只搭websocket模式？
https://github.com/crazypeace/V2ray_VLESS_WebSocket_TLS_CaddyV2
