### ISSUE TITLE
BUG: 更新V2RAYN-V5.32 出现443反馈

### ISSUE THREAD

**Issue by Echo310** [233boy/v2ray#916]
求助，V2RAYN  版本 V5.32
无法连接上外网，
A. 系统代理：清除系统代理
路由设置：whitelist，
域名解析策略：AsIs，
具体反馈如下
启动服务(2022/8/25 21:55:10)...
Xray 1.5.6 (Xray, Penetrates Everything.) Custom (go1.18.2 windows/386)
A unified platform for anti-censorship.
2022/08/25 21:55:10 [Info] infra/conf/serial: Reading config: C:\Users\Administrator\Desktop\v2rayN-Core\config.json
2022/08/25 21:55:10 [Warning] core: Xray 1.5.6 started

B. 系统代理：自动配置系统代理
反馈如下：
配置成功
[] [VMess] JMS-471231@c72s4.jamjams3.net:30962(45***120:30962)
启动服务(2022/8/25 21:59:04)...
Xray 1.5.6 (Xray, Penetrates Everything.) Custom (go1.18.2 windows/386)
A unified platform for anti-censorship.
2022/08/25 21:59:05 [Info] infra/conf/serial: Reading config: C:\Users\Administrator\Desktop\v2rayN-Core\config.json
2022/08/25 21:59:05 [Warning] core: Xray 1.5.6 started
2022/08/25 21:59:08 127.0.0.1:33851 accepted //beacons.gvt2.com:443 [http -> block]
2022/08/25 21:59:08 127.0.0.1:33852 accepted //beacons.gvt2.com:443 [http -> block]
2022/08/25 21:59:28 127.0.0.1:33889 accepted //ssl.gstatic.com:443 [http -> direct]
2022/08/25 21:59:28 127.0.0.1:33891 accepted //beacons.gcp.gvt2.com:443 [http -> block]
2022/08/25 21:59:28 127.0.0.1:33892 accepted //beacons.gcp.gvt2.com:443 [http -> block]
2022/08/25 21:59:28 127.0.0.1:33893 accepted //beacons.gcp.gvt2.com:443 [http -> block]
2022/08/25 21:59:28 127.0.0.1:33894 accepted //beacons.gcp.gvt2.com:443 [http -> block]
2022/08/25 21:59:28 127.0.0.1:33895 accepted //beacons.gvt2.com:443 [http -> block]
2022/08/25 21:59:28 127.0.0.1:33896 accepted //beacons.gvt2.com:443 [http -> block]
2022/08/25 21:59:28 127.0.0.1:33897 accepted //beacons.gvt2.com:443 [http -> block]
2022/08/25 21:59:28 127.0.0.1:33898 accepted //beacons.gvt2.com:443 [http -> block]
2022/08/25 21:59:28 127.0.0.1:33899 accepted //beacons2.gvt2.com:443 [http -> block]
2022/08/25 21:59:28 127.0.0.1:33900 accepted //beacons2.gvt2.com:443 [http -> block]
2022/08/25 21:59:28 127.0.0.1:33901 accepted //beacons2.gvt2.com:443 [http -> block]
2022/08/25 21:59:28 127.0.0.1:33902 accepted //beacons2.gvt2.com:443 [http -> block]
2022/08/25 21:59:28 127.0.0.1:33903 accepted //beacons3.gvt2.com:443 [http -> block]
2022/08/25 21:59:28 127.0.0.1:33904 accepted //beacons3.gvt2.com:443 [http -> block]
2022/08/25 21:59:28 127.0.0.1:33905 accepted //beacons3.gvt2.com:443 [http -> block]
2022/08/25 21:59:28 127.0.0.1:33906 accepted //beacons3.gvt2.com:443 [http -> block]
2022/08/25 21:59:28 127.0.0.1:33907 accepted //beacons4.gvt2.com:443 [http -> block]
2022/08/25 21:59:28 127.0.0.1:33908 accepted //beacons4.gvt2.com:443 [http -> block]
2022/08/25 21:59:28 127.0.0.1:33909 accepted //beacons4.gvt2.com:443 [http -> block]
2022/08/25 21:59:28 127.0.0.1:33910 accepted //beacons4.gvt2.com:443 [http -> block]
2022/08/25 21:59:28 127.0.0.1:33911 accepted //beacons5.gvt2.com:443 [http -> block]
2022/08/25 21:59:28 127.0.0.1:33912 accepted //beacons5.gvt2.com:443 [http -> block]
2022/08/25 21:59:28 127.0.0.1:33913 accepted //beacons5.gvt2.com:443 [http -> block]
2022/08/25 21:59:28 127.0.0.1:33914 accepted //beacons5.gvt2.com:443 [http -> block]
2022/08/25 21:59:28 127.0.0.1:33915 accepted //beacons5.gvt3.com:443 [http -> proxy]
2022/08/25 21:59:40 127.0.0.1:33937 accepted //ssl.gstatic.com:443 [http -> direct]
2022/08/25 21:59:40 127.0.0.1:33939 accepted //beacons5.gvt3.com:443 [http -> proxy]
2022/08/25 22:00:01 [Warning] [2069001142] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [dial tcp 45.78.53.120:30962: i/o timeout dial tcp 45.78.53.120:30962: operation was canceled] > common/retry: all retry attempts failed
2022/08/25 22:00:13 [Warning] [940853690] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [dial tcp 45.78.53.120:30962: i/o timeout dial tcp 45.78.53.120:30962: operation was canceled] > common/retry: all retry attempts failed

请问要怎么处理这个问题呢？

**Comment by crazypeace** [comment]
不习惯新版本的v2rayN, 可以用老版本的。

这里有一个小改了一下支持VLESS导入导出的 v2rayN v3.29
https://github.com/crazypeace/v2rayN-3.29-VLESS

**Comment by Mcobb880** [comment]
我也是遇到同样的问题

**Comment by Mcobb880** [comment]
具体该怎么操作？ 我目前的版本号是V5.30

**Comment by crazypeace** [comment]
2022/12/12 15:52:23 tcp:127.0.0.1:2793 accepted tcp:www.google.com:443 [proxy]
这一条是说访问google的请求从你本地的v2ray的代理端出去了。

那么接下来就是这个出去的翻墙请求有没有达到你的梯子。

既然你的手机可以正常使得这个梯子，那么就是你公司电脑到梯子之间的问题了。
排错教程：https://zelikk.blogspot.com/2022/04/connect-v2ray-websocket-tls-troubleshoot.html

你可以在你公司的电脑上，用浏览器访问 梯子的域名/梯子的path 看能否得到 400 bad request
https://www.youtube.com/watch?v=13ofpEBUHo0

**Comment by fatherworld** [comment]
maybe update your v2rayN is effect
