### ISSUE TITLE
最近方法4一直无法连接，不知有大佬有解决方案吗

### ISSUE THREAD

**Issue by xiaoshenwl** [233boy/v2ray#918]
一直 Web server is down

**Comment by crazypeace** [comment]
想搭websocket模式，可以换个直接一点的脚本
https://github.com/crazypeace/V2ray_VLESS_WebSocket_TLS_CaddyV2

这个脚本只有这一个模式。

**Comment by apa7** [comment]
+1

**Comment by apa7** [comment]
> 

主要是小火箭不支持vless

**Comment by crazypeace** [comment]
> > 
> 
> 主要是小火箭不支持vless

你用的哪个版本的小火箭shadowrocket 不支持vless？
你是想说 小猫咪clash不支持vless吧？
