### ISSUE TITLE
请问

### ISSUE THREAD

**Issue by xivi1839** [233boy/v2ray#92]
我请教一下，用了站长的脚本，v2ray连接什么是没问题，
但是RaiDrive（https://www.raidrive.com/）
却一直无法连接谷歌空间什么原因？但是可以访问谷歌和油管呀，
换了SSR就可以连接RaiDrive，使用v2ray就不行，有什么办法可以让它连接？

**Comment by 233boy** [comment]
@xivi1839 
这个我也不清楚了

**Comment by xivi1839** [comment]
不用了，我已经找到原因了

**Comment by guohaiping** [comment]
@xivi1839 怎么解决的？能否分享下？
