### ISSUE TITLE
安装成功，但是显示“未在运行”

### ISSUE THREAD

**Issue by suxinjie** [233boy/v2ray#921]
在ubuntu16.04 和 Red Hat 9.3.1-2 上均成功安装，但是状态显示“未在运行“，没有错误输入。

执行脚本：bash <(curl -s -L https://raw.githubusercontent.com/xyz690/v2ray/master/install.sh)

**Comment by suxinjie** [comment]
经过测试，可以用 /usr/bin/v2ray/v2ray run 启动，通过help查看，无法通过 -config指定配置文件。启动默认加载/usr/bin/v2ray/config.json

通过自动化配置后，将配置好的配置文件覆盖到默认位置：
cp /etc/v2ray/config.json /usr/bin/v2ray/

然后通过 /usr/bin/v2ray/v2ray run 启动v2ray即可访问

应该是新版本或者管理脚本没有更新导致的

**Comment by ukhack** [comment]
同样遇到这个问题了，半年前装的脚本正常用。手贱升级了最新版然后寄了。
在一台新服务器上安装了发现也是装好后 不启动，同时还报flag provided but not defined: -version错误。
初步判断应该是脚本安装器有bug，希望作者修复吧

**Comment by daliang1215** [comment]
可以执行 systemctl status v2ray 看到脚本的路径是哪？
```
● v2ray.service - V2Ray Service
     Loaded: loaded (/lib/systemd/system/v2ray.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2022-09-07 16:06:01 CST; 2min 54s ago
       Docs: https://www.v2ray.com/
             https://www.v2fly.org/
   Main PID: 6406 (v2ray)
      Tasks: 9 (limit: 28701)
     Memory: 7.6M
        CPU: 36ms
     CGroup: /system.slice/v2ray.service
             └─6406 /usr/bin/v2ray/v2ray run -config /etc/v2ray/config.json

Sep 07 16:06:01 arm systemd[1]: Started V2Ray Service.
Sep 07 16:06:01 arm env[6406]: V2Ray 5.1.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.19 linux/arm64)
Sep 07 16:06:01 arm env[6406]: A unified platform for anti-censorship.
```
然后将/lib/systemd/system/v2ray.service 文件中的 
`/usr/bin/env v2ray.vmess.aead.forced=false /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json`
改成
`/usr/bin/env v2ray.vmess.aead.forced=false /usr/bin/v2ray/v2ray run -config /etc/v2ray/config.json`
加一个run即可 ，可以直接在命令行里执行一下 
`/usr/bin/env v2ray.vmess.aead.forced=false /usr/bin/v2ray/v2ray run -config /etc/v2ray/config.json`
如果还是报错，例如
`V2Ray 5.1.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.19 linux/arm64)
A unified platform for anti-censorship.
Failed to start: main/commands: failed to load config: [/etc/v2ray/config.json] > infra/conf/v4: failed to parse to outbound detour config. > infra/conf/cfgcommon/loader: unknown config id: mtproto`
直接编辑/etc/v2ray/config.json
将以下内容改一下， 
```
},
		{
			"protocol": "mtproto",
			"settings": {},
			"tag": "tg-out"
		}
		//include_out_config
		//
	],
```
改成
```
}
		//{
		//	"protocol": "mtproto",
		//	"settings": {},
		//	"tag": "tg-out"
		//}
		//include_out_config
		//
	],
```
注意第一个大括号后面的逗号也去掉
然后重启服务就可以了。

**Comment by qsxazcv** [comment]
> 同样遇到这个问题了，半年前装的脚本正常用。手贱升级了最新版然后寄了。 在一台新服务器上安装了发现也是装好后 不启动，同时还报flag provided but not defined: -version错误。 初步判断应该是脚本安装器有bug，希望作者修复吧

我也是 手贱升级了一下 用不了呢 显示没启动

**Comment by vipusername** [comment]
搞了快一天，终于搜到一个可用的了，亲测进去选第一个有效，后面的无效
bash <(curl -sL https://raw.githubusercontent.com/daveleung/hijkpw-scripts-mod/main/xray_mod1.sh)

**Comment by Sanjogahara** [comment]
> 搞了快一天，终于搜到一个可用的了，亲测进去选第一个有效，后面的无效 bash <(curl -sL https://raw.githubusercontent.com/daveleung/hijkpw-scripts-mod/main/xray_mod1.sh)

这个提示
There are no enabled repos.
 Run "yum repolist all" to see the repos you have.
 You can enable repos with yum-config-manager --enable <repo>
应该怎么弄？

**Comment by magicpigxp** [comment]
看样子手贱的人还不少，楼上dalian的兄弟的方法有效

**Comment by pengit2018** [comment]
我用楼上[daliang1215] 的方法不行，报错不一样，先装其它脚本用吧，

**Comment by 233boy** [comment]
@suxinjie 
@ukhack 
@daliang1215 
@Sanjogahara 
@pengit2018 

请使用如下命令修复：
`v2ray update.sh; v2ray restart`

**Comment by pengit2018** [comment]
我是刚更新完然后脚本用不了，之后查了下电报执行v2ray update.sh显示无更新，重启V2也不行，我已经换其它脚本先用，等那天有时间再用回这脚本（主要用SS和S5）

**Comment by 233boy** [comment]
@qsxazcv 
@pengit2018 

再试试看？

请使用如下命令修复：
`v2ray update.sh; v2ray restart`

使用 `v2ray v` 查看一下，看看管理脚本版本是否在 3.60；

如果还是不正常；请再执行如下命令；
`v2ray reload; v2ray restart`

最后，要是还是不行；试试看重装……
`v2ray reinstall`

**Comment by DAarkn** [comment]
我用楼上[daliang1215] 的方法，报错一模一样，但是最后一步直接编辑/etc/v2ray/config.json，他说我没有权限，permission denied，不知道怎么弄了

**Comment by 233boy** [comment]
> 我用楼上[daliang1215] 的方法，报错一模一样，但是最后一步直接编辑/etc/v2ray/config.json，他说我没有权限，permission denied，不知道怎么弄了

@DAarkn 直接重装，v2ray reinstall

**Comment by DAarkn** [comment]
> > 我用楼上[daliang1215] 的方法，报错一模一样，但是最后一步直接编辑/etc/v2ray/config.json，他说我没有权限，permission denied，不知道怎么弄了
> 
> @DAarkn 直接重装，v2ray reinstall

问题已经解决了，我找到原因了，谢谢

**Comment by cuiweipeng** [comment]
> 

这个命令怎么后台运行啊

**Comment by huohu4399** [comment]
> @qsxazcv @pengit2018
> 
> 再试试看？
> 
> 请使用如下命令修复： `v2ray update.sh; v2ray restart`
> 
> 使用 `v2ray v` 查看一下，看看管理脚本版本是否在 3.60；
> 
> 如果还是不正常；请再执行如下命令； `v2ray reload; v2ray restart`
> 
> 最后，要是还是不行；试试看重装…… `v2ray reinstall`

reload 这个可行  一下就好了
