### ISSUE TITLE
是不是都用不了了，这个代码，显示未运行，并且连接失败

### ISSUE THREAD

**Issue by WZL233** [233boy/v2ray#923]
● v2ray.service - V2Ray Service
Loaded: loaded (/lib/systemd/system/v2ray.service; enabled; vendor preset: enabled)
Active: failed (Result: exit-code) since Wed 2022-09-07 23:09:07 CST; 9min ago
Docs: https://www.v2ray.com/
https://www.v2fly.org/
Process: 23193 ExecStart=/usr/bin/env v2ray.vmess.aead.forced=false /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json (code=exited, status=2)
Main PID: 23193 (code=exited, status=2)
CPU: 16ms

Sep 07 23:09:07 ip-172-31-45-215 systemd[1]: v2ray.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Sep 07 23:09:07 ip-172-31-45-215 systemd[1]: v2ray.service: Failed with result 'exit-code'.
Sep 07 23:09:07 ip-172-31-45-215 systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 5.
Sep 07 23:09:07 ip-172-31-45-215 systemd[1]: Stopped V2Ray Service.
Sep 07 23:09:07 ip-172-31-45-215 systemd[1]: v2ray.service: Start request repeated too quickly.
Sep 07 23:09:07 ip-172-31-45-215 systemd[1]: v2ray.service: Failed with result 'exit-code'.
Sep 07 23:09:07 ip-172-31-45-215 systemd[1]: Failed to start V2Ray Service.

**Comment by WZL233** [comment]
日志显示这样
root@ip-172-31-45-215:~# journalctl -u v2ray
-- Journal begins at Wed 2022-09-07 16:11:45 CST, ends at Wed 2022-09-07 23:38:45 CST. --
Sep 07 16:47:28 ip-172-31-45-215 systemd[1]: Started V2Ray Service.
Sep 07 16:47:28 ip-172-31-45-215 env[11301]: flag provided but not defined: -config
Sep 07 16:47:28 ip-172-31-45-215 env[11301]: Usage of /usr/bin/v2ray/v2ray:
Sep 07 16:47:28 ip-172-31-45-215 systemd[1]: v2ray.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Sep 07 16:47:28 ip-172-31-45-215 systemd[1]: v2ray.service: Failed with result 'exit-code'.
Sep 07 16:47:29 ip-172-31-45-215 systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 1.
Sep 07 16:47:29 ip-172-31-45-215 systemd[1]: Stopped V2Ray Service.
Sep 07 16:47:29 ip-172-31-45-215 systemd[1]: Started V2Ray Service.
Sep 07 16:47:29 ip-172-31-45-215 env[11307]: flag provided but not defined: -config
Sep 07 16:47:29 ip-172-31-45-215 env[11307]: Usage of /usr/bin/v2ray/v2ray:
Sep 07 16:47:29 ip-172-31-45-215 systemd[1]: v2ray.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Sep 07 16:47:29 ip-172-31-45-215 systemd[1]: v2ray.service: Failed with result 'exit-code'.
Sep 07 16:47:29 ip-172-31-45-215 systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 2.
Sep 07 16:47:29 ip-172-31-45-215 systemd[1]: Stopped V2Ray Service.
Sep 07 16:47:29 ip-172-31-45-215 systemd[1]: Started V2Ray Service.
Sep 07 16:47:29 ip-172-31-45-215 env[11311]: flag provided but not defined: -config
Sep 07 16:47:29 ip-172-31-45-215 env[11311]: Usage of /usr/bin/v2ray/v2ray:
Sep 07 16:47:29 ip-172-31-45-215 systemd[1]: v2ray.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Sep 07 16:47:29 ip-172-31-45-215 systemd[1]: v2ray.service: Failed with result 'exit-code'.
Sep 07 16:47:29 ip-172-31-45-215 systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 3.
Sep 07 16:47:29 ip-172-31-45-215 systemd[1]: Stopped V2Ray Service.
Sep 07 16:47:29 ip-172-31-45-215 systemd[1]: Started V2Ray Service.
Sep 07 16:47:29 ip-172-31-45-215 env[11315]: flag provided but not defined: -config
Sep 07 16:47:29 ip-172-31-45-215 env[11315]: Usage of /usr/bin/v2ray/v2ray:
Sep 07 16:47:29 ip-172-31-45-215 systemd[1]: v2ray.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Sep 07 16:47:29 ip-172-31-45-215 systemd[1]: v2ray.service: Failed with result 'exit-code'.
Sep 07 16:47:29 ip-172-31-45-215 systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 4.
Sep 07 16:47:29 ip-172-31-45-215 systemd[1]: Stopped V2Ray Service.
Sep 07 16:47:29 ip-172-31-45-215 systemd[1]: Started V2Ray Service.
Sep 07 16:47:29 ip-172-31-45-215 env[11319]: flag provided but not defined: -config
Sep 07 16:47:29 ip-172-31-45-215 env[11319]: Usage of /usr/bin/v2ray/v2ray:
Sep 07 16:47:29 ip-172-31-45-215 systemd[1]: v2ray.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Sep 07 16:47:29 ip-172-31-45-215 systemd[1]: v2ray.service: Failed with result 'exit-code'.
Sep 07 16:47:30 ip-172-31-45-215 systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 5.
Sep 07 16:47:30 ip-172-31-45-215 systemd[1]: Stopped V2Ray Service.
Sep 07 16:47:30 ip-172-31-45-215 systemd[1]: v2ray.service: Start request repeated too quickly.
Sep 07 16:47:30 ip-172-31-45-215 systemd[1]: v2ray.service: Failed with result 'exit-code'.
Sep 07 16:47:30 ip-172-31-45-215 systemd[1]: Failed to start V2Ray Service.
Sep 07 17:14:35 ip-172-31-45-215 systemd[1]: Started V2Ray Service.
Sep 07 17:14:35 ip-172-31-45-215 env[11475]: flag provided but not defined: -config

**Comment by dadnna3633** [comment]
我这也是同样的问题.
v2ray.service: Main process exited, code=exited, status=2/INVALIDARGUMENT 
从昨天下午开始 所有的安装都不行了..

**Comment by WZL233** [comment]
> 我这也是同样的问题. v2ray.service: Main process exited, code=exited, status=2/INVALIDARGUMENT 从昨天下午开始 所有的安装都不行了..

的确啊，昨天下午连续十几个实例都不行，最后用别的脚本可以成功，才知道是这个脚本坏了

**Comment by Hzexiang** [comment]
w

> > 我这也是同样的问题。v2ray.service: 主进程退出, code=exited, status=2/INVALIDARGUMENT 从昨天下午开始所有的安装都行了..
> 
> 确实啊，最后一个实例行，最后一个单独的脚本可以成功了，才知道是这个异常的坏了

什么脚本可以发一下麻烦

**Comment by leeleelee333** [comment]
关键是怎么换脚本呢。。。

**Comment by devilq90** [comment]
> > 我这也是同样的问题. v2ray.service: Main process exited, code=exited, status=2/INVALIDARGUMENT 从昨天下午开始 所有的安装都不行了..
> 
> 的确啊，昨天下午连续十几个实例都不行，最后用别的脚本可以成功，才知道是这个脚本坏了

哪个脚本啊

**Comment by tomphere** [comment]
> > 我这也是同样的问题. v2ray.service: Main process exited, code=exited, status=2/INVALIDARGUMENT 从昨天下午开始 所有的安装都不行了..
> 
> 的确啊，昨天下午连续十几个实例都不行，最后用别的脚本可以成功，才知道是这个脚本坏了

麻烦能提供一下脚本吗？

**Comment by vipusername** [comment]
> ● v2ray.service - V2Ray Service Loaded: loaded (/lib/systemd/system/v2ray.service; enabled; vendor preset: enabled) Active: failed (Result: exit-code) since Wed 2022-09-07 23:09:07 CST; 9min ago Docs: https://www.v2ray.com/ https://www.v2fly.org/ Process: 23193 ExecStart=/usr/bin/env v2ray.vmess.aead.forced=false /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json (code=exited, status=2) Main PID: 23193 (code=exited, status=2) CPU: 16ms
> 
> Sep 07 23:09:07 ip-172-31-45-215 systemd[1]: v2ray.service: Main process exited, code=exited, status=2/INVALIDARGUMENT Sep 07 23:09:07 ip-172-31-45-215 systemd[1]: v2ray.service: Failed with result 'exit-code'. Sep 07 23:09:07 ip-172-31-45-215 systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 5. Sep 07 23:09:07 ip-172-31-45-215 systemd[1]: Stopped V2Ray Service. Sep 07 23:09:07 ip-172-31-45-215 systemd[1]: v2ray.service: Start request repeated too quickly. Sep 07 23:09:07 ip-172-31-45-215 systemd[1]: v2ray.service: Failed with result 'exit-code'. Sep 07 23:09:07 ip-172-31-45-215 systemd[1]: Failed to start V2Ray Service.

我的也是的，同样的脚本以前可以用，最近全部不行，试了好多都用不了，查看v2ray状态：未在运行。是什么原因？

**Comment by 13544171247** [comment]
你试试是不是vps ping不通gitgub.com  我是昨天下午才这样的，问了vps技术，说是昨天github官网发布了公告，但是我的还没恢复

PING github.com (192.30.255.113) 56(84) bytes of data.
^C
--- github.com ping statistics ---

**Comment by aaron5551** [comment]
> 
PING github.com (140.82.112.3) 56(84) bytes of data.
^C
--- github.com ping statistics ---
212 packets transmitted, 0 received, 100% packet loss, time 216045ms

我也是这个情况
要不再等等看吧
请问，github官网的公告在哪看？

**Comment by WZL233** [comment]
知道问题在哪里了，他更新了版本，但是版本号更新错了

## V2Ray 版本: v  /  V2Ray 状态: 未在运行 ##

**Comment by 13544171247** [comment]
> > 
> 
> PING github.com (140.82.112.3) 56(84) bytes of data. ^C --- github.com ping statistics --- 212 packets transmitted, 0 received, 100% packet loss, time 216045ms
> 
> 我也是这个情况 要不再等等看吧 请问，github官网的公告在哪看？

https://www.githubstatus.com/incidents/pz0bvrjx9ztp

**Comment by jason0809** [comment]
> 知道问题在哪里了，他更新了版本，但是版本号更新错了
> 
> ## V2Ray 版本: v / V2Ray 状态: 未在运行

@WZL233 请问有解决办法吗？

**Comment by Yang-Zhuo95** [comment]
vim /usr/lib/systemd/system/v2ray.service

把ExecStart=/usr/bin/env v2ray.vmess.aead.forced=false /usr/bin/v2ray/v2ray config /etc/v2ray/config.json
改成ExecStart=/usr/bin/env v2ray.vmess.aead.forced=false /usr/bin/v2ray/v2ray run config /etc/v2ray/config.json
就是config前面加个run

systemctl daemon-reload
systemctl restart v2ray

**Comment by vipusername** [comment]
> > 知道问题在哪里了，他更新了版本，但是版本号更新错了
> > ## V2Ray 版本: v / V2Ray 状态: 未在运行
> 
> @WZL233 请问有解决办法吗？

https://github.com/233boy/v2ray/issues/923#issuecomment-1240288358
这个可用，进去只能选第一个有效，其它的无效

**Comment by vipusername** [comment]
> > > 知道问题在哪里了，他更新了版本，但是版本号更新错了
> > > ## V2Ray 版本: v / V2Ray 状态: 未在运行
> > 
> > 
> > @WZL233 请问有解决办法吗？
> 
> [#923 (comment)](https://github.com/233boy/v2ray/issues/923#issuecomment-1240288358) 这个可用，进去只能选第一个有效，其它的无效

https://github.com/233boy/v2ray/issues/923#issuecomment-1240288358

> > > 知道问题在哪里了，他更新了版本，但是版本号更新错了
> > > ## V2Ray 版本: v / V2Ray 状态: 未在运行
> > 
> > 
> > @WZL233 请问有解决办法吗？
> 
>bash <(curl -s -L https://github.com/233boy/v2ray/issues/923#issuecomment-1240288358) 这个可用，进去只能选第一个有效，其它的无效
![image](https://user-images.githubusercontent.com/100401526/189058654-eed7a521-678c-4aea-b227-98788e7d0f48.png)

**Comment by shuang669539827** [comment]
> vim /usr/lib/systemd/system/v2ray.service
> 
> 把ExecStart=/usr/bin/env v2ray.vmess.aead.forced=false /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json 改成ExecStart=/usr/bin/env v2ray.vmess.aead.forced=false /usr/bin/v2ray/v2ray run -config /etc/v2ray/config.json 就是config前面加个run
> 
> systemctl daemon-reload systemctl restart v2ray

ok !!!!!

**Comment by qsxazcv** [comment]
> vim /usr/lib/systemd/system/v2ray.service
> 
> 把ExecStart=/usr/bin/env v2ray.vmess.aead.forced=false /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json 改成ExecStart=/usr/bin/env v2ray.vmess.aead.forced=false /usr/bin/v2ray/v2ray run -config /etc/v2ray/config.json 就是config前面加个run
> 
> systemctl daemon-reload systemctl restart v2ray

改了 可以启动了 但是还是连接不了 不知道为什么

**Comment by leeleelee333** [comment]
> 

我是新手，进入这个命令行修改后，请问怎么退出到命令行呢？

**Comment by qsxazcv** [comment]
> > > vim /usr/lib/systemd/system/v2ray.service
> > > 把ExecStart=/usr/bin/env v2ray.vmess.aead.forced=false /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json 改成ExecStart=/usr/bin/env v2ray.vmess.aead.forced=false /usr/bin/v2ray/v2ray run -config /etc/v2ray/config.json 就是config前面加个run
> > > systemctl daemon-reload systemctl restart v2ray
> > 
> > 
> > 改了 可以启动了 但是还是连接不了 不知道为什么
> 
> 大佬我是新手，想问一下这个命令行改完以后怎么退出到能输入systemctl daemon-reload systemctl restart v2ray这行命令的地方呢？

我搞完可以启动 但是连接不了 不知道哪里出问题了

**Comment by Yang-Zhuo95** [comment]
> > > > vim /usr/lib/systemd/system/v2ray.service
> > > > 把ExecStart=/usr/bin/env v2ray.vmess.aead.forced=false /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json 改成ExecStart=/usr/bin/env v2ray.vmess.aead.forced=false /usr/bin/v2ray/v2ray run -config /etc/v2ray/config.json 就是config前面加个run
> > > > systemctl daemon-reload systemctl restart v2ray
> > > 
> > > 
> > > 改了 可以启动了 但是还是连接不了 不知道为什么
> > 
> > 
> > 大佬我是新手，想问一下这个命令行改完以后怎么退出到能输入systemctl daemon-reload systemctl restart v2ray这行命令的地方呢？
> 
> 我搞完可以启动 但是连接不了 不知道哪里出问题了

ip可以正常访问吗? 先ping一下ip

**Comment by leeleelee333** [comment]
> > > > > > vim /usr/lib/systemd/system/v2ray.service
> > > > > > 把ExecStart=/usr/bin/env v2ray.vmess.aead.forced=false /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json 改成ExecStart=/usr/bin/env v2ray.vmess.aead.forced=false /usr/bin/v2ray/v2ray run -config /etc/v2ray/config.json 就是config前面加个run
> > > > > > systemctl daemon-reload systemctl restart v2ray
> > > > > 
> > > > > 
> > > > > 改了 可以启动了 但是还是连接不了 不知道为什么
> > > > 
> > > > 
> > > > 大佬我是新手，想问一下这个命令行改完以后怎么退出到能输入systemctl daemon-reload systemctl restart v2ray这行命令的地方呢？
> > > 
> > > 
> > > ：wq！
> > 
> > 
> > 这是啥意思？输入 wq 和叹号？
> > 左上角ESC
> > 输入 冒号wq
> > :wq

谢啦！

**Comment by qsxazcv** [comment]
> > > > > vim /usr/lib/systemd/system/v2ray.service
> > > > > 把ExecStart=/usr/bin/env v2ray.vmess.aead.forced=false /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json 改成ExecStart=/usr/bin/env v2ray.vmess.aead.forced=false /usr/bin/v2ray/v2ray run -config /etc/v2ray/config.json 就是config前面加个run
> > > > > systemctl daemon-reload systemctl restart v2ray
> > > > 
> > > > 
> > > > 改了 可以启动了 但是还是连接不了 不知道为什么
> > > 
> > > 
> > > 大佬我是新手，想问一下这个命令行改完以后怎么退出到能输入systemctl daemon-reload systemctl restart v2ray这行命令的地方呢？
> > 
> > 
> > 我搞完可以启动 但是连接不了 不知道哪里出问题了
> 
> ip可以正常访问吗? 先ping一下ip

可以的，我就是今天手贱升级了下版本 不行了，启动不了。。

**Comment by CangMang1** [comment]
还是不行。。。还是启动不了

**Comment by AskedYORK** [comment]
> vim /usr/lib/systemd/system/v2ray.service
> 
> 把ExecStart=/usr/bin/env v2ray.vmess.aead.forced=false /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json 改成ExecStart=/usr/bin/env v2ray.vmess.aead.forced=false /usr/bin/v2ray/v2ray run -config /etc/v2ray/config.json 就是config前面加个run
> 
> systemctl daemon-reload systevmctl restart v2ray
还是不行，请问怎么切换到v4.45.2版本，那个版本是可以的

**Comment by Yang-Zhuo95** [comment]
> systemctl daemon-reload
有没有执行
systemctl daemon-reload
或者执行
systemctl status v2ray
看下是什么错误
https://github.com/v2fly/fhs-install-v2ray/issues/243

**Comment by AskedYORK** [comment]
> > systemctl daemon-reload
> > 有没有执行
> > systemctl daemon-reload
> > 或者执行
> > systemctl status v2ray
> > 看下是什么错误
> > [v2fly/fhs-install-v2ray#243](https://github.com/v2fly/fhs-install-v2ray/issues/243)

端口被占用了，原来的服务没有stop掉

**Comment by jwang287** [comment]
用不了

**Comment by Sanjogahara** [comment]
有没有大神输入一下退版本的行命令？

**Comment by 233boy** [comment]
@AskedYORK 
@jason0809 
@lanruo942 
@Sanjogahara 
@WZL233 

请使用如下命令修复：
`v2ray update.sh; v2ray restart`

**Comment by tomphere** [comment]
> v2ray restart

更新之后状态还是启动失败
![image](https://user-images.githubusercontent.com/52732352/189257457-20ec5887-5e90-4e0b-8d9b-7300b8b33d5f.png)

**Comment by 233boy** [comment]
@tomphere 

你执行 `v2ray reload; v2ray restart; v2ray status` 看看

还是不行，重装解决；
`v2ray  reinstall`

**Comment by WZL233** [comment]
> 

好像是系统版本号错了，重装了还是没解决哦

**Comment by aawwsslll** [comment]
因为v2ray核心刚刚才升级到5.0的版本，目前还是不太稳定，在用4.5的不建议这么急着升级。等一两个月后稳定了再说。

**Comment by 233boy** [comment]
> 因为v2ray核心刚刚才升级到5.0的版本，目前还是不太稳定，在用4.5的不建议这么急着升级。等一两个月后稳定了再说。
> 
> 编辑： 新版管理脚本有bug，我没升级v2ray核心，只升级了v2ray管理脚本3.6 现在也报错了

其实得两个都升级才行……我再修一下吧

**Comment by 233boy** [comment]
@aawwsslll 
@WZL233 
你把管理脚本，跟核心版本都升级一下看看；还会不会出错？
`v2ray U; v2ray u; v2ray restart`

**Comment by 233zq** [comment]
![image](https://user-images.githubusercontent.com/113227651/189470877-c2e10c91-2a7d-43d8-a29e-f75d34943e48.png)
这是什么意思，启动不了，官方的安装脚本也这样
