### ISSUE TITLE
@AskedYORK

### ISSUE THREAD

**Issue by CangMang1** [233boy/v2ray#925]
@AskedYORK 
@jason0809 
@lanruo942 
@Sanjogahara 
@WZL233 

请使用如下命令修复：
`v2ray update.sh; v2ray restart`

_Originally posted by @233boy in https://github.com/233boy/v2ray/issues/923#issuecomment-1240973560_

试了不行呀  还是## V2Ray 版本: v  /  V2Ray 状态: 未在运行 ##

**Comment by jason0809** [comment]
重新安装了，可以使用。

**Comment by 233boy** [comment]
@CangMang1 

请使用如下命令修复：
`v2ray update.sh; v2ray restart`

使用 `v2ray v` 查看一下，看看管理脚本版本是否在 3.60；

如果还是不正常；请再执行如下命令；
`v2ray reload; v2ray restart`

最后，要是还是不行；试试看重装……
`v2ray reinstall`

**Comment by aawwsslll** [comment]
@233boy
我只升级管理脚本到3.6.0，结果现在直接报错导致用不了了。v2ray核心还是4.45.2，运行中。错误信息
2022/09/08 15:33:33 [Error] app/dns: failed to retrieve response > Post "https://8.8.8.8/dns-query": context canceled
2022/09/08 21:56:27 [Error] app/dns: failed to retrieve response > Post "https://8.8.8.8/dns-query": context canceled
2022/09/09 09:22:17 [Error] app/dns: failed to retrieve response > Post "https://8.8.8.8/dns-query": context canceled
2022/09/09 09:22:17 [Error] app/dns: failed to retrieve response > Post "https://8.8.8.8/dns-query": context canceled

**Comment by 233boy** [comment]
> @233boy 我只升级管理脚本到3.6.0，结果现在直接报错导致用不了了。v2ray核心还是4.45.2，运行中。错误信息 2022/09/08 15:33:33 [Error] app/dns: failed to retrieve response > Post "https://8.8.8.8/dns-query": context canceled 2022/09/08 21:56:27 [Error] app/dns: failed to retrieve response > Post "https://8.8.8.8/dns-query": context canceled 2022/09/09 09:22:17 [Error] app/dns: failed to retrieve response > Post "https://8.8.8.8/dns-query": context canceled 2022/09/09 09:22:17 [Error] app/dns: failed to retrieve response > Post "https://8.8.8.8/dns-query": context canceled

你直接升级再看看；
执行 `v2ray u`

**Comment by aawwsslll** [comment]
升级5.10之后可以可以用了。
