### ISSUE TITLE
如何在搭建中修改节点名称呢

### ISSUE THREAD

**Issue by willwongup** [233boy/v2ray#927]
请问，如何在搭建时修改节点名称呢？
每次v2ray url 复制导入到shadowrocket节点名称都会出现233v2.com+ip
除了在软件里修改名称，如何快速在搭建中利用脚本修改节点名称呢？

**Comment by 233boy** [comment]
这个暂时不支持，自己手动在软件那边改一下

**Comment by crazypeace** [comment]
> 请问，如何在搭建时修改节点名称呢？ 每次v2ray url 复制导入到shadowrocket节点名称都会出现233v2.com+ip 除了在软件里修改名称，如何快速在搭建中利用脚本修改节点名称呢？

只能是你自己改脚本了。
