### ISSUE TITLE
安装新版后服务能启动，但通过v2ray客户端连接后无法实际访问网络

### ISSUE THREAD

**Issue by cacabebe** [233boy/v2ray#928]
脚本版本
![image](https://user-images.githubusercontent.com/38130849/189666297-f6ab31ed-474b-40ea-ada3-e7090416fdaf.png)
vps连接谷歌
![image](https://user-images.githubusercontent.com/38130849/189666410-5a62c966-f306-433a-ab72-48464279c4ea.png)
配置信息 开始用的tcp协议连接不上，换的kcp也不行
![image](https://user-images.githubusercontent.com/38130849/189666648-18848f82-2f92-497f-8a1a-5b61844999be.png)
客户端测试真连接 测试结果一栏 是超时 我自己用浏览器确实也打不开网页
![image](https://user-images.githubusercontent.com/38130849/189666754-0bb1e37c-7c13-4357-9aee-821a7464a0a4.png)
老版本脚本客户端测试真连接 这个是另外一个服务器上之前配置的老版本脚本，还一直能用
![image](https://user-images.githubusercontent.com/38130849/189666895-1a7e2c69-404f-4d07-9f48-1b3f6245f113.png)
脚本状态
![image](https://user-images.githubusercontent.com/38130849/189667231-1f6eb1ad-c469-41fc-81fa-efaf8a76cf9f.png)
错误日志
![image](https://user-images.githubusercontent.com/38130849/189667376-112d3a1a-01c8-4964-a4e1-665433e2d878.png)
访问日志没有
![image](https://user-images.githubusercontent.com/38130849/189667449-f6e7acf7-c12b-4463-9e13-f5b7c01f5357.png)

大佬们帮忙看看啥原因呀

**Comment by cacabebe** [comment]
脚本状态
![image](https://user-images.githubusercontent.com/38130849/189667147-3e54c92e-fd8d-49a2-b900-c2faf4af822a.png)

**Comment by x3xx1818** [comment]
你客户端版本是最新的吗

**Comment by cacabebe** [comment]
> 你客户端版本是最新的吗

![image](https://user-images.githubusercontent.com/38130849/189821645-0779f4c0-aaae-4a01-b280-cdb2ae706922.png)
是5.34的最新版本，刚在官网下的

**Comment by x3xx1818** [comment]
如果不能用那就重置服务器，然后重新安装脚本

**Comment by doaoso** [comment]
你好你的这个问题解决了吗

**Comment by doaoso** [comment]
> 脚本版本 ![image](https://user-images.githubusercontent.com/38130849/189666297-f6ab31ed-474b-40ea-ada3-e7090416fdaf.png) vps连接谷歌 ![image](https://user-images.githubusercontent.com/38130849/189666410-5a62c966-f306-433a-ab72-48464279c4ea.png) 配置信息 开始用的tcp协议连接不上，换的kcp也不行 ![image](https://user-images.githubusercontent.com/38130849/189666648-18848f82-2f92-497f-8a1a-5b61844999be.png) 客户端测试真连接 测试结果一栏 是超时 我自己用浏览器确实也打不开网页 ![image](https://user-images.githubusercontent.com/38130849/189666754-0bb1e37c-7c13-4357-9aee-821a7464a0a4.png) 老版本脚本客户端测试真连接 这个是另外一个服务器上之前配置的老版本脚本，还一直能用 ![image](https://user-images.githubusercontent.com/38130849/189666895-1a7e2c69-404f-4d07-9f48-1b3f6245f113.png) 脚本状态 ![image](https://user-images.githubusercontent.com/38130849/189667231-1f6eb1ad-c469-41fc-81fa-efaf8a76cf9f.png) 错误日志 ![image](https://user-images.githubusercontent.com/38130849/189667376-112d3a1a-01c8-4964-a4e1-665433e2d878.png) 访问日志没有 ![image](https://user-images.githubusercontent.com/38130849/189667449-f6e7acf7-c12b-4463-9e13-f5b7c01f5357.png)
> 
> 大佬们帮忙看看啥原因呀

你好你的解决了吗

**Comment by x3xx1818** [comment]
你换成KCP协议以后防火墙端口打开了吗

**Comment by cacabebe** [comment]
> 你换成KCP协议以后防火墙端口打开了吗

关闭防火墙之后能用了，谢谢！

**Comment by cacabebe** [comment]
> 你好你的这个问题解决了吗

我使用kcp+dtls协议，配置好后关闭防火墙，能正常使用了

**Comment by wengdajie** [comment]
同样的问题，关闭防火墙是能用了。 但是部署的一些docker容器失效了。 这要咋整

**Comment by x3xx1818** [comment]
关于“docker容器失效”我不是很专业，建议是新开一个贴问下大佬

**Comment by JenryMa** [comment]
我也碰到同样的问题，需要弃用TCP， 用KCP+DTLS吗？

**Comment by x3xx1818** [comment]
我用的是第二个，貌似流量会多损耗一点

**Comment by Gattussolee** [comment]
> 你换成KCP协议以后防火墙端口打开了吗

THANKS!!!!LIFE SAVER!
