### ISSUE TITLE
你客户端版本是最新的吗

### ISSUE THREAD

**Issue by CangMang1** [233boy/v2ray#929]
你客户端版本是最新的吗

_Originally posted by @x3xx1818 in https://github.com/233boy/v2ray/issues/928#issuecomment-1244839047_
求问 最新版 版本号是多少呀

**Comment by x3xx1818** [comment]
电脑版本最新的：https://github.com/2dust/v2rayN  目前我的版本是：5.30
安卓版本最新的：https://github.com/2dust/v2rayNG  目前我的版本是：谷歌商店下载的最新版
复制谷歌商店链接到：https://apps.evozi.com/apk-downloader  可以提取应用安装包（如果你设备没有谷歌商店）
iOS我用的：Shadowrocket（需要外服苹果账号，软件售价2.99美元，可以自己注册账号然后买3美元充值卡购买）
