### ISSUE TITLE
安装成功但是V2RAY状态显示：未在运行

### ISSUE THREAD

**Issue by ktljk123** [233boy/v2ray#930]
![`60A U@W0~J1~5)RR%UF `M](https://user-images.githubusercontent.com/113428233/189860811-b4d4f5e3-a3a0-4aeb-b704-e303a5408ad4.png)

**Comment by 233boy** [comment]
@ktljk123 
输入 systemctl status v2ray 看看

**Comment by ktljk123** [comment]
![QQ图片20220915040338](https://user-images.githubusercontent.com/113428233/190251341-c0012628-8373-4ffc-a9fd-e0acb8bf944e.png)

**Comment by qinlgumt** [comment]
我也遇到这个问题了
![image](https://user-images.githubusercontent.com/113533350/190299571-2595b49e-39e9-4947-819d-a5386861bd71.png)

**Comment by 233boy** [comment]
@qinlgumt 
你这个问题，
请使用如下命令修复：
v2ray update.sh; v2ray u; v2ray restart

**Comment by allyfireshen** [comment]
用了这个命令也不行

**Comment by 233boy** [comment]
@allyfireshen @ktljk123 @qinlgumt 
那就直接重装，v2ray reinstall

**Comment by Ai686Leo** [comment]
> @allyfireshen @ktljk123 @qinlgumt 那就直接重装，v2ray reinstall

不行，😵‍💫

**Comment by Fax9527** [comment]
也出现这个问题了，一周前还没事

**Comment by allyfireshen** [comment]
![image](https://user-images.githubusercontent.com/24688380/190962300-eac8d282-1d5a-4c0d-a1f2-4365cee2722e.png)
修改/etc/systemd/system/v2ray.service这个文件，
将
ExecStart=/usr/bin/v2ray/v2ray  -c /etc/v2ray/config.json
修改为
ExecStart=/usr/bin/v2ray/v2ray run -c /etc/v2ray/config.json
重启v2ray即可科学上网

**Comment by JasonDu007** [comment]
UID过期了，换1个就可以了
