### ISSUE TITLE
站群多ip服务器搭建v2ray不管连接那个ip都是搭建的那个ip

### ISSUE THREAD

**Issue by kevinceacer** [233boy/v2ray#931]
站群多ip服务器搭建v2ray不管连接那个ip都是搭建的那个ip
不会要一个一个装吧？

**Comment by crazypeace** [comment]
自己手动改配置文件

 V2Ray多入口IP多出口IP
理论基础:
https://www.v2ray.com/chapter_02/01_overview.html
搜索listen和sendThrough关键字。
配置文件参考:
https://github.com/v2ray/v2ray-core/issues/2276

**Comment by kevinceacer** [comment]
谢谢了，已经解决了😉

crazypeace ***@***.***> 于2022年9月29日周四 21:42写道：

**Comment by Skobo** [comment]
兄弟你是怎么解决的？我可以出钱请你帮忙解决。有意向你回复我下，skobo090300@hotmail.com

**Comment by kangcwei** [comment]
多ip搭建支持  jjwei886@gmail.com
