### ISSUE TITLE
安装成功了,但是客户端访问外网出现以下提示

### ISSUE THREAD

**Issue by cuiweipeng** [233boy/v2ray#932]
2022/09/14 16:45:11 [Warning] [4201760722] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 45.77.27.212:24702: i/o timeout dial tcp ip:端口: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed

**Comment by RGXMG** [comment]
> > 2022/09/14 16:45:11 [Warning] [4201760722] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 45.77.27.212:24702: i/o timeout dial tcp ip:端口: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed
> 
> failed to process outbound traffic 老哥们有懂的吗

老哥解决了吗？我也是这个问题！
