### ISSUE TITLE
部署的v2ray客户端刚打开能打开油管，然后就加载不出东西了，报错日志如下，大佬帮忙分析下是哪里的问题？

### ISSUE THREAD

**Issue by jfmeng** [233boy/v2ray#933]
2022/09/15 09:44:32 [Warning] proxy/vmess/encoding: Critical Warning: potentially invalid user: a non VMessAEAD connection is received. From 2022 Jan 1st, this kind of connection will be rejected by default. You should update or replace your client software now. This message will not be shown for further violation on this inbound.
2022/09/15 09:44:33 [Warning] [3067981280] app/dispatcher: default route for tcp:www.google.com:80
2022/09/15 09:44:33 [Warning] [3599937934] app/dispatcher: default route for tcp:www.google.com:80
2022/09/15 09:44:33 [Error] app/dns: failed to retrieve response > context canceled
2022/09/15 09:44:33 [Warning] [2489549088] app/dispatcher: default route for tcp:26.26.26.2:853
2022/09/15 09:44:36 [Warning] [2092191812] app/dispatcher: default route for udp:142.250.107.95:443
2022/09/15 09:44:36 [Warning] [2502248807] app/dispatcher: default route for tcp:youtubei.googleapis.com:443
2022/09/15 09:44:36 [Warning] [4234792510] app/dispatcher: default route for tcp:youtubei.googleapis.com:443
2022/09/15 09:44:36 [Warning] [1202963119] app/dispatcher: default route for udp:142.250.107.119:443
2022/09/15 09:44:36 [Warning] [2189742092] app/dispatcher: default route for tcp:i.ytimg.com:443
2022/09/15 09:44:37 [Warning] [3436078275] app/dispatcher: default route for tcp:suggestqueries.google.com:443
2022/09/15 09:44:43 [Warning] [1351392789] app/dispatcher: default route for udp:142.251.33.78:443
2022/09/15 09:44:43 [Warning] proxy/vmess/encoding: Critical Warning: potentially invalid user: a non VMessAEAD connection is received. From 2022 Jan 1st, this kind of connection will be rejected by default. You should update or replace your client software now. This message will not be shown for further violation on this inbound.
2022/09/15 09:44:43 [Warning] [1046958963] app/dispatcher: default route for tcp:redirector.googlevideo.com:443
2022/09/15 09:44:43 [Warning] [163212588] app/dispatcher: default route for tcp:redirector.googlevideo.com:443
2022/09/15 09:44:43 [Warning] [2851562426] app/dispatcher: default route for tcp:redirector.googlevideo.com:443
2022/09/15 09:44:43 [Error] app/dns: failed to retrieve response > Post "https://dns.google/dns-query": context canceled
2022/09/15 09:44:43 [Error] app/dns: failed to retrieve response > Post "https://dns.google/dns-query": context canceled
2022/09/15 09:44:46 [Warning] [1375008342] app/dispatcher: default route for tcp:redirector.googlevideo.com:443
2022/09/15 09:44:46 [Warning] [2189775930] app/dispatcher: default route for tcp:redirector.googlevideo.com:443
2022/09/15 09:44:46 [Warning] [454039728] app/dispatcher: default route for tcp:redirector.googlevideo.com:443

**Comment by crazypeace** [comment]
2022/09/15 09:44:32 [Warning] proxy/vmess/encoding: Critical Warning: potentially invalid user: a non **VMessAEAD** connection is received. From 2022 Jan 1st, this kind of connection will be rejected by default. You should update or replace your client software now. This message will not be shown for further violation on this inbound.
---
你的客户端需要升级。
如果不方便的话，那就在服务器上搭老版本的v2ray
https://github.com/crazypeace/v2ray
