### ISSUE TITLE
设置ws+tls时无法确认本机域名解析

### ISSUE THREAD

**Issue by Cattigrew** [233boy/v2ray#936]
![image](https://user-images.githubusercontent.com/51364432/190988341-476b6bbf-d94a-4d0f-ab79-b19efd6fe68c.png)

ping: invalid option -- '4'

应该是脚本里的ping 命令报错，不知道执行的脚本文件在哪里所以没法debug

**Comment by 233boy** [comment]
@Cattigrew 
是检测域名的时候出错了，在变量 test_domain 那
你可以尝试手动把 test_domain 变量的 ping -4 删除掉

**Comment by channelsray** [comment]
@233boy 改哪个脚本的test_domain，我找个几个脚本改，都没生效

**Comment by crazypeace** [comment]
> 

这里有个一键vless+websocket+tls的脚本，带参数可以跳过检查。
```
bash <(curl -L https://github.com/crazypeace/V2ray_VLESS_WebSocket_TLS_CaddyV2/raw/main/install.sh) 你的域名
```
教程 
https://zelikk.blogspot.com/2022/03/v2ray-vless-websocket-tls-caddy-v2.html
