### ISSUE TITLE
请教 alterID在哪里修改？

### ISSUE THREAD

**Issue by myworksfun** [233boy/v2ray#94]
请问额外ID=233 ，在哪里修改呢？ 没有选项，vi的路径是哪个呢？

**Comment by bigswordCN** [comment]
vi /etc/v2ray/config.json

**Comment by myworksfun** [comment]
thank you ~

bigswordCN <notifications@github.com> 于2019年1月10日周四 上午12:15写道：

**Comment by 78775546946** [comment]
/etc/v2ray/233blog_v2ray_backup.conf，这里的也改一下，要不生成的vmess链接所包含的额外ID还是233

**Comment by fuschenkin** [comment]
用 v2ray ai 命令最好
