### ISSUE TITLE
WS + TLS搭建时明明选择的不是443端口

### ISSUE THREAD

**Issue by willwongup** [233boy/v2ray#944]
WS + TLS搭建时明明选择的不是443端口，为啥一直显示是443端口，修改也修改不了，切换其他协议，改好了端口再变成WS + TLS协议时还是443端口
![微信截图_20221001113026](https://user-images.githubusercontent.com/104425594/193385832-cd1dc829-e356-41f7-962b-c1a3d391982a.png)

**Comment by 233boy** [comment]
@willwongup 
这你不用管的，就是 443 端口的，这是前面套了一层真实的 TLS，所以是 443 端口。
逻辑大概这样：
你 》Caddy （443）》V2 （端口）》网站。

**Comment by weilingwei** [comment]
> @willwongup 这你不用管的，就是 443 端口的，这是前面套了一层真实的 TLS，所以是 443 端口。 逻辑大概这样： 你 》Caddy （443）》V2 （端口）》网站。

连接错误是什么原因

**Comment by hougarry** [comment]
![1664841804241](https://user-images.githubusercontent.com/52512824/193707352-3a081a4c-7791-4359-a83f-72cbff5457db.png)
和你问题一样，也是连接失败

**Comment by lbh159** [comment]
某天同时升级内核脚本后无法使用，提示证书失效。
重置vps后再安装，经测试443端口打开失败
