### ISSUE TITLE
新版本（ v2ray 5.10, 脚本3.6）不能用，能不能退回到老版本？

### ISSUE THREAD

**Issue by JenryMa** [233boy/v2ray#946]
新版本脚本v2ray 5.10 不能用， 另外一个vps用的是v2ray 4.26, 脚本3.34用起来没问题，能否返回旧的脚本？包括旧的 4.x的v2ray版本？

**Comment by 0xJchen** [comment]
老哥方便留下另一个脚本的链接吗

**Comment by 233boy** [comment]
@0xJchen @0xJchen 
能正常使用的，看这里的操作
https://github.com/233boy/v2ray/issues/924

**Comment by JenryMa** [comment]
试过很多次了，都不行。。。
