### ISSUE TITLE
WS+TLS方式安装客户端连接错误，伪装域名能正常显示网页，是https协议

### ISSUE THREAD

**Issue by weilingwei** [233boy/v2ray#947]
WS+TLS按照伪装域名无法连接，伪装域名能正常显示网页，是https协议，但是客户端无法vmess连接，错误。
安装方式1正常
安装方式4 WS+TLS错误，
是什么原因导致的，脚本无法使用了吗

**Comment by cc3941329** [comment]
我这一模一样的问题，关键是我早上还可以用啊

**Comment by weilingwei** [comment]
> 伪装域名能正常显示网页

如果是443端口，伪装域名的https是无法显示的，但是我能正常显示

**Comment by Zhihua-Lee** [comment]
bash <(curl -sL https://raw.githubusercontent.com/daveleung/hijkpw-scripts-mod/main/xray_mod1.sh)
不嫌麻烦可以试试这个脚本？
我的网页也可以正常显示，客户端也配置好了，就是上不去谷歌，ip也是好的
后来用telnet测试端口发现只有443不行，然后我改成其它端口就没问题了

**Comment by cc3941329** [comment]
> 请问下是怎么修改端口的，caddy不是默认绑定443么

**Comment by weilingwei** [comment]
> 
这个脚本不用443端口无法伪装域名，是通过ip+端口通信的 不是域名

**Comment by superchun** [comment]
ping.pe 看一下服务器443端口是不是被block了

**Comment by lbh159** [comment]
> ping.pe 看一下服务器443端口是不是被block了

我重置vps用最新脚本装的，经ping.pe测试443端口确实无法连接（国内外节点都无法连接），请问这是vps厂商干的吗？

**Comment by weilingwei** [comment]
443端口被墙了，还有什么其他方式伪装？ip被禁了就凉了

**Comment by superchun** [comment]
> > 开会且国庆期间，你懂的发自我的 iPhone在 2022年10月4日，下午4:24，lbh159 _**@**_._**> 写道：﻿ ping.pe 看一下服务器443端口是不是被block了 我重置vps用最新脚本装的，经ping.pe测试443端口确实无法连接（国内外节点都无法连接），请问这是vps厂商干的吗？ —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: _**@**_.**_>
> 
> 使用网站 ping.pe 查询ip:443 ， China, Shenzhen failed，所有中国地区全部失败，其他地区全部成功successful，这个是443端口被墙了吗？

是的，我的也是这样，国内都是failed。等吧，过几天应该就会解封了，如果不急用的话，建议还是不折腾了，免得到时ip给折腾没了（我现在就是坐等

**Comment by weilingwei** [comment]
> > > 开会且国庆期间，你懂的发自我的 iPhone在 2022年10月4日，下午4:24，lbh159 _**@**_._**> 写道：﻿ ping.pe 看一下服务器443端口是不是被block了 我重置vps用最新脚本装的，经ping.pe测试443端口确实无法连接（国内外节点都无法连接），请问这是vps厂商干的吗？ —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: _**@**_.**_>
> > 
> > 
> > 使用网站 ping.pe 查询ip:443 ， China, Shenzhen failed，所有中国地区全部失败，其他地区全部成功successful，这个是443端口被墙了吗？
> 
> 是的，我的也是这样，国内都是failed。等吧，过几天应该就会解封了，如果不急用的话，建议还是不折腾了，免得到时ip给折腾没了（我现在就是坐等

嗯，不折腾了，之前的把cf的cdn打开就可以使用了，但是卡的要死。

**Comment by wuxushun** [comment]
我也被封了。。。希望过几天能解封

**Comment by stampidx** [comment]
> > > > 开会且国庆期间，你懂的发自我的 iPhone在 2022年10月4日，下午4:24，lbh159 _**@**_._**> 写道：﻿ ping.pe 看一下服务器443端口是不是被block了 我重置vps用最新脚本装的，经ping.pe测试443端口确实无法连接（国内外节点都无法连接），请问这是vps厂商干的吗？ —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: _**@**_.**_>
> > > 
> > > 
> > > 使用网站 ping.pe 查询ip:443 ， China, Shenzhen failed，所有中国地区全部失败，其他地区全部成功successful，这个是443端口被墙了吗？
> > 
> > 
> > 是的，我的也是这样，国内都是failed。等吧，过几天应该就会解封了，如果不急用的话，建议还是不折腾了，免得到时ip给折腾没了（我现在就是坐等
> 
> 嗯，不折腾了，之前的把cf的cdn打开就可以使用了，但是卡的要死。

我这边走cf的今天也连不上了，主要在能连谷歌的情况下，cf的网站也连不上...wtf

**Comment by wuxushun** [comment]
还没解封，啥时候是个头~

**Comment by superchun** [comment]
> 

估计要等到二十大开完之后？毕竟大选的日子

**Comment by lbh159** [comment]
我现在正好相反，ws+tls方式，但是不能选伪装和路径，否则无法访问。

**Comment by Yanqi7** [comment]
解封了踢我一jio，我也是，我vps还有建站呢，因为搞这个被墙了ip，正常网页也废了
