### ISSUE TITLE
Context deadline exceeded 

### ISSUE THREAD

**Issue by Kiyngra** [233boy/v2ray#948]
Hello everyone
I cant find any sloved way for this error
Anyone can help?

` 3319440536] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://host73959.ml/8snasdr9):  > context deadline exceeded transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://host73959.ml/8snasdr9):  > read tcp 22.186.119.90:55624->164.142.15.126:443: i/o timeout transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://host73959.ml/8snasdr9):  > context deadline exceeded transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://host73959.ml/8snasdr9):  > read tcp 22.186.119.90:55642->164.142.15.126:443: i/o timeout] > common/retry: all retry attempts failed
 `

**Comment by 233boy** [comment]
@Kiyngra 
cant not connect your server, pls try use vmess tcp

**Comment by Kiyngra** [comment]
> @Kiyngra cant not connect your server, pls try use vmess tcp

I get connect with tcp.http finally
But
Only with mobile data
With home wifi i get error : gail detect internet: io:read/write on closed pipe
