### ISSUE TITLE
运行bash命令后无反应

### ISSUE THREAD

**Issue by leeztt** [233boy/v2ray#952]
CentOS 7 运行`bash <(curl -s -L https://git.io/v2ray.sh)`后无反应，请问是怎么回事？
![image](https://user-images.githubusercontent.com/108344557/194327175-868a790c-9af9-4402-89e2-5127a2f9f71b.png)

**Comment by qianlei6148** [comment]
输入命令`bash <(curl -s -L https://git.io/v2ray.sh)`后，应该出现的安装界面，你是安装界面没出现吗？

**Comment by leeztt** [comment]
是的，root下输入命令没反应

**Comment by dujiepeng** [comment]
出现了一样的问题。

**Comment by Wake2020** [comment]
出现了同样问题。

**Comment by chocozhao** [comment]
尝试一下这个。bash <(curl -s -L https://raw.githubusercontent.com/233boy/v2ray/master/install.sh)
