### ISSUE TITLE
我的服务器443端口被墙了，请问如何变更tls默认的443端口

### ISSUE THREAD

**Issue by InkAndHumour** [233boy/v2ray#955]

**Comment by wuxushun** [comment]
CaddyFile 改一下端口

**Comment by jy324** [comment]
https://github.com/XTLS/Xray-core/issues/1237#issue-1396617933
换端口也可能被封，建议开启Cloudflare CDN

**Comment by wuxushun** [comment]
Cloudflare CDN 现在非常慢，感觉现在越来越难了

**Comment by InkAndHumour** [comment]
> CaddyFile 改一下端口
谢谢大佬指点，但是我找了一圈，没找到配置文件在哪里，请问配置文件在哪里呀

**Comment by InkAndHumour** [comment]
> [XTLS/Xray-core#1237 (comment)](https://github.com/XTLS/Xray-core/issues/1237#issue-1396617933) 换端口也可能被封，建议开启Cloudflare CDN
谢谢大佬，也是一个好的解决思路。

**Comment by jy324** [comment]
/etc/caddy/Caddyfile

**Comment by InkAndHumour** [comment]
> 

嘿嘿好的谢谢

**Comment by InkAndHumour** [comment]
> /etc/caddy/Caddyfile

嘿嘿好的谢谢
