### ISSUE TITLE
更新完5.1+3.63后，caddy无法启动，重装系统也没用。

### ISSUE THREAD

**Issue by dbguo** [233boy/v2ray#960]
V2Ray 状态: 正在运行  /  Caddy 状态: 未在运行

root@dbsh:~# systemctl status caddy
● caddy.service - Caddy
   Loaded: loaded (/lib/systemd/system/caddy.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2022-10-12 12:17:33 CST; 9min ago
     Docs: https://caddyserver.com/docs/
  Process: 2427 ExecStart=/usr/local/bin/caddy run --environ --config /etc/caddy/Caddyfile (code=exited, status=1/FAILURE)
 Main PID: 2427 (code=exited, status=1/FAILURE)

Oct 12 12:17:33 dbsh.ml caddy[2427]: SHELL=/bin/sh
Oct 12 12:17:33 dbsh.ml caddy[2427]: INVOCATION_ID=e3ff1dd1459d4da385d320304c5ae5a5
Oct 12 12:17:33 dbsh.ml caddy[2427]: JOURNAL_STREAM=8:17173
Oct 12 12:17:33 dbsh.ml caddy[2427]: {"level":"info","ts":1665548253.6928368,"msg":"using provided configuration","config_file":"/etc/cad
Oct 12 12:17:33 dbsh.ml caddy[2427]: {"level":"warn","ts":1665548253.6931624,"msg":"No files matching import glob pattern","pattern":"sit
Oct 12 12:17:33 dbsh.ml caddy[2427]: run: adapting config using caddyfile: parsing caddyfile tokens for 'reverse_proxy': /etc/caddy/Caddy
Oct 12 12:17:33 dbsh.ml systemd[1]: caddy.service: Main process exited, code=exited, status=1/FAILURE
Oct 12 12:17:33 dbsh.ml systemd[1]: Failed to start Caddy.
Oct 12 12:17:33 dbsh.ml systemd[1]: caddy.service: Unit entered failed state.
Oct 12 12:17:33 dbsh.ml systemd[1]: caddy.service: Failed with result 'exit-code'.

**Comment by dbguo** [comment]
刚发现是不能反代伪装域名，不然caddy就无法启动~~

**Comment by hmf17** [comment]
@dbguo 请问v2ray5.1能使用吗，昨天我的服务也中断了，更换服务器也没有奏效

**Comment by dbguo** [comment]
> @hmf17 @dbguo 更新一下脚本，你再查看设置伪装网站能够正常运行 [c8583eb](https://github.com/233boy/v2ray/commit/c8583eb6017397a9b5873f6fe0097fdc15935e60)

谢谢回复，我在更新3.64管理脚本之后，反代伪装已正常。
