### ISSUE TITLE
download-caddy.sh脚本错误

### ISSUE THREAD

**Issue by VeddySama** [233boy/v2ray#963]
这里使用了错误得caddy版本,原脚本中得版本为/v2.6.1/caddy_2.6.2
```shell
local caddy_download_link="https://github.com/caddyserver/caddy/releases/download/v2.6.1/caddy_2.6.2_linux_${caddy_arch}.tar.gz"
```

实际应为/v2.6.2/caddy_2.6.2
```shell
local caddy_download_link="https://github.com/caddyserver/caddy/releases/download/v2.6.2/caddy_2.6.2_linux_${caddy_arch}.tar.gz"
```

**Comment by xiangsanliu** [comment]
同款错误

> --2022-10-14 14:45:41--  https://github.com/caddyserver/caddy/releases/download/v2.6.1/caddy_2.6.2_linux_amd64.tar.gz
Resolving github.com (github.com)... 20.27.177.113
Connecting to github.com (github.com)|20.27.177.113|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-10-14 14:45:41 ERROR 404: Not Found.

**Comment by VeddySama** [comment]
> 

临时解决办法
```shell
# 将sh脚本保存
wget https://git.io/v2ray.sh
# 给与脚本权限
chmod 777 v2ray
```
新增一段代码即可临时解决
![image](https://user-images.githubusercontent.com/49411287/195781051-fb52e119-a847-42f9-838f-fdd01fe33353.png)

**Comment by 233boy** [comment]
@xiangsanliu @VeddySama 
好吧我写 BUG了，没注意看，更新一下 脚本就行，v2ray update.sh
#964
