### ISSUE TITLE
用的网上的一键部署，查询状态一直都是未运行

### ISSUE THREAD

**Issue by ksmoove2019** [233boy/v2ray#966]
查询的地址：https://linuxword.com/?p=8635
报错信息：
tail: cannot open ‘/var/log/v2ray/error.log’ for reading: No such file or directory
tail: no files remaining

**Comment by ksmoove2019** [comment]
用这个部署，报错
bash <(curl -sL https://raw.githubusercontent.com/hijkpw/scripts/master/centos_install_v2ray.sh)
错误：
Archive:  /tmp/v2ray/v2ray.zip
  inflating: /usr/bin/v2ray/geosite.dat  
  inflating: /usr/bin/v2ray/geoip.dat  
  inflating: /usr/bin/v2ray/v2ray    
caution: filename not matched:  v2ctl
Failed to copy V2Ray binary and resources.

**Comment by dbguo** [comment]
别人家的脚本为什么会问到这里来。。。
