### ISSUE TITLE
tls似乎无法搭建了

### ISSUE THREAD

**Issue by enomiya** [233boy/v2ray#968]
现在搭建ws+tls发现已经不行了，搭建完毕后伪装网站上不去。感觉像是伪装网站搭建的部分出了啥情况？

**Comment by enomiya** [comment]
补充一下，没有开伪装，vless-ws-tls，试了几次都不行，神奇的是，之前用这种办法搭好的服务器一点问题都没有。

**Comment by enomiya** [comment]
补充一下，没有开伪装，33的vless-ws-tls还有4的搭建，试了几次都不行，神奇的是，之前用这种办法搭好的服务器一点问题都没有。证书的问题？

**Comment by 233boy** [comment]
@enomiya 直接重装看看，v2ray reinstall

**Comment by enomiya** [comment]
自行解决了，不清楚是不是脚本跑的途中出了什么状况，重头搭起来发现莫名其妙好了。

**Comment by yueyagou** [comment]
> 自行解决了，不清楚是不是脚本跑的途中出了什么状况，重头搭起来发现莫名其妙好了。

咋解决的？
