### ISSUE TITLE
请问有没有办法禁止访问某些网页?

### ISSUE THREAD

**Issue by hucs2542** [233boy/v2ray#97]
例如我不希望用代理来看视频,我想屏蔽youtube

**Comment by xyqyear** [comment]
https://toutyrater.github.io/basic/routing/

**Comment by kanseavegs** [comment]
使用配置就可以实现，在服务端编辑config.json文件，在outbounding配置里面添加：

`"routing": {
    "rules": [
	  {
        "type": "field",
        "domain": [
           "bilibili.com",
		   "*.hdslb.com",
           "*.bilibili.com",
		   "youtube.com",
		   "*.youtube.com",
		   "www.baidu.com",
		   "*.baidu.com",
		   "www.ipip.net",
		   "tiktok.com",
		   "*.tiktok.com",
		   "coursera.org",
		   "spark.kanseaveg.xyz",
		   "reddit.com",
		   "*.reddit.com"
        ],
        "outboundTag": "blocked"
      },
      {
        "type": "field",
        "inboundTag": [
          "VLESS-in"
        ],
        "outboundTag": "direct"
      }
    ]`


具体可以参见[https://toutyrater.github.io/basic/routing/notice.html](文档)
