### ISSUE TITLE
换了好几个服务器服务商主机，都是状态未运行

### ISSUE THREAD

**Issue by FranciscoJorgeH** [233boy/v2ray#972]
![ZK{JP)`5Z1(_2WV%IBV3CXL](https://user-images.githubusercontent.com/116419489/197324534-717715c5-a321-4c68-b7b9-2efd69b0618b.png)
换了好几个服务器服务商主机，都是状态未运行

**Comment by featherwit001** [comment]
遇到了同样的问题

**Comment by 233boy** [comment]
@featherwit001 @PaulSpears111 
直接重装看看，v2ray reinstall
这是因为新版本的 V2Ray，启动方式变了，没做兼容，然后大家更新到新版本都挂了。

**Comment by PaulSpears111** [comment]
> 变

请求开发者做下兼容，不然折腾死我们小白了，哈哈😂

**Comment by PaulSpears111** [comment]
重装了也不行，大师能让我们退回之前的版本嘛？😢

**Comment by 233boy** [comment]
@featherwit001 @PaulSpears111 
卸载后，执行这个
```bash
bash <(curl -sL https://git.io/v2ray.sh) online old
```

**Comment by PaulSpears111** [comment]
> @featherwit001 @PaulSpears111 卸载后，执行这个
> 
> ```shell
> bash <(curl -sL https://git.io/v2ray.sh) online old
> ```

好了，可以连上了，谢谢大神 👍

**Comment by carlosxuchun** [comment]
BWH的IP被封，换vultr 的Debian 11 x64 (bullseye)，安装新版本无法启动，于是安装博主推荐的“bash <(curl -sL https://git.io/v2ray.sh) online old”旧版本。旧版本安装可以启动，但在win客户端V2ray N V5.35版本下无法连接到服务器(老版本V2.48也无法连接），用站长工具扫描端口一直显示未开启。以上方法尝试过多次也未成功。麻烦博主分析下是什么原因。谢谢@233boy

**Comment by carlosxuchun** [comment]
> @featherwit001 @PaulSpears111 卸载后，执行这个
> 
> ```shell
> bash <(curl -sL https://git.io/v2ray.sh) online old
> ```

BWH的IP被封，换vultr 的Debian 11 x64 (bullseye)，安装新版本无法启动，于是安装博主推荐的“bash <(curl -sL https://git.io/v2ray.sh) online old”旧版本。旧版本安装可以启动，但在win客户端V2ray N V5.35版本下无法连接到服务器(老版本V2.48也无法连接），用站长工具扫描端口一直显示未开启。以上方法尝试过多次也未成功。麻烦博主分析下是什么原因。谢谢@233boy

**Comment by PaulSpears111** [comment]
> 

我电脑可以链接，下午去公司看看版本号告诉你。

**Comment by PaulSpears111** [comment]
> 版

我电脑用的2.23可以上

**Comment by PaulSpears111** [comment]
bash <(curl -sL https://git.io/v2ray.sh) online old
这个有的主机可以，有的不可以 😭
我觉得之前那个233一键安装的4.44版本，最完美，从来没出问题，大神可以给个脚本么？🙏

**Comment by PaulSpears111** [comment]
Ubuntu 19 完美运行，显示版本号，运行状态，上网速度也快 👏

**Comment by PaulSpears111** [comment]
Ubuntu 19 完美运行，显示版本号 5.1.0，运行状态，上网速度也快 👏

**Comment by PaulSpears111** [comment]
又遇到个奇怪的问题，用新版233帮同事搭建的，自己电脑手机用都没问题
只要同事用电脑新版(可以变颜色的)v2ray的4.29版本一链接就死掉，重启vps也不得行，只有卸载vps里的重新搭建才可以上，好奇怪呀。

**Comment by carlosxuchun** [comment]
root@vultr:~# ss -tunlp| grep v2ray
udp   UNCONN 0      0                                      *:45262            *:*    users:(("v2ray",pid=838,fd=3)) 

@233boy 应该是服务器所有的端口都封了，用端口查看，发现出了22端口，其他端口都没回应

**Comment by carlosxuchun** [comment]
@PaulSpears111 估计和服务器端口被封有关，BWH的IP被封。VULTR的端口被封，最近不知道怎么回事

**Comment by PaulSpears111** [comment]
> @PaulSpears111 估计和服务器端口被封有关，BWH的IP被封。VULTR的端口被封，最近不知道怎么回事

发生了好几次，只要他一链接，瞬间灭了，无论哪个设备都再也连不上，重装了就可以，下午发现这个问题了叫他不要用他那个电脑版的连接了，然后一直都好好的了。好奇怪。
我在想是不是他的客户端是被改过的，只能用他们线路，因为以前他是从卖VPN的那里下载的v2。

**Comment by carlosxuchun** [comment]
@PaulSpears111 应该是敏感时期，对于做开发的人来说没网真的累

**Comment by PaulSpears111** [comment]
> 

嗯，恼火

**Comment by chakbun** [comment]
😭 一直用v字头的服务商，周五开始完全挂了，选了好几个主机重装都不行。
大佬们现在有什么方案吗？

**Comment by FranciscoJorgeH** [comment]
> 

我用的v字头的还好呀。
