### ISSUE TITLE
脚本配置成功了，1 2 3 4 种协议全试过了，配置成功复制vmess url 但是连不上网...

### ISSUE THREAD

**Issue by NarcissusAleo** [233boy/v2ray#973]
脚本配置成功了，1 2 3 4 种协议全试过了，配置成功复制vmess url 但是连不上网...不知道咋回事儿， 新换的vps地址

**Comment by 233boy** [comment]
@NarcissusAleo 配置一个ss 看看；v2ray ss

**Comment by NarcissusAleo** [comment]
v2ray ss 这个咋配置的QAQ

**Comment by 233boy** [comment]
> v2ray ss 这个咋配置的QAQ

@NarcissusAleo 直接服务器输入 v2ray ss

**Comment by gistest1** [comment]
同样的情况，v2ray运行正常，但是无法上网，ss也没用

**Comment by xieruiyin** [comment]
一样，有大佬知道怎么解决么

**Comment by crazypeace** [comment]
安装 V2Ray Websocket + TLS 模式 排错指引
 (https://zelikk.blogspot.com/2022/04/setup-v2ray-websocket-tls-troubleshoot.html)

连接 V2Ray Websocket + TLS 模式的过程 及 排错指引
(https://zelikk.blogspot.com/2022/04/connect-v2ray-websocket-tls-troubleshoot.html)
