### ISSUE TITLE
突然不能用了，重置后仍不能使用

### ISSUE THREAD

**Issue by Designxiaozai** [233boy/v2ray#975]
大家有这个问题麽，之前用的一直好好的 
启动也正常，就是无法使用
最近有更新版本麽

**Comment by 233boy** [comment]
@Designxiaozai 装旧版本看看
```
v2ray uninstall
bash <(curl -sL https://git.io/v2ray.sh) online old
```

**Comment by Designxiaozai** [comment]
试了 也是不行。

**Comment by dongfeng555** [comment]
> @Designxiaozai 装旧版本看看
> 
> ```
> v2ray uninstall
> bash <(curl -sL https://git.io/v2ray.sh) online old
> ```

旧版本可以用，多谢！

**Comment by zhangh1014** [comment]
> @Designxiaozai 装旧版本看看
> 
> ```
> v2ray uninstall
> bash <(curl -sL https://git.io/v2ray.sh) online old
> ```

我也是突然不能用了，卸载后装这个就按本可以，为什么呢？

**Comment by NarcissusAleo** [comment]
> v2ray uninstall
> bash <(curl -sL https://git.io/v2ray.sh) online old

试了也不行，用的是websocket+tls..脚本最近出小问题了吗

**Comment by Designxiaozai** [comment]
试了好久可以了 就是好慢呀

**Comment by NarcissusAleo** [comment]
> 试了好久可以了 就是好慢呀

你脚本选的哪个模式，我还是不行QAQ

**Comment by shpxhk** [comment]
我也遇到哎..啥情况...

**Comment by Designxiaozai** [comment]
@233boy  您好，今天旧版本也不能用了。

**Comment by NarcissusAleo** [comment]
tcping测试，一直timeout，v2ray运行正常，脚本业务报错，一开代理就全局断网，xshell联通确认没有连接访问，就是代理服务器貌似没成

**Comment by NarcissusAleo** [comment]
tcping测试，一直timeout，v2ray运行正常，脚本也没报错，一开代理就全局断网，xshell联通确认没有连接访问问题，就是代理服务器貌似没成

**Comment by peace-dove** [comment]
请教一下，现在我的服务器甚至不能ssh连接，控制台检查端口等都没有问题，这种一般是什么情况呢。

**Comment by NarcissusAleo** [comment]
> 

不能ssh连接是不是ip被ban了

**Comment by 233boy** [comment]
@shpxhk @Designxiaozai @peace-dove 
检测一下是不是 IP 被墙了，到这里
https://www.itdog.cn/ping/

**Comment by peace-dove** [comment]
确实被墙了，请问解决方案是不是只有更换ip或者换一个服务器。
请问仅使用这个v2ray自动脚本搭建的是不是被墙的风险比较高，是不是需要其他措施。
@233boy @NarcissusAleo

**Comment by shpxhk** [comment]
> 
我是全新的ip,使用最新版本部署完毕之后不能使用,然后使用old那个版本才可以用

**Comment by shpxhk** [comment]
想问下大神...old版本对应的tag是哪个..我fork下...

**Comment by NarcissusAleo** [comment]
> > 
> 
> 我是全新的ip,使用最新版本部署完毕之后不能使用,然后使用old那个版本才可以用
我旧的脚本都用不了，也是新换的一个vps，脚本没问题，v2ray运行状态正常，但就是连不上网，tcping测试超时。老哥，你咋配的old版

**Comment by shpxhk** [comment]
> > > 
> > 
> > 
> > 我是全新的ip,使用最新版本部署完毕之后不能使用,然后使用old那个版本才可以用
> > 我旧的脚本都用不了，也是新换的一个vps，脚本没问题，v2ray运行状态正常，但就是连不上网，tcping测试超时。老哥，你咋配的old版

v2ray uninstall
bash <(curl -sL https://git.io/v2ray.sh) online old

能不能用.来反馈下

**Comment by peace-dove** [comment]
> > 
> 
> 我是全新的ip,使用最新版本部署完毕之后不能使用,然后使用old那个版本才可以用

我直接无法ssh服务器，没法配置
@shpxhk

**Comment by shpxhk** [comment]
> > > 
> > 
> > 
> > 我是全新的ip,使用最新版本部署完毕之后不能使用,然后使用old那个版本才可以用
> 
> 我直接无法ssh服务器，没法配置 @shpxhk

被干掉了,换IP吧

**Comment by DEEMO101** [comment]
> > > > 
> > > 
> > > 
> > > 我是全新的ip,使用最新版本部署完毕之后不能使用,然后使用old那个版本才可以用
> > > 我旧的脚本都用不了，也是新换的一个vps，脚本没问题，v2ray运行状态正常，但就是连不上网，tcping测试超时。老哥，你咋配的old版
> 
> v2ray uninstall bash <(curl -sL https://git.io/v2ray.sh) online old
> 
> 能不能用.来反馈下
无法使用，能启动部署，但是无法使用

**Comment by UMRzcz-831** [comment]
> @shpxhk @Designxiaozai @peace-dove 检测一下是不是 IP 被墙了，到这里 https://www.itdog.cn/ping/

更换IP后还是
![ip banned](https://user-images.githubusercontent.com/52395980/197744545-35f5b6ae-d5ff-49f5-aecf-129f2eaf9781.jpg)

是不是凉了

**Comment by tcas2570** [comment]
我的也是突然不能用了，ip和域名都是通的，删了安装那个online old 版本也不行

**Comment by NarcissusAleo** [comment]
> 

情况一样的，部署都正常，就是没网

**Comment by carlosxuchun** [comment]
最近估计都是封端口或者封IP,bwh直接封了ip, VULTR除了22端口，其他全封。换了多个IP和地区都不好使

**Comment by NarcissusAleo** [comment]
> 最近估计都是封端口或者封IP,bwh直接封了ip, VULTR除了22端口，其他全封。换了多个IP和地区都不好使

那也不至于，我刚申请的vps，然后直接配置脚本，然后就没网，这么迅速吗

**Comment by bbc117** [comment]
一样的情况，kcp可以用但tls、xtls用不了其他，基本上只要需要网址的协议都用不了

**Comment by taincheng** [comment]
二十大前一天失效了，换了新的vps，ping ip、域名都通，安装部署正常，就是无法使用

**Comment by yunsheng-hawk** [comment]
> @Designxiaozai 装旧版本看看
> 
> ```
> v2ray uninstall
> bash <(curl -sL https://git.io/v2ray.sh) online old
> ```

亲测有效

**Comment by beilove** [comment]
> @Designxiaozai装旧版本看
> 
> ```
> v2ray uninstall
> bash <(curl -sL https://git.io/v2ray.sh) online old
> ```

用了旧版本后，过了一晚上又不能用了

**Comment by SpencerXyj** [comment]
折腾好久就是连不上  centos换装了Ubuntu 就好了....奇怪
