### ISSUE TITLE
VPS两个IP，怎么选择另外一个

### ISSUE THREAD

**Issue by moonsbtt** [233boy/v2ray#977]
VPS两个IP，一个能用，一个被墙。

装VLESS WS TLS， 要域名解析IP，但是脚本提示的IP是不能用的那个， 怎么修改成能用的那个IP

**Comment by 233boy** [comment]
@moonsbtt 不用修改，直接配置就行，搞定了之后，你在客户端配置那边，地址那栏，把域名改成你的另外一个 IP 就行了

**Comment by crazypeace** [comment]
> 

这个脚本带域名参数执行可以跳过IP检测部分
https://github.com/crazypeace/v2ray_wss
