### ISSUE TITLE
@carlosxuchun

### ISSUE THREAD

**Issue by carlosxuchun** [233boy/v2ray#978]
@carlosxuchun 
你看看 V2 有没有在监听端口，执行命令如下
`ss -tunlp| grep v2ray`

如果有在监听端口，证明在运行，那就可能是防火墙的问题了

_Originally posted by @233boy in https://github.com/233boy/v2ray/issues/972#issuecomment-1290097929_
      

root@vultr:~# ss -tunlp| grep v2ray
udp   UNCONN 0      0                                      *:45262            *:*    users:(("v2ray",pid=838,fd=3)) 

应该是我服务器所有的端口都被封了

**Comment by 233boy** [comment]
@carlosxuchun 你这个只有 UDP 监听，你看看切换一下协议，v2ray config
换成 TCP 看看，然后检测一下有没有监听上端口
