### ISSUE TITLE
443端口被封，改配置文件后caddy监听还是443，改端口失败

### ISSUE THREAD

**Issue by ak58100** [233boy/v2ray#979]
用脚本搭好的v2ray突然连不上网，排错之后发现443端口被墙了，所以就想把443端口换掉。

协议用的是VLESS_WebSocket_TLS。我因为比较小白，只知道改端口是在配置文件里改，但是/etc/v2ray文件夹里有三个配置文件：一个233blog_v2ray_backup.conf，按这个文件的内容提示，这个配置文件应该是不需要改的；第二个配置文件是233blog_v2ray_config.json，这个文件第九行是443端口，所以我就把这里的443换成了65535端口；第三个配置文件是config.json，我在网络上搜到的改端口教程，提到的是改config.json，但是我打开这个配置文件后，发现里面没有443相关的内容，也就没有改动这个

所以我就是把233blog_v2ray_config.json里的443端口给改了，但是改完之后，我重启v2ray，执行netstat -tunlp，发现65535端口没有开启，仍然是443端口在监听。

而且netstat -tunlp执行的结果显示，443端口对应的是caddy。因为我比较小白，也不知道这里的caddy是做什么的，所以我就又搜索了一下，似乎是443被墙之后，还需要改caddy的配置文件，但我的/etc/caddy文件夹里并没有config.json配置文件。

研究了一下午和一晚上，还是没搞懂443端口到底怎么在配置文件里换成其他端口，所以求教233boy大佬，或者其他大佬，希望能解决掉换端口的问题

**Comment by 233boy** [comment]
@ak58100 
因为真实的 TLS （HTTPS）就是要 443 端口实现的，你改 V2 端口没有用，除非 你不用 TLS 相关。

我不知道你能不能理解，简单逻辑：
你》443(CADDY ) 》V2

这个 443 不是 V2 监听的，是 CADDY，CADDY 接收到数据后再转发到 V2。

这也是为什么你打开 config.json 没有 443 端口的原因，因为不是 V2 在监听 443 端口；并且那个 233blog_v2ray_config.json 是给客户端用的，这里改了也没有什么用，服务器用的是 config.json。

解决方案：
由于 443 不能用了，你肯定无法使用 TLS 相关的协议，所以只能换协议，虽然换协议理论上是可用了，但是可能会上升到直接封 IP；最近墙有点高数丈，反正被封 端口 甚至 被封 IP 的人太多了。

但如果你还是想要用 TLS 的，可以尝试套一下 cloudflare，这样也不用担心 IP 被封，只是速度超级慢；

**Comment by NarcissusAleo** [comment]
> 

怎么排查的老哥，我也想排查一下我的端口

**Comment by ak58100** [comment]
> @ak58100 因为真实的 TLS （HTTPS）就是要 443 端口实现的，你改 V2 端口没有用，除非 你不用 TLS 相关。
> 
> 我不知道你能不能理解，简单逻辑： 你》443(CADDY ) 》V2
> 
> 这个 443 不是 V2 监听的，是 CADDY，CADDY 接收到数据后再转发到 V2。
> 
> 这也是为什么你打开 config.json 没有 443 端口的原因，因为不是 V2 在监听 443 端口；并且那个 233blog_v2ray_config.json 是给客户端用的，这里改了也没有什么用，服务器用的是 config.json。
> 
> 解决方案： 由于 443 不能用了，你肯定无法使用 TLS 相关的协议，所以只能换协议，虽然换协议理论上是可用了，但是可能会上升到直接封 IP；最近墙有点高数丈，反正被封 端口 甚至 被封 IP 的人太多了。
> 
> 但如果你还是想要用 TLS 的，可以尝试套一下 cloudflare，这样也不用担心 IP 被封，只是速度超级慢；

感谢233大佬，你讲的整体逻辑我听明白了，我换下协议再试试

**Comment by ak58100** [comment]
> > 
> 
> 怎么排查的老哥，我也想排查一下我的端口

我是用[http://coolaf.com/tool/port](url) 测的IP端口在国是不是开放状态，也可以用[https://tool.chinaz.com/port](url)，然后用[https://www.yougetsignal.com/tools/open-ports/](url)测ip端口在国外的开放状态，如果测出来的ip端口在国内是关闭，但在国外是开放，就说明ip的这个端口被墙了

**Comment by ak58100** [comment]
过233大佬的指点，尝试了换协议和套cloudflare两个方法，确实都是可行的办法，不过目前还是继续用VLESS_WebSocket_TLS + 套cloudflare。

套了cloudflare之后，感觉不同网络运营商似乎有差别，用移动的网络连上v2ray之后很稳，而且跑了下测速，网速没有明显变慢，反而上传网速还比以前好了一些。但换成本地非三大运营商的宽带网络后，就不太行了，经常断连，断连后v2rayNg报错 “失败：context deadline exceeded” 。

**Comment by 233boy** [comment]
@ak58100 移动可能走的香港线路，速度不会很差，其他的走美国，那就速度很差了。建议可以先套 CF 暂时用着先

**Comment by woowalker** [comment]
> 经过233大佬的指点，尝试了换协议和套cloudflare两个方法，确实都是可行的办法，不过目前还是继续用VLESS_WebSocket_TLS + 套cloudflare。
> 
> 套了cloudflare之后，感觉不同网络运营商似乎有差别，用移动的网络连上v2ray之后很稳，而且跑了下测速，网速没有明显变慢，反而上传网速还比以前好了一些。但换成本地非三大运营商的宽带网络后，就不太行了，经常断连，断连后v2rayNg报错 “失败：context deadline exceeded” 。

所以到底咋换443端口？求指教。我也想套个 cloudlfare，但不知道怎么更换 443 端口

**Comment by woowalker** [comment]
突然明白了，应该不用改啥 443 端口，直接套 cloudflare 就行是吧？

**Comment by woowalker** [comment]
@ak58100 想确认一下，443端口已经被封了，直接在原IP上套cloudflare是不是也不行？要必须换一个IP，然后再把域名重新解析到新IP上，然后再套cloudflare才可以？

**Comment by ak58100** [comment]
> @ak58100 想确认一下，443端口已经被封了，直接在原IP上套cloudflare是不是也不行？要必须换一个IP，然后再把域名重新解析到新IP上，然后再套cloudflare才可以？

直接套cloudflare就行了，不过直接套的话，网速大概率会非常慢，你可以看下这个项目[](https://github.com/XIU2/CloudflareSpeedTest)，用这个CloudflareST去选一个最适合你网络的优选IP。

**Comment by NarcissusAleo** [comment]
> 经过233大佬的指点，尝试了换协议和套cloudflare两个方法，确实都是可行的办法，不过目前还是继续用VLESS_WebSocket_TLS + 套cloudflare。
> 
> 套了cloudflare之后，感觉不同网络运营商似乎有差别，用移动的网络连上v2ray之后很稳，而且跑了下测速，网速没有明显变慢，反而上传网速还比以前好了一些。但换成本地非三大运营商的宽带网络后，就不太行了，经常断连，断连后v2rayNg报错 “失败：context deadline exceeded” 。

老哥，你没换ip，就是原来IP套的cloudflare就能用吗。有教程能推荐下吗，我之前好像尝试过套cloudflare也没出网

**Comment by NarcissusAleo** [comment]
电报群是多少呀

**Comment by NarcissusAleo** [comment]
> > > 
> > 
> > 
> > 怎么排查的老哥，我也想排查一下我的端口
> 
> 我是用coolaf.com/tool/port测的IP端口在国内是不是开放状态，也可以用tool.chinaz.com/port，然后用www.yougetsignal.com/tools/open-ports/测ip端口在国外的开放状态，如果你测出来的ip的443端口在国内是关闭，但在国外是开放，就说明ip的这个443端口被墙了

我国内外测试，端口都是关闭的...

**Comment by ak58100** [comment]
> > 经过233大佬的指点，尝试了换协议和套cloudflare两个方法，确实都是可行的办法，不过目前还是继续用VLESS_WebSocket_TLS + 套cloudflare。
> > 套了cloudflare之后，感觉不同网络运营商似乎有差别，用移动的网络连上v2ray之后很稳，而且跑了下测速，网速没有明显变慢，反而上传网速还比以前好了一些。但换成本地非三大运营商的宽带网络后，就不太行了，经常断连，断连后v2rayNg报错 “失败：context deadline exceeded” 。
> 
> 老哥，你没换ip，就是原来IP套的cloudflare就能用吗。有教程能推荐下吗，我之前好像尝试过套cloudflare也没出网

教程很多呀，你去油管上搜一下，波仔，不良林，好多博主都讲过套cloudflare和优选ip

**Comment by ak58100** [comment]
> > > 经过233大佬的指点，尝试了换协议和套cloudflare两个方法，确实都是可行的办法，不过目前还是继续用VLESS_WebSocket_TLS + 套cloudflare。
> > > 套了cloudflare之后，感觉不同网络运营商似乎有差别，用移动的网络连上v2ray之后很稳，而且跑了下测速，网速没有明显变慢，反而上传网速还比以前好了一些。但换成本地非三大运营商的宽带网络后，就不太行了，经常断连，断连后v2rayNg报错 “失败：context deadline exceeded” 。
> > 
> > 
> > 老哥，你没换ip，就是原来IP套的cloudflare就能用吗。有教程能推荐下吗，我之前好像尝试过套cloudflare也没出网
> 
> ip不用动，cloudflare会自动分配，如果你用CloudflareST优选ip了，才需要换。教程很多呀，你去油管上搜一下，波仔，不良林，好多博主都讲过套cloudflare和优选ip

**Comment by Coltonchan** [comment]
> > > > 
> > > 
> > > 
> > > 怎么排查的老哥，我也想排查一下我的端口
> > 
> > 
> > 我是用coolaf.com/tool/port测的IP端口在国内是不是开放状态，也可以用tool.chinaz.com/port，然后用www.yougetsignal.com/tools/open-ports/测ip端口在国外的开放状态，如果你测出来的ip的443端口在国内是关闭，但在国外是开放，就说明ip的这个443端口被墙了
> 
> 我国内外测试，端口都是关闭的...

老哥我也是啊。。。不知道咋办好

**Comment by zhoujingchao** [comment]
> > 经过233大佬的指点，尝试了换协议和套cloudflare两个方法，确实都是可行的办法，不过目前还是继续用VLESS_WebSocket_TLS + 套cloudflare。
> > 套了cloudflare之后，感觉不同网络运营商似乎有差别，用移动的网络连上v2ray之后很稳，而且跑了下测速，网速没有明显变慢，反而上传网速还比以前好了一些。但换成本地非三大运营商的宽带网络后，就不太行了，经常断连，断连后v2rayNg报错 “失败：context deadline exceeded” 。
> 
> 老兄，我的情况和你是一模一样的443端口已被封，但我套CF后，国内外ip和端口测试也都通了，并且手机上的小火箭app也绿了，连通性测试跑的通了，不再是超时。可最后访问google浏览器的时候还是一样无法访问，这就麻了，不知道咋排查了= =

教程已找到：https://github.com/233boy/v2ray/wiki/%E4%BD%BF%E7%94%A8Cloudflare%E4%B8%AD%E8%BD%ACV2Ray%E6%B5%81%E9%87%8F
