### ISSUE TITLE
安装v2ray 后，指定的端口还是TCP国内外均不可用

### ISSUE THREAD

**Issue by colintheunique** [233boy/v2ray#980]
安装过程中，出现fastmirror链接超时，启用cache 镜像：
Could not retrieve mirrorlist http://mirrors.elrepo.org/mirrors-elrepo.el7 error was
12: Timeout on http://mirrors.elrepo.org/mirrors-elrepo.el7: (28, 'Connection timed out after 30001 milliseconds')
 * base: mirror.xeonbd.com
 * elrepo: mirrors.coreix.net
 * epel: repo.extreme-ix.org
 * extras: mirror.xeonbd.com
 * updates: mirror.aktkn.sg
No packages marked for update

Package lrzsz-0.12.20-36.el7.x86_64 already installed and latest version
Package git-1.8.3.1-23.el7_8.x86_64 already installed and latest version
Package zip-3.0-11.el7.x86_64 already installed and latest version
Package unzip-6.0-24.el7_9.x86_64 already installed and latest version
Package curl-7.29.0-59.el7_9.1.x86_64 already installed and latest version
Package wget-1.14-18.el7_6.1.x86_64 already installed and latest version
Package qrencode-3.4.1-3.el7.x86_64 already installed and latest version
Package libcap-2.22-11.el7.x86_64 already installed and latest version
Package jq-1.6-2.el7.x86_64 already installed and latest version
Nothing to do
Cloning into '/tmp/233boy/v2ray'...
remote: Enumerating objects: 89, done.
remote: Counting objects: 100% (89/89), done.
remote: Compressing objects: 100% (59/59), done.
remote: Total 89 (delta 29), reused 68 (delta 27), pack-reused 0
Unpacking objects: 100% (89/89), done.

试过防火墙和vultr配置端口，指定端口还是TCP不可用。
各位大佬帮忙看看什么问题呢？

**Comment by 233boy** [comment]
@colintheunique 换 Ubuntu 系统 试试看吧
