### ISSUE TITLE
🆘 V2Ray 状态: 未在运行

### ISSUE THREAD

**Issue by Joe3019** [233boy/v2ray#981]
........... V2Ray 管理脚本 v3.52 by 233v2 ..........

## V2Ray 版本: v  /  V2Ray 状态: 未在运行 ##

反馈问题: https://github.com/233boy/v2ray/issues

捐助 V2Ray: https://www.v2ray.com/chapter_00/02_donate.html

_______________________________________________________

Activate the web console with: systemctl enable --now cockpit.socket

Last login: Tue Nov  1 17:06:26 2022 from 116.230.60.18
[root@vultr ~]# /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json
flag provided but not defined: -config
Usage of /usr/bin/v2ray/v2ray:
[root@vultr ~]#

**Comment by Joe3019** [comment]
完全看不懂问题是什么，有没有大神指导啊~~

**Comment by jiuyuan-light** [comment]
> 纯纯的小白！完全看不懂问题是什么，有没有大神指导啊~~

新版本的v2ray用/usr/bin/v2ray/v2ray run -c /etc/v2ray/config.json &命令启动

**Comment by 233boy** [comment]
@Joe3019 用旧的版本即可，执行下面命令，先卸载当前版本，再安装旧的版本
```
v2ray uninstall
bash <(curl -sL https://git.io/v2ray.sh) online old
```

**Comment by 233boy** [comment]
@Joe3019 

执行，`systemctl status v2ray`，显示什么错误？

**Comment by MichaelScd** [comment]
> 
● v2ray.service - V2Ray - A unified platform for anti-censorship
     Loaded: loaded (/etc/systemd/system/v2ray.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2022-11-02 21:49:16 CST; 2min 22s ago
       Docs: https://v2ray.com
             https://guide.v2fly.org
    Process: 1172 ExecStart=/etc/v2ray-agent/v2ray/v2ray -confdir /etc/v2ray-agent/v2ray/conf (code=exited, status=2)
   Main PID: 1172 (code=exited, status=2)
        CPU: 15ms

Nov 02 21:49:16 iZj6c9bt871i5t2xcb11ebZ systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 5.
Nov 02 21:49:16 iZj6c9bt871i5t2xcb11ebZ systemd[1]: Stopped V2Ray - A unified platform for anti-censorship.
Nov 02 21:49:16 iZj6c9bt871i5t2xcb11ebZ systemd[1]: v2ray.service: Start request repeated too quickly.
Nov 02 21:49:16 iZj6c9bt871i5t2xcb11ebZ systemd[1]: v2ray.service: Failed with result 'exit-code'.
Nov 02 21:49:16 iZj6c9bt871i5t2xcb11ebZ systemd[1]: Failed to start V2Ray - A unified platform for anti-censorship.

启动命令变了

root@iZj6c9bt871i5t2xcb11ebZ:~# /etc/v2ray-agent/v2ray/v2ray help
A unified platform for anti-censorship.

Usage:

        v2ray <command> [arguments]

The commands are:

        run           run V2Ray with config
        api           call V2Ray API
        convert       convert config files
        test          test config files
        tls           TLS tools
        uuid          generate new UUID
        verify        verify if a binary is officially signed
        version       print V2Ray version

Use "v2ray help <command>" for more information about a command.

Additional help topics:

        config-merge  config merge logic
        format-loader config formats and loading

Use "v2ray help <topic>" for more information about that topic.

**Comment by 233boy** [comment]
@Joe3019 
哎，你是不是装过别的脚本？或者是官方的。。你先卸载别的再安装我的

```
bash <(curl -sL https://git.io/v2ray.sh) online old
```

**Comment by Joe3019** [comment]
***@***.*** ~]# systemctl status v2ray
● v2ray.service - V2Ray Service
   Loaded: loaded (/etc/systemd/system/v2ray.service; enabled; vendor
preset: disabled)
  Drop-In: /etc/systemd/system/v2ray.service.d
           └─10-donot_touch_single_conf.conf
   Active: active (running) since Wed 2022-11-02 17:34:46 CST; 19h ago
     Docs: https://www.v2fly.org/
 Main PID: 15684 (v2ray)
    Tasks: 6 (limit: 12393)
   Memory: 16.2M
   CGroup: /system.slice/v2ray.service
           └─15684 /usr/local/bin/v2ray run -config
/usr/local/etc/v2ray/config.json

Nov 02 17:34:46 vultr.guest systemd[1]: v2ray.service: Succeeded.
Nov 02 17:34:46 vultr.guest systemd[1]: Stopped V2Ray Service.
Nov 02 17:34:46 vultr.guest systemd[1]: Started V2Ray Service.
Nov 02 17:34:46 vultr.guest v2ray[15684]: V2Ray 5.1.0 (V2Fly, a
community-driven edition of V2R>
Nov 02 17:34:46 vultr.guest v2ray[15684]: A unified platform for
anti-censorship.
Nov 02 17:34:46 vultr.guest v2ray[15684]: 2022/11/02 17:34:46 [Warning]
V2Ray 5.1.0 started
lines 1-18/18 (END)

**Comment by Joe3019** [comment]
我就是先卸载。。然后安新的
