### ISSUE TITLE
同《V2Ray 状态: 未在运行》求助！

### ISSUE THREAD

**Issue by t6reep** [233boy/v2ray#983]
........... V2Ray 管理脚本 old-v0.1 by 233v2.com ..........

## V2Ray 版本: v4.45.2  /  V2Ray 状态: **未在运行** ##

**错误日志如下**
`tail: cannot open ‘/var/log/v2ray/error.log’ for reading: No such file or directory
tail: no files remaining`

最近vps的ip被墙了，于是重新配置了下v2ray！
结果发现v2ray重新配置后无法正常连接了。
很疑惑是不是新发的ip是有问题的。
所以试了下ip工具看看到底有没有被墙。虽然发现40/80和默认的SSH端口都能正常连接；但配置好的Vmess和Shadowsoks端口会提示“ICMP可用；TCP不可用（国外线路同提示）”。于是回v2ray脚本里看了下发现《 **V2Ray 状态: 未在运行 ##**》，进入启动选项，手动重启后仍然显示未在运行。

`请选择菜单 [1-11]:8

 1. 启动 V2Ray

 2. 停止 V2Ray

 3. 重启 V2Ray

 4. 查看访问日志

 5. 查看错误日志

请选择 [1-5]:3

 **V2Ray 重启完成**`

请问这种情况是该如何处理呢？

**Comment by t6reep** [comment]
使用systemctl status v2ray后的结果

● v2ray.service - V2Ray Service
   Loaded: loaded (/etc/systemd/system/v2ray.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/v2ray.service.d
           └─10-donot_touch_single_conf.conf
   Active: active (running) since Wed 2022-11-02 23:18:29 CST; 9h ago
     Docs: https://www.v2fly.org/
 Main PID: 1807 (v2ray)
   CGroup: /system.slice/v2ray.service
           └─1807 /usr/local/bin/v2ray run -config /usr/local/etc/v2ray/config.json

**Comment by 233boy** [comment]
@t6reep 
你这是因为装了官方的脚本，然后又装我的脚本，冲突了。
你得先把官方的脚本给卸载了；这是必须的。
然后再执行 `v2ray reinstall`

**Comment by t6reep** [comment]
> @t6reep 你这是因为装了官方的脚本，然后又装我的脚本，冲突了。 你得先把官方的脚本给卸载了；这是必须的。 然后再执行 `v2ray reinstall`

成功了！
把服务器系统重新装了下，然后用`bash <(curl -sL https://git.io/v2ray.sh) online old `
配置成功了！
可能是之前指令装的脚本不适配
`bash <(curl -s -L https://git.io/v2ray-setup.sh)`

**Comment by 5k5k** [comment]
@233boy 
我这里报flag provided but not defined: -version
使用bash <(curl -sL https://git.io/v2ray.sh) online old 好使

**Comment by 233boy** [comment]
@5k5k 因为太多这个运行问题，所以特意弄了一个 old 版本，只能说 v2 官方有点问题，不知道是故意还是有意的，一个简单的兼容却不愿意做。反观 xray 那边就不会出现这种错误。
@t6reep 你之前安装的那个不是我的脚本呀！ 😂

**Comment by BaiShaojie123123** [comment]
> > @t6reep 你这是因为装了官方的脚本，然后又装我的脚本，冲突了。 你得先把官方的脚本给卸载了；这是必须的。 然后再执行 `v2ray reinstall`
> 
> 成功了！ 把服务器系统重新装了下，然后用`bash <(curl -sL https://git.io/v2ray.sh) online old ` 配置成功了！ 可能是之前指令装的脚本不适配 `bash <(curl -s -L https://git.io/v2ray-setup.sh)`

ip容易被封么？用的哪家服务器？

**Comment by xiasummer** [comment]
您好，遇到了相同的问题，但是我连服务器都重装了，但是还是没有用。

 运行 `systemctl status v2ray`
```
● v2ray.service - V2Ray Service
   Loaded: loaded (/etc/systemd/system/v2ray.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/v2ray.service.d
           └─10-donot_touch_single_conf.conf
   Active: active (running) since Mon 2022-11-14 13:51:27 CST; 33s ago
     Docs: https://www.v2fly.org/
 Main PID: 4811 (v2ray)
    Tasks: 7 (limit: 1458)
   CGroup: /system.slice/v2ray.service
           └─4811 /usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json

Nov 14 13:51:27 racknerd-d40aa6 systemd[1]: Started V2Ray Service.
Nov 14 13:51:27 racknerd-d40aa6 v2ray[4811]: V2Ray 4.45.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.18.1 linux/amd64)
Nov 14 13:51:27 racknerd-d40aa6 v2ray[4811]: A unified platform for anti-censorship.
Nov 14 13:51:27 racknerd-d40aa6 v2ray[4811]: 2022/11/14 13:51:27 [Info] main/jsonem: Reading config: /usr/local/etc/v2ray/config.json
Nov 14 13:51:27 racknerd-d40aa6 v2ray[4811]: 2022/11/14 13:51:27 [Warning] V2Ray 4.45.0 started
```

但是此时查看 v2ray status 状态还是未在运行。

请问大神这是怎么回事？

**Comment by 233boy** [comment]
@xiasummer 
你装了官方的脚本版本吧；或者别的；简单点就是继续重新重装一个新的系统；
然后使用这个命令来安装V2
```
bash <(curl -sL https://git.io/v2ray.sh) online old
```

备注，不要执行别的安装命令。

**Comment by xiasummer** [comment]
https://github.com/233boy/v2ray/issues/983#issuecomment-1314801769 
亲测是正确的解决方案。
我也不知道怎么去完全卸载之前安装的服务，所以我重新安装了一个新的 ubuntu 系统，然后重新安装了这个脚本下的服务。目前这个一键配置脚本是正确的，可以正常使用的。

非常感谢楼主的方法。

PS， 我之前安装的版本是 https://www.itblogcn.com/article/406.html 这里提供的方法，但是看起来这个脚本与 online old 的脚本并不相同。

**Comment by shuiwen** [comment]
感谢楼主的解决方法！

**Comment by kumailf** [comment]
如果你使用过官方的安装脚本，你需要先删除干净相关的所有文件，再重新使用脚本安装，否则会造成冲突
下面是我使用的删除命令：
rm -rf /usr/local/bin/v2ray /usr/local/bin/v2ctl /usr/local/share/v2ray/ /etc/systemd/system/v2ray* 

请确认路径输入无误，这很重要，因为使用了rm -rf
