### ISSUE TITLE
安装时，选择ws+tls时，域名解析，能不能不要强制检查

### ISSUE THREAD

**Issue by Nicolas-Gong** [233boy/v2ray#984]
因vps没有ipv4，所以无法解析到IP上，所以导致卡死在这里，而我不想走warp，所以最多只能解析到ipv6，另外解不解析对我的方法而言都无所谓，所以希望能给个不强制检查的选择。
希望大佬脚本上加下或者我可以提交pr

**Comment by 233boy** [comment]
@Nicolas-Gong 
我修复了这个问题，你得更新一下脚本，`v2ray update.sh`
确保版本 v3.66+
然后，你直接增加一个 AAAA 解析到 VPS IP 上就行，
但是强制检查 肯定要检查 的，避免 Caddy 无法跑起来。省事一点，要不然又老有人问为什么不在运行。

commit: https://github.com/233boy/v2ray/commit/ab15bf6f7fe42802aa91ee0a59c4fe8bfb4aa763

**Comment by Nicolas-Gong** [comment]
好的，谢谢大佬了，这样以后就省了走warp刷个IPv4的问题了，只连IPv6更安全些。

**Comment by 233boy** [comment]
@Nicolas-Gong 
你测试一下，看看是否符合如期（由于我没 纯 ipv6 小鸡就无法测试了，但是理论上是没问题的  😂

**Comment by Nicolas-Gong** [comment]
> 

明天上班时我试试，狗东买的SSD今天到了，正在装系统，啥都没有，不好搞。
免费的ipv6的vps 有woiden和hax了解下。

**Comment by Nicolas-Gong** [comment]
> @Nicolas-Gong 你测试一下，看看是否符合如期（由于我没 纯 ipv6 小鸡就无法测试了，但是理论上是没问题的 joy

![image](https://user-images.githubusercontent.com/23067153/199869368-370357d7-4d51-43c1-9557-20309a054741.png)
应该可以了

**Comment by 233boy** [comment]
@Nicolas-Gong 
OK，能跑就行；

**Comment by Nicolas-Gong** [comment]
> @Nicolas-Gong OK，能跑就行；

老哥，还是有问题，当我给IPV6机子刷了IPV4的IP，然后我去用你的脚本安装时，到了解析域名这一步时，你的脚本优先去ping的是ipv6的地址，我是IPV4和IPV6都解析了同一个域名还是过不去，我不管怎么搞都过不去。。。而且你ping出来的ipv6的地址还是不对的，我用其他几个vps ping都试过得到的结果都是CF解析的IPV6正确的地址。

![image](https://user-images.githubusercontent.com/23067153/201011807-1f8cfee1-8dbe-4a5a-b531-ba0fc78db936.png)

**Comment by Nicolas-Gong** [comment]
这里应该做一个前置选择，用户自己选择是IPV6还是IPV4，然后再到这步输入域名，亦或者ping得到的IP只要存在其中一个，都满足通过的条件。

**Comment by Nicolas-Gong** [comment]
刚才又试了下安装，这次ping出来的IPV6的地址是对的了，这个地址我几天前就解析上去了，但是依然过不去，要求是ipv4的ip。。。

**Comment by 233boy** [comment]
@Nicolas-Gong 
脚本优先使用 ipv4 ip，如果机子有 ipv4 就默认使用 ipv4，否则就是使用 ipv6；
你的想法是，假设 VPS 同时有 v4 和 v6；但是不使用 v4 而是使用 v6?

**Comment by Nicolas-Gong** [comment]
@233boy 
       我虽然通过warp刷到了IPV4的地址，但是很多时候这个v4地址是无法使用的，而且ping的时候出来的不会是v4的地址，这时候我已经把v4的地址加上解析了，因为warp上选择了优先v6地址且全局，上图你就看到了。
       我只是尝试先刷了下，然后再去安装你的脚本时发现了这个问题，导致卡这里了，没有路可以走了，只能先把warp关全局了，再安装你的脚本，这时候你的脚本就只提示解析到v6地址了，其实可以不管用户是用的v4还是v6，只要解析一个就可以通过了，如果不想改用户的流程，就在脚本里增加同时获取v4和v6的地址，然后or关系即可。

**Comment by Nicolas-Gong** [comment]
> @Nicolas-Gong 
> 逻辑我明白，但是如果像你这样的，如果检测有 v4 符合就给过，这种情况理论上 caddy 到时候可能会报错；指获取证书

那你看看如何操作兼容下呗。我想了下我这种搭建方法其实没必要有TLS的，直接走ws就好了，毕竟cf自带了TLS了，我应该只需纯走了ws协议就好了，明天搬砖时研究下ws协议试试。

**Comment by 233boy** [comment]
> > @Nicolas-Gong
> > 逻辑我明白，但是如果像你这样的，如果检测有 v4 符合就给过，这种情况理论上 caddy 到时候可能会报错；指获取证书
> 
> 那你看看如何操作兼容下呗。我想了下我这种搭建方法其实没必要有TLS的，直接走ws就好了，毕竟cf自带了TLS了，我应该只需纯走了ws协议就好了，明天搬砖时研究下ws协议试试。

是的，其实不用 TLS，直接监听 80 端口既可；TLS 用 CF 实现，但是脚本弄成一键那样，是为了省事……

**Comment by crazypeace** [comment]
这个脚本带域名参数执行，可以跳过IP的检测部分。
https://github.com/crazypeace/v2ray_wss
