### ISSUE TITLE
运行脚本总是监听IPV6端口

### ISSUE THREAD

**Issue by learn-py-c** [233boy/v2ray#985]
v2ray运行之后总是自动监听IPv6地址（实际没有公网IPV6地址），IPV4的端口不被监听，多次安装之后就会一直处于未运行状态。
233boy4.44版本的脚本哪位大佬还有，这个版本一直没有出过问题

**Comment by 233boy** [comment]
@learn-py-c 
你试试看旧版本？执行下面命令，先卸载当前版本，再安装旧版本
```
v2ray uninstall
bash <(curl -sL https://git.io/v2ray.sh) online old
```

**Comment by learn-py-c** [comment]
> @learn-py-c 你试试看旧版本？执行下面命令，先卸载当前版本，再安装旧版本
> 
> ```
> v2ray uninstall
> bash <(curl -sL https://git.io/v2ray.sh) online old
> ```

不是这个问题，我重装过多次系统（centos7/8），测试过多个脚本都不行。最后更换为ubuntu一次成功。但是客户端拨上之后测试youtube正常，但是netflix.com访问不了，telnet netflix.com 443端口都能通，就是访问不了网站，很奇怪的问题
