### ISSUE TITLE
更新完5.1+3.65后，caddy无法启动，重装系统也没用

### ISSUE THREAD

**Issue by etsb5z** [233boy/v2ray#986]
同 #960 
~# v2ray status

 V2Ray 状态: 正在运行  /  Caddy 状态: 未在运行

~# service caddy restart
Job for caddy.service failed because the control process exited with error code.
See "systemctl status caddy.service" and "journalctl -xe" for details.

**Comment by 233boy** [comment]
@etsb5z 
输入 `systemctl status caddy.service` 看看

**Comment by etsb5z** [comment]
@233boy
~# systemctl status caddy.service
● caddy.service - Caddy
   Loaded: loaded (/lib/systemd/system/caddy.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2022-11-04 14:41:22 CST; 11s ago
     Docs: https://caddyserver.com/docs/
  Process: 3393 ExecStart=/usr/local/bin/caddy run --environ --config /etc/caddy/Caddyfile (code=exited, status=1/FAILURE)
 Main PID: 3393 (code=exited, status=1/FAILURE)

Nov 04 14:41:22 VM-0-14-debian caddy[3393]: USER=root
Nov 04 14:41:22 VM-0-14-debian caddy[3393]: SHELL=/bin/sh
Nov 04 14:41:22 VM-0-14-debian caddy[3393]: INVOCATION_ID=72074724ba5d4c1d9494160235b74df0
Nov 04 14:41:22 VM-0-14-debian caddy[3393]: JOURNAL_STREAM=9:26138
Nov 04 14:41:22 VM-0-14-debian caddy[3393]: {"level":"info","ts":1667544082.7231505,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":""}
Nov 04 14:41:22 VM-0-14-debian caddy[3393]: {"level":"warn","ts":1667544082.72323,"msg":"No files matching import glob pattern","pattern":"sites/*"}
Nov 04 14:41:22 VM-0-14-debian caddy[3393]: Error: adapting config using caddyfile: parsing caddyfile tokens for 'reverse_proxy': /etc/caddy/Caddyfile:2 - Error during parsing: for now, URLs for pro
Nov 04 14:41:22 VM-0-14-debian systemd[1]: caddy.service: Main process exited, code=exited, status=1/FAILURE
Nov 04 14:41:22 VM-0-14-debian systemd[1]: caddy.service: Failed with result 'exit-code'.
Nov 04 14:41:22 VM-0-14-debian systemd[1]: Failed to start Caddy.

**Comment by 233boy** [comment]
@etsb5z 
把 /etc/caddy/Caddyfile 文件 第二行最后的 / 删除掉

**Comment by qinlgumt** [comment]
caddy.service - Caddy
     Loaded: loaded (/lib/systemd/system/caddy.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2022-11-18 15:18:44 CST; 1min 34s ago
       Docs: https://caddyserver.com/docs/
    Process: 4556 ExecStart=/usr/local/bin/caddy run --environ --config /etc/caddy/Caddyfile (code=exited, status=1/FAILURE)
   Main PID: 4556 (code=exited, status=1/FAILURE)
     Status: "loading new config: http app module: start: listening on :80: listen tcp :80: bind: address already in use"

Nov 18 15:18:44 fine-delight-1.localdomain caddy[4556]: {"level":"info","ts":1668755924.0269918,"logger":"http","msg":"server is listening only o>
Nov 18 15:18:44 fine-delight-1.localdomain caddy[4556]: {"level":"info","ts":1668755924.0270157,"logger":"http","msg":"enabling automatic HTTP->H>
Nov 18 15:18:44 fine-delight-1.localdomain caddy[4556]: {"level":"info","ts":1668755924.0273216,"logger":"tls.cache.maintenance","msg":"started b>
Nov 18 15:18:44 fine-delight-1.localdomain caddy[4556]: {"level":"info","ts":1668755924.0276725,"logger":"tls","msg":"cleaning storage unit","des>
Nov 18 15:18:44 fine-delight-1.localdomain caddy[4556]: {"level":"info","ts":1668755924.0278287,"logger":"tls","msg":"finished cleaning storage u>
Nov 18 15:18:44 fine-delight-1.localdomain caddy[4556]: {"level":"info","ts":1668755924.028033,"logger":"tls.cache.maintenance","msg":"stopped ba>
Nov 18 15:18:44 fine-delight-1.localdomain caddy[4556]: Error: loading initial config: loading new config: http app module: start: listening on :>
Nov 18 15:18:44 fine-delight-1.localdomain systemd[1]: caddy.service: Main process exited, code=exited, status=1/FAILURE
Nov 18 15:18:44 fine-delight-1.localdomain systemd[1]: caddy.service: Failed with result 'exit-code'.
Nov 18 15:18:44 fine-delight-1.localdomain systemd[1]: Failed to start Caddy.

@233boy 这啥情况，也开不了caddy了

**Comment by 233boy** [comment]
@qinlgumt 
>"loading new config: http app module: start: listening on :80: listen tcp :80: bind: address already in use"

端口被占用了；使用 `ss -tunlp | grep :80` 看看是什么程序占用的吧

**Comment by qinlgumt** [comment]
> @qinlgumt
> 
> > "loading new config: http app module: start: listening on :80: listen tcp :80: bind: address already in use"
> 
> 端口被占用了；使用 `ss -tunlp | grep :80` 看看是什么程序占用的吧

Nginx占用了...
