### ISSUE TITLE
总是监听ipv6怎么解决

### ISSUE THREAD

**Issue by suyan599** [233boy/v2ray#987]
一直显示解析错误，用了旧版本也还是一样的

**Comment by 233boy** [comment]
@suyan599 你什么VPS

**Comment by suyan599** [comment]
hostwinds的

**Comment by suyan599** [comment]
昨天还正常，今天就异常了

**Comment by 233boy** [comment]
@suyan599 
那这就很奇怪了，莫名其妙的。

**Comment by suyan599** [comment]
我把DNS解析到cf了，云朵也是灰色的，不知道啥情况了

**Comment by 233boy** [comment]
@suyan599 你在主机上 PING 一下你的域名看看

**Comment by suyan599** [comment]
ping 出来是正确的ipv4的

**Comment by suyan599** [comment]
监听出来的ipv6的地址也不是我vps的ipv6的地址啊。。。

**Comment by 233boy** [comment]
@suyan599 
你是不是 IP 被封了 443 端口；你到 itdog.cn 去测试一下自己的 IP

**Comment by suyan599** [comment]
查了，443端口被封了。。

**Comment by lijietk** [comment]
一样的问题  我用的vutlr   创建vps的时候关掉ipv6就可以了
![image](https://user-images.githubusercontent.com/117452490/199973356-f0a4d5bc-167b-4f23-8d8c-e5a34b271e6b.png)

**Comment by lijietk** [comment]
![image](https://user-images.githubusercontent.com/117452490/199974727-26978530-34a5-490c-9af7-f69b67c3beb6.png)
如果不关掉的话 搭建出来的地址就是ipv6的地址

**Comment by suyan599** [comment]
可以了，感谢大佬

**Comment by suyan599** [comment]
> ![image](https://user-images.githubusercontent.com/117452490/199974727-26978530-34a5-490c-9af7-f69b67c3beb6.png) 如果不关掉的话 搭建出来的地址就是ipv6的地址

可以了，感谢大佬

**Comment by xieruiyin** [comment]
@suyan599  请问你解决 443 端口被封的问题了么

**Comment by suyan599** [comment]
我换了个IP

**Comment by suyan599** [comment]
> @suyan599 请问你解决 443 端口被封的问题了么

我换了个IP
