### ISSUE TITLE
请求支援:用了旧版本，还是连接不上

### ISSUE THREAD

**Issue by JduenznnxjSj** [233boy/v2ray#988]
最开始是程序未运行，爬楼看了别人的帖子我也下了旧版本，但还是连接不上。。我萌新，xshell连接后就直接bash <(curl -sL https://git.io/v2ray.sh) online old安装v2ray了。。所以是我遗漏了什么没做吗？
Ps: 我的v2ray配置那ip地址显示是乱码
       因为Windows程序一直打不开，所以我用的手机连接
Vps是Vultr centOS7，没有防火墙
       弄了一夜我心力交瘁，明天起来再发一下日志嗷
希望大神能给我一个帮助，感谢！

**Comment by xieruiyin** [comment]
一样的，有大佬知道怎么解决码

**Comment by xieruiyin** [comment]
好的，感谢大佬白忙之间抽时间回复我们

**Comment by xieruiyin** [comment]
大佬，我换了系统之后还是不行，报了下面的错误
failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [dial tcp 144.202.88.173:21676: i/o timeout] > common/retry: all retry attempts failed
2022/11/04 11:03:42 [Warning] [1986970638] proxy/http: failed to read response from www.goole.com > io: read/write on closed pipe
2022/11/04 11:03:42 [Warning] [1986970638] app/proxyman/inbound: connection ends > proxy/http: connection ends > proxy/http: failed to write response > write tcp 127.0.0.1:1081->127.0.0.1:52605: wsasend: An established connection was aborted by the software in your host machine.
2022/11/04 11:03:44 127.0.0.1:52837 accepted //optimizationguide-pa.googleapis.com:443 [proxy]
2022/11/04 11:03:49 [Warning] [2919480941] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [dial tcp 144.202.88.173:21676: i/o timeout] > common/retry: all retry attempts failed
2022/11/04 11:03:49 [Warning] [2919480941] proxy/http: failed to read response from www.goole.com > io: read/write on closed pipe
2022/11/04 11:03:56 127.0.0.1:52870 accepted //content-autofill.googleapis.com:443 [proxy]
2022/11/04 11:04:06 [Warning] [230352182] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [dial tcp 144.202.88.173:21676: i/o timeout dial tcp 144.202.88.173:21676: operation was canceled] > common/retry: all retry attempts failed

**Comment by 233boy** [comment]
@xieruiyin 
你到 itdog.cn PING 一下你的 IP；这好像是 你的 IP 有问题；

**Comment by xieruiyin** [comment]
大佬，你好，是没有问题的
![image](https://user-images.githubusercontent.com/20101054/199877965-aedc55a0-16f8-4431-be21-5cff5c879712.png)

**Comment by xieruiyin** [comment]
tcping 变成这样了，请问是什么原理，大佬
![image](https://user-images.githubusercontent.com/20101054/199878423-624482b6-b07d-440b-8ef0-020463b46792.png)

**Comment by xieruiyin** [comment]
大佬，是可以ping同的，但是tcping 就不行了，请问有什么办法可以突破

**Comment by JduenznnxjSj** [comment]
> @xieruiyin @JduenznnxjSj vultr 换个 Ubuntu 系统 再来看看。。。

还是不行呢？

**Comment by xieruiyin** [comment]
是的，我就是换的Ubuntu 系统

**Comment by JduenznnxjSj** [comment]
@233boy 有空了可以教教吗？不会弄了

**Comment by 233boy** [comment]
> 大佬，是可以ping同的，但是tcping 就不行了，请问有什么办法可以突破

@xieruiyin 端口不通；换端口看看；

**Comment by 233boy** [comment]
> 到 itdog.cn PING 一下你的 IP

到 itdog.cn PING 一下你的 IP；PING，和 tcping 都测试一下

**Comment by JduenznnxjSj** [comment]
@233boy Ping了，跟上面两张图一样。换哪个端口？

**Comment by 233boy** [comment]
@JduenznnxjSj 
使用 `v2ray ss` 创建一个 SS 看看能不能用，如果能用，那就 V2 换 端口，WS +TLS 用不了的话，可能是 443 端口被封了。

**Comment by JduenznnxjSj** [comment]
@233boy ss也连不上

**Comment by xieruiyin** [comment]
大佬，是443 端口被封了，请问要怎么解决

**Comment by JduenznnxjSj** [comment]
Socket error Event: 32 Error: 10053.
Connection closing...Socket close.

Connection closed by foreign host.

Disconnected from remote host(新建会话) at 15:11:21.

Type `help' to learn how to use Xshell prompt.
[C:\~]$ 

VPS会莫名断开呢，是不是因为这个原因

**Comment by JduenznnxjSj** [comment]
刚才看了，我也是443端口被封

**Comment by JduenznnxjSj** [comment]
WARNING! The remote SSH server rejected X11 forwarding request

**Comment by JduenznnxjSj** [comment]
WARNING! The remote SSH server rejected X11 forwarding request

**Comment by JduenznnxjSj** [comment]
@233boy 大佬下午了，开始摸鱼，看看咋弄，是vps的问题吗

**Comment by douwxin** [comment]
大佬 也是无法链接 更换端口也没用

**Comment by JduenznnxjSj** [comment]
@233boy 艾特大佬出一期443端口被封的解决方案✔

**Comment by douwxin** [comment]
@233boy 艾特大佬出一期443端口被封的解决方案✔

**Comment by 233boy** [comment]
@xieruiyin @JduenznnxjSj @douwxin 
套CF 就行了；只是可能速度会很慢

**Comment by xieruiyin** [comment]
很慢啊，那看视频会卡吗

**Comment by douwxin** [comment]
> 

大佬不会搞呀

**Comment by xieruiyin** [comment]
@douwxin  别做伸手党啊，可以自己研究啊，大佬又不收费，没有义务帮你们搞啊，可以试试这个方法，我也不知道行不行https://www.freenom.com/zh/index.html?lang=zh

**Comment by JduenznnxjSj** [comment]
@233boy 可以给个学习地址吗，昨晚查了一宿实在没找到

**Comment by xieruiyin** [comment]
![image](https://user-images.githubusercontent.com/20101054/200112815-6c0ecc75-5e62-4d22-b8d9-a6c7f2040d29.png)
@JduenznnxjSj  我请问一个服务器大佬的回答，你可以试试

**Comment by xieruiyin** [comment]
设置下安全组和防火墙，开放443 应该就可以了

**Comment by JduenznnxjSj** [comment]
@xieruiyin 在哪里开呢？我正在查套cf的资料，freenom注册不了域名。。。。

**Comment by JduenznnxjSj** [comment]
Iptatles的安装代码是什么，我安装试试

**Comment by xieruiyin** [comment]
我最近在赶需求还没时间搞列，你百度下试试，我明天休息抽个时间也试试吧

**Comment by xieruiyin** [comment]
我已经一个多星期没翻出去了，难受的很

**Comment by JduenznnxjSj** [comment]
我刚开始入门，很多都不懂，已经五天六夜了，基本没怎么睡觉

**Comment by xieruiyin** [comment]
悠着点，身体要紧，你先好好休息把，或者实在想上外网可以花钱买一个先暂时用着

**Comment by JduenznnxjSj** [comment]
我现在用机场翻的，就是学着弄v2ray自己搭个节点。。。花钱学习也可以，新手太难了，就是不知道谁教……

**Comment by JduenznnxjSj** [comment]
我现在用机场翻的，就是学着弄v2ray自己搭个节点。。。花钱学习也可以，新手太难了，就是不知道谁教……

**Comment by douwxin** [comment]
> 星期没翻出去了，难受的很

大佬我是小白呀 在学

**Comment by 233boy** [comment]
@JduenznnxjSj @douwxin 
套 CF是指的是；cloudflare 中转 v2ray 流量
我之前写过教程，但是已经过时了，等过些时间重建博客我再写一些教程吧。

**Comment by JduenznnxjSj** [comment]
@233boy 好的大佬，我可以加一个你的联系方式吗

**Comment by JduenznnxjSj** [comment]
网上的资料搜到很多都是老版本的，有一些内容花费一两个小时摸索之后才发现没用了……

**Comment by 233boy** [comment]
@JduenznnxjSj 
先不要折腾了；反正现在这段时间也难搞，过些日子再说吧

**Comment by douwxin** [comment]
> cloudflare 中转 v2ray 流量

感谢大佬

**Comment by lijietk** [comment]
先安装一下新版本 bash <(curl -s -L https://raw.githubusercontent.com/xyz690/v2ray/master/install.sh)
再重装一下旧版本v2ray reinstall
我的就是这样好的  不知道为什么要先安装一下新版本 直接安装旧版也不行

**Comment by lijietk** [comment]
> @lijietk 你这用的是别人修改我的东西。。。。。。。

那大佬现在能直接用的是那个  那个我也是在网上找的

**Comment by lijietk** [comment]
bash <(curl -sL https://git.io/v2ray.sh) online old 
我直接用安装这个旧版本也没用

**Comment by ZCDW-HTHY** [comment]
3台服务器因为重装崩了3台，剩下1台好的再也不敢碰了。大佬啥时候能修复呀？

**Comment by ZCDW-HTHY** [comment]
github上有人说是5.1核心的通病【https://github.com/v2fly/v2ray-core/issues/1950】，但我试过了没办法恢复。
如果用大佬你那个原版的，很多敏感图片都会被GFW过滤掉，有些网址也没法访问。
