### ISSUE TITLE
V2rayN V5.36客户端连接一直提示Warning

### ISSUE THREAD

**Issue by Eiffee** [233boy/v2ray#989]
搬瓦工，香港主机，Centos 7 x86_64 bbr系统，安装的老版本v2ray，配置的WebSocket + TLS

2022/11/05 02:31:21 [Warning] [3892377563] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to

**Comment by 233boy** [comment]
@Eiffee 
到 itdog.cn ping 一下，以及 tcping；看看是不是端口被封了

**Comment by Eiffee** [comment]
> @Eiffee 到 itdog.cn ping 一下，以及 tcping；看看是不是端口被封了

ping了，IP正常，80，443端口都正常能通，现在就是PC使用v2rayN，一直出现那个Warning，然后速度很慢，要不就是掉线，苹果手机用小火箭，就完全不行了，连接都是超时，找不出问题在哪里，VPS主机系统重装了好几遍，v2ray+caddy也都跑起来运行了，就还是这样子，求大神指教！

**Comment by crazypeace** [comment]
从你使用的网络环境往VPS 检测一下数据通路上哪里有问题。
https://zelikk.blogspot.com/2022/04/setup-v2ray-websocket-tls-troubleshoot.html
https://zelikk.blogspot.com/2022/04/connect-v2ray-websocket-tls-troubleshoot.html
