### ISSUE TITLE
大佬不会搞呀

### ISSUE THREAD

**Issue by douwxin** [233boy/v2ray#990]
@xieruiyin @JduenznnxjSj @douwxin 
套CF 就行了；只是可能速度会很慢

_Originally posted by @233boy in https://github.com/233boy/v2ray/issues/988#issuecomment-1304382782_

**Comment by crazypeace** [comment]
手把手的教程：
https://zelikk.blogspot.com/2021/11/racknerd-vps-v2ray-1g-1t-12g-768mb-1088.html

跳过买 VPS 的部分。
