### ISSUE TITLE
脚本是有问题吗

### ISSUE THREAD

**Issue by huangsir1** [233boy/v2ray#992]
<img width="538" alt="image" src="https://user-images.githubusercontent.com/19603136/200171807-528ef175-3f10-471d-9a82-19833cb238ed.png">

sudo bash < <(curl -s -L https://git.io/v2ray.sh)

这个脚本为啥输入就疯狂输出

**Comment by 233boy** [comment]
这个才对

`bash <(curl -s -L https://git.io/v2ray.sh)`
