### ISSUE TITLE
请问大佬在哪里关掉IPV6，我是hostwinds的

### ISSUE THREAD

**Issue by yyf202211** [233boy/v2ray#996]
> ![image](https://user-images.githubusercontent.com/117452490/199974727-26978530-34a5-490c-9af7-f69b67c3beb6.png) 如果不关掉的话 搭建出来的地址就是ipv6的地址

可以了，感谢大佬

_Originally posted by @suyan599 in https://github.com/233boy/v2ray/issues/987#issuecomment-1303754482_

**Comment by 233boy** [comment]
@yyf202211 
使用 `v2ray update.sh` 更新一下脚本就行了；
