### ISSUE TITLE
twitter访问失败

### ISSUE THREAD

**Issue by lianzhidong** [233boy/v2ray#997]
在远端能够ping通twitter，
在本地却ping不通
请问大佬是什么问题啊

**Comment by Nicolas-Gong** [comment]
ping 基本不被代理吧。。。你应该用curl -v之类的来看返回的结果。。。

**Comment by crazypeace** [comment]
你要利用本地的v2ray生成的socks代理去访问twitter
光ping就是裸连，并没有代理。

还有一种方法是用TUN模式的翻墙客户端，那相当于模拟了一个网卡。
