### ISSUE TITLE
请教一下，搭好后刚开始可以用，几分钟后就用不了了，什么原因，防火墙是关了的

### ISSUE THREAD

**Issue by hcss-ptebhy** [233boy/v2ray#998]
请教一下，搭好后刚开始可以用，几分钟后就用不了了，什么原因

**Comment by crazypeace** [comment]
开CDN 试试

**Comment by xieruiyin** [comment]
@crazypeace 请问cdn 怎么开

**Comment by MrLiu-647** [comment]
可能是端口冲突了，建议找个 1w 以上的端口试试

**Comment by crazypeace** [comment]
@xieruiyin 看教程: https://zelikk.blogspot.com/2021/11/racknerd-vps-v2ray-1g-1t-12g-768mb-1088.html 后面的部分
