### ISSUE TITLE
国内PING通TCP通但v2rayN无法翻墙

### ISSUE THREAD

**Issue by WebofLaw** [233boy/v2ray#999]
debian系统，新脚本和旧脚本都试过。已经在服务器上设置好了防火墙，使用TCP端口。一切都通了但是用v2rayN却无法翻墙

**Comment by ivanfeixue** [comment]
我也是，前几天突然不能用了，重装都不行

**Comment by WebofLaw** [comment]
有可能是v2rayN的问题，重新装了v2rayN，手动用最新的V2ray替换，就好了

**Comment by zhychen1173** [comment]
我也是，自建的3个节点突然都连不上了，vmess+tls+ws，ip并没有被封，估计墙升级了

**Comment by xieruiyin** [comment]
请问你们有好的方法翻墙吗

**Comment by JialingRichard** [comment]
有更好地方案吗，有的话踢我一脚~
